### ISSUE TITLE
VimwikiToggleListItem stopped working after vim-7.4.527

### ISSUE THREAD

**Issue by rsommer** [vimwiki/vimwiki#100]
Hi,

i'm using vimwiki on gentoo and after vim-7.4.527 i can no longer toggle list items, wether i'm using the shortcut (<C-space>) nor by entering :VimwikiToggleListItem. I tried with 7.4.542 and 7.4.560.

Until 7.4.527 ToggleListItem gets the correct line1/line2 i'm on as parameter, using vim-7.4.542 or later the function is always called with (1,1) as line1 and line2.

Hope that helps for further investigation.

**Comment by EinfachToll** [comment]
It's a bug in Vim, likely the same issue as #96, but it seems like it's not fixed yet. Two options:
1. wait for it to be fixed
2. break it down to a minimal example without Vimwiki being involved and post the issue to the vim_dev mailing list

**Comment by EinfachToll** [comment]
Is it fixed now? I tried it with 7.4.567 and everything seems to work.

**Comment by chmeee** [comment]
@EinfachToll It works again for me in that version of vim (7.4.567)

**Comment by EinfachToll** [comment]
Ok. If the bug persists, feel free to reopen.
