### ISSUE TITLE
How do I express a literal asterisk (or other special character)?

### ISSUE THREAD

**Issue by waxlamp** [vimwiki/vimwiki#1003]
Title says it all: I'm not sure how to escape special characters in my vimwiki text. In particular, I have a note where I want to use an asterisk to refer to a "footnote" at the bottom of the note.

I realize there is probably a better way to express a footnote, but that would still leave the question of how to put, e.g., a literal asterisk in the text for any other (valid) reason.

Thanks!

**Comment by tinmarino** [comment]
__Short answer:__ `&#42;` or put it in code block
```
`*`
```


__Long bad solution:__ The asterix is very important in   markdown syntax. It is a token, so you cannot use it safely:

* if the first character of a line => otherwise a list begin
* If preceding a non space => Starts italic (if one) or bold (if two)
* If following a non space => Ends ....

So you may * have * to * put it alone * but this is .... not recommended ****

If you have other question of this kind: vimwiki collaborators (Ranebrown) whoed me: the [github spec](https://github.github.com/gfm/) pretty page implemented [here](https://github.com/commonmark/commonmark-spec/). See that they embeded every * in code `*`

**Comment by tinmarino** [comment]
So you want somthing like this

```markdown
&#42; desc 1  
&#42; desc 2  
&#42; desc 3  
```

Note the trailing two space (selecting the previous text) important for newlines
which converts to:

```html
<p>* desc 1<br />
* desc 2<br />
* desc 3</p>
```

**Comment by uolot** [comment]
In Github Flavoured Markdown you can add a backslash in front of the asterisk:

* using `*`

\* using `\*`

**Comment by tinmarino** [comment]
Thanks @uolot I did not even know [there](https://github.github.com/gfm/#backslash-escapes) is the backslash spec.

So this is on the TODO list for vimwiki (markdown) syntax highlighting.
It should be fast

**Comment by tinmarino** [comment]
@uolot, @waxlamp  do you want this one ? There is one line to modify here:

https://github.com/vimwiki/vimwiki/blob/a7f34cd8cfd7e3ab8f1ef3824f5d1233e92f91c6/autoload/vimwiki/u.vim#L318-L340

to ignroe `\*` or generaly `\token` in th typeface region and here:

https://github.com/vimwiki/vimwiki/blob/a7f34cd8cfd7e3ab8f1ef3824f5d1233e92f91c6/autoload/vimwiki/u.vim#L301-L315

Estimated time: 1h, 2h with the test but I can do the tests. What do you think ?

**Comment by waxlamp** [comment]
Hi @tinmarino. I would gladly take this on, but unfortunately I have almost no knowledge of vimscript :confused: 

If you can point me to some extra background information about how these two code snippets can ignore escaped characters, I can try to make it work, but it may be better for someone else to tackle.

Let me know. Thanks!

**Comment by tinmarino** [comment]
> If you can point me to some extra background information about how these two code snippets can ignore escaped characters

`:h syn-region` -> skip parameter and a nice example

```vim
:syntax region String   start=+"+  skip=+\\"+  end=+"+
```

You can grep `vimwiki#u#hi_tag` to see who is calling it and to add a `\\\*` pattern to skip for bold. And you got it.

---
> It may be better for someone else to tackle

You can always find someone better than yourself, that should not be a reason for not trying.
But if you don't like it, this is the best reason you can have. In like the diversity of languages but understand that most people prefer sticking to their python contort zone.
If you are diving into vimscript: my favorite help page: `:h function-list`

**Comment by waxlamp** [comment]
@tinmarino, I appreciate your words of encouragement. I dived into the code a bit, but did not make much progress. Here's what I was able to figure out:
1. In `u#hi_tag` I can easily place a clause that adds `'\\' . a:post_tag` to the skip list; this would prevent an escaped delimiter from prematurely ending the syntax region.
2. `u#hi_expand_regex` seems to be for limiting when a delimiter group gets picked up as actually starting/ending a region. For example, in `thisisregular*thisisregulartoo`, a bold region will not begin at the `*`. However, I am not sure why.
3. I tried to use `[^\\]\@<!` to prevent matching a delimiter when it is preceded by a `\`, but it does not seem to be working. I am also not entirely certain where this matcher would need to actually go.
4. I am also not sure how those escaping backslashes would be processed by the HTML renderer.

Let me know if you have any further insights.

**Comment by tinmarino** [comment]
> 2 u#hi_expand_regex seems to be for limiting when a delimiter group gets picked up as actually starting/ending a region. For example, in thisisregular*thisisregulartoo, a bold region will not begin at the *. However, I am not sure why.

Becaus it is in the markdown spec, the typeface delimiter must not be surrounded y words characters

> 3 I tried to use [^\\]\@<! to prevent matching a delimiter when it is preceded by a \, but it does not seem to be working. I am also not entirely certain where this matcher would need to actually go.

Those are region so you must use the skip keyword also (I guess that is why). But try or paste here your full regex

> 4 I am also not sure how those escaping backslashes would be processed by the HTML renderer.

They must be skipped by the typeface parser and finally replaced by their unescaped version.

All that would be a great help.
Total time: 4h

**Comment by tinmarino** [comment]
Related: #783
