### ISSUE TITLE
Changing color of concealed latex scripts in vimwiki markdown?

### ISSUE THREAD

**Issue by zamlz** [vimwiki/vimwiki#1004]
I can't seem to find any information on how to change the color of these latex scripts once they are concealed by vimwiki. Notice how the summation and other characters are too dark to reliably see on the screen. How can i change that?

![2020-09-02-091710_295x82_scrot](https://user-images.githubusercontent.com/10750027/92010001-1f590f00-ecfe-11ea-9888-14956905d7d3.png)

Here is what it looks like while I'm editing the line.

![2020-09-02-092441_453x64_scrot](https://user-images.githubusercontent.com/10750027/92010145-49123600-ecfe-11ea-82b1-c8312c74340b.png)

**Comment by tinmarino** [comment]
`:hi Conceal ctermfg=red`

**Comment by zamlz** [comment]
Great it seems to work but why doesn't this affect other concealed elements
in markdown like bold/italic text or urls?

**Comment by tinmarino** [comment]
>  I'm guessing something might be unsetting it?

Good intuition: use the `verbose` command to inspect where were the variable set: `:verbose hi Conceal`

> why doesn't this affect other concealed elements in markdown like bold/italic text or urls?

Unfortunately, here you are wrong: there is only one Conceal hi color (which I reaaly dont like). So it does affect the other conceal colors. But the conceal color is the replacement text. In case of bold: `__this__` is concealing  `__` with am empty conceal text replacement and higlight `this` as bold and conceal `__`  so you cannot tell the conceal color of an empty region

**Comment by tinmarino** [comment]
You can try somehting like this:
```vim
:syn match MyConceal /aa/ conceal cchar=B
```
And see that the B is color.

Vimwiki command for typeface is a bit more complex: regions and conceal_end (to conceal the `__` extremities). We mutualise this verbosity in a function

https://github.com/vimwiki/vimwiki/blob/dbbadc8035a3fb3e3b51e8d646fde32fa0aa1ebb/autoload/vimwiki/u.vim#L324-L340
