### ISSUE TITLE
Markdown reference-style links not refreshing

### ISSUE THREAD

**Issue by patdavid** [vimwiki/vimwiki#1005]
Howdy!

I'm using markdown as my syntax.
`VimwikiShowVersion` = `Stable Version 2.5`

vimwiki settings:
```
let wiki_1 = {}
let wiki_1.path = '~/Nextcloud/vimwiki/' 
let wiki_1.path_html = '~/Nextcloud/vimwiki/export/html/'
let wiki_1.syntax = 'markdown' 
let wiki_1.ext = '.md'
"let wiki_1.vimwiki_markdown_link_ext = 1
let wiki_1.auto_diary_index = 1
let wiki_1.auto_toc = 1
let wiki_1.auto_tags = 1

let g:vimwiki_list = [wiki_1, wiki_2]
let g:vimwiki_markdown_link_ext=1
let g:vimwiki_global_ext=0
```

It appears that using a reference-style markdown link doesn't work immediately (so <CR> on a link tries to open the [Id] as a wiki page:

```
[Test][]
[second test][2]

[Test]: https://patdavid.net
[2]: https://www.gimp.org
```

Entering the markdown link and pressing `<CR>` _should_ open the link in my browser, but instead it opens a new wiki page `Test.md` or `2.md`.
The help seems to indicate:
> To scan the page for new or changed definitions for reference-links, simply
re-open the page ":e<CR>".

But this doesn't seem to help (at least in Vim/GVim 8.2 on win10).
*Note:* Closing down Vim and re-opening the file _does_ seem to refresh the link so that it works.

- [ ] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [X] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [X] Include the output of `:VimwikiShowVersion`.

**Comment by tinmarino** [comment]
Dyhow!

Sorry, [reference style link](https://github.github.com/gfm/#link-reference-definitions) have not been implemented already. Meanwhile, you must use weblinks:

```markdown
[Test](https://patdavid.net)
```

With the conceal support, it is not so ugly: the destination url gets hidden

**Comment by tinmarino** [comment]
I think it is because you added the link at this current section and it is not reparsed. you can debug

`breakadd func :breakadd  func vimwiki#markdown_base#open_refli
nk`

and `echo b:vimwiki_markdown_ref` after pressing enter.

Some `setf vimwiki` may help, not sure.

**Comment by patdavid** [comment]
I _really_ appreciate the help, but I am not sure where or how to use those commands to help debug.

I can use weblinks if needed at the moment, but would really love to get full markdown support working.

I'll can start familiarizing myself with the environment.

**Comment by patdavid** [comment]
Grr.  Re-opening the file in a fresh vim instance and the links are parsed correctly (and opened).  Now, how to trigger that behavior manually...

**Comment by tinmarino** [comment]
`call vimwiki#markdown_base#scan_reflinks() `

**Comment by tinmarino** [comment]
`setf vimwiki_markdown_custom` may help, this is not documented at all. How to use it @ranebrown

**Comment by tinmarino** [comment]
https://github.com/vimwiki/vimwiki/blob/dbbadc8035a3fb3e3b51e8d646fde32fa0aa1ebb/autoload/vimwiki/base.vim#L1634-L1639

**Comment by patdavid** [comment]
> 
> 
> `call vimwiki#markdown_base#scan_reflinks() `

There's the magic sauce right there!  Thank you for this!

**Comment by 1bildung** [comment]
Thanks, great!

**Comment by erig0** [comment]
> `call vimwiki#markdown_base#scan_reflinks() `

Thanks! I used the following autocmd to make this automatic.

```vimscript
" Update reference links after write
autocmd FileType vimwiki autocmd BufWritePost <buffer> silent call vimwiki#markdown_base#scan_reflinks()
```
