### ISSUE TITLE
Wiki Links not collapsing properly

### ISSUE THREAD

**Issue by antaxiom** [vimwiki/vimwiki#1006]
Prior to submitting a new issue make sure to complete these steps:

- [ ] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet

I'm not clear on how to install the dev branch using plug if anyone could tell me that would be of great help

- [X] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`

I'm using the default syntax and my settings are:

```  let g:vimwiki_key_mappings =
    \ {
    \   'all_maps': 1,
    \   'global': 1,
    \   'headers': 1,
    \   'text_objs': 1,
    \   'table_format': 1,
    \   'table_mappings': 1,
    \   'lists': 1,
    \   'links': 1,
    \   'html': 1,
    \   'mouse': 1,
    \ }

let g:vimwiki_list = [{'path': '~/Documents/notes/vimwiki/',
\ 'syntax': 'default', 'exclude_files': ['**/README.md', '**/Readme.md'] }]

let g:vimwiki_diary_months = {
      \ 1: 'January', 2: 'February', 3: 'March',
      \ 4: 'April', 5: 'May', 6: 'June',
      \ 7: 'July', 8: 'August', 9: 'September',
      \ 10: 'October', 11: 'November', 12: 'December'
      \ }
```

- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.

I can use vimwiki but Wiki links do not collapse (eg. turning [[This]] into **This**) but markdown links (eg. [Link to video](www.video.link) into **Link to video**) do collapse. I am using the default vimwiki syntax so none of this makes sense. I would also like to note [Brodie Robertson's Video](https://www.youtube.com/watch?v=vBJj7YMVn6I) shows a lack of syntax highlighting but does show links properly collapsing

- [X] Include the output of `:VimwikiShowVersion`.
Stable Version: 2.5

**Comment by tinmarino** [comment]
> I'm not clear on how to install the dev branch using plug if anyone could tell me that would be of great help

got to the path where vimwiki is installed: `.vim/pack/opt/bundle/vimviki`

```bash
git status  # Ensure you are in the good git repo
git fetch --all  # Get all branches
git checkout dev
``` 

I have no idea why this is happening, it should be some config in your side: Try to remove use a minial vimrc with `vim -U` to find the responsible configuration line.

**Comment by antaxiom** [comment]
I totally forgot to mention I am using neovim but it seems the process is the same just in config ~/.config/nvim, also but what config do I give to -U?

**Comment by tinmarino** [comment]
> that config do I give to -U?

A full reproductive example with a custom vimrc and test.md you especially to be loaded with `vim -U vimrc -N test.md` so that I can reproduce the error here. Doing that may take you 30 min but in the process, it is very likely that you find the bug.

**Comment by antaxiom** [comment]
I didn't understand what you needed very well but I assume you want my full config, It's very messy but it's on my [dotfiles repo](https://github.com/antaxiom/dotfiles). I'll try using the default config and figuring out what's going on.

**Comment by antaxiom** [comment]
I just wanted to put one more additional note that I just realized, all markdown files say their file type is vimwiki, which I find to be very strange

**Comment by dk949** [comment]
Hi. Having the same issue with vanilla Vimwiki settings and the default syntax. Also using neovim with a clean init.vim (apart from loading the plugin with vundle).
I checked the dev branch and the issue persists there. 
It seems only links in tables refuse to collapse. This is really strange as they used to do it without any issues before.
One time restarting vim helped but now it's just stuck this way.

Thank you for looking into this.

**Comment by antaxiom** [comment]
@dk949 Good to see someone with the same problem as me, I didn't have the time to fix this nor did I make heavy use of vim wiki so I've left this as is. I home the devs take a note and look into this a bit more.

**Comment by tinmarino** [comment]
Closing <= seems to affect only former master branch
