### ISSUE TITLE
New Markdown headers are not foldable

### ISSUE THREAD

**Issue by ryanisaacg** [vimwiki/vimwiki#1010]
Syntax: markdown
Version: `Stable version: 2.5`
Config:
```vim
let g:vimwiki_list = [{ 'path': '~/vimwiki', 'syntax': 'markdown', 'ext': '.txt' }]
hi VimwikiLink cterm=underline ctermfg=DarkBlue
let g:vimwiki_folding = 'expr'
```
Reproduce:
1. Open a Vimwiki file with some headers, in Markdown syntax
2. Unfold all headers with `zR`
3. Create a new header
4. Attempt to fold it, and the previous header will fold instead
5. Reload the buffer, and the new header works fine

**Comment by tinmarino** [comment]
__What:__ The foldmethod is very easy and robust: https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/ftplugin/vimwiki.vim#L142-L156

__Why:__ You can see the discussion in [this vim forum](http://vim.1045645.n5.nabble.com/Why-is-there-no-foldupdate-td1194649.html).

The solution is given in [this stackoverflow](https://stackoverflow.com/a/29579160/2544873) (or `:h zx` which you could not guess)

__How (Solution):__ So you can `nnoremap zR zxzR` as long as your file is not too long (less than 2000 lines)

Thank you to feed us with a reproducible issue (Helpfull for dev and future users) 

__Keywords:__ __Fold__, __Update__, __Refresh__, __Synchronyse__, __Not working__ (lol)

**Comment by tinmarino** [comment]
You can also have a look at `$VIMRUNTIME/ftplugin/markdown.vim` which defines `function! MarkdownFold() abort` looking almost the same  (and from Tim Pope, which is a good sign)

**Comment by ryanisaacg** [comment]
Thanks for the tip! It does seem like this is the best it gets for Markdown folding. I'll close this, because it doesn't seem to be anything vimwiki can fix?

**Comment by tinmarino** [comment]
Sure better to close it. It could be "fixed" in Vim or Vimwiki but both do not want: we prefer lazy parsing just when necessary.

In both case, this could be done at InsertLeave, to see if the line change. Easy in theory but it is dangerousm can freeze for Vim scope and for the Vimwiki scope, we prefer letting the user map is fold or press `zx` when He feels something has changed.

So this could be improved but much work and performance lost for very poor adition => Sent to user scope
