### ISSUE TITLE
Vimwiki under W10, OneDrive - link fail

### ISSUE THREAD

**Issue by DannyQuah** [vimwiki/vimwiki#1014]
![1-not-activating](https://user-images.githubusercontent.com/6435951/92534856-757f0280-f268-11ea-93b6-32ecfa075d66.png)
![2-open-Command-Window](https://user-images.githubusercontent.com/6435951/92534860-76b02f80-f268-11ea-9fd2-8233919ab399.png)

Vimwiki links fail for me when the wiki file is placed in OneDrive under W10. I can't figure out how to fix this but netminds here might well already know. More detailed description follows.

When the sample `index.md` (below) is placed outside of OneDrive (anywhere else in my C:\Users\sppme\) everything works as expected, and exactly as on my Ubuntu systems. 

1. However, when `index.md` is in `myWikiTrial` under OneDrive (referring to my `.vimrc` snippet below),  the vimwiki-style link Note activates, i.e., displays itself as an active link, while the markdown link Test keeps its as-coded form and fails to activate. Notice this is even with `myWikiTrial.syntax` set to 'markdown'. 
2. Doing Enter on the Note link fails to create or open `Note.md` in vimwiki, but instead only pops open a new Windows Command window. Note there are no forward or backslashes in the filename.  

My .vimrc snippet below includes `myWikiWork` to check that everything works fine there. The issue is not a Windows one alone, but some interaction between Windows and OneDrive. (So I don't think this is the same issue as https://github.com/vimwiki/vimwiki/pull/1011) 

Nothing changes in my description of outcomes no matter how the wikis are ordered in `vimwiki_list`. 

Items 1. and 2. are not, in my understanding, part of vimwiki expected behaviour, and are certainly not observed on my Ubuntu machines. Thank you  in advance for any suggestions.

(I have tried this on the dev branch as well; again :VimwikiShowVersion gives Stable version 2.5.)

```
--- index.md --- 
[[Note.md|Note]]
[Test](Test.md) 
--- end
```
I put this same index.md under both `myWikiWork` and `myWikiTrial` to test.

```
--- the relevant part of my .vimrc --- 
let myWikiWork = {} 
let myWikiWork.path = '~/0/VimWiki/'
let myWikiWork.syntax = 'markdown' 
let myWikiWork.ext = '.md'

let myWikiTrial = {}
let myWikiTrial.path = '~/OneDrive/'
let myWikiTrial.syntax = 'markdown' 
let myWikiTrial.ext = '.md'

let g:vimwiki_list = [myWikiWork, myWikiTrial]
let g:vimwiki_markdown_link_ext = 0 
--- end

**Comment by tinmarino** [comment]
Strange behaviour, I would expect the opposite: `[Test](Test.md)`  to work but not `[[Note.md|Note]]`.
Do the bug still appear in the dev branch ?

**Comment by DannyQuah** [comment]
Yep, the same behaviour appears in the dev branch. I'm still uneasy about opening this issue since no one else seems to have seen the problem. I'd thought by posting this, other users might come forwards but I'm seeing none do so.

**Comment by tinmarino** [comment]
>  I'm still uneasy about opening this issue since no one else seems to have seen the problem

In doubt, after verifying there is no duplicate, just open the issue. Then you can still close it. I don't remember the bug bug one month ago, Toto opened the issue, Titi commented, Tutu found the solution and I added the 2 lines of code. The the issue forum was usefull, And we are all glad Toto opened it.

**Comment by tinmarino** [comment]
Closing <= old

It may just be a permission issue
