### ISSUE TITLE
Inconsistent behaviour of   "%p   in Vimwiki diary

### ISSUE THREAD

**Issue by mgarort** [vimwiki/vimwiki#1015]
- OS: Ubuntu 18.04.4 LTS
- Syntax: Vimwiki native syntax
- Output of `:VimwikiShowVersion`: Stable version 2.5
-  Link to vimwiki settings in my `vimrc` on GitHub:  https://github.com/mgarort/dotvim/blob/master/vimrc#L75

I think I have found an inconsistency/bug in the behaviour of `"%p` in the Vimwiki diary. It is nothing major, too inconvenient or urgent in any way. However, I would like to know whether other people also experience the same behaviour, or it is a rogue config in my `vimrc`.

If I'm not wrong, the keybinding `"%p` should paste the current filename in the buffer. Just the filename, not the whole path to it. However, I find that in my Vimwiki diary entries, `"%p` pastes the whole path.

- If I do `"%p` in a random `.txt` file, such as `/home/mgarort/random.txt`, I paste just the filename `random.txt`.
- If I do `"%p` in a random Vimwiki note, such as `/home/mgarort/repos/wiki/random.wiki`, I paste just the filename `random.wiki`.
- If I do `"%p` in a Vimwiki diary note, such as `/home/mgarort/repos/wiki/diary/2020-09-15.wiki`, I paste the entire filepath, i.e. `/home/mgarort/repos/wiki/diary/2020-09-15.wiki`.

Could someone tell me if the same happens to them? Thanks!

**Comment by tinmarino** [comment]
It is the expected current behaviour as vimwiki open in_wiki_files with the absolute path: the absolute path of the wiki_root concatenate with diary concatenated with today_diary_name

The command define in plugin:
https://github.com/vimwiki/vimwiki/blob/78216de25e92ca6c862587c86f2a163a1667bd83/plugin/vimwiki.vim#L364-L365

Calls `vimwiki#diary#make_note`:
https://github.com/vimwiki/vimwiki/blob/78216de25e92ca6c862587c86f2a163a1667bd83/autoload/vimwiki/diary.vim#L269-L308

Calls `vimwiki#base#open_link` with a `diary:` prefix.
Which in turn calls `resolve_link`, with a strong string and dictionnary work, concatenating the required path parts. There you can see the filename is absolute.
https://github.com/vimwiki/vimwiki/blob/78216de25e92ca6c862587c86f2a163a1667bd83/autoload/vimwiki/base.vim#L257-L264

Some devs refactored path handling, to get all that more robust (#478).
My idea (bad) was to make all path linux compatible.
@EinfachToll idea (better) was to use object to contain path information.
This is a work in progress. And after the path format is clear, it is easy to open the file as relative if this last is shorter. Well it is easy now but would be hard to maintain.

Hope this answer the question.

**Comment by mgarort** [comment]
Hi @tinmarino , thanks a lot for your detailed answer!

I understand now. I also understand the content  of the `%` register better. I thought that `%` contained just the filename, i.e. just the filename plus the extension, without any directory information. However, rather than the filename, it contains _the path that was used to open the file_.

So for example, if I'm in my home folder `/home/mgarort/`, and I have a file `/home/mgarort/test_file.txt`:

- If I open `test_file.txt` with `vim test_file.txt`, then `%` contains `test_file.txt`.
- If I open `test_file.txt` with a weird, redundant path such as `vim ../mgarort/../mgarort/../mgarort/test_file.txt`, then somewhat surprisingly `%` contains the whole weird path `../mgarort/../mgarort/../mgarort/test_file.txt`.

I didn't know this before, and I used to think `%` always contained `test_file.txt`, hence my previous confusion.

Thanks for clearing that up. I will close this now since it is not a bug.
