### ISSUE TITLE
In markdown syntax `set filetype?` shows `vimwiki`

### ISSUE THREAD

**Issue by MahbubAlam231** [vimwiki/vimwiki#1019]
I am using vimwiki with markdown syntax:

    let g:vimwiki_ext2syntax = {'.md': 'markdown'}
    let g:vimwiki_list = [{'path': '~/vimwiki/',
                \'syntax': 'markdown',
                \'ext': '.md'}]

`:VimwikiShowVersion` says `Stable version 2.5`.

Since I am using markdown syntax, I wanted `commentstring` to be set to `<!--%s-->`.  But vimwiki sets `commentstring=%%%s` (`~/.vim/plugged/vimwiki/ftplugin/vimwiki.vim`). So I added the following to `.vimrc`:

    autocmd FileType markdown setlocal commentstring=

But it wasn't working, then [it was pointed out to me](https://vi.stackexchange.com/questions/27416/comments-for-github-flavored-markdown-with-vim-commentary?noredirect=1#comment49459_27416) that even in the case markdown syntax in vimwiki, `set filetype?` shows `vimwiki`, so I had to change the above to (and this works)

    autocmd FileType vimwiki setlocal commentstring=

Why is it that the filetype is `vimwiki` even in case of markdown syntax? It's no issue, as I said the above 'works', it's just a question.

Also maybe it will be helpful to markdown syntax users like me if you could add the above autocmd line to [Changing Wiki Syntax](https://github.com/vimwiki/vimwiki#changing-wiki-syntax) section in the README.md.

----------
**Edit:** Ok setting `let g:vimwiki_global_ext = 0` works. Maybe it will be helpful to markdown syntax users like me if you could add this to [Changing Wiki Syntax](https://github.com/vimwiki/vimwiki#changing-wiki-syntax) section in the README.md.

------------
Prior to submitting a new issue make sure to complete these steps:

- [ ] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [X] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [X] Include the output of `:VimwikiShowVersion`.

**Comment by tinmarino** [comment]
No, we won't put the autocmd in Readme because this is not the recommended way: see `:h g:vimwiki_commentstring` also search commentstring in issues fir more info.
Yes for adding the global ext: the reference issue is #664

**Comment by MahbubAlam231** [comment]
@tinmarino I see, though `g:vimwiki_commentstring` isn't in `master` branch yet.
