### ISSUE TITLE
Documentation inconsistency with default values of default template, path and extension

### ISSUE THREAD

**Issue by blipp** [vimwiki/vimwiki#102]
In `plugin/vimwiki.vim`, the default values for `template_path`, `template_default`, `template_ext` are empty:

```
let s:vimwiki_defaults.template_path = ''
let s:vimwiki_defaults.template_default = ''
let s:vimwiki_defaults.template_ext = ''
```

But the documentation says that the default values are

```
~/vimwiki/templates/
default
.html
```

I would like to suggest setting the default values according to the documentation, because it is nice to have non-empty defaults. Maybe instead of `.html`, choose `.tpl`, as the default template shipped with vimwiki is named `default.tpl`.

**Comment by EinfachToll** [comment]
Allright, thanks!

**Comment by blipp** [comment]
Thank you for fixing this.
