### ISSUE TITLE
UltiSnips <tab> doesn't work while using vimwiki (related issues: #357 #669)

### ISSUE THREAD

**Issue by MahbubAlam231** [vimwiki/vimwiki#1021]
My vimwiki syntax:
```vim
let g:vimwiki_ext2syntax = {'.md': 'markdown'}
let g:vimwiki_list = [{'path': '~/vimwiki/',
            \'syntax': 'markdown',
            \'ext': '.md'}]
```
`:VimwikiShowVersion`: `Stable version: 2.5`

Related issues: #357 #669 

**Description of the problem:**
[UltiSnips](https://github.com/SirVer/ultisnips) `<tab>` doesn't work with vimwiki filetypes. `:verbose imap <tab>` shows:
```vim
i  <Tab>       *@vimwiki#tbl#kbd_tab()
        Last set from ~/.vim/plugged/vimwiki/ftplugin/vimwiki.vim line 543
i  <Tab>       * <C-R>=UltiSnips#ExpandSnippet()<CR>
        Last set from ~/.vim/plugged/ultisnips/autoload/UltiSnips/map_keys.vim line 61
```
On the other hand there are plugins such as [supertab](https://github.com/ervandew/supertab) whose `<tab>` works along side UltiSnips. I wanted to keep the behaviour of `<tab>` from UltiSnips, so to overcome this issue I put the following in my `.vimrc`:
```vim
let g:vimwiki_table_mappings=0
augroup ChangeVimwikiTableTab
    autocmd!
    autocmd Filetype vimwiki inoremap <silent><expr><buffer> <M-n> vimwiki#tbl#kbd_tab()
    autocmd Filetype vimwiki inoremap <silent><expr><buffer> <M-p> vimwiki#tbl#kbd_shift_tab()
augroup end
```

According the `:h vimwiki` [here](https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/doc/vimwiki.txt#L3617), `g:vimwiki_table_mappings` option will be fully removed at a later point. Then the above wouldn't work.

I think UltiSnips is a very useful plugin. I wish vimwiki `<tab>` worked alongside UltiSnips `<tab>` just like [supertab](https://github.com/ervandew/supertab) does -- is there any way to implement this from `.vimrc` or elsewhere?

----------------------
Prior to submitting a new issue make sure to complete these steps:

- [X] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [X] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [X] Include the output of `:VimwikiShowVersion`.

**Comment by tinmarino** [comment]
### Brief

Add in you vimrc before packadd wiki:
```vim
let g:vimwiki_key_mappings = {}
let g:vimwiki_key_mappings.table_mappings = 0
```
### Explanation

According  #699 solved by 6ec85cd0e82f66: @ranebrown Allow buffer local mappings to overwrite existing mappings even removed the check.
The argument is that in vimwiki files, buffer local maps rule.

In ftpluging:
```vim
if str2nr(vimwiki#vars#get_global('key_mappings').table_mappings)
  inoremap <expr><buffer> <Tab> vimwiki#tbl#kbd_tab()
  inoremap <expr><buffer> <S-Tab> vimwiki#tbl#kbd_shift_tab()
endif
```

**Comment by MahbubAlam231** [comment]
@tinmarino I am sorry, I didn't understand what am I supposed to. Will this make both UltiSnips and vimwiki work with tab? Should I add

> ```viml
> let g:vimwiki_key_mappings = {}
> let g:vimwiki_key_mappings.table_mappings = 0
> ```

before adding all the plugins in vimrc?

And this
 
> ```viml
> if str2nr(vimwiki#vars#get_global('key_mappings').table_mappings)
>   inoremap <expr><buffer> <Tab> vimwiki#tbl#kbd_tab()
>   inoremap <expr><buffer> <S-Tab> vimwiki#tbl#kbd_shift_tab()
> endif
> ```
should be in `~/.vim/ftplugin/vimwiki.vim`?

**Comment by tinmarino** [comment]
Add the first to your vimrc.
The second is a reference to the responsible code

**Comment by MahbubAlam231** [comment]
@tinmarino If I add the first to my vimrc, it disables tab in tables altogether. No matter where I add it, before or after loading plugins, the same result.

There isn't anyway where vimwiki tab and UltiSnips tab work together? As I mentioned earlier UltiSnips tab and [supertab](https://github.com/ervandew/supertab) tab work together.

**Comment by tinmarino** [comment]
No, there is no way for a dual map: you must choose if you want to send the
map to Ultisnip or Vimwiki.
If you want you can add a condition like if Ultisnip is not trigering
results, use Vimwiki or the oposite.
But Vimwiki will not add plugin dependant code (It would be horrible to
maintain).

**Comment by MahbubAlam231** [comment]
> If you want you can add a condition like if Ultisnip is not trigering results, use Vimwiki or the oposite.

Yeah right, if UltiSnips isn't triggering results vimwiki tab should work, that's what I want.

I don't really know vim much, how to add a conditional to achieve this?

**Comment by rddunphy** [comment]
Here's my hacky solution to this problem (in `~/.vim/after/ftplugin/vimwiki.vim`):

```vim
function! VimwikiTabOrUltiSnips() abort
	let ret = vimwiki#tbl#kbd_tab()
	if ret=="\<Tab>"
		return "\<C-R>=UltiSnips#ExpandSnippetOrJump()\<CR>"
	end
	return ret
endfunction

function! VimwikiShiftTabOrSupertab() abort
	let ret = vimwiki#tbl#kbd_shift_tab()
	if ret=="\<S-Tab>"
		return "\<C-R>=SuperTab('p')\<CR>"
	end
	return ret
endfunction

inoremap <expr><buffer> <TAB> VimwikiTabOrUltiSnips()
inoremap <expr><buffer> <S-TAB> VimwikiShiftTabOrSupertab()
```

This makes `<TAB>` behave the Vimwiki when the cursor is in a table, and defaults to UltiSnips outside of tables (the second function is for if you also have SuperTab). It does mean that you can't expand snippets within a table, but I don't usually have so much stuff in tables that this is an issue.

**Comment by MahbubAlam231** [comment]
Thanks! It works.
