### ISSUE TITLE
foldexpr seems to be ignored when setting g:vimwiki_folding to custom

### ISSUE THREAD

**Issue by joejobber** [vimwiki/vimwiki#1024]
I tried to find out if this was reported already, but did not find a post about this issue. My apologies if my search-fu failed me.

I wanted to try out the example given in the help file for not including the last blank line in a fold, but it seems Vimwiki won't load the custom foldexpr. Or I messed up.

Here's what I did:

I set `g:vimwiki_folding ='custom'`

I added the settings shown in the help file to my vimwiki autogroup:
```vim
augroup myvimwiki
    au! myvimwiki
    au FileType vimwiki setlocal tabstop=2
    au FileType vimwiki setlocal breakindent
    au FileType vimwiki setlocal fileencoding=utf-8
    au FileType vimwiki setlocal foldmethod=expr
    au FileType vimwiki setlocal foldenable
    au FileType vimwiki set foldexpr=VimwikiFoldLevelCustom(v:lnum)
    au BufEnter *.wiki set isfname+=&,(,)
    au BufLeave *.wiki set isfname-=&,(,)
    au BufWinLeave *.wiki mkview
    au BufWinEnter *.wiki silent loadview
 augroup END
```

I copied the function VimwikiFoldLevelCustom shown in the help file to my vimrc.

I reloaded my vimrc and then opened a vimwiki file.

The folding was just the same. So I checked the value of the options and variables and they were as expected. Only when I checked the current value of foldexpr it showed the default function:

```vim
foldexpr=VimwikiFoldLevel(v:lnum)
```
instead of `VimwikiFoldLevelCustom(v:lnum)`

I am doing something obviously wrong here?

**Comment by tinmarino** [comment]
This is strange: Please post the output of
```vim
echo vimwiki#vars#get_global('folding')
```
the corresponding code is in [plugin](https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/plugin/vimwiki.vim#L176-L190). You may use the `debug` awesome buiiltin

**Comment by joejobber** [comment]
Thanks for responding! The output of that is literally "custom".

**Comment by tinmarino** [comment]
> The output of that is literally "custom".

Ok, so it is __not__ the fault of your conf but an inconsistent behavior (Good for you, bad for me LoL).


To be honest, I am surprised and do not know how to solve this.
Just one idea. Why is that the only `set`, why do not you put `setlocal` ?
```vim
au FileType vimwiki set foldexpr=VimwikiFoldLevelCustom(v:lnum)
```

If that do not work, try step by step:
Ensure you are at the top of the dev branch.
Remove all your conf and adding in vimrc:
```vim
set g:vimwiki_folding ='custom'
set foldmethod=expr
set foldexpr=VimwikiFoldLevelCustom(v:lnum)
```
and in vimwiki:
```vim
echo vimwiki#vars#get_global('folding')
verbose set foldmethod
verbose set foldexpr
```

**Comment by joejobber** [comment]
To be honest myself, I have no idea why I choose to use 'set' instead of 'setlocal' for that one expression. But I changed it to setlocal and it made no difference. Sadly.

Please, give me a few days to load the newest dev-branch and do some testing. I'll get back with the results as soon as I have had the opportunity to do this.

**Comment by joejobber** [comment]
OK, I found some time to do some testing. Here's exactly what I did:

1] Followed the steps in https://vimwiki.github.io/vimwikiwiki/Troubleshooting.html
2] Fired up vim -> no error messages.
3] Appended the 3 lines from above to min_vimrc:
set g:vimwiki_folding ='custom'
set foldmethod=expr
set foldexpr=VimwikiFoldLevelCustom(v:lnum)
4] Fired up vim again:
vim -u min_vimrc
Error detected while processing ~/vw_tmp/min_vimrc:
line   12:
E518: Unknown option: g:vimwiki_folding ='custom'
Press ENTER or type command to continue
5] Press ENTER
6] Vim runs 'normally'
7] Entered \ww in normal mode
8] Entered 'echo vimwiki#vars#get_global('folding')' in command mode -> no output
9] Entered 'verbose set foldmethod' in command mode -> see resulting output below:
foldmethod=manual
Last set from ~/vw_tmp/vimwiki/plugin/vimwiki.vim line 194
Press ENTER or type command to continue
10] Entered 'verbose set foldexpr' in command mode -> see resulting output below:
foldexpr=VimwikiFoldLevelCustom(v:lnum)
Last set from ~/vw_tmp/min_vimrc line 14
Press ENTER or type command to continue

Additional information: all done on an up-to-date (as in updated today) Debian testing install with an unmodified vim/gvim from the official Debian repository.

If I can do something else to help find the cause of this issue, just holler!

**Comment by tinmarino** [comment]
Good job, you cannot `set` the variable `g:vimwiki_folding ='custom'` you must `let` it because it is a user variable and not a vim internal variable. (It was my mistake sorry)

```vim
" You must define the function VimwikiFoldLevelCustom
let g:vimwiki_folding ='custom'
set foldmethod=expr
set foldexpr=VimwikiFoldLevelCustom(v:lnum)
```

**Comment by joejobber** [comment]
Oww, shoot! I don't know how I did not see that... Not near the laptop with the test install on it right now. I'll try again when I am back home.

**Comment by joejobber** [comment]
OK, I did take a look at my vimrc and there it says let instead of set, so I don't think that will be the cause of the trouble. But when I am home again I will test it with the test version I created earlier today, just to be sure.

**Comment by joejobber** [comment]
I did some testing with a corrected min_vimrc. The results did change.

:echo vimwiki#vars#get_global('folding')
custom
:verbose set foldmethod
foldmethod=expr
Last set from ~/vw_tmp/min_vimrc line 13
Press ENTER or type command to continue
:verbose set foldexpr
foldexpr=VimwikiFoldLevelCustom(v:lnum)
Last set from ~/vw_tmp/min_vimrc line 14
Press ENTER or type command to continue

So the custom function is actually loaded now. However, in my "normal" vim install it still is not. Therefore I pulled in the latest dev-branch for that install as well. The strangest thing happens after that: it does not load the custom folding function automatically (through the augroup), but now I can at least set it by hand afterwards and then it will load. No idea why it is not loaded through the autogroup settings though. More digging to do...

**Comment by joejobber** [comment]
OK, maybe that wasn't the best of ideas... After installing the dev-branch a new issue popped up. Only  the first number of wiki-links is shown as a link. The rest is shown as plain text. See screenshot. I tried with the minimal install as well, the same thing happens there too.

**Comment by joejobber** [comment]
New attempt for the screenshot
![screenshot_plain-text_links](https://user-images.githubusercontent.com/51863512/97001777-3ca99d00-1539-11eb-9880-5c0c76d5748d.png)

**Comment by joejobber** [comment]
Aha! The mystery about the loading of the custom folding function has been solved (as far as I can see right now). I use vim's views and I noticed after using 'verbose set foldexpr' that the result stated foldexpr was loaded through the view file. I removed the view file and voila! Customized folding! So, the view functionality was interfering. Maybe something to add to the help file, so others are not caught unaware?

**Comment by tinmarino** [comment]
I don't know vim view's. Can you link me to it please.
This kind of plugin precedence is no uncommon. In taht case the tipical solution, that work for you is:
1. Search in issues
2. Add issue
3. Dichotomically search your vimrc. That is what you may do if you post a minimal conf in the issue.

Glad it worked.

**Comment by joejobber** [comment]
View are built-in. See :he views

**Comment by tinmarino** [comment]
OK, it is like a section, I don't think it is useful to notify it because,
there are many ways like this to override configuration and this belongs to
the vim's documentation.
