### ISSUE TITLE
E806: using Float as a String

### ISSUE THREAD

**Issue by pejaham** [vimwiki/vimwiki#1029]
When I do a "git commit" using vim as editor I get a vimwiki error

Hinweis: Warte auf das Schließen der Datei durch Ihren Editor... Error detected while processing /Users/peter/.vim/plugged/vimwiki/plugin/vimwiki.vim:
line   13:
E806: using Float as a String

As a workaround I set the version number to dev as described in the source code on line 13:

" Set to version number for release, otherwise -1 for dev-branch
let s:plugin_vers = -1

Is there a better fix?

**Comment by tinmarino** [comment]
May you give more details : I can't reproduce it. And s:plugin_vers  is always treated as a float

**Comment by tinmarino** [comment]
Fixed by @dmouraneto in #1039

Thanks @dmouraneto!
