### ISSUE TITLE
Header folding truncation

### ISSUE THREAD

**Issue by ludenticus** [vimwiki/vimwiki#1035]
How do you change the character count at which the folding truncates a header?

In my experience, it truncates somewhere around characters 44 to 54, no matter the font size.

### Info
* Stable version: 2.5
* Syntax: markdown

**Comment by tinmarino** [comment]
```vim
set textwidth=12  " If you want it to be 12
set nowrap  " If you want no wrap
```

**Comment by tinmarino** [comment]
Closing <= Inactive question
