### ISSUE TITLE
Can I use customwiki2html.sh under windows 10?

### ISSUE THREAD

**Issue by VimWei** [vimwiki/vimwiki#1036]
- [x] Post the syntax you are using (default/mediawiki/markdown) 

markdown

- [x] Include the output of `:VimwikiShowVersion`.

Os: Windows
Vim: 802
Branch: HEAD
Revision: c9e6afe
Date: 2020-05-26 23:09:58 +0200

- [x] What I want?

Batch convert vimwiki Markdown files to HTML.

- [x] Question?

Can I use customwiki2html.sh under windows 10? (How to install Discount in windows? )

https://github.com/vimwiki/vimwiki/blob/master/autoload/vimwiki/customwiki2html.sh

**Comment by VimWei** [comment]
ref: https://github.com/WnP/vimwiki_markdown/issues/7

**Comment by tinmarino** [comment]
Hi VimWei.

vimwiki_markdown script is expecting too much arguments
You should use [pandoc](https://pandoc.org/) over vimwiki_markdown for many reasons: better maintenance, more versatile, robust, fast, stable, avalaible ...

Here is my [wiki2html](https://github.com/tinmarino/wiki/blob/master/wiki2html.sh). As you can see 6 arguments, vimwiki_markdown is expecting 9.


Cheers.

**Comment by VimWei** [comment]
Thanks!
