### ISSUE TITLE
Meta: Add Tag Hacktoberfest to repo

### ISSUE THREAD

**Issue by tinmarino** [vimwiki/vimwiki#1037]
Hello @Nudin,

Would you mind adding the "hacktoberfest" tag to the repo? That way, we could get some new contributors.

Links:
- How to add tag: https://www.youtube.com/watch?v=FxBv4FMcDgo&ab_channel=DigitalOcean
- Hacktoberfest: https://hacktoberfest.digitalocean.com

**Comment by Nudin** [comment]
good idea

**Comment by tinmarino** [comment]
Thanks @Nudin. Now I know what to do => I'll tag some issues and support some newcomers.

**Comment by tinmarino** [comment]
Thank you again @Nudin for your fast reaction (and long term contribution of course).
I added some tag, we'll see if that bring some humans.
