### ISSUE TITLE
Can I change how :VImwikibacklinks displays?

### ISSUE THREAD

**Issue by Vamsee30** [vimwiki/vimwiki#1040]
Right now the buffer shows a file directory. I would rather it show either just the filename (without the complete path) or even some kind of %title element within the Note. Is this possible?

**Comment by brennen** [comment]
There's no way to configure this right now, but after looking I think it would be possible to improve.

Some quick research:

`:VimwikiBacklinks` calls `vimwiki#base#backlinks`, which uses [setloclist()](https://vimhelp.org/eval.txt.html#setloclist%28%29) under the hood.

`setloclist()` takes a `what` dictionary, which the [`setqflist()` docs](https://vimhelp.org/eval.txt.html#setqflist%28%29) say can include the following:

```
		    bufnr	buffer number; must be the number of a valid
				buffer
		    filename	name of a file; only used when "bufnr" is not
				present or it is invalid.
		    module	name of a module; if given it will be used in
				quickfix error window instead of the filename.
		    lnum	line number in the file
		    pattern	search pattern used to locate the error
		    col		column number
		    vcol	when non-zero: "col" is visual column
				when zero: "col" is byte index
		    nr		error number
		    text	description of the error
		    type	single-character error type, 'E', 'W', etc.
		    valid	recognized error message
```

So probably:

  - `text` could be assigned some sort of title (extract `%title` if present and fall back to first line or something if not?), or probably better just the line where the link appears.
  - `module` can be assigned `fnamemodify(source_File, ":t")` or something like it to condense filename display

I wound up with this:

```vim
          call add(locations, {'filename':source_file, 'lnum':lnum, 'col':col, 'text':'foo', 'module':fnamemodify(source_file, ":t")})
```

Which yields a location list like this:

```
2020-01-03.wiki|10 col 26| foo
2021-02-09-2227-17.wiki|26 col 7| foo
machines.wiki|52 col 7| foo
toc.wiki|1005 col 7| foo
wmf.wiki|35 col 9| foo
```

You'd want to replace foo with the line that includes the link, or your `%title`.

The other problem with this function is just that it's incredibly slow for a large wiki.  Maybe we could narrow the search space with `:vimgrep` or something first.

If I get ambitious I might turn this into a real pull request, but no promises.

**Comment by tinmarino** [comment]
Closing <= Inactive question

Thanks @brennen for the answer: I did not really understand the question but for sure you are pointing to the good way.

**Comment by hulufei** [comment]
I made an [alternative lua plugin](https://github.com/hulufei/backlinks.nvim), if you're using neovim, you can try it.

BTW, it's faster than `:Vimwikibacklinks`.
