### ISSUE TITLE
Error detected while processing function vimwiki#base#go_back_link

### ISSUE THREAD

**Issue by Giatroo** [vimwiki/vimwiki#1046]
I reinstalled vimwiki and now it doesn't show my lightline anymore when I enter a wiki file. I need to create a split and then it appears again. 

More over, when I'm at `foo.md` and I hit backspace (to return to some previous file) this message is printed: 
```
Error detected while processing function vimwiki#base#go_back_line[12]..vimwiki#base#edit_file:
line 26:
E171: Missing :endif 
Error detected while processing function vimwiki#base#go_back_link:
line 12:
E171: MIssing :endif
```
If I hit enter the expected outcome happens and I return to the previous page. But now, if I try to go `foo.md` by hitting enter, this message is printed:
```
Error detected while processing function vimwiki#base#follow_link[75]..vimwiki#base#open_link[34]..vimwiki#base#edit_file:
line 26:
E171: Missing :endif
Error detected while processing function vimwiki#base#follow_link[75]..vimwiki#base#open_link:
line 34:
E171: Missing :endif
Error detected while processing function vimwiki#base#follow_link:
line 74:
E171: Missing :endif
```
I hit enter and the expected outcome happens and now I'm in `foo.md`, but my backspace key doesn't work anymore.

-----

My vimwiki settings are:
```
" required
set nocompatible

" Changing wiki dir
let g:vimwiki_list = [{'path' : '~/vimwiki/',
                    \ 'syntax' : 'markdown', 'ext' : '.md'}]

" Remove the tab bind in insert mode
let g:vimwiki_key_mappings = {
  \   'all_maps': 1,
  \   'global': 1,
  \   'headers': 1,
  \   'text_objs': 1,
  \   'table_format': 1,
  \   'table_mappings': 0,
  \   'lists': 1,
  \   'links': 1,
  \   'html': 1,
  \   'mouse': 0,
  \ }

```

and my version is `Stable version: 2.5`.

**Comment by tinmarino** [comment]
Please use the `dev` version before submiting an issue. Maybe it has been fixed.
This bug seems to have been fixed in dev: https://github.com/vimwiki/vimwiki/issues?q=E171%3A+Missing+%3Aendif

**Comment by Giatroo** [comment]
Oh, I'm sorry. I actually don't know how to switch to the `dev` version, but it seems working now (I switched to airline instead lightline).

Thanks for the support anyway =)
