### ISSUE TITLE
customwiki2html.sh - Conversion to HTML is not supported for this syntax 

### ISSUE THREAD

**Issue by arozehnal** [vimwiki/vimwiki#1049]
I run Vim 8.1 and vimwiki 2.5 on AIX.

I'd like to use Mardown syntax. I decide to use customwiki2html.sh,  so I installed Discount converter and I did some changes in my .vimrc:
`let g:vimwiki_list = [{'path': '~/vimwiki/',
                      \ 'syntax': 'markdown', 'ext': '.md' }]
let g:vimwiki_customwiki2html='/intax/roze/.vim/plugged/vimwiki/autoload/vimwiki/customwiki2html.sh'
`
After I run -> Vimwiki2HTML

I got this error:
Vimwiki Error: Conversion to HTML is not supported for this syntax   

I controlled customwiki2html.sh ...
ls -l /intax/roze/.vim/plugged/vimwiki/autoload/vimwiki/customwiki2html.sh 
-rwxr-x---    1 roze     adis           1596 10 lis 08:10  /intax/roze/.vim/plugged/vimwiki/autoload/vimwiki/customwiki2html.sh

I guess I have something wrong in my .vimrc.
Any suggestion?

**Comment by deepredsky** [comment]
it works for me setting the cutomwiki2html script inside the wikilist definition like this:

```vim
let g:vimwiki_list = [{'path': '~/notes/', 'syntax': 'markdown', 'ext': '.md', 'template_path': '', 'custom_wiki2html': '$HOME/.bin/wiki2html.sh' }]
```

**Comment by tinmarino** [comment]
Thanks @deepredsky.

@arozehnal you can follow the deepredsky's way or you can at least put a command separator between your town command or better separe then with a new line

```vim
let g:vimwiki_list = [{'path': '~/vimwiki/', \ 'syntax': 'markdown', 'ext': '.md' }]
let g:vimwiki_customwiki2html='/intax/roze/.vim/plugged/vimwiki/autoload/vimwiki/customwiki2html.sh'
```

Also what is the syntax of the current file?
```vim
echo %
echo vimwiki#vars#get_wikilocal('syntax')
set ft
```

**Comment by arozehnal** [comment]
The syntax of the current file is markdown.
deepredsky's way works mi fine - thank you for your advice/help :-)

**Comment by stephan-t** [comment]
The problem is that the `customwiki2html.sh` documentation has a typo.

The variable `vimwiki_customwiki2html` should be `vimwiki_custom_wiki2html`, as specified in the `vimwiki.txt` documentation.

Also, the comment on line 16 about `mkd2text` should be `mkd2html`.
