### ISSUE TITLE
Examples of personal vim wikis

### ISSUE THREAD

**Issue by jsatk** [vimwiki/vimwiki#1050]
This isn't an issue, but I was unsure of how else or where else to ask this.

I think this project is awesome and the idea of a personal wiki is very intriguing to me. I read through the `:help` and the `README.md` — which are great at telling me how to use vimwiki in terms of its commands and navigating, etc. But I'm a bit stumped as to how to actually make one. What does a great personal wiki look like? I googled it (as I know this isn't the only personal wiki software out there) and all the examples were either just telling me to use some software or unrealistic examples.

So my question is this — are there any good examples of a personal wiki out there that I can read and explore to get ideas and inspiration from? Given that it's a _personal_ wiki I realize that the vast majority of people probably *don't* want to share theirs. But if any exist it'd be super helpful to see them to glean inspiration. And possible link to them as examples from the `README`. 

Thanks in advance and — again — apologies if opening an issue to ask this question was the wrong move.

**Comment by tinmarino** [comment]
https://github.com/vimwiki/vimwikiwiki

**Comment by jsatk** [comment]
Thank you so much.

**Comment by jsatk** [comment]
Finally getting around to looking at this. Thanks @tinmarino. Very helpful.
