### ISSUE TITLE
Typefaces don't render when the text contains underscore

### ISSUE THREAD

**Issue by FelixZhang** [vimwiki/vimwiki#1059]
Prior to submitting a new issue make sure to complete these steps:

- [ ] syntax: markdown
- [ ] **steps to reproduce the issue**
    - input *foobar* *foo_bar*
    - only "foobar" is rendered as italic while "foo_bar" is not
- [ ] output of `:VimwikiShowVersion`: Stable version: 2.5

**Comment by tinmarino** [comment]
Hello @FelixZhang,

When underscore_are_between_2_word_leteers it do not trugger underscore.

Anyhow, checkout to the dev branch, many imporvement on typeface have been done: now they are syntax region and not matches any more.

**Comment by FelixZhang** [comment]
Understood. Thanks very much for the hint.
