### ISSUE TITLE
resolve_link does not properly resolve absolute links

### ISSUE THREAD

**Issue by thorlucas** [vimwiki/vimwiki#1064]
`vimwiki#base#resolve_link` does not properly resolve absolute links:

```
:echo vimwiki#path#is_absolute('Chemistry/Reactions/index.md')
0

:echo vimwiki#base#resolve_link('Chemistry/Reactions/index.md')
{'index': 0, 'filename': '/Users/ME/Dropbox/Wiki/Chemistry/Reactions/index.md', 'scheme': 'wiki0', 'anchor': ''}

:echo vimwiki#path#is_absolute('/Users/ME/Dropbox/Wiki/Chemistry/Reactions/index.md')
1

:echo vimwiki#base#resolve_link('/Users/ME/Dropbox/Wiki/Chemistry/Reactions/index.md')
{'index': 0, 'filename': '/Users/ME/Dropbox/Wiki/Users/ME/Dropbox/Wiki/Chemistry/Reactions/index.md', 'scheme': 'wiki0', 'anchor': ''}
```

Clearly that is incorrect.

**Comment by tinmarino** [comment]
Hi, Feel free to open a PR

**Comment by thorlucas** [comment]
@tinmarino I’m still learning Vimscript and projects as big as Vimwiki are a bit beyond my capabilities right now...

**Comment by brennen** [comment]
I think the behavior described above is actually correct.

In VimWiki, a link to `/foo` should go to `foo.wiki` in the root of the wiki folder. If you want an absolute file path, you can use something like `//Users/ME/Dropbox/Wiki/Chemistry/Reactions/index.md`.  (Note leading `//`.)

From the docs under `:help vimwiki-syntax-links`:

```
...wiki links starting with "/" are considered to be
absolute to the wiki root directory, that is, the link [[/index]] always opens
the file /path/to/your/wiki/index.wiki, no matter in which subdirectory you
are currently in.

...

If you want an absolute path in your local box you can prefix the path
with //
  [[//absolute_path]]
For example:
  [[///tmp/in_root_tmp]]
  [[//~/in_home_dir]]
  [[//$HOME/in_home_dir]]
```

That said, correct behavior here is currently a bit broken on the dev branch. See #1084.
