### ISSUE TITLE
Feature request: Open external link in the same terminal

### ISSUE THREAD

**Issue by doxanthropos** [vimwiki/vimwiki#1069]
Since Vim itself and therefore also Vimwiki are applications that can be comfortably used without a graphical environment (X, Wayland etc.) and are used by some users through ssh sessions, it would (IMHO) be nice to have a way to deal with external links without invoking X-stuff (xdg-open). There is a variaty of terminal internet browsers available that could be used to open external links.
On a secone note: internet protocols that are not supported by current graphical browsers (gopher, gemini etc.) are sometimes supported by older terminal browsers like Lynx or newer ones like Bombadillo.
For these reasons, I think it would be great to have an option to open external links in the terminal, without routing through x (at the moment I changed xdg-open to x-terminal-emulator -e lynx for myself in the url function in base.vim), but in a similar way that less uses for switching to an editor and back (suspending to the background, starting lynx, restoring to foregroud when lynx quits).
I would and will work on this, because it is something I want.
My question and reason for this issue is twofold:

- Is there already something like this that I am missing?
- Would others be interested in this, so that it shoud become a PR or is it just me?

**Comment by brennen** [comment]
> Is there already something like this that I am missing?

Have a look at `:help VimwikiLinkHandler`.  Opening different URL schemes in the browser of your choice should be fairly simple by overriding that function.

On a recent version of vim, you could probably even spawn a terminal inside a window split in the editor (see `:help :terminal`) and start Lynx there.  Another approach that might work well is using tmux and sending commands to a tmux buffer.

**Comment by brennen** [comment]
This seems to work, more or less:

```vim
   function! VimwikiLinkHandler(link)
     if a:link =~# '^https\?:'
        try
          execute ':terminal lynx ' . a:link
          return 1
        catch
          echo "Failed executing Lynx."
        endtry
     endif
     return 0
   endfunction
```

**Comment by brennen** [comment]
Leaving this open for the moment since it's probably a good candidate for adding to the docs, at least.

**Comment by doxanthropos** [comment]
Wow this is nice!
I did not know about ":terminal".
Will now probably use that a lot, not just for opening links in lynx (which it does).
Thank you very much!

**Comment by tinmarino** [comment]
Closing <= Inactive question
