### ISSUE TITLE
Go back to previous wiki page using <RightMouse><LeftMouse> not working 

### ISSUE THREAD

**Issue by Shubhamsm** [vimwiki/vimwiki#1070]
Prior to submitting a new issue make sure to complete these steps:

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [ ] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [ ] Include the output of `:VimwikiShowVersion`.

**Comment by tinmarino** [comment]
`:h vimwiki_mouse` and then `:h g:vimwiki_key_mappings` (search mouse). Sorry the doc is not nicely formatted.

in your vimrc:
```
let g:vimwiki_key_mappings = { 'mouse': 1, 'lists_return': 1 }
```

The list_returns is added due to a just discovered bug from #1066
