### ISSUE TITLE
Render div with custom class

### ISSUE THREAD

**Issue by jericdeleon** [vimwiki/vimwiki#1071]
First of all, thanks for the plugin! Currently planning to migrate all my notes into it.

Is there any easy way to have a block of text rendered inside a `div` tag, with a custom class? It should be very similar to what the preformatted text feature (`{{{ ... }}}`) does, but the text inside rendered in a `div` tag (instead of a `pre` tag).

Use case: I want to utilize [Mermaid](https://mermaid-js.github.io/mermaid/#/) in my wikis. So far, I'm using the preformatted text feature to inject the class, but the rendered SVG is inside the `pre` block:

Wiki:
```
= Mermaid =
{{{class="mermaid"
graph TD;
  A-->B;
  A-->C;
  B-->D;
  C-->D;
}}}
```

HTML:
![mermaid01](https://user-images.githubusercontent.com/4323447/103162122-0c40e200-47ba-11eb-9234-9a7c5cd0cdef.png)

**Comment by tinmarino** [comment]
Hello @jericdeleon,
Currently, I don't know how to do that. Let's follow the conversation in the

duplicate issue: #1045

**Comment by jericdeleon** [comment]
Thanks for linking the ongoing discussion!
