### ISSUE TITLE
Syntax coloring not working

### ISSUE THREAD

**Issue by samyak-jain** [vimwiki/vimwiki#1075]
Prior to submitting a new issue make sure to complete these steps:

- [X] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [X] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [X] Include the output of `:VimwikiShowVersion`.

## VimWiki Settings:
```
let g:vimwiki_list=[{'path': '~/vimwiki/',
                      \ 'syntax': 'markdown', 'ext': '.md'}]
let g:vimwiki_hl_headers=1
let g:vimwiki_hl_cb_checked=1
```

## Description:
I am unable to see any highlight color like in the screenshots in the Readme. I have tried several different colorschemes including the default and none of them seem to have any highlighting at all with the exception of links, bullets and checklists. 

![image](https://user-images.githubusercontent.com/10133258/103374586-f73bba00-4afd-11eb-9b4f-47cf8c50be7f.png)

## Output of :VimwikiShowVersion
```
Os: Linux                                                                                                
Vim: 800
Branch: dev
Revision: ffc4e41
Date: 2020-12-29 11:38:24 -0300
```

I'm running neovim.
```
NVIM v0.5.0-dev+980-g28a0f6b17
Build type: RelWithDebinfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az175-356

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

Terminal Emulator: Kitty
```
kitty 0.19.3 created by Kovid Goyal
```

Please let me know if there's any info I've missed out or if this is not the right place to post this.

**Comment by chipsenkbeil** [comment]
@samyak-jain, your screenshot shows vimwiki syntax but your vimwiki settings indicate markdown. Which language are you having trouble getting syntax highlighting? How is the current buffer trying to be treated (as wiki or md)?

Your list has syntax highlighting, so wondering if it's a case of having the wrong language set.

**Comment by samyak-jain** [comment]
Can't believe I missed something so obvious. Thanks for pointing it out!
