### ISSUE TITLE
How to select a wiki by index (from a bash script)

### ISSUE THREAD

**Issue by patrickdavey** [vimwiki/vimwiki#108]
Hi there,

I completely love vimwiki - use it all the time.  In a git commit hook I am automatically generating the html and then rsync'ing the files where I want them to go.  For the default wiki (it works fine) and looks like this:

```bash
  #!/bin/bash
  vim - "+VimwikiIndex" "+VimwikiAll2HTML" "+quit"
  ~/vimwiki/site_html/sync.sh
```

Now, I have a second wiki (at index 2) that I want to do a similar process for.  I couldn't, for the life of me, work out how to do it.  I looked in [the plugin source for VimwikiIndex](https://github.com/vimwiki/vimwiki/blob/dev/plugin/vimwiki.vim#l509-510) and I can see it takes a count, but I couldn't work out how to do it using the syntax above.  I'd like to do something like

```bash
  #!/bin/bash
  vim - "+2VimwikiIndex" "+VimwikiAll2HTML" "+quit"
  ~/vimwiki/site_html/sync.sh
```

In the end I created (just locally) a copy of the command to do what I wanted it to do:

```
command! VimwikiSpecialIndex
   \ call vimwiki#base#goto_index(2)
```

But I'm just guessing there is a way.  If there is, can you let me know, if not, is this something that's possible to program up (and if you can make a suggestion I'll try to implement it :)

Best,
Patrick

**Comment by EinfachToll** [comment]
`:2VimwikiIndex` doesn't work, because it's a bit difficult in Vimscript to make a command that takes a count *and* to make a mapping to that command which takes a count also. So, as a solution, you can use the mapping instead of the command: so instead of "+2VimwikiIndex" use "+normal 2\ww" (if \ is your leader key).

**Comment by patrickdavey** [comment]
That works absolutely perfectly :+1: 

Closing - thanks!
