### ISSUE TITLE
Question/Feature Request: Open PDF file in Zotero

### ISSUE THREAD

**Issue by IIPatternII** [vimwiki/vimwiki#1081]
Prior to submitting a new issue make sure to complete these steps:

- [x] Check out the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.

**Zotero with the ZotFile extension** allows generating a markdown file with notes and highlights of a PDF. Something like this:

```
# Extracted Annotations (2021-01-10)

> "Experiments 1-3 manipulate the complexity of texts and find a negative relationship between complexity and judged intelligence." 
([Oppenheimer 2006:139](zotero://open-pdf/library/items/WZH9EBRZ?page=1))

> "Experiment 4 directly manipulated fluency and found that texts in hard to read fonts are judged to come from less intelligent authors." 
([Oppenheimer 2006:139](zotero://open-pdf/library/items/WZH9EBRZ?page=1))
```
Is there a way that I can make VimWiki open the PDF that is in Zotero's storage via this link?:

**`[Oppenheimer 2006:139](zotero://open-pdf/library/items/WZH9EBRZ?page=1)`**

I have tried:
- Using the link as it is --> VimWiki tries to create a new note on the path.
- Adding different variations of "**file:**" and "**local:**"  --> VimWiki doesn't open the link and gives no feedback.

As expected, it works ok if I specify the full path to the PDF with "**local:**". But I'm looking to avoid that because I have dozens of PDFs, and can't modify every single link.

Note: When I open the file with macOS TextEdit App, highlight the link, and click on **Open URL** in the menu, it works correctly.

**Comment by brennen** [comment]
I'm guessing the easiest path to this is by overriding the `VimwikiLinkHandler` function.  See `:help VimwikiLinkHandler`.

As an example other than the one in the help file, I happen to have written this one yesterday:

```vim
    " override default vimwiki link handling - could be extended to add
    " custom link types, etc.  Right now all it does is use vim itself
    " to handle files, crudely.
    function! VimwikiLinkHandler(link)
       if a:link =~# 'file:'
        try
          " chop off the leading file: - see :h expr-[:] for syntax:
          execute ':e ' . a:link[5:]
          return 1
        catch
          echo "Something went wrong..."
        endtry
      endif
      return 0
    endfunction
```

...pretty much based on the example from the docs, and surely could be improved. I'd guess you could figure out a command-line to give zotero for this, or maybe even just feed the URL to whatever MacOS command opens URLs.  Maybe something like `open -a "Zotero" zotero://open-pdf/library/items/WZH9EBRZ?page=1` does the trick, but I'm a bit hazy on that part.

**Comment by IIPatternII** [comment]
Thanks, @brennen! This is the function for Zotero:
```

    function! VimwikiLinkHandler(link)
       if a:link =~# 'zotero:'
        try
          execute "!open -a Zotero " . shellescape(a:link)
          return 1
        catch
          echo "Something went wrong..."
        endtry
      endif
      return 0
    endfunction
```

It works, but you have to press enter every time it executes. I couldn't make it work with `silent` instead of `execute`. Good enough for me, closing the issue. 

**Thanks again!**
