### ISSUE TITLE
Page links with leading slash lead to a file in working directory, not a page at the root of the wiki

### ISSUE THREAD

**Issue by brennen** [vimwiki/vimwiki#1084]
**Note:** I originally thought this was only broken for pages in a subdirectory (like the diary), but I've updated the description below to reflect that currently (I'm on 61a6ce66) it fails for everything.

- [X] Checkout the `dev` branch and confirm the issue is present there as well.

Yeah.  It's something in 850aace. When I `git revert` that commit, the problem goes away.

cc: @tinmarino 

- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.

With Default vimwiki syntax, open a page and write a link like `[[/foo]]`.  Press enter on that link.  You'll be taken to a file in the current working directory, rather than in the vimwiki directory.

For example:

* My wiki is in `~/notes/vimwiki`.
* I start vim from `~/notes`
* I edit `~/notes/vimwiki/diary/2021-01-15.wiki`, and try to link to `[[/foo]]`.
* When I press enter on that link, I am editing `~/notes/foo.wiki` instead of the expected `~/notes/vimwiki/foo.wiki`.
    * Does the same for other working directories.

- [X] Include the output of `:VimwikiShowVersion`.

```
Os: Linux
Vim: 801
Branch: dev
Revision: 61a6ce6
Date: 2021-02-05 08:58:02 -0300
```

- [X] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`

Default syntax.

Test `.vimrc`:

```vim
" a stub vimrc for just running vimwiki on an otherwise stock setup

set nocompatible
set nomodeline
let mapleader = ","

" vundle setup & vundle-managed plugins {{{

  filetype off

  set rtp+=~/.vim/bundle/Vundle.vim/
  call vundle#begin()

  " let Vundle manage Vundle - required:
  Plugin 'VundleVim/Vundle.vim'

  " CUSTOMIZE: vimwikis - for notes, daily logs, etc. {{{

    " main personal wiki
    let wiki = {}
    let wiki.path = '~/notes/vimwiki/'
    let wiki.path_html = '~/notes/html/'
    let wiki.auto_tags = 1
    let wiki.auto_diary_index = 1
    let wiki.automatic_nested_syntaxes = 1

    " a markdown wiki for testing purposes
    let markdownwiki = {}
    let markdownwiki.path = '~/notes/markdownwiki'
    let markdownwiki.path_html = '~/notes/markdownwiki/html/'
    let markdownwiki.auto_tags = 1
    let markdownwiki.auto_diary_index = 1
    let markdownwiki.automatic_nested_syntaxes = 1
    let markdownwiki.syntax = 'markdown'
    let markdownwiki.ext = '.md'

    " there can be many of these
    let g:vimwiki_list = [wiki, markdownwiki]

    " don't make temporary wikis based on file extensions in the list - this
    " is necessary to avoid .md files getting a filetype of vimwiki instead of
    " markdown:
    let g:vimwiki_global_ext = 0

    let g:vimwiki_folding = 'expr'
    " let g:vimwiki_folding = 'syntax'
    " let g:vimwiki_folding = 'list'

    " links concealing, etc.
    " let g:vimwiki_conceallevel = 0

    " don't obscure URLs in links
    " let g:vimwiki_url_maxsave = 0

    " make links clickable and such
    let g:vimwiki_use_mouse = 1

    " use colors in header highlighting
    let g:vimwiki_hl_headers = 1

    Plugin 'vimwiki/vimwiki'

  " }}}

  call vundle#end()
  filetype plugin on
  filetype indent on

" }}}
```

**Comment by tinmarino** [comment]
@brennen thanks for creating the issue.
I plan to have a look it this week end.

**Comment by brennen** [comment]
Thanks for looking into it! Definitely kind of an edge case - I use those links a lot, but my setup is a bit weird and I don't know how common it is really.  I'll update here if I find some time to investigate more closely...

**Comment by brennen** [comment]
I was just trying to track this down.

If I comment out the `let is_absolute = 1` [added here](https://github.com/vimwiki/vimwiki/commit/850aace4655253ec6faf36e907e22a2b2afea3a8#diff-80d1f2cb0f199164f5727892242649d1dfef394f9b2afca019962b4b496419f7R188), currently [line 194](https://github.com/vimwiki/vimwiki/blob/61a6ce668621359056d4b252ca8fbc6d1e3d2534/autoload/vimwiki/base.vim#L194), a `[[/foo]]`-style link works again.

That made me wonder if `is_absolute` was even getting set before that commit, which it was, but only like so:

```vim
  " Check if absolute or relative path
  let is_absolute = 0
  if is_wiki_link && link_text[0] ==# '/'
    if link_text !=# '/'
      if link_text !=# '//' && link_text[0:1] ==# '//'
        let link_text = resolve(expand(link_text))
        let link_text = link_text[2:]
        let is_absolute = 1
      else
        let link_text = link_text[1:]
      endif
    endif
    let is_relative = 0
  elseif !is_wiki_link && vimwiki#path#is_absolute(link_text)
    let is_relative = 0
  else
    let is_relative = 1
    let root_dir = fnamemodify(source_file, ':p:h') . '/'
  endif
```

I think there's some confusion between the original meaning of `is_absolute` in this function, as written in e3e841f33 by @justrajdeep, and what `vimwiki#path#is_absolute()` checks for.

I'm pretty sure @justrajdeep's version of the variable only gets set if the link has a leading `//`, while the function returns true for a leading windows drive letter, a `/`, or `~`.  That is, the function's checking a _filesystem path_, and not a vimwiki page path.

Does that sound right?  `resolve_link()` is not an easy function to think through.

**Comment by brennen** [comment]
Looking again, e3e841f itself also doesn't seem to work.

With VimWiki syntax:

- `[//etc]]` takes me to `etc.wiki` in the current working directory
- `[///etc]` takes me to `/etc.wiki`
- `[[///home/brennen/notes/vimwiki/index.wiki]]` does take me to `/home/brennen/notes/vimwiki/index.wiki`, but I'm not sure why I would need that and it doesn't match the documentation.

**Comment by brennen** [comment]
> Looking again, e3e841f itself also doesn't seem to work.

...ok, looking at the tests, I guess this is behaving as intended.  I may just not understand the use case for it.
