### ISSUE TITLE
Embed lists in tables

### ISSUE THREAD

**Issue by Mavpt** [vimwiki/vimwiki#1085]
I would like to be able to embed lists into tables.

I know it's possible to do this the other way around, but I think it'd be a useful alternative to indenting lists with few main entries and many sub-entries, namely for todo-lists.

If there's already a way to do this or a workaround to make it work, please point me in the right direction.

**Comment by tinmarino** [comment]
I think you can't, there is a syntax permited list in tables (see syntax/vimwiki.vim).
Would you like it for mardown or vimwiki format? A good html convertion is important, do that exist in markdown (lists in table's cells)?

**Comment by Mavpt** [comment]
So far I haven't done much with VimWiki so switching from VimWiki Syntax to Markdown wouldn't be much of a hassle if this feature was to be implemented in the latter.
From my (admittedly short) research, to include a to-do list in a table using Markdown you're limited to using pure HTML (https://stackoverflow.com/questions/47344571/how-to-draw-checkbox-or-tick-mark-in-github-markdown-table/55523035).
Of course it's only worthwhile to include this feature in either syntax if it can be properly converted to HTML, but I couldn't find a way to do so in Markdown and am unaware of how troublesome such a feature can be to implement.

**Comment by tinmarino** [comment]
I'll try to add your link in markdown as a non regression.
This markdown html trick is the best solution without any doubt: vimwiki do
not handle markdown convertion and this feature in wiki format is too much
work to think it will be done.
