### ISSUE TITLE
vimwiki Github Profile Picture

### ISSUE THREAD

**Issue by thecliguy** [vimwiki/vimwiki#1086]
Since VimWiki has a logo it would be nice to use it as the project's Github profile picture.

In [this](https://github.com/vimwiki/vimwiki/blob/master/doc/splash.png) version of the logo the text runs horizontally. I'm not sure but this might make the text hard to read when scaled to fit the dimensions and aspect ratio used for Github profile pictures. So it might be better to have a version of the logo where the text runs vertically, EG:

```
 vim
 ---
 wiki
```

Some experimenting will probably be required to find out what works best...

**Comment by mtoohey31** [comment]
Something like this?
![vertical-logo](https://user-images.githubusercontent.com/36740602/111336446-a1ca7000-864b-11eb-989a-022b0afed1d1.png)
(I'm just messing around in Inkscape here, don't have a clue about graphic design.)

If this is kinda what we're going for I have the svg, I can only attach images to this reply though.

**Comment by thecliguy** [comment]
@mtoohey31 That looks excellent to me, it's exactly what I had in mind.

@Nudin Are you happy to try using this as project's Github profile picture?

I think this would look a lot better than the existing default image. For example, if you navigate to [my Github profile](https://github.com/thecliguy) and scroll down to `Organizations`, currently you'll see this:

![image](https://user-images.githubusercontent.com/23440389/111351710-5def5f00-867b-11eb-9dfb-2b209b005791.png)

**Comment by Nudin** [comment]
I set it as the image for the organization. Sadly the tiny version  looks a bit weird. Maybe creating a thumbnail version from the original SVG works better?

**Comment by thecliguy** [comment]
@Nudin I think the problem is that the word "wiki" doesn't render as a solid colour.

@mtoohey31 Are you able to provide the original SVG? Perhaps you could create a repo under your account and upload it?

**Comment by mtoohey31** [comment]
Sure, here's the repo: https://github.com/mtoohey31/vimwiki-logo

**Comment by thecliguy** [comment]
@mtoohey31 Is that just the same file as the one you attached to this issue? Because it seems to be a PNG again rather than an SVG.

**Comment by mtoohey31** [comment]
My bad! Meant to push the SVG version instead, it's up there now!

**Comment by thecliguy** [comment]
> 
> 
> I set it as the image for the organization. Sadly the tiny version looks a bit weird. Maybe creating a thumbnail version from the original SVG works better?

@Nudin Now that the [SVG](https://raw.githubusercontent.com/mtoohey31/vimwiki-logo/main/vertical-logo.svg) is available do you want to try using this?

**Comment by Nudin** [comment]
I reuploaded it as 100px png image (svg isn't supported by github). It looks fine on the [organization page](https://github.com/vimwiki), on user pages the 'wiki' is barely readable, but that's probably not necessary?

**Comment by thecliguy** [comment]
Excellent. I think the version that's displayed on a user profile looks fine.

When you hover over the image, a tooltip appears with a slighly larger version:

![image](https://user-images.githubusercontent.com/23440389/112396982-157a1600-8cf9-11eb-81d3-75cfd5388330.png)

Since this is an asset that's now used by the project, I think it should be under version control. Perhaps the most appropriate place for it to reside is in `vimwiki/doc/`?

Should mtoohey31 submit a PR for this? 
_(I just want to make sure he gets the credit for making this contribution)._

**Comment by mtoohey31** [comment]
:+1:  Lmk if you'd like me too submit it as PR, also, I added darker variants of the logos to that repo for now if you'd prefer a darker colour for "wiki" so it's more visible. You can also play around with in Inkscape if you want to tweak it, it's not too complicated, you just have to select "wiki" and then adjust the fill colour with Object > Fill and Stroke.

**Comment by Nudin** [comment]
@mtoohey31 If you open a PR that adds the svg version to the doc folder, that would be great. The alternative versions may be better suited in the [vimwikiwiki](https://github.com/vimwiki/vimwikiwiki)-repo, so that we don't bloat this repo more than necessary.

**Comment by thecliguy** [comment]
@Nudin Do you need to accept the PR into the vimwikiwiki-repo, or is there another maintainer with permission to do this?

**Comment by tinmarino** [comment]
We are around 7 "mantainers" with the right to accept PRs but your last PR targets master and should target dev.
Not sure if you can change that, otherwise please create an other PR.

**Comment by thecliguy** [comment]
@tinmarino The [vimwikiwiki](https://github.com/vimwiki/vimwikiwiki) repo doesn't have a dev branch, only master.
