### ISSUE TITLE
Proposal: Improve Vimwiki and markdown coexistance

### ISSUE THREAD

**Issue by the42** [vimwiki/vimwiki#1091]
I have been using markdown extensivelly on my computer. Navigating between links and some minimal Todo-handling of vimwiki is a welcomed extension.

For newcomers vimwiki provides a great out of the box experience. Some other plugins, which are more focused on markdown, do an arguably better job when it comes eg. to syntax highlighting.

I would propose as an enhancement:

1. Vimwiki should either recognize existing plugins for markdown highlighting and leave highlighting to those plugins; or
1. provide some documentation how syntax highlighting of markdown files can be left to markdown plugins, even though the vimwiki syntax has been set to markdown.

Additional note: I achieved to use markdown syntax highlighting to use plasticboy/vim-markdown as simple as

`au FileType vimwiki setlocal syntax=markdown`

**Comment by brennen** [comment]
Please see #664 for ongoing Markdown work.
