### ISSUE TITLE
Search Default Wiki from Non-Wiki Page

### ISSUE THREAD

**Issue by atomdmac** [vimwiki/vimwiki#1095]
Is there a way to search the default wiki from a non-wiki page?  It looks like `:VWS` is only available when you have a wiki page open.

I'm hoping to use `vimwiki` primarily as a note-taking app and would like to be able to quickly find particular documents quickly without having to open the index first.

**Comment by brennen** [comment]
It doesn't look like it right now.

It might make sense to convert `:VimwikiSearch` to a global command that takes a count to specify the desired wiki, the way `:VimwikiIndex` does. I'm not sure how much effort that would entail, or whether it would be backwards-compatible with the current implementation.  If not, maybe it would make sense to implement a `:VimwikiGlobalSearch` or similar.

**Comment by tinmarino** [comment]
Closing <= Inactive question

Basiccally you can do it in 2 commands VimwikiIndex, and VimwikiGoto or Search, you can create a custom command if you want to reduce to one call.
