### ISSUE TITLE
[Question] Correct way to conceal HTML tags

### ISSUE THREAD

**Issue by mgarort** [vimwiki/vimwiki#1097]
- [ ] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.

Apologies if this is explained somewhere, but I have checked the documentation and past issues and I haven't found a solution to my problem. I use the native Vimwiki syntax, and the result of `:VimwikiShowVersion` is `Stable version: 2.5`. I haven't checked the `dev` branch because this is not really an issue, but more of a question.

What is the correct way to hide HTML tags? For example, if I write `<u>Text</u>` then `Text` is correctly identified as underlined and is displayed as such, but the tags `<u>` and `</u>` remain visible, which clutters my notes. I would like to hide them while maintaining the underlining, in a similar way to how `*Text*` and `_Text_` are displayed as bold and italic respectively, but `*` and `_` are hidden.

Based on issue #1012, I have tried to hide  `<u>` and `</u>` with `:syn match VimwikiConceal /<u>\|<\/u>/ conceal`. This hides the tags, but it also removes the underlining, which defeats the purpose of using underlining tags.

Thanks a lot in advance.

**Comment by brennen** [comment]
> I haven't checked the dev branch because this is not really an issue, but more of a question.

Based on a quick check of the `dev` branch vs. `master`, this appears to only work on `dev`.

I'm using the default for `g:vimwiki_conceallevel`.
