### ISSUE TITLE
Custom Keymaps Not Working

### ISSUE THREAD

**Issue by andybyers21** [vimwiki/vimwiki#1099]
## vimrc Settings

```vim
set nocompatible
filetype plugin on
syntax on

" Disable the creation of temporary wikis in all markdown files
let g:vimwiki_global_ext = 0

" give vimwiki access to all keymaps
let g:vimwiki_key_mappings = { 'all_maps': 1, }

" Set location & format
let g:vimwiki_list = [{'path': '~/Documents/Nota/2021_Notes/',
                      \ 'syntax': 'markdown', 'ext': '.md'}]

" add .md to markdown links
let g:vimwiki_markdown_link_ext = 1
```

## Environment

- NeoVim 0.4.4
- Mac OS Big Sur 11.2
- Vimwiki version 2.5, using markdown syntax

## Issue

When using vimwiki some custom keymaps don't seem to be working correctly. For example, none of the following execute in vimwiki but work in all other files:

```vim
nnoremap o o<Esc>
nnoremap O O<Esc>
map <Leader>o oO
map - $
```

However, the following maps for commands work fine:

```vim
nnoremap <Leader>p :bp<CR>
nnoremap <Leader>n :bn<CR>
nnoremap <Leader>f :bf<CR>
```

When I run `:verbose map <none working keymap>` I get the following output:

```shell
n  -            @<Plug>VimwikiRemoveHeaderLevel
        Last set from ~/.config/nvim/plugged/vimwiki/autoload/vimwiki/u.vim line 113
   -             $
        Last set from ~/.config/nvim/init.vim line 42
```

Following the u.vim file I find the following function but I am unsure of the functionality:

```vim
" a:mode single character indicating the mode as defined by :h maparg
" a:key the key sequence to map
" a:plug the plug command the key sequence should be mapped to
" a:1 optional argument with the following functionality:
"   if a:1==1 then the hasmapto(<Plug>) check is skipped.
"     this can be used to map different keys to the same <Plug> definition
"   if a:1==2 then the mapping is not <buffer> specific i.e. it is global
function! vimwiki#u#map_key(mode, key, plug, ...) abort
  if a:0 && a:1 == 2
    " global mappings
    if !hasmapto(a:plug) && maparg(a:key, a:mode) ==# ''
      exe a:mode . 'map ' . a:key . ' ' . a:plug
    endif
  elseif a:0 && a:1 == 1
      " vimwiki buffer mappings repeat mapping to the same <Plug> definition
      exe a:mode . 'map <buffer> ' . a:key . ' ' . a:plug
  else
    " vimwiki buffer mappings
    if !hasmapto(a:plug)
      exe a:mode . 'map <buffer> ' . a:key . ' ' . a:plug
    endif
  endif
endfunction,
```

**Comment by deepredsky** [comment]
if you map those vimwiki cmds to something else, your own custom mapping will work. for example

```
nmap <leader>v- <Plug>VimwikiRemoveHeaderLevel
```

**Comment by andybyers21** [comment]
Thanks, I'm not sure I understand though. I've tried unmapping the vimwiki default maps as per the docs but I'm not sure I'm getting the syntax right.

```vim
map - $ <Plug>VimwikiRemoveHeaderLevel
```

I've also tried unmapping on a seprate line which should init before the new maps but again vimwiki overides this and end's up doing both commands at the same time.

**Comment by deepredsky** [comment]
@andybyers21 

basically i m mapping the vimwiki function to some other mapping, thus relieving `-` to be mapped to another function

try

```
nmap XXX <Plug>VimwikiRemoveHeaderLevel
```

where XXX is some random mapping that you will never use. behind the scene vimwiki checks if this function is already mapped or not. and it it's already mapped it will not create the default map for this function

you can check what is currently `-` currently mapped to by using this

```
:verbose map -
```

example output

```
n  -             <Plug>VinegarUp
        Last set from ~/jd/vim/plugged/vim-vinegar/plugin/vinegar.vim line 32
```

hope this helps

**Comment by andybyers21** [comment]
Ah, now I get it, I was trying to do everything in one command. 

Command 1 = map vimwiki command to something else,
Command 2 = create your custom keymap.

Thanks again
