### ISSUE TITLE
Refactor tables

### ISSUE THREAD

**Issue by EinfachToll** [vimwiki/vimwiki#11]
So before again somebody else makes unnecessary effort and makes things I already did I'll share some thoughts on the tables in Vimwiki. The problems there are so far:
- when making big tables, Vim gets unusable slow (at least on my computer). The reason is the syntax definitions.
- as far as I can see the only effect of the syntax is to prevent that chars get concealed inside the table
- and that's because it is difficult to compute the width of a table cell if it contains concealed chars
- and then I want to have ─ and │ for the lines of the table because it looks better

So what I did is:
- when redrawing the table, replace - and | with ─ and │
- use synconcealed() and stuff to get the correct width of the table cells even when there are concealed chars. Was a bit complicated but feasible.
- throw away the syntax definitions

But there is a big drawback: visually selecting a column is nearly useless if there are concealed characters because what in fact gets visually selected is not what you expect. But that's Vim's fault, not mine.

The interested reader finds my current state here: https://github.com/EinfachToll/Vimwiki/tree/better-tables

**Comment by hq6** [comment]
@EinfachToll , It looks like you haven't updated `better-tables` in the last 6 years. 
Have the problems pointed out been addressed by #47 and later optimizations in your view?

**Comment by ranebrown** [comment]
I'm going to close this one for now since there have been some pretty good improvements made. It can always be reopened or a new issue created with more specifics.
