### ISSUE TITLE
Option to enable auto-change-dir when opening a wiki index page with <Leader>ww

### ISSUE THREAD

**Issue by t7ko** [vimwiki/vimwiki#110]
I'm using `CtrlP` plugin to quickly jump to vimwiki pages.  It requires that I change dir to wiki folder to start searching.  I'd like to add an option (I propose a global one) which, when enabled, forces vimwiki to do `:lcd wikidirectory` automatically when opening a wiki page with `<Leader>ww` and `<Leader>wt`.

**Comment by EinfachToll** [comment]
I looked at CtrlP some years ago and I think it has an option to specify some kind of root directory. But I might be wrong.

**Comment by t7ko** [comment]
@EinfachToll -- I have implemented it.  t7ko/vimwiki branch 'auto-cd'.  Let me know if you want me to create a pull request.

**Comment by EinfachToll** [comment]
Looks OK to me, so I think you can merge it into the dev branch. I don't know if it is easier for you to push the auto-cd branch to this repo and then merge it or directly put the commits onto the dev branch somehow. Well, whatever :)

**Comment by t7ko** [comment]
Did it through pull request #113  -- looks like the easiest way, and consistent with other merges.
