### ISSUE TITLE
Can we use your keybindings with Rmarkdown/RMD

### ISSUE THREAD

**Issue by shahid777-py** [vimwiki/vimwiki#1101]
I know this plugin can be used with markdown/md , i need that checkbox Toggling keybind, im so used to it with vimwiki. So is there anything i can do to get this done in rmd as well.

I tried one plugin called checkbox.vim it cant work with <C-Space> but ur plugin is woking perfectly well whats the magic.

**Comment by ranebrown** [comment]
You could create your own function and command/mapping based on the vimwiki code (links below). Easier method might be to register the rmd extension `:h vimwiki-register-extension`

[command](https://github.com/vimwiki/vimwiki/blob/61a6ce668621359056d4b252ca8fbc6d1e3d2534/ftplugin/vimwiki.vim#L335)
[plug key map](https://github.com/vimwiki/vimwiki/blob/61a6ce668621359056d4b252ca8fbc6d1e3d2534/ftplugin/vimwiki.vim#L462-L463)
[default key map](https://github.com/vimwiki/vimwiki/blob/61a6ce668621359056d4b252ca8fbc6d1e3d2534/ftplugin/vimwiki.vim#L462-L465)
[function](https://github.com/vimwiki/vimwiki/blob/61a6ce668621359056d4b252ca8fbc6d1e3d2534/ftplugin/vimwiki.vim#L462-L465)

**Comment by ranebrown** [comment]
It would probably work to put something like `nnoremap <C-space> :call vimwiki#lst#toggle_cb(line('.'), line('.'))<CR>` in your vimrc if you have vimwiki installed. That would cause autoload functions to load.

**Comment by shahid777-py** [comment]
> You could create your own function and command/mapping based on the vimwiki code (links below). Easier method might be to register the rmd extension `:h vimwiki-register-extension`
> 
> [command](https://github.com/vimwiki/vimwiki/blob/61a6ce668621359056d4b252ca8fbc6d1e3d2534/ftplugin/vimwiki.vim#L335)
> [plug key map](https://github.com/vimwiki/vimwiki/blob/61a6ce668621359056d4b252ca8fbc6d1e3d2534/ftplugin/vimwiki.vim#L462-L463)
> [default key map](https://github.com/vimwiki/vimwiki/blob/61a6ce668621359056d4b252ca8fbc6d1e3d2534/ftplugin/vimwiki.vim#L462-L465)
> [function](https://github.com/vimwiki/vimwiki/blob/61a6ce668621359056d4b252ca8fbc6d1e3d2534/ftplugin/vimwiki.vim#L462-L465)

Thanks the file type extension registering works, but i dont know why that `nnoremap <C-space> :call vimwiki#lst#toggle_cb(line('.'), line('.'))<CR>` didn't work , by the way thanks, but one thing becuase of vimwiki treating rmd as md they syntax highlighting was lost, i tried to create  a function specifically for checkbox toggling but why on earth i can't map <C-Space>/<C-@>/<Nul> but it's only working in ur plugin.Thanks any way any suggestion would be great.

**Comment by shahid777-py** [comment]
> It would probably work to put something like `nnoremap <C-space> :call vimwiki#lst#toggle_cb(line('.'), line('.'))<CR>` in your vimrc if you have vimwiki installed. That would cause autoload functions to load.

i dont why this mapping isn't working

**Comment by shahid777-py** [comment]
`nnoremap <silent><script><buffer><C-space> :call vimwiki#lst#toggle_cb(line('.'), line('.'))<CR>`
mapping like this solved my issue. thanks i think it has to do with `<C-Space>` keybind  specifically in vim/neovim or maybe oven terminal issue. thanks for the aweosme plugin.
