### ISSUE TITLE
[QUESTION] What does <D-CR> mean?

### ISSUE THREAD

**Issue by mgarort** [vimwiki/vimwiki#1102]
- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.

Apologies if this is explained somewhere, but I have checked the documentation and past issues and I haven't found an explanation. I use the native Vimwiki syntax, and the result of `:VimwikiShowVersion` is `Stable version: 2.5`.

What is the meaning of `<D-CR>`? It is listed under `vimwiki_<C-S-CR>` and  `vimwiki_<D-CR>` as a keybinding for `<Plug>VimwikiTabnewLink`. Searching `:h <D>` leads nowhere. Based on the context, is `<D-CR>` just `<C-S-CR>`?

Thanks.

**Comment by deepredsky** [comment]
It's `Command` key for map

try

```vim

:help <D-
```

**Comment by mgarort** [comment]
I see! Thanks, I couldn't find this anywhere. I had searched for `<D>` but it didn't occur to me to search `<D-`.
