### ISSUE TITLE
Manual installation failed (while other plugins work that way)

### ISSUE THREAD

**Issue by TravelTrader** [vimwiki/vimwiki#1104]
As it is written `:help vimwiki` for example does not work.
My steps:

1. unzipped zipfile in bundle subfolder
2. added the 3 lines in `.vimrc`
3. added `set runtimepath^=~/.vim/bundle/vimwiki-2.5` in `.vimrc`

But it does not work.
I used vimwiki 2.5, vim 8.0 and `:VimwikiShowVersion` outputs that it's not an editor command.
Would be great if anybody could help.

**Comment by deepredsky** [comment]
Make sure you have these settings in your vimrc file: >
    set nocompatible
    filetype plugin on
    syntax on

Without them Vimwiki will not work properly.

**Comment by tinmarino** [comment]
The bundle solution is for old version of vim.
Try the git solution (supposing you are using vim > 7.4 on any Linux):

```vim
git clone https://github.com/vimwiki/vimwiki.git ~/.vim/pack/plugins/start/vimwiki

# to generate documentation i.e. ':h vimwiki'
vim -c 'helptags ~/.vim/pack/plugins/start/vimwiki/doc' -c quit
```

Also you must run the `helptags` command to visit the help files. This must be run from vim if the `runtimepath` contains vimwiki.
Cloning vimwiki in ~/.vim/pack/plugins/start/vimwiki will automatically add it to the `runtimepath`

In the end, this is the file that must be sourced: https://github.com/vimwiki/vimwiki/blob/master/plugin/vimwiki.vim

**Comment by TravelTrader** [comment]
Thanks for the detailed help @tinmarino!
I got it running. It was mainly that I just tested the help and vimwiki was already running but I had to implement the help.
