### ISSUE TITLE
Line formatting is slow with markdown syntax

### ISSUE THREAD

**Issue by idnsunset** [vimwiki/vimwiki#1109]
Prior to submitting a new issue make sure to complete these steps:

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.

I am using markdown format and set the following in `~/.vim/after/ftplugin/vimwiki.vim` to gain better markdown syntax highlighting.

```
au BufEnter *.md setl syntax=markdown
```

But I got considerable lag when performing `qgip` to format a paragraph. After removing this autocmd, the issue is gone. Please advice what vimwiki is actually doing from behind in such case and how to work it around?

The output of `:VimwikiShowVersion`:

```
OS: Linux
Version: 802
Branch: dev
Revision: db85dc5
Date: 2021-03-15 15:19:42 -0300
```

**Comment by brennen** [comment]
> Please advice what vimwiki is actually doing from behind in such case and how to work it around?

I know a lot of people are probably doing something like this, but I don't think we can treat this as a supported configuration.  This is not likely to be a bug in vimwiki as-shipped.

I'll note briefly that I wasn't able to reproduce this problem in a relatively simple Markdown file using either the default vim `markdown` syntax or `plasticboy/vim-markdown`, so you may have other configuration slowing things down, or the complexity of the file may be a factor.
