### ISSUE TITLE
Links completion with c-x c-o  breaks after local-dir is changed

### ISSUE THREAD

**Issue by t7ko** [vimwiki/vimwiki#111]
* Open wiki.
* Type `[[<c-x><c-o>`, watch results -- completion list shows link names allright.
* Perform `:lcd %:p:h`
* Try `<c-x><c-o>` again -- it produces some ugly paths instead of page names!  On Windows, paths seem to be generated by a following pattern: repeated `../` to get to the upmost level, then adds full wiki path, then page name.

**Comment by t7ko** [comment]
More specific steps:
* Start gvim
* Open wiki page (in my case it's index of wiki number 2, accessed with `2\ww`
* `:echo vimwiki#base#get_wikilinks(1)`  -- here 1 is wiki NR minus one
* `:lcd %:p:h`
* `:echo vimwiki#base#get_wikilinks(1)`  -- here 1 is wiki NR minus one

Last step prints out those bad paths instead of wiki links.

**Comment by t7ko** [comment]
Turns out, the problem is, after `:lcd` `wikify_path` returns path with drive letter upcased (Windows), while wiki config contains driver letter in lower case.

**Comment by t7ko** [comment]
What I'll do is I'll fix `vimwiki#path#relpath()` to work the same way as `vimwiki#path#path_common_pfx()`.  Which is: ignore case when comparing paths.  This is not correct on *nix platforms, of course.  But it is an easy fix and is compatible with other functions so I guess it's ok.

**Comment by t7ko** [comment]
See pull request #112.

**Comment by EinfachToll** [comment]
>This is not correct on *nix platforms, of course. But it is an easy fix and is compatible with other functions so I guess it's ok.

Errr, that's a pretty bad justification. At the moment, I have no Windows machine available, so I can not see it, but do I understand you right that 

    :echo expand('%:p:h')

produces different output (letter case) at different times? If it has nothing to do with Vimwiki, then it's a bug in Vim, isn't it?

**Comment by t7ko** [comment]
@EinfachToll - you are right, this is the thing with Vim.  But, strictly speaking, this is not a bug -- just a "strange" behaviour.  Since Windows ignores cases in paths, `d:\` and `D:\` are considered equivalent on the OS level.  Doing `cd d:\` and `cd D:\` produces the same result.  AFAIK, Windows on the OS level does not promise you to preserve the letter case in paths you use on their creation, nor it promises to always return you the same letter case in paths.  (Even though it does that most of the time.)  It is an app's responsibility to handle this awful mess with case insensitivity.  Vim does not have built-in functions to compare paths which would account for the OS specific and do it case sensitive/insensitive depending on the OS.  So, vimwiki would have to implement it.

**Comment by EinfachToll** [comment]
Come on, ugly code is no excuse for bugs in a program. Yeah, nobody said it's easy to write proper vimscript ;)
I think, a function in path.vim which compares a string either ignoring case if and only if on Windows should do the trick. Although that makes code using this function very verbose.

**Comment by t7ko** [comment]
@EinfachToll -- Check out the #112, last checkin does proper comparison.

**Comment by EinfachToll** [comment]
Ok, so, does it work for you now? As I said, I can't test it.

**Comment by t7ko** [comment]
Yes, tested it; with #112 completion works fine, I'll close this issue now.
