### ISSUE TITLE
Is there a way to color a certain cell within a table?

### ISSUE THREAD

**Issue by rifazn** [vimwiki/vimwiki#1121]
Can I color/highlight particular cells within tables? I think editing the default html template might be part of the way to go, but I can't figure the whole thing out.

**Comment by brennen** [comment]
I'm not aware of anything builtin that's table-specific.  It looks like you might be able to use `<span>` tags - see `:help :VimwikiColorize` and `:help g:vimwiki_valid_html_tags`.  I had to add `<span>` to the list of valid tags, and it's a bit weird that there's a command to generate `<span>` tags but they don't get passed through as raw html by default, but anyway:

I set the following in my `.vimrc`:

```vim
    let g:vimwiki_valid_html_tags = 'b,i,s,u,sub,sup,kbd,br,hr,span'
```

Then wrote a table like so:

```
| foo | bar                                             |
| boo | <span style="background-color: red;">baz</span> |
```

Which, rendered, gives:

![Screenshot-2021-05-19-23:27:00](https://user-images.githubusercontent.com/74990/118924075-cec02b00-b8f9-11eb-8712-e0b6557444fa.png)

This is a dirty hack, but sort of works. There might be other ways if you write your own custom CSS (see `:help vimwiki-option-css_name`); my CSS is rusty at best, and it's gotten a lot more capable in recent years.  But we don't (that I know of) have a way to do something like specify a class for an individual table row/cell.

Anyway, I think probably at the point where people want this level of control over table markup, it'd be easier to use something like the verbatim/passthrough syntax proposed in #1045 (once that's implemented) and just write raw HTML.  Offering this kind of thing in lightweight wiki markup always winds up re-implementing everything the HTML syntax provides, but less consistently and with weird gotchas.

(If you're using Markdown syntax, well, you might already get HTML passthrough for free, depending on how you're rendering the Markdown - but passing through HTML is the original default behavior, and a lot of Markdown interpreters do so, or can be made to do so.)
