### ISSUE TITLE
Invalid expression error using 'markdown' syntax.

### ISSUE THREAD

**Issue by etiennekintzler** [vimwiki/vimwiki#1129]
On the last dev version, i have the following error when opening vimwiki (using `vim +'VimwikiIndex'` or `<leader>ww`) : 

```vim
Error detected while processing function vimwiki#vars#get_global:
line    1:
E716: Key not present in Dictionary: schemes_local
E15: Invalid expression: g:vimwiki_global_vars[a:key]
```

The .vimrc part related to vimwiki

```vim
" vim wiki path
let g:vimwiki_list = [{'path' : 'PATH/TO/DIR', 'ext': '.md', 'syntax': 'markdown'}]
let g:vimwiki_global_ext = 0
```

The output of the `:VimwikiShowVersion` : 
```bash
Os: Linux
Vim: 800
Branch: dev
Revision: 8fef79b
Date: 2021-05-20 14:50:10 -0500
```

Note that the error disappears when I remove `'syntax': 'markdown'` from my `.vimrc` file (however I loose markdown highlight).

**Comment by tinmarino** [comment]
vim -u vimrc -N +'VimwikiIndex'   # works for me with vimrc:

```vim
let g:vimwiki_list = [{'path' : '/home/tourneboeuf/Test/Wiki', 'ext': '.md', 'syntax': 'markdown'}]
let g:vimwiki_global_ext = 0
packadd wiki
```

**Comment by etiennekintzler** [comment]
Thank @tinmarino 

I try your instruction (without `packadd wiki` which raises another error) and it works.

I proceed by difference with my actual `.vimrc` and realized that the error disappears when I remove the following line (related to vimwiki plug) in my .vimrc:

```vim
Plug 'vimwiki/vimwiki'
```

I have no idea why it's the case, as the other Plug don't raise any error, nor this error is present when I don't add 'syntax':'markdown'`.

Any idea ?

**Comment by tinmarino** [comment]
Hi @etiennekintzler,

Sry, please replace `packadd wiki` by `packadd vimwiki` <= I remove the `vim` prefix of the directory name of my plugins.
I'll have a look statically anyway to see in which case `schemes_local` can be undefined.

**Comment by tinmarino** [comment]
It is important to `packadd vimwiki` or `Plug vimwiki` __after__ the configuration. These comands both `source vimwiki/plugin/vimwiki.vim` wich will deriver many `vimwiki` internal variable from those user configs. (i still did not have a look :-).

**Comment by etiennekintzler** [comment]
I **reinstalled vimwiki** (using Vim Plug) after deleting folders `.vim/pack/plugins/start/vimwiki/` and `.vim/plugged/vimwiki`.

It solved the problem.

**Comment by tinmarino** [comment]
Glad it worked @etiennekintzler!

That is what I was starting to think: incoherent plugin file due to a bad instalation, say a bad git checkout.

Have a nice day!

**Comment by etiennekintzler** [comment]
Thanks again for your help @tinmarino 

I think that the issue happens when I install the `dev` version. I might not have removed/cleaned the standard install first.

Have a nice day as well :)
