### ISSUE TITLE
Proposed: Migrate official IRC from freenode to libera.chat

### ISSUE THREAD

**Issue by brennen** [vimwiki/vimwiki#1131]
Due to recent changes in Freenode management, the migration of staff to libera.chat, and the general [mass exodus](https://github.com/siraben/freenode-exodus) of most responsible FOSS projects, I think it's probably time to close `#vimwiki` on Freenode.

I've registered `#vimwiki` on irc.libera.chat as a placeholder, and can add founder access to the channel for other maintainers.  It sounds like Matrix bridging is now available: https://fosstodon.org/@liberachat/106320476905973945

cc: @Nudin as founder of channel on Freenode and admin of `#vimwiki:matrix.org`.

**Comment by brennen** [comment]
cc: @vimwiki/maintainer in general.

**Comment by Nudin** [comment]
I have no problem with that in general! Do you know how synchronization works, do we also need to ask all people in the matrix room to move to a new matrix room?

**Comment by brennen** [comment]
Good question - I'll dig into this.

**Comment by brennen** [comment]
Ok, so I didn't actually do anything, but the `#vimwiki:libera.chat` room bridge is now working on Matrix:

https://app.element.io/#/room/#vimwiki:libera.chat

I'm not entirely clear on this - as an admin of the existing room, can you relinquish the existing `#vimwiki:matrix.org` address and then we can repurpose it and ask people to move?  If not, I suppose we should just proceed directly to the asking-people-to-move step.

**Comment by Nudin** [comment]
I can remove the `#vimwiki:matrix.org` adress from the old room, then it should be possible to add it to the new. Either you give me admin rights for the new channel or you add it, but then we should to coordinate to avoid someone stealing the name in between. ;)
However, at least currently I cannot join the new room `#vimwiki:libera.chat` – maybe it's just a temporary bug – will check again in the next days.

**Comment by brennen** [comment]
> However, at least currently I cannot join the new room #vimwiki:libera.chat – maybe it's just a temporary bug – will check again in the next days.

It's currently working for me, at least in the desktop web app.

I wonder does it work if you use https://app.element.io/#/room/!GIznXKZtWCcuKpZdbK:libera.chat ?

**Comment by thecliguy** [comment]
@Nudin Hello Nudin, can #1167 be applied to master without needing to wait for the next release of VimWiki?

**Comment by Nudin** [comment]
> @Nudin Hello Nudin, can #1167

From my side: sure, go for it.

Sorry for the late reply…
