### ISSUE TITLE
[markdown]: `g:vimwiki_markdown_link_ext = 1` doesn't seem to work properly

### ISSUE THREAD

**Issue by hkupty** [vimwiki/vimwiki#1136]
Hi. I'm trying to integrate vimwiki/taskwiki to my workflow and the idea is that in my index page I set up an actual index for my "subprojects".

I followed up what was described in [this video](https://www.youtube.com/watch?v=A1YgbAp5YRc), which I assume is a bit outdated but still within the `dev` branch.

However, it seems to me that links in markdown doesn't seem to be working as described. If I create a link from vimwiki, it links using the default `[[Personal]]` syntax. If I try to create a folder and add them, for example `[Journal](diary/diary.md)` that doesn't seem to work, as shown in the attached picture:
![image](https://user-images.githubusercontent.com/2695819/121049238-cf8d0400-c7b7-11eb-94e2-8ccd8276a1e2.png)

I've added the configuration flag in my default config file and, since it didn't work, I created a ftplugin file and added it there as well, but none seem to make any effect.

Since I saw it working in the video, I guess I missed some configuration, but then I would expect documentation to tell me so. If that is all configuration I need, then it feels like this is a bug.

As implied by my configuration below, I'm using neovim, built from master.

---

`ftplugin/vimwiki.vim`
```
let g:vimwiki_markdown_link_ext = 1

nmap <silent> _ <Plug>VimwikiRemoveHeaderLevel
```

`lua/config.lua`
```
vim.g.vimwiki_list = {
  {
    path = "/opt/code/wiki/",
    index = "main",
    sytax = "markdown",
    ext = "md",
    auto_diary_index = 1,
    auto_toc = 1,
    auto_generte_links = 1
  }
}

vim.g.vimwiki_ext2syntax = {
  ['.md'] = 'markdown',
  ['.markdown'] = 'markdown',
  ['.mdown'] = 'markdown',
}

vim.g.vimwiki_markdown_link_ext = 1
vim.g.taskwiki_markup_syntax = 'markdown'
vim.g.markdown_folding = 1
```

`:VimwikiShowVersion`
```
Os: Linux
Vim: 800
Branch: dev
Revision: 8fef79b
Date: 2021-05-20 14:50:10 -0500
```

```
:version
NVIM v0.5.0-dev+1384-gf2906a466
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=native -O2 -pipe -fno-exceptions     -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS     -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -flto -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -Og -g
 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOA
T32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/opt/code/aur/neovim-git/src/build/config -I/opt/code/aur/neovim-git/src/neovim-git/src -I/usr/include -I/opt/code/aur/neovim-git/src/build/src/nvim/auto -I/opt/code/aur/neovim-git/src/build/include
Compiled by hkupty

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by brennen** [comment]
Haven't tried to reproduce, but I do note a typo here:

```
 sytax = "markdown",
```

**Comment by tinmarino** [comment]
Thanks @brennen , I think that was it.
