### ISSUE TITLE
vimwiki now supported in cobalt.rs static site generator

### ISSUE THREAD

**Issue by chipsenkbeil** [vimwiki/vimwiki#1137]
https://github.com/cobalt-org/cobalt.rs/pull/866

We have a couple of places where we list out 3rd party projects that support vimwiki or are related to vimwiki. Is there one we want to use as a source of truth? Personally, I think having them listed in the README would be easiest to see.

Was told to make a [wiki page here](https://github.com/vimwiki/vimwiki/wiki/Plugins-and-Tools) awhile back when I started working on the Rust impl, but looks like our wiki is deprecated in favor of the main website. If that's the case, shouldn't we remove the wiki tab in the settings of this repo?

**Comment by tinmarino** [comment]
Hi @chipsenkbeil,

I keep prefering the github/wiki of this project, at least for fast edition by any user.
If you want to make it more persistent, the oficial doc should be there: https://github.com/vimwiki/vimwiki.github.io but was not really maintained due to the scaryness of the word: "offical".

Cheers,

**Comment by tinmarino** [comment]
I added the reference to the github wiki of this page. It is easily editable so we can close this.

@chipsenkbeil, I understand the official site is better. But for time being, it is faster to add here and then at each release, we will copy the lines of the wiki to the github.io.

I am expecting many additions to the related plugins so better have a easyly editable (by all user) page. That is what other project do (even if that last is a bad argument lol).

See you.

**Comment by chipsenkbeil** [comment]
@tinmarino sounds fine. Was more asking what to do rather than dictating, so the wiki is fine with me :)

**Comment by tinmarino** [comment]
@chipsenkbeil you were right to ask for clarification. Nice to see we agree on:
1. https://github.com/vimwiki/vimwiki/wiki
2. https://vimwiki.github.io/vimwikiwiki/Related%20Tools.html

**Comment by floZx** [comment]
t
,l
