### ISSUE TITLE
documentation for syntax highlights

### ISSUE THREAD

**Issue by sainivasmangu** [vimwiki/vimwiki#1143]
I am trying to add the syntax highlights of Vimwiki to a colorscheme. I saw the `syntax/vimwiki.vim` file and wanted to ask if there is a place where I can find some documentation regarding what these highlights "highlight". I'm new to this so maybe go easy on me. Thanks in advance.

**Comment by tinmarino** [comment]
Hello @sainivasmangu.

Vim is matching syntax elements with the syntax command (`:h syntax`) and then map these name group (VimwikiComment) to some common groups (Comment) at the end of [syntax/vimwiki.vim](https://github.com/vimwiki/vimwiki/blob/212a66fcd69f342a848ba93642aa89f856386170/syntax/vimwiki.vim#L379).

Those names syntax elements get their color with the highlight command (`:h hi`)  in a colorsheme file like `$VIMRUNTIME/colors/pablo.vim` (i.e. not in vimwiki).
I personally use [gruvbox](https://github.com/morhetz/gruvbox) colorsheme.

I hope that anwaer your question.

**Comment by sainivasmangu** [comment]
That clarified my doubts. I still wanna know what `VimwikiMarkers` are... thanks for the reply :)

**Comment by tinmarino** [comment]
Well they are the Vimwiki markers hahaha, just kidding.
We use it for the delimiters like `__` for bold. Usually they will be
concealed but in case its are not (see concellevel), its are colorified as
Nomal text.

```
$ rg VimwikiMarker
syntax/vimwiki.vim
379:hi def link VimwikiMarkers Normal
462:hi def link VimwikiEqInChar VimwikiMarkers
463:hi def link VimwikiCellSeparator VimwikiMarkers
464:hi def link VimwikiBoldChar VimwikiMarkers
465:hi def link VimwikiItalicChar VimwikiMarkers
466:hi def link VimwikiBoldItalicChar VimwikiMarkers
467:hi def link VimwikiItalicBoldChar VimwikiMarkers
468:hi def link VimwikiDelTextChar VimwikiMarkers
469:hi def link VimwikiSuperScriptChar VimwikiMarkers
470:hi def link VimwikiSubScriptChar VimwikiMarkers
471:hi def link VimwikiCodeChar VimwikiMarkers
472:hi def link VimwikiHeaderChar VimwikiMarkers
475:hi def link VimwikiEqInCharT VimwikiMarkers
476:hi def link VimwikiBoldCharT VimwikiMarkers
477:hi def link VimwikiItalicCharT VimwikiMarkers
478:hi def link VimwikiBoldItalicCharT VimwikiMarkers
479:hi def link VimwikiItalicBoldCharT VimwikiMarkers
480:hi def link VimwikiDelTextCharT VimwikiMarkers
481:hi def link VimwikiSuperScriptCharT VimwikiMarkers
482:hi def link VimwikiSubScriptCharT VimwikiMarkers
483:hi def link VimwikiCodeCharT VimwikiMarkers
484:hi def link VimwikiHeaderCharT VimwikiMarkers
```

**Comment by sainivasmangu** [comment]
thanks for clarifying. i am almost done with my changes. gotta make some aesthetic decisions with my artistically challenged brain now ;)

**Comment by sainivasmangu** [comment]
@tinmarino I did it and it's all thanks to you!

https://github.com/ChristianChiarulli/nvcode-color-schemes.vim/pull/44
