### ISSUE TITLE
neovim snippet support for mardown files

### ISSUE THREAD

**Issue by Vanderscycle** [vimwiki/vimwiki#1148]
Prior to submitting a new issue make sure to complete these steps:

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.

dev has g:vimwiki_global_ext which allow for all .md to be treated as a mini wiki but if that's the case my problem is expanding.

- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`

My vimwiki config inside my plugins.lua from my [dotfiles](https://github.com/Vanderscycle/dot-config/tree/main/nvim)
```lua
use {
    'vimwiki/vimwiki',
    config = function()
        vim.g.vimwiki_global_ext = 0
        vim.g.vimwiki_list = {
            {
                auto_export =  1,
                path_html = '~/Documents/dotFiles/obsidian/',
                path = '~/Documents/dotFiles/obsidian/',
                syntax = 'markdown',
                ext = '.md',
            }
        }
    end
}
```
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.

I am trying to use snippets as part of my vimwiki workflow.

Here's a video of what I am experiencing.
[![asciicast](https://asciinema.org/a/2VrDBWK98RKBrTHpujVF4ufOG.svg)](https://asciinema.org/a/2VrDBWK98RKBrTHpujVF4ufOG)

- [x] Include the output of `:VimwikiShowVersion`.
```
Stable version 2.5
```

First, I'd like to start that I absolutely love vimwiki and that it has greatly helped me become more focused.

I save my vimwiki files inside the obsidian folder that I also use with obsidian for its mind map interface. I am trying to use mardown snips as a way to template my entries with vimwiki, but can't seem to do so inside the vimwiki folder for some reason. 

My config is mainly centered around neovim and its usage of lsp.

The video was for showing snips. Vimwiki has vimwikitables which works very well and is what I use for markdown tables.

Thank you for reading

**Comment by tinmarino** [comment]
Include the other plugin before vimwiki. I guess you want another behavior pressing `<Tab>`. You can get the current vim mapping with
```
:verbose map <Tab>
```
If it is from vimwiki like: 
```
n  <Tab>        @<Plug>VimwikiNextLink
        Last set from ~/.vim/pack/bundle/opt/wiki/autoload/vimwiki/u.vim line 225
Press ENTER or type command to continue
```
It is the normal behavior, vimwiki mapped the key `<tab>` as there were no mapping (see  [vimwiki#u#map_key](https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/autoload/vimwiki/u.vim#L101-L116)).
But if <Tab> is already mapped, vimwiki will not map it. It may have changed between master and dev. The idea now is to not interfere with other plugin but othe plugins do the same thing (or ot) so the oder of plugin sourcing matters a lot.  

Hope that helps.

**Comment by Vanderscycle** [comment]
@tinmarino 

Thank you for getting back to me. I think its a bit clearer and makes now makes me wonder what choice to take using the tab key.

Tab is indeed mapped nvim compe in my settings. Calling :verbose returned the following.
```vim
n  <Tab>       * <Cmd>BufferLineCycleNext<CR>
        Last set from ~/.config/nvim/init.lua
s  <Tab>       * v:lua.tab_complete()
        Last set from ~/.config/nvim/init.lua
```
I found issue #622 to be very helpful as it allowed to create a template folder and call from it using :r . Also, I noticed that tab and shift tabs allows me to jumps between wiki pages links which is actually really usefull for navigating.

>Include the other plugin before vimwiki.

I have some lazy loading going on so not everything is loaded at the same time. Please find the resuilt of one of the test from vim-startuptime.
```
  000.011  000.011: --- NVIM STARTING ---
  000.307  000.296: locale set
  000.667  000.360: inits 1
  000.690  000.023: window checked
  000.698  000.007: parsing arguments
  000.798  000.101: expanding arguments
  000.847  000.049: inits 2
  001.564  000.716: init highlight
  036.493  034.822  034.822: sourcing /home/henri/.config/nvim/init.lua
  036.504  000.119: sourcing vimrc file(s)
  046.797  000.017  000.017: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/vim-fugitive/ftdetect/fugitive.vim
  047.490  010.939  010.921: sourcing /usr/share/nvim/runtime/filetype.vim
  047.901  000.053  000.053: sourcing /usr/share/nvim/runtime/ftplugin.vim
  048.319  000.049  000.049: sourcing /usr/share/nvim/runtime/indent.vim
  049.220  000.426  000.426: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
  049.669  000.948  000.521: sourcing /usr/share/nvim/runtime/syntax/synload.vim
  049.799  001.145  000.198: sourcing /usr/share/nvim/runtime/syntax/syntax.vim
  051.473  000.024  000.024: sourcing /usr/share/nvim/runtime/plugin/gzip.vim
  051.507  000.015  000.015: sourcing /usr/share/nvim/runtime/plugin/health.vim
  051.623  000.100  000.100: sourcing /usr/share/nvim/runtime/plugin/man.vim
  051.659  000.018  000.018: sourcing /usr/share/nvim/runtime/plugin/matchit.vim
  051.698  000.019  000.019: sourcing /usr/share/nvim/runtime/plugin/matchparen.vim
  051.742  000.026  000.026: sourcing /usr/share/nvim/runtime/plugin/netrwPlugin.vim
  051.966  000.015  000.015: sourcing /home/henri/.local/share/nvim/rplugin.vim
  051.975  000.215  000.201: sourcing /usr/share/nvim/runtime/plugin/rplugin.vim
  052.141  000.151  000.151: sourcing /usr/share/nvim/runtime/plugin/shada.vim
  052.211  000.041  000.041: sourcing /usr/share/nvim/runtime/plugin/spellfile.vim
  052.262  000.026  000.026: sourcing /usr/share/nvim/runtime/plugin/tarPlugin.vim
  052.300  000.017  000.017: sourcing /usr/share/nvim/runtime/plugin/tohtml.vim
  052.348  000.028  000.028: sourcing /usr/share/nvim/runtime/plugin/tutor.vim
  052.404  000.027  000.027: sourcing /usr/share/nvim/runtime/plugin/zipPlugin.vim
  061.205  000.177  000.177: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/autoload/mkdp/util.vim
  445.269  392.775  392.598: sourcing /home/henri/.config/nvim/plugin/packer_compiled.lua
  445.577  003.406: loading plugins
  446.248  000.240  000.240: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/galaxyline.nvim/plugin/galaxyline.vim
  450.786  004.369  004.369: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/lightspeed.nvim/plugin/lightspeed.vim
  451.331  000.284  000.284: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/plugin/mkdp.vim
  451.606  000.039  000.039: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/nvim-bufferline.lua/plugin/bufferline.vim
  451.844  000.072  000.072: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/nvim-lspinstall/plugin/lspinstall.vim
  452.065  000.058  000.058: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/nvim-web-devicons/plugin/nvim-web-devicons.vim
  452.339  000.051  000.051: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/plenary.nvim/plugin/plenary.vim
  452.722  000.033  000.033: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/todo-comments.nvim/plugin/todo.vim
  453.039  000.158  000.158: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/trouble.nvim/plugin/trouble.vim
  455.590  002.390  002.390: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/vim-fugitive/plugin/fugitive.vim
  455.735  000.017  000.017: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/vim-fugitive/ftdetect/fugitive.vim
  456.632  000.534  000.534: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/vimwiki/autoload/vimwiki/vars.vim
  458.978  000.142  000.142: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/vimwiki/autoload/vimwiki/u.vim
  463.363  007.523  006.847: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/vimwiki/plugin/vimwiki.vim
  463.590  000.026  000.026: sourcing /home/henri/.local/share/nvim/site/pack/packer/start/which-key.nvim/plugin/which-key.vim
  463.823  002.986: loading packages
  464.113  000.289: loading after plugins
  464.146  000.033: inits 3
  464.153  000.007: reading ShaDa
  464.179  000.026: clearing screen
  464.549  000.370: opening buffers
  464.599  000.050: BufEnter autocommands
  464.612  000.013: editing files in windows
```

**Comment by tinmarino** [comment]
Hi @Vanderscycle, I expected some VimwikiCommand in your map output. Otherwise, the problem is not from vimwiki. Are you sure you runned the command in the same condition that where you see the bug?

You must follow the <Tab> mapping from the init to the problem, I am not expert with your [lua mapping configuration](https://github.com/Vanderscycle/dot-config/blob/main/nvim/lua/mappings.lua#L91-L96). Try to
* Reproduce the problem
* Send me the `verbose map <Tab>` output at this moment and the one you would expect
* Remove your lua conf, see if that changes.

Comment: I did not know about [markdown-preview](https://github.com/iamcco/markdown-preview.nvim), it seems nice but doeas it take 0.5 second of your real time before editing in Vim ? It seems that you must wait for its load because editing a markdown file, is that it ?

**Comment by CalvoUTN** [comment]
@Vanderscycle hey! I'm having the same problem. Can you explain a bit how you solved it?

**Comment by CalvoUTN** [comment]
So I dug a lot about what was happening. In my case, I was using luasnip. Apparently, even tho it's labeled as a ".md" file, my plugin was detecting it like a "vimwiki" file. I had to "extend" the plugins to this type of file:

https://github.com/L3MON4D3/LuaSnip/issues/161

In LuaSnip you do it like this:

`require("luasnip").filetype_extend("vimwiki", {"markdown"}`

Hope it helps someone!
