### ISSUE TITLE
Links to other parts of the file?

### ISSUE THREAD

**Issue by marlun** [vimwiki/vimwiki#115]
Is it possible to create links on the top of a wiki file to parts further down?

**Comment by EinfachToll** [comment]
Yes, if you use the dev branch of this repository. You may want to take a look at `:h vimwiki-anchors` and `:h vimwiki-toc`.

**Comment by marlun** [comment]
I'm not currently, was hoping the new version would come out but no worries, I'll try the dev branch, thanks! :smile:
