### ISSUE TITLE
vimwiki opens index in wrong directory?

### ISSUE THREAD

**Issue by molleweide** [vimwiki/vimwiki#1150]
Hi,

Why is vimwiki opening index with ,ww under ~/notes/vimwiki.index and not under ~/vimwiki/vimwiki.index?
If i edit a markdown file under notes/ then it does not open index under ~/vimwiki/

**Comment by sinarf** [comment]
Hello, 

It could be because you set it up that way. 

Did you add some config to your vim ? Something that might look like this : 

```vim
let g:vimwiki_list = [{'path': '~/notes/',
  \ 'syntax': 'markdown', 'ext': '.md'}]
```

**Comment by sinarf** [comment]
Since OP doesn't answer I think this issue can be closed.

**Comment by brennen** [comment]
Thought this might duplicate #1149, but seems sort of like the inverse problem.

**Comment by brennen** [comment]
@molleweide it's not clear what's happening here without seeing your configuration.  Please paste your `.vimrc` and the output of `:VimwikiShowVersion`.

**Comment by joshgubler** [comment]
I had the same problem and stumbled across this issue. `g:vimwiki_global_ext = 0` solved it for me. In my opinion, 0 should be the default value for this setting. Not every Markdown file should be treated like a wiki.

To replicate the issue:
```
 let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]
 ```

-  cd someOtherDirectory
- vim README.md
- leader ww

opens `someOtherDirectory/index.md`, but I expect it to open `~/vimwiki/index.md`.

If anybody else has this issue, read:
```
:help g:vimwiki_global_ext
```

**Comment by molleweide** [comment]
> Since OP doesn't answer I think this issue can be closed. 

Yeah my apologies, this issue disappeared completely in my feed I guess so I haven't seen this until now.

Is it okay if I close. Atm I am not using vimwiki so I cant really help out.

I hope I haven't wasted too much of your time with this.
