### ISSUE TITLE
Links not working with pandoc

### ISSUE THREAD

**Issue by n3ry7** [vimwiki/vimwiki#1152]
I am trying to export all my vimwiki files to an epub. 

It works but the links generated from my wiki do not point to other sections.

I am using markdown syntax.

vimrc settings:
let g:vimwiki_list = [{'path': '~/vimwiki/',
                      \ 'syntax': 'markdown', 'ext': '.md'}]
VimwikiShowVersion:
 Stable version:2.5

pandoc 2.14.0.2
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
citeproc 0.4.0.1, ipynb 0.1.0.1

pandoc command used:
pandoc -o ./vimwiki.epub metadata.txt ./*.md ./diary/*.md --toc

Sorry in advance if this is pandoc problem. I could not figure it out, apreciate any help.

**Comment by tinmarino** [comment]
Links are working fine in markdown, We cannot help you if you do not give file_in and file_out, and the command used to generate the llinks
