### ISSUE TITLE
Keep undo-history clean for `vimwiki_auto_toc = 1`

### ISSUE THREAD

**Issue by tmerse** [vimwiki/vimwiki#1156]
Summary: Pressing <kbd>u</kbd>(ndo) after saving a file jumps to `# Contents`-section (even if it does not affect the TOC) if `vimwiki_auto_toc` is enabled.

---

Prior to submitting a new issue make sure to complete these steps:

- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`

`markdown`

- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.

1. set `let g:vimwiki_auto_toc = 1`
2. edit some content except headings.
3. press <kbd>u</kbd>
  - **Expected result**: Undo last content change
  - **Result**: Cursor jumps to `TOC`-section

- [x] Include the output of `:VimwikiShowVersion`.

```
Os: Linux
Vim: 800
Branch: dev
Revision: 212a66f
Date: 2021-06-11 12:06:43 -0400
```

I find this behavior mildly annoying and propose pr #1155 as a possible solution (only update listing if there are changes which affect the listing). If someone has a better solution (altering undo history, etc.) please let me know.

**Comment by tinmarino** [comment]
Fixed by #1155
