### ISSUE TITLE
Customising colours in vim's view

### ISSUE THREAD

**Issue by protist** [vimwiki/vimwiki#116]
Is it possible to change the default colours for the marked-up text, which is displayed within vim itself? Specifically, I find it difficult to see pre-formatted/code text, especially when it's in a large block of "normal" text. I'd like to give it a light-yellow background, perhaps.

![Screenshot](https://i.imgur.com/dX1jgJp.png)

**Comment by EinfachToll** [comment]
You find the mapping from Vimwiki syntax elements to color here:https://github.com/vimwiki/vimwiki/blob/dev/syntax/vimwiki.vim#L516-L596
You can override it by simply mapping it to another color or to another already defined syntax group. For example, if you put this in your .vimrc:
~~~viml
hi def link VimwikiCode Search
~~~
the inline code is shown with the same color like searched text. You can type `:hi` for an overview of already defined syntax groups.

**Comment by protist** [comment]
Thank you very much, that works well. Also, for future reference, is it possible to use fully-customisable colours, or are we restricted to the pre-defined schemes for existing syntax?

**Comment by EinfachToll** [comment]
Of course you can customize everything, for example this line (copied from the Vim help file) changes how the Comment syntax group looks like:
```viml
:hi Comment	term=bold ctermfg=Cyan guifg=#80a0ff gui=bold
```
But this is where my knowledge ends. Take a look at `:h :hi` for more information.

**Comment by protist** [comment]
Brilliant! Thanks for that. Just to be explicit, something like the following lines in `~/.vimrc` works.

    hi VimwikiCode term=bold ctermfg=Cyan guifg=#80a0ff gui=bold
    hi VimwikiPre term=bold ctermfg=Cyan guifg=#80a0ff gui=bold

**Comment by alehresmann** [comment]
Hi, in case someone was looking to something similar as me, that is, highlighting bold text to be a particular colour, you can do it very similarly to the comment above.

For instance, for cyan bold text and dark red italic text, just add this to your `.vimrc`:

```
hi VimwikiBold term=bold ctermfg=Cyan guifg=#80a0ff gui=bold
hi VimwikiItalic term=bold ctermfg=Red guifg=#cc0000 gui=italic
```
