### ISSUE TITLE
Website: is `set nocompatible` necessary?

### ISSUE THREAD

**Issue by alat-rights** [vimwiki/vimwiki#1161]
https://vimwiki.github.io/ instructs users to add `set nocompatible` to their vimrc files, but since nocompatible is automatically set if a vimrc or gvimrc file is found, is this actually necessary?

**Comment by brennen** [comment]
This makes it clear that `nocompatible` is the necessary state for running the plugin, I'd say.  It will be in that state most of the time, but someone might otherwise try running under `compatible`.
