### ISSUE TITLE
Changing status options

### ISSUE THREAD

**Issue by TheNomadicAspie** [vimwiki/vimwiki#1163]
I enjoy incrementing and decrementing the status of each task so I can see which ones are in progress or how close they are to completion. But I can't find a way to change the actual options instead of ., o, 0, and X.

Is there a way to change the characters/strings used?

**Comment by brennen** [comment]
See `:help vimwiki-options-listsyms` and `:help g:vimwiki_listsyms`:

> You can set it to some more fancy symbols like this:                                                                         
>                                                                                                                          
>   `let g:vimwiki_listsyms = '✗○◐●✓'`
