### ISSUE TITLE
Is it possible to add a diary entry for a past date?

### ISSUE THREAD

**Issue by MaxPancake** [vimwiki/vimwiki#1164]
Sorry this is not really an "issue," but I can't find a place to ask questions.

**Comment by brennen** [comment]
Sure.  Just open something like `diary/2021-08-20.wiki` and edit away, or make an appropriate link in the form of `[[diary:2021-08-20]]` and hit enter.

I often navigate to past or future diary pages by using the `Calendar.vim` integration - see `:help vimwiki-calendar` for details.

Ctrl-up and Ctrl-down may work for navigating diary entries as well, depending on what vim you're using.
