### ISSUE TITLE
Cannot unbind <leader>wi

### ISSUE THREAD

**Issue by worldpe** [vimwiki/vimwiki#1165]
When I attempt to unbind the command, I am told that it does not exist, but it appears to be the case that it does exist as it is 100% replicable.

**Comment by brennen** [comment]
I'm unable to reproduce this - running `:unmap <Leader>wi` behaves as expected.

Please post Vim version, output of `:VimwikiShowVersion`, configuration from your `.vimrc`, and exactly what command you're running and the error message given.

**Comment by tinmarino** [comment]
Closing <= cannot reproduce either
