### ISSUE TITLE
How to refer to a specific line?

### ISSUE THREAD

**Issue by nikinbaidarr** [vimwiki/vimwiki#1168]
Is there a way to make references to a list item? As in to make a reference to a heading we do `[[anchor|##heading title]]` but suppose i want to refer to a specific point or line under that heading is there a way or least a work around to achieve that sort of referencing?

**Comment by brennen** [comment]
There's not, as far as I know, syntax just for creating an anchor. `:help vimwiki-anchors` mentions that tags and bold text also create anchors, so that's one possible workaround.

See #890 for the idea of linking to a specific line number.
