### ISSUE TITLE
Wiki to Markdown

### ISSUE THREAD

**Issue by diego-rapoport** [vimwiki/vimwiki#1173]
Is there already a way to convert the .wiki files directly to .md?

**Comment by brennen** [comment]
[Pandoc](https://pandoc.org/) supports a subset of VimWiki syntax.

**Comment by diego-rapoport** [comment]
That fulfills my need, but it would be great to have it native on vimwiki as we have vimwiki2html. Also thanks for the response!

**Comment by brennen** [comment]
Have a look at the stuff under `:help vimwiki-option-custom_wiki2html`. It's definitely kind of a second-class citizen, and there's work that could be done to make it much simpler out of the box, but I doubt VimWiki itself will ever implement Markdown → HTML conversion. There are already so many ways to do it that adding and maintaining yet another really wouldn't make much sense.
