### ISSUE TITLE
Support page names with dot/period in their name

### ISSUE THREAD

**Issue by bluss** [vimwiki/vimwiki#1177]
Prior to submitting a new issue make sure to complete these steps:

- [ ] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.

```
--- .vimrc
let g:vimwiki_global_ext = 0  " not for .md files outside
let g:vimwiki_url_maxsave=0
let g:vimwiki_list = [{'path': '~/00_Meta/2_Notes/', 'syntax': 'markdown', 'ext': '.md'}]
---
```
Using markdown syntax

For organization I'd like to try to name note pages with leading ordinal numbers, [like in this scheme](https://johnnydecimal.com/).
This causes various issues since the extension of the files is no longer used.

I write `[10 Test/11 Category/11.1 Topic][]` on the index page, use the return key to navigate to the link and confirm creating the page. The page is created with the filename `11.1 Topic` without the .md extension.

Because the file does not use the .md extension, it is also not found by the GenerateLinks command, unfortunately. But links work.

I've seen the issue  #924 so I see that this has kind of been an issue before, but it was decided to not fix anything at that time.

If you use the rename function to rename to a new name using a dot, then the file will still have the .md extension. (Inconsistent with creating a page from a link, unfortunately).

Stable version: 2.5

**Comment by tinmarino** [comment]
This have been fixed in dev branch. Please use the dev branch
You can test with
```
/Folder.new/dir1.new/file new with dot.in filena.dot
```
Press V    => select line
Press Enter => Create link
Press Enter => Ask you to confirm and will create the folder and file with dot and space

**Comment by bluss** [comment]
Awesome. Thanks for working on vimwiki :slightly_smiling_face:
