### ISSUE TITLE
Specify base directory for vimwiki "home"

### ISSUE THREAD

**Issue by protist** [vimwiki/vimwiki#118]
I'm migrating my zim database, where I use numerous relative links. For example, I might have a page at `/path/to/vimwiki/foo/bar.wiki` link to another at `/path/to/vimwiki/cat/hat.wiki`. I know that I could refer to the latter with the relative path `../cat/hat`, but is there a way to specify the "base" vimwiki directory instead? i.e. something like `vwbase/cat/hat`?

**Comment by EinfachToll** [comment]
That was discussed in #105, so I'm closing this issue. I agree that some sort of “absolute” links are useful, that is, links relative to the base, not to the current file. If you have a proposal for a good syntax, report it in #105.

**Comment by protist** [comment]
Oops, sorry about that. I had a search but missed that one.
