### ISSUE TITLE
forward jump motion [mapping help]

### ISSUE THREAD

**Issue by jaker-dotcom** [vimwiki/vimwiki#1182]
Hello there!
So I gather from the vim help that usually there is a motion to go forward in the jump list which is bound to TAB and CTRL+i. However with vimwiki both of them jump to the next wiki link. I would like to unmap this behavior from CTRL+i to be able to use jump list. What would I write into my init.vim to disable it? `map <TAB> <Plug>VimwikiNextLink` doesn't solve my issue.

Thanks,
Jaker

i run stable version 2.5

My init.vim:
`let g:vimwiki_list = [{'path': '~/doc/vimwiki', 'syntax': 'markdown','ext': '.md','auto_diary_index': 1}]
let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown','.mdown': 'markdown'}
let g:vimwiki_markdown_link_ext = 1
let g:vimwiki_markdown_syntax = 'markdown'
let g:vimwiki_diary_months = {
      \ 1: 'Januar', 2: 'Februar', 3: 'März',
      \ 4: 'April', 5: 'Mai', 6: 'Juni',
      \ 7: 'Juli', 8: 'August', 9: 'September',
      \ 10: 'Oktober', 11: 'November', 12: 'Dezember'
      \ }
let g:vimwiki_autowriteall = 1
`

**Comment by tinmarino** [comment]
```vim
:h g:vimwiki_key_mappings

let g:vimwiki_key_mappings =                      \ {                                             \ 'links': 0, 
             \ }
```


In the dev branch

```
442 " Declare Map: default links key mappings   443 if str2nr(vimwiki#vars#get_global('key_mappi    ngs').links)                                444   call vimwiki#u#map_key('n', '<CR>', '<Plug    >VimwikiFollowLink')                        445   call vimwiki#u#map_key('n', '<S-CR>', '<Pl    ug>VimwikiSplitLink')                       446   call vimwiki#u#map_key('n', '<C-CR>', '<Pl    ug>VimwikiVSplitLink')                      447   call vimwiki#u#map_key('n', '<M-CR>', '<Pl    ug>VimwikiBaddLink')                        448   call vimwiki#u#map_key('n', '+', '<Plug>Vi    mwikiNormalizeLink')                        449   call vimwiki#u#map_key('v', '+', '<Plug>Vi    mwikiNormalizeLinkVisual')                  450   call vimwiki#u#map_key('v', '<CR>', '<Plug    >VimwikiNormalizeLinkVisualCR')             <dle/opt/wiki/ftplugin/vimwiki.vim57%  0,441/776
```

**Comment by jaker-dotcom** [comment]
Hey thanks!
I use vim-plug but that shouldn't matter I guess. Never used a branch other than main though. The readme clearly states that it is recommended to run main branch. Is there any risk attached to trying dev branch? I'd guess it's done by providing the link to the dev branch '''Plug vimwiki/vimwiki/tree/dev'''?

**Comment by tinmarino** [comment]
Hi, in your case, you can keep using the master branch.
Using the dev, there should be no big problem, but if there is, reporting/
fixing it will help the whole comunity.

**Comment by jaker-dotcom** [comment]
Okay certainly feels better for me to stay on main. Your suggested change `let g:vimwiki_key_mappings = {'links': 0}` made it so that I can't follow no links no more. Enter will just make me jump to the next link.

Could it be some interference with other lines in my init.vim? I have it as the first line in the file.
E.g. should I delete the previously mentioned line `map <TAB> <Plug>VimwikiNextLink`
Could I provide some output to help you identify the problem?

**Comment by tinmarino** [comment]
No side effect, no need to have ot first line, but before the packadd.
Yes remove your mapping if you do not want it.
Post tricks (i.e. in after) are no so effective with vimwiki.
In doubt, test by dichotomically deleting lines of your vimrc until you get
what you want.

Sry if that do not answer, not sure I understood well your doubts. All that
(Vimscript) is not so easy
