### ISSUE TITLE
Help with VimwikiToggleListItem

### ISSUE THREAD

**Issue by JunkyardCat** [vimwiki/vimwiki#1183]
Im using
vimwiki 2.5 stable
neovim 0.5.1
vim-plug
windows 10

Issue description: when i do ctrl + space to toggle checkbox it doesnt do anything. i then add nmap to my vim.init(vimrc) "nmap <Leader>tl <Plug>VimwikiToggleListItem" save then quit and restarted vim. i go to my wiki index create new line type "\tl" nothing happens. i type "*" then type "\tl" it finally creates the empty checkbox ("[ ]")

is this a normal behavior? should i be able to create a checkbox whether theres an asterisk present or not?

**Comment by tinmarino** [comment]
Can you try with dev branch?

Are you mapping OK
```
:map <C-Space>
v  <C-Space>    @<Plug>VimwikiToggleListItem
n  <C-Space>    @<Plug>VimwikiToggleListItem
```

The format of your toto list item ?
```
* [ ] toto
* [ ] toto
```

**Comment by Kyllingene** [comment]
`<C-Space>` doesn't work for me either, trying to rmap it to `<C-Space>` doesn't work; however, I mapped it to `<leader><space>`, which works. I'm on Windows, and tried with both Cmder and Terminal.

**Comment by mkeeter** [comment]
I'm also seeing this issue (macOS, iTerm2), and can confirm that the default mappings look correct:

```
v  <C-Space>    @<Plug>VimwikiToggleListItem
n  <C-Space>    @<Plug>VimwikiToggleListItem
```

**Comment by brennen** [comment]
> Issue description: when i do ctrl + space to toggle checkbox it doesnt do anything. i then add nmap to my vim.init(vimrc) "nmap tl VimwikiToggleListItem" save then quit and restarted vim. i go to my wiki index create new line type "\tl" nothing happens. i type "*" then type "\tl" it finally creates the empty checkbox ("[ ]")

Couple of thoughts here:

- `:VimwikiToggleListItem` won't make a list item out of a line with no list marker.  If you add one, it will then cycle through the checkbox states.
- Your map probably needs to be `<Leader>tl` if you want to include the `\`.

> turns out my OS was eating Ctrl-Space as "Select previous input source", so once I disabled that, it worked fine. Using showkeys helped narrow this down, since that showed me it wasn't getting to the terminal at all!

I suspect something like this is what's going on in most cases.
