### ISSUE TITLE
Disable one specific mapping

### ISSUE THREAD

**Issue by Jasha10** [vimwiki/vimwiki#1186]
I'm aware that groups of mappings can be enabled/disabled using the key mappings table `g:vimwiki_key_mappings`.
For example, `leg g:vimwiki_key_mappings = {'links': 0}`.

For my use case, I'd like to disable one specific mapping from inside the `'links'` group. I'd like to disable the `<Tab>` mapping without disabling the other mappings from the links group. Is this possible?

```text
:VimwikiShowVersion
Os: Linux
Vim: 800
Branch: dev
Revision: a3a3fbf
Date: 2021-09-20 11:16:56 -0600
```

**Comment by brennen** [comment]
Try mapping `<Plug>VimwikiNextLink` to something else. As an example:

```vim
nmap <Leader>nl <Plug>VimwikiNextLink
```

**Comment by krzkrzkrz** [comment]
For anyone still looking. Using the Lazy package manager:

```
return {
  'vimwiki/vimwiki',
  init = function()
    -- ..
  end,
  config = function()
    vim.g.vimwiki_key_mappings = {
      table_mappings = 0,
    }

    vim.keymap.set('n', '<leader>nl', '<Plug>VimwikiNextLink', { silent = true })
  end
}
```
