### ISSUE TITLE
Allow highlighting for blockquotes in Markdown

### ISSUE THREAD

**Issue by piersolenski** [vimwiki/vimwiki#1187]
Is it possible to add the option to highlight blockquotes in themes?

The [vimwiki syntax](https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/doc/vimwiki.txt#L1424) seems to cover it (without highlighting) but it would be great to have the Markdown equivalent supported too, i.e. `>`.

**Comment by tinmarino** [comment]
Hi @piersolenski, yes it is possible but how do you want to highlith it?
Acording to me, the Normal highlithg is the best, potencionally nested syntax.
```
:help  group-name
```

**Comment by piersolenski** [comment]
Anything that allows it to stand out really. I use them quite heavily and they get easily lost amongst the other text at the moment. Other Markdown tools I've used (Notion/Joplin/Bear) all give you some visual indication of when you're using a blockquote, so would be cool to be able to target it for highlighting here.

PS I've added VimWiki support to https://github.com/rose-pine - https://github.com/rose-pine/neovim/blob/main/lua/rose-pine/theme.lua#L402 - so happy to keep updating it if we found a group name that worked.

**Comment by tinmarino** [comment]
Hey @piersolenski ! Glad to hear you offer your support.
Syntax.vim is a funny task (syncerely). Some in syntax/vimwiki*.vim some in u.vim (typeface) and some variable in vars.vim (which should no affect you.

First, you should link the syntax to `VimwikiBlockquote` so that user can change this (vimwiki) specific group. Then I propose to link `VimwikiBlockquote` to `Todo` which is less hardcoded than typefacing it to bold (but you can also do the latter.

From `:h group-name`

```
*Todo  anything that needs extra attention;    mostly the                                         keywords TODO FIXME and XXX
```

Thanks again to volunteer, good luck and have fun!

**Comment by tinmarino** [comment]
You can change the color of VimwikiPre

```vim
:hi VimwikiPre ctermfg=Red ctermbg=blue
```

![Screenshot from 2023-06-14 14-09-35](https://github.com/vimwiki/vimwiki/assets/6123962/b6cde558-3d61-4745-bfdf-8008e6ac249b)

Currently set as
```
:hi VimwikiPre
VimwikiPre     xxx links to PreProc
```

**Comment by tinmarino** [comment]
Closed <= Prefered to be implemented at user configuration, as this looses Vimwiki default highlighting, like bold.

You can do the following in your vimmrc

```vim
execute 'syntax match VimwikiBlockquote /^\(' . join(vimwiki#vars#get_syntaxlocal('blockquote_markers'), '|') . '\).*/'
hi VimwikiBlockquote ctermfg=red
```
![Screenshot from 2023-06-14 14-18-30](https://github.com/vimwiki/vimwiki/assets/6123962/29d57e45-85f0-422a-89de-78ab6ddc2758)
