### ISSUE TITLE
May I start the "diary of the day" using a file-link/command-line-argument?

### ISSUE THREAD

**Issue by llinfeng** [vimwiki/vimwiki#119]
While I am trying to customize my keyboard, I wondered if I could create a file path that could start the "diary of the day".

Currently, I can only trigger Vim and then press `<leader>w<leader>w` to get to the diary of the day. However, it would be ideal if I can reach such file using a file-link.

The question is: had there been a syntax that could feed the Vim session to be ran with a function to be executed? For the diary case, it is the `<Plug>VimwikiMakeDiaryNote` function.

All the best, 

-Linfeng

**Comment by EinfachToll** [comment]
No, but you can write yourself a link handler function and put it in your .vimrc. Take a look at `:h VimwikiLinkHandler` to see how it works.

Untested example:
~~~viml
  function! VimwikiLinkHandler(link)
     if a:link =~ "command:"
      let cmd = a:link[8:]
      execute cmd
      return 1
    else
      return 0
    endif
endfunction
~~~

Then, a link `[[command:VimwikiMakeDiaryNote]]` should execute that command.

**Comment by llinfeng** [comment]
Opps, apologize for not making myself clear enough. I would like to have an external link that "physically exists" by itself as a *file*. This would then be used by the keyboard, which can only execute a *file*. Something in my mind is: to have a new vim session start fresh, with the diary of the day also loaded as a buffer.
I am not sure if this should be a reasonable task at Vim's end. Maybe I shall just use a bat-file which can fetch the date.

Nevertheless, your idea could be a walk-around, as I could put the `[[command:VimwikiMakeDiaryNote]]` at the front of diary-index-file could well provide a stable port. However, as I've updated in my `_vimrc`, what you've suggested seems to be not work. After adding the function you've suggested, (my `_vimrc` could be found here: https://www.github.com/llinfeng/vim), pressing enter while having the cursor hovering over the `[[command:VimwikiMakeDiaryNote]]` does not trigger any action/motion.

Any further suggestion on either track?

All the best, 

-Linfeng

**Comment by EinfachToll** [comment]
Ok, you mean a link on the operation system level.
You can start Vim with a command as a parameter, which is executed immediately after Vim has started. It goes like this: `vim -c VimwikiMakeDiaryNote`. For you as Windows user it's not that easy to start a program with additional parameters, but Google will help you to figure it out.

**Comment by llinfeng** [comment]
@EinfachToll. Calling the function `VimwikiMakeDiaryNote` as parameter is way simpler than what I have imagined. Thank you for providing the syntax.

As for Windows, saving the following content into a `.bat` file will do the work.
````
 gvim -c VimwikiMakeDiaryNote
````

**Comment by cosmicraga** [comment]
Thanks for the above answer. How to implement the above solution for multiple diaries?

**Comment by llinfeng** [comment]
@cosmicraga It is doable for multiple diaries, or, to be more precise: for
creating diary entries in multiple **wikis**.

Suppose that you store your non-default Wiki in directory
`/path/to/your/wiki2/` and that you would like to create a new diary for that
specific Wiki (for example: `/path/to/your/wiki2/2019-10-18.wiki`). The following
one-liner shall do the trick:
    ```bash
    vim /path/to/your/wiki2/Index.wiki -c VimwikiMakeDiaryNote
    ```
The bottom line is that you would like to first enter a Vim session that is
loaded with one-wiki-file in your desired diary/wiki directory. This is done by
the `vim /path/to/your/wiki2/Index.wiki`. Then, the common command line flag 
`-c VimwikiMakeDiaryNote` shall create/switch-to the diary of the day in that
specific Wiki.
