### ISSUE TITLE
Extra dots in link name fail to open the correct file.

### ISSUE THREAD

**Issue by timhemel** [vimwiki/vimwiki#1199]
Prior to submitting a new issue make sure to complete these steps:

- [ ] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.

Please forgive me for skipping this, I did not have the time for it.

- [ ] Post the syntax you are using (markdown) **and** your vimwiki settings from your `.vimrc`

Markdown text:

```
* [test-1.2](test-1.2.md)
```

Vimiwiki settings:

```
" vimwiki 
let g:vimwiki_list = [ { 'path' : '/path/to/wiki/', 'ext': '.md', 'syntax': 'markdown' } ] 
let g:vimwiki_auto_chdir = 1
let g:vimwiki_global_ext = 0
```

- [ ] Provide a detailed description of the problem including **steps to reproduce the issue**.

The following markdown opens the file `test-1.2` instead of `test-1.2.md`.

```
* [test-1.2](test-1.2.md)
```

I noticed that when converting `test-1.2` into a link, vimwiki replaces dots and dashes in the link text, and it does not add the .md extension, perhaps these issues are related.

- [ ] Include the output of `:VimwikiShowVersion`.

Stable version: 2.5

**Comment by brennen** [comment]
This duplicates #950, which I can confirm is still an issue.
