### ISSUE TITLE
VimwikiCheckLinks reports false positives

### ISSUE THREAD

**Issue by protist** [vimwiki/vimwiki#120]
I ran `:VimwikiCheckLinks`, and it reported a few false positives.

* It attempted to parse code inside code blocks, that were supposedly links. IMO it should ignore these. e.g.

```
{{{
[[foo]]
}}}
```

and

```
`[[foo]]`
```

* It incorrectly listed directories such as `[[file:/home/protist/directory]]` that really *did* exist. Normally, vimwiki opens these correctly from wikilinks. Also, `:VimwikiCheckLinks` works fine with files, just not directories.

**Comment by EinfachToll** [comment]
Your second point should be fixed now.

Regarding your first point: to be precise, these (non-)links behave like regular links in *every* aspect save for highlight and HTML conversion. You can jump to them and “click” on them. If we wanted to prevent that, we would have to parse the whole document and check which parts are inside a code block or whatever. That would make things either slow or rediculously complicated. I guess we just have to live with that.

**Comment by protist** [comment]
The fix doesn't seem to work for me. If I add the link `[[file:/tmp]]` to a page, included in the output is
```
/path/to/wiki/index.wiki|63 col 3| there is no such file: /tmp
```

With the second case, it's a bit annoying, but I can certainly accept it given that performance might otherwise suffer.

**Comment by EinfachToll** [comment]
> The fix doesn't seem to work for me. If I add the link [[file:/tmp]] to a page, ...

Links to directories must end with `/`, so `[[file:/tmp/]]` should work as expected.

**Comment by protist** [comment]
Yes, that works. FWIW if I omit the final `/`, e.g. `[[file:/tmp]]`, then I can still "follow" the link fine with Enter. Thanks again for the prompt fix.
