### ISSUE TITLE
Table Highlight Color

### ISSUE THREAD

**Issue by mbpowers** [vimwiki/vimwiki#1200]
I was wondering if there was a way to change the color of the table elements such as `|` `_` and `:`. I saw there was a highlight group called `VimwikiTableRows` but when I did `:hi VimwikiTableRows guifg=#FFFF00` it had no affect, so I assume it was not intended for that purpose. 

If it isn't currently possible I think this would be a cool feature, assuming it wouldn't be too much work, as the bright cell borders take focus away from the content of the cells.

**Comment by tinmarino** [comment]
Hi @mbpowers, sorry for the delay.

Run

```vim
:hi VimwikiCellSeparator ctermfg=red
```

To colorize them

![Screenshot from 2023-03-17 03-07-15](https://user-images.githubusercontent.com/6123962/225826001-a30b3fc4-6462-4ae7-b7c7-5f7bcd62da7f.png)

Note that found this with this utility in my vimrc

```vim
  function! SynStack()
    if !exists('*synstack')
      return
    endif
    echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
  endfunction
```

Closing as a tip.
