### ISSUE TITLE
Do templates work with markdown files?

### ISSUE THREAD

**Issue by sdondley** [vimwiki/vimwiki#1203]
I'm having trouble getting templates working with markdown. I'm not sure if I'm missing something or if this is something I have to do in the custom conversion script.

Os: Mac
Vim: 800
Branch: dev
Revision: 4d7a4da
Date: 2021-12-19 00:49:16 -0300

**Comment by CaeChao** [comment]
Vimwiki2HTML is currently functional only for the default syntax, you need to customize your wiki2html script, using tool like pandoc to convert markdown to html

**Comment by brennen** [comment]
@CaeChao is correct here.  See `:help vimwiki-option-custom_wiki2html`
