### ISSUE TITLE
Links don't display properly while writing and while hovering

### ISSUE THREAD

**Issue by Rowaaaaan** [vimwiki/vimwiki#1216]
Prior to submitting a new issue make sure to complete these steps:

- [X] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [X] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.
## Issue
The link I'm trying to write disappears whenever I write them in between two brackets. This should only happen when I'm not currently hovering over the link.

## Steps to reproduce
+ Create a link [[link | this is a link]]
+ link disappears without leaving the line while in insert mode or normal mode

![Issue](https://envs.sh/EK8.gif)

- [X] Include the output of `:VimwikiShowVersion`.
```
Os: Linux                                                                                                                                       
Vim: 800
Branch: dev
Revision: 4d7a4da
Date: 2021-12-19 00:49:16 -0300
``

**Comment by brennen** [comment]
Feels like something with concealment, but I'm not sure what offhand. Posting your overall vimrc might be helpful.

**Comment by Rowaaaaan** [comment]
Here are the two config files that are probably actually relevant to the problem.

<details>
<summary>init.vim</summary>

    source ~/.config/nvim/plugins.vim
    source ~/.config/nvim/keys.vim
    source ~/.config/nvim/autocmds.vim
    source ~/.config/nvim/commands.vim
    source ~/.config/nvim/dashboard.lua
    
    " Base settings
    set nocompatible
    filetype plugin on
    syntax on
    set mouse=a
    set path+=**
    set wildmenu
    set termguicolors
    
    " Indentation settings
    set number relativenumber
    set tabstop=4
    set softtabstop=-1
    set shiftwidth=0
    set shiftround
    set autoindent smartindent
    
    " Fold settings
    set foldmethod=indent
    set foldnestmax=10
    set nofoldenable
    set foldlevel=2
    
    " LSP settings
    set updatetime=300
    
    "Color settings
    "Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
    "If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
    "(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
    if (empty($TMUX))
      if (has("nvim"))
        "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
        let $NVIM_TUI_ENABLE_TRUE_COLOR=1
      endif
      "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
      "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
      " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
      if (has("termguicolors"))
        set termguicolors
      endif
    endif
    
    " LaTex
    let g:livepreview_previewer='zathura'
    let g:liveprevier_engine='pdflatex'
    
    " Dashboard
    let g:dashboard_default_executive = 'telescope'
    
    " Neovide
    let g:neovide_cursor_vfx_mode="railgun"
    set guifont=FiraCode
    
    "colorscheme onedark
    "let g:airline_theme='onedark'
    "let g:onedark_termcolors=256
    "let g:onedark_terminal_italics=1
</details>

<details>
<summary>plugins.vim</summary>
    if empty(glob('~/.vim/autoload/plug.vim'))
	    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
		    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
    endif
    
    
    call plug#begin('~/.vim/plugged')
    
	    Plug 'tpope/vim-sensible'
	    Plug 'tpope/vim-sleuth'
    
    " File manipulation =============================={{
    
	    Plug 'liuchengxu/vim-which-key'                     " Shows popup of leader key combinations
	    Plug 'tpope/vim-repeat'                             " Repeats last command using .
	    Plug 'tpope/vim-surround'                           " Surrounds text with either func name ex. main(), html tags, or brackets {} of choice
	    Plug 'jiangmiao/auto-pairs'                         " Automatically pairs brackets and parenthesis
	    Plug 'haya14busa/incsearch.vim'                     " Show search result-highlights whilst typing the query
    
    " =============================================}}
    
    " File browsing =================================={{
    
	    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } } " Fuzzy file opener, use: :FZF or :FZF! for fullscreen
	    Plug 'junegunn/fzf.vim'
    
    " =============================================}}
    
    " Plugin for Git =============================={{
    
	    if has('nvim') || has('patch-8.0.902')
		    Plug 'mhinz/vim-signify'
	    else
		    Plug 'mhinz/vim-signify', { 'branch': 'legacy' }
	    endif
    
	    Plug 'tpope/vim-fugitive'
    
    " =============================================}}
    
    " Navigation ================================={{
    
	    Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
	    Plug 'pechorin/any-jump.vim'
	    Plug 'justinmk/vim-sneak'
	    Plug 'honza/vim-snippets'
    
    " =============================================}}
    
    " Formatting =========================================================== {{
    
	    Plug 'godlygeek/tabular'							 " :Tab /regex can align code on occurrences of the given regex. I.e. :Tab /= aligns all = signs in a block.
	    Plug 'preservim/nerdcommenter'
    
    " =============================================}}
    
    " Bloat ================================================================ {{
    
	    "Plug 'glacambre/firenvim', { 'do': { _ -> firenvim#install(0) } }
	    Plug 'machakann/vim-highlightedyank'
	    Plug 'vim-airline/vim-airline-themes'
	    Plug 'vim-airline/vim-airline'
	    Plug 'joshdick/onedark.vim'
	    Plug 'kyoz/purify', { 'rtp': 'vim' }
	    "Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' } " Shows colors from hex and rgb codes
	    Plug 'ryanoasis/vim-devicons'
	    Plug 'psliwka/vim-smoothie'
	    Plug 'vimwiki/vimwiki', { 'branch' : 'dev' }
	    Plug 'xuhdev/vim-latex-live-preview'
	    Plug 'onsails/lspkind-nvim'
	    Plug 'kyazdani42/nvim-web-devicons'
	    Plug 'Yggdroot/indentLine'
	    Plug 'glepnir/dashboard-nvim'
	    Plug 'nvim-lua/popup.nvim'
	    Plug 'nvim-lua/plenary.nvim'
    
    " =============================================}}
    
    " Language Plugins ===================================================== {{{
    
	    Plug 'puremourning/vimspector', {
		    \ 'do': 'python3 install_gadget.py --enable-vscode-cpptools'
		    \ }
    
	    Plug 'sheerun/vim-polyglot'		" Syntax highlighting for most languages
	    Plug 'alvan/vim-closetag'
    
	    " PHP
	    Plug 'adoy/vim-php-refactoring-toolbox'
	    Plug 'StanAngeloff/php.vim'
	    Plug 'kevinoid/vim-jsonc'
	    Plug 'stephpy/vim-php-cs-fixer'
    
	    " HTML
	    Plug 'ap/vim-css-color'
	    Plug 'mattn/emmet-vim'
    
	    " JS
	    Plug 'pangloss/vim-javascript' " syntax highlighting JS
	    Plug 'ianks/vim-tsx'
	    Plug 'leafgarland/typescript-vim'
	    Plug 'HerringtonDarkholme/yats.vim' " typescript syntax highlighting
	    Plug 'mxw/vim-jsx'
    
	    Plug 'neoclide/coc.nvim', {'branch': 'release'}
	    Plug 'turbio/bracey.vim', {'do': 'npm install --prefix server'}
    
    " =============================================}}}
    " ========= Unused plugins ========== {{{
    
	    "" Haskell
	    " Plug 'neovimhaskell/haskell-vim'
	    " Plug 'Twinside/vim-hoogle', {'on': 'Hoogle'}
    
	    " Rust
	    " Plug 'rust-lang/rust.vim'
	    " Plug 'mattn/webapi-vim'
    
	    " Plug 'LnL7/vim-nix'
	    " Plug 'udalov/kotlin-vim'
	    " Plug 'purescript-contrib/purescript-vim'
    
	    " Plug 'nathanaelkane/vim-indent-guides' " Can be toggled using <leader>ig (intent-guides)
	    " Plug 'liuchengxu/vim-clap', { 'do': ':Clap install-binary' }
	    " Plug 'hauleth/sad.vim'                              " Use siw instead of ciw. when using . afterwards, will find the next occurrence of the changed word and change it too
    
    " =============================================}}}
    call plug#end()
</details>

**Comment by tinmarino** [comment]
Hi, unset the concealcursor string, which is a dangeours feature permitting to conceal current (cursor) line.
I guess it has been set by another plugin.

```vim
set concealcursor=
```

```vim
:h concealevel
:h concealcursor
```

Cheers.

**Comment by tinmarino** [comment]
Closing <= due to specific configuration and other plugins => no changes expected in the vimwiki code
