### ISSUE TITLE
Question: vimwiki_url_maxsave appears to have no effect

### ISSUE THREAD

**Issue by tompropst** [vimwiki/vimwiki#1217]
With the setup below, my link URL's are still concealed if the cursor is not on the same line. From the description in the help, I thought setting `g:vimwiki_url_maxsave = 0` would disable this. Am I missing something?

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
    ```
    let wiki_1 = {}
    let wiki_1.path = '~/notes/'
    let wiki_1.diary_rel_path = 'journal/'
    let wiki_1.syntax = 'markdown'
    let wiki_1.ext = '.md'
    let wiki_1.auto_diary_index = 1
    
    let g:vimwiki_list = [wiki_1]
    
    let g:vimwiki_global_ext = 0
    let g:vimwiki_dir_link = 'index'
    let g:vimwiki_folding = 'expr'
    let g:vimwiki_markdown_link_ext = 1
    let g:vimwiki_url_maxsave = 0
    ```
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.
    ```
    Os: Linux
    Vim: 802
    Branch: dev
    Revision: 4d7a4da
    Date: 2021-12-19 00:49:16 -0300
    ```

**Comment by tompropst** [comment]
Confirmed that this happens whether `taskwiki` is active or not. The only way I can stop the URL concealing is to set `g:vimwiki_conceallevel = 0` which of course disables all concealing.

**Comment by brennen** [comment]
I'm using this on:

```
Os: Linux                                                                                                        
Vim: 801                                                                                                         
Branch: brennen-tabdrop                                                                                          
Revision: 9b0042f                                                                                                
Date: 2022-05-21 18:43:03 -0600 
```

...and wasn't able to reproduce in a Markdown wiki. Slight possibility it's regressed between vim releases.

**Comment by xgpt** [comment]
Plug 'Yggdroot/indentLine was the cause, not sure why but it causes conceallevel to be set to 2 each time i load a page...disabling it fixed the issue for me.

**Comment by tinmarino** [comment]
The variable `url_maxsave` is used to shorten url, changing the 1 in 2
```
1: https://vimwiki.org/1234567890/1234567890/1234567890
2: https://vimwiki.org/~/1234567890
```

If you want to prevent conceal, there is only the `let g:vimwiki_conceallevel = 0` variable as you noticed, no more customization easily possible.
