### ISSUE TITLE
The wiki info in my vim looks a little weird. 

### ISSUE THREAD

**Issue by Dimpagger** [vimwiki/vimwiki#1218]
I'm using default syntax for wiki, and that's my .vimrc config:

```
:autocmd BufRead,BufNewFile *.wiki set filetype=vimwiki
:autocmd FileType vimwiki map diary :VimwikiMakeDiaryNote
" auto toggle vim calendar
function! ToggleCalendar()
    execute ":Calendar"
    if exists("g:calendar_open")
	if g:calendar_open == 1
	    execute "q"
	    unlet g:calendar_open
	else
	    g:calendar_open = 1
	end
    else
	let g:calendar_open = 1
    end
endfunction
:autocmd FileType vimwiki map c :call ToggleCalendar()

" vimwiki stuff "
" Run multiple wikis "
let g:vimwiki_list = [{'path': '~/Library/Mobile\ Documents/com\~apple\~CloudDocs/VimWiki/personal.wiki'},{'path': '~/Library/Mobile\ Documents/com\~apple\~CloudDocs/Vimwiki/work.wiki'}]
```
That's it looks like:
<img width="1042" alt="截屏2022-04-03 03 02 39" src="https://user-images.githubusercontent.com/4070286/161397603-19b18501-d43b-483a-ba03-2dbe4e22d68a.png">
different from the screenshot on readme file, the vimwiki link & strikeout text & others display directly by the code without styles.

I'm very sorry I can't reproduce this on another computer. in my MAC, it always seems that.

My Vimwiki version is "Stable Version 2.5".

Prior to submitting a new issue make sure to complete these steps:
- [X] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [X] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [X] Include the output of `:VimwikiShowVersion`.

**Comment by hundertzwoelf** [comment]
Does `:set conceallevel=2` solve your problem?

**Comment by rodhash** [comment]
Does this help?
`:set concealcursor=inc`

Conceal suddenly stopped working in my setup and I just realized that another plugin changed from `inc` to only `i` .. now it's back to normal.

**Comment by Dimpagger** [comment]
The reason is I use the default vim on my mac, that version didn't include conceal feature.

I reinstall it through homebrew and up to version 9.0 solve the problem.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/4070286/189802344-4edb189a-4e8a-4256-a142-57ad4fc9c4e1.png">

**Comment by Dimpagger** [comment]
> Does this help? `:set concealcursor=inc`
> 
> Conceal suddenly stopped working in my setup and I just realized that another plugin changed from `inc` to only `i` .. now it's back to normal.

thanks, I think I found the reason.

**Comment by tinmarino** [comment]
Closing <= Fixed with vim compiled with +conceal

Thank you @Dimpagger for sharing the solution.
