### ISSUE TITLE
Vimwiki file-types overloaded by markdown file-type

### ISSUE THREAD

**Issue by rafi** [vimwiki/vimwiki#122]
Using the markdown syntax, every time I open a link - the newly opened file's type is `markdown` instead of `vimwiki`. Interestingly, the first page, opened by `:VimwikiIndex` is fine, its file-type set to `vimwiki` correctly, but any opened link from hereinafter opens incorrectly as filetype `markdown`.

I had to add an ugly fix to my `filetype.vim`:
```vim
" Vimwiki: Fix markdown autodetection
autocmd BufEnter */docs/wiki/*.md setfiletype vimwiki
```
Any clue how could this be fixed "the right way"?

**Comment by EinfachToll** [comment]
Hm, I can't reproduce it. Do you have another plugin which sets the filetype? Can you temporarily remove your fix and post the output of `:verbose set filetype`? This command shows which script set the file type for the last time.

**Comment by rafi** [comment]
Thanks, that helped realizing it's [vim-markdown/ftdetect/markdown.vim](https://github.com/rcmdnk/vim-markdown/blob/mod/ftdetect/markdown.vim). Any thoughts?

**Comment by EinfachToll** [comment]
I think we can safely force vimwiki filetype for opened files. So, your problem should be fixed now.

**Comment by rafi** [comment]
Works great, thanks.
