### ISSUE TITLE
Define Nested Item Style

### ISSUE THREAD

**Issue by Druidefix** [vimwiki/vimwiki#1220]
Prior to submitting a new issue make sure to complete these steps:

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.

I'm using commit id 4d7a4da, which should be the latest on the `dev` branch, and the following minimal `.vimrc`

```
set nocompatible
filetype off
syntax on

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'vimwiki/vimwiki'
call vundle#end()
filetype plugin indent on
:let mapleader = " "

let g:vimwiki_list = [{
\ 'syntax': 'markdown',
\ 'ext': '.vmd',
\ }]
```

to have a nearly simple environment using the `markdown` syntax. The requested output is

```
Os: Linux
Vim: 800
Branch: dev
Revision: 4d7a4da
Date: 2021-12-19 00:49:16 -0300
```

I'm heavily using nested lists to structure my notes in the vimwiki and I'm also using different list item styles to easily see on which level the nested element is, e.g.:

```
- first level
    + second level
        * third level
```

When I create this nested list, I'm doing the following based on this [cheat sheet](https://gist.github.com/drkarl/4c503bccb62558dc85e8b1bc0f29e9cb):

1. write `- first level`
2. hit enter
3. go to second level with [ctrl] + [t]
4. go to normal mode with [esc], switch the style with `gl+`,  append with `A` and continue.

Is there a possibility to define some item style dependent on indention level, e.g., ['-', '+', '*']?

**Comment by brennen** [comment]
This sounds possible but also complicated.

**Comment by brennen** [comment]
That said, do note (from `:help vimwiki-list-manipulation`):

```
Use gl followed by the desired symbol to change the symbol of a list item or                                     
create one. Type gL and the symbol to change all items of the current list.                                      
For default syntax, the following types are available:                                                           
    - hyphen                                                                                                     
    * asterisk                                                                                                   
    # hash                                                                                                       
    1. number with period                                                                                        
    1) number with parenthesis                                                                                   
    a) lower-case letter with parenthesis                                                                        
    A) upper-case letter with parenthesis                                                                        
    i) lower-case Roman numerals with parenthesis                                                                
    I) upper-case Roman numerals with parenthesis
```

**Comment by tinmarino** [comment]
Hi @Druidefix, thank you for the idea.

As @brennen said above, the cost is high. I would add that the payback is not so high. I do not know how to prioritize issues for the moment and we have more that 150 issues on the list.
I honestly liked the idea, but I prefer to close this in order to get a better visibility on the issues we cannot procrastinate. Sorry for that.

Closing as won't do.
