### ISSUE TITLE
Could g:vimwiki_global_vars.web_schemes1 be made configurable?

### ISSUE THREAD

**Issue by jpmor** [vimwiki/vimwiki#1223]
This isn't a bug. It seems like intentionally some `vimwiki_global_vars` are not configurable: https://github.com/vimwiki/vimwiki/blob/63af6e72dd3fa840bffb3ebcb8c96970c02e0913/autoload/vimwiki/vars.vim#L36

Just curious why? Could those schemes be defaults in `read_global_settings_from_user` instead?

Sorry if there is a different existing way to add additional schemes that I've missed :P.

**Comment by brennen** [comment]
This has been rearranged a bit on the dev branch - see https://github.com/vimwiki/vimwiki/blob/dev/autoload/vimwiki/vars.vim#L177

As best I understand it, those are the schemes that are:

1. highlighted on their own without link markup like `[[ ]]`
2. expected to be passed off to a system link handler - see [`vimwiki#base#system_open_link()`](https://github.com/vimwiki/vimwiki/blob/dev/autoload/vimwiki/base.vim#L298)

You can set `g:vimwiki_schemes_web` - see `:help g:vimwiki_schemes_web`.  That said, if you want to add a useful scheme, you _may_ want to look at `:help VimwikiLinkHandler` instead.  There are a couple of examples there, but I'll paste mine in case it's useful:

```vim
    " override default vimwiki link handling - could be extended to add
    " custom link types, etc.  Right now all it does is use vim itself
    " to handle files, crudely.
    function! VimwikiLinkHandler(link)
      if a:link =~# '^file:'
        try
          " chop off the leading file: - see :h expr-[:] for syntax:
          execute ':split ' . a:link[5:]
          return 1
        catch
          echo "Failed opening file in vim."
        endtry
      elseif a:link =~# '^workspace:'
        try
          " chop off the leading file: - see :h expr-[:] for syntax:
          execute ':split ' . '~/workspace/' . a:link[10:]
          return 1
        catch
          echo "Failed opening workspace location in vim."
        endtry
      " elseif a:link =~# '^https\?:'
      "    try
      "      execute ':terminal lynx ' . a:link
      "      return 1
      "    catch
      "      echo "Failed executing Lynx."
      "    endtry
      endif
      return 0
    endfunction
```
