### ISSUE TITLE
Covert lines to list (check list)

### ISSUE THREAD

**Issue by madhurachanna** [vimwiki/vimwiki#1224]
Hi, Is their a way to convert multiple lines into Todo-list or any list?

For example:
Convert visually selected lines
```
apple
orange
banana
```
to 
```
- [ ] apple
- [ ] orange
- [ ] banana
```

**Comment by brennen** [comment]
It doesn't seem to be documented very well, but try using the `:VimwikiListToggle` command, and then hit **Ctrl-Space** to turn them into tasks.

There are also a lot of idioms for doing this kind of thing in Vim.

One option: Place your cursor on the `a` in `apple`.  Hit **Ctrl-V**.  Move your cursor to the `b` in `banana`. Hit **I**, type `- [ ] `, hit **Esc**.

Another: **V** for visual selection, select all lines, hit **>>** to indent, then use **Ctrl-V** to select a column in front and replace it with list markers.

If you have existing regular list items selected, **Ctrl-Space** will convert to tasks and then toggle them between done states.
