### ISSUE TITLE
Does vimwiki support latex notation?

### ISSUE THREAD

**Issue by Leticia-maria** [vimwiki/vimwiki#1226]
Hi all, just a quick question (actually, this is not a real issue): is there a way to manage .tex files using vimwiki?

**Comment by brennen** [comment]
Not _really_, although I think there's a little bit of support for math notation with MathJax. I've never used it but see `:help vimwiki-syntax-mathjax`.

As a wiki it only supports the following as first-class syntax:

- its own VimWiki syntax
- A version of Markdown
- A little bit of MediaWiki, although I'm not sure to what extent it still works

**Comment by brennen** [comment]
Closing this, but please comment further if there's something else we can help with here. Implementing TeX support is... Not super likely, it'd just be a ton of work and in my view we already support about 2 markup languages too many to really get any of them right...
