### ISSUE TITLE
Relative links converted to absolute links during HTML generation

### ISSUE THREAD

**Issue by embear** [vimwiki/vimwiki#123]
Hi there,

I'm exposing my generated HTML files of vimwiki over a lighttp server in my local network. But I'm having problems with links to files. I'm using the following settings.

```
let wiki = {}
let wiki.path = /home/user/vimwiki
let wiki.path_html = wiki.path . '/html/'
let wiki.template_path = wiki.path_html
let wiki.template_default = 'template'
let wiki.template_ext = '.thtml'
let wiki.ext = '.vimwiki'
let wiki.nested_syntaxes = {'bash': 'sh', 'c': 'c', 'c++': 'cpp'}
let wiki.auto_toc = 1
let wiki.auto_tag = 1
let g:vimwiki_list += [ wiki ]
```

In vimwiki I use a relative link to a PDF file, for example ``[[local:./data/file.pdf|File]]``. The generated link is the absolute file::// scheme path ``file:&#47;&#47;&#47;home&#47;user&#47;vimwiki&#47;data&#47;file.pdf``. This is a problem when the HTML is delivered by the webserver as the client doesn't have the file in this location. What I would like to get is a relative path like ``..&#47;data&#47;file.pdf`` in the generated HTML also. If I read the documentation correctly this is exactly the purposse of the ``local:`` scheme opposed to the ``file:`` scheme.

Is there a scheme or a setting I am missing.

**Comment by EinfachToll** [comment]
> Is there a scheme or a setting I am missing.

No, it's just a bug. I'm currently working on the absolute/relative path problem anyway, so I hope I can fix it soon.

**Comment by EinfachToll** [comment]
So, now local: and file: are converted to relative or absolute paths, respectifely. Can you try the latest version and see if it does what you want?

**Comment by embear** [comment]
Hi,

the newest version on dev branch works for the "local:" scheme correctly. But I don't think the result for "file:" and "http:" is correct:
```
[[file:path/to/file.pdf|PDF]]
```
gets converted to
```
<a href="&#47;full&#47;path&#47;to&#47;file.pdf">PDF</a>
```
which results in this link destination
```
http://my.server.org/full/path/to/file.pdf
```
and
```
[[http://github.com/vimwiki/vimwiki|vimwiki]]
```
gets converted to
```
<a href="..&#47;..&#47;..&#47;..&#47;https:&#47;&#47;github.com&#47;vimwiki&#47;vimwiki.html">vimwiki</a>
```
which results in this link destination
```
http://my.server.org/https://github.com/vimwiki/vimwiki.html
```

**Comment by EinfachToll** [comment]
HTTP-Links don't need the brackets, it's just `http://github.com/vimwiki/vimwiki`. But then, you can't conceal it with the description. So we probably should allow http: etc. in brackets as well.

But I don't understand this:

> gets converted to

> `<a href="&#47;full&#47;path&#47;to&#47;file.pdf">PDF</a>`

>which results in this link destination

>`http://my.server.org/full/path/to/file.pdf`

What do you mean with "results in this link"? And what's wrong with the HTML output?

**Comment by embear** [comment]
In previous versions the brackets for `http://` links worked fine and that way it was possible to use a custom name for the link.

As for your second question: As written in the initial issue, I use a lighttp server to serve the generated html pages. It seems that lighttp adds the server address to an absolute link automatically. Wouldn't it be better if the link converter adds a "file://" in front of the path? But in general this is not a problem for me as I don't use this scheme. I just tested it because you mentioned in your "please test" comment.

**Comment by EinfachToll** [comment]
So, `http:` links in brackets should work now (again). As for the `file:` problem: URLs starting with `file:` are for linking to files on the client's file system, not on the server's. This may or may not be what you want, so if someone wants a specific behavior, they can use a custom VimwikiLinkConverter function.

**Comment by embear** [comment]
`local:` links and external `http:` links work fine.
As for the `file:`: You are right. The current behavior is most likely the one "normal" user expects.
Thanks!
