### ISSUE TITLE
Error detected while processing function <SNR>17_setup_buffer_leave: line 10: E329: No menu "Vimwiki"

### ISSUE THREAD

**Issue by zhihau** [vimwiki/vimwiki#1231]
**my vimrc**
`set nocompatible              " be iMproved, required
set autochdir "auto change dir
"default open file with utf8 encoding
"if there is a unknown character, use one of the file encodings list to open
"file.
set backspace=indent,eol,start
set encoding=utf-8 fileencodings=ucs-bom,utf-8,cp936,gbk,gb18030,gb2312
"show hidden characters
nnoremap <F4> :set list!<CR>
set spell
" Enable folding
set foldmethod=indent
set foldlevel=99
" Enable folding with the spacebar
nnoremap <space> za

colorscheme ron
set langmenu=en_US
set fileencoding=utf-8
let $LANG = 'en_US'
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
syntax on
set nu
set hls
let g:auto_save = 1
" enable auto format when write. (defaut)
"let g:vfmt = 1
:map <F2> :e $MYVIMRC<CR>
":map <F3> :e $HOME/_link.vim<CR>
" write all tabs and compile run v code
":map <F5> :wa<CR>:!v run "%:r"<CR>
":map <F6> :wa<CR>:!start v run "%"<CR>
:map <F7> :NERDTreeToggle %<CR>
"use default program to open current file
:map <F8> :!start "%"<CR>
"check broken image
":map <F9> :!cmd /k python d:\Bin\check_file_exists.py -d "%:p:h" -e html -i 0 -a img -x "png;PNG"<CR>

filetype plugin indent on    " required
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab
" Put your non-Plugin stuff after this line
call plug#begin('~/.vim/plugged')
Plug '907th/vim-auto-save'
" Error  cat is not internal or external command
"Plug 'zakuro9715/vim-vtools'
"Plug 'ollykel/v-vim'
Plug 'vimwiki/vimwiki'
Plug 'preservim/nerdtree'
call plug#end()
if has("autocmd")
  augroup templates
    autocmd BufNewFile *.c,*.cpp,*.java,*.js,*.php 0r ~/.vim/templates/skeleton.c
    autocmd BufNewFile *.pl,*.py 0r ~/.vim/templates/skeleton.pl
    autocmd BufNewFile *.sh 0r ~/.vim/templates/skeleton.sh
    autocmd BufNewFile *.bat 0r ~/.vim/templates/skeleton.bat
  augroup END
endif
`

**Steps to reproduce the issue**
After I loaded my vimrc with :so %, then switch to another tab or split window the error message will show at bottom of editor. Error detected while processing function 17_setup_buffer_leave: line 10: E329: No menu "Vimwiki"
Does anyone knows how to fix this bug? Thanks

**Vim version**
* My vim is gvim 8.0.568. 
* vimwiki version is 2.5.

**Comment by brennen** [comment]
Ok, so this is coming from 

```vim
" Autocommand called when the cursor leaves the buffer
function! s:setup_buffer_leave() abort
  " don't do anything if it's not managed by Vimwiki (that is, when it's not in
  " a registered wiki and not a temporary wiki)
  if vimwiki#vars#get_bufferlocal('wiki_nr') == -1
    return
  endif

  let &autowriteall = s:vimwiki_autowriteall_saved

  if !empty(vimwiki#vars#get_global('menu'))
    exe 'nmenu disable '.vimwiki#vars#get_global('menu').'.Table'
  endif
endfunction
```

I wasn't able to reproduce the error, but these lines stood out to me:

```
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
```

From the top of `/usr/share/vim/vim81/delmenu.vim` on my system:

```vim
" This Vim script deletes all the menus, so that they can be redefined.
" Warning: This also deletes all menus defined by the user!
```

Maybe try getting rid of those and see if you still get the error?

**Comment by zhihau** [comment]
Hi Brennen,

I try to uncomment this line. The error is gone. I don't know why.

> "source $VIMRUNTIME/delmenu.vim

Thanks a lot for your tips.

Brennen Bearnes ***@***.***> 於 2022年5月22日 週日 上午7:20寫道：

**Comment by brennen** [comment]
Glad I could help!
