### ISSUE TITLE
Proposed: Cut 2.6 release now, move to a rolling release cadence

### ISSUE THREAD

**Issue by brennen** [vimwiki/vimwiki#1235]
This proposal has a few parts.

# part 1: cut a 2.6.0 release from the current state of the dev branch

We're coming up on two years out since the [last official release at 2.5](https://github.com/vimwiki/vimwiki/releases/tag/v2.5).  We routinely advise users to switch to the dev branch. I think the staleness of the mainline branch causes more confusion than it brings benefit in terms of stability.

I know there are outstanding bugs with the current state of dev, but there are also a ton of fixes and feature enhancements. Unless there's anything seriously, seriously broken at the moment, I think we should just release what's there now. We know it's already in use by quite a few of the heaviest users of the plugin.

# part 2: move to a rolling release cadence

Instead of accumulating a lot of PRs into a 2.7 release at some distant point in the future, I suggest that we:

1. Adopt [semver](https://semver.org/)
2. Update the version as appropriate and cut a new release every time a PR is merged

As a side note, it would be nice to [use "main" instead of "master" for the mainline branch](https://github.com/github/renaming). I imagine we would break a lot of setups if we deleted it, but we could use main as the default here and mirror changes to master to support legacy checkouts for the time being.

Or, now that I think about it, we could just use dev as the default branch and treat master as a mirror of that.  That would have the advantage of working with essentially all existing checkouts.

Thoughts?

Also noting that I'm around to discuss this on `#vimwiki` - ping me and I _will_ get back to you, though it might take some hours up to a day or so, depending on what I'm doing.  Often but not always available for realtime conversation:

  - [#vimwiki](ircs://irc.libera.chat:6697/vimwiki) on irc.libera.chat
  - [Connect via webchat](https://web.libera.chat/?channels=#vimwiki)
  - Connect via Matrix/Element: [#vimwiki:libera.chat](https://matrix.to/#/#vimwiki:libera.chat)

cc: @vimwiki/community @vimwiki/contributors @vimwiki/maintainer

**Comment by brennen** [comment]
@Nudin, @tinmarino, @EinfachToll, @ranebrown thoughts here?

**Comment by ranebrown** [comment]
I agree moving to the rolling release is a better approach. Mirroring dev and master would be nice if that can be done automatically.

**Comment by brennen** [comment]
> I agree moving to the rolling release is a better approach. Mirroring dev and master would be nice if that can be done automatically.

If there's a consensus here, I'd be happy to do the work. Unfortunately I'm not currently a member of @vimwiki/maintainer or an owner and don't have the required access.

**Comment by brennen** [comment]
Thanks to @Nudin for setting me up with necessary permissions here. I put together #1282 for bumping version and updating contributor docs if anyone's got thoughts there. After some thought wonder if the overhead of maintaining a version number is worth it in combination with keeping `dev` in a rolling-release state, but at any rate that should work for getting something out the door.

I'll tidy some other things in the coming days. (PR & issue templates, default branch, etc.)
