### ISSUE TITLE
Folding of links, bold etc. does not work inside table

### ISSUE THREAD

**Issue by Lislegaard** [vimwiki/vimwiki#1238]
Normally I can write f.eks. [[my-notes|My notes]] and it will show up as My notes and link to my-notes.wiki.
Also I can write `*This is important*` and it will show up as **This is important**.

When I use the table funtion this does not work.
F.ex.
` | [[my-notes|My notes]] | *This is important*|` shows all the bits instead of hiding it.

Syntax: Default
Versjon: 2.5

<img width="551" alt="Skjermbilde 2022-05-28 kl  14 14 02" src="https://user-images.githubusercontent.com/73965966/170825020-c1351e70-e304-4894-a3b4-be4d21468f81.png">

**Comment by brennen** [comment]
Duplicates #450.
