### ISSUE TITLE
Setting folding in Vimwiki

### ISSUE THREAD

**Issue by EricEWeir** [vimwiki/vimwiki#1239]
Prior to submitting a new issue make sure to complete these steps:

- [ ] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.

**********
I am using markdown syntax.Here’s my vimwiki setup from my .vimrc:

"restrict vimwiki operation to only those paths listed in g:vimwiki_list.
let g:vimwiki_global_ext = 0

"set vimwiki syntax to markdown 
let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown'}]

"add wiki as an extent recognized as a markdown file
autocmd BufRead,BufNewFile *.wiki :set ft=markdown

"set vimwiki syntax to markdown; suggested by brennen on vimwiki github to get
"wiki recognized as a markdown file. But it doesn't work.  
"let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': 'wiki'}]

"convert vimwiki headers to markdown headers
" symmetric: '== title ==' --> asymmetric '## title' for any level of header
nnoremap <Leader>be :%s@^\(\s*\)\(=\+\)\s\+\(.*\)\s\+\2\%(\s*\)$@\=submatch(1).

"enable vimwiki folding

************

When I do “VimwikiShowVersion” I get lNot an editor command.”

***********

My .vimrc has long had “let g:vimwiki_folding=1” for setting folding. It seems I got that from the “Vimwiki 1.1.1 Quick Referencel cheatsheet.”

Recently an error message in terminal informed that that command does not recognize “1” as an option, that only “expr,” “syntax,” and “list” are recognized. I see from the Global Options section of the Vimwiki help pages that that is correct.

I have tried all this options. I get folding with none of them. When I return “let g:vimwiki_folding” to “1” folding is returned.

I have no problem. With “let g:vimwiki_folding=1” I have folding. Curious why the conflict between the cheatsheet and the help pages

**Comment by EricEWeir** [comment]
Also when I do “:verbose :set foldmethod?” I get “foldmethod=manual.” Why donI get this when I have “let g:vimwiki_folding=1” in my .vimrc?

**Comment by brennen** [comment]
> When I do “VimwikiShowVersion” I get lNot an editor command.”

This seems likely to mean you're using an older version of VimWiki.  Try upgrading to _at least_ the latest stable release, v2.5.

**Comment by EricEWeir** [comment]
> On Jun 1, 2022, at 3:48 PM, Brennen Bearnes ***@***.***> wrote:
> 
> When I do “VimwikiShowVersion” I get lNot an editor command.”
> 
> This seems likely to mean you're using an older version of VimWiki. Try upgrading to at least the latest stable release, v2.5.

Thanks. I ran Vim-Plug’s PlugUpdate. Got “Already up to date.” Ran “VimwikiShowVersion” I got “Stable version: 2.5.” In the process I realized that earlier I may have mis-typed the show version command as “ShowVimwikiVersion.:
 
------------------------------------------------------------------------------------------
Eric Weir
Decatur, GA  USA
***@***.***

“Man has been a murderer forever.”

- Peter Matthiessen.

**Comment by jhncondix** [comment]
I am using vimwiki stable version 2.5. in vim 8.2. In my vimrc I have:

let g:vimwiki_list = [{'path': '~/Vimwiki/',
                      \ 'syntax': 'markdown', 'ext': '.md'}]
let g:vimwiki_global_ext = 0
let g:vimwiki_folding = 'custom'
Before this in my vimrc I have these markdown settings for plasticboy/vim-markdown:

let g:vim_markdown_follow_anchor = 1
let g:vim_markdown_autowrite = 1
let g:vim_markdown_edit_url_in = 'tab'
let g:vim_markdown_folding_level = 3
set conceallevel=2 

Result: In markdown files outside Vimwiki I get the expected folding levels and the ability to fold and unfold. But in vimwiki markdown notes there is no folding. I do zR and zM on headings and nothing happens.

**Comment by EricEWeir** [comment]
I may be mistaken. It’s been a while since I was actively using VimWiki. But you may not need plastic boy/vim-markdown. I think it has—it may have—markdown syntax built in. (I hope someone will correct me if I’m mistaken.)

**Comment by jhncondix** [comment]
I decided to google this problem and found a solution here: https://www.reddit.com/r/vim/comments/vkbyfa/vimwiki_and_vimmarkdown_conflicting/
I added this to the above settings in my vimrce as u/godRosko/ suggests:

au BufRead,BufWinEnter,BufNewFile *.{md,mdx,mdown,mkd,mkdn,markdown,mdwn} setlocal syntax=markdown

au BufRead,BufWinEnter,BufNewFile *.{md,mdx,mdown,mkd,mkdn,markdown,mdwn}.{des3,des,bf,bfa,aes,idea,cast,rc2,rc4,rc5,desx} setlocal syntax=markdown

Result: vimwiki now uses my vim-markdown settings - folding works normally with zR and zM etc, and the setting "let g:vim_markdown_folding_level = 3" is respected.
