### ISSUE TITLE
Can not open http links (dev branch)

### ISSUE THREAD

**Issue by lervag** [vimwiki/vimwiki#124]
To reproduce, hit `<cr>` on any http url in any wiki page.

The problem started with commit 6922836a0cbfb7e539bb1cf458eb8f1619d6188f by @EinfachToll (found with a simple `git bisect`). In particular, it seems [this](https://github.com/vimwiki/vimwiki/commit/6922836a0cbfb7e539bb1cf458eb8f1619d6188f#diff-20a89d6c9c99a3ed4a8b8995f2fe4244R551) line is the main reason it fails now.

**Comment by EinfachToll** [comment]
Should be fixed now.

**Comment by lervag** [comment]
Thanks, this seems to indeed fix the problem. I had to update my own link handler, though, so I guess one should update the docs concerning how the link handler function is written.

**Comment by EinfachToll** [comment]
Can you specify what exactly should be updated? (Or make a pull request.)

**Comment by lervag** [comment]
The documentation for the custom linke handler, see `:h VimwikiLinkandler`. In the latest version, you've changed the argument into a dictionary, while in the docs it is a string similar to `scheme:url`.

**Comment by lervag** [comment]
Nice, good work!
