### ISSUE TITLE
Vimwiki overwrites virtual line nav remaps

### ISSUE THREAD

**Issue by dtjohnst** [vimwiki/vimwiki#1248]
Prior to submitting a new issue make sure to complete these steps:

- [ *] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [ *] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [ *] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [ *] Include the output of `:VimwikiShowVersion`.

1. 'dev' branch checked out as per ':VimwikiShowVersion':

    Os: Linux
    Vim: 800
    Branch: dev
    Revision: 61c513d
    Date: 2022-04-09 20:14:04 -0400

2. Syntax and settings:

    " wimwiki settings
    let g:vimwiki_list = [ {
        \ 'path'             : '~/wiki',
        \ 'index'            : 'index',
        \ 'syntax'           : 'markdown',
        \ 'ext'              : '.md',
        \ 'links_space_char' : '-'
        \ } ]

    let g:vimwiki_ext2syntax = {
        \ '.md'       : 'markdown',
        \ '.markdown' : 'markdown',
        \ '.mdown'    : 'markdown'
        \ }

    let g:vimwiki_markdown_link_ext = 0

    " other relevant settings
    noremap  <buffer> <silent> k gk
    noremap  <buffer> <silent> j gj
    noremap  <buffer> <silent> 0 g0
    noremap  <buffer> <silent> \\$ g\\$ " there is no \\ before the dollarsign but this breaks github markdown it seems

3. Description of Problem

I prefer virtual line navigation and have remapped j, k, 0 and $ as indicated in included settings so they do that. If I open the index from the CLI (ie `nvim ~/wiki/index.md`) then it works correctly *on the index page only*. But once a page is navigated to using a vimwiki command (either pressing `Enter` on a link or `<leader>ww` or any other method, the remap is broken; the keys behave in their default manner skipping virtual lines and navigating on logical lines only. I would prefer to be able to navigate with virtual lines rather than logical. Is there someway to do this that prevents vimwiki from overwriting them?

**Comment by brennen** [comment]
Just noting I wasn't able to reproduce this.

What do you get if you run `:verbose map j` after this happens?  It should tell you where the mapping was last set, which might point to a culprit.

**Comment by tinmarino** [comment]
Closing <= stagned.

Please follow brennen advise above to troubleshoot, Vimwiki is not unmapping anymap so it should be in your config, maybe an autocommand, etc.
