### ISSUE TITLE
How TF do I close vimwiki?

### ISSUE THREAD

**Issue by LrnzDC3696** [vimwiki/vimwiki#1249]
How do I close vimwiki? my current solution is just :bd.

**Comment by marrs** [comment]
@LrnzDC3696 I've taken to having a separate `wiki` command that calls `gvim path/to/index.wiki`.  That way, my session doesn't get cluttered up with wiki buffers that I don't need, and I don't lose whatever file I was originally working on before I opened the wiki.

You can do the same in the terminal with an alias (or shell script).  For example, `alias wiki='vim path/to/index.wiki'`.

You can actually run that from inside vim itself by typing `:!wiki`.  That will run vim within vim, as it were.  `:q` will restore your parent vim session.  Finally, for bonus points, you could rebind your `[Leader]ww` key combo to that command.

Hope this helps.
