### ISSUE TITLE
Documentation contains many non-ssl links

### ISSUE THREAD

**Issue by fwolfst** [vimwiki/vimwiki#1253]
The documentation [`doc/vimwiki.txt`](https://github.com/vimwiki/vimwiki/blob/63af6e72dd3fa840bffb3ebcb8c96970c02e0913/doc/vimwiki.txt#L1134) contains many http (vs httpS) links.
I can create a PR replacing most or all of these, if wanted.
Most of these redirect to a https anyway (so, we save a roundtrip for the users browser).

**Comment by brennen** [comment]
> I can create a PR replacing most or all of these, if wanted.

Sounds good!  Please do make sure that links in question load via https.

**Comment by tinmarino** [comment]
Done, thank you @fwolfst for the idea
