### ISSUE TITLE
[Feature Request] Creating directories for each 'branch'

### ISSUE THREAD

**Issue by aboss10123** [vimwiki/vimwiki#1255]
The idea being if the user wants to they would have the option of creating a directory for a 'branch' of the vimwiki. This will mean that in the wiki folder there would be folders and subfolders. the reason for this being is that it would be easier to navigate through a file browser or via the terminal. And also allow you to name files with the same names as they are in different directories so they wont clash. This is good for very large wikis. You would also have to make it so that if you are referencing a specific file in some subfolder of a directory then you would have to write the entire path than just simply putting in the name, but I would think that is a good compromise if you are having the names of each file or directory be simpler. Obviously I don't know how hard this is to implement but I think its a good feature to have.

**Comment by brennen** [comment]
As far as I can tell, what you want is already supported. There's no concept of branches, but pages can be placed in subdirectories, and the link syntax supports a range of ways to reference them.

Try making a link like `[[foo/bar]]` - you'll be taken to `foo/bar.wiki`.

From there, you can link to pages in other directories with relative paths like `[[../baz]]` or absolute paths from the root of the wiki `[[/baf/foo.wiki]]`.  A link like `[[blah]]` will take you to `foo/blah.wiki`.

If you want more encapsulation, you can also just define multiple wikis, and link between them with interwiki links:

`[[wiki1:foo]]`

`[[wiki2:foo]]`

For background on that, see `:help vimwiki-syntax-links` and look for the "Interwiki" section.

(Examples assume default syntax.)
