### ISSUE TITLE
Change working path of wiki files on keybind

### ISSUE THREAD

**Issue by systemb4** [vimwiki/vimwiki#1259]
[Feature Request]

Having a vimwiki command to be able to change the current working path of wiki files to be able to different paths for different wikis would be very helpful. Something like <code>:VimwikiPath ['path']</code> would be very useful.
<br>

let g:vimwiki_list = [{
            \ 'auto_diary_index': 1,
            \ 'path': '/home/name/doc/vimwiki/',
            \ 'syntax': 'markdown',
            \ 'ext': '.md',
            \ 'path_html': '/home/name/doc/vimwiki/html_doc/'
            \ }]

Stable version: 2.5

**Comment by brennen** [comment]
Can you elaborate on this?  I'm not exactly sure what you're asking for.

You can currently switch between wikis with `[number]<Leader>ww`.

**Comment by systemb4** [comment]
> 

Oops, you are right! I must have not dug that deep into the documentation. Thank You!

For anyone wondering how to configure this its in section 12 of the help page <code>:help vimwiki-option</code>
