### ISSUE TITLE
Pressing <leader>ww to open index wiki file resulting in E21

### ISSUE THREAD

**Issue by deadlytackler5** [vimwiki/vimwiki#126]
Using Windows7
Installed VIM 7.4 in E:\
:echo $HOME - C:\Users\akk

Installed vimwiki through Pathogen
Downloaded Zip file , Pasted in vimfiles\bundle

As suggsted changed gvimrc with -
        set nocompatible
	syntax on
	filetype plugin indent on

helpfile is opening, however pressing Qww resulting in E21

What else is needed?

**Comment by EinfachToll** [comment]
Hmm, why do you press Qww? The `<leader>` key is usually not Q but `\` (the backslash key), if you didn't specify otherwise.

**Comment by deadlytackler5** [comment]
I set the "Q"  as leader, strange however \ worked. Thanks

**Comment by EinfachToll** [comment]
If you set the mapleader in your .vimrc, it should normally work. If you set it somewhere else, it might not work, because it has to be set **before** Vimwiki (and other plugins) are loaded.
