### ISSUE TITLE
Feature: Support for <mark> in Markdown

### ISSUE THREAD

**Issue by folofjc** [vimwiki/vimwiki#1261]
Similar to #1045, it would be great to have support for `<mark>` and `</mark>` tags in markdown. Basically doing some conceal on the tags when not on this line (like for bold, italic, etc) and "highlighting" it in some way. Many Markdown editors show things within the `<mark>` and `</mark>` tags as highlights.

Many Markdown editors also use `==Highlighted Text==`, but this would break the vimwiki header syntax, so that doesn't seem feasible. Although maybe if there is no space between the `==` and the text, or if there is more text on the same line?

**Comment by tinmarino** [comment]
From: https://www.w3schools.com/tags/tag_mark.asp

```css
mark {
  background-color: yellow;
  color: black;
}
```


![Screenshot from 2023-03-17 03-23-15](https://user-images.githubusercontent.com/6123962/225828574-d41f7718-5d3d-4773-a5f0-1e6f1ca26cf2.png)

**Comment by tinmarino** [comment]
Closing <= Implemented in 8374bcfccfba9 present in the dev branch

![Screenshot from 2023-03-17 03-39-54](https://user-images.githubusercontent.com/6123962/225832570-2195f28b-36a2-40c9-8f31-39735fe21431.png)
