### ISSUE TITLE
Vimwiki Error "E65" on gvim with Markdown

### ISSUE THREAD

**Issue by jspille** [vimwiki/vimwiki#1265]
I installed Vimwiki and get the Error "E65"

### My observations:

1. My first observation is, that the word "House" is converted to a link `[House](House)` if I press Enter, but the word "123abc" is not converted, without error message. However, "2022Today" is again converted.
2. Everything seems to be fine, until I create a second diary file and press Enter on a word, then I get the error E65.

### How to reproduce the issue:

Start with the settings below and an empty wiki:

1. "\<leader\>ww" and insert the words: "House 123abc" convert both words to links by pressing `Enter`. Result will be: `[House](House) 123abc`. The "123abc" will not be converted.
2. "\<leader\>w\<leader\>w" and insert "Today", convert it to a link: Result will be "`[Today](Today)`"
3. "\<leader\>w\<leader\>m" and insert "Tomorrow", convert it to a link: **Result will be E65.**
4. if I got back to step 2 and extend the file, the same Error occurs again.

**BUT!** If I rename the diary file from `2022-09-03.md` to something like `my2022-09-03.md`, then it is working again, without error!

*A workaround might be to add a prefix to the dairy file name, but how? Just an idea. It looks like that the Windows path seperator `\` in combination with a following number in the file name might cause the issue. Just guessing.*

### Error Message:

> Error detected while processing function vimwiki#base#follow_link[89]..vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[5]..<SNR>46_normalize_link_syntax_n[48]..vimwiki#base#is_diary_file:
> 
> **E65: Illegal back reference**

### Installation:

- : **VimwikiShowVersion** => Stable Verion: 2.5
- Running on Windows10 and 11 (64 bit) - Test done on two PCs. 
- with gvim.exe Version
  - VIM - Vi IMproved **9.0** (2022 Jun 28, compiled Jun 28 2022 12:46:00)
  - MS-Windows 32-bit GUI version with OLE support

### _vimrc: (not other commands, just this few lines) 

```
set nocompatible
filetype plugin on
syntax on

" vim-plug section
call plug#begin('c:\DataProg\PortProg\Vim9.0\Plugged')
Plug 'mattn/calendar-vim'
Plug 'vimwiki/vimwiki'
call plug#end()

" Vim Wiki
let g:vimwiki_list = [{'path': 'c:\VimWikiData\',
    \'syntax': 'markdown',
    \'ext': '.md'}]
```

  
<eof>

**Comment by jspille** [comment]
I download the dev version from 23.8.2022 and it seems to work w/o E65. However, the `123abc` issue still exist. I will continue to test this dev version.

**Comment by jspille** [comment]
I have tested the dev version form 23.8.2022 on gVim 9.0 on Windows for 7 days now. No E65 anymore.

**Comment by brennen** [comment]
Sounds like this is resolved?
