### ISSUE TITLE
g:vimwiki_table_mappings=0 does not disable <tab> mapping in local buffer

### ISSUE THREAD

**Issue by john-shupe-amteck** [vimwiki/vimwiki#1268]
I have set `g:vimwiki_table_mappings=0` in my .vimrc file, closed vim and console completely, reloaded vim and the <tab> mapping is still visible in `:verbose imap`.
I am on the dev branch of the project. I am using markdown syntax. Below are my .vimrc settings followed by the output of `:VimwikiShowVersion`.

```vimrc
let g:vimwiki_table_mappings=0
```

```
Os: Linux
Vim: 801
Branch: dev
Revision: 584f073
Date: 2022-08-23 16:48:01 -0600
```

I have spent a few hours reading previous issues (#461 and #669) on here with the same problem and following their suggested solutions but still cannot get this to work. 

I am using this with UltiSnips but I believe the issue I am currently experienceing is outside of their interactions.

**Comment by brennen** [comment]
I wasn't originally sure about the reasoning, but the changelog for the 2.5 release shows:

```
Removed:~
    * PR #698: Remove awa check triggering silent file edits.
    * Options g:vimwiki_use_mouse and g:vimwiki_table_mappings. These are
      still present in the code for backwards compatibility but have been
      removed from the documentation and will be fully removed at a later
      point.
```

Digging a bit further, it looks like #686 added `g:vimwiki_key_mappings`.

You probably want something like:

```vim
    " disable table mappings:
    let g:vimwiki_key_mappings =
      \ {
      \ 'table_mappings': 0,
      \ 'table_format': 0
      \ }
```
