### ISSUE TITLE
Is it possible to get the TODO, DONE, STARTED, FIXME, FIXED, XXX tags for .todo style to color code each tag separately?

### ISSUE THREAD

**Issue by dallasspohn** [vimwiki/vimwiki#1275]
Prior to submitting a new issue make sure to complete these steps:

This is a request:
- [  ] Include the output of `:VimwikiShowVersion`. 
  - Stabe version 2.5

**Comment by dallasspohn** [comment]
Also how would I change the tags to use what we use at Redhat. i.e. started, PR Review, Arch Review, etc.

**Comment by tinmarino** [comment]
This does not exist currently in Vimwiki. It a very customizable feature which stands better in your personal vimrc.
Still I will note it as enhancement ideas. Meanwhile you can implement it youself in your configuration file


Add the following in file: `.vim/after/syntax/vimwiki.vim `

```vim
syntax keyword myTODO TODO
highlight myTodo ctermfg=124 guifg=#cc241d
```

Or more intensively

```vim
for [keyword, ctermfg, guifg] in [
      \ ['TODO', 124, '#cc241d'], 
      \ ['DONE', 106, '#98971a'], 
      \ ['STARTED', 66, '#d79921'], 
      \ ['FIXME', 132, '#458588'], 
      \ ['FIXED', 72, '#689d6a'], 
      \ ['XXX', 166, '#d65d0e'], 
![Screenshot from 2023-03-13 17-47-25](https://user-images.githubusercontent.com/6123962/224829098-c17b0e58-1b97-4989-8288-b01b5abfdafa.png)

      \ ]
  execute 'syn keyword my' . keyword . ' ' . keyword
  execute 'hi my' . keyword . ' ctermfg=' . ctermfg . ' guifg=' . guifg 
endfor
```

To get this:
![Screenshot from 2023-03-13 17-47-25](https://user-images.githubusercontent.com/6123962/224829169-d4677595-6347-49e2-946d-f69dbfb2ddf5.png)
