### ISSUE TITLE
Fix/Improvement: When re-wrap a long line in a definition by 'gq' it should insert ':: ' at the new line

### ISSUE THREAD

**Issue by cmon1701** [vimwiki/vimwiki#1279]
Hello,
when I re-wrap a long line in a definition by 'gq' it should insert ':: ' at the new line, so that the definition continues and is not treated as a new paragraph.

It should behave like an item, when doing 'gq', a long item line gets re-wrapped with two spaces at the new line (by the way, how or where is this coded?).

Thanks! 
I am using stable Version 2.5, so special configuration in .vimrc

**Comment by tinmarino** [comment]
That would be a nice feature, it is implemented [here](https://github.com/vimwiki/vimwiki/blob/738e24134ee02c6755e38412929bc6190392ae59/ftplugin/vimwiki.vim#L138-L152), see `:h comments`.

I am on it to add :: prefixs

**Comment by tinmarino** [comment]
Related to #915 for adding the blockquote prefix when pressing enter. Finally it is in the blockquote_markers syntax variable, as pointed to en [imap <CR> => CR function => vimwiki#lst#kbd_cr](https://github.com/tinmarino/vimwiki/blob/0069c5fb4e00608094d4f4570be97a7b76cac7cb/autoload/vimwiki/lst.vim)

**Comment by tinmarino** [comment]
Closing <= Fixed in the dev branch

Fixed adding "::" to "&comments" and also to syntax var "blockquote_markers".

Thank you @cmon1701  for the report, please checkout to the dev branch to get the fix.
