### ISSUE TITLE
Syntax highlighting for code

### ISSUE THREAD

**Issue by marlun** [vimwiki/vimwiki#128]
It would be nice if vimwiki could syntax highlight code if entered using the ```language syntax just like github does or like https://github.com/xolox/vim-notes is able to do. If for example I write ```php the following code will be highlighted using the vim php syntax. Works really great in vim-notes.

**Comment by EinfachToll** [comment]
That's already possible, see `:h vimwiki-option-nested_syntaxes`.

**Comment by marlun** [comment]
Was hoping for such an answer. Could this not be possible without having to define which nested syntaxes I want to use and just use the one I specify?

**Comment by EinfachToll** [comment]
Not in an easy way, because you have to somehow detect that the user starts to write a new code section and then load the syntax definition file of the nested syntax from Vim's runtime path. That's not possible, at least not efficiently.
