### ISSUE TITLE
Syntax highlighting initially set to "markdown" instead of "vimwiki" when opening an .md file from command line

### ISSUE THREAD

**Issue by sdondley** [vimwiki/vimwiki#1283]
I've got a minimal neovim config using packer to load plugins:

```
return require('packer').startup(function(use)
  use { 
          { 'wbthomason/packer.nvim', opt = false },
          { 'christoomey/vim-tmux-navigator',	    opt = false, cond = true },
          { 'jebaum/vim-tmuxify', 		    opt = false, cond = true },
          { 'vimwiki/vimwiki', branch = 'dev',
                               opt = 'true',
                               ft  = 'vimwiki',
                               },
      }
end)
```

The `init.lau` file looks like this:

```
vim.cmd[[
let mapleader=';'
syntax on
filetype on
set nocompatible
set mouse=a
set clipboard=unnamedplus
set background=dark
set tabstop=4
set hlsearch
set incsearch
set expandtab
set number
set cpt=.,w,b,u,t
set softtabstop=4
set shiftwidth=4
set autoindent
set number
set backupdir=~/.cache/nvim
set ignorecase
set smartcase
set timeoutlen=400
set fo-=c
set fo-=o
set fo-=r
set fo+=t
]]
require('plugins')
vim.cmd[[set syntax=vimwiki]]   " <<<--------------- NOTICE that syntax is explicitly set here
```

When I first open an `*.md` file, `:verb syntax?` returns:

```
  syntax=markdown
        Last set from /usr/local/Cellar/neovim/0.8.1/share/nvim/runtime/syntax/syntax.vim line 34
```

So the syntax is set to `markown`.

Running `:e` command or closing and then reopening the file fixes things:

```
  syntax=vimwiki
        Last set from /usr/local/Cellar/neovim/0.8.1/share/nvim/runtime/syntax/syntax.vim line 34
```

Why is syntax/syntax.vim setting the highlighting to markdown initially?

**Comment by brennen** [comment]
> Why is syntax/syntax.vim setting the highlighting to markdown initially?
> 

Am I correct in thinking you:

1. Don't have any specific configuration for VimWiki beyond loading the plugin, and are just using the defaults?
2. Are loading a Markdown file in an existing wiki?

You may just need to set the `syntax` option for that wiki.  See `:help vimwiki-option-syntax`.

**Comment by sdondley** [comment]
The filetype is recognized as a vimwiki file as soon as it is opened. So I have no idea why it's using markdown syntax highlighting. Doesn't make any sense to me.

**Comment by sdondley** [comment]
I tried reproducing on docker image, I could not. Also, the problem somehow cleared itself up on my main machine after randomly playin with config settings. But still not sure why this odd behavior occurred.
