### ISSUE TITLE
YAML/front matter syntax highlighting

### ISSUE THREAD

**Issue by basilioss** [vimwiki/vimwiki#1287]
After updating to version 2022.12.02 or specifically after [this](https://github.com/vimwiki/vimwiki/commit/fc056cfecadc24887dff8df184b66fcd9ee69f14) commit YAML/front matter syntax is broken as you can see in the image bellow. Is there a way to disable SetExt heading highlighting? Better yet, could you add a proper YAML highlighting?

![image](https://user-images.githubusercontent.com/71596800/205858950-6057578e-f92f-4fca-a746-0c7c8cc35812.png)

Here's an example of how [Obsidian](https://obsidian.md/) handles YAML block:

![image](https://user-images.githubusercontent.com/71596800/205861932-8b72b7aa-4ad6-48da-9214-9d52d5426a78.png)

**Comment by zmingee** [comment]
In case anyone else comes here looking for a short-term fix until it's addressed upstream, if you're using `pandoc` to generate your HTML pages the second set of `---` can be substituted for `...`. It's still not highlighted as YAML, but it at least removes the annoying invalid highlighting.

https://pandoc.org/MANUAL.html#extension-yaml_metadata_block

![image](https://user-images.githubusercontent.com/6311084/224584408-da468c75-8ceb-4b74-9898-95cd4ecbabdf.png)
![image](https://user-images.githubusercontent.com/6311084/224584440-5e30e0ce-506e-4321-bf07-298a9379f712.png)

**Comment by tinmarino** [comment]
Hello @basilioss,

Thank you for the report and the workaround.
Vimwiki highlight your line as a VimwikiHeader2 as it believes it is an heading.
I overlooked this fact but now that you report it I will have a look in order to get a pretty Yaml title highlighting feature like highligthing the titles and getting and `---` separator.

**Comment by tinmarino** [comment]
Commit 8bf4d63 should have fixed it highlithing this as a YAML region.
@zmingee or @basilioss can you please confirm?

---

![Screenshot from 2023-03-13 16-55-57](https://user-images.githubusercontent.com/6123962/224818234-16fce683-ea47-469e-92f8-3b897f0f1423.png)


From: https://pandoc.org/MANUAL.html#extension-yaml_metadata_block

A YAML metadata block is a valid YAML object,
* Delimited by a line of three hyphens (---) at the top and a line of three hyphens (---) or three dots (...) at the bottom.
* The initial line --- must not be followed by a blank line.
* A YAML metadata block may occur anywhere in the document, but if it is not at the beginning, it must be preceded by a blank line.

**Comment by zmingee** [comment]
It's partially fixed, AFAICT. When using `---`/`---`, it works as expected. But with `---`/`...` it breaks rendering for me.

![image](https://user-images.githubusercontent.com/6311084/224822071-d06ee285-e9ce-4c6c-9291-79dcaf1de419.png)
![image](https://user-images.githubusercontent.com/6311084/224822124-144ee089-5db1-41c6-90f9-60d296523097.png)

**Comment by tinmarino** [comment]
Thank you @basilioss, I misred the spec, this should be fixed, can you check again please?

**Comment by basilioss** [comment]
@tinmarino Thank you for implementing this feature! Everything works fine for me, including rendering with `---`/`...`.
