### ISSUE TITLE
Incompatability with (Packer) lazy-loading

### ISSUE THREAD

**Issue by ag-eitilt** [vimwiki/vimwiki#1288]
This is likely not a bug per se given it's an external subversion of the expected (Neo)vim behaviour, but I previously had Packer set to only load vimwiki when I specifically interacted with it (filetype and/or command), and that seemed to break its wiki detection and management.

Symptomatically, if I ran `:VimwikiUISelect` without having opened something of the right filetype I'd get some placeholder line not corresponding to any of the three wikis I defined, and (more critically) if *did* open a markdown file beforehand it would *always* show the second wiki as being active no matter what wiki I was actually in.  Less visibly but perhaps even more disruptively, absolute links were similarly borked and always tried opening within that second wiki (and absolute links within that wiki might have been treated as relative; I didn't test that layer as far, and I've not even installed Packer in classic vim).

Like I said, since this is all in the interactions with a third-party tool and since the resolution is simply "don't lazy-load vimwiki" (it's completely fine in Packer otherwise) I don't think it's necessarily something which even needs to be fixed, but I wanted to report it just so y'all were aware and in case anyone else was searching for info after trying to do the same.

**Comment by brennen** [comment]
At minimum, we should probably document this one, since I think it's biting a fair number of users.  I have no idea if there's an easy fix, but it's something to investigate.

**Comment by jmacias1503** [comment]
> Bit of a necropost, sorry, but this is also the case with lazy.nvim. I tried setting vimwiki to load on wiki or markdown filetypes and roughly half of the commands would show up, if any. I discovered this as i could not get `:VimwikiFollowLink` to work.
> 
> As stated previously, i don't know if there's much that can be done here (i've never been any good at vimscript., but i suppose it would be nice if this worked.

Having something probably similar with lazy

**Comment by tinmarino** [comment]
Closing <= workaround exists in lazy.vim and below <= Thank @jmacias1503 for the following solution

See @folke [comment in lazy.vim](https://github.com/folke/lazy.nvim/issues/408).
> Literally replace config with init

And @jmacias1503 [comment](https://github.com/vimwiki/vimwiki/issues/1319#issuecomment-1477256835) in #1319.

```vim
return {
   'vimwiki/vimwiki',
   init = function () --replace 'config' with 'init'
      vim.g.vimwiki_list = {{path = '~/Docs/Mywiki', syntax = 'markdown', ext = '.md'}}
   end
}
```

**Comment by tinmarino** [comment]
Also, if someone step on the same problem, Vimwiki variables can be reloaded with

```vim
unlet g:vimwiki_syntaxlocal_vars
call vimwiki#vars#init()
```

> A `force` parameter and some documentation would be nice, I admit.


This helps me troubleshoot those issues:

```vim
" Print
echo vimwiki#vars#get_wikilocal('path', 0)
" Bad: /home/mtourneb/vimwiki/
echo g:vimwiki_list
" Good: [{'path': '~/Test/Wiki', 'ext': '.md', 'syntax': 'markdown'}]

" Reload
unlet g:vimwiki_syntaxlocal_vars
call vimwiki#vars#init()

" Print
echo vimwiki#vars#get_wikilocal('path', 0)
" Good: /home/mtourneb/Test/Wiki/
```
