### ISSUE TITLE
question: wikiname -> html links converstion

### ISSUE THREAD

**Issue by patrickdavey** [vimwiki/vimwiki#129]
Hi there,

I love vimwiki and use it all the time.  I currently use it in (github) markdown format and use a little rubygem I created to convert the `md` to `html` files.  That's all working fine.  As a part of the linking process, I take the `title` of the page, and use [parameterize](http://apidock.com/rails/ActiveSupport/Inflector/parameterize) to convert the names to be web safe.  So, for example `[[My Happy Page]]` becomes - `my-happy-page.html`

My ruby script runs quite slowly however, but most of that is down to the fact that `vimwiki` doesn't correctly skip the files, as, of course, the names don't match.  I was wondering if you would accept a pull request to at least make the sanitization configurable.  Say it could have a default, but if you supplied a function name it would call out to that.

My own first very crude approximation is here:
https://github.com/patrickdavey/vimwiki-1/blob/with_my_sanitized/autoload/vimwiki/html.vim#L242-248

With that in place it drops from a minute to a few seconds to generate changed files. I need to work out how to correctly delete files, that's not done at the moment, but it'll use similar code I guess.

Anyway, love vimwiki, happy to maintain my own fork, but thought I'd ask.

**Comment by ranebrown** [comment]
@patrickdavey It looks like you are still maintaining the gem you created. Is this issue still something that needs addressed?

**Comment by ranebrown** [comment]
Looks like you have this as a known issue in your README. If you are willing to create a PR against the `dev` branch I will review and merge it.

**Comment by patrickdavey** [comment]
@ranebrown thanks for getting in touch. It's more of a nice-to-have rather than a must have. Basically the issue is that the [vimwiki_markdown gem](https://github.com/patrickdavey/vimwiki_markdown) alters the filenames it writes out. If your wiki is called `Foo Bar.md` it gets written to disk as `foo-bar.html`.

I'll try make time to look at `vimwiki` and see how easy it is to configure what I need. It's probably a bit hard to fully fix the issue (as there are tags like `%title` which make things hard), but, I'll aim to make the filename that vimwiki checks against match what [active supports paramaterized method does](https://apidock.com/rails/ActiveSupport/Inflector/parameterize)

**Comment by patrickdavey** [comment]
@ranebrown I updated my `dev` spike -> https://github.com/vimwiki/vimwiki/compare/dev...patrickdavey:dev?expand=1 

One issue I need to fix is the way that `vimwiki` deletes files which don't match, I need to fix that up (or else have an option to turn off deleting unmatched files)

What's the nicest way to get this configuration into `vimwiki` ?

1. configuration option for sanitization- `g:vimwiki_html_filename_sanitization` true|false ? (and default to false, current behavior ?

If there's a better way, I'm keen to hear it.

**Comment by ranebrown** [comment]
Yep, using a global option defined [here](https://github.com/vimwiki/vimwiki/blob/dev/autoload/vimwiki/vars.vim#L143-L192) (0/1 value) and then checking its value with `vimwiki#vars#get_global()` should do the trick.

I would prefer not to have another option to turn off deleting the files. Maybe reverse the paramaterized name first?

**Comment by patrickdavey** [comment]
Yip sounds good, and yes I agree, checking the reversed name is the approach I'd use 👍

**Comment by patrickdavey** [comment]
Actually, thinking about it a little more, it's not _really_ a reversible process. For example, all of `my-doc.md` `My-Doc.md` `my doc.md` and `MY DOC.md` would all become `my-doc.html`. The only way I can think of to check the reverse process (for deleting) would be to build up a list of all the possible paramaterized file names and then check against those each time.  Doesn't seem that elegant .

Maybe I'll just add in the sanitisation option (as that's probably useful anyway) and I can just leave a note about turning off deleting (unless you're happy to have an extra variable to allow that to be turned off).

**Comment by ranebrown** [comment]
If all of those files end up with the same name after sanitization how are there not conflicts when accessing the html files?

**Comment by patrickdavey** [comment]
I guess the answer is "there could be" conflicts, but, in practice this is very unlikely to happen. The only way you'd get a conflict is if you're intentionally spelling links the same and hoping to differentiate on spacing / capitalization. Even vimwiki itself tries to protect you from this (as far as I can see)

For example:

```
[[hello world]]
[[Hello World]]
```

Both of those vimwiki links will create the file `hello world.md`, so, at least as far as capitalization vimwiki is doing it's own downcasing. But yes, if I have `[[hello-world]]` and `[[hello world]]` as wikilinks, that would cause a conflict using my `vimwiki_markdown` gem as I would write both to the file `hello-world.html`, but, in vimwiki proper they would go to `hello world.html` and `hello-world.html`.

I haven't yet had anyone complain about this though ;) But, totally reasonable if you think the paramaterization is a bad feature. I'm happy to have this issue closed, and I can just put a note on [vimwiki_markdown](https://github.com/patrickdavey/vimwiki_markdown)

**Comment by ranebrown** [comment]
If you're feeling ambitious I think a hash table using the filename as the key and the sanitized html name as the lookup value would work to check if a file needed deleted. This would prevent dead files in the html output directory but isn't a deal breaker.

The other option would be to disable deletion as you mentioned. I think it would make sense to automatically disable deletion if the `g:vimwiki_html_filename_sanitization` option is set and just have a note in the help file. Is there any reason why a second option to disable deletion would be better?

**Comment by patrickdavey** [comment]
:) Yip, I agree, the hash table and filename key would be the way to go. In the interests of _actually getting something out and then getting something better out later ;) _ ... how about

1. We add the `g:vimwiki_html_filename_sanitization` boolean which just does active-support like paramaterization to the filenames (so it'll match the files that vimwiki_markdown produced) and which also disables the deleting of files
2. _later_ if I can wrap my head around vimscript I'll add the hash table lookup idea.

The only thing I don't _really like_ about this whole thing, is that it's really just helpful for `vimwiki_markdown` so I wonder if it should really get into your codebase at all :( . I mean, if `g:vimwiki_html_filename_sanitization` was turned on for `vimwiki` itself, it would actually break all of your links (as I'm not planning on fixing the way vimwiki itself rewrites links).  Still, if you're happy to merge it in, great :)

**Comment by ranebrown** [comment]
Sounds like a solid plan.

It makes sense to go ahead with this for two reasons:
1. Your gem is one of the only ways to convert markdown syntax vimwiki to html.
2. We already support and document integration with third party plugins such as calendar and tagbar.

As long as the documentation makes the behavior of the option clear and specifies it is only for integration with `vimwiki_markdown` I don't see it being a problem. Also, this should actually probably be a wiki local option instead of a global option so it can be enabled selectively for wikis that use markdown syntax. Cheers! 🍻
