### ISSUE TITLE
How to add the OS's CPU/Memory/Network at the top of the vim?

### ISSUE THREAD

**Issue by sihunqu123** [vimwiki/vimwiki#1290]
I found this is very useful when reading the readme of this git repo.
![image](https://user-images.githubusercontent.com/22839917/208056025-8e44d25b-63ab-48d3-8a44-e84ce3452bb6.png)

Can someone tell when what Plugin does the git repo using to achieve this?

Thanks.

**Comment by claman** [comment]
I think this might be a case of the person who took the screenshot using [iTerm](https://iterm2.com). It's a terminal emulator for macOS.
