### ISSUE TITLE
Using swap files

### ISSUE THREAD

**Issue by Deviner75** [vimwiki/vimwiki#1293]
I'm getting this error almost for every file even tho I save it with :wq
How do you avoid it?
I'm using nvim

```
Using swap file "~/.local/state/nvim/swap// {...} 1.wiki.swp"
Original file "~/mywiki/Essay 1.wiki"
Recovery completed. You should check if everything is OK.
(You might want to write out this file under another name
and run diff with the original file to check for changes)
You may want to delete the .swp file now.
```

https://user-images.githubusercontent.com/31226325/210206159-0aff873a-52e0-4bf8-890f-7114bb4f0803.png

Version: 2022.12.02
Os: Linux \ Arch
Vim: 800
Branch: dev
Revision: fea8bee
Date: 2022-12-04 21:25:52 -0700

**Comment by brennen** [comment]
Did you perhaps have a crash or unexpected power loss, and wind up with a bunch of swapfiles that just need deleted?

**Comment by Deviner75** [comment]
Hello Brennen, nothing like that, well, it's not every file that does it ofc, but quite often
Should it save it automatically in theory?

**Comment by tinmarino** [comment]
Hello @Deviner75,

Swapfiles are created during your vim session in case someone want to modify it at the same time. Additionally, it is an historical method used before persistent undo feature in. Read `:h swapfile` for more information.

The point is that you never need swapfiles, so just add `no swapfile`  to your vimrc and, after removing the last swapfiles created form past sessions, this problem will not come back.

I don' t think this is vimwki related but we can help you troubleshoot it.

Please close the issue when you found a solution, or assign it back to me for more information.

And ... have fun!
