### ISSUE TITLE
Table formatting breaks on multibyte separator

### ISSUE THREAD

**Issue by druckdev** [vimwiki/vimwiki#1297]
Prior to submitting a new issue make sure to complete these steps:

- [X] Include the VimWiki settings from your `.vimrc`:
```
if (!exists('g:vimwiki_syntax_list'))                     
	let g:vimwiki_syntax_list = {}                        
endif                                                     
if (!has_key(g:vimwiki_syntax_list, 'markdown'))          
	let g:vimwiki_syntax_list['markdown'] = {}            
endif                                                     
let g:vimwiki_syntax_list['markdown']['rxTableSep'] = '│' 
```
- [X] Include the syntax you are using (~default~ / Markdown / ~MediaWiki~) 
- [X] Include the output of `:VimwikiShowVersion`:
```
Version: 2022.12.02
Os: Linux
Vim: 800
Branch: dev
Revision: fea8bee382b2
Date: 2022-12-04 21:25:52 -0700
```
- [X] Provide a detailed description of the problem including **steps to reproduce the issue**:

## Description

When setting a multibyte table separator (e.g. vertical box drawing character / Unicode U+2502), the table formatting breaks and clears the whole table.

## Steps to reproduce

1. `:VimwikiTable`
2. Move the cursor into the new table (which is generated with the correct separator)
3. Enter insert mode
4. Exit insert mode

**Comment by tinmarino** [comment]
Closing <= Fixed by PR #1298
