### ISSUE TITLE
Markdown `[text](link)` backlinks don't work anymore

### ISSUE THREAD

**Issue by nesaro** [vimwiki/vimwiki#1300]
I used to be able to get `VimwikiBacklinks` to see all the links from other files with the syntax `[text](link)` , but after the last update they stopped working

Instead `VimwikiBacklinks` shows backlinks made with the `[[link]]` syntax.

This is unexpected because links made while pressing <enter> on text have the `[text](link)` syntax
vimwiki related settings:
```
call plug#begin('~/.vim/plugged')
Plug 'mileszs/ack.vim'
Plug 'godlygeek/tabular'
Plug 'vimwiki/vimwiki'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim', {'commit': '4145f53f3d343c389ff974b1f1a68eeb39fba18b'}
Plug 'https://github.com/Alok/notational-fzf-vim'
Plug 'savq/melange'
Plug 'junegunn/goyo.vim'
Plug 'https://github.com/mattn/calendar-vim'
Plug 'jlanzarotta/bufexplorer'
Plug 'git@github.com:papis/papis-vim.git'
call plug#end()

let g:vimwiki_list = [{'path': '~/wiki/',
                      \ 'syntax': 'markdown', 'ext': '.md', 'auto_diary_index':1}]
```
version

```
Version: 2022.12.02
Os: Linux
Vim: 800
Branch: master
Revision: fea8bee
Date: 2022-12-04 21:25:52 -0700
```

**Comment by Deviner75** [comment]
Hello nesaro, it seems to work for me.
with Markdown and links like [text](link)

Version: 2022.12.02
Os: Linux
Vim: 800
Branch: dev
Revision: fea8bee
Date: 2022-12-04 21:25:52 -0700

![image](https://user-images.githubusercontent.com/31226325/214216820-ffa13795-7989-497a-8548-5a17a0274161.png)

**Comment by nesaro** [comment]
Thanks for checking.

Looking at it again, I noticed that this pattern only happens when there is a directory involved.

example in my `index.md`
```
...
1: [ ](p/permanent_index) 2: [[permanent_index]] 3: [[p/permanent_index]]
...
```

when I run VimwikiBacklinks from p/permanent_index.md I get:

```
wiki/index.md|27 col 55|             
```

which is the column for link number 3. If I remove link number 3 in `index.md`:
```
1: [ ](p/permanent_index) 2: [[permanent_index]]   
```

then VimwikiBacklinks returns nothing for that line

**Comment by tinmarino** [comment]
Works fine on the dev branch
