### ISSUE TITLE
Failure to highlight code, bold, italic if it ends in `\` after `63af6e72`

### ISSUE THREAD

**Issue by lmburns** [vimwiki/vimwiki#1303]
**Settings**:
```lua
g.vimwiki_folding = ""
g.vimwiki_hl_headers = 1
g.vimwiki_conceallevel = 2
g.vimwiki_commentstring = "<!--%s-->"

g.vimwiki_ext2syntax = {
    [".Rmd"] = "markdown",
    [".rmd"] = "markdown",
    [".md"] = "markdown",
    [".markdown"] = "markdown",
    [".mdown"] = "markdown"
}
g.vimwiki_list = {
    {
        path = "~/vimwiki",
        syntax = "markdown",
        ext = ".md",
        bullet_types = {"-", "*", "+"}
    }
}
g.vimwiki_key_mappings = {
    all_maps = 1,
    global = 1,
    headers = 1,
    text_objs = 1,
    table_format = 1,
    table_mappings = 0,
    lists = 1,
    links = 1,
    html = 1,
    mouse = 0
}
```

**Syntax**: markdown

`:VimwikiShowVersion`:

```
Version: 2022.12.02
Os: Linux
Vim: 801
Branch: master
Revision: fea8bee
Date: 2022-12-04 21:25:52 -0700
```

**Problem**:
After the commit `63af6e72`, a code snippet, bold text, or italic text are no longer highlighted correctly if it ends in a backslash. That is, none of the following end the highlight on the closing pair of symbols and instead highlights the rest of the document. All three examples below *fail*.

```
`$\`
**$\**
*$\*
```

After that same commit, if I try to use bold or italic within parenthesis, they are no longer highlighted either. The examples below all *fail*. A code snippet within parenthesis works just fine.

```
(*italic*)
(**bold**)
```

However, if a space is added either right after the opening parenthesis, then highlighting works correctly. The following examples all *succeed*.

```
( *italic*)
( **bold**)
(`code`)
```

---

**Problem that isn't related to that commit**:
If part of word is to be italicized or boldened, the highlighting is also messed up. The following examples all *fail*.

```
w*or*d
w**or**d
```

A code snippet *succeeds* though.

```
w`or`d
```

**Comment by tinmarino** [comment]
You are right. We did not like to emphasis `or` in `w**or**d` but this is the markdown specification, see [left flanking delimiter](https://github.github.com/gfm/#left-flanking-delimiter-run).

I'll go for this one and report here on completion as I implemented the typeset region highlighting in topic here. Thank you for the nice report with regression examples, it will make implementation and test easy.

From: https://markdowntohtml.com/

![Screenshot from 2023-03-09 16-17-02](https://user-images.githubusercontent.com/6123962/224132758-8376725d-af99-4428-9f7d-abf65e3bbdba.png)


```markdown
1: `$\`<br/>
2: **$\**<br/>
3: *$\*<br/>
4: (*italic*)<br/>
5: (**bold**)<br/>
6: ( *italic*)<br/>
7: ( **bold**)<br/>
8: (`code`)<br/>

11: \`notcode\`<br/>
12: \*not italic\*<br/>
13: \_\_not bold\_\_<br/>

21: w*or*d<br/>
22: w**or**d<br/>
23: w`or`d<br/>
```

**Comment by tinmarino** [comment]
Fixed in dev branch, see test cases at [test/syntax_markdown_gfm_typeface.vader)](https://github.com/vimwiki/vimwiki/blob/6d4208157da068ac8a1128ccd5c1b0d74a589e00/test/syntax_markdown_gfm_typeface.vader).

Thank again @lmburns for the very explicit report.
