### ISSUE TITLE
Vimwiki custom paths not working in Neovim

### ISSUE THREAD

**Issue by Azkaas** [vimwiki/vimwiki#1305]
Hi, Ive used vimwiki in the past without any problems, but its been a while since i used it last.
I recently moved from packer to lazy in Neovim, but for some reason my paths arent working.

Im not completely sure if it has something to do with my config, or if something has changed with Vimwiki since i havent used it in a while. Here is my config:

![image](https://user-images.githubusercontent.com/112915552/220128298-cc427516-9439-4f62-8ea1-648da4c11647.png)

**Comment by Azkaas** [comment]
I managed to find the issue. Apparently when using Lazy, you want to have vim.g commands under init = function(), not config = function()

**Comment by khiet** [comment]
> I managed to find the issue. Apparently when using Lazy, you want to have vim.g commands under init = function(), not config = function()

Thank you @Azkaas, this got me as well 👍
