### ISSUE TITLE
Why is "filetype=vimwiki" when using markdown syntax?

### ISSUE THREAD

**Issue by PhilippFeO** [vimwiki/vimwiki#1306]
I have rather a question than an issue. Why is the output of `set filetype?` equal to `filetype=vimwiki` on my `index.md`?

The only hint on this topic I've found is the following thread on [vi.stackexchange](https://vi.stackexchange.com/questions/16528/mardown-files-always-have-vimwiki-filetype-vimwiki-plugin) saying this behavior is intended, now I am interested in the why. :)

---

- [x] Include the VimWiki settings from your `.vimrc`
```lua
vim.g.vimwiki_list = {{
        path = '~/.vimwiki/',
        syntax = 'markdown',
        ext = '.md',
    }}
vim.g.vimwiki_global_ext = 0
```
- [x] Include the syntax you are using (default / Markdown / MediaWiki)
*Markdown*

- [ ] ~Provide a detailed description of the problem including **steps to reproduce the issue**.~  
*No problem just a question*

- [x] Include the output of `:VimwikiShowVersion`.
```
Version: 2022.12.02                                                                         
Os: Linux                                                                                   
Vim: 800                                                                                    
Branch: dev                                                                                 
Revision: fea8bee                                                                           
Date: 2022-12-04 21:25:52 -0700 
```

**Comment by brennen** [comment]
VimWiki uses its own filetype and implementation of Markdown syntax rather than relying on other filetypes / plugins.

You can see this in `syntax/vimwiki.vim` and `syntax/vimwiki_markdown_custom.vim`.

**Comment by joaoandreporto** [comment]
If markdown is needed, I think the following can be used to register the markdown filetype for vimwiki files:

```vimrc
let g:vimwiki_filetypes = ['markdown']
```

The filetype will get set to "vimwiki.markdown".

The help files mention:
> WARNING: this option can allow other plugins to overwrite vimwiki settings and operation so take care when using it. 
> Any plugin that uses a set filetype will be enabled.
