### ISSUE TITLE
Feature request: image caption and referencing

### ISSUE THREAD

**Issue by horror-vacui** [vimwiki/vimwiki#1309]
Two related feature request related to handling images:
- Is it possible to add figure captions to images in vimwiki syntax? It would be nice to know what the image is about in vim when the filename isn't descriptive enough, and it would be definitively useful for the generated html view.
- Is it possible to refer back to an existing figure with a hyperlink (i.e. I do not want to include the image multiple times, but I would like to have a hyperlink, which will bring the reader to the location of the image in the html file)

I've not found these features in my current vimwiki, but I think they are useful for a knowledge management system.

**Comment by brennen** [comment]
> Is it possible to add figure captions to images in vimwiki syntax? It would be nice to know what the image is about in vim when the filename isn't descriptive enough, and it would be definitively useful for the generated html view.

It looks like alt text is supported (search for "Transclusion" in `:help vimwiki`):

> Transclude image with alternate text:
>  `{{https://raw.githubusercontent.com/vimwiki/vimwiki/master/doc/splash.png|Vimwiki}}`
> in HTML:
>  `<img src="https://raw.githubusercontent.com/vimwiki/vimwiki/master/doc/splash.png" alt="Vimwiki"/>`

I assume you're asking instead for a [`<figure>` tag with a `<figcaption>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption)? That's not currently supported.  I suppose it could be added using a similar approach to how CSS is currently handled for images:

> Transclude image with alternate text and some style:
>  `{{http://.../vimwiki_logo.png|cool stuff|style="width:150px;height:120px;"}}`
> in HTML:
>  `<img src="https://raw.githubusercontent.com/vimwiki/vimwiki/master/doc/splash.png" alt="cool stuff" style="width:150px; height:120px"/>`

> Is it possible to refer back to an existing figure with a hyperlink (i.e. I do not want to include the image multiple times, but I would like to have a hyperlink, which will bring the reader to the location of the image in the html file)

Headers, tags, and bold text currently provide anchors you can link to - see `:help vimwiki-anchors`. I don't think there's a way to just define an anchor at the moment.

**Comment by tinmarino** [comment]
Closing <= full answer by @brennen above.
