### ISSUE TITLE
supertab doesn't work with vimwiki 

### ISSUE THREAD

**Issue by hrrybrwn** [vimwiki/vimwiki#131]
Hi guys,

I'm using SuperTab regularly to autocomplete english words.

Supertab does work in any regular file.

But when I use SuperTab in a file.wiki file, Supertab doesn't work anymore. For example, when try to tab the word "acknow", I get a tab instead of a list of possible completions.

I'm not a expierienced vim user yet, so I hope you can help me solve this issue.

Here is a link to my .vimrc
http://pastebin.com/EFu4K9w1

**Comment by EinfachToll** [comment]
Vimwiki maps the tab key to jumping to the next cell when editing a table. You can try to disable this mapping by putting this line into you vimrc:
`let g:vimwiki_table_mappings = 0`

**Comment by hrrybrwn** [comment]
This solved my issue. Thank you very much!

**Comment by sjfloat** [comment]
This workaround doesn't appear to work for me anymore.
