### ISSUE TITLE
Add an only-one buffer to control vimwiki

### ISSUE THREAD

**Issue by awelormro** [vimwiki/vimwiki#1310]
Prior to submitting a new issue make sure to complete these steps:

- [ ] Include the VimWiki settings from your `.vimrc`
- [ ] Include the syntax you are using (default / Markdown / MediaWiki) 
- [ ] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [ ] Include the output of `:VimwikiShowVersion`.

It is not an issue at all, just a suggestion for everyone who has vimwiki enabled with tons of another buffers active and need space when you get into a very nested wiki, or lots of files opened, here's how I've achieved this:

Tested in Vim 9 under Arch Linux, with the vimwiki dev version 
```vim
function Opencloselinks()
  let s:name=execute(":echo bufnr()")
  execute 'VimwikiVSplitLink move_cursor|'
  execute 'wincmd h'
  execute 'bd '.s:name
endfunction
```

**Comment by tinmarino** [comment]
Hi @awelormro,

Thank you for sharing.

I do not understand well what it does, I understand that it closes some buffer and windows as you open links as new windows with VSplit.

Closing as no addition is expected.

Cheers,
