### ISSUE TITLE
Can't enable syntax highlighting for codes in HTML files when converting wiki to HTML

### ISSUE THREAD

**Issue by lefthairynut** [vimwiki/vimwiki#1311]
Hi. I really really love this project and can't live without it but I have an annoying problem that I couldn't resolve it on my own.
The problem is I can't enable syntax highlighting for the codes in my wikis when I convert them to HTML. 
The only time I can get it to work(sort of) is when I assign a custom `pygmentize` command to `g:vimwiki_listing_hl_command` which is in my `.vimrc` down below.
here's my `.vimrc`
```
inoremap jk <ESC>

set shiftwidth=4
set tabstop=4
set expandtab
set hidden
set number
set relativenumber
set nocompatible
filetype plugin on
syntax on
call plug#begin()
Plug 'vimwiki/vimwiki'
call plug#end()
let g:vimwiki_listing_hl = 1
let g:vimwiki_listing_hl_command = 'pygmentize -f html -O style=default -O noclasses=True'
```

For example, this is my wiki:
```
{{{type=py
if (a == 2):
    print("2")
else:
    print("other")
}}}
```
And here's how the converted HTML file ([source code](http://0x0.st/HzCk.html)) looks like:
![Screenshot_2](https://user-images.githubusercontent.com/30195179/223430008-dfd7183c-67f6-4913-886e-790f44261692.png)
All the codes are in one line .New lines should be `<br>` but instead they're shown as `\n`.

Any help is appreciated. 

Vimwiki Version:
```
Version: 2022.12.02
Os: Linux
Vim: 900
Branch: dev
Revision: fea8bee
Date: 2022-12-04 21:25:52 -0700
```

**Comment by tinmarino** [comment]
Closing <= Fixed by 40c2bbdcf3f93

It was a quoting error `'\n'` versus `"\n"`. Thank you @lefthairynut for the report. Please update your dev branch to get the fix.
