### ISSUE TITLE
Does alternative tag syntax change how we build .vimwiki_tags?

### ISSUE THREAD

**Issue by trev-dev** [vimwiki/vimwiki#1316]
Ref: https://github.com/vimwiki/vimwiki/issues/922

I switched my tags to `#tag1 #tag2` with `g:vimwiki_tag_format`, swapped all my tags to suit this new format.  The syntax highlighting works!  However if I `:VimwikiRebuildTags` my tag file gets emptied.

Is this working as intended?

**Comment by tinmarino** [comment]
Hello @trev-dev,

Thank you for the report. Vimwiki is not parsing tags in heading due to [this line](https://github.com/vimwiki/vimwiki/blob/91fe25ad5f1d89ab9442a67b46d38d08a1e48ce5/autoload/vimwiki/tags.vim#L120).

```vim
continue " tags are not allowed in headers
```

I commented out this line in the commit refering to this issue (in dev).


---

To repeat the issue, I added this in vimrc:

```vim
let g:vimwiki_tag_format = {'pre_mark': '#tag1', 'post_mark': '#tag2', 'sep': '|'}
```

Then you can see the regex the tag parsing it looking for with:

```vim
:VimwikiVar tag_format
" Out: Vimwiki: Got: tag_format = {'pre_mark': '#tag1', 'sep': '|', 'conceal': 0, 'post_mark': '#tag2', 'cchar': '', 'post': '\s\|$', 'in': '[^:''[:space:]]\+', 'pre': '^\|\s'}   " <= From: Wikilocal

echo vimwiki#vars#get_syntaxlocal('tag_search')
" Out: \%(^\|\s\)\%(#tag1\)\zs\%([^:'[:space:]]\+\)\%(\%(|\)\%([^:'[:space:]]\+\)\)*\ze\%(#tag2\)\%(\s\|$\)

:VimwikiRebuildTags!
```

**Comment by tinmarino** [comment]
Fixed by 035b2f1 in dev branch. Assigning to @trev-dev. Please close if OK or assign back to me if more changes are required

# Before fix

Only 3 tags generated

![Screenshot from 2023-03-16 22-56-14](https://user-images.githubusercontent.com/6123962/225802889-aac0d6b9-3936-4f04-a6cb-9ff02e6c8c38.png)

# After fix

The 4 tags are generated

![Screenshot from 2023-03-17 00-09-37](https://user-images.githubusercontent.com/6123962/225802949-c7600bd8-c48d-4b0d-8440-12dbf9d323b8.png)

**Comment by trev-dev** [comment]
@tinmarino Thanks for the help and the detailed response so far.

Since I know that these matches should apply to building tag quickfix lists and I'm not misunderstanding the intention of `g:vimwiki_tag_format`, Here is a better example.

Here is an example document, the tags are `vim` and `momo`:

```markdown
# This is a document about Vim
#vim #momo

Blah blah blah
```

I have tried numerous patterns since your recent commits to match this.  The highlighting works, the rebuild tags file does not.

```vim
g:vimwiki_tag_format = { 'pre_mark': '#\w\@=', 'post_mark': '', sep: ' ' }
```

The tagfile sorta follows, but sorta does not:
```log
!_TAG_FILE_FORMAT	2
!_TAG_FILE_SORTED	1
!_TAG_OUTPUT_MODE	vimwiki-tags
!_TAG_PROGRAM_AUTHOR	Vimwiki
!_TAG_PROGRAM_NAME	Vimwiki Tags
!_TAG_PROGRAM_URL	https://github.com/vimwiki/vimwiki
!_TAG_PROGRAM_VERSION	2022.12.02
#momo	vim/momo_vim_tips.md	11;"	vimwiki:vim/momo_vim_tips\tvim/momo_vim_tips#vim-momo\tvim #momo
```
The vim tag is missed entirely, and using `:VimwikiSearchTags vim` or `:VimwikiSearchTags momo` are fruitless

**Comment by tinmarino** [comment]
Checkout to the new dev branch (I added a change permitting tag in heading)
Try something like 

```vim
let g:vimwiki_tag_format = {'pre_mark': '#\w\@=', 'post_mark': '', 'sep': '[#[:space:]]\+', 'in': '[^#:[:space:]]\+' }
```

Gave me

```
!_TAG_FILE_FORMAT	2
!_TAG_FILE_SORTED	1
!_TAG_OUTPUT_MODE	vimwiki-tags
!_TAG_PROGRAM_AUTHOR	Vimwiki
!_TAG_PROGRAM_NAME	Vimwiki Tags
!_TAG_PROGRAM_URL	https://github.com/vimwiki/vimwiki
!_TAG_PROGRAM_VERSION	2022.12.02
momo	issue-1316.md	2;"	vimwiki:issue-1316\tissue-1316#vim-momo\tvim #momo
vim	issue-1316.md	2;"	vimwiki:issue-1316\tissue-1316#vim-momo\tvim #momo
```

**Comment by trev-dev** [comment]
@tinmarino 
This works in terms of building the `.vimwiki_tags` file, *but* the `:VimwikiSearchTags vim` or `:VimwikiSearchTags momo` still turn up empty.  Great progress so far!

```
!_TAG_FILE_FORMAT	2
!_TAG_FILE_SORTED	1
!_TAG_OUTPUT_MODE	vimwiki-tags
!_TAG_PROGRAM_AUTHOR	Vimwiki
!_TAG_PROGRAM_NAME	Vimwiki Tags
!_TAG_PROGRAM_URL	https://github.com/vimwiki/vimwiki
!_TAG_PROGRAM_VERSION	2022.12.02
momo	linux_and_tools/index.md	4;"	vimwiki:linux_and_tools/index\tlinux_and_tools/index#vimmomo\tvim#momo
vim	linux_and_tools/index.md	4;"	vimwiki:linux_and_tools/index\tlinux_and_tools/index#vimmomo\tvim#momo
```

**Comment by tinmarino** [comment]
Commit b06d3bc in dev branch should fix the issue with `VimwikiSearchTags` which was only search for `:tag:` with this format (hardcoded).

@trev-dev may you please check again? By the way, that you for your nice report containing easy regression tests.

**Comment by trev-dev** [comment]
I am happy to be as thorough as I can. I know maintaining stuff is hard.  If I were better at vimscript, could have been a pull request instead.

It looks like you've smoothed out the rough edges and the tag searches work :D
