### ISSUE TITLE
Error when opening nvim with latest vimwiki

### ISSUE THREAD

**Issue by bitterhalt** [vimwiki/vimwiki#1317]
Prior to submitting a new issue make sure to complete these steps:

- [ ] Include the VimWiki settings from your `.vimrc`
`        use {'vimwiki/vimwiki',
            config = function()
                vim.g.vimwiki_list = {
                    {
                        path = '~/Documents/.vimwiki/',
                        syntax = 'markdown',
                        ext = '.md',
                    }
                }
            end
        }
`

- [ ] Include the syntax you are using (default / Markdown / MediaWiki) 
Markdown
- [ ] Provide a detailed description of the problem including **steps to reproduce the issue**.
When i open nvim I got this stranger error if I install Vimwiki 
![2023-03-17_21-31](https://user-images.githubusercontent.com/95308907/226006250-35bb8440-9674-4a0f-ae91-bccd6e89f2a6.png)

- [ ] Include the output of `:VimwikiShowVersion`.

Version: 2022.12.02                                                                                                                                                        
Os: Linux
Vim: 801
Branch: dev
Revision: 8640988
Date: 2023-03-17 16:08:27 -0300

**Comment by bitterhalt** [comment]
I tested to this with allmost clean Nvim. Issue does not happen if i disable markdown.

**Comment by loiccoyle** [comment]
I get the same behaviour.

**Comment by loiccoyle** [comment]
I think its because of a stray `echom` left in `vars.vim`:

https://github.com/vimwiki/vimwiki/commit/8640988c5c46c00255c09111cc158b8e16ffb5af#diff-dbb8fde5360bf7f23246e959eccdc9bcedd075a938f8f6f101be4676c214cb4bR1370

**Comment by tinmarino** [comment]
Thank you guys for the fast report. My bad, I pushed a debug echom. Sorry for that. It is fixed 5eb5c9c71f8b as @loiccoyle  pointed.

**Comment by bitterhalt** [comment]
> Thank you guys for the fast report. My bad, I pushed a debug echom. Sorry for that. It is fixed [5eb5c9c](https://github.com/vimwiki/vimwiki/commit/5eb5c9c71f8b04dc8221fdeb7d31353994cd1c1b) as @loiccoyle pointed.

Well that was fast. Thank you!
