### ISSUE TITLE
Vimwiki doesn't load user configs with lazy.nvim for markdown syntax

### ISSUE THREAD

**Issue by jmacias1503** [vimwiki/vimwiki#1319]
# Main issue

Just migrated to [lazy.nvim](https://github.com/folke/lazy.nvim), and started having troubles setting up the markdown syntax

Doesn't log any error, it just won't load, my `lua/plugins/vimwiki.lua` looks like this: 
```lua
return {
   'vimwiki/vimwiki',
   config = function ()
      vim.g.vimwiki_list = {{path = '~/Docs/Mywiki', syntax = 'markdown', ext = '.md'}}
   end
}
```
When I load  `VimwikiIndex`, asks me for the default config of the `.wiki` file, don't know if someone had that problem before

## Version of Vimwiki

```
Version: 2022.12.02
Os: Linux
Vim: 801
Branch: dev
Revision: 72d0220
```

Have tried also to moving the config to the `after` directory
Maybe related with #1288

**Comment by brennen** [comment]
I've experience with lazy.nvim specifically, but lazy-loading under at least one other plugin manager is known not to work.  See #1288.

**Comment by brennen** [comment]
> I've no experience with lazy.nvim specifically, but lazy-loading under at least one other plugin manager is known not to work. See #1288.

(Sorry, see you already mentioned that. It's been a long day.)

**Comment by jmacias1503** [comment]
Just found out a [solution](https://github.com/folke/lazy.nvim/issues/408), just a syntax problem with [lazy.nvim](https://github.com/folke/lazy.nvim), hope this helps anyone

**Comment by tinmarino** [comment]
Nice @jmacias1503 , thank you very much.

**Comment by omaru-ok** [comment]
@jmacias1503 thx so much , i was having path issue too

**Comment by calon** [comment]
Unfortunately, not working for me with Lazy.nvim
the file type is vimwiki.markdown, but when I trigger VimwikiFollowLink command, vimwiki creates mediawiki style link, not opening the existed markdown file
turns [title](link) to [[[title]]](link)

the syntax and ext configs are below, but it still treats the markdown file as wiki style

```
{ "vimwiki/vimwiki",
        branch = "dev",
        init = function()
            vim.g.vimwiki_list = {
                {path = '~/Note/Inbox', syntax = 'markdown', ext = '.md', auto_tags = 1},
            }
            vim.g.vimwiki_key_mappings = {table_mappings = 0}
        end,
    },
```

Version info:

```
Version: 2023.05.12
Os: Windows
Vim: 801
Branch: dev
Revision: 0bb1b49
Date: 2023-10-31 13:45:18 -0300
```
