### ISSUE TITLE
VimwikiRebuildTags generates duplicate entries

### ISSUE THREAD

**Issue by jplanisky** [vimwiki/vimwiki#1326]
`VimwikiRebuildTags` generates duplicate entries if there are multiple non-concatenated tags on a line.  

- `:test_1:test_2:test_3:` generates correct entries in `.vimwiki_tags`
- `:test_4: :test_5: :test_6:` generates 2 entries for `test_5` and 3 entries for `test_6` in `.vimwiki_tags`
 
### VimWiki settings from your `.vimrc`
```
let vimwiki_main = {}
let vimwiki_main.path = '~/vimwiki/'
let vimwiki_main.path_html = '~/vimwiki_html/'
let vimwiki_main.auto_export = 0
let vimwiki_main.auto_toc = 0
let vimwiki_main.auto_diary_index = 0
let vimwiki_main.auto_generate_tags = 0
let vimwiki_main.auto_tags = 0

let vimwiki_old = {}
let vimwiki_old.path = '~/vimwiki_old/'
let vimwiki_old.path_html = '~/vimwiki_old_html'
let vimwiki_old.auto_export = 0
let vimwiki_old.auto_toc = 1
let vimwiki_old.auto_diary_index = 1

let g:vimwiki_list = [vimwiki_main, vimwiki_old]
let g:vimwiki_dir_link = 'index'
let g:vimwiki_hl_headers = 1
let g:vimwiki_folding = 'syntax'
let g:vimwiki_global_ext = 0
let g:vimwiki_emoji_enable = 0

nmap <Leader>k <Plug>VimwikiDiaryPrevDay
nmap <Leader>j <Plug>VimwikiDiaryNextDay

" Use a template for new diary pages.
au BufNewFile ~/vimwiki/diary/*.wiki :silent 0r !~/.vim/bin/vimwiki-diary-template.sh '%'
```

### syntax you are using
Default

### Steps to reproduce the issue

1. Create a standard Vimwiki page with one line tagged with multiple concatenated tags and another line with multiple separate tags.  Example:  
```
Tag bug demo


This line contains concatenated tags :test_1:test_2:test_3:

This line contains separate tags :test_4: :test_5: :test_6:
```
2. Run `:VimwikiRebuildTags`
3. Examine `.vimwiki_tags` and note duplicate entries for `test_5` and `test_6`    
```
test_1	vimwiki/TagTest.wiki	4;"	vimwiki:vimwiki/TagTest\tvimwiki/TagTest#test_1\tvimwiki/TagTest#test_1
test_2	vimwiki/TagTest.wiki	4;"	vimwiki:vimwiki/TagTest\tvimwiki/TagTest#test_2\tvimwiki/TagTest#test_2
test_3	vimwiki/TagTest.wiki	4;"	vimwiki:vimwiki/TagTest\tvimwiki/TagTest#test_3\tvimwiki/TagTest#test_3
test_4	vimwiki/TagTest.wiki	6;"	vimwiki:vimwiki/TagTest\tvimwiki/TagTest#test_4\tvimwiki/TagTest#test_4
test_5	vimwiki/TagTest.wiki	6;"	vimwiki:vimwiki/TagTest\tvimwiki/TagTest#test_5\tvimwiki/TagTest#test_5
test_5	vimwiki/TagTest.wiki	6;"	vimwiki:vimwiki/TagTest\tvimwiki/TagTest#test_5\tvimwiki/TagTest#test_5
test_6	vimwiki/TagTest.wiki	6;"	vimwiki:vimwiki/TagTest\tvimwiki/TagTest#test_6\tvimwiki/TagTest#test_6
test_6	vimwiki/TagTest.wiki	6;"	vimwiki:vimwiki/TagTest\tvimwiki/TagTest#test_6\tvimwiki/TagTest#test_6
test_6	vimwiki/TagTest.wiki	6;"	vimwiki:vimwiki/TagTest\tvimwiki/TagTest#test_6\tvimwiki/TagTest#test_6
```
Note that the duplicate entries are generated even if there are other non-tag words between the tags. E.g. 
```
I submitted the :VimWiki: tag bug on the issues page on :GitHub: today.
```
results in 2 entries for `GitHub`.

### Output of `:VimwikiShowVersion`
```
Version: 2023.04.04
Os: Linux
Vim: 802
Branch: HEAD
Revision: 71edcf6
Date: 2023-04-04 20:28:34 -0600
```

**Comment by jplanisky** [comment]
I think I have a fix for this, but it will take me some time to get familiar with the testing framework and write tests for it.

**Comment by jplanisky** [comment]
I'm almost ready to create the PR for this fix, but I need some clarification.   In CONTRIBUTING.md, it says (or implies) that I need to update the version number in a couple places.   Is that really something I do prior to creating the PR for a bug fix, or is that done by a maintainer when the PR is accepted and merged? (I'm a noob with PRs on Github )

**Comment by tinmarino** [comment]
Hi @jplanisky,

Thank you for volunteering a PR <= "nothing worth the force of a volunteer 😎" (Pearl Harbor movie).

That is a good question, in short, do not worry with the release number, let the maintener car for that. Try to add your name in the credits though.
For details:  I (maintainer) also have trouble to update version at each change. Besides, this makes no sense for PR as you cannot know when we will merge it.

So it would be great if you could share your fix in a PR, no bureaucracy expected from you.

Cheers

**Comment by tinmarino** [comment]
**Closing <= Fixed by 1349**

Thank you very much @jplanisky, that was a good, easy to integrate fix.

Please feel encouraged to make other PRs on Vimwiki, when you have a coding motivation, please have a look to [good first issues](https://github.com/vimwiki/vimwiki/labels/good%20first%20issue)
