### ISSUE TITLE
vimwiki default start location

### ISSUE THREAD

**Issue by JunkyardCat** [vimwiki/vimwiki#1328]
Im using vim 9.0 on windows 10 and was wondering how i can change my default start location
I already added let g:vimwiki_root_dir = pathtofile to my _vimrc but still wouldnt start in that path i specified
Im not using any package manager and vimwiki is installed in vimfiles folder under my user folder not the c programs folder

**Comment by JunkyardCat** [comment]
Anyone can help?

**Comment by claman** [comment]
That setting your vimrc should be `let g:vimwiki_list = [*path and extension here*]`, as per the docs

**Comment by tinmarino** [comment]
`:h vimwiki_list`

What I do is

```vim
let g:vimwiki_list = []
let g:vimwiki_list += [{
  \ 'path': '$h/wiki/wiki',
  \ 'path_html': '$h/wiki/wiki_html'
  \ }]
```

Replace `$h/wiki/wiki` by your path
