### ISSUE TITLE
Upgraded Fedora 37 to 38: Error detected while processing BufRead Autocommands for "*.wiki"..function 

### ISSUE THREAD

**Issue by philiprhoades** [vimwiki/vimwiki#1329]
People,

Opening a .wiki file now gives:

Error detected while processing BufRead Autocommands for "*.wiki"..function <SNR>30_setup_new_wiki_buffer[19]..vimwiki#u#ft_set[9]..FileType Autocommands for "*"..Syntax Autocommands for "*".
.function <SNR>3_SynSet[25]..script /home/phr/.vim/plugged/vimwiki/syntax/vimwiki.vim[554]..function vimwiki#emoji#apply_conceal:
line    3:
E844: Invalid cchar value
E475: Invalid argument: VimwikiEmoji :key: conceal cchar=<bf>?

I can't see what the problem is . . 

call plug#begin('~/.vim/plugged')
" served from GitHub:
Plug 'vimwiki/vimwiki'
call plug#end()

Version: 2023.04.04
Os: Linux
Vim: 900
Branch: master
Revision: 71edcf6
Date: 2023-04-04 20:28:34 -0600

**Comment by tinmarino** [comment]
Closing <= duplicated #1339

In short: disable emoji
