### ISSUE TITLE
Link to another wiki?

### ISSUE THREAD

**Issue by hrrybrwn** [vimwiki/vimwiki#133]
How can I link a wiki to another wiki outside current directory?

For example: my default directory is on `/home/user/wiki/index.wiki` and I would like to link a wiki in `/mnt/usb/anotherwiki/index.wiki`.

When I put the link `[[wiki#:///mnt/usb/anotherwiki/index.wiki]]` in my default wiki, it creates subdirectories within the current directory, instead of linking to another directory where the other wiki already exist.

**Comment by EinfachToll** [comment]
You need to register both wikis, see `:h vimwiki-register-wiki`. Then, the correct link would be simply `[[wikiX:index]]`, where X is the number of the wiki in /mnt/usb/anotherwiki/. Note that the count starts at zero, so if it's the second one defined in g:vimwiki_list, your link would become `[[wiki1:index]]`. See `:h vimwiki-syntax-schemes` for more details.

**Comment by hrrybrwn** [comment]
Thank you again sir.
