### ISSUE TITLE
[Feature] Application link handling

### ISSUE THREAD

**Issue by awilkins** [vimwiki/vimwiki#1330]
I'm wanting to handle links to applications that use custom protocol names ; e.g.

`obsidian://`  
`slack://`

etc.

I guess the simplest thing would be to hand them off to the browser, which has ways of handling them, but it might also be nice to create your own handlers (map a specific handler to running a particular command with the URL templated in).

I don't see a hook or means of adding protocol handlers in the code currently.

**Comment by brennen** [comment]
See `:help VimwikiLinkHandler`.
