### ISSUE TITLE
Italics broken with 7a48268 commit

### ISSUE THREAD

**Issue by rahulsalvi** [vimwiki/vimwiki#1331]
On the current latest commit (7a48268) with default syntax, italics and bold italics using "*_" to start don't seem to work for me. Bold italics with the _ first work normally. On the parent commit (71edcf6), everything works as expected.

I use the test file:
```
*bold*
_italic_
_*bolditalic with _ first*_
*_bolditalic with * first_*
~~strikethrough~~
```

7a48268:
![image](https://user-images.githubusercontent.com/1747204/234154566-818f2a70-bd5f-48d4-b4b0-51a6e5039c53.png)

71edcf6:
![image](https://user-images.githubusercontent.com/1747204/234154625-bf4765d1-4aab-4a37-b233-d543e3e6a449.png)

7a48268 with below patch:
![image](https://user-images.githubusercontent.com/1747204/234154695-a4f8d1de-b999-44e2-b4b0-6a76eb5ba57e.png)

This patch fixes the issue for me, but I don't know enough about this codebase to know if it's correct.
```diff
diff --git a/autoload/vimwiki/vars.vim b/autoload/vimwiki/vars.vim
index ca54359..dc0c986 100644
--- a/autoload/vimwiki/vars.vim
+++ b/autoload/vimwiki/vars.vim
@@ -699,7 +699,7 @@ function! s:get_default_syntaxlocal() abort
         \ 'symH': {'type': type(1), 'default': 1},
         \ 'typeface': {'type': type({}), 'default': {
         \   'bold': vimwiki#u#hi_expand_regex([['\*', '\*', '[*]', 0]]),
-        \   'italic': vimwiki#u#hi_expand_regex([['_', '_', '', 0]]),
+        \   'italic': vimwiki#u#hi_expand_regex([['_', '_', '[_]', 0]]),
         \   'underline': vimwiki#u#hi_expand_regex([]),
         \   'bold_italic': vimwiki#u#hi_expand_regex([['\*_', '_\*', '[*_]', 1], ['_\*', '\*_', '[*_]', 1]]),
         \   'code': [
```

Prior to submitting a new issue make sure to complete these steps:

- [X] Include the VimWiki settings from your `.vimrc`

No special settings. This vimrc is enough to demonstrate the issue for me.

```vim
set nocompatible
set nomodeline
filetype off

call plug#begin('~/.config/nvim/plugins')
Plug 'https://github.com/vimwiki/vimwiki'
call plug#end()

filetype plugin on
filetype indent on
syntax on
```

- [X] Include the syntax you are using (default / Markdown / MediaWiki) 
default
- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [X] Include the output of `:VimwikiShowVersion`.
```
Version: 2023.04.04
Os: Linux
Vim: 801
Branch: dev
Revision: 7a48268
Date: 2023-04-19 15:13:50 -0400
```

**Comment by tinmarino** [comment]
Hi @rahulsalvi,

Thank you for the report and the proposed solution. It passed all the tests and only affects the default syntax so I accepted it.

Note that I treated _ differently from * in markdown to permit innner_word_underscores without changing the typeface (PS: but I just cheched and it is still OK).

So perfect, thank you!
