### ISSUE TITLE
Recognize message:// URLs on Mac

### ISSUE THREAD

**Issue by dickscheid** [vimwiki/vimwiki#1332]
Mac OSX supports `message://<message-id>` URL schemes to open emails directly in Mail.app (see e.g. [here](https://nshipster.com/message-id/)). It is extremely handy to use such URLs to link from Vimwiki to emails on Mac OSX (and also IOS), which can then be opened independent of the mail folder they are stored in. The attached patch adds support to recognize this scheme in Vimwiki links, by adding 'message' to the 'schemes_web' list of the global vars. I suggest to include this patch.
[recognize_message_url_scheme.patch](https://github.com/vimwiki/vimwiki/files/11329722/recognize_message_url_scheme.patch)

Thanks a lot for this wonderful plugin!

**Comment by tinmarino** [comment]
Accepted and coded at [2cff977](https://github.com/tinmarino/vimwiki/commit/2cff9776e87983b4866cc323e89ca6c6773a6079).

Thanks to you both Brennen and @dickscheid

**Comment by dickscheid** [comment]
Wonderful, thank you so much for accepting the change!
