### ISSUE TITLE
vimwiki and calendar-vim

### ISSUE THREAD

**Issue by OrionRandD** [vimwiki/vimwiki#1336]
" Hook for calendar.vim
if vimwiki#vars#get_global('use_calendar')
  let g:calendar_action = 'vimwiki#diary#calendar_action'
  " This conflicts with calendar.vim plugin
  " let g:calendar_sign = 'vimwiki#diary#calendar_sign'
endif

calendar-vim gives me lots of errors if I do not comment:
" let g:calendar_sign = 'vimwiki#diary#calendar_sign'

Could you check this?
I think, if it is not a bug, it is a configuration clash...

v

**Comment by LukeDAtkinson** [comment]
I was having this issue and fixed it by setting a value for the g:vimwiki_list variable. In vimscript:
```let g:vimwiki_list = [{'path': '~/vimwiki/'}]```
or in lua:
```vim.g.vimwiki_list = "[{'path': '~/vimwiki/'}]"```

Looks like the `vimwiki#diary#calendar_sign` function does not handle this variable not being set

**Comment by OrionRandD** [comment]
On Wed, May 10, 2023 at 10:43:16AM -0700, Luke Atkinson wrote:


Thx a lot!

This worked for me:

" this is needed to play well with calendar-vim
"
 let g:vimwiki_list = [{'path': '~/vimwiki/'}]

 let g:calendar_diary = "~/vimwiki/diary"

 " or in lua:
 " vim.g.vimwiki_list = "[{'path': '~/vimwiki/'}]"


    I was having this issue and fixed it by setting a value for the
    g:vimwiki_list variable. In vimscript:
    let g:vimwiki_list = [{'path': '~/vimwiki/'}]
    or in lua:
    vim.g.vimwiki_list = "[{'path': '~/vimwiki/'}]"
 
    Looks like the vimwiki#diary#calendar_sign function does not handle
    this variable not being set
 

    Reply to this email directly, [1]view it on GitHub, or [2]unsubscribe.
    You are receiving this because you authored the thread. Message ID:
    ***@***.***>
 
 References
 
    1. https://github.com/vimwiki/vimwiki/issues/1336#issuecomment-1542580361
