### ISSUE TITLE
Getting errors opening wiki files after Fedora upgrade 37=>38

### ISSUE THREAD

**Issue by philiprhoades** [vimwiki/vimwiki#1339]
call plug#begin('~/.vim/plugged')

Plug 'brtastic/vim-jsonviewer'
Plug 'chrisbra/vim-diff-enhanced'
Plug 'stsewd/gx-extended.vim'
Plug 'vim-voom/VOoM'
Plug 'vim-scripts/AnsiEsc.vim'
Plug 'vimwiki/vimwiki'
Plug 'will133/vim-dirdiff'

call plug#end()

When I open a wiki file now I get an error like:

"VitaDAO.wiki" 297L, 11484B
Error detected while processing BufRead Autocommands for "*.wiki"..function <SNR>30_setup_new_wiki_buffer[19]..vimwiki#u#ft_set[9]..FileType Autocommands for "*"..Syntax Autocommands for "*".
.function <SNR>3_SynSet[25]..script /home/phr/.vim/plugged/vimwiki/syntax/vimwiki.vim[554]..function vimwiki#emoji#apply_conceal:
line    3:
E844: Invalid cchar value
E475: Invalid argument: VimwikiEmoji :key: conceal cchar=<bf>?

Any idea what change has happened?  I updated vimwiki but it was already up to date and I still get the error . .

Thanks.

**Comment by tinmarino** [comment]
I think you do not have the same encoding, and the emoji char in vimscripts are not reckgnised at runtime.
Disable emoji support with, and let us know.

```bash
let g:vimwiki_emoji_enable = 0
```

Sorry for the inconvenience

**Comment by philiprhoades** [comment]
Yes!  - that's it! - thank you!  So people are using emojis in Vim?!

> Sorry for the inconvenience

No worries at all - since I started using vimwiki, it has spread to lots of my files! - I couldn't do without vimwiki and Voom!

Thanks again!
