### ISSUE TITLE
Feature Request: Allow to run table formatting via mapping

### ISSUE THREAD

**Issue by andres-lowrie** [vimwiki/vimwiki#1342]
Firstly let me say this plugin is awesome! 

This may be a bit obscure but I figured I would throw this out there see if it would be of interest. 

I currently have the `let g:vimwiki_table_auto_fmt = 0` since I tend to draw ascii diagrams in my files but sometimes I actually would like proper tables and so I was wondering if there's a way to have vimiwiki do the formatting of table via a keybinding that way I could tell it when to do it as opposed to automatically when leaving insert mode

something like `:VimwikiFormatTable` or something to that tune that I could then bind with `nmap` 

thanks in advance

**Comment by tinmarino** [comment]
`gqq`or `VimwikiTableAlignQ`  from [design_note.md (the expert doc)](https://github.com/vimwiki/vimwiki/blob/dev/doc/design_notes.md).

```text
In Vimwiki, formatting tables occurs dynamically, when navigating between cells
and adding new rows in a table in the Insert mode, or statically, when pressing
`gqq` or `gqw` (which are mappings for commands `VimwikiTableAlignQ` and
`VimwikiTableAlignW` respectively) in the Normal mode. It also triggers when
leaving Insert mode, provided variable `g:vimwiki_table_auto_fmt` is set. In
this section, the original and the newer optimized algorithms of table
formatting will be described and compared.
``
