### ISSUE TITLE
toggle typefaces off?

### ISSUE THREAD

**Issue by tipa40** [vimwiki/vimwiki#1346]
Hi,
Sorry for creating an issue if there shouldn't be one.
I have a question about whether it is possible to toggle formatting such as bold, italics and other font formatting off to just use the other goodies that vimwiki has to offer. I use markdown so whenever using asterisk for instance I get italics in the document which is unwanted in some docs. I have tried for instance
:VimwikiVar typeface={}
to turn it off, but it does not apply.

Version: 2023.05.12
Os: Linux
Vim: 801
Branch: dev
Revision: cd9cfd2
Date: 2023-05-12 22:05:10 -0400

**Comment by tipa40** [comment]
Wow, thank you so much for that detailed explanation! No problem I understand you must be quite busy, I'm not that quick myself ;). I will try this tomorrow after a good night's sleep. I am very happy about this solution!

I am using nvim(sorry ;)) with vimwiki for my personal very long todo's and learnings files(which i should actually split to multiple files each of course, but that's a todo ;)) and currently I have long sections in those in unintended/unwanted italics or bold messing up the other vimwiki syntax coloring and therefore I wanted a way to turn it off. Other than that I think it's a very nice feature of vimwiki with the typface formatting.

I'll try it and close the ticket if I get it working which I am sure of. As long as there is some way I am very happy. I'll consider opening a ticket for the permanent command. There are many small details like this in my todo list which I would like to get working so I'll probably have a couple of more issues for different other projects to ask about. Takes some time to set up your "perfect" Linux env ;).

**Comment by tipa40** [comment]
I have now tried it in neovim, I understand that it is not the intended target, although for me the only option. It's also optional for you to provide a working solution for my case of course. But here are my results:

After starting up my nvim with no extra configuration just as prior to this and then manually running below works:
`let typeface_dic = {'bold': [], 'italic': [], 'underline': [], 'bold_italic': [], 'code': [], 'del':  [], 'sup':  [], 'sub':  [], 'eq': []}|echo vimwiki#vars#set_syntaxlocal('typeface', typeface_dic)|e`
It does not apply without reloading the file with "e".

If trying to initialise it from my ~/.config/nvim/init.vim using for instance
```
augroup vimWikiTypeFacesOff
  au!
  au BufRead,BufNewFile *.md let typeface_dic = {'bold': [], 'italic': [], 'underline': [], 'bold_italic': [], 'code': [], 'del':  [], 'sup':  [], 'sub':  [], 'eq': []}
  au BufRead,BufNewFile *.md sil! echo vimwiki#vars#set_syntaxlocal('typeface', typeface_dic)
  au BufRead,BufNewFile *.md verbose call vimwiki#u#hi_typeface(typeface_dic)
augroup END
```
it will not take effect until I reload the file manually with :e. So I guess it's my best bet so far, which is of course far better than it was before, although not the best.

But if you do have some idea about how I can get it done from the initialisation at once without having to reload the file a second time and without manual step I would appreciate it! :)

**Comment by tinmarino** [comment]
Hello @tipa40,

Yes I just tested the way to make it persistent. 

```
let g:vimwiki_syntax_list = {}
let g:vimwiki_syntax_list['markdown'] = {}
let g:vimwiki_syntax_list['markdown']['typeface'] = {'bold': [], 'italic': [], 'underline': [], 'bold_italic': [], 'code': [], 'del':  [], 'sup':  [], 'sub':  [], 'eq': []}
```

This is an undocumented mess I reckon.

**Comment by tipa40** [comment]
Super, I am completely happy with this solution! Works very well, thanks :)
