### ISSUE TITLE
[Feature] Concealer

### ISSUE THREAD

**Issue by niksingh710** [vimwiki/vimwiki#1347]
will it be possible to have a concealer like glow in vimwikki?

**Comment by niksingh710** [comment]
let me elaborate what am trying to say....
i have recently tried neorg.nvim it have a feature that conceals what we type 
e.g 
```
* Heading
```
This heading will be converted into ` Heading` this makes it looks minimal and nice while working.
They acheive this using treesitter and conceal api if the cursor is in insert mode and on the line it shows the original text otherwise it conceals it with a nice view.

kindda links get's concealed in markdown.

i mentioned glow.lua with respect of picking few ui elements from there.
![image](https://github.com/vimwiki/vimwiki/assets/60490474/f94e568c-0929-4caa-86b7-12e7bff11ba5)

**Comment by tinmarino** [comment]
Thank you for the explanation, I understand now. Unfortunately Vim has a limited concealment support. Like replaced by only one character, and all concealed character have the same color (controlled by the Conceal highlighting group, see #1004).

* The heading prefix `#` conceal is not a must feature
* The list prefix `*`conceal  should have the color of list items but this would change the Conceal color for all others (like embeded tex document).

Keep in mind than Vim do not permit to really modify the view of a file (buffer) very far from the text content of this file (unlike Emacs and maybe Nvim more and more). What you see is the text file, not what you get.

To see the best we can archive with Vim's conceal, [see vimtex](https://github.com/lervag/vimtex) and to see a hard limitation [see Vim ccstr feature request](https://github.com/vim/vim/issues/4687).

**Comment by niksingh710** [comment]
I understand now, and it seems a limitation how vim allows the concealment.
I guess a new plugin from scratch for neovim specific can achieve this goal that can be used parallel to vimwikki.

**Comment by diegoroccia** [comment]
@niksingh710 out of curiosity did you find a plugin to do that?

**Comment by niksingh710** [comment]
> @niksingh710 out of curiosity did you find a plugin to do that?

nop didn't found any yet.
