### ISSUE TITLE
Setting `g:vimwiki_list.path` after Vimwiki has loaded can break link logic

### ISSUE THREAD

**Issue by jjaderberg** [vimwiki/vimwiki#135]
I set `g:vimwiki_list` in my .vimrc and I use `~` in the path option, similar to the example in the help docs. Vimwiki expands the path correctly and links work. If I then source my .vimrc, without changes, links no longer work.

For example, I set path to `~/wiki` and in my index page I type `[[library/index|Library]]`. The link works, it correctly points to `/home/me/wiki/library/index.wiki`. At this point `:echo VimwikiGet('path', 0)` returns the absolute and expanded path `/home/me/wiki`. Then I source my .vimrc. Now when I try to follow the link I am asked if I want to 

> Make new directory: `/home/me/wiki/home/me/wiki/library`

 and `VimwikiGet('path', 0)` now returns `~/wiki`. This in turn means that when constructing a link path, `vimwiki#base#current_subdir` passes this non-expanded path to `vimwiki#base#subdir`. It compares the dirpath string `~/wiki` to the filepath string `/home/me/wiki/library/index.wiki` and finds no common path components (it should have been passed `/home/me/wiki` and would then have removed this part from the filepath before proceeding). Then the filepath string is split into a list of components, and rebuilt into a dirpath string, leaving out the filename, and this is returned. Since nothing is removed from the beginning of the filepath string before this operation, except the leading `/` which is removed when the string is split, the dirpath string that is returned is now a relative path, `home/wiki/library/`, which gets appended as a subdir when the link path is constructed. The same happens for other paths that include `~` and are set from my .vimrc.

I believe the reason that the path is not expanded correctly after I source my .vimrc is that, while the function `Validate_wiki_options` does expand the path, it runs once and then stores the validated value by overwriting the path value in `g:vimwiki_list`. When I source my .vimrc I overwrite that value again. Vimwiki assumes that the options are already validated and uses the path without first expanding it.

Should I expect Vimwiki to be able to handle that path options are set again after it has already loaded, or should I change how I set the options, e.g., expand the paths before setting them, or conditionally set the option only if I haven't done so already? I have another problem, which may be relevant: in my .vimrc I override some Vimwiki key mappings, like <kbd>TAB</kbd> for jumping between links, because I use these maps elsewhere.  This also works fine until I source my .vimrc, at which point Vimwikis default mappings are back. This is a separate issue and I haven't investigated it yet, but since this problem also occurs when I source my .vimrc it makes me think I may need to reconsider how I do my configuration there. Suggestions?

**Comment by EinfachToll** [comment]
The first issue is clearly a bug. The second ... don't know. I will try to reproduce it.
The handling of Vimwiki's internal variables are a bit messy and error-prone in general.

**Comment by ranebrown** [comment]
@jjaderberg This appears to be fixed on the latest `dev` branch. If you are still having issues please reopen.
