### ISSUE TITLE
Misdirection of link to file of form `x.log.md`

### ISSUE THREAD

**Issue by Meph24** [vimwiki/vimwiki#1352]
- [x] Include the VimWiki settings from your `.vimrc`

```
call plug#begin()

Plug 'vimwiki/vimwiki'
Plug 'preservim/nerdtree'
Plug 'dyng/ctrlsf.vim'

call plug#end()

let mapleader = " "
let g:vimwiki_list = [{
      \ 'path': 'Q:\users_A-L\Graf.Robert\vertraulich\notes',
      \ 'syntax': 'markdown', 'ext' : '.md'
\ }]
let g:vimwiki_auto_chdir = 1

" archiving a selection to another file with timestamp
" I imagine to use this for the purpose of deleting old todos, without loosing
" the information of what I had done there

function! Timestamp()
  return '[' . strftime('%Y-%m-%d %H:%M:%S') . ']'
endfunction

" returns a link to todays diary
function! DiaryTimestamp()
  "TODO ensure we are in vimwiki file
  return Timestamp() . "(/diary/" . strftime('%Y-%m-%d') . ".md)"
endfunction

function! DiaryFileOfToday()
  return '\diary\' . strftime('%Y-%m-%d')
endfunction

function! ArchiveSelectedLinesToFile(filename) range
  "write to archive file
    let diaryfile = DiaryFileOfToday()
    let timestamp = '***Archived on: ' . Timestamp() . '(' . diaryfile . ')***'
    let lines = getline(a:firstline, a:lastline)
    let archival_data = ["",""] + [repeat("-", 42)] + [timestamp] + lines     
    call writefile(archival_data, a:filename, 'a')
  "finally delete lines in current document
    execute a:firstline . ',' . a:lastline . 'd'
endfunction

function! CurrentArchiveFile()
    let archive_line_file_ending = '.log.md'
    return expand('%:p:r') . archive_line_file_ending
endfunction

xnoremap <leader>wa :call ArchiveSelectedLinesToFile(CurrentArchiveFile())<CR>

function! MoveToCurrentArchiveFile()
  execute 'tabnew ' . CurrentArchiveFile()
endfunction

nnoremap <leader>wa :call MoveToCurrentArchiveFile()<CR>
nmap <leader>tt i<C-R>="[" . strftime("%Y-%m-%d %H:%M:%S") . "]"<CR><Esc>
```

- [x] Include the syntax you are using: markdown
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
Cannot follow a link written as `[LINK](x.log.md)`. Following the link by pressing enter will result in moving to `x.log`, without the md, which is a different file.
My best guess is it has something to do with either having multiple extension `.`s in a filename, or the feature of being able to omit the `md` in a wiki file link.
- [x] Include the output of `:VimwikiShowVersion`: Stable version: 2.5

**Comment by tinmarino** [comment]
Hello @Meph24,

Please use the dev branch: this feature has changed and v2.5 is really old. It is still unperfect but a discussion is on #1271.

Closing for duplicate.

**Comment by brennen** [comment]
`dev` is pretty much expected to be the only branch at this point, with `master` as a mirror of it. Which we haven't been doing a great job of keeping up with. I'll look into some automation when I get a bit of time free to devote to VimWiki things. (Have been extra busy with life & work lately.)
