### ISSUE TITLE
Structuring my wiki

### ISSUE THREAD

**Issue by tibofordeyn** [vimwiki/vimwiki#1357]
I have a question about structuring in Vimwiki. I have been trying for some time now to make it so that when I create a new note in my vimwiki, not only is a new markdown file created, but also a new folder in the current directory is created. This folder should have the same name as the note (without the file extension) and should contain the newly created markdown file. 

The reason for this is that I'd like to have a better structure for my work wiki and keep files that are associated with a particular note in a specific directory that belongs to that note. For example, if in index.md I create a note called "current-tasks", I would like Vimwiki to create a directory called "current-tasks" and put the file "current-tasks.md" in it. Additionally, I should still be able to navigate through the wiki as usual.

Is this something that's currently possible in Vimwiki? I haven't found anything on this topic in the documentation.

As a workaround, I have tried writing some bash scripts and modifying my vimrc file, but without any success. For reference, here is my current vimrc:
let g:vimwiki_list = [
\ {
\   'path': '~/work/notes',
\   'index': 'index',
\   'syntax':'markdown',
\   'ext': '.md',
\   'key': '<Leader>ww',
\   'auto_export': 0,
\   'template_path': '~/work/index/templates/',
\   'template_default': 'default',
\   'template_ext': '.tpl',
\   'nested_syntaxes': {'python': 'python', 'bash': 'sh'}
\ },
\ {
\   'path': '~/notebooks/',
\   'index': 'index',
\   'syntax':'markdown',
\   'ext': '.md',
\   'key': '<Leader>wp',
\   'diary_rel_path': 'journal/',
\   'diary_index': 'index'
\ }
\ ]
Has anyone else faced a similar issue and found a workaround? Or is this functionality something that could be considered for a future update?

**Comment by brennen** [comment]
Something like this would probably be achievable with (for example):

- An autocommand (see `:help autocommand`) to filter a file on save and create directories for links
- Overriding default VimWiki link handling (see `:help VimwikiLinkHandler`)

...but it's not something that the core project could easily support, and I think it would be a lot of complexity to implement in a general way for not much payoff.

My suggestion:  Just a pattern like `[[/current-tasks/index]]` for links.  It's slightly more verbose, but it's already fully supported.
