### ISSUE TITLE
Under tmux there is an issue

### ISSUE THREAD

**Issue by jon-yip** [vimwiki/vimwiki#136]
I tried to use vimwiki under tmux and every time I type 'o' in normal mode, I get the message
 "call vimwiki#lst#kbd_o0('o')".

I am using OS X Yosemite.

**Comment by EinfachToll** [comment]
Hm, I'm using tmux as well and I don't see these issues. Can you try the latest Vimwiki version from the dev branch?

**Comment by EinfachToll** [comment]
Closing. Feel free to reopen if the issue persists.
