### ISSUE TITLE
Slowdown when pressing Enter/o

### ISSUE THREAD

**Issue by mbwgh** [vimwiki/vimwiki#1360]
Prior to submitting a new issue make sure to complete these steps:

- [x] Include the VimWiki settings from your `.vimrc`

```
let g:vimwiki_list = [{'path': '~/vimwiki/',
    \ 'auto_tags': 1,
    \ 'template_path': '~/vimwiki/templates/',
    \ 'template_default': 'template',
    \ 'template_ext': '.html',
    \ 'listsyms_propagate': 0}]
let g:vimwiki_listsyms = ' .oOx'
```    

- [x] Include the syntax you are using (default / Markdown / MediaWiki) 

Default (I believe :))

- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.

See the attached file I produced via running `sed 's/[a-zA-Z]\{2,\}/bla/g' my-work-notes > bla`.
I use this kind of notes file without vimwiki for now, because it would be prohibitively slow otherwise.

The `prof` file was created via:
* Opening the wiki index and adding a new entry
* Copy-Pasting the `bla` contents into it
* `:profile start prof | profile func *`
* `G o <enter> <enter> <esc> o <esc> :wq`
    * I.e. Add a new line at the end, remove the new bullet-point added by vimwiki (after `o`), add two new lines via enter and o (both slow), write and quit (also slow)

- [x] Include the output of `:VimwikiShowVersion`.

```
Version: 2022.12.02
Os: Linux
Vim: 801
Branch: master
Revision: fea8bee
Date: 2022-12-04 21:25:52 -0700
```

This appears similar in behavior to some other issues I saw, but those had folds enabled and I don't use that to my knowledge.
Setting `auto_tags` to `0` will speed up `:w`, but not inserting new lines.

If there's some obvious setting to try, any pointers would be greatly appreciated.

[bla.txt](https://github.com/vimwiki/vimwiki/files/12206881/bla.txt)
[prof.txt](https://github.com/vimwiki/vimwiki/files/12206882/prof.txt)

**Comment by infinitewhileloop** [comment]
I imported your file into my Vimwiki and adding a new line at the end is indeed very slow (about 10 seconds). I use the Markdown syntax and have folds enabled.

This looks very similar to #225. 

By default, folding should be disabled, but try setting this explicitly `let g:vimwiki_folding = ''`. When I did this, the issue disappeared completely after reloading Vimwiki.

For more information, see `:h vimwiki-folding` and `:h g:vimwiki_folding`.

**Comment by infinitewhileloop** [comment]
Is this only happening for large files?

Your sample file has almost 7000 lines, when I truncate it to 1000 lines it's a lot faster, even with folding enabled.

You could also try switching to Markdown syntax and test if the issue persists.

**Comment by mbwgh** [comment]
Yes, this only happens for large files.

I have been trying to read into how to switch the used syntax to markdown and converting the file also.
I modified my `init.vim` (Neovim, does that make a difference? I hope not...) to read
```
" Vimwiki configuration.
let g:vimwiki_folding = ''
let g:vimwiki_list = [{'path': '~/testdir/vimwiki/',
    \ 'syntax': 'markdown', 'ext': '.wiki',
    \ 'auto_tags': 1,
    \ 'template_path': '~/vimwiki/templates/',
    \ 'template_default': 'template',
    \ 'template_ext': '.html',
    \ 'listsyms_propagate': 0}]
let g:vimwiki_listsyms = ' .oOx'

```

but unfortunately, that does not seem to work, it's still very slow.
Especially pressing enter at the end of a nested list, e.g. the last list item in the sample file.

Is the above configuration as intended?

**Comment by infinitewhileloop** [comment]
> Yes, this only happens for large files.
> Especially pressing enter at the end of a nested list, e.g. the last list item in the sample file.

This still points to folding, but you said it was disabled. Do you have another plugin installed that is adding folding? Is `zR` (open all folds) or `zM` (close all folds) doing anything?

> Is the above configuration as intended?

This how part of my configuration in my `.vimrc` looks like. I prefer a more verbose configuration, with a separate line for each object property.

```vim
let g:vimwiki_folding = 'expr:quick'

let g:wiki_1 = {}
let g:wiki_1.name = 'My Wiki'
let g:wiki_1.path = '~/wiki/'
let g:wiki_1.index = 'index'
let g:wiki_1.syntax = 'markdown'
let g:wiki_1.ext = '.md'

let g:wiki_2 = {}
let g:wiki_2.name = 'Another Wiki'
...

let g:vimwiki_list = [g:wiki_1, g:wiki_2]
```

I can confirm that your sample file works fine in Vimwiki in  Neovim, when I disable folding. I like folding a lot, so if I were in your shoes I would consider splitting your massive sample file into multiple smaller ones.

**Comment by mbwgh** [comment]
Just to make sure, I reduced my `init.vim` to this:

```
call plug#begin('~/.vim/plugged')
Plug 'vimwiki/vimwiki'
call plug#end()

set nofoldenable
let g:vimwiki_folding = ''

let g:wiki_1 = {}
let g:wiki_1.name = 'My Wiki'
let g:wiki_1.path = '~/testwiki/'
let g:wiki_1.index = 'index'
let g:wiki_1.syntax = 'markdown'
let g:wiki_1.ext = '.md'

let g:vimwiki_list = [g:wiki_1]
```

I.e. removed every Plugin, I ran `:PlugUpdate` to make sure I use the latest version, and started a new empty Wiki with markdown syntax and folding disabled.

Then I do these things specifically:

* `nvim -c VimwikiIndex`
* Paste contents of bla.txt
* Navigate to the last nested list item on line 6870
* `A <enter> <enter>` (nvim blocks multiple seconds)
* `<enter> <enter>` (blocks again)

There must be some other latent variable at play here then.

I included another profile which only includes the `A <enter> <enter>` step (and exiting without writing).
[prof.txt](https://github.com/vimwiki/vimwiki/files/12269028/prof.txt)

Pressing `zM` or `zR` did not have any visible effect.

**Comment by infinitewhileloop** [comment]
Your test config looks the same as mine now. There is just one difference; I remember it was recommended to use the `dev` branch. Try inserting this line and update the plugin:
`Plug 'vimwiki/vimwiki', {'branch': 'dev'}`

Apart from that, I don't know what could be causing this. I tried your steps and I don't experience blocking. Hopefully someone else has suggestions.

**Comment by mbwgh** [comment]
Dev-branch seems to behave the same unfortunately.

I would be curious if repeating the profile step just for `A <enter> <enter>` would yield wildly different results.
Especially comparing the summary
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
 1307  25.859820   0.671752  <SNR>63_adjust_numbered_list()
 1305  23.634138  12.099117  <SNR>63_adjust_numbered_list_below()
 3368  20.226209   0.044584  <SNR>63_adjust_items_recursively()
    2   8.631631   0.000250  <SNR>56_CR()
    2   8.627509   0.000317  vimwiki#lst#kbd_cr()
    1   8.624334   0.000166  <SNR>63_cr_on_empty_list_item()
    1   8.623965   0.000262  <SNR>63_change_level()
    1   8.620156   0.000057  <SNR>63_adjust_mrkr()
 4673   4.391622   0.481481  <SNR>63_get_next_list_item()
117223   4.113856   1.932065  vimwiki#vars#get_syntaxlocal()
29392   3.384702   1.334205  <SNR>63_get_next_line()
48514   2.781800   1.063909  <SNR>63_get_level()
128869   2.402016   1.264807  vimwiki#vars#get_wikilocal()
 3368   1.510731   0.137590  <SNR>63_get_first_child()
 1304   1.405032   0.057788  <SNR>63_get_next_child_item()
128869   1.137209             vimwiki#vars#get_bufferlocal()
 1305   1.065069   0.022131  <SNR>63_get_first_item_in_list()
 1467   1.047446   0.118016  <SNR>63_get_prev_list_item()
 1304   1.045363   0.089958  <SNR>63_get_last_line_of_item_incl_children()
 5822   0.650295   0.430410  <SNR>63_get_item()
```

If the order and number of function calls would look similar for you, but the execution time was just lower, this might in the end just be due to hardware :/

**Comment by infinitewhileloop** [comment]
I have repeated the profile.

Just to be clear, this is what I did:

- Comment out the line in my `.vimrc` about Vimwiki folding, so it reverts to the default (no folding)
- Download your `bla.txt`, put it inside my Vimwiki directory, rename it it to `bla.md` and open it in Neovim
- `:profile start foo | profile func *`
- Go to line 6870
- Press `A <enter> <enter>`

This is the profile output:
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   15   0.409252   0.004456  airline#check_mode()
   11   0.394730   0.052100  airline#highlighter#highlight()
  434   0.295830   0.089400  airline#highlighter#exec()
  746   0.250044   0.106366  airline#highlighter#get_highlight()
  126   0.186524   0.012081  <SNR>98_exec_separator()
   15   0.149119   0.049623  airline#extensions#whitespace#check()
 2984   0.133836             <SNR>98_get_syn()
    5   0.118284   0.000346  <SNR>48_on_focus_gained()
    5   0.117811   0.000570  <SNR>48_airline_refresh()
    5   0.116422   0.000804  airline#update_statusline()
    5   0.114446   0.000570  <SNR>93_invoke_funcrefs()
    5   0.097725   0.009979  19()
  252   0.089318   0.005504  airline#themes#get_highlight()
    1   0.088473             <SNR>102_check_mixed_indent()
   30   0.072081   0.001289  <SNR>110_get_separator()
   35   0.055913   0.002842  <SNR>110_get_transitioned_separator()
   35   0.053071   0.001199  airline#highlighter#add_separator()
    1   0.047577   0.000585  which_key#start()
  161   0.041118             <SNR>98_GetHiCmd()
    2   0.025538   0.000371  <SNR>113_CR()
```

Everything went smooth and the function calls taking the most time aren't even related to Vimwiki. 

The result for your top function call is this:
```
FUNCTION  <SNR>128_adjust_numbered_list()
    Defined: ~/.local/share/nvim/plugged/vimwiki/autoload/vimwiki/lst.vim:742
Called 3 times
Total time:   0.005406
 Self time:   0.000162
```

I repeated the profile one more time, now with folding enabled:

```

FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
48100  18.618653   4.626431  VimwikiFoldLevel()
144325  13.994819   6.595255  vimwiki#vars#get_syntaxlocal()
    1  13.702851   0.000322  <SNR>113_CR()
    1  13.699693   0.000217  vimwiki#lst#kbd_cr()
    1  13.699106   0.075137  <SNR>128_cr_on_list_item()
    1  10.939635   0.000138  <SNR>128_clone_marker_from_to()
    2  10.939058   0.299336  <SNR>128_substitute_rx_in_line()
144330   7.399847   3.890062  vimwiki#vars#get_wikilocal()
    1   5.461038   0.000044  <SNR>128_set_indent()
144330   3.509785             vimwiki#vars#get_bufferlocal()
    9   0.224688   0.002577  airline#check_mode()
    6   0.216773   0.027733  airline#highlighter#highlight()
  224   0.156473   0.045973  airline#highlighter#exec()
  348   0.113546   0.048400  airline#highlighter#get_highlight()
   56   0.082881   0.005312  <SNR>98_exec_separator()
 1392   0.060702             <SNR>98_get_syn()
    1   0.047151   0.000563  which_key#start()
  112   0.038424   0.002410  airline#themes#get_highlight()
  109   0.027301             <SNR>98_GetHiCmd()
    1   0.025424   0.000331  <SNR>17_cache_key()
```

I don't know how to solve this issue, but I think it's definitely software related. Maybe this can help: https://vimwiki.github.io/vimwikiwiki/Troubleshooting.html

**Comment by infinitewhileloop** [comment]
If you are still struggling with this issue, there is a small chance [this](https://github.com/vimwiki/vimwiki/issues/225#issuecomment-1682984036) might fix it. It's basically installing the `vim-pandoc` plugin and changing some settings.

**Comment by mbwgh** [comment]
Hi @infinitewhileloop, sorry for going silent, I was pretty swamped with exams and now work.
I haven't given up on this issue yet and wanted to have another look this weekend.

**Comment by mbwgh** [comment]
Since changing the syntax to markdown is something I would prefer not to do, I gave this another look.
A some struggling with the limited debugging facilities and the fact that you apparently can't add breakpoints for `s:` functions, I came to the following conclusions so far:

Pressing `i<Enter><Enter><Enter>` inside the nested list item at the bottom of the file, i.e. here:
```
    * bla
    * bla (#1363):
        * bla bla bla bla bla-bla
        * bla bla bla bla bla bla bla
        * bla bla bla, bla bla bla bla. bla bla bla bla <--
```

will cause a lot of invocations of `s:adjust_numbered_list`, `s:adjust_numbered_list_below` and `s:adjust_items_recursively`.
Commenting these calls out, pressing Enter is fast again.

I have however yet to find out in what scenarios this would break anything.
While there are no numbered lists in this file, I saw that there is some support for having list items like `*`, `**`, `***` etc.?

Even without these `adjust` calls however, one thing still remains slow.
And that is if you press `o` or `i-<Enter>` in between paragraphs like this:
```
            * bla bla bla.bla.bla.216 bla bla bla bla bla bla bla
            * bla bla bla bla bla.bla bla bla
<-- here
* [ ] 2023-07-28 13:45 - 18:00, 22:30 - 23:45
    * bla (#1363):
        * bla-bla-bla:
```

In this case, the `kbd_o` or `kbd_enter` handler will call the `s:get_corresponding_item` function, which seems to try to find out where the beginning of a (possibly nested) list is. For this example, the while-loop inside will keep iterating until it arrives at the very beginning of the file, i.e. ~6000 iterations with multiple further function calls per iteration.

I am not sure what to make of this and have to take a break here.
One may argue that this kind of input file (basically one large list) is not a use case for vimwiki.
On the other hand, vimwiki here tries to do some clever things which may not be necessary and could either be avoided, be made configurable, or be made more efficient.

**Comment by mbwgh** [comment]
Closing this, since I do not intend to investigate this anymore.
