### ISSUE TITLE
How to run InspectTree ? Enable Treesitter support?

### ISSUE THREAD

**Issue by ariel-frischer** [vimwiki/vimwiki#1367]
I've tried messing with a bunch of syntax configuration options:

```
M.vimwiki_enabled_paths = { "~/vimwiki/", "~/repos/" }
local vimwiki_list = {}
for _, value in ipairs(M.vimwiki_enabled_paths) do
  table.insert(vimwiki_list, { path = value, syntax = "markdown", ext = "md" })
end

g.vimwiki_ext2syntax = {
  [".md"] = "markdown",
  [".markdown"] = "markdown",
  [".mdown"] = "markdown",
}

g.vimwiki_filetypes = { "markdown" }
g.vimwiki_sync_branch = "main"
g.vimwiki_ext = "markdown"
g.vimwiki_list = vimwiki_list
g.vimwiki_sync_branch = "main"
g.vimwiki_ext = "markdown"
g.vimwiki_global_ext = 0 -- make sure vimwiki doesn't own all .md files
g.vimwiki_automatic_nested_syntaxes = 1
g.vimwiki_nested_syntaxes = { python = "python" }
g.vimwiki_conceal_onechar_markers = 0
```

When I run `:InspectTree` I get the following error:
```
Error executing Lua callback: ...4c7/share/nvim/runtime/lua/vim/treesitter/playground.lua:241: No parser available for the given buffer
stack traceback:
	[C]: in function 'assert'
	...4c7/share/nvim/runtime/lua/vim/treesitter/playground.lua:241: in function 'inspect_tree'
```
When I run `lua print(vim.bo.filetype)` I get:
```
vimwiki.markdown
```
Does treesitter see this filetype and just give up? How do I change the filetype to regular markdown so it has treesitter support - but also I still get vimwiki support? My files have been markdown files (.md) anyway not .wiki or .vimwiki files.

**Comment by daodejing** [comment]
This was bothering me too: Here is what worked for me.
`:h vim.treesitter.language.register()`

Put this command in your ftplugin/vimwiki.lua (or autocommand):
`vim.treesitter.language.register('markdown', 'vimwiki')`

**Comment by tinmarino** [comment]
Closing <= workaround in previous comment
