### ISSUE TITLE
Resolving E492: Not an editor command :VimwikiIndex

### ISSUE THREAD

**Issue by paullotz** [vimwiki/vimwiki#1369]
Started to use neovim with NvChad + added vimwiki to the default configuration with this code:
```
{
  "vimwiki/vimwiki",
  event = "BufEnter *.md",
  keys = { "<leader>ww", "<leader>wt" },
  init = function()
    vim.g.vimwiki_list = {
      {
        path = "/home/xxx/Documents/notes/",
        syntax = "markdown",
        ext = ".md",
      },
    }
    vim.g.vimwiki_ext2syntax = {
      [".md"] = "markdown",
      [".markdown"] = "markdown",
      [".mdown"] = "markdown",
    }
  end,
},
```
Everything seems to work except using the command :VimwikiIndex which results in this error:
`E492: Not an editor command: VimwikiIndex`

Also tried executing `:VimwikiShowVersion` but this also results in the same E492 error.

**Comment by tinmarino** [comment]
No idea, try to load the plugin the Vim way with packadd and it works fine.
