### ISSUE TITLE
Normal URLs and <Leader>whh open in different browsers

### ISSUE THREAD

**Issue by protist** [vimwiki/vimwiki#137]
Opening links in a vimwiki file with `<Enter>` launches Firefox. However, `<Leader>whh` launches Konqueror. Using `xdg-open` opens Firefox.

`<Leader>whh` previously opened in Firefox, so it's possible a recent upgrade to KDE Plasma 5 changed something. However, I would have expected consistency between the two commands.

Arch Linux
Plasma 5.3.0
vimwiki: using the git/dev branch

**Comment by EinfachToll** [comment]
In both cases, the same function in Vimwiki is called and therefore xdg-open. In the first case, however, the argument to xdg-open is a URL (or not?) and in the second case it's a path to a html file. Apparently, xdg-open treats them differently. So you have to configure it somehow, but there's nothing we can do on the Vimwiki side.

**Comment by protist** [comment]
Ah yes, good point. However, when I `xdg-open` the same html file, it opens up with Firefox, so there's still some inconsistency there.

**Comment by bewuethr** [comment]
In case somebody else is stumped by this, the hint "URL vs. path to HTML file" helped me fix this. I was confused because `xdg-settings get default-web-browser` was already set to the browser I wanted (Chrome, in my case); however, I also had to set

```sh
xdg-settings set default-url-scheme-handler file google-chrome.desktop
```

to use Chrome for `file:` URLs.
