### ISSUE TITLE
Highlighting for open/close block {{{ }}} ``` is broken with defining language

### ISSUE THREAD

**Issue by Shuraken007** [vimwiki/vimwiki#1370]
Hello, I have a question, how highlight was added at this screenshot from Readme page.
I had to fixed code a bit to get this.
https://github.com/vimwiki/vimwiki/blob/dev/doc/entries.png

so
```
{{{ go
...
}}}
```
start and end brackets are highlighted with blue

I added binding to check syntax matches
```vim
" Show syntax highlighting groups for word under cursor
nmap <leader>z :call <SID>SynStack()<CR>
function! <SID>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc
```

So, without language `go` - all works as expected - everything marked as `VimwikiPre`
Brackets are marked with `VimwikiPreDelim`

But with `go` - `VimwikiPreDelim` disappeared
Everything marked with `textSnipGO`
and  string with brackets marked as `VimwikiPre`

after changing param for `get_syntaxlocal`: `VimwikiPre` -> `VimwikiPreDelim`
VimwikiPreDelim appeared again
```
diff --git a/syntax/vimwiki.vim b/syntax/vimwiki.vim
index 8580ce4..f519286 100644
--- a/syntax/vimwiki.vim
+++ b/syntax/vimwiki.vim
@@ -526,7 +526,7 @@ if !empty(s:nested)
     call vimwiki#base#nested_syntax(s:vim_syntax,
           \ vimwiki#vars#get_syntaxlocal('rxPreStart').'\%(.*[[:blank:][:punct:]]\)\?'.
           \ s:hl_syntax.'\%([[:blank:][:punct:]].*\)\?',
-          \ vimwiki#vars#get_syntaxlocal('rxPreEnd'), 'VimwikiPre')
+          \ vimwiki#vars#get_syntaxlocal('rxPreEnd'), 'VimwikiPreDelim')
   endfor
 endif
--
```

Is this bug, or I havn't understand smth?

**Comment by tinmarino** [comment]
Add this to your vimrc
```vim
let g:vimwiki_automatic_nested_syntaxes = 1
```
