### ISSUE TITLE
(Feature Request/I'm building it) Vimwiki Agenda

### ISSUE THREAD

**Issue by systemb4** [vimwiki/vimwiki#1376]
If I built an agenda feature like org agenda in Python, would it be possible to integrate it into Vimwiki which is written in VimScript? I'm currently building it right now and of course I can just create a key binding and have output open in a terminal buffer, but it would be pretty cool to integrate into Vimwiki as that's the use case I'm writing it for.

**Comment by brennen** [comment]
We're pretty unlikely to directly integrate a new large body of Python code, but maybe it's a good candidate for something like the [utils repo](https://github.com/vimwiki/utils).

It might also be the kind of thing that's usefully combined with a code execution feature, if we had one - see #1001.

**Comment by tinmarino** [comment]
Hello @systemb4,

Sorry for our late reply. Please notify us if your agenda works, we could integrate them in the web documentation as a sister plugin.

But Vimwiki have had a "pure Vimscript" restriction for a long time, much before I became maintainer, so we will not integrate a python plugin, sorry for that too.

**Comment by systemb4** [comment]
Hi @tinmarino,

The app I wrote was very crap, lol, no need.

Cheers!
