### ISSUE TITLE
Linking to directories doesn't work

### ISSUE THREAD

**Issue by fd0** [vimwiki/vimwiki#138]
The documentation states that it is possible to link to directories this way:
```
Links to directories (ending with a "/") are also supported:
  [[/home/somebody/|Home Directory]]
```

However, this doesn't seem to work (Debian Jessie). To reproduce, create the following link to an already existing directory:
```
[[/home/fd0/Documents/]]
```

Accessing this link, vimwiki asks if the directory `home/fd0/Documents` below my vimwiki path should be created:
```
Vimwiki: Make new directory: /home/fd0/doc/vimwiki//home/fd0/Documents
 [Y]es/[n]o? 
```

vim version:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:36:07)
Included patches: 1-488, 576
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by jamessan@debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
[...]
```

**Comment by tempo** [comment]
Same issue here on Debian stretch
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  1 2015 01:37:44)
Included patches: 1-712
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version with GTK2 GUI.  Features included (+) or not (-):
```

**Comment by EinfachToll** [comment]
You are right, the documentation is misleading. The behavior is actually right. Links like `[[/a/b/]]` are for links to directories *inside the wiki directory*, while `[[file:/a/b/]]` is a link to a directory in the file system. Personally, I don't know what the former is good for, but now it's there.

**Comment by EinfachToll** [comment]
I hope it's more clear now.

**Comment by fd0** [comment]
Great, that works, thanks a lot! I think this issue is solved then.
