### ISSUE TITLE
(neovim) Vimwiki always creates .wiki files instead of .md

### ISSUE THREAD

**Issue by tjex** [vimwiki/vimwiki#1384]
Prior to submitting a new issue make sure to complete these steps:

~/.config/nvim/after/plugin/vimwiki.lua (I've also tried with vimwiki.vim using vim syntax):
```lua
vim.g.vimwiki_ext2syntax = { ['.md'] = 'markdown'}
vim.g.vimwiki_filetypes = { "markdown " }
vim.g.vimwiki_markdown_link_ext = 1
vim.g.vimwiki_global_ext = 0
vim.g.vimwiki_list = {
	{
		auto_export = 1,
		path = "~/vimwiki",
		syntax = "markdown",
		ext = ".md",
	},
}
```

Steps to reproduce:

- create a directory at `~/vimwiki`
- open neovim and execute `<leader><leader>ww`
- `~/vimwiki/index.wiki` is created (not `index.md`)

Version:

```text
Version: 2023.05.12
Os: Mac
Vim: 801
Branch: dev
Revision: 0bb1b49
Date: 2023-10-31 13:45:18 -0300
```

## Further

(not sure then if this is part of the same behaviour)

create an entry in index.wiki:
```text
test
```

hit enter on "test" -> test.wiki is created.

## Things I've tried

More so to get marksman syntax highlighting to work.

nvim/ftdetect/filetype.lua:
```lua
vim.filetype.add({
	extension = {
		wiki = "markdown",
	},
})
```

nvim/ftdetect/vimwiki.vim:
```vim
autocmd BufWinEnter *.md setlocal syntax=markdown
```

After both of these attempts `:lua print(vim.bo.filetype)` still returns `vimwiki`

**Comment by tjex** [comment]
Alright... never mind (but keeping here for other excited fools like me).

It would seem like the config at `~/.config/nvim/after/plugin/vimwiki.lua` was either not being loaded, or faulty.

I made a file again at `~/.config/nvim/ftdetect/vimwiki.vim` and populated with:

```vim
let g:vimwiki_ext2syntax = {}
let g:vimwiki_global_ext = 0
let g:vimwiki_list = [{'path': '~/vimwiki/',
                      \ 'syntax': 'markdown', 'ext': 'md'}]

```

And now everything is functioning as expected.

**Comment by tjex** [comment]
or `nvim/after/plugin/vimwiki.lua`:

```lua
vim.g.vimwiki_list = { { path = '~/notes/tech', syntax = 'markdown', ext = 'md' } }
vim.g.vimwiki_ext2syntax = {}
vim.g.vimwiki_global_ext = 1
```

(probably better)

**Comment by talayhan** [comment]
Thanks for saving my day. I really annoyingly faced this after moving from vimrc to lua config (I don't know if it's related).

I created the same file under `~/.config/nvim/ftdetect/` with the name `vimwiki.lua` and rewrite:

```
vim.g.vimwiki_global_ext = 0
vim.g.vimwiki_list = {
  {
    path = '~/vimwiki/',
    syntax = 'markdown',
    ext = '.md'
  }
}
```
