### ISSUE TITLE
How can I disable VimWiki's table mode?

### ISSUE THREAD

**Issue by stellarorion** [vimwiki/vimwiki#1385]
Prior to submitting a new issue make sure to complete these steps:

- [x] Include the VimWiki settings from your `.vimrc`
- [x] Include the syntax you are using (default / Markdown / MediaWiki) 
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.

## Question

Is it possible to disable Vimwiki's table formatting? I would prefer to use vim-table-mode plugin for managing Markdown tables, unfortunately I couldn't figure out how to disable the default automatic table formatting of VimWiki.

### Output of VimwikiShowVersion

Version: 2023.05.12
Os: Linux
Vim: 801
Branch: dev
Revision: 0bb1b49
Date: 2023-10-31 13:45:18 -0300

### Config:

call plug#begin()

Plug 'David-Kunz/gen.nvim'
Plug 'dhruvasagar/vim-table-mode'
Plug 'ntpeters/vim-better-whitespace'

" Telescope
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.5' }

Plug 'nvim-treesitter/nvim-treesitter'

" LF
Plug 'ptzz/lf.vim'
Plug 'voldikss/vim-floaterm'

" Wiki
"Plug 'lervag/wiki.vim'
Plug 'vimwiki/vimwiki'

" vim-markdown
"Plug 'godlygeek/tabular'
"Plug 'plasticboy/vim-markdown'

call plug#end()

set number

set linebreak

set spelllang=cs,en

set clipboard+=unnamedplus

" Key bindings
let g:mapleader = " "
nnoremap <leader><leader>f <cmd>Telescope find_files<cr>

" Settings

" Wiki.vim
let g:wiki_root = '~/Documents/TDrive/'

" Vimwiki
let g:vimwiki_list = [{'path': '~/Documents/TDrive/', 'syntax': 'markdown', 'ext': 'md', 'custom_wiki2html': '~/Documents/TDrive/customwiki2html.sh'}]
let g:vimwiki_global_ext = 0
let g:vimwiki_table_mappings = 0

" For wiki.vim

"let g:vim_markdown_folding_disabled = 1
"set conceallevel=2

set nocompatible
filetype plugin on
syntax enable

**Comment by brennen** [comment]
I'd try the following:

```vim
    " disable table mappings:
    let g:vimwiki_key_mappings =
      \ {
      \ 'table_mappings': 0,
      \ 'table_format': 0
      \ }
    let g:vimwiki_table_auto_fmt = 0
```
