### ISSUE TITLE
Addition of new line is not reflected in conversion from .wiki to .html 

### ISSUE THREAD

**Issue by vishalrao009** [vimwiki/vimwiki#1390]
Prior to submitting a new issue make sure to complete these steps:

- [x] Include the VimWiki settings from your `.vimrc`
-
let vimwiki = {'path': '~/phd_work/notes/vimwiki/','path_html':'~/phd_work/notes/wiki/vimwiki_html/', 'syntax': 'default', 'ext': '.wiki','html_header':'~/phd_work/notes/wiki/vimwiki_html/header.html','html_footer':'~/phd_work/notes/wiki/vimwiki_html/footer.      html','template_path':'~/phd_work/notes/wiki/templates','template_default': 'default_colored','template_ext':'.html'}

- [x] Include the syntax you are using (default / Markdown / MediaWiki) 
I am using default syntax.

- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.

Try writing few lines which does not contain any of '.' or ':' characters, it's conversion to html does not include the new line character. If want to convert a column of numbers which does not end with '.' or ':', then all numbers are represented without any new line. 

- [x] Include the output of `:VimwikiShowVersion`.
Version: 2023.05.12                                                                         
Os: Linux
Vim: 801
Branch: dev
Revision: 0bb1b49
Date: 2023-10-31 13:45:18 -0300

**Comment by brennen** [comment]
Have a look at `:help g:vimwiki_text_ignore_newline`.
