### ISSUE TITLE
[HOW]: Images inline in document ?

### ISSUE THREAD

**Issue by danielb2** [vimwiki/vimwiki#141]
I've tried a few ways to get images to display inline lately, and it used to be I just put the URL in there in a list: 

```
= Nintendo DSi =
http://upload.wikimedia.org/wikipedia/commons/8/85/Nintendo-DSi-Bl-Open.jpg
```

However, this no longer works. I've tried:

```
[[http://upload.wikimedia.org/wikipedia/commons/8/85/Nintendo-DSi-Bl-Open.jpg http://upload.wikimedia.org/wikipedia/commons/8/85/Nintendo-DSi-Bl-Open.jpg]]
```

and
```
[[http://upload.wikimedia.org/wikipedia/commons/8/85/Nintendo-DSi-Bl-Open.jpg | http://upload.wikimedia.org/wikipedia/commons/8/85/Nintendo-DSi-Bl-Open.jpg]]
```

but none work. How do I get the image to display inline?

**Comment by danielb2** [comment]
My settings:

```
let g:vimwiki_list = [{
  \ 'path': '~/misc/vimwiki/',
  \ 'path_html': '~/web/otherware.org/vimwiki/',
  \ 'template_path': '~/misc/vimwiki/',
  \ 'template_default': 'default',
  \ 'template_ext': '.tpl.html',
  \ 'css_name': 'style.css',
  \ 'auto_export': 1}]
```

**Comment by Fruglemonkey** [comment]
Does this work?

https://github.com/vimwiki/vimwiki/blob/master/doc/vimwiki.txt#L1002-L1003

I.E

    {{http://www-archive.xenproject.org/images/globals/Rackspace_Logo_VerySmall.png}}

**Comment by EinfachToll** [comment]
"doesn't work" is a little unspecific. What is the expected output and what is the actual output?
Are you using the latest version from the dev branch?
Both of this should work:
`http://upload.wikimedia.org/wikipedia/commons/8/85/Nintendo-DSi-Bl-Open.jpg`
`{{http://upload.wikimedia.org/wikipedia/commons/8/85/Nintendo-DSi-Bl-Open.jpg}}`

Both behave the same in Vim, but when converted to HTML, the first one becomes a link to the image and the second one the actual image embedded in the page.

This, however:
`[[http://upload.wikimedia.org/wikipedia/commons/8/85/Nintendo-DSi-Bl-Open.jpg]]`
produces garbage in the HTML output, which should be fixed.

**Comment by danielb2** [comment]
> "doesn't work" is a little unspecific.

I just mean that since the goal was to produce an online image, and it was unsuccessful using that format, I just meant it didn't work. To be more specific, it just produces a URL instead of an inline image. I tried the four options you specified, and only the `{{ }}` notation made the image inline. Thank you @Fruglemonkey 


Here's a screenshot of the all the four options labeled in order:

![screen shot 2015-07-03 at 7 59 18 am](https://cloud.githubusercontent.com/assets/26678/8501350/71734664-2159-11e5-904a-874bd6b38608.png)

produces:

![screen shot 2015-07-03 at 7 58 54 am](https://cloud.githubusercontent.com/assets/26678/8501355/7acdd9b8-2159-11e5-9cf7-66ff6813eeeb.png)
