### ISSUE TITLE
Collision with vim-vinegar's mapping

### ISSUE THREAD

**Issue by fancsali** [vimwiki/vimwiki#1426]
Prior to submitting a new issue make sure to complete these steps:

- [X] Include the VimWiki settings from your `.vimrc`
```
let g:vimwiki_list = [
    \ {'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': '.md', 'auto_diary_index': 1, 'diary_caption_level': 6, 'auto_tags': 1, 'listsyms': ' .X'},
    \ {'path': '~/vimwiki-test/', 'syntax': 'markdown', 'ext': '.md', 'auto_diary_index': 1, 'diary_caption_level': 6, 'auto_tags': 1, 'listsyms': ' .X', 'diary_frequency': 'weekly'}
    \ ]
```
- [X] Include the syntax you are using (default / Markdown / MediaWiki) -- **Markdown**
- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.

The default mapping for `VimwikiRemoveHeaderLevel` (`vimwiki_-`) collides with the mapping to open the file browser in `vim-vinegar` (https://github.com/tpope/vim-vinegar).

- [X] Include the output of `:VimwikiShowVersion`.
```
Version: 2024.01.24
Os: Linux
Vim: 901
Branch: todo-quickfix
Revision: acdfc1d
Date: 2024-06-25 15:23:41 +0100
```

**Comment by brennen** [comment]
This has been in place for at least 14 years, and I don't think we can really guarantee that keybindings in VimWiki won't collide with those from any other plugin. I'd suggest rebinding in this case.
