### ISSUE TITLE
Error: Conversion to HTML is not supported for this syntax

### ISSUE THREAD

**Issue by coderj001** [vimwiki/vimwiki#1434]
Prior to submitting a new issue make sure to complete these steps:

- [x] Include the VimWiki settings from your `.vimrc`
- [x] Include the syntax you are using (default / Markdown / MediaWiki) 
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.
```
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => VimWiki
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let g:vimwiki_list = [{'path': '~/Misc/vimwiki/', 'path_html': '~/Misc/vimwiki2html/', 'auto_export': 1,
                      \ 'syntax': 'markdown', 'ext': '.md'}]

let g:vimwiki_global_ext = 0
let g:vimwiki_ext2syntax = {'.md': 'markdown',
                  \ '.mkd': 'markdown',
                  \ '.wiki': 'media'}

```
Version: 2024.01.24

Everything works fine but get error when i save any vimwiki files,
```
Vimwiki: Error: Conversion to HTML is not supported for this syntax
```

**Comment by brennen** [comment]
VimWiki doesn't convert Markdown to HTML on its own.  You can specify a script to do conversion.

See [Changing wiki syntax](https://github.com/vimwiki/vimwiki/blob/dev/README.md#changing-wiki-syntax) in README.md and `:help vimwiki-option-custom_wiki2html`.

This could be better documented. I filed #1435 for that.
