### ISSUE TITLE
vimwiki poor list default in input mode

### ISSUE THREAD

**Issue by atsepkov** [vimwiki/vimwiki#145]
When I'm creating a list, if I'm in normal mode on top of a list item and press <kbd>o</kbd> to start the next line, the plugin (or maybe vim) automatically turns the next line into a bullet as well (inserting `- ` and setting my cursor after the space), I like that.

A more common use case, however, is for me to type a long list without going out of insert mode. In that case, the plugin simply aligns my indentation with with the first letter of previous line without inserting the `- ` before. As you can imagine this is even more annoying than if it didn't do the alignment at all, as I now have to backspace twice to put the dash back in:

    - list item[cursor in input mode]

Result after pressing enter:

    - list item
      [cursor in input mode]

**Comment by EinfachToll** [comment]
Which version of Vimwiki are you using? In the dev branch, the behavior of list input changed a lot. Also, see `:h vimwiki-lists`.
