### ISSUE TITLE
vimwiki and something funky with setf? incompatibility with other plugins

### ISSUE THREAD

**Issue by atsepkov** [vimwiki/vimwiki#146]
As reported in #145 vimwiki seems to have a poor default for starting out the next newline when working with lists.

I figured I'd work around this issue by adding a macro to my version of smartinput plugin (https://github.com/atsepkov/vim-smartinput), the problem is that vimwiki seems to ignore the rules from the plugin. Rules should automatically apply if `setf` is set correctly, which leads me to believe vimwiki is doing something funky with `setf` that I don't understand. I tried a few experiments:

- add a new macro for 'vimwiki' filetype in `vim-smartinput/autoload/smartinput.vim`
- add the same macro for 'markdown' filetype (same file)
- open a new file, type `:setf markdown`, macro **works correctly**, close file
- open a new file, type `:setf vimwiki`, macro has **no effect**, close file
- open a new file, type `:setf vimwiki`, then change it to `:setf markdown`, macro **has no effect**, close file
- open a new file, type `:setf markdown`, then change it to `:setf vimwiki`, macro **has no effect**, close file
- open a new file, type `:setf markdown`, then change it to `:setf vimwiki`, then change it back to `:setf markdown`, macro **has no effect**, close file

So it seems that no matter what order I change filetype in, if at any point it's changed to 'vimwiki', it stops respecting the macro.

**Comment by EinfachToll** [comment]
Vimwiki of course sets the filetype of a buffer when it's loaded and if it's a wiki file. Other than that, I'm not aware of other fancy stuff Vimwiki does regarding the filetype. Are you sure it's Vimwiki's fault that smartinput doesn't work? Also, if you want me to try to reproduce the issue, please provide more specific steps, because I don't know how smartinput works.

**Comment by EinfachToll** [comment]
Feel free to reopen if the problem persists.
