### ISSUE TITLE
Can't make file links with spaces

### ISSUE THREAD

**Issue by Tanath** [vimwiki/vimwiki#147]
Links to local files containing a space anywhere in the path cause the link to end incorrectly at the space, even if you start typing the link manually with [[ and even if you quote or escape the spaces.

**Comment by EinfachToll** [comment]
\*sigh\* What version of Vimwiki are you using? What exactly are you trying? What do you expect? What do you see instead?

**Comment by Tanath** [comment]
Vimwiki 2.1.
This was reproducible for me yesterday - I couldn't get it working. Today I can't seem to reproduce it. I guess this can be closed. Sorry.

**Comment by jondkinney** [comment]
I'm seeing this problem with Version: 2.2

Here's a repro:

**Comment by jondkinney** [comment]
I'm seeing this problem with Version: 2.2

It seems to be when you have slashes in the heading. I get why this is a problem, but seems like there is a solution to maybe urlencode the file name or something to eliminate any chars being an issue.

Here's a repro: 

![screen recording 2016-01-11 at 02 27 pm](https://cloud.githubusercontent.com/assets/4521/12247008/7f558372-b877-11e5-8922-35da0f208731.gif)

**Comment by EinfachToll** [comment]
@jondkinney Thanks for the little screencast. But I still don't understand, what the problem actually is. Wiki files can be in a subdirectory of your main wiki directory and a slash in a wiki link is just the path separator, see `:h vimwiki-syntax-links`. So, if you press Enter on a link `[[testing / this out]]` Vimwiki just asks if you really want to create the subdirectory `testing /`. I think there is nothing wrong here.

**Comment by jondkinney** [comment]
@EinfachToll huh, I guess that's my misunderstanding then. I didn't expect to be able to create a subdirectory, but that's good to know. I was just expecting to be able to have a file name with a slash in its title. Thanks for taking the time to reply!!
