### ISSUE TITLE
URL encode html links

### ISSUE THREAD

**Issue by tsurai** [vimwiki/vimwiki#148]
Html links to wiki pages should always be URL encoded to allow the usage of characters like # and ? inside a wiki page name.

According to [RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.2) all reserved characters `! * ' ( ) ; : @ & = + $ , / ? # [ ]` should be encoded. I'm not sure where exactly this magic happens otherwise I would have made a pull request.

**Comment by hpincket** [comment]
I'm no vimwiki developer, but just to clarify:
You're asking for encoding to happen when exporting a wiki to html?
