### ISSUE TITLE
Last Change Date Script, Any Updates Since 2012?

### ISSUE THREAD

**Issue by thestumbler** [vimwiki/vimwiki#156]
I've been using the script provided by /u/habamax which puts the Last Change date in a wiki page when you exit the page.  http://code.google.com/p/vimwiki/issues/detail?id=342
And, I've started tweaking it some, so that I can append/replace the Last Change date in the file referencing the wiki page (it's a manual process at the moment, but that's generally fine for my application).  Before I get too carried away enhancing this script, just wanted to ask if there were any newer versions around.  This issue 342 was back in 2012, and I'd hate to reinvent the wheel.
-Chris

**Comment by EinfachToll** [comment]
Yes, the newest version is always on the dev branch: https://github.com/vimwiki/vimwiki/tree/dev

**Comment by thestumbler** [comment]
I meant a newer version of the referenced "Last Change" script, not vimwiki itself.  Unless that feature has been rolled into vimwiki proper. -Chris

**Comment by EinfachToll** [comment]
Whoops. No, at least in this official repo, there is no newer version and it's not included.
