### ISSUE TITLE
problem opening local files on mac

### ISSUE THREAD

**Issue by schmeisers** [vimwiki/vimwiki#158]
I'm not able to open local files on a mac.  The problem seems to be in vimwiki#base#system_open_link(url).  There's an if/else to detect the system type and to call the appropriate handler.

    if vimwiki#u#is_windows()
      call s:win32_handler(a:url)
      return
    elseif has("macunix")
      call s:macunix_handler(a:url)
      return
    else
      call s:linux_handler(a:url)
      return
    endif

On a mac, it falls through to the linux handler.  If I change s:linux_handler(a:url) to s:macunix_handler(a:url) everything works great.

**Comment by EinfachToll** [comment]
What is shown if you type `:echo has("macunix")` in Vim? And `:echo has("mac")`?

**Comment by schmeisers** [comment]
Both return 0

**Comment by EinfachToll** [comment]
OK. According to this question: http://stackoverflow.com/questions/10139972/vim-hasmacunix-or-hasmac-do-not-work the has() feature detection does not work correctly. But we can work around that. Two more tests: what do `:echo has("unix")` and `:echo system("uname")` return for you?

**Comment by schmeisers** [comment]
> :echo has("unix")

1

> :echo system("uname")

Darwin


Thanks for looking into this!

**Comment by EinfachToll** [comment]
Can you try out the latest version from the dev branch?

**Comment by schmeisers** [comment]
That worked great for me.  Hopefully someone using macvim can also test.
