### ISSUE TITLE
Vimwiki default directory

### ISSUE THREAD

**Issue by DavidParkin** [vimwiki/vimwiki#160]
Is 'vimwiki' a good default? It conflicts with the plugin name eg when using git clone. Perhaps it should be a hidden (.) directory?

**Comment by EinfachToll** [comment]
> Is 'vimwiki' a good default?

Yes :)

> It conflicts with the plugin name eg when using git clone.

But the default path is ~/vimwiki, so it's located in the home directory. Vim plugins are usually not in the home directory. Or do you mean that if you do a git clone while you are in your home directory, the plugin in cloned into your wiki folder? That may happen and is certainly annoying, but, well, it's the users fault :)

**Comment by DavidParkin** [comment]
User's fault. Not really. I meant when one clones it in order to fix one of the many problems :¬)
