### ISSUE TITLE
Reducing size of transcluded local images

### ISSUE THREAD

**Issue by manasthakur** [vimwiki/vimwiki#162]
I am using the transclusion feature for including inlined local images in my wiki. However, the size of the images is spanning twice the width of my screen.

I tried using the following syntax as given in the help file:
{{local:images/someimage.jpg|style="width:15px; height: 12px;"}}

But there is no effect in the HTML produced even after this. What could be the problem?

**Comment by EinfachToll** [comment]
If you want to specify a style for an image, you have to provide an alt text as well, like this:
`{{local:images/someimage.jpg|my image|style="width:15px; height: 12px;"}}`.

**Comment by manasthakur** [comment]
Thanks EinfachToll.
