### ISSUE TITLE
about VimwikiDiaryGenerateLinks

### ISSUE THREAD

**Issue by youanan** [vimwiki/vimwiki#163]
hello:
I use <leader>w<leader>i,
Status bar prompts this：
you can generate diary links only in a diary index page.

but，I'm already in the diary.wiki.

why？

**Comment by EinfachToll** [comment]
Is diary.wiki really the diary file for your wiki? Do you get there if you press `<Leader>wi`?
Can you post you .vimrc? (At least the section relevant to Vimwiki.)

**Comment by EinfachToll** [comment]
Feel free to reopen if the problem persists.
