### ISSUE TITLE
Is there any way(suggestion) to sync .wiki files in different machines?

### ISSUE THREAD

**Issue by ruanyl** [vimwiki/vimwiki#164]
I am now using Dropbox to sync `~/vimwiki/` folder between two laptops. Are there other suggestions to do this?

**Comment by hpincket** [comment]
I too use dropbox.

**Comment by ruanyl** [comment]
that would be super if `vimwiki` can do the sync internally, for example by `gist`. Don't know if this is possible or if there is any other plan on supporting `wiki sync`?

**Comment by EinfachToll** [comment]
> that would be super if vimwiki can do the sync internally, for example by gist.

If you already use Dropbox, why do you want something new? Why reinvent the wheel?

**Comment by ruanyl** [comment]
@EinfachToll True, Dropbox do solve my problem at the moment. But IMO, setup Dropbox with `vimwiki` is kind of 'extra' work if people want the `sync` feature. 

However, on the other hand, `sync` maybe extra feature for `vimwiki` ;)

Thank you for reply anyway :)

**Comment by EinfachToll** [comment]
This feature is a little too much for a humble vim plugin.
