### ISSUE TITLE
Provide settings so vimwiki does not map my keys by default

### ISSUE THREAD

**Issue by matthiasbeyer** [vimwiki/vimwiki#166]
Because it is really just boilerplate code for me to prevent vimwiki from mapping things I've already mapped.

**Comment by EinfachToll** [comment]
But how do you use Vimwiki then? If all that `<Leader>w` mappings come into your way, you can change that with `let g:vimwiki_map_prefix = '<Leader>e'`.

**Comment by matthiasbeyer** [comment]
Didn't know about the `map_prefix` thing. Closes this for me, thanks!

**Comment by matthiasbeyer** [comment]
To answer your question: Map the commands myself (but to something completely different than the defaults provided by vimwiki)
