### ISSUE TITLE
My vimwiki wrapper command stopped working after updating vimwiki to latest master

### ISSUE THREAD

**Issue by pitchforks** [vimwiki/vimwiki#171]
So I saw the release announce somewhere and updated vimwiki (manually, by cloning the github repo and copying over all the files, I use pathogen).

What did I do wrong:

- I did not save a copy of old vimwiki version
- I do not remember what older version of vimwiki I was using, it was some other revision from master, not a stable release, pulled at a random time

These mistakes restrict the amount of useful information I can add to the bug report, sorry. Yet I hope to get some pointers about my issue.

To launch vimwiki with a wiki in a custom location, I cd into a directory that has a bunch of `.wiki` files and run the following shell script wrapper:

    HTML="$PWD/html"; gvim -c "let g:vimwiki_conceallevel=0 | let g:vimwiki_list = [{}, {'path': '$PWD', 'path_html': '$HTML'}] | normal 2\\
ww"

When running this, it will launch gvim and open index.wiki in it. After updating the vimwiki codebase, it stopped working. This looks like I've hit a backwards incompatibility issue. How can I fix my script so it works again? Thanks.

PS: I have no custom vimwiki settings in my vimrc, except

    let g:vimwiki_folding='list'

**Comment by EinfachToll** [comment]
I think I can reproduce the issue. Does it help if you replace `'$PWD'` with `'$PWD/'`? (And, likewise, append a slash to `html`).

**Comment by pitchforks** [comment]
Thanks, your suggestion makes a difference.

This code

    HTML="$PWD/html/"; gvim -c "let g:vimwiki_conceallevel=0 | let g:vimwiki_list = [{}, {'path': '$PWD/', 'path_html': '$HTML'}] | normal 2\\ww"

loads a custom located vimwiki in vim fine.

Should I adjust my shell wrapper script or you'll be making changes to fix the broken backwards compatibility?

**Comment by EinfachToll** [comment]
I will look into this, backwards compatibility is important. Still, just fixing your script is the easiest solution for now.

**Comment by EinfachToll** [comment]
I think I fixed the problem now. It is admittedly rather a quick hack, but I'm planning to refactor the whole handling of user settings and global variables etc.
