### ISSUE TITLE
RSS feed of diary entries.

### ISSUE THREAD

**Issue by DerekLeach** [vimwiki/vimwiki#172]
Would it be possible to produce an RSS XML file containing the latest 10 diary entries? Something like:

``` xml
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
<channel>
 <title>My VimWiki Diary</title>
 <description>VimWiki Diary Entries</description>
 <link>http://www.example.com/diary/index.html</link>
 <lastBuildDate>Sat, 28 Nov 2015 16:20:00 +0000 </lastBuildDate>

 <item>
  <title>Header 1</title>
  <description><![CDATA[html <b>content</b> of my diary entry.]]></description>
  <link>http://www.example.com/diary/2015-11-28.html</link>
  <pubDate>Sat, 28 Nov 2015 16:20:00 +0000</pubDate>
 </item>

 <item>
  <title>Header 1</title>
  <description><![CDATA[html content of my diary entry.]]></description>
  <link>http://www.example.com/wiki/diary/2015-11-25.html</link>
  <pubDate>Wed, 25 Nov 2015 15:40:00 +0000</pubDate>
 </item>
</channel>
</rss>
```

The .rss file would be written to the html directory. I imagine it would use aspects of VimwikiDiaryGenerateLinks and Vimwiki2HTML.

**Update:**

I copied the RSS example from wikipedia, but I mistakenly left out '<' and '>' around the CDATA sections.

**Comment by EinfachToll** [comment]
My knowledge of RSS and the like is limited, but it looks like it would be not that complicated.

**Comment by ranebrown** [comment]
If there is still interest in this please open a PR.

**Comment by tinmarino** [comment]
#934 added the feature with `:VimwikiRss`
