### ISSUE TITLE
Links to other notes broken since reinstall

### ISSUE THREAD

**Issue by 99arobe** [vimwiki/vimwiki#173]
I've recently bought a new system and downloaded my wiki from my dropbox backup and reinstalled vimwiki. All notes correctly load but none of the links between notes work anymore. I can create new notes and they link correctly but any links that I try to follow from/to my old notes no longer work. Pressing enter on them does nothing. Is there an obvious reason that this would happen and if so how can I fix it?

**Comment by EinfachToll** [comment]
Do you use CamelCaseWords as links? In an earlier version of Vimwiki, they where allowed as links, but they work no longer. Use `[[Link]]` instead.
Are the settings in your .vimrc still correct? Especially 'path' in g:vimwiki_list. There is currently a bug (#171) which breaks links opening under some circumstances when the 'path' doesn't end with a slash.

Apart from that, I have no idea at the moment what causes your issue. Try to open Vimwiki and type `:echom vimwiki#base#resolve_link('Bla').filename`. This shows to which file you would get to if you would hit a link `[[Bla]]` in the current buffer. Is the output correct?

**Comment by 99arobe** [comment]
I think I've made a bit of progress on this. 

It appears that the previous version of Vimwiki that I was using allowed me to create new wiki notes that were named things like: #FEATURE-1 or #ISSUE-34. In the version that I am now using it won't create a new wiki note if it starts with `#`. Also, if it has `#` anywhere in the file name (e.g. ISSUE-#23a) it will correctly create a new note but the filename will be terminated from the `#` onwards (e.g ISSUE-). Is there a reason why this might have changed?

My current solution is to change my naming format so that I don't use `#` anywhere but I assume this could also apply to other characters too?

To answer the rest of your questions in case it's helpful. I don't use camel case. All links are [[like-this]]. My .vimrc is the same as it was before pointing at the correct path and path_html directories. Originally these directories didn't end with `/` but even after adding this the links still don't work. 

When I type `:echom vimwiki#base#resolve_link('Bla').filename` and replace `Bla` with one of my old links the string it displays is the path to the note that I am currently in, so it's certainly possible that all of the old links are, for some reason, linking to the current note (rather than simply not working at all).

**Comment by pitchforks** [comment]
> Do you use CamelCaseWords as links? In an earlier version of Vimwiki, they where allowed as links, but they work no longer. Use [[Link]] instead.

Can you please explain this? Because I don't understand what it means. Which part of the documentation should I read to learn more about it?

**Comment by EinfachToll** [comment]
@99arobe: yes, that's the reason. Now, `[[foo#bar]]` means "go to file foo.wiki and in this file jump to an anchor 'bar'". I will add a note to the changelog.

@pitchforks: In version 1.2 and before, something like `ThisIsALink` was a wiki link, even without brackets. As of version 2.0, you have to write `[[ThisIsALink]]`. See the section for version 2.0 in the changelog in the help file.
