### ISSUE TITLE
Error when opening wiki pages

### ISSUE THREAD

**Issue by fpnick** [vimwiki/vimwiki#175]
Hi,

when I open a wiki page (by using :VimwikiIndex or following a link within the wiki) I get the following error message: 
> Error executing "function <SNR>57_setup_buffer_enter":
> Line   84:
> E486: Pattern not found: setup_buffer_enter
Unfortunately I'm not sure what has changed in my configuration since the last time everything worked fine (which it did a couple of days ago).

My Vim version is  7.4.629 .

Any hints?

Fabian.

P.S.: Could be related to #174

**Comment by EinfachToll** [comment]
Are you using the latest Vimwiki version from the dev branch? Can you post the relevant settings from your .vimrc?

**Comment by fpnick** [comment]
I'm seeing the same issue on the dev branch and the master branch.

I don't have any vimwiki related settings in my vimrc - at least not intentionally. But I attached my vimrc if you want to have a look...
[vimrc.txt](https://github.com/vimwiki/vimwiki/files/58033/vimrc.txt)

**Comment by EinfachToll** [comment]
Don't you set any vimwiki settings at all, like the path to your wiki files? Or do you make settings later?
Can you post the content of the variable g:vimwiki_list before you execute VimwikiIndex? You get the content with the following command (it appears in the first line of the buffer)

    :call append(0, string(g:vimwiki_list))


This is very very very strange. I don't even have an idea what the error message you posted is supposed to tell us. I don't understand what 'line 84' refers to, because the function setup_buffer_enter() doesn't have 84 lines. Do you know enough vim script to pinpoint the exact place where the error occurs?

**Comment by fpnick** [comment]
Here's the output

> [{'maxhi': 0, 'css_name': 'style.css', 'auto_export': 0, 'diary_index': 'diary', 'template_default': 'default', 'nested_syntaxes': {}, 'auto_toc': 0,          'auto_tags': 0, 'diary_sort': 'desc', 'path': '/home/fnick/vimwiki/', 'diary_link_fmt': '%Y-%m-%d', 'template_ext': '.tpl', 'syntax': 'default',               'custom_wiki2html': '', 'index': 'index', 'diary_header': 'Diary', 'ext': '.wiki', 'path_html': '/home/fnick/vimwiki_html/', 'temp': 0, 'template_path': '/    home/fnick/vimwiki/templates/', 'list_margin': -1, 'diary_rel_path': 'diary/'}]

As I see it has the path to my wiki files in there, however I didn't set that explicitly - it's the default I assume?!

I don't know a lot of vimscript, but I did find out that commenting out line 499 of vimwiki.vim
> exe 'autocmd BufWinEnter *'.s:ext.' call s:setup_buffer_enter()'
solves the issue. However this is not a 'real' solution I guess...
It looks like this line is somehow calling setup_buffer_enter but can't find it. This is just a guess though.

**Comment by EinfachToll** [comment]
> As I see it has the path to my wiki files in there, however I didn't set that explicitly - it's the default I assume?!

Ok, you don't mess up the settings. Yes, these are the default values.


> I don't know a lot of vimscript, but I did find out that commenting out line 499 of vimwiki.vim
    exe 'autocmd BufWinEnter *'.s:ext.' call s:setup_buffer_enter()'
solves the issue. However this is not a 'real' solution I guess...

Ok. Can you replace in this line "exe" with "echom"? This will print out the exact command instead of executing it. And can you post the output?

> It looks like this line is somehow calling setup_buffer_enter but can't find it.

Does that mean there is no function in the file plugin/vimwiki.vim on your computer? It should looke like this: https://github.com/vimwiki/vimwiki/blob/master/plugin/vimwiki.vim#L140

BTW, is the error message from your start post really the exact text, character for character, that you see?

**Comment by fpnick** [comment]
The output is 
> autocmd BufWinEnter *.wiki call s:setup_buffer_enter()

> Does that mean there is no function in the file plugin/vimwiki.vim on your computer? 
The function is there, so vim SHOULD find it. What I meant was it looks like for some reason it isn't

I translated the error message from german to english, but from your username I assume you can read the german one as well...

> Fehler beim Ausführen von "function <SNR>57_setup_buffer_enter":
> Zeile   84:
> EE486: Muster nicht gefunden: vimwi

Ooops, now that's funny: where it said
>  E486: Muster nicht gefunden: setup_buffer_enter

before, it now says
> EE486: Muster nicht gefunden: vimwi

This is REALLY strange.

**Comment by EinfachToll** [comment]
Das sieht alles nach einem sehr speziellen Problem aus, das andere wohl nicht betrifft. Dann können wir uns auch gleich auf deutsch unterhalten.

>    EE486: Muster nicht gefunden: vimwi
> This is REALLY strange.

In der Tat. Steht da wirklich EE486 oder doch E486? Kannst du mal sicherstellen, dass Vimwiki auch ordentlich installiert ist? Also mal in .vim/bundle/ gehen, vimwiki/ löschen und mit `git clone https://github.com/vimwiki/vimwiki.git` nochmal installieren?

**Comment by fpnick** [comment]
Sorry, da steht nur ein E. Das zweite muss beim rumeditieren dazugekommen sein...

Auch mit der 'manuellen' Installation bekomme ich wieder 
> Fehler beim Ausführen von "function <SNR>57_setup_buffer_enter":
> Zeile   84:
> E486: Muster nicht gefunden: vimwi

Sehr merkwuerdig. Bis vor ein paar Tagen ging alles gut. Mich beschleicht das Gefuehl, das irgendetwas anderes querschiesst, aber ich habe an der .vimrc nichts geaendert. Nur zwei oder drei andere Plugins haben sich vor ein paar Tagen mal aktualisiert...

**Comment by EinfachToll** [comment]
Vim selbst hast du wohl auch nicht aktualisiert, nehme ich an, jedenfalls ist 7.4.629 auch nicht die aktuelle Version.
Und seit wann genau gibts jetzt den Fehler? Das letzte Release von Vimwiki war ja vor 15 Tagen. Kannst du dich erinnern, ob der Fehler gleich nach dem Update aufgetreten ist?

**Comment by fpnick** [comment]
Nein, vim habe (kann) ich nicht aktualisiert.
Gut moeglich, dass es den Fehler seit dem Update gibt. Hatte aber auch schon versucht, aeltere Commits auszuchecken, ohne Erfolg. 

Was waere denn der Commit den ich auschecken muesste, um an die Version vor dem letzten Update zu kommen?

**Comment by EinfachToll** [comment]
Das wäre `git checkout v2.1`.

**Comment by fpnick** [comment]
Habe mal ein git bisect gemacht mit folgendem Ergebnis:

1c88deeee0682b508a419640f4eb353ed014f755 is the first bad commit
commit 1c88deeee0682b508a419640f4eb353ed014f755
Author: Maxim Kim <habamax@gmail.com>
Date:   Tue Jun 18 18:43:03 2013 +0400

    Issue 415: No-folding configuration ignored.
    
    When g:vimwiki_folding is set to '' there should be no folding no matter
    what foldmethod you have in your .vimrc.

:040000 040000 7611b8d36f0e812afc58461bb02fca4c0394f001 c06531bf705990d0f10e81bc4daf962b250538c8 M	plugin

**Comment by EinfachToll** [comment]
Eieiei, der Fehler ist, dass dort "normal zE" ausgeführt wird, also die Tastenkombination zE. Und du hast z auf irgendwas anderes gemappt, wie ich deiner vimrc entnehme.
Ich werde wohl gleich mal einen Hotfix machen.

**Comment by EinfachToll** [comment]
So, darfst wieder den master-branch auschecken.

**Comment by fpnick** [comment]
Danke. Fix funktioniert!
