### ISSUE TITLE
Error in ftplugin\vimwiki.vim when opening wiki page

### ISSUE THREAD

**Issue by OISumeko** [vimwiki/vimwiki#176]
OS: Windows 7 x64
Vim 7.4, official 32-bit GUI distribution
vimwiki updated to commit 3bd3d9b86036b21aecd69f0a1e572643d626c280

I have an environment variable ```%GDRIVE%``` set up to point to my google drive directory located at ```C:\Users\Cameron Grout\Google Drive\```. In my vimrc, I have the vimwiki configuration: 
```
let g:vimwiki_list = [{'path': '$GDRIVE\\Documents\\vimwiki\\', 'index': 'main', 'auto_toc': 1, 'auto_export': 1}]
```

This path correctly expands, and my wiki files appear where I expect them to be. However, when opening a wiki file or navigating through wiki links, I get the error:

```
Error detected while processing C:\Users\Cameron Grout\vimfiles\bundle\vimwiki\ftplugin\vimwiki.vim
line   34:
E518: Unknown option: Grout\Google
```

This error can be dismissed and everything seems to function normally, but it is a bit frustrating having this pop up every time I change files. As a workaround, I added the junction ```C:\GDrive <==> C:\Users\Cameron Grout\Google Drive\``` which resolves the issue, but I'd prefer not to have to hardlink directories on all my machines. Any chance that handling paths with spaces is an easy fix here?

**Comment by EinfachToll** [comment]
Should be fixed now. Can you try the latest version?

**Comment by OISumeko** [comment]
Tested with 949b29b6943a0448f6d4551d62d2d24843b00496 and that works great. Thanks for that.
