### ISSUE TITLE
Navigation using vimwikidiarynext/prevday broken with multiple diaries 

### ISSUE THREAD

**Issue by Fruglemonkey** [vimwiki/vimwiki#177]
My current situation: I have two diaries, one for personal usage and one acting as a worklog. My current settings for vimwiki are as follows:

```
Plugin 'vimwiki/vimwiki'
let g:vimwiki_list = [{'path': '~/Dropbox/wikis', 'path_html': '~/Dropbox/wikis_html/'},
                     \{'path': '~/Dropbox/xxx/worklogs', 'path_html': '~/Dropbox/xxx/worklogs_html'}]

let g:vimwiki_dir_link='index'
let g:vimwiki_folding='syntax' 
let g:vimwiki_table_mappings=0
let g:vimwiki_use_mouse=1
```

If I'm in my worklog diary, and I use the vimwikidiaryprevday mapping, I instead land in my regular diary.

**Comment by Fruglemonkey** [comment]
However, if I open another entry from the same worklog in another buffer, the mapping works as expected.

iirc, this problem has been around for a while?

**Comment by EinfachToll** [comment]
> iirc, this problem has been around for a while?

Yes. I hope this issues is solved (or at least easier to solve) when I have refactored the way Vimwiki stores its internal state, which is a (relatively huge) issue I'm working on at the moment.

**Comment by ranebrown** [comment]
@Fruglemonkey can you confirm if this is still an issue in the latest `dev` branch? #256 was completed and may have resolved the issue.

**Comment by ranebrown** [comment]
I did a quick test and this seems resolved for both markdown and default syntax. If you are still having issues please reopen.
