### ISSUE TITLE
"vimwiki_+" [apostrophe issue?]

### ISSUE THREAD

**Issue by icaroperseo** [vimwiki/vimwiki#178]
Good day!

Apparently I found a little problem using the functionality described in the thread topic. Every time I try to create the following link (visual mode, entirely select the lower line and and press the `+` key):

```
https://www.perseosblog.com|Perseo's Blog
```

I get this error message (sorry for that the information below is not textually identical because my _Linux system_ is set to the _Spanish language_):

```
It found an error processing the function vimwiki#base#normalize_link..<SNR>162_normalize_link_syntax_v:
line 14
The expression is not valid: 'https://www.perseosblog.com|Perseo's Blog'
It has detected an error while processing the function vimwiki#base#normalize_link:
line 9
missing ":endif"
```

Moreover, I tried the following:

```
https://www.perseosblog.com|Perseo
```

and

```
https://www.perseosblog.com|Perseo Blog
```

and everything works as expected. I am currently using the default syntax —Google Code wiki syntax— for vimwiki, as well as more recent version of vimwiki —provided by NeoBundle— and _GVim_ 7.4.

Best regards.

**Comment by Nudin** [comment]
This has been fixed quite a while ago.
