### ISSUE TITLE
vimwikify startify

### ISSUE THREAD

**Issue by linuxcaffe** [vimwiki/vimwiki#18]
I was just introduced to Startify;

https://github.com/mhinz/vim-startify
"Startify is a plugin that shows recently used files, bookmarks and
sessions that were saved to a certain directory."

The description under-states how cool this plugin really is, 
quite feature-rich and for vim users, it is total candy!

Startify allows user-defined header and footer, and as I played with them, I realized one thing I would really like to be able to do is to "wikify" the footer, to edit it in place, and to use all the markup and links that vimwiki has to offer.. but I have no idea how to set that up :)

**Comment by ranebrown** [comment]
If there is still interest please create a PR to support this.
