### ISSUE TITLE
Unknown function: vimwiki#lst#kbd_oO

### ISSUE THREAD

**Issue by madjxatw** [vimwiki/vimwiki#180]
"Unknown function: vimwiki#lst#kbd_oO" is given when pressing o/O in Normal mode.
"Not enough arguments for function: vimwiki#lst#kbd_cr" is given when pressing Enter in Insert mode

**Comment by EinfachToll** [comment]
The function vimwiki#lst#kbd_oO was present in an old release of Vimwiki, but not in the current. Looks like something went wrong with your installation of Vimwiki. Make sure you remove all old files (also from autoload/vimwiki/) and install it again. Where the files are exactly depend on your plugin manager, if you use one.

**Comment by madjxatw** [comment]
yes, this is my fault. I reviewed the source code and found vimwiki#lst#kbd_oO has been divided into two separate functions. I have a old version of vimwiki.vim in ~/.vim/ftplugin/ which conflicts to the  current version of vimwiki managed by vundle.
Thanks for your reply!
