### ISSUE TITLE
Proposol to change default link template for markdown syntax

### ISSUE THREAD

**Issue by lotabout** [vimwiki/vimwiki#185]
Currently, when we normalize a link(press enter on a word), we will get the vimwiki-style link like:

```
[[some link]]
```

I think it would be better to generate markdown-style links when using markdown syntax, like:

```
[some link](some link)
```
In this way, it will be more consistent. Cause when you open this file in other editors, the link will still work(at least be parsed as a link).

So here I am  to suggest to change the default link template for markdown syntax to the markdown-style. Or at least add an option for this change.

**Comment by lotabout** [comment]
Sorry that I just found out this issue is the same to #64 . Close it for duplication.

**Comment by borismus** [comment]
The other issue is also closed. Would be great to get this fixed!
