### ISSUE TITLE
Create a link using mapping vimwiki_+ fails with links http:// https:// file://

### ISSUE THREAD

**Issue by xeyownt** [vimwiki/vimwiki#188]
Creating a vimwiki link with the '+' shortcut doesn't work with links like `http://` `https://` `file://`. For instance, type the following link:
```
https://github.com/vimwiki/vimwiki
```

Move the cursor over `https` and press '+' key. This gives
```
[[https]]://github.com/vimwiki/vimwiki
```
Undo, and move it over `github` and press '+'. This gives:
```
https:[[//github.com/vimwiki/vimwiki]]
```

In both case, the expected result is
```
[[https://github.com/vimwiki/vimwiki]]
```

The same applies for `http://` and `file://`.

**Comment by EinfachToll** [comment]
These raw URLs work also without the brackets. The brackets are only necessary if you want to add a description to the link. Anyway, this should work now.
