### ISSUE TITLE
Markdown emphasis syntax seems incorrect

### ISSUE THREAD

**Issue by zachfedor** [vimwiki/vimwiki#189]
According to the [markdown syntax guide at Daring Fireball](https://daringfireball.net/projects/markdown/syntax#em), the syntax for inline emphasis is incorrect. For example:

```
for italic text, you can use:
*single asterisks* or _single underscores_

for bold text, you can use:
**double asterisks** or __double underscores__
```

I'm totally open to submitting a PR to get this plugin more inline with the official syntax, but I thought I'd ask here first just in case. I do see a benefit in being able to mix and match bold and italic styles, though. And I'm guessing this is the rationale for the difference. Or it could be something else entirely. Just let me know how to proceed.

Thanks! And thanks for a great plugin!

**Comment by EinfachToll** [comment]
Yes, the Markdown support differs a little from the (more or less) official spec, see also #186. Feel free to create a PR, since I'm busy at the moment.

**Comment by zachfedor** [comment]
Excellent. I'll start on it tonight.

The implementation as I'm planning it now will hopefully allow using either `*` or `_` for _italic_ and either `**` or `__` for **bold**, while allowing both (i.e. __*bold italics*__) at the same time with any of the examples below:
```
*__bold italics__*
_**bold italics**_
**_bold italics_**
__*bold italics*__
```

If anyone has any other thoughts, feel free to chime in!

**Comment by ranebrown** [comment]
See #318
