### ISSUE TITLE
executable links [[command: args|description]]

### ISSUE THREAD

**Issue by linuxcaffe** [vimwiki/vimwiki#19]
I'm not sure if such a thing exists already, and it leans towards document templating. My example use-case is all taskwarrior (www.taskwarrior.org) but I can see it working with lots of other executables, let me try and describe it. 

I would like to be able to place links in an anything.wiki that

a) insert (replace themselves with) the result of a command as a block of text, into the buffer

<pre>
[[task: ls project:foo limit:5]]
</pre>

(this executes system command "task ls project:foo limit:5")

b) present a description, and on hitting enter, a block of text is inserted (like above)

<pre>
[[task: ls project:foo limit:5|The top 5 Foo Project tasks]]
</pre>

or c) un-like above, launching the vim-taskwarrior plugin command :TW, with the query
(https://github.com/farseer90718/vim-taskwarrior)
instead of inserting text.

<pre>
[[:TW list project:foo limit:5|The top 5 Foo Project tasks]]
</pre>

does anything like this exist? should it? got any suggestions?
(this is related to #16 and #18)

**Comment by matt-snider** [comment]
Hi, I came across this because I use vimwiki and was looking for a similar feature. This sounds to me like [orgmode's babel](https://orgmode.org/worg/org-contrib/babel/intro.html). Is there anyway to get this functionality in vim/vimwiki? Would something like this fit into vimwiki's vision?

**Comment by ranebrown** [comment]
Using a custom VimwikiLinkHandler is the best option for this functionality.
