### ISSUE TITLE
VimwikiGenerateTags ignores file hierarchy

### ISSUE THREAD

**Issue by lecagot** [vimwiki/vimwiki#190]
##### Versions
* vim 7.4
* vimwiki v2.2.1

##### Bug description
Generating a list of links to files with tags does not set links correctly according to the file hierarchy (sub-/parent -folders etc.), but only uses the actual filename.

##### Steps to reproduce
1. tag a file `./file.mkd` with `:tag1:`
2. tag a file `./subfolder/file2.mkd` with `:tag1:tag2:`
3. rebuild tags with `:VimwikiRebuildTags`
4. create list of files with tags in `./tags.mkd` with `:VimwikiGenerateTags`

##### Actual behaviour
`./tags.mkd`:
```wiki
# Generated Tags

## tag1

    - [[file]]
    - [[file2]]

## tag2

    - [[file2]]
```

##### Expected behaviour
`./tags.mkd`:
```wiki
# Generated Tags

## tag1

    - [[file]]
    - [[subfolder/file2]]

## tag2

    - [[subfolder/file2]]
```

**Comment by EinfachToll** [comment]
@lecagot : this is already fixed. Check the dev branch. BTW, thumbs up for your detailed bug report!

**Comment by lecagot** [comment]
Ah, OK. I switched to the `dev` branch and got the same effect. However, it did not update old tags (as it only checks for files _younger_ than the tags file when rebuilding, I suspect). Removing `.tags` solved the issue, thanks.
