### ISSUE TITLE
Superscript breaking multiline LaTeX code

### ISSUE THREAD

**Issue by GravityScore** [vimwiki/vimwiki#193]
I'm using MathJax to render LaTeX code from my wiki, which has support for multiline, centred equations in the format:

```
$$
y = x^2
$$
```

The problem is that Vimwiki doesn't recognise these as math blocks, and so if I have a line with two exponents in it (^ characters), it treats it as superscript and distorts the outputted HTML with `<sup>` tags, preventing MathJax from rendering the LaTeX. This is really annoying me. Example:

```
$$
|a + bi| = \sqrt{a^2 + b^2}
$$
```

Is there anyway to fix this? Can I turn superscript off somehow? Currently the only course of action I can see is forking the repository and turning off superscript in the code manually. Will there be future support for multiline math code?

A similar thing doesn't seem to happen for italics text oddly.

**Comment by EinfachToll** [comment]
Why don't you write your math like this?
```
{{$
y = x^2
}}$
```
This syntax is already supported by Vimwiki.

**Comment by GravityScore** [comment]
Oh cool I had no idea about that syntax. Looks like I completely missed it when looking at the documentation. Sorry for the unnecessary issue.

**Comment by vishalrao009** [comment]
Hi but inline math is also not working, using $ math $ or /( math /) is also not working while using superscripts. And it is supported by vimwiki as per described in documentation of vimwiki.
