### ISSUE TITLE
Can't update via Vundle

### ISSUE THREAD

**Issue by Harsh-Vardhan** [vimwiki/vimwiki#195]
When I try to update via Vundle using `:PluginUpdate` command I get the attached response in the logs.

![screenshot from 2016-03-04 19 32 42](https://cloud.githubusercontent.com/assets/381681/13529159/9cb07556-e240-11e5-8fa6-331807f98a1e.png)

I don't understand what I have to do here.
Any help is appreciated.

**Comment by EinfachToll** [comment]
This is not related to Vimwiki nor to Vundle. Looks like you made manual changes to the file autoload/vimwiki/custowiki2html.sh, so git (which is apparently invoked by Vundle) refuses to overwrite it. If you don't want to keep your changes to this file, you can probably just delete Vimwiki and install it again.

**Comment by Harsh-Vardhan** [comment]
Thank you. I did as you said. It works now.
