### ISSUE TITLE
return in insert mode broken with E116 error message

### ISSUE THREAD

**Issue by lecagot** [vimwiki/vimwiki#196]
#### Versions
* vim 7.4.1584-1
* vimwiki `722d6e4` (`dev`)

#### Bug description
**(I think this bug occured after a recent vim update, so I'm not sure if this is a problem of vim itself or vimwiki)**

(Carriage) `return` in `insert` mode does not work and gives the following error message:

```vim
E116: Invalid arguments for function <SNR>74_CR
```

This **only** happens while `ft=vimwiki`.

**Comment by EinfachToll** [comment]
I updated my Vim some days ago (to 7.4.16XX something) and everything works, so I suggest that you try a newer version of Vim as well.

**Comment by lecagot** [comment]
yes, it's fixed with `7.4.1639` on Arch Linux now again.
