### ISSUE TITLE
E172: Only one file name allowed

### ISSUE THREAD

**Issue by protist** [vimwiki/vimwiki#198]
I have my wiki organised in subdirectories. When I open files in one particular subdirectory, I get the following error.
```
"foo.wiki" 15L, 700C
Error detected while processing function vimwiki#base#get_links:
line   68:
E172: Only one file name allowed: lcd! /path/to/vimwiki/bar
E172: Only one file name allowed: lcd! /path/to/vimwiki/bar
Press ENTER or type command to continue
```

This even persists in further nesting of the subdirectories. (Note the slightly different error message in the fifth line.)
```
"baz/qux.wiki" 62L, 1235C
Error detected while processing function vimwiki#base#get_links:
line   68:
E172: Only one file name allowed: lcd! /path/to/vimwiki/bar
E172: Only one file name allowed: lcd! /path/to/vimwiki/bar/baz
Press ENTER or type command to continue
```
Happy to troubleshoot further but not sure where to start. Other subdirectories are fine.

**Comment by EinfachToll** [comment]
What version of Vimwiki are you using? In the recent version, there is no function `vimwiki#base#get_links`. Also, can you specify what kinds of directory names work and which don't? I suppose it's directory names containing spaces which don't work.

**Comment by protist** [comment]
Oh, sorry, I was relying on the fact that Arch Linux's AUR package was up to date. It was actually shipping 2.1. Sorry for the noise; the newest release (2.2.1) works fine. (I didn't check conclusively, but the one directory that failed indeed contained a space.) Apologies again.
