### ISSUE TITLE
Paragraphs with multiple lines are not exported to HTML correctly 

### ISSUE THREAD

**Issue by vicmunoz** [vimwiki/vimwiki#199]
Paragraphs with multiple lines are not exported to HTML correctly. All lines are concatenated together.

Below wiki text:

```

This is first paragraph
with two lines.

This is a second paragraph with
two lines

```

Is exported to HTML like:

```

This is first paragraph with two lines.

This is a second paragraph with two lines. 

```

**Comment by EinfachToll** [comment]
This is intended. Most markdown implementation do it like this, for example. But I agree that we could make that behavior optional. Vimwiki has currently the option `g:vimwiki_list_ignore_newline`, which works only in list items.

**Comment by tinmarino** [comment]
Closing <= I definitely think that this is better: up to you to make newlines wherever you want and if you want a newline to be displayed, just add a blank line.
Other behaviour is luxury (i.e. not required)
