### ISSUE TITLE
Close current page on :VimwikiFollowLink.

### ISSUE THREAD

**Issue by korjavin** [vimwiki/vimwiki#20]
How to map ENTER for closing current buffer and opening link ?

**Comment by i-interprete-on-the-fly** [comment]
Is there any update on this?

**Comment by ranebrown** [comment]
@i-interprete-on-the-fly Pretty sure this still doesn't work but it seems like more of a feature request to me. If you are willing to figure out how to get a `VimwikiLinkHandler` working or open a pull request yourself that would be great. Otherwise this is probably pretty low priority right now.

**Comment by ranebrown** [comment]
I got a chance to take a look at this and I think it can be handled with `VimwikiLinkHandler` using something like this:
```vim
  function! VimwikiLinkHandler(link)
    let buf = bufnr('%')
    let link_infos = vimwiki#base#resolve_link(a:link)
    if link_infos.filename == ''
      echomsg 'Vimwiki Error: Unable to resolve link!'
      return 0
    else
      exe 'edit ' . fnameescape(link_infos.filename)
      exe 'bd' . buf
      return 1
    endif
  endfunction
```

It should be easy enough to exclude the index page if desired as well.
