### ISSUE TITLE
Automatic Smart Quotes (and other typographical features) à la SmartyPants

### ISSUE THREAD

**Issue by HarrisonB** [vimwiki/vimwiki#205]

**Comment by ranebrown** [comment]
I'm assuming this is related to the html output e.g. turning `(tm)` into `&trade;` which results in ™.
I found [this link](http://misaka.61924.nl/#misaka.smartypants) with some more examples.
This would be a nice feature to add, PRs are welcome.

**Comment by tinmarino** [comment]
**Closing**: even if it is a good idea and if anyone want to add a PR with some macro like that, no problem.
