### ISSUE TITLE
<CR> no longer follows links after updating vimwiki

### ISSUE THREAD

**Issue by daveyarwood** [vimwiki/vimwiki#206]
For some reason, pressing Enter while the cursor is on a link will no longer follow a link in Vimwiki buffers. Instead, my default (global) behavior of `<CR>` occurs.

I took a brief glance through the source code, but wasn't able to figure out the cause. Any ideas on why this might be happening?

**Comment by alesandar** [comment]
Same here. Tested with a clean Neovim setup (removed everything except vimwiki from my config).

**Comment by EinfachToll** [comment]
Can you be a little more specific which version worked and which version not?

**Comment by daveyarwood** [comment]
Unfortunately, I don't have a record of what commit I was on before, but now I am on this commit:

```f567009 2016-04-25 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #201 from irfansharif/patch-1```

**Comment by daveyarwood** [comment]
I noticed that I only see this bug when I open a vimwiki buffer on vim startup, i.e. `vim ~/Dropbox/vimwiki/index.wiki`. If I do that, `<CR>` doesn't work.

If, however, I open any other kind of buffer with vim (or if I just start vim by running `vim`) and *then* open a vimwiki buffer (e.g. by running `:VimwikiIndex` inside vim), `<CR>` works as it should.

@alesandar Is it the same for you?

**Comment by tarr11** [comment]
This occurs for me as well.  I am using the latest Janus distribution.

**Comment by daveyarwood** [comment]
I just updated and it's fixed for me.

**Comment by Nudin** [comment]
Probably fixed? If not please feel free to reopen.

**Comment by daveyarwood** [comment]
I can confirm it's still fixed for me.
