### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by pathologicalhandwaving** [vimwiki/vimwiki#207]
It would be great if there was a way to use footnotes. If there is a way to do this let me know but I can't seem to find it in the documentation anywhere.

**Comment by karlh626** [comment]
in the vimwiki doc it shows the following:
  super^script^
  sub,,script,,
maybe that could be substituted instead of footnotes?

**Comment by tinmarino** [comment]
Closing <= inactive + unclear + duplicated
