### ISSUE TITLE
Comments in code snippets activate folding for Markdown syntax

### ISSUE THREAD

**Issue by lervag** [vimwiki/vimwiki#212]
Example:

`````` md
# Test

Here be code snippet:

```sh
#!/bin/sh

ls
```end

# Next section

More text.
``````

Note, the "end" after the closing snippet marker is added just to make the example printable. Here the `#` in `#!/bin/sh` opens a fold. I propose one of two solutions:
1. Only fold when there is a space after opening `#`s, i.e. don't treat `#test` as a section title.
2. Add a check for being inside a code snippet. The simplest thing would be to ensure that all code snippets have a particular syntax group, and then check for this group. It should be relatively simple, I think.

**Comment by mrjovanovic** [comment]
This is very frustrating, and also happens with the default vimwiki syntax. For example
```
{{{sh
=== some text ===
ls -lah
}}}
```
adds a fold at `=== some text ==`

The bug also makes it impossible to fold code snippets when using markdown, as they are folded to the next comment string. 

I think option 2. suggested by @lervag makes sense - folding shouldn't happen within code snippets, or should rather use the syntax of the defined syntax group within the code snippet block.

**Comment by lervag** [comment]
I've solved this in my own ["fork" of vimwiki](https://github.com/lervag/wiki.vim). This is based on how I suggested it here, and it works well.

**Comment by mrjovanovic** [comment]
Thank you so much! Any plans on submitting a PR to vim-wiki proper, or is the code substantively different?

**Comment by lervag** [comment]
No, sorry. I've rewritten most/everything from scratch, so that is not so easy. But if anyone is interested they can probably find something useful there as inspiration for building a PR.

**Comment by ranebrown** [comment]
Commit a17a9826bdebb4d12fdeeccda3d9b10dfdbab9f7 can probably be used to fix this.

**Comment by ranebrown** [comment]
Should be fixed now.
