### ISSUE TITLE
Bullets and todo items are misaligned in HTML

### ISSUE THREAD

**Issue by pocc** [vimwiki/vimwiki#214]
When you write 

```
== Heading 2 ==
* Bullet
* [ x] Done item
```

the bullets are not aligned when exported to HTML

**Comment by EinfachToll** [comment]
Hm, I tried Firefox and Ephiphany and everything looks fine. Which browser are you using? Can you make a screenshot?

**Comment by pocc** [comment]
My apologies for not providing more information and not following up on this. Closing.
