### ISSUE TITLE
auto_toc with non-standard file extension

### ISSUE THREAD

**Issue by fab4100** [vimwiki/vimwiki#215]
I have noticed that if I set 'syntax' to "markdown" and 'ext' to ".md", the auto_toc option does not work.  However, if I set 'ext' to default, auto_toc works.  It seems that there is a dependence on 'ext' when auto_toc is used, which is not resolved properly?

Thanks
Fab

**Comment by ranebrown** [comment]
Please reopen if you are still seeing this behavior. From my testing it has been fixed.
