### ISSUE TITLE
Conversion to HTML not supported (using Markdown and .txt)

### ISSUE THREAD

**Issue by vcavallo** [vimwiki/vimwiki#217]
I'm getting this error:

`Vimwiki Error: Conversion to HTML is not supported for this syntax`

### here is the current contents of my wiki directory:

```
[ my bash prompt... ] ~/Dropbox/wiki
 $ ls
index.txt               testing_page.txt

[ my bash prompt... ] ~/Dropbox/wiki
 $ cat *
# test

[testing_page](testing_page)
this is a test page *yippie*
```

### my `.vimrc` configs:

```
" vimwiki
let wiki_1 = {}
let wiki_1.path = '~/Dropbox/wiki/'
let wiki_1.syntax = 'markdown'
let wiki_1.ext = '.txt'
let g:vimwiki_list = [wiki_1]
 ```

when running `:Vimwiki2HTML` i get the error mentioned above.

Everything else seems to work just fine.

**Comment by vcavallo** [comment]
.......and I just noticed this line in the help file:

>Wiki syntax.  You can use different markup languages (currently: Vimwiki's
default, Markdown, and MediaWiki), but only Vimwiki's default markup will be
converted to HTML at the moment.

so... disregard i guess :)

**Comment by matcharles** [comment]
Any idea if support has been added for .md files since then?

**Comment by ranebrown** [comment]
It isn't officially supported yet but is something I plan to work on. For now take a look at autoload/vimwiki/customwiki2html.sh or WnP/vimwiki_markdown

**Comment by matcharles** [comment]
Thanks for this. I'm not in a hurry and will wait until it's being pushed in the main repo. Appreciate your work!
