### ISSUE TITLE
Error message occurs whenever starts

### ISSUE THREAD

**Issue by Zooc** [vimwiki/vimwiki#222]
Eventhought i switch to dev branch, it still happens. 

"~/vimwiki/index.wiki" 1L, 23C
Error detected while processing /home/kenny/.vim/bundle/vimwiki/autoload/vimwiki/u.vim:
line   47:
E122: Function vimwiki#u#reload_regexes already exists, add ! to replace it
line   52:
E122: Function vimwiki#u#reload_omni_regexes already exists, add ! to replace it
line   57:
E122: Function vimwiki#u#reload_regexes_custom already exists, add ! to replace it
line   63:
E122: Function vimwiki#u#sw already exists, add ! to replace it
Error detected while processing /home/kenny/.vim/syntax/vimwiki.vim:
line   18:
E117: Unknown function: vimwiki#u#time
E15: Invalid expression: vimwiki#u#time(starttime)  "XXX
Error detected while processing /home/kenny/.vim/bundle/vimwiki/autoload/vimwiki/u.vim:
line   47:
E122: Function vimwiki#u#reload_regexes already exists, add ! to replace it
line   52:
E122: Function vimwiki#u#reload_omni_regexes already exists, add ! to replace it
line   57:
E122: Function vimwiki#u#reload_regexes_custom already exists, add ! to replace it
line   63:
E122: Function vimwiki#u#sw already exists, add ! to replace it
Error detected while processing /home/kenny/.vim/syntax/vimwiki.vim:
line   50:
E117: Unknown function: vimwiki#u#time
E15: Invalid expression: vimwiki#u#time(starttime)  "XXX
Error detected while processing /home/kenny/.vim/bundle/vimwiki/autoload/vimwiki/u.vim:
line   47:
E122: Function vimwiki#u#reload_regexes already exists, add ! to replace it
line   52:
E122: Function vimwiki#u#reload_omni_regexes already exists, add ! to replace it
line   57:
E122: Function vimwiki#u#reload_regexes_custom already exists, add ! to replace it
line   63:
E122: Function vimwiki#u#sw already exists, add ! to replace it
Error detected while processing /home/kenny/.vim/syntax/vimwiki.vim:
line  244:
E117: Unknown function: vimwiki#u#time
E15: Invalid expression: vimwiki#u#time(starttime)  "XXX
Error detected while processing function <SNR>34_add_target_syntax_ON:
line    1:
E121: Undefined variable: g:vimwiki_debug
E15: Invalid expression: g:vimwiki_debug > 1
E121: Undefined variable: g:vimwiki_debug
E15: Invalid expression: g:vimwiki_debug > 1
E121: Undefined variable: g:vimwiki_debug
E15: Invalid expression: g:vimwiki_debug > 1
E121: Undefined variable: g:vimwiki_debug
E15: Invalid expression: g:vimwiki_debug > 1
E121: Undefined variable: g:vimwiki_debug
E15: Invalid expression: g:vimwiki_debug > 1
Error detected while processing /home/kenny/.vim/syntax/vimwiki.vim:
line  329:
E121: Undefined variable: g:vimwiki_debug
E15: Invalid expression: g:vimwiki_debug > 1
Error detected while processing /home/kenny/.vim/bundle/vimwiki/autoload/vimwiki/u.vim:
line   47:
E122: Function vimwiki#u#reload_regexes already exists, add ! to replace it

**Comment by EinfachToll** [comment]
Looks like something went wrong with updating. Check your installation of Vimwiki and try uninstalling and reinstalling. Depends on your plugin manager, if any.

**Comment by Zooc** [comment]
@EinfachToll Thanks, it was caused by pathogen. After I used vundle to install it Vimwiki again, it works fine.
