### ISSUE TITLE
Enhancement: Add a fraction of completed child items on the parent item?

### ISSUE THREAD

**Issue by zachfedor** [vimwiki/vimwiki#224]
I'm in the middle of adding a feature and thought I would check its value before I got too deep. The proposed plan would be to add the following features:
- function to calculate a parent item's completed items / total items
- command to add/remove this fraction to parent with mapping
- update a parent's fraction on children's state change

```
# proposed feature in the wild:
- [.] parent item [1/3]
  - [x] completed child
  - [ ] uncompleted child
  - [o] partial parent/child [1/2]
    - [ ] grandchild
    - [x] grandchild
```

This is a feature in Org-Mode and I thought it would be nice to have here. I know we have percent-based state on checkboxes (`.o0X` or whatever the default is), but this adds another way to visualize that. It's very handy number specific TODOs (e.g. "Go the gym 3 times this week", "Get 4 articles on xyz topic", etc.). This feature wouldn't be too intrusive since it's hidden by default. It requires a command to change anything so no one's workflow will be disrupted. I guess I could even add a global option to turn it on and off.

So what does everyone think? Is it worthwhile?

**Comment by zachfedor** [comment]
For reference, [here is the org-mode doc on checkboxes](http://orgmode.org/manual/Checkboxes.html). They call the fractions `cookies` and also allow for percentages. It just depends if you create them by appending `[/]` or `[%]`. Since we already have the rate of the item, this would be an easy addition if people wanted it.

**Comment by EinfachToll** [comment]
>  I thought it would be nice to have here
...
>  if people wanted it

Doesn't sound like you really want it, but you only add it because it *could* be cool ;)

Personally, I would not use it, because I want as few visual clutter as possible in my files. But if you really want it and everything works, I'm not opposed to including it.

**Comment by zachfedor** [comment]
No, I would definitely use it. I do it manually now, so automating it is even better. I just know that people use things like vimwiki for the reason you mentioned: the lack of visual clutter. I was trying to be respectful and wouldn't bother adding it if people thought that it would be too much.

I'll take a crack at it then! Thanks for the feedback.

**Comment by ranebrown** [comment]
Pretty sure this has been implemented and this issue was never closed. Please reopen if I'm missing something.
