### ISSUE TITLE
[count]<leader>w<leader>w opens new note in current diary regardless of count

### ISSUE THREAD

**Issue by thornecc** [vimwiki/vimwiki#228]
I have some wikis specified in g:vimwiki_list,
`let g:vimwiki_list = [ {'path': '~/vimwiki/Personal', 'auto_export': 1}, {'path': '~/vimwiki/Work', 'auto_export': 1}, etc ]`

When I type `2;w;w` in a new vim instance, the note will be created in `~/vimwiki/Personal/diary`, though when I press backspace I will be returned to the correct index file `~/vimwiki/Work/diary/diary.wiki`.

In addition, if I am already viewing a file in my Work wiki and I type `3;w;w` then the file will be created in '~/vimwiki/Work/diary/` though again pressing backspace takes me to the correct diary index file.

**Comment by malramsay64** [comment]
#366 should fix this problem if it is still bothering you.

**Comment by ranebrown** [comment]
Also see #543. Please reopen if you are still seeing problems.
