### ISSUE TITLE
Getting diary error when generating index on diary index

### ISSUE THREAD

**Issue by mblarsen** [vimwiki/vimwiki#230]
Getting the following error on the diary index page:

```
Vimwiki: You can generate diary links only in a diary index page! 
```

Keys:

```
<Leader>wi <Leader>w<Leader>i
```

Sometimes it will generate the index, but mostly I'll get the error.

**Comment by timcmartin** [comment]
I am seeing the same behaviour.

**Comment by timcmartin** [comment]
Update to my comment ^^.
In my case, I have my vimwiki in Dropbox.  My Dropbox directory has an uppercase 'D'.
The path to my vimwiki in my vimrc had the path entered with a lowercase 'D'. 
Changing the value in my vimrc to use an uppercase 'D' solved my problem.

**Comment by mblarsen** [comment]
Back to using vimwiki after a year. Worked fine for about a month. Now I get the issue again. The filename is not the issue.

**Comment by mblarsen** [comment]
Digging into the source it seems the problem is that current file has a full path to diary index while the settings uses `~`.

`/Users/me/vimwiki/diary/diary.md` vs `~/vimwiki/diary/diary.md` 

I have this in my config:

```
let g:vimwiki_list = [{'path': '~/vimwiki/',
      \ 'syntax': 'markdown', 'ext': '.md'}]
```

So changing path to `/Users/me/vimwiki` resolves it.

Although this resolves the issue in my case I'd suggest that the paths being resolved before `is_equal` is called to avoid this false negative.

**Comment by tinmarino** [comment]
Should be fixed now. Reopen otherwise.
