### ISSUE TITLE
VimwikiGenerateTags format: remove indentation and input correct link format for markdown syntax

### ISSUE THREAD

**Issue by lecagot** [vimwiki/vimwiki#231]
#### versions
- vim 7.4
- vimwiki v2.3 `483138`
#### relevant `vimrc` settings

``` vim
let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': '.mkd'}]
```
#### problem description

Currently the output of `:VimwikiGenerateTags` looks like that:

``` markdown
# Generated Tags

## a

    - [[a1]]
    - [[a2]]

```

Besides that vimwiki currently ignores the syntax setting and inputs the links as vimwiki style links [0] the list is indented which causes it  to be displayed as a code block on GitHub. The preferred output format would be:

``` markdown
# Generated Tags

## a

- [[a1]]
- [[a2]]

```

and ideally, if `markdown` is set as the syntax:

``` markdown
# Generated Tags

## a

- [a1](a1.mkd)
- [a2](a2.mkd)

```

[0] There's another issue with the current auto-generated links by pressing `Enter`, as the links are generated in the format `[link](link)`, but not in the format `[link](link.mkd)` which would also be supported i.e. with GitHub. I should file a seperate issue for that.

**Comment by lecagot** [comment]
> [0] There's another issue with the current auto-generated links by pressing Enter, as the links are generated in the format `[link](link)`, but not in the format `[link](link.mkd)` which would also be supported i.e. with GitHub. I should file a seperate issue for that.

I opened a separate issue #233 for that feature request.

**Comment by ranebrown** [comment]
See #529, #634, #635
