### ISSUE TITLE
I only have one color in the vim terminal, and no color when add a space in front of a header

### ISSUE THREAD

**Issue by digdig** [vimwiki/vimwiki#232]
I am using a terminal, it is colorful when I open an source code for example `.c` or `.py`. However, when I enter the `vimwik` and edit the `.wiki` files, only a single color pink occurs. Not like the screen shot in this repo that there are different colors for different headers and bullets. All of them are pink color.

A second issue is that when I add a space in front of the a header(in order to make it center), the highlight for that header disappear.

![2016-08-18-060348_422x466_scrot](https://cloud.githubusercontent.com/assets/5459093/17754938/a458a020-6509-11e6-9cfb-d1c22e735b5d.png)

Note that the small dots and vertical dots are not manually add, it is the indentLine package.

**Comment by EinfachToll** [comment]
The headers are highlighted, bold text and links as well, so I think there is nothing wrong with the highlight from Vimwiki's side. If you don't like the colors, well, just use another color scheme.

Regarding the lost highlight with the space in front of the header: I see that the bullet points are not highlighted as well, when there are spaces in front of it. I would guess that the indentLine addon you use is responsible. Can you try and disable it?

**Comment by johnmarcampbell** [comment]
I'm closing this, as some advice was given but original poster never responded.

**Comment by jrd-oje** [comment]
For all of you who landed here because you want to give the vimwiki headers different colors, according to your terminal color scheme, and perpetuate it in your neovim lua configuration: This works very well:
```
vim.cmd('highlight vimwikiHeader1 ctermfg=1')
vim.cmd('highlight vimwikiHeader2 ctermfg=2')
vim.cmd('highlight vimwikiHeader3 ctermfg=3')
```
