### ISSUE TITLE
change format of wiki links with markdown syntax from [link](link) to [link](link.mkd)

### ISSUE THREAD

**Issue by lecagot** [vimwiki/vimwiki#233]
If the syntax is set to `markdown` vimwiki currently generates a link with the following format when the cursor is over a word and `<CR>` is pressed (format 1):

``` markdown
[link](link)
```

Though this format works to follow links in vimwiki (obviously!), the following format works as well (`mkd` is set as the file extension in `vimrc`) (format 2):

``` markdown
[link](link.mkd)
```

The latter format has the benefit that the link works as well i.e. with gitit and on GitHub.

Is there a specific reason for the first syntax? If not it might be good to change the syntax to the latter one, as this increases the compatibility of vimwiki to other markdown using systems (gitit, GitHub, ...).

If there is a specific reason, would it be possible to implement a variable to set whether the file extension should be added in links?
#### background

I am using vimwiki extensively, and have it backed up in a git repository. Additionally I use GitHub to access my vimwiki via browser also from computers on which I don't have access to the raw git repository. The markdown rendering works nicely, but it would be awesome if I would not have to manually add the file extension to links in order to follow them on GitHub.

Although I started to dig into the source of vimwiki, so far I am unable to understand its structure and implement this feature myself.

**Comment by smitec** [comment]
I would also find this useful, I use vimiwiki personally and at work for this same purpose (github hosted knowledge base). Being also to configure an extension (`.md`, `.mkd` etc)  to be added to new links would be helpful.

**Comment by MatthiasKauer** [comment]
I'd like to add that appending the extension automatically prevents
links like `[my cpp header](foo/bar.h)` from working.
At least in my setup, vimwiki will try to open "foo/bar.h.md" instead.

**Comment by ranebrown** [comment]
See #529
