### ISSUE TITLE
Is it possible to automatically generate the links of a bunch of files?

### ISSUE THREAD

**Issue by digdig** [vimwiki/vimwiki#234]
Suppose I have a bunch of files under my `vimwiki` folder. Can I automatically generate links to all these files? 

That is, can I generate one link per file automatically? Just as what we do with `diary`. However, these `.wiki` files are not named according to the date...

**Comment by EinfachToll** [comment]
Does `:VimwikiGenerateLinks` what you want?

**Comment by digdig** [comment]
@EinfachToll  Yeah, this works.
