### ISSUE TITLE
Enhancement: "Won't-do" state for checkbox list items

### ISSUE THREAD

**Issue by davidlmontgomery** [vimwiki/vimwiki#239]
In addition to done and not-done, I like to have a checkbox status for "won't do" (which might also be considered as "indefinitely deferred (but not forgotten)".

Often as I work through a to-do list I decide that I will not do a particular item that I had previously added. Before I started using vimwiki, I used "[ ]" for open items, "[x]" for completed items, and "[-]" for these "won't do" items, and I've missed having this functionality in vimwiki.

Won't-do items are different from done items because they have not been completed, so "[X]" is not appropriate. Reviewing a list later one would see such an item and think it was done (or, more likely, not even notice the item as it does not stand out from other items).

Won't-do items are different from open items because they have been consciously considered, and determined as something that will not be done at least for the time being. So "[ ]" is not appropriate. While working the list, list items with "[ ]" will be repeatedly reviewed, which we don't want for won't-do items. Thus we want to mark such items so that when reviewing the work to be done we no longer scan these items.

Won't do items are different from deleted items (e.g., by deleting the line) because they document that some task has been considered and determined to be unnecessary (or at least deferred for current purposes). 

Below are two patches that I added to my local vimwiki to begin adding support for "won't-do" items. 

```
--- lst.vim 2016-08-28 11:39:39.095041130 -0700
+++ lst.vim 2016-08-28 11:07:20.035108267 -0700
@@ -693,6 +693,9 @@
     return -1
   endif
   let state = a:item.cb
+  if state == g:vimwiki_wont_do_cb
+    return 100
+  endif
   return index(g:vimwiki_listsyms_list, state) * 25
 endfunction "}}}

@@ -1500,6 +1503,9 @@

   "the user can set the listsyms as string, but vimwiki needs a list
   let g:vimwiki_listsyms_list = split(g:vimwiki_listsyms, '\zs')
+
+  "add checkbox value for "won't-do" items
+  let g:vimwiki_wont_do_cb = '-'
 endfunction "}}}

 function! vimwiki#lst#TO_list_item(inner, visual) "{{{

```

```
--- vimwiki_markdown.vim    2016-08-28 11:36:14.063048229 -0700
+++ vimwiki_markdown.vim    2016-08-28 11:03:47.331115631 -0700
@@ -76,7 +76,7 @@
 call vimwiki#lst#setup_marker_infos()

 let g:vimwiki_rxListItemWithoutCB = '^\s*\%(\('.g:vimwiki_rxListBullet.'\)\|\('.g:vimwiki_rxListNumber.'\)\)\s'
-let g:vimwiki_rxListItem = g:vimwiki_rxListItemWithoutCB . '\+\%(\[\(['.g:vimwiki_listsyms.']\)\]\s\)\?'
+let g:vimwiki_rxListItem = g:vimwiki_rxListItemWithoutCB . '\+\%(\[\(['.g:vimwiki_listsyms.g:vimwiki_wont_do_cb.']\)\]\s\)\?'
 let g:vimwiki_rxListItemAndChildren = '^\(\s*\)\%('.g:vimwiki_rxListBullet.'\|'.g:vimwiki_rxListNumber.'\)\s\+\['.g:vimwiki_listsyms_list[4].'\]\s.*\%(\n\%(\1\s.*\|^$\)\)*'

 " Preformatted text

```

I haven't yet tried to make all the logic work with state changes of parent and child items. My sense of how I would make this work, if I were adding it, is like this:
- When setting a child item to won't-do, it is generally treated by the parent as if it were being completed. The percent done should be recalculated and the appropriate listsym applied. An unimportant refinement would be that if this is the last child item (so now at 100%), and every child item has a won't-do state, then the parent item gets a won't-do state rather than a done state.
- When setting a parent item to won't do, I would imagine setting every open child item to also have won't do status.

**Comment by Nudin** [comment]
I'm interested in implementing this.

> When setting a child item to won't-do, it is generally treated by the parent as if it were being completed. The percent done should be recalculated and the appropriate listsym applied.

Wouldn't it make more sense to treat such an item as if it doesn't exist?
Example:
```
- [ ] top
 - [x] foo
 - [ ] bar
 - [-] baz
```
Should `top` have the state 2/3 or 1/2? I think 1/2 is more realistic, because you haven't spend (much) work into baz and adding stuff, you won't do, to your todo-list shouldn't get you nearer to you goal.

**Comment by EinfachToll** [comment]
@Nudin agreed

**Comment by davidlmontgomery** [comment]
@Nudin I agree, too.

**Comment by Nudin** [comment]
I finally had time to implement this, still needs minor work and documentation, then I will create a pull request.
Open question:

1. How should be name this? I'm currently with rejected, other options: declined, ignore, wontdo, …
2. What keybinding should we default the toggling to? I thought about <M-Space> but that works only with neovim and gvim. Also <M-Space> binds already to `VimwikiVSplitLink` (@EinfachToll I can't find where in the code this happens). <C-S-Space> doesn't work. Maybe glx?

**Comment by Nudin** [comment]
This is now implemented in the dev-branch. Please report if you find any issues.
