### ISSUE TITLE
Syntax for preformatted text without fold

### ISSUE THREAD

**Issue by mMontu** [vimwiki/vimwiki#241]
While the use of folding for large sections of preformatted  text is great, it is sometimes annoying when the preformatted text consists in two or three lines.

Is it possible to include some syntax to indicate preformatted text that do NOT fold? I'm mainly interested in applying nested syntax for a small number of lines without the drawback of multiple small/cumbersome folds on a given section.

It could be an alternative solution to #140.

**Comment by tinmarino** [comment]
If someone want to make a PR for this feature and it does not break anything, feel free. But it is not a dev priority.
