### ISSUE TITLE
Automatically Title New Wiki Pages

### ISSUE THREAD

**Issue by KTSCode** [vimwiki/vimwiki#245]
I think it would be awesome to automatically title each new page that is created from a wiki link. 

I just switched from xolox/vim-notes to vimwiki, and I really miss this feature, it helped a lot with locational awareness. Since switching to vimwiki, I've found myself manually titling every new page I create. 

It would be extra useful if the title was highlighted, and was used as the page title when converted to html.

**Comment by EinfachToll** [comment]
What do you mean by title? Obviously, the link name becomes the file name of the newly created page. What else do you want?

**Comment by bhrutledge** [comment]
I think the idea is that pressing Enter on `[[Title]]` would create `Title.wiki`, with the first line being `= Title =`. Similarly, it would be nice if `:VimwikiMakeDiaryNote` would add something like `= 2016-11-29 =` to new notes; it would be especially awesome if the format could be configurable.

On a related note, it would be cool if `:VimwikiGenerateLinks` used the first header text as the link description, similar to `:VimwikiDiaryGenerateLinks`.

**Comment by bhrutledge** [comment]
I'm guessing this could be accomplished independently of vimwiki, using [`:autocmd`](http://stackoverflow.com/questions/162617/how-can-i-automatically-add-some-skeleton-code-when-creating-a-new-file-with-vim) or something like [vim-skeleton](https://github.com/noahfrederick/vim-skeleton).

**Comment by aq2** [comment]
old thread, i know, but a very simple two liner solution is
```
autocmd BufNewFile *.wiki :r! echo = %:t:r =
autocmd BufNewFile *.wiki :norm kddo
```
i am no vim scripter, so i am sure there are much better ways of doing this, but the first line automatically inserts the title (wrapped with '=') into the document, but for some reason inserts a new line before it. So the second autocommand deletes it - again i am sure there are better ways - all comments and suggestions welcome!

**Comment by ranebrown** [comment]
@KTSCode @bhrutledge @aq2 I would appreciate it if any of you could test the implementation in PR #661 and post any results here or in the PR. Thanks!

**Comment by aq2** [comment]
well that was simple!

seems to work fine here - i made a comment on the PR

**Comment by aq2** [comment]
[diary-ex](https://user-images.githubusercontent.com/13156649/56463407-a50b4180-63cb-11e9-9782-7931c313ba95.png)
