### ISSUE TITLE
configuration and markdown links

### ISSUE THREAD

**Issue by xrasto** [vimwiki/vimwiki#246]
I open root file SUMMARY.md  (from a playbook). It contains links of this form:
"[Rails](rails.md)"
I put cursor on this link and press enter. 
Expected outcome : visit the file "rails.md"
Actual outcome      : the file rails.md.md is created (and visited) 

How do I configure vimwiki to enable links with extension.
Or is it possible to have both pon-extension and extension links?
Best regards
/Torgny

**Comment by lecagot** [comment]
for me both formats work:

```
[link](link.mkd)
[link](link)
```

vimwiki revision: `483138`

**Comment by EinfachToll** [comment]
Actually, this should work, as lecagot pointed out. Can you post your Vimwiki related settings from your .vimrc?

**Comment by ranebrown** [comment]
See #529
