### ISSUE TITLE
Auto export too more times for single file

### ISSUE THREAD

**Issue by icersong** [vimwiki/vimwiki#248]
while swich the same buf more then one times, then wite file, it will export more then one times, the times is the switch times to this buf 

eg: switch four times to buffer index.html, then write file, ...

"index.md" 163L, 3128C written
Converted file to: /Users/apple/.vim/wiki/static/technology/index.html^@
Converted file to: /Users/apple/.vim/wiki/static/technology/index.html^@
Converted file to: /Users/apple/.vim/wiki/static/technology/index.html^@
Converted file to: /Users/apple/.vim/wiki/static/technology/index.html^@

**Comment by EinfachToll** [comment]
I'm afraid I don't understand. What do you mean by “switch“?

**Comment by johnmarcampbell** [comment]
Closing this, due to extended time passing without requested info being provided.
