### ISSUE TITLE
.vimrc gets recognized as vimwiki filetype

### ISSUE THREAD

**Issue by BonarBeavis** [vimwiki/vimwiki#249]
Hi,

.vimrc gets recognized as vimwiki filetype

Cheers

**Comment by hpincket** [comment]
This is not the case on my box. So I suppose more information would be helpful.
1. What is the result of ```:set ft?``` in your .vimrc buffer?
2. What version of Vim are you using?
3. I don't know how to tell your vimwiki version, but that would seem useful too.
(I'm no vim expert, so I can't help beyond the superficial.)

**Comment by BonarBeavis** [comment]
My bad, I was inside my vimwiki filetype function and it got shown in my statusbar...
