### ISSUE TITLE
VimwikiBacklinks seems doesn't work properly

### ISSUE THREAD

**Issue by yuex** [vimwiki/vimwiki#25]
`:VimwikiBacklinks` uses simple regex expression to `lvimgrep` all words matching current file's name with extension striped. Shouldn't it match just words in a link format rather than just plain word?

Further more, when directories taken into consideration, this kind of regex matching causes more trouble. Because `[[ dir/ ]]` doesn't point to same vimwiki file, for examle, in `foo/index.md`, it points to `foo/dir/index.md`, while in `bar/index.md`, it points to `bar/dir/index.md`. And in this scenario, `:VimwikiBackLinks` in `foo/index.md` also matches `foo/dir/index.md` and `bar/index.md`

We can completely resolve this problem by simply using the full path to the vimwiki file with a description when normalizing a link. Then the link will be much easier to be precisely matched with while not being presented as a eye-mess too

Do I missed something in the docs or is there already a work-around to get over this problem?

**Comment by ranebrown** [comment]
It looks to me like this has been resolved but the issue was never closed. There are still some issues on Windows with backlinks #413.
