### ISSUE TITLE
Allow setting default path_html for temporary wikis

### ISSUE THREAD

**Issue by protist** [vimwiki/vimwiki#250]
I have temporary wikis littered around my file system that contains notes on various projects. I store them in the project directory. I occasionally render these into html, but the html path seems to be autogenerated, with no way to specify my preferred path. I then have to manually delete the html directory every time. I don't want to keep the html output, so ideally, I'd create this html output in `/tmp`. It'd be great to be able to specify a generic location for html output from temporary wikis.

**Comment by EinfachToll** [comment]
That will be possible when #257 is resolved.

**Comment by protist** [comment]
In the meantime, creating a symlink is a workaround:
```
$ rm -r ~/vimwiki_html
$ ln -s /tmp ~/vimwiki_html
```

**Comment by tinmarino** [comment]
Closing <= follow up in #894 <= too many ticket to know where to start coding, tickets with `ref` tag are mutualising its
Thanks @protist
