### ISSUE TITLE
? shortens previous word in VimWiki

### ISSUE THREAD

**Issue by sdebnath** [vimwiki/vimwiki#252]
VimWiki renders this https://www.youtube.com/watch?v=JFh22atXTRQ
as https://www.youtube.com/~?v=JFh22atXTRQ

Is there a way to avoid this or have it show full URL for external links/urls?

**Comment by EinfachToll** [comment]
There is an option (see `:h g:vimwiki_url_maxsave`) which somewhat controls the concealing of urls. Does it do what you want?

**Comment by sdebnath** [comment]
That would do it - thank you.
