### ISSUE TITLE
Motions for vimwiki elements

### ISSUE THREAD

**Issue by mMontu** [vimwiki/vimwiki#253]
It would be useful to have motions regarding vimwiki elements (such as heading and list elements), similar to the custom text objects:
```
3.3. Text objects                                       *vimwiki-text-objects*

ah                      A section segment (the area between two consecutive
                        headings) including trailing empty lines.
ih                      A section segment without trailing empty lines.

You can type 'vah' to select a section segment with its contents or 'dah' to
delete it or 'yah' to yank it or 'cah' to change it.

a\                      A cell in a table.
i\                      An inner cell in a table.
ac                      A column in a table.
ic                      An inner column in a table.

al                      A list item plus its children.
il                      A single list item.
```

My understanding is that these text-objects allow easy *edition*, but not navigation. Is that correct?

One possible approach could be add `[h`, `[l`, etc, to mimic the default `[{` and `[(`.

**Comment by EinfachToll** [comment]
There is already a PR here: #23 which implements this. It's just that nobody of the participants (including me) polished the patch yet. But thanks for the reminder ;)

**Comment by mMontu** [comment]
I'm sorry, I did lots of searches but couldn't find that. Thanks!

As your memory seems to work a lot better than my searching skills, do you mind if I ask you about another functionality I've been missing?
Is it possible to indicate the end of heading? Sometimes I want to fold some content in the middle of a header content, but creating a level 2 header inside a top header conceals everything until the end of the level 1 header. I have been using preformatted text ({{{ and }}}) to do that, but it is sub-optimal as it loses the syntax highlight, unless I set the nested syntax, which has the downside of making the visualization very slow.

**Comment by EinfachToll** [comment]
So you have something like this:
```
= Top header =
some top content
== Subheader ==
sub content
more sub content

top content again
```
and you want to fold only the subheader plus the sub content but not the last line, right? Personally, I don't use folding at all, but I think you cant just visually select the subheader stuff and press zf to fold it, or you put an arbitrary marker string (e.g. `===`) at the end of the section and select everything up to this marker with `v/===`. Or maybe you can just indent all your content like python source code and fold according to the indent level.

**Comment by mMontu** [comment]
Indeed, I should have described with the exact example you provided :)

As far as I understand `zf` creates a manual fold, so it wouldn't show up in another machine or if I don't save it in a session. And using fold according to indentation could potentially affect text outside the sub content. I was wondering if anyone else was needed this in the context of vimwiki, automatically, but probably the answer is no.
