### ISSUE TITLE
Long multiline links are incorrectly wrapped

### ISSUE THREAD

**Issue by wuzwm** [vimwiki/vimwiki#254]
Vimwiki shortens links to certain length. Usually this works fine, as long as expanded link length does not extend the length of the line.
![bug1](https://cloud.githubusercontent.com/assets/7996873/20178657/7f1623ce-a752-11e6-85b7-8acb741b10eb.png)

As soon as this happens links that could very well fit in the single line (shortened) get incorrectly wrapped in the ugly way.

Example with two lines:
![bug2](https://cloud.githubusercontent.com/assets/7996873/20178659/7f3992c8-a752-11e6-8f0b-7d028d0902cd.png)

Example with more lines:
![bug3](https://cloud.githubusercontent.com/assets/7996873/20178658/7f34aa2e-a752-11e6-906a-d6e3765007ba.png)

I have the issue with clean .vimrc and only vimwiki plugin loaded.

**Comment by wuzwm** [comment]
Okay, I guess the issue can be closed as unsolvable. It seems to be an unfixable property of the "conceal" syntax argument.

https://github.com/vim/vim/issues/260

**Comment by louwers** [comment]
I don't think it's unsolvable, but implementing that would require a lot of work as Bram mentioned in the thread you linked to.
