### ISSUE TITLE
Move mapping for ENTER to ALT-ENTER?

### ISSUE THREAD

**Issue by philiprhoades** [vimwiki/vimwiki#255]
People,

I have started using VimWiki - which suits me in that it allows me to move my collection of *.txt files to their *.wiki equivalents but I _can't_ get used to using ENTER for going to another link (file) - I use ENTER _constantly_ for going to the beginning of the next line - is it possible to move the VimiWiki fn for ENTER to ALT-ENTER?

Thanks,
Phil.

**Comment by EinfachToll** [comment]
See `:h vimwiki_<CR>` for how to remap Enter. Putting `:nmap <A-CR> <Plug>VimwikiFollowLink` in your .vimrc would be the right way, but it depends on your terminal if you actually can use Alt+Enter as a key in Vim. At least for me, it doesn't work.

**Comment by philiprhoades** [comment]
No, doesn't work for me either:

Fedora 25 x86_64
xfce4-terminal v0.8.0

Any ideas about where to look to fix it?

Thanks!

**Comment by philiprhoades** [comment]
I am using <C-A> for the time being - I tried using logkeys to work out what was going on but didn't get anywhere . .

**Comment by EinfachToll** [comment]
Maybe it works in Neovim. AFAIK it was one of their goals to make alt keys work properly. Other than that, I know of no better solution than using a different key.

**Comment by christianrondeau** [comment]
I'm using `<CR>` as `<ESC>` by default, and vimwiki takes over. A simple setting to avoid remapping all `<CR>` mapping variations would solve everything. I'm ready to make a pull request, if you think it makes sense.  Something like `g:vimwiki_prevent_cr_remap = 1`

**Comment by christianrondeau** [comment]
To disable all cr mappings :

    nnoremap łwf <Plug>VimwikiFollowLink
    nnoremap łws <Plug>VimwikiSplitLink
    nnoremap łwv <Plug>VimwikiVSplitLink
    nnoremap łwv <Plug>VimwikiTabnewLink
    vnoremap łwn <Plug>VimwikiNormalizeLinkVisualCR
    inoremap łwn VimwikiReturn

**Comment by calsioro** [comment]
This might be related, should probably be a separate issue:
When giving a count to `i` `I` `a` or `A`, the inserted text repeats after pressing enter OR escape, but it repeats in the same line either way.

To reproduce:
- open a new vimwiki buffer, and in normal mode enter 10 and one of {`i`, `I`, `a`, `A`}, type "abc" press `<CR>`.

Result: `abcabcabcabcabcabcabcabcabcabc`

Counts with `o` or `O` don't work, they give an `E16: Invalid range` error.

**Comment by EinfachToll** [comment]
@calsioro Yes, it's a unrelated issue. Anyway, as far as my Vimscript knowledge goes, keeping all the normal Vim behaviour concerning counts and commands would be very complicated and is probably not worth the hassle. I would guess there are not many users who rely on this.

I only made a change which prevents the error message when pressing count+o or count+O.

**Comment by ranebrown** [comment]
The option `g:vimwiki_create_link` that was recently added might also help instead of remapping `<CR>`.

**Comment by hq6** [comment]
@ranebrown , I think this closure is fine since it doesn't look like there exists a good solution. However, FYI, the feature `g:vimwiki_create_link` is solving the different problem of *creating* links where one does not intend to. This Issue was about not mapping <Enter> to *follow* links by default.

**Comment by ranebrown** [comment]
Yeah, I was more pointing out a related option which affects `<CR>` that might be of interest. I didn't really make that clear or mention that the option is currently only available on the `dev` branch (until v2.5). Thanks!
