### ISSUE TITLE
Refactor handling of the internal state

### ISSUE THREAD

**Issue by EinfachToll** [vimwiki/vimwiki#256]
At the moment, user options, syntax definitions and other internal state is managed by a ton of global variables and fragile access functions. This needs to be systematized. We need to distinguish between

- state variables which are truly global (very few)
- state variables local to a wiki (because there can be multiple wikis open at the same time. At the moment, many spurious bugs occur because this is not handled well)
- state variables local to a syntax (for the ton of highlight regexes)
- buffer local variables
- window local variables (ATM, only prev_link)

**Comment by pjf** [comment]
Just hopping in to say I've been heavily using d5ed58f, with multiple wikis defined, in both markdown and native vimwiki syntax, for a few weeks now. It's been really solid, and except for #301 I haven't encountered any other issues with the branch. :)

**Comment by EinfachToll** [comment]
That's good to know! (Because writing integration tests for Vimwiki is rather ... meh.)

**Comment by Nudin** [comment]
Since this is merged since quite some time and no major issues have arose, I'm closing this. We can have new issues for other refactorings.
