### ISSUE TITLE
Unify global and wiki-local user options

### ISSUE THREAD

**Issue by EinfachToll** [vimwiki/vimwiki#257]
It makes sense for almost all options if the user could set them for a specific wiki only. Exceptions:

- map_prefix and the options regarding temporary wikis make only sense as global options
- path can be wiki-local only

All others can by made wiki-local, but `let g:vimwiki_Option = value` would set the value of the option `Option` for every wiki. That means this is backwards compatible.

**Comment by EinfachToll** [comment]
Depends on #256

**Comment by tinmarino** [comment]
Closed in favor of #894 (a reference issue)
