### ISSUE TITLE
"breadcrumb" style links

### ISSUE THREAD

**Issue by linuxcaffe** [vimwiki/vimwiki#26]
I suppose it would be possible to manually produce a wiki-link (or set of links) that looked like;

```
~/ vimwiki/ assets/ ledgers/ this.ledger.txt
```

where all 5 elements are "clickable", the first 4 to directories and the last one to the file, but it would be swell if this were easy to make!

**Comment by ranebrown** [comment]
If there is any interest in creating a function to support this please create a PR.
