### ISSUE TITLE
Could some iOS Apps browse the vim wikies in phone?

### ISSUE THREAD

**Issue by griffinqiu** [vimwiki/vimwiki#261]

**Comment by EinfachToll** [comment]
Um, well, is this a question (then the answer is probably yes. I can't tell, because I don't even have a smartphone, but I hope there are apps which let you look at plain text files) or a feature request?

**Comment by griffinqiu** [comment]
👍
It is a question. 
I am look for unified node for different platform. 
But the basic requirements is need support Vim as client and it be able to sync for every devices
I checked the Bear, Evernote and etc. The all could not edit the node with other editor. Unfortunately.

**Comment by kllmctrl** [comment]
Hi, u can try this
https://appsto.re/cn/B6c9gb.i

**Comment by johnmarcampbell** [comment]
Closing this, as a solution has been suggested and discussion has died down.
