### ISSUE TITLE
Prevent exit without saving

### ISSUE THREAD

**Issue by jeanCarloMachado** [vimwiki/vimwiki#263]
Its common for me to update a file and forget to save it, my default vim prevents me to exit without saving. Theres a way to do the same with the wiki?

**Comment by EinfachToll** [comment]
I don't really understand what you mean. You can't really close the wiki other than closing Vim entirely or by closing each wiki buffer individually. So, what do you want to happen on which event?

**Comment by jeanCarloMachado** [comment]
The problem I'm facing is:

- If I open vim
- Open the wiki
- Change the wiki without saving
- Quit

The wiki closes without warning me about the edited (and unsaved) buffer.
On other buffers - that arent part of the wiki - the edited buffers are always warned.

**Comment by EinfachToll** [comment]
Ah, OK. Vim has two settings `'autowrite'` and `'autowriteall'` which control whether or not Vim saves the buffers on exit. Vimwiki has a setting `g:vimwiki_autowriteall` which enables this behaviour only for wiki buffers. It is enabled by default. Just turn it of in your vimrc and wiki and non-wiki buffers should behave the same.

**Comment by jeanCarloMachado** [comment]
Ah ok, now I see, and it worked. Sorry for the trouble.
