### ISSUE TITLE
Use diary as weekly (instead of daily) (question)

### ISSUE THREAD

**Issue by markwmuller** [vimwiki/vimwiki#265]
Is it possible to have vimwiki-diary operate on weekly entries, rather than daily? I couldn't find it in the docs. I love the diary feature, just don't use it often enough to require daily entries.

**Comment by EinfachToll** [comment]
No, there is no such a feature at the moment.

**Comment by jgilchrist** [comment]
A :+1: from me for this, I currently have files I create every Monday, so daily is a little too frequent for me.

**Comment by teranex** [comment]
I'd also love to use a weekly, or even monthly, diary file.

**Comment by ranebrown** [comment]
PRs are welcome!

**Comment by tinmarino** [comment]
Fixed #884 
See: `:h vimwiki-option-diary_frequency`

**Comment by gravlaks** [comment]
I tried running `:h vimwiki-option-diary_frequency` in vim, and get the error message: 
E149: Sorry, no help for vimwiki-option-diary_frequency

**Comment by tinmarino** [comment]
@gravlaks use the `dev` branch, refrech your tags (`:h helptags`)

**Comment by gravlaks** [comment]
> @gravlaks use the `dev` branch, refrech your tags (`:h helptags`)

Thanks, worked well! Didn't understand what you meant by refreshing the tags, but now weekly option is set at least.
