### ISSUE TITLE
Issue installing with Vundle

### ISSUE THREAD

**Issue by davemabe** [vimwiki/vimwiki#271]
When I add this line to my vimrc:

`Plugin 'vimwiki/vimwiki'`

and then open vim and run:

`:PluginInstall`

It loads vimwiki just fine.  However, when I close vim and open it up again it appears that vimwiki is not being loaded properly as the standard ww command fails.  It's only when I run:

`':PluginUpdate'`

during the vim session does it load properly.  Is there something that needs to be done to have vimwiki work properly with Vundle?

**Comment by stevenwalton** [comment]
I don't think this will make a difference but I am using vim wili through vundle and do not have this problem. My full vundle section is:
```
filetype off 
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'vimwiki/vimwiki.git'
Plugin 'scrooloose/nerdtree.git'
Plugin 'vim-syntastic/syntastic.git'
Plugin 'Xuyuanp/nerdtree-git-plugin.git'
Plugin 'godlygeek/tabular.git'
Plugin 'vim-airline/vim-airline.git'
Plugin 'ryanoasis/vim-devicons.git'
Plugin 'powerline/powerline.git'

call vundle#end()
filetype plugin indent on
```
I don't think the `.git` at the end would change anything, but just trying to get you some response since it has been 6 days.

**Comment by davemabe** [comment]
Thanks for the suggestion.  It didn't help.  I also tried using Plug instead of Vundle and I get the same behavior.  Very strange.  I'm on Windows.  I think there's something in vimwiki that's causing this.

**Comment by Nudin** [comment]
Since the ticket is quite old and no second person reported this: Is this still an issue for you?

**Comment by ranebrown** [comment]
Please reopen if this is still a problem.
