### ISSUE TITLE
Allow g:vimwiki_listsyms be larger than 5 elements

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#275]
Allowing g:vimwiki_listsyms to be an arbitrary size would allow smoother transitions for the parents like:
▁▂▃▄▅▆▇▉

If it contains n elements one would use element 0 for progress == 0, element n-1 for progress == 100 and element ceil(progress/100*(n-1)) for all other values of progress.

**Comment by EinfachToll** [comment]
Thanks!
