### ISSUE TITLE
Missing leading slash in .tags

### ISSUE THREAD

**Issue by tlvince** [vimwiki/vimwiki#280]
Using the categories/tags feature (#85), the generated `.tags` file appears to be missing a leading slash, resulting in "file does not exist" errors when using `:tag`.

For example, given a file containing `# hello\n:hello:\n`, `VimwikiRebuildTags` produces:

```
!_TAG_FILE_SORTED       1
hello    Users/user/docs/wiki/hello.md    1;" vimwiki:Users/user/docs/wiki/hello1\tUsers/user/docs/wiki/hello
```

Note `Users/…` not `/Users/…`.

NVIM 0.1.5
OS X 10.10
vimwiki 3a87437

**Comment by EinfachToll** [comment]
It is correct that the slash is absent, but the Users/user/docs/ stuff shouldn't be there, either. Normally, the tag should be of the form `<subdirectory>/<pagename>.<extension>`. The subdirectory is present when the wiki file is not directly in your wiki directory but inside a subdirectory of it. Can you post your Vimwiki-related settings from your .vimrc? Looks a bit like your wiki directory would be `/`.

**Comment by tlvince** [comment]
Thanks. Here you go:

```
❯ cat after/plugin/vimwiki.vim 
let g:vimwiki_list = [{
  \ 'path': '~/docs/wiki/',
  \ 'syntax': 'markdown',
  \ 'index': 'home',
  \ 'ext': '.md'
\ }]

autocmd BufEnter ~/docs/wiki/* setlocal filetype=vimwiki
autocmd BufWritePost ~/docs/wiki/* call AutoCommit()
```

**Comment by EinfachToll** [comment]
Hm, this is a rather strange setup. If you put your settings in after/etc/, they are read, well, after all the plugins have been loaded. Try putting your settings in your vimrc instead.

This whole stuff regarding the user settings is currently a mess anyway, and I'm in the middle of refactoring it (see #256). When I'm done, this is hopefully either fixed or at least easier to fix than now.

(BTW: the penultimate line of your settings should not be necessary)

**Comment by tlvince** [comment]
Thanks. This indeed was the issue; moving the settings into `vimrc` produces `.tags` lines in their expected format.

I'll close this issue for now, but feel free to open reopen it if it's useful for #256 (e.g. a test case).
