### ISSUE TITLE
Escaping of pipes in table cells

### ISSUE THREAD

**Issue by sometoby** [vimwiki/vimwiki#281]
I'm trying to make a cheat sheet of Unix commands. Some of these commands include pipes, and putting them into a table messes up the formatting. Is there a way to escape/quote pipes so they're treated as text and not the cell border?

**Comment by EinfachToll** [comment]
Wrapping the | in backticks is the easiest solution: `` `|`  ``. Or add something else to the line, so that it does not start and end with |.

**Comment by sometoby** [comment]
You misunderstood the problem. It is not resolved, and the solution you suggested does not work.

Here is a video to show what's happening: https://www.youtube.com/watch?v=PsE3lfegAac

**Comment by sometoby** [comment]
I was [working on a fix already](https://github.com/sometoby/vimwiki/commit/73331df0a2f123e2be37e30a25fd794b4d9e9349), but there's still some work to be done on the HTML output which will still include the escape characters.

**Comment by vimishor** [comment]
@EinfachToll I have a similar issue:

Writing:

```markdown
| Heading |
| ----- |
| `^|` = desc |
```
I would expect to get :

```markdown
| Heading     |
|-------------|
| `^|` = desc |
```
But the actual result is:

```markdown
| Heading     |          |
|-------------|          |
| `^          | ` = desc |
```

**Comment by EinfachToll** [comment]
Yes, there is currently no way to make the table formatting code ignore certain pipe characters. A quick and dirty "solution" is to write a vertical bar instead of a pipe (you get it in Vim by typing Ctrl+k v v). But yes, there should be a way.

**Comment by tinmarino** [comment]
I just made a commit that permits `\|` symbols in table at least for formating, pandoc supports this for markdown tables.


You can also use these unicode symbols from https://en.wikipedia.org/wiki/Vertical_bar 

U+007C | VERTICAL LINE (HTML &#124; · &verbar;, &vert;, &VerticalLine;) (single vertical line)
U+00A6 ¦ BROKEN BAR (HTML &#166; · &brvbar;) (single broken line)
U+2016 ‖ DOUBLE VERTICAL LINE (HTML &#8214; · &Verbar;, &Vert;) (double vertical line ( ‖ {\displaystyle \|} \| ): used in pairs to indicate norm)
U+FF5C ｜ FULLWIDTH VERTICAL LINE (HTML &#65372;) (Fullwidth form)
U+2225 ∥ PARALLEL TO (HTML &#8741; · &DoubleVerticalBar;, &par;, &parallel;, &shortparallel;, &spar;)
U+01C0 ǀ LATIN LETTER DENTAL CLICK (HTML &#448;)
U+01C1 ǁ LATIN LETTER LATERAL CLICK (HTML &#449;)
U+2223 ∣ DIVIDES (HTML &#8739; · &mid;, &shortmid;, &smid;, &VerticalBar;)
U+2502 │ BOX DRAWINGS LIGHT VERTICAL (HTML &#9474; · &boxv;) (and various other box drawing characters in the range U+2500 to U+257F)
U+0964 । DEVANAGARI DANDA (HTML &#2404;)
U+0965 ॥ DEVANAGARI DOUBLE DANDA (HTML &#2405;)
