### ISSUE TITLE
option to disable mappings

### ISSUE THREAD

**Issue by aeosynth** [vimwiki/vimwiki#282]
i want to use this plugin, but the mappings are too invasive. can we have an option to disable mappings?

**Comment by EinfachToll** [comment]
The mappings which start with `<Leader>w` can be changed at once like this:

     let g:vimwiki_map_prefix = '<Leader>e'

You can kind of disable them by setting this option to a nonexisting key, e.g. `<F13>`

**Comment by aeosynth** [comment]
that will help, thanks. now i want less options, to make finding relevant ones easier :)
