### ISSUE TITLE
Completion with deoplete plugin does not work

### ISSUE THREAD

**Issue by ErickChacon** [vimwiki/vimwiki#283]
I use [deoplete](https://github.com/Shougo/deoplete.nvim/) plugin for completion. However, when I use deoplete when editing vimwiki files, it does not work. It shows me the menu for completion, but when I choose the option (with enter), it just go to the following line but do not complete the word.

This is my setup for the two plugins:

```
" Vimwiki settings
let g:vimwiki_list = [{'path':'$HOME/Documents/Nvim/Vimwiki',
      \ 'syntax': 'markdown', 'ext': '.md'}]
let g:deoplete#enable_at_startup=1 " active deoplete
```

**Comment by lukehinds** [comment]
Did you find any resolution @ErickChacon ? I  too use deoplete so this affects me as well.

**Comment by lukehinds** [comment]
OK, you can stop the tab collision by disabling table mappings. Put the following into your `init.vim` 

    let g:vimwiki_table_mappings = 0

**Comment by ErickChacon** [comment]
@lukehinds , I have tried your suggestion without success.

**Comment by EinfachToll** [comment]
It probably interferes with the mapping to `<CR>` in insert mode. Does it help if you put this in your `init.vim`?

    inoremap <F13> <Esc>:VimwikiReturn 1 5<CR>

**Comment by ErickChacon** [comment]
Ok, problem solved. <CR> in insert mode is used to work with lists in vimwiki. It is actually very useful. Then, what I had to do is to remap `deoplete#close_popup()` but just inside vimwiki buffer. 
So, if you add the following line on the file `.config/nvim/ftplugin/vimwiki.vim` it works with the right arrow instead of <CR>.

```
inoremap <silent><buffer> <expr><Right> pumvisible() ? deoplete#close_popup() : "<CR>"
```

**Comment by craigdallimore** [comment]
I found the suggestion from @lukehinds appears to work for `.vimwiki` files but not for `.md` files.

**Comment by matt-snider** [comment]
@ErickChacon  @lukehinds Came across this issue myself. I didn't want to use change the character I use for completion (`<CR>`).

I found the following works:
```vim
" Disable <CR> mapping
inoremap <F13> <Esc>:VimwikiReturn 1 5<CR>

" Only run VimwikiReturn if the popup menu is not showing
inoremap <silent><expr><CR> pumvisible() ? "<CR>" : "<Esc>:VimwikiReturn 1 5<CR>"
```

**Comment by FocusedWolf** [comment]
I haven't got around to setting up deoplete so with just standard omnicompletion this worked for me:

`" Prevent remapping <CR> so i can interact with an open OmniCompletion popup:
" SOURCE: https://github.com/vimwiki/vimwiki/blob/master/doc/vimwiki.txt#L1491
" SOURCE: https://github.com/vimwiki/vimwiki/issues/283
inoremap <expr> <CR>   pumvisible() ? "\<CR>"   : "<Esc>:VimwikiReturn 1 5<CR>"
inoremap <expr> <S-CR> pumvisible() ? "\<S-CR>" : "<Esc>:VimwikiReturn 2 2<CR>"`

The extra bit is the <S-CR> bind. It seems to be used by VimWiki to insert two <CR>'s or something, So, same treatment as <CR>, don't call vimwiki functions if pumvisible().

**Comment by ranebrown** [comment]
Another option is to use the new feature on the `dev` branch which allows for disabling all or certain groups of vimwiki key mappings. See the [documentation](https://github.com/vimwiki/vimwiki/blob/45025fa4f066eccca2f78607cae3b64ff5f2c3c7/doc/vimwiki.txt#L3306-L3373)

**Comment by snawaz** [comment]
> It shows me the menu for completion, but when I choose the option (with enter), it just go to the following line but do not complete the word.

I'm facing the same issue even though I'm not using `deoplete` at all. I'm nvim.
