### ISSUE TITLE
Prefixing WikiLinks at HTML conversion

### ISSUE THREAD

**Issue by maqiv** [vimwiki/vimwiki#284]
I want to publish my wiki on my homeserver under a sub-url on the server with Vimwiki2HTML, e.g. `http://myhomeserver/w`. But on my machine where I use vimwiki the path is set to `~/.vimwiki/` where the index.wiki file and corresponding file- and folderstructure for my wiki is located, thus relative html links are generated with the missing prefix `w/`.
Did I miss something or is this a missing feature/function?
Overwriting the VimwikiLinkConverter function as described in the helpfile is not possible due to the fact that it only is called for external links (http, https, etc.) and not links to other pages within the wiki.

Maybe I've search the wrong keywords, but I couldn't find anything here the last ~3.5h so I thought I'd ask.

**Comment by maqiv** [comment]
> The generated links are all relative (e.g. the link [[stuff]] in the file index.wiki should produce the link <a href="stuff.html">stuff</a> in index.html)

Right, but when I want to serve the files under `http://myhomeserver/w` then it wouldn't point to `http://myhomeserver/w/stuff.html`, but instead to `http://myhomeserver/stuff.html` and the webserver would respond with a 404.

But I've tried overwriting the VimwikiLinkConverter function again and I think it'll do the trick. I guess I was wrong about the VimwikiLinkConverter function in my issue request....I'll keep you updated!

Thanks for you response!

**Comment by maonx** [comment]
@EinfachToll I got same problem as it , When I use `{{local:test.png}}` , it convertered as `<img src="../../../C:\Users\Maonx\Dropbox\vimwiki\test.png">`.  I read the help and rewrited `VimwikiLinkConverter ` function as help said in my vimrc, but it convertered as same as above.

**Comment by maqiv** [comment]
Heja

Since I couldn't find a suitable solution for the [mentioned problem](https://github.com/vimwiki/vimwiki/issues/284#issue-198780577) with existing tools, I've decided to write a little Markdown to HTML converter for Vimwiki pages, which has the ability to prefix relative links between Vimwiki pages to support hosting converted Vimwiki HTML pages in URL subpaths.

Example for hosting converted Vimwiki HTML pages in the URL subpath `w/`:
```
https://example.com/w/index.html
https://example.com/w/tasks.html
https://example.com/w/images/slow_lori.png
....
```

I'm adding additional features (see [todo section](https://github.com/maqiv/vimwiki-godown#todo) in readme) to the converter from time to time. The fact that I use the converter myself very frequently ensures that this won't be another dying project ;-).

For more details please go to https://github.com/maqiv/vimwiki-godown

PS.: If you're using [misaka_md2html.py](https://github.com/jason6/vimwiki_md2html) and you're interessted/are planning to switch to Vimwiki-GoDown, but can't because of missing feature compatibility such as _percent codes_, please let me know so I can prioritize planned feature.

@EinfachToll: With your permission, I'll add it to the GitHub Wiki page [Connected Plugins](https://github.com/vimwiki/vimwiki/wiki/Connected-Plugins)?

**Comment by ranebrown** [comment]
I added a link on the [vimwiki wiki page](https://vimwiki.github.io/vimwikiwiki/Related%20Tools.html#Related%20Tools-External%20Tools)
