### ISSUE TITLE
something wrong with [[../../index|index]]

### ISSUE THREAD

**Issue by huangming** [vimwiki/vimwiki#287]
issue:
1.open my vimwiki index,write `[[level1/index|level1_index]]` and press `<CR>`.
2.in `level1/index.wiki` write `[[../index|index]]`  `[[level2/index|level2_index]]`and press `<CR>`.
3.in  `level1/level2/index.wiki` write `[[../index|level1_index]]` and press `<CR>`.
3.in `level1/level2/index.wiki` write `[[../../index|index]]` and press `<CR>`.The page goes to itself and i want it goes to vimwiki index.

**Comment by Nudin** [comment]
I couldn't reproduce this. Does this problem still occur?

**Comment by huangming** [comment]
![vimwiki](https://user-images.githubusercontent.com/1462302/32144989-7c99f79a-bcfc-11e7-8b22-5381eaca5bdd.gif)
Yes,it occurs. Vimwiki version is 2.3(maybe or not as i found it on help-docs).My vim version is 7.4.

**Comment by ranebrown** [comment]
This works correctly on the `master` and `dev` branch. Please reopen if you are still seeing this behavior.
