### ISSUE TITLE
xolox/vim-notes fails to save edited files to disc after vimwiki installation

### ISSUE THREAD

**Issue by cvrn** [vimwiki/vimwiki#288]
I just installed vimwiki beside an existing installation of xolox/vim-notes.
vimwiki works fine, but now vim-notes fails to save edited files to disc.
Pressing "w" in vim... nothing happens. Leaving vim with q!
After removing vimwiki vim-notes works as before.

**Comment by ranebrown** [comment]
@cvrn Is this still an issue for you with the latest `dev` branch of vimwiki? It doesn't look like [vim-notes](https://github.com/xolox/vim-notes) is being actively developed...

**Comment by ranebrown** [comment]
Please reopen if this is still a problem.
