### ISSUE TITLE
Support Org Syntax

### ISSUE THREAD

**Issue by daveloyall** [vimwiki/vimwiki#289]
Hello, strange Vim people who are working towards the same goals as we Emacs people, who may seem strange to you! :)

Consider http://orgmode.org/worg/dev/org-syntax.html

That is all.

**Comment by EinfachToll** [comment]
Don't worry, I'm aware of org-mode. Maybe supporting org syntax as well is worthwhile for the millions of users who change their mind and switch to Vim ;)

**Comment by ranebrown** [comment]
I think maintaining the current syntax variations is more than enough work and this would create more trouble than it's worth.

**Comment by theherk** [comment]
Given the implementations of [nvim-orgmode](https://github.com/nvim-orgmode/orgmode) and [milisims/tree-sitter-org](https://github.com/milisims/tree-sitter-org) since this was closed, any chance of reconsideration for supporting this syntax?

**Comment by brennen** [comment]
> Given the implementations of [nvim-orgmode](https://github.com/nvim-orgmode/orgmode) and [milisims/tree-sitter-org](https://github.com/milisims/tree-sitter-org) since this was closed, any chance of reconsideration for supporting this syntax?

Not any time soon. VimWiki's current implementation is such that differences between its supported syntax options are already its largest source of bugs and implementation difficulties. Wedging another one in there would probably not go very well.

(Sidebar: I was going to say "two supported syntax options".  There are theoretically three, but I have yet to meet anyone using the MediaWiki support, and I doubt it really works.)

I more or less think adding support for n syntax choices would require a ground-up rewrite.

**Comment by theherk** [comment]
Well I think that's a bummer... but a completely understandable one. :) I think org mode is a great syntax and with treesitter these days it should be more simple (not trivial) to support many different formats when developing something from scratch. But I'm not saying at all that you should, and thank you for taking the time to reply on an old closed issue.

**Comment by brennen** [comment]
Sure thing - sorry I don't have a better answer.

I think if I were designing a VimWiki-like plugin from scratch, I'd try to decouple the specific syntax from other implementation details, and it'd be great to support something like org. I actually came to VimWiki in the first place by way of bouncing off of Emacs, trying [vim-orgmode](https://github.com/jceb/vim-orgmode), and then landing here.

I haven't really surveyed what else is available lately, but e.g. [wiki.vim](https://github.com/lervag/wiki.vim) might have an architecture where it'd be a lot easier to drop in a new syntax. It doesn't seem like it relies on filetype per se.
