### ISSUE TITLE
Make all markdown files as vimwiki file

### ISSUE THREAD

**Issue by tnguyen14** [vimwiki/vimwiki#292]
After installing the plugin, when I open any markdown file, the `syntax` is set as `vimwiki`. Is there any way I could prevent this from happening?

**Comment by EinfachToll** [comment]
`let g:vimwiki_global_ext=0` should help. See `:h g:vimwiki_global_ext`.

**Comment by tnguyen14** [comment]
That works. Thanks @EinfachToll
