### ISSUE TITLE
Define Anchors?

### ISSUE THREAD

**Issue by nabsiddiqui** [vimwiki/vimwiki#293]
I like to write my diary files in markdown, but having headings with "#" in my diary entry causes all the diary entry generations to use them as anchor points.  Is there a way to use a different anchor when using markdown?

**Comment by ranebrown** [comment]
@nabsiddiqui Is this still a problem with the latest release and/or the `dev` branch? There have been some modifications to markdown support and think this has likely been fixed.

**Comment by ranebrown** [comment]
If this is still an issue please reopen and provide an example to reproduce the problem.

**Comment by nabsiddiqui** [comment]
Honestly I can't even remember what this bug was.  I have been using vimwiki for 2 years now without problems.  Thank you for the work in putting this together.
