### ISSUE TITLE
It is not clear how to remove link

### ISSUE THREAD

**Issue by emilhuseynli** [vimwiki/vimwiki#294]
Pressing ```<CR>``` in normal mode and when cursor is on some word decorates that word with double square brackets, i.e. makes it to link (no corresponding wiki page created).

But isn't there any way to undo that? Say, if I hit enter on some word by mistake then exit vim and open same wikipage again later and I see that dangling link which doesn't point to anyware, how can I remove a decoration from unwanted link? I could use surround plugin (ds[ twice), but maybe there's more proper way?

**Comment by EinfachToll** [comment]
You have all of Vim's super duper text editing power right under your fingertips. Just press `u` like you undo everything in Vim.

**Comment by emilhuseynli** [comment]
Undo will not work if vim is closed and opened again later. But anyway, I can still easily remove stale brackets with the help of tpope's surround plugin (ds[ two times). Just wanted to know whether there's a predefined command for that in vimwiki already. The answer is no. Thanks for the quick response! I'm closing the issue then.

**Comment by EinfachToll** [comment]
> Undo will not work if vim is closed and opened again later.

It will with this command: `:set undofile`.

**Comment by EinfachToll** [comment]
I don't understand what you mean. When you create a new page by accident, then you have most likely only one link to it. There are not links in other pages. Also, when a page is deleted, I don't think it makes sense for Vimwiki to go around and remove the brackets around the links to this page. Only the user knows what to to with these superfluous links now.

**Comment by sdondley** [comment]
There should be a command for removing links. Seems like a no brainer to me. If I create a link and a page and then decide to delete the page, the link should be removed for me automatically. If not, there should at least be a way remove a link manually. Undo is impossible if I want to remove a link moths or days later. Even if the link was created recently, using "undo" is hackish and you shouldn't have to rely on an external program or write a map to do something so basic.

**Comment by johnyoonh** [comment]
@sdondley Spot on. I resorted to using [gf](https://vim.fandom.com/wiki/Open_file_under_cursor) command instead of VimWikiLinks just because of this.

**Comment by sdondley** [comment]
Here's a map to remove a markdown link: `nmap <Leader>wx mads[f(df)x\`a`

**Comment by ranebrown** [comment]
Is the desired behavior here just to remove the link syntax?
```
[[file|description]] -> description
[[file_only]] -> file_only OR nothing?
[md_description](md_file) -> md_description
```

**Comment by sdondley** [comment]
Yes.

**Comment by ranebrown** [comment]
Can you create a new issue with a detailed description of the feature request? Or _even better_ create a PR that implements the change.

**Comment by sdondley** [comment]
My vim scripting ability is extremely spotty and I haven't done more than write a few simple functions and hacked on other vim scripts. But if you can steer me in the right direction to help save me some time, I'd be willing to give it a shot.

**Comment by ranebrown** [comment]
I think the easiest method would be to place a new command that uses a regex pattern and `substitute()` and then map that command to a key binding. This should be placed in `ftplugin/vimwiki.vim`. You should be able to use some of the other commands defined in that file as examples. You might need to create a new function if multiple steps are needed or to handle the substitution.

**Comment by ranebrown** [comment]
Might actually be a little more complicated now that I think about it since you need to grab the text, modify it and replace it. [vimwiki#base#follow_link](https://github.com/vimwiki/vimwiki/blob/1e5c93ea917bbb27cade5de54fc120a989333f32/autoload/vimwiki/base.vim#L1252) is probably a good starting point.

**Comment by sdondley** [comment]
How are tests run with Vimscript? Can you recommend any good books on basic development with vim? I’ve read small doses of learn vim script the hard way.

**Comment by ranebrown** [comment]
The only test framework I know of is [vader](https://github.com/junegunn/vader.vim) which this project doesn't currently use (but needs to). I don't know of any books of the top of my head but I'm sure there are some good ones out there. As you mentioned [Learn Vimscript the Hard Way](http://learnvimscriptthehardway.stevelosh.com/) is a pretty good resource. The Vim help files are well written but it can't be difficult to find something if you don't know the correct name. Vim also has a built in debugger, brief overview [here](http://inlehmansterms.net/2014/10/31/debugging-vim/). Hope some of that helps.
