### ISSUE TITLE
creating all html generates wrong links to subwiki diaries

### ISSUE THREAD

**Issue by Garonenur** [vimwiki/vimwiki#298]
moin,

I have 3 wikis, a main wiki which is just an index file with links to the two subwikis one is general work stuff and one is for a distinct project. Both subwikis have diaries and all of them are defined in my vimrc as follows:
```vim
let main_wiki = {}
let main_wiki.path = 'path/wiki/text/'
let main_wiki.path_html = 'path/wiki/html'
let main_wiki.template_path = 'path/wiki/templates'
let main_wiki.template_default = 'my'
let project_wiki       = {}
let project_wiki.path  = 'path/wiki/text/Projekt'
let project_wiki.path_html = 'path/wiki/html/Projekt'
let project_wiki.diary_rel_path = 'Projekt/diary'
let project_wiki.index = 'Notes'
let project_wiki.ext   = '.wiki'
let work_wiki       = {}
let work_wiki.path  = 'path/wiki/text/work/'
let work_wiki.path_html = 'path/wiki/html/work'
let work_wiki.diary_rel_path = 'work/diary'
let work_wiki.index = 'Notes'
let work_wiki.ext   = '.wiki'
let g:vimwiki_list = [main_wiki, work_wiki, project_wiki]
```
I tested other values for ```diary_rel_path``` without success.

Every ```[[diary:SOMETHING]]```-Link points to the diary folder which would exist if the main-wiki had one.

Do you need any more information? Or am I simply doing something wrong?

**Comment by Garonenur** [comment]
actualy, doing the above breaks diary links and creation within vim. Without setting ```diary_rel_path``` for any of the wikis in vim everything works as expected, but html links to diary stuff always point to the main/default wiki diary.

**Comment by Garonenur** [comment]
if I use ```[[diary/diary|diary]]``` it works the error seems to be in the interpretation of the ```diary:``` when creating the html.

**Comment by Nudin** [comment]
Is this still an issue?

**Comment by Garonenur** [comment]
my setup changed a lot since I created this issue.
I will have to check if I can test it.

**Comment by tinmarino** [comment]
Closing: inactive (I think it is fixed). Feel free to reopen a new issue linking this one with a reproductible test.
