### ISSUE TITLE
linking between interwikis is broken for html export

### ISSUE THREAD

**Issue by Garonenur** [vimwiki/vimwiki#299]
using the ```[[wikiN:|description]]``` syntax to link between different wikis works for vim, but not for html export.

if two wikis are at different locations the link in the html will point to the directory of the source file, not the created .html file (I am using a similar scheme like in the documentation, have a folder ```text``` and one ```html``` for each sub/interwiki).
It changes the file ending to html, but uses the text-folder, not the html output folder.
I tried to understand what is happening in the script, but my vimscript is rudementary at best.
Strangely if I have a interwiki located in a subfolder of another wiki (a main wiki) it works, but this might be due to the fact, that the input/output folder thing is hirarchichaly above the distinction of the interwikis?
Please tell me if You need more information to solve this.

**Comment by adi93** [comment]
Hi, I am looking at some past vimwiki bugs, and thought that I should start with this. Can you provide a sample wiki file, the generated html file, and exactly where the bug is?

**Comment by Garonenur** [comment]
I am sorry, this is old and I am not sure on which PC I had this problem and if I still have that problem anywhere?
I will check.

**Comment by tinmarino** [comment]
Closing <= refactoring html issues to #1139 (too many to browse ticket efficiently).
