### ISSUE TITLE
`:VimwikiDiaryGenerateLinks` does not understand markdown syntax and custom file ext.

### ISSUE THREAD

**Issue by dpc** [vimwiki/vimwiki#302]
```
let g:vimwiki_list = [ {'path': '~/vimwiki', 'syntax': 'markdown', 'ext': '.md.wiki'} ]
```

Create couple of diaries, `:VimwikiDiaryGenerateLinks` - the generated links are using non-markdown syntax and point to wrong directories.

BTW. Vimwiki is awesome.

**Comment by argshook** [comment]
hello, i noticed the same thing using `'ext': '.wiki.gpg'`. Generated links contain additional `.wiki` and link to `diary-entry.wiki.wiki.gpg` whilst it should link to `diary-entry.wiki.gpg`

**Comment by dpc** [comment]
@argshook :  Please test my patch and let me know.

**Comment by argshook** [comment]
@dpc hey, it seems to work well, thanks!

**Comment by johnmarcampbell** [comment]
Alright, it's merged in. Thanks for the patch, @dpc!
