### ISSUE TITLE
Feature: Create function VimwikiDeleteFile

### ISSUE THREAD

**Issue by mdm508** [vimwiki/vimwiki#306]
I have the following dependencies
A) computer organization -> file 
B) Read Lecture 7 -> file

when I delete the 'file' link in dependency A, I want the link to 'file' link in dependency B to be gone when I navigate into 'computer organization'. What is the best way to accomplish this? Thank you all for help.

**Comment by EinfachToll** [comment]
Either do `:VimwikiBacklinks` **before** you delete a wiki page and then, after you deleted the file, use `:lnext` etc. to jump to all links, or you simly search in all pages for "file" (with grep on the command line or with `:VimwikiSearch`).

That makes me realize it would probably a good idea to populate the location list automatically with all links whenever you delete a page with `:VimwikiDeleteLink`.

**Comment by f-dj** [comment]
> That makes me realize it would probably a good idea to populate the location list automatically with all links whenever you delete a page with `:VimwikiDeleteLink`.

Are there any plans to implement this? Or is it already implemented by now?

**Comment by ranebrown** [comment]
Not to my knowledge. I'll reopen for now so this doesn't get lost.

**Comment by tinmarino** [comment]
Issue Renamed from "Question on How to delete all links that point to a deleted link."
I saw this request in an other issue I closed, it is easy to implement so I keep open.
Feel free to look at `RenameFile` and create its brother `DeleteFile`

**Comment by tinmarino** [comment]
Done
