### ISSUE TITLE
Disable one Plug but not the other

### ISSUE THREAD

**Issue by hgiesel** [vimwiki/vimwiki#307]
In this plugin, `<cr>` is assigned one very useful mapping, and one quite annoying (for my use case anyway), which is the creation of new links.
Can I disable `<plug>VimwikiNormalizeLinkVisualCR` and keep `<plug>VimwikiFollowLink` on pressing `<cr>`?

**Comment by hgiesel** [comment]
I actually just realized that <plug>VimwikiFollowLink created the links. Can I somehow disable this feature from <plug>VimwikiFollowLink?

**Comment by EinfachToll** [comment]
> I actually just realized that VimwikiFollowLink created the links. Can I somehow disable this feature from VimwikiFollowLink?

Yes, the mapping key -> command is not created if there already is a mapping to the command. If you don't want any key to map to this command, you can use a dummy key which does not exist on your keyboard:
```viml
nmap <buffer> <F13> <Plug>VimwikiFollowLink
```

**Comment by protist** [comment]
I think I have a similar question, but I'm not sure if we're all on the same page.

If I understand correctly, @hgiesel is saying that `<CR>`  follows links, but can also create links. I think that they would like it to *only* follow links, but *not* create links. Is that possible?

Also, is it further possible to make `<CR>` only follow urls? And then have the other two functions (follow or create wiki links) on a different mapping?

**Comment by protist** [comment]
To clarify, my main issue with `<CR>` following wiki links is that it opens the next file in a new buffer, but *saves* the original file. If I go back to the original file, the undo tree has disappeared!

**Comment by ranebrown** [comment]
@hgiesel, @protist There is a new option `g:vimwiki_create_link` that was added in PR #528. This is merged to the `dev` branch and will be part of the v2.5 release #638. Give that a try and reopen if things aren't working as expected.
