### ISSUE TITLE
Increase/Decrease Todo-List status

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#308]
With :VimwikiToggleListItem we can change the status of a listitem between 0% and 100% – but we also include sub states configured in g:vimwiki_listsyms – for now we use them mostly to indicate the status of a item with subitems but it can already be nested, so it is possible to use the inbetween-states also for items without subitems.
This would become easier and more obvious if there are functions and keybindings to increment and decrement the state.

I've written a quick-and-dirty patch [in my branch](https://github.com/Nudin/vimwiki/commit/5eb6b1c2ab8c0417a61a8d5d3976ad2b99c65556).
I'll do some code-reuse and documentation but maybe you can already tell me what you think. Also I'm not sure which keybindings we should use by default…

**Comment by johnmarcampbell** [comment]
It looks like there's a merged PR that solves this, so I'm closing the issue.
