### ISSUE TITLE
Question: How do you set the width of the calendar-vim window in vimwiki?

### ISSUE THREAD

**Issue by dbhaig** [vimwiki/vimwiki#310]
When I open calendar-vim in vimwiki, it opens such that it is too narrow to display all of the columns. Is there a configuration variable that I can set in my .vimrc file to correct this?

Thanks

**Comment by EinfachToll** [comment]
Vimwiki and calendar.vim are two unrelated plugins. Are really doubt that it's Vimwiki which messes with the window width.
