### ISSUE TITLE
different color for completed todo list entry

### ISSUE THREAD

**Issue by machin3io** [vimwiki/vimwiki#311]
Been wondering how it can be done, as it is clearly shown on the second screenshot. For me an open todolist entry is the same color as a completed one.
The highlights in https://github.com/vimwiki/vimwiki/blob/dev/syntax/vimwiki.vim#L516-L596 don't seem to distinguish between the 2 todo list states either. What am I missing? Thanks, love vimwiki!

**Comment by EinfachToll** [comment]
Put this in your .vimrc: `let g:vimwiki_hl_cb_checked = 2`. See `:h g:vimwiki_hl_cb_checked` for more infos.

**Comment by machin3io** [comment]
Perfect, thank you so much!
