### ISSUE TITLE
Don't conceal one-character markers

### ISSUE THREAD

**Issue by Ram-Z** [vimwiki/vimwiki#315]
Add an option to disable conceiling one-char markers? I want typefaces to not be conceiled but URLs still shortened.

**Comment by pjf** [comment]
@Ram-Z : I'm walking through tickets trying to better understand them. Can you give an example of what you mean, with current and desired behaviour?

**Comment by Ram-Z** [comment]
When setting the typeface for text, the various markers are being concealed. I.e. `*bold text*` will simply show up as **bold text** rather than **\*bold text\***, or `_italic text_` as _italic text_ rather than _\_italic text\__.

I know I can change `g:vimwiki_conceallevel` to disable it, but that would also disable concealing wiki links (`[[This is a link source|Description of the link]]` -> <u>Description of the link</u>), which I would like to keep.

**Comment by adc17** [comment]
@pjf I think this helps usability a lot; some fonts don't support bold/italic, so if the markup is conceiled it just looks like regular text.

**Comment by ranebrown** [comment]
This would be quite easy to implement. Just create a new option and wrap these [lines](https://github.com/vimwiki/vimwiki/blob/master/syntax/vimwiki.vim#L158-L175) in an `if` statement using `vimwiki#vars#get_global()` to check the variable status.
