### ISSUE TITLE
Open links in previous window

### ISSUE THREAD

**Issue by mediapathic** [vimwiki/vimwiki#316]
[edit: am I not allowed to label this a feature request, or am I not understanding some UI on github?]

I'm not certain if this is a feature request, or a help request for a feature I can't find. Please let me know if this is the wrong place for this. 

I am using the multimarkdown transclusion syntax to write large documents. Vimwiki respects this syntax and follows links (which I was pleasantly surprised by, thanks!), but as far as I can tell there is no way to keep one window open with a list of links and always open the result in the same split, so as to rapidly switch between sub-files. I'm thinking here of something similar to how netrw has a binding for "open in previous window." Or, if it helps, another way of thinking of this is that I am essentially using vimwiki with a split window as one is meant to use Voom (only for multiple documents). 

I suspect this is solvable by a keybinding, but I can't figure out the syntax to do so. However, I submit that others probably would like this capability too, so it may be a feature worth incorporating into vimwiki as well. 

Thanks very much for keeping vimwiki going. I love this project, and it has been helpful to me as a writer in ways I don't have time to write and you don't have time to read. Your work is very appreciated!

**Comment by EinfachToll** [comment]
This is totally the right place for feature requests.

I just added the possibility to do what you wanted, but didn't provide a default key binding.
Check out the "dev" branch and see `:h vimwiki-follow_link` for how to make a key mapping.

**Comment by mediapathic** [comment]
Thanks so much for the rapid reply! It works great in all cases except the one I want :) By which I mean: For a normal wiki link, it works fine. But for the multimarkdown transclude syntax, doing vsplit and reuse has a rather strange behavior. The first file works fine, but trying to reuse the split causes vimwiki to try to create a new subdirectory. An example:

if I have
`{{parts/file1.txt}}
{{parts/file2.txt}}'

doing :call vimwiki#base#follow_link('vsplit', 1, 1) on the first line opens the the file as needed. But then, calling it on the second line gives me the error message that vimwiki wants to create  `parts/parts/file2.txt`because it doesn't exist. It seems to be getting confused about what directory it's in.

Does that make sense? If you need any further details please don't hesitate to ask.

Thanks!
