### ISSUE TITLE
VimwikiMakeDiaryNote not working well after sourcing $MYVIMRC

### ISSUE THREAD

**Issue by llinfeng** [vimwiki/vimwiki#324]
As demonstrated in the following screencast, I am not able to get directly back to the up-to-date diary page once having sourced `$MYVIMRC`. This problem is consistent across my Linux machine and my MacBook. (The screenshot is made on Windows machine.)

## The screencast 
![vimwiki_redirection_problem](https://cloud.githubusercontent.com/assets/5890407/24612388/2867545e-1853-11e7-9595-10e2817c7e75.gif)

## The minimum steps:
1. Start Vim fresh
2. Check to make sure `VimwikiMakeDiaryNote` is working. (I used `<leader>w<leader>w` to trigger this function.)
3. Source `_vimrc` by issuing command `:so $MYVIMRC`. (The file to be sourced on *NIX machines shall be `.vimrc`)
4. Try to call function `VimwikiMakeDiaryNote`, and end up with a *almost correct* absolute path, leading to an empty file. I guess this is a *path* issue, as:
  - The correct path to the diary of the day is: `~/Dropbox/Wiki/Warehouse/2017-04-03.wiki`
  - The path to the blank file is `~/Dropbox/Wiki/Warehouse2017-04-03.wiki`; 
5. Activating the master page of the default Wiki solves this problem. (Pressing `<leader>ww`)

**Comment by EinfachToll** [comment]
As a quick fix, it should work if you make sure that in your vimrc bot the path to your wiki ('path') and 'diary_rel_path' end with a `/`.
For a real fix, the whole path handling stuff in Vimwiki needs to be refactored, and I'm currently working on exactly this, because it is related to some other bugs I personally encountered ;)

**Comment by llinfeng** [comment]
This solution works like a breeze! Thanks a lot!
