### ISSUE TITLE
No fenced code blocks in Markdown

### ISSUE THREAD

**Issue by lordspamalot** [vimwiki/vimwiki#327]
Unfortunately, the fenced code blocks are not working for me. 
I use the following settings:

`let g:vimwiki_list = [{'path': 'C:\wiki\', 'path_html': 'C:\wiki\',
                   \ 'syntax': 'markdown', 'ext': '.md'}]
`

I use the following syntax for the code blocks:

````
```html
<pre>
  <p>Sample text here...</p>
</pre>
```
````

If I use a plain markdown file outside of Vimwiki, everything is working as expected.
What am I doing wrong?

**Comment by EinfachToll** [comment]
What do you mean by "not working"? Do you mean it is not highlighted at all? Or it is highlighted, but not like HTML?

**Comment by lordspamalot** [comment]
No highlighting for any language.

**Comment by EinfachToll** [comment]
I'm confused. Can you just post a screenshot? Also, remember that after you inserted a code block, you may have to reload the current buffer (`:e`) to make the highlighting of the code block work.

**Comment by lordspamalot** [comment]
I reloaded the buffer. But nothing happens.

Here is the screenshot:

![vimwiki](https://cloud.githubusercontent.com/assets/8754179/24994330/a0cc622a-202a-11e7-908d-7f5c157d6e39.png)

**Comment by EinfachToll** [comment]
Hm, strange. Does the html filetype work normally in your Vim distribution? If you just open a .html file with Vim, is it highlighted correctly?

**Comment by lordspamalot** [comment]
Yes the highlighting is working in a .html file.

![2017-04-18 10_36_02-test html _desktop - gvim1](https://cloud.githubusercontent.com/assets/8754179/25121843/4d68ea7a-2423-11e7-8821-c62ad8b92ea8.png)

Also in a normal markdown file.

![2017-04-18 10_38_12-test md _desktop - gvim1](https://cloud.githubusercontent.com/assets/8754179/25121876/66b6748e-2423-11e7-9673-ee770fd2a820.png)

**Comment by yangkev** [comment]
I'm experiencing this issue as well. It seems that vimwiki has its own filetype, so when switching to markdown via 
```
:set ft=markdown
```
suddenly the fenced code block highlighting works (if you have let g:markdown_fenced_languages = ['python'...])

**Comment by EinfachToll** [comment]
@yangkev Yes, if you change the filetype to markdown, the markdown plugin takes care of the highlighting instead of Vimwiki. And apparently, it works better.
Anyway, I don't really have a clue what could be the issue. Maybe it helps if you provide a little more info. Does this issue occur only for HTML (or Python) code snippets or with every language? What if you use the default vimwiki syntax instead of markdown? (In default syntax, a code block would look like:
```
{{{html
<p> foo
}}}
```
)

**Comment by yangkev** [comment]
I wasn't able to reproduce the issue, and it is working as expected now.

**Comment by EinfachToll** [comment]
Ok, closing this for now. If the issue reappears and your have more info, feel free to reopen.
