### ISSUE TITLE
syntax is all just one color

### ISSUE THREAD

**Issue by shibumi** [vimwiki/vimwiki#329]
Hello,
first of all thanks for vimwiki. It's really great. Before it I rarely documented stuff, now I really write down a lot.

I have just one question. Why do I have for everything the same color in highlighting?

`set syntax?` says: `vimwiki`

and how can I enable nested_syntaxes? 
The documentation says:`automatic_nested_syntaxes` should be enabled on default. But it doesn't seem so...

Here an example:
![](https://paste.archlinux.de/S6j/)

**Comment by EinfachToll** [comment]
I'm not sure I understand. In your screenshot, the headers clearly have a different color than the other text and are set in bold.
The output of `set syntax?` is correct, it's always `vimwiki`, even when you have set markdown.
As for the bash code snippet: the file type after the `{{{` must be the name under which **Vim** knows the file type, and that is `sh`, not `bash` (likewise `cpp` and not `c++`). Also notice that after you changed the name, you have to reload the buffer (`:e`) to see the highlighting.

**Comment by shibumi** [comment]
Hello,
Thanks for your answer. Indeed `{{{sh` works. But what I still not understand is: why is the whole vimwiki syntax highlighting for me in just 1 color?
Here is another example: In your README you have different colors for 1. header, 2. headers and links.. I have just everything in pink?! I don't have this issue with any other syntax highlighting. All of my other syntax highlightings are very colorful.
![](https://paste.archlinux.de/swb/)

**Comment by dwierenga** [comment]
@EinfachToll: it might be helpful to say on the README what colorscheme you were using when you took the screenshot.

**Comment by EinfachToll** [comment]
@shibumi You have to setup the header colors yourself, see `:h vimwiki-syntax-headers`. Thinking about it, I should integrate it into Vimwiki. The fact that the headers and the links have the same color in your screenshot is most likely just a matter of your colorscheme.

@dwierenga Will do. It's solarized, BTW.

**Comment by acornq** [comment]
I am having a similar issue. That is all the headers are in the same colour and I can't change them. In the documentation it says you can change the headers' colour with :hi VimwikiHeader1 guifg=#FF0000. This doesn't work for me. It actually resets it to normal text colour and boldness. Changing the #value doesn't matter. I tested this behaviour using vanilla vim, no colourscheme and just the recommended additions to vimrc

**Comment by RidaAyed** [comment]
Hi

Expecting titles that differ in colours, all my titles are equally coloured.


Is there a particular setting I may set or do I have to *set each title for each theme* I'm using as proposed from @EinfachToll ?

# This title should be coloured differently than

## This subtitle

### Or this title

Expected
![Expected](https://github.com/vimwiki/vimwiki/blob/dev/doc/screenshot_1.png?raw=true)

Current
![Current](https://i.imgur.com/wmZCICa.png)

**Comment by johnmarcampbell** [comment]
Well, I think you have two options. You can either set them all manually as described in `:h vimwiki-syntax-headers`, or you can link them to pre-existing highlight groups. For instance, try running `:so $VIMRUNTIME/syntax/hitest.vim`. This should open a buffer that lists all the existing highlight groups (it may take 10 or 20 seconds to load). By default, vimwiki links all `VimwikiHeaderX` styles to the `Title` group, which you should see in the `Highlight test` buffer you opened. You can change the links by executing `:hi link VimwikiHeader2 {newGroup}` where `{newGroup}` is one of the highlight groups you see in the `Highlight test` buffer.

I have a pretty limited understanding of how this works with different  color schemes, but I think each theme just changes the attributes of different highlight groups. So if you link the `VimwikiHeader`'s to well-established highlight groups I think they should automatically change when you switch themes.

**Comment by ranebrown** [comment]
The documentation has been updated and regarding nested syntaxes and the header color highlighting was a configuration issue so I'm going to close this. Please create a new issue needed.

**Comment by jrd-oje** [comment]
For all of you who landed here because you want to give the vimwiki headers different colors, according to your terminal color scheme, and perpetuate it in your neovim lua configuration: This works very well:
```
vim.cmd('highlight vimwikiHeader1 ctermfg=1')
vim.cmd('highlight vimwikiHeader2 ctermfg=2')
vim.cmd('highlight vimwikiHeader3 ctermfg=3')
```
