### ISSUE TITLE
Add option to convert multiple rows in table to single HTML table row, one cell

### ISSUE THREAD

**Issue by standardeyre** [vimwiki/vimwiki#330]
Vimwiki is great.  I like the tables.

In one corner case, I want to have multiple lines of table text in one single cell when converted from vimwiki to HTML. The resulting HTML should contain all the table text in one cell within one row (and one column).

I wrote a fix to answer [this question I opened on vi.stackexchange.com][1].  I will submit a pull request soon.

-----
[1]:http://vi.stackexchange.com/q/11638/6590

**Comment by EinfachToll** [comment]
The proposed solution is suboptimal, as I wrote in #331, but the idea is still valid.

**Comment by tinmarino** [comment]
Closing <= workaround exists, feature not required in vimwiki.
