### ISSUE TITLE
VimwikiGeneratedTags not work

### ISSUE THREAD

**Issue by maonx** [vimwiki/vimwiki#332]
Hello, I like vimwiki very much, but when I wanted to generated tags `:VimwikiGeneratedTags`,it not generated all tags but only `= Generated Tags =`. 
I read help text but there was little info about `VimwikiGeneratedTags`, so what should I to fix it?
PS: Macbook Pro, Macvim

**Comment by EinfachToll** [comment]
Maybe you have to build the tags first by `:VimwikiRebuildTags!`. See `:h vimwiki-syntax-tags` for more.

**Comment by maonx** [comment]
Thank you ,it worked!! :laughing:

**Comment by EinfachToll** [comment]
I added a note to the doc.
