### ISSUE TITLE
Conceal link name prefix

### ISSUE THREAD

**Issue by caedn** [vimwiki/vimwiki#333]
I like prefixing links to external resources with ⇱ like so: 

```markdown
[&#8689; Wikipedia](https://en.wikipedia.org/)
```
Is there a way to conceal the html entity but still show the name of the link? I have managed to conceal the whole link if it's a prefixed link but I'd still like to see the name. 

```vim
:syntax region VimwikiLink start="\[&#8689; " end=")" conceal
```
I have also tried to create a conceal for the entity but it's either ignored in links (but works elsewhere):

```vim
:syntax match Entity "&#8689;" conceal cchar=⇱
```

or breaks the rest of the original conceal:

```vim
:syntax region VimwikiLink start="\[&#8689" end=";" conceal cchar=⇱
```

**Comment by EinfachToll** [comment]
AFAIK highlighting patterns which overlap are very nasty in Vim, so it's probably hard to make a `:syntax` pattern in your .vimrc which adds some highlighting to Vimwiki without breaking anything. If you want to bake your changes in the Vimwiki code, [these](https://github.com/vimwiki/vimwiki/blob/dev/syntax/vimwiki.vim#L357-L360) are the relevant lines. This is all I can do for you, you have to figure out the rest for yourself :)
