### ISSUE TITLE
Apostrophe in anchor caused error

### ISSUE THREAD

**Issue by Flurrywinde** [vimwiki/vimwiki#338]
I had a header with an apostrophe in it, something like:
`== A dog's life ==`
Then I made a link to it: `[[Some file#A dog's life]]`

Got this error: 
> Error detected while processing function vimwiki#base#follow_link[39]..vimwiki#base#open_link[26]..vimwiki#base#edit_file[34]..<SNR>74_jump_to_anchor:
>line 9:
> E15: Invalid expression: 'A dog's life'

**Comment by johnmarcampbell** [comment]
I just tested this with PR #411 merged in, and it works fine. @Flurrywinde, if you're experiencing this problem can you update *from the dev branch* and see if it fixes it?

**Comment by Flurrywinde** [comment]
Works fine now with the latest dev branch. Thanks!

**Comment by johnmarcampbell** [comment]
Glad to hear it!
