### ISSUE TITLE
Broken link (partial URL) sent to browser when using Markdown syntax

### ISSUE THREAD

**Issue by qjcg** [vimwiki/vimwiki#342]
The `markdown` syntax link: 

`[VimWiki](https://github.com/vimwiki/vimwiki)`

Opens the following URL in my browser when I press Enter with the cursor over it in vimwiki:

<https://github.com/vimwiki/vi>

Something is happening to the `mwiki`!

I do **not** have the same issue when using the `default` syntax --- following this link sends my browser to the correct, full URL:

`[[https://github.com/vimwiki/vimwiki|VimWiki]]`

**Comment by ranebrown** [comment]
@qjcg I tested this and I believe the issue has been fixed. If you are still seeing this behavior please reopen.
