### ISSUE TITLE
Feature Request: Get Diary Name from first header

### ISSUE THREAD

**Issue by mediapathic** [vimwiki/vimwiki#344]
...which I know is the case usually. But! If I create a diary file with YAML metadata, the diary link name is empty. 

Example:
If I make `2017-05-07` and it looks like
```
# Hello world 
foo
``` 
the diary entry becomes 
```
[[2017-05-07|Hello world]]
``` 
Which is as it should be. But, if `2017-05-07` looks like this:

```
tags: test 

# Hello world 
foo
``` 
the link is 

```
[[2017-05-07]]
```
I'd like it if in the second case the link also includes the name from the first header. Alternately, I suspect some people would prefer having it read a `title` tag in the metadata if it exists. That's not my preference but it's something to consider for others I think. 

Thanks!

**Comment by EinfachToll** [comment]
```
tags: test 

# Hello world 
foo
```

Did you try exactly this file or only a similar one? AFAIR Vimwiki always looks in the first 5 lines of a diary file for the first header and takes this one, so this should actually work.

**Comment by ranebrown** [comment]
I tested this and the provided example uses the header. Since there hasn't been a response from the author I'm closing.
