### ISSUE TITLE
Bug: Error with `:VimwikiSearch` -> `E926: Current location list was changed`

### ISSUE THREAD

**Issue by sandervanburken** [vimwiki/vimwiki#350]
A search inside the wiki with `:VimwikiSearch <term>` results, after the search finds the first match, in this error: `E926: Current location list was changed`

Any help on how to debug this issue is appreciated!

**Comment by sandervanburken** [comment]
Likely this issue is caused by a conflicting setting from 'scrooloose/syntastic'. Disabling this syntastic is a work around: `let g:syntastic_check_on_open = 0`

**Comment by pkazmier** [comment]
I'm also receiving this error, but I am not using syntastic. I am, however, using `w0rp/ale`. When I comment out the ale plug-in, then it works fine. I recognize this is not a vimwiki issue, but I am looking for any guidance on how to troubleshoot further if anyone has ideas.

**Comment by ranebrown** [comment]
@pkazmier What are your ALE and Vimwiki settings?

**Comment by chliul** [comment]
@pkazmier I set g:ale_set_loclist = 0 disable ale using loaction list, which seems works for me now.

**Comment by tinmarino** [comment]
Closing <= 3td party workaround is the official solution (so that we do not have custom ALE support)
