### ISSUE TITLE
Is it possible to configure Vimwiki to use triple backticks (```) instead of '{{{' and '}}}'?

### ISSUE THREAD

**Issue by sromeroi** [vimwiki/vimwiki#351]
Hi.

I've just discovered vimwiki and I'm very surprised and pleased with it. I'm used to write markdown "github-style" so I create code blocks with either 4 spaces or between triple backticks (```), and VimWiki uses {{{ and }}}.

Is it possible somehow with a config variable to change {{{ and }}} to triple backticks?

Also, I don't understand why, but "set filetype=mkd" is coloring in green contents between {{{ and }}} but "set filetype=vimwiki" is not doing it (I don't have green color for code blocks inside Wiki pages).

**Comment by Snaptags** [comment]
You have to switch to markdown syntax to use triple backticks instead of the VimWiki syntax:
```
" vimrc:
let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]
