### ISSUE TITLE
Vimwiki steals `Tab` event on markdown files.

### ISSUE THREAD

**Issue by dpc** [vimwiki/vimwiki#353]
I'm trying to get autocompletion working with deoplete for markdown files and it looks that `vim-wiki` is breaking it. This is same (similiar?) to https://github.com/vimwiki/vimwiki/issues/283

I get the popup menu but pressing `Tab` inserts indentation/spaces instead of cycling through the completion menu.

It looks like `vimwiki` of markdown files is intercepting the `<Tab>`.

Is there anything that I could do? I would really like to have autocompletion of words working when I type markdown.

**Comment by lsrdg** [comment]
Because of Vimwiki, I gave up about using `<tab>` for autocompletion, and just got used to `CTRL-n` and `CTRL-p`. I am way happier using Vimwiki than with autocompletion. :D 
But the "stealing" behavior got out of control after #345 ...

**Comment by hq6** [comment]
@dpc, Is this issue still reproducible against `dev` or `master`? If so, please give concrete steps for reproducing it.

**Comment by hq6** [comment]
I am closing this issue due to lack of response.

**Comment by elhenro** [comment]
i have this issue, with youcompleteme and vim 8.2.100

**Comment by ranebrown** [comment]
Vimwiki remaps tab for the `vimwiki` filetype for use with tables. You can disable that mapping with a new option (available on the `dev` branch) or create a new mapping that combines the vimwiki and completion mapping. I think the supertab plugin might be an easy way to go about that.

**Comment by yonathanF** [comment]
Any idea when this will be in master?

**Comment by MewtR** [comment]
Basically if you add `let g:vimwiki_key_mappings = { 'table_mappings': 0 }` to your config, your tab completion should come back if you have it setup elsewhere in your config.

**Comment by yebo29** [comment]
For anyone coming here from search, this also fixed Github Copilot integration via Vundle install of both vimwiki and Copilot.

**Comment by jrebs** [comment]
MewtR's suggestion also solved my problem where vimwiki+copilot was giving completion suggestions but not inserting them on tabs. I load my nvim plugins with Lazy in individual lua files, so for anyone looking to implement this fix in a similar setting, it looks like this for me (in `~/.config/nvim/lua/custom/plugins/vimwiki.lua`):

```lua
return {
  'vimwiki/vimwiki',
  init = function()
    vim.g.vimwiki_key_mappings = {
      table_mappings = 0, -- disable table mappings
    }
    -- plus whatever other config stuff you might have
  end,
}
```
