### ISSUE TITLE
Links vary during html export

### ISSUE THREAD

**Issue by lancosch** [vimwiki/vimwiki#354]
I don't know if it by design, but links vary depending on from which place you call VimwikiAll2HTML
Scenario:

index.wiki
diary/d01.wiki
diary/picture.png

If you want to link picture.png in both wiki pages in index.wiki [[local:diary/picture.png]] in d01.wiki [[local:picture.png]]

If you export both individually by Vimwiki2HTML you are OK. If you use VimwikiAll2HTML depending on which wiki you are editing during initiation that's going to be OK (and any other in that directory) the other will point to the wrong place.

VimwikiAll2HTML should behave as individually initiated Vimwiki2HTML calls.

ps: using file: for absolute path results the same problem.

**Comment by BehindTheBrain** [comment]
I just posted a patch fixing this: #997

**Comment by tinmarino** [comment]
Closing <= follow in #1139
