### ISSUE TITLE
Function to set a todo item as 'in progress'

### ISSUE THREAD

**Issue by orev** [vimwiki/vimwiki#355]
The todo item toggle (Ctrl-Space) only allows toggling between "not done" and "done" status.  I often like to keep track of things that are 'currently in progress'.  I usually use a `+` to indicate this inside the brackets, like `[+]`.  It would be useful if there was a function that could toggle this kind of status on todo items.  

The symbol could be defined in a similar way as `g:vimwiki_listsyms`.  I wouldn't expect this to update the "doneness" of the parent todo items.

**Comment by Nudin** [comment]
What is possible to do already:
You can specify as many intermediate states between "not done" and "done"  with g:vimwiki_listsyms and you can use gln/glp to toggle through all these status-symbols.

So the only thing still not possible from your request is having states that are different from the not-done-state but are considered not-done when calculating the parent status. Right?

**Comment by orev** [comment]
I was able to get this effect by calling :VimwikiIncrementListItem to start the item on the first state of doneness.  It does what I want in that it does also affect the parent showing it also has a status.

This is sufficient for me, so I will leave it up to you if you want to implement further to use a different state that does not affect the parent status.
