### ISSUE TITLE
How to make vimwiki works with UltilSnips?

### ISSUE THREAD

**Issue by icymind** [vimwiki/vimwiki#357]
OS: `OSX 10.11.6`
MacVim: 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  9 2017 10:07:21)
MacOS X (unix) version
Included patches: 1-596
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
```
vimwiki keymapping:
```
map <leader>wc <Plug>VimwikiToggleListItem
map <leader>wd <Plug>VimwikiMakeDiaryNote
map <leader>wg <Plug>VimwikiDiaryGenerateLinks
map <Leader>wD <Plug>VimwikiDeleteLink
map <Leader>wn <Plug>VimwikiNextLink
map <Leader>wp <Plug>VimwikiPrevLink
```
UltiSnips config:
```
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
```

YouCompleteMe config:
```
let g:ycm_key_list_select_completion = ['<c-j>', '<Down>']
let g:ycm_key_list_previous_completion = ['<c-k>', '<Up>']
let g:ycm_complete_in_comments = 1
let g:ycm_complete_in_strings = 1
let g:ycm_use_ultisnips_completer = 1
let g:ycm_collect_identifiers_from_comments_and_strings = 1
let g:ycm_collect_identifiers_from_tags_files = 1
let g:ycm_seed_identifiers_with_syntax=1
let g:ycm_goto_buffer_command = 'horizontal-split'
let g:ycm_filetype_blacklist = {
            \ 'notes': 1,
            \ 'help': 1,
            \ 'unite': 1,
            \ 'tagbar': 1,
            \ 'pandoc': 1,
            \ 'qf': 1,
            \ 'vimfiler': 1,
            \ 'infolog': 1,
            \ 'mail': 1
            \}
```
Before install vimwiki, Ultisnips works well in all kinds of filetypes. when I enter "ddate" in any file, press `<tab>` Ultisnips will expend "ddate" to current date.

but after install vimwiki, Ultisnips works well in other filetypes except vimwiki.  I tried change vimwiki filetype to markdown, but didn't help.

Any advice? Thanks

**Comment by stupidus89** [comment]
I am having the same issue. I think it is due to `<tab>` being mapped by vimwiki.
`:verbose map <tab>` gives the following:
```
n  <Tab>        @<Plug>VimwikiNextLink
        Last set from /usr/share/vim/vimfiles/ftplugin/vimwiki.vim
x  <Tab>       * :call UltiSnips#SaveLastVisualSelection()<CR>gvs
        Last set from ~/.config/nvim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim
s  <Tab>       * <Esc>:call UltiSnips#ExpandSnippet()<CR>
        Last set from ~/.config/nvim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim
n  <Tab>       * :cprev<CR>
        Last set from ~/.config/nvim/config/keys.vimrc
```
I worked around this by adding the following to `after/ftplugin/vimwiki`
```
vmap <F9> :call UltiSnips#SaveLastVisualSelection()<CR>gvs
imap <F9> <C-R>=UltiSnips#ExpandSnippet()<CR>
```
This allows me to use F9 as the ultisnips trigger for vimwiki. However, this is not the best solution and I would really like to be able to use `<tab>` for ultisnips in vimwiki.

**Comment by icymind** [comment]
@stupidus89 I dive into the source code and find something. There's some code:
```vim
 if g:vimwiki_table_mappings
   inoremap <expr> <buffer> <Tab> vimwiki#tbl#kbd_tab()
   inoremap <expr> <buffer> <S-Tab> vimwiki#tbl#kbd_shift_tab()
 endif
```

That means vimwiki will take over tab in insert mode. just put 
```vim
let g:vimwiki_table_mappins = 0
```
 to your vimrc.

Then you can:
- use tab to jump between vimwiki's link in `normal` mode;
- use tab to expend ultisnippet in `insert` mode.

**Comment by abair** [comment]
If you want to keep the vimwiki's table functionality, you can set your UltiSnips trigger to something other than <tab>:
```
let g:UltiSnipsExpandTrigger = <C-p>
```

**Comment by peterhoejlundandersen** [comment]
I've just tried the same thing. But it is not working. I have my custom snippets for VimWiki in a folder, and they are successfully called - i can se that by showing a list (ctrl-tab). 
But are not triggered bye <tab>. 
My `.vimrc`:

```
"=========== VIMWIKI 
"So it doesn't conflict with UltiSnips <tab>
nmap <leader><space> <Plug>VimwikiNextLink
nmap <leader>. <Plug>VimwikiPrevLink
" Conflict with the tab in source code: https://github.com/vimwiki/vimwiki/issues/357
let g:vimwiki_table_mappins = 0
let g:vimwiki_list = [{'path': '~/vimwiki',
  \ 'syntax': 'markdown', 'ext': '.md'}]
"=========== VIMWIKI END

"=========== ULTISNIPS
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
"=========== ULTISNIPS END
```

Any suggestions?

**Comment by stupidus89** [comment]
@peterhoejlundandersen There is a typo in your config. It should be `let g:vimwiki_table_mappings = 0`

**Comment by peterhoejlundandersen** [comment]
Thanks @stupidus89! It is working now.

**Comment by lpanebr** [comment]
I managed to fix my vimwiki ultisnippets by changing the vimwiki file extension to `.mdvimwiki` and registering it with @ranebrown the `UltisnipsAddFiletypes` tip. 

**I did not need** the `let g:vimwiki_table_mappings = 0`.

This is what I added to my vim.init:

```vim
autocmd FileType mdvimwiki UltiSnipsAddFiletypes vimwiki

" use my custom folder, markdown syntax and custom extension
let g:vimwiki_list = [{'path': '~/.config/mynotes/',
                    \ 'syntax': 'markdown', 'ext': '.mdvimwiki'}]
```

**Comment by MahbubAlam231** [comment]
@overcache There are plugins such as [supertab](https://github.com/ervandew/supertab) that works alongside UltiSnips' `tab`. Disabling `vimwiki_table_mappings` deactivates `tab` in tables altogether. Is there a way that `tab` can be used by both plugins, UltiSnips and vimwiki?

Your soluntion down here
-------------

> @stupidus89 I dive into the source code and find something. There's some code:
> 
> ```viml
>  if g:vimwiki_table_mappings
>    inoremap <expr> <buffer> <Tab> vimwiki#tbl#kbd_tab()
>    inoremap <expr> <buffer> <S-Tab> vimwiki#tbl#kbd_shift_tab()
>  endif
> ```
> 
> That means vimwiki will take over tab in insert mode. just put
> 
> ```viml
> let g:vimwiki_table_mappins = 0
> ```
> 
> to your vimrc.
> 
> Then you can:
> 
>     * use tab to jump between vimwiki's link in `normal` mode;
> 
>     * use tab to expend ultisnippet in `insert` mode.

**Comment by DragonL40** [comment]
Setting `let g:vimwiki_table_mappings = 0` did not work for me. Instead, I had to put `let g:vimwiki_key_mappings = { 'table_mappings': 0, }` in my init.vim. This disabled the table mapping that was overwriting my UltiSnips <tab> mapping and everything works fine.
My init.vim, for reference:
```vim
let g:vimwiki_global_ext = 0
let g:vimwiki_key_mappings = { 'table_mappings': 0, }
let g:vimwiki_list = [{
	\ 'path': '~/vimwiki',
	\ 'template_path': '~/vimwiki/templates/',
	\ 'template_default': 'default',
	\ 'syntax': 'markdown',
	\ 'ext': '.md',
	\ 'path_html': '~/vimwiki/site_html/',
	\ 'custom_wiki2html': 'vimwiki_markdown',
	\ 'template_ext': '.tpl'}]
```

**Comment by MahbubAlam231** [comment]
@DragonL40 What are your table mappings now?

There is a suggested (by tinmarino) solution [here](https://github.com/vimwiki/vimwiki/issues/1021#issuecomment-715925455) using a conditional, but I don't know how to write that code/make it work. Any ideas?

**Comment by tinmarino** [comment]
I have the in my ftplugin/vimwiki.vim

```vim
" Ultisnip
if exists('did_plugin_ultisnips')
  UltiSnipsAddFiletypes markdown
endif
```
to add the markdown filetype even if the filetype is vimwiki. Not sure that
helps.

Cheers.

**Comment by chenle02** [comment]
Thank you, this works for me!

> Setting `let g:vimwiki_table_mappings = 0` did not work for me. Instead, I had to put `let g:vimwiki_key_mappings = { 'table_mappings': 0, }` in my init.vim. This disabled the table mapping that was overwriting my UltiSnips mapping and everything works fine.
> My init.vim, for reference:
> 
> ```viml
> let g:vimwiki_global_ext = 0
> let g:vimwiki_key_mappings = { 'table_mappings': 0, }
> let g:vimwiki_list = [{
> 	\ 'path': '~/vimwiki',
> 	\ 'template_path': '~/vimwiki/templates/',
> 	\ 'template_default': 'default',
> 	\ 'syntax': 'markdown',
> 	\ 'ext': '.md',
> 	\ 'path_html': '~/vimwiki/site_html/',
> 	\ 'custom_wiki2html': 'vimwiki_markdown',
> 	\ 'template_ext': '.tpl'}]
> ```

**Comment by Nealium** [comment]
I just ran into this issue with `enter`, but I still want the Default VimWiki functions. *In my case: auto generated numbers in Lists*    
So I'll share my solution, because it's nice to have both, but it involves changing the source code. I'll do both `enter` and `tab` **ExpandTrigger** settings, I tested both.

#### General Idea
<pre>
1. See if UltilSnippet Exists (if `g:UltiSnipsExpandTrigger` is defined)
2. Manually check if Trigger is going to conflict.
    a. If so: Change the map to check if the pop-up is open    
          * Open: Do Snippet Things    
          * Closed: Do Default VimWiki Things    
    b. No Conflict: Default Map    
</pre>

### Tab (`<Tab>`)
* Open `ftplugin\vimwiki.vim`
* Search for: `kbd_tab`
* Replace Line with:
```vim
if exists("g:UltiSnipsExpandTrigger") && g:UltiSnipsExpandTrigger == "<Tab>"
    inoremap <expr> <silent><buffer> <Tab> pumvisible() ? "\<C-R>=UltiSnips#ExpandSnippet()<cr>" : vimwiki#tbl#kbd_tab()
else
    inoremap <expr><buffer> <Tab> vimwiki#tbl#kbd_tab()
endif
```
* **Note:** Won't work with Multi-Step Snippets, but it's a Table so rare-case you'd actually do that

### Enter (`<CR>`)
* Open `ftplugin\vimwiki.vim`
* Search for: `has('patch-7.3.489')`
* Replace contents of the **True** with:
```vim
if exists("g:UltiSnipsExpandTrigger") && g:UltiSnipsExpandTrigger == "<CR>"
    inoremap <expr> <silent><buffer> <CR> pumvisible() ? "\<C-R>=UltiSnips#ExpandSnippet()<cr>" : "<C-]><Esc>:VimwikiReturn 1 5<CR>"
else
    inoremap <silent><buffer> <CR> <C-]><Esc>:VimwikiReturn 1 5<CR>
endif
```
* **Note:** I presume it would also work in the `else` / without the patch, but recommend just updating in general

### Extra
* I Used: **Ultisnips e99fdf1** & **asyncomplete 9c76518**, but I presume YouCompleteMe also uses Pop-ups 
* You could also replace **both** `enter` & `tab` and this could potentially be added to source
