### ISSUE TITLE
Broken navigation with Tab/S-Tab in tables with empty cells

### ISSUE THREAD

**Issue by xeyownt** [vimwiki/vimwiki#362]
Using commit 4831384, and minimal `.vimrc`:

```
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'vimwiki/vimwiki'
call plug#end()
```

Create the following table

```
|   |   | X | X | X | X | X |   |   |
|   |   |   |   |   |   |   |   |   |
```
*  `gg`, `i` to start inserting at the beginning, then
*  press `Tab` multiple times until reaching next line. Watch that the cursor is at the wrong position (glued to `|`).
* Press `S-Tab` multiple times. Notice you can't get beyond last column on first line.

Apparently the problem occurs right after the first empty cell.

**Comment by ranebrown** [comment]
This seems to be fixed on the latest `dev` branch. If you still see this behavior using `dev` please reopen.

**Comment by xeyownt** [comment]
I confirm that the bug is fixed using `dev`.
