### ISSUE TITLE
vimwiki project still active?

### ISSUE THREAD

**Issue by maqiv** [vimwiki/vimwiki#363]
I know this is all voluntary work that is done here, especially by the project leader, so I really don't wanna be disrespectful at all. But there hasn't been any activity (merge pull requests, answer questions/issues, etc.) for more than two months.
So I just wanted to ask if this project is still actively maintained?

**Comment by EinfachToll** [comment]
Don't worry, Vimwiki is not forgotten. I had not much time in the recent past, but I'm planning to devote a little more in the future.

**Comment by maqiv** [comment]
Thank you very much! I really appreciate your work on that project!
