### ISSUE TITLE
Markdown or Vimwiki syntax?

### ISSUE THREAD

**Issue by ycpei** [vimwiki/vimwiki#364]
Hello fellow Vimwiki users,

What syntax do you use with the Vimwiki plugin? I normally use Vimwiki syntax but I'm considering moving to Markdown since it is more widely supported. Does the Vimwiki plugin support the Markdown syntax as much as the Vimwiki syntax? What type of Markdown does it support, Github flavored, Pandoc, commonMark or something else?

**Comment by standardeyre** [comment]
I have tried VimWiki syntax, MediaWiki syntax, and finally settled on Markdown syntax.  I wrote a [blog post][1] detailing my reasons.

While I write and edit in VimWiki, I have three different output formats in mind for my content.  I create an EPUB file, I update a MediaWiki site, and I build note cards using LaTeX files. Markdown syntax for VimWiki makes creating those output files with [Pandoc][2] much easier.

----
[1]: http://standardeyre.blogspot.ca/2017/06/markdown-all-way.html
[2]:https://pandoc.org/

**Comment by Nudin** [comment]
Maybe we should create a wikipage wit the pros and cons of the three syntaxes…

I personally prefer Vimwiki, since it's neare to mediawiki wich I'm used to from wikipedia and other wikis but does a few things better. There also is a pandoc reader for vimwiki now…

**Comment by ycpei** [comment]
@standardeyre Interesting blog post. I am curious how you use markdown in vimwiki. For example, how do you make wikilinks, i.e. equivalence of `[[link]]`?

@Nudin I agree it would be great if there is more documentation about how markdown in vimwiki...

**Comment by EinfachToll** [comment]
> Does the Vimwiki plugin support the Markdown syntax as much as the Vimwiki syntax?

IIRC especially the various variants of Markdown links are not fully supported. But we should really fix that, because from the bug reports (the only user feedback I receive ;) I see that many people are using Markdown.

> What type of Markdown does it support, Github flavored, Pandoc, commonMark or something else?

Here it gets tricky, because "support" mainly means that the syntax highlighting highlights the various items correctly. But using regular expressions we can't get everything right. For example, I checked the commonmark spec a few years ago and just the rules for using _ and * to emphasize text are too complex for regular expressions. So, the supported flavor is probably just one more added to the ton of already existing Markdown flavors.

**Comment by phansch** [comment]
Personally, I much prefer Markdown over anything else because otherwise I would have to constantly switch between Markdown/VimWiki. I use Markdown everywhere: on Github, for code documentation, for writing blog posts, writing end user documentation and in Vimwiki.
I have been really happy when I found out that Vimwiki supports Markdown, as that makes it my favorite note taking tool so far.

**Comment by copyme** [comment]
Maybe it would be a good idea to have a link in the documentation to this project: https://github.com/patrickdavey/vimwiki_markdown I used it and it does what I need.

**Comment by Nudin** [comment]
> Maybe it would be a good idea to have a link in the documentation to this project: https://github.com/patrickdavey/vimwiki_markdown I used it and it does what I need. 

For now I've added it to this list: https://github.com/vimwiki/vimwiki/wiki/Connected-Plugins The list is quite incomplete. Please add if you know other tools/plugins.

**Comment by derrickcope** [comment]
ruby gem gimli works well to convert .md files to pdf and supports custom css. 
Would be great to have .md to html and pdf by default. 
Is this in the works?

**Comment by cstsunfu** [comment]
please enhance markdown highlight.

**Comment by francium** [comment]
Improved markdown syntax highlighting would be nice.

**Comment by johnmarcampbell** [comment]
@cstsunfu and @francium, thanks for your comments! What sorts of things would you like to see about the syntax highlighting?

**Comment by francium** [comment]
I've only started using markdown syntax a day ago, but I've noticed I'm getting slightly odd behavior when I open arbitrary markdown files (not just the ones in the ~/vimwiki directory).

One the left is gvim and right is vim inside xfce4 terminal -- same file in both
![https://i.imgur.com/4pBwrDQ.png](https://i.imgur.com/4pBwrDQ.png)

I also can't force markdown syntax on markdown files anymore (which is mentioned in issue #60 as well).

**Comment by johnmarcampbell** [comment]
It sounds like syntax highlighting for markdown works fine when opening vimwiki files, but not for non-vimwiki markdown files. That latter is where you get this problem of different highlighting in different terminals. Is that correct?

If that's the case, then vimwiki is working fine. To my knowledge vimwiki doesn't try to impose any kind of highlighting on files outside of it's domain.

One thing you can try is `:so $VIMRUNTIME/syntax/hitest.vim`, which will show you what vim thinks all the highlight groups are supposed to look like. If those are different between gVim and terminal vim, it's most likely not a vimwiki problem and just a difficulty getting colors in general to display in xfce4 terminal.

**Comment by DancingQuanta** [comment]
Can vimwiki detect [plasticboy/vim-markdown](https://github.com/plasticboy/vim-markdown), [tpope/vim-markdown](https://github.com/tpope/vim-markdown), [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc) and use their syntax highlighting. This would avoid reinventing the wheel, though means needing dependencies. I like vimwiki's organisation more than its syntax.

**Comment by ErickChacon** [comment]
you can put this in your `nvim/init.vim` in order to use pandoc syntax highlighting:

```
au FileType vimwiki set syntax=pandoc
```

**Comment by jonathandion** [comment]
Any news?

**Comment by redapemusic35** [comment]
> you can put this in your `nvim/init.vim` in order to use pandoc syntax highlighting:
> 
> ```
> au FileType vimwiki set syntax=pandoc
> ```

I have just started using Vimwiki. I am writing in markdown and can convert to other files with vim-pandoc. however pandoc no longer recognizes my yaml fields and yaml syntax is not working either. Like @DancingQuanta I am also using  plasticboy/vim-markdown, tpope/vim-markdown, vim-pandoc. Where would I find
 ```au FileType vimwiki set syntax=pandoc``` ?

**Comment by DancingQuanta** [comment]
The configuration file for nvim could be found at `~/.config/nvim/init.vim`

**Comment by redapemusic35** [comment]
> The configuration file for nvim could be found at `~/.config/nvim/init.vim`

I should have mentioned that I am using macvim. Will this still work for me?

**Comment by DancingQuanta** [comment]
One way to find out is to run `:version` in vim command mode. This prints out the location of configuration files it expect to find in. Look for a line beginning with 'user vimrc file'.

Note that for ordinary vim, `init.vim` is really `~/.vimrc` and that nvim is NeoVim. I don't think there is a mac version of NeoVim so your macvim is ordinary vim and so work with `~/.vimrc`.

**Comment by redapemusic35** [comment]
Oh great thank you!

**Comment by redapemusic35** [comment]
> Oh great thank you!
> […](#)

Worked!

**Comment by redapemusic35** [comment]
I use the markdown syntax. I write papers for school in markdown and so this way I can take notes for class and write the paper in the same medium. I use [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc) to convert markdown into pdf, docx, html. I am also starting to toy around with the idea of using notes as posts for a blog that I am keeping.

**Comment by ranebrown** [comment]
Markdown is fairly well supported at this point. Any specific problems or enhancements should be opened as new issues.
