### ISSUE TITLE
Markdown section links

### ISSUE THREAD

**Issue by emKaroly** [vimwiki/vimwiki#367]
It is possible to jump to markdown section in same file?

[Section link](#linked-section)

## Linked Section

some text

**Comment by Nudin** [comment]
Yes, this works. Exaclty as you have done it. Do you have any issues with that?

**Comment by emKaroly** [comment]
It doesn't do anything

**Comment by Nudin** [comment]
So I have this test-file:
```
[to foo](#foo)
[to bar](#bar)
[to test](#test)

## foo

## bar

# test
```
When on `to foo` and press Enter, the cursor jumps to `## foo`, etc. Does this not work for you? If so, are you using latest dev-branch version? If it works but not in yiour code please share example code. Or do you mean something else?

**Comment by emKaroly** [comment]
Thank you. Your example works, mine doesn't. I read somewhere i should put only lowercase in link and replace whitespace with "-". But as i can see it should be the exact same string in link as it is in heading.

**Comment by matt-snider** [comment]
It would be nice if this was compatible with other common markdown flavours - e.g. [GitLab](https://docs.gitlab.com/ee/user/markdown.html#header-ids-and-links) and [GitHub](https://help.github.com/articles/basic-writing-and-formatting-syntax/#section-links).

Currently `# My header` can only be linked to properly with `[Some label](#My header)` (instead of `#my-header`)

**Comment by f-dj** [comment]
> It would be nice if this was compatible with other common markdown flavours - e.g. [GitLab](https://docs.gitlab.com/ee/user/markdown.html#header-ids-and-links) and [GitHub](https://help.github.com/articles/basic-writing-and-formatting-syntax/#section-links).
> 
> Currently `# My header` can only be linked to properly with `[Some label](#My header)` (instead of `#my-header`). Am I doing something wrong or is this a known issue/by design?

Yes, I am also very desperate for that feature! Made everything work for my use case by tweaking configs, writing custom converter scripts etc. This is the ONLY feature I can not get to work the way I want!!

**Comment by brennen** [comment]
In my testing, this works:

```markdown
A link to a later header in markdown using the lower-case-and-dashes style:

[test header](#a-test-header)

### a test header
```

Hitting enter on the `test header` link jumps to `### a test header`.  If this isn't working, can you paste the output of `:VimwikiShowVersion`? It may only be on the `dev` branch.

**Comment by brennen** [comment]
> I have Stable version: 2.5. Do you suggest using dev version?

Yes. We haven't done a release in quite a while; the dev version contains a large number of fixes and enhancements since then. See #1235.

**Comment by DannyDannyDanny** [comment]
I hope to see vimwiki go forward with #1235. I'll hop to `dev` for now! Cheers @brennen and thanks for your effort!
