### ISSUE TITLE
Is it possible to embed HTML code into .wiki file?

### ISSUE THREAD

**Issue by rupc** [vimwiki/vimwiki#368]
Hi, I want to embed pure HTML code into my wiki files. But I can't find how to do except for modifying converted HTML files. Is there any convenient way to do that?

**Comment by johnmarcampbell** [comment]
Certain html tags are already ignored by `:vimwiki2HTML` (<i>, <br>, etc.), so you can write those directly into your wiki files and it will work fine. If you want to add more tags, check out `:h vimwiki_valid_html_tags`.

**Comment by ranebrown** [comment]
If the above answer doesn't resolve your question please reopen.

**Comment by tinmarino** [comment]
> New to GitHub; please let me know if there's a better way to bring this issue up than commenting on this old thread

You did well to comment the old thread

I often advice to use a specific html generation program like [pandoc](https://pandoc.org/): well supported, many file types ...

Maybe this pull request  #778 can solve your issue with some verbatim html :

```text
%plainhtml <div style="text-align: center;">
My normal vimwiki paragraph that will be centered when viewed with html browser.
%plainhtml </div>
```

**Comment by apreynolds** [comment]
Wonderful, thanks. The plainhtml tag works perfectly.
