### ISSUE TITLE
Ignore link starting with '#'

### ISSUE THREAD

**Issue by detergen** [vimwiki/vimwiki#370]
vimwiki won't follow links starting with # 
fe click on  [[#435 Lockal link]] ignoring. In previous versions (~2012) was ok.

**Comment by EinfachToll** [comment]
Well, in the last five years, some things have changed, notably that you can link to a specific place in a file (i.e. anchors): `[[file#anchor]]`. A link starting with a '#' is a shortcut for a link to another place in the same file the link is in.
This means basically that you can't have wiki files with a '#' in their names anymore. Sorry for the inconvenience, but in every system like Markdown or Vimwiki where you use ASCII characters for markup, you have to make compromises.
