### ISSUE TITLE
Change what editor vimwiki uses to open files?

### ISSUE THREAD

**Issue by Vitruvia** [vimwiki/vimwiki#371]
I'm currently on Ubuntu and I always open my files using neovim. However, it seems ubuntu has gedit as standard editor and that has been a pain to change. 

Gedit only pops up when I try to open files from other links (like when vimwiki links to a file in my computer), so I was wondering if there is a way to change what editor vimwiki uses.

**Comment by EinfachToll** [comment]
Do you mean the editor which opens when you press Enter on a link like `[[file:bla.txt]]`? On Linux, Vimwiki calls `xdg-open bla.txt`. The program `xdg-open` is usually available in the popular distributions. But how you configure it which editor to use for .txt files, for example, I can't say, you have to google that yourself.

**Comment by Vitruvia** [comment]
Thanks! The solution I found was to  get the .desktop file from the neovim repo and then right click the file I wanted to open and choose "Open With" then look for neovim and set it as default.
