### ISSUE TITLE
Creating more than 1 diary entry per day

### ISSUE THREAD

**Issue by Vitruvia** [vimwiki/vimwiki#379]
I know diaries are usually meant to be separated by day, but I actually used them as a "quick note feature". These notes are often unrelated to one another, and one I get multiple unrelated notes on a day, my entry for that day can get pretty clogged. 

I thought it might be good if we could create these quick notes on the fly, maybe it would be good to have an option to allow multiple entries per day or maybe it could be possible to create a new feature called quicknotes. What do you think?

**Comment by louwers** [comment]
You can change `diary_link_fmt` to also include the time ([see here](https://github.com/vimwiki/vimwiki/blob/d5df4c7726d2242d8dd8f855a88b2d6d1297428c/plugin/vimwiki.vim#L353)) but that is not supported yet.

**Comment by louwers** [comment]
You can change it like this (for example):

```
let g:vimwiki_list = [{'diary_link_fmt': '%Y-%m-%d_%X'}]
```
It seems to work fine, but it's not a documented feature (I'm not sure why, I hope we can clarification on that). Let us know if you run into problems.

**Comment by Vitruvia** [comment]
Thanks! This configuration works well for generating a new diary note every time I press `<leader>\w<leader>\w`, but when I try to save the buffer via `:w` I get "Can't open file for writing". I wonder what is wrong.

**Comment by louwers** [comment]
You are probably on a system that doesn't allow the use of a colon in the filename. Choose a different date format, which by the way isn't portable (see `:h strftime`). You could try `%Y-%m-%d_%H_%M`.

**Comment by Vitruvia** [comment]
Thank you very much.
I chose a `%Y-%m-%d_%Hh$Mm` which gives something like `12h14m48s`. This feature is really nice, too bad it isn't portable. It would be nice to have a feature where each note created is counted and then you get something like: `2017-08-19-note_1` then `note_2` and so on. But this solves it for me right now, so thanks again!

**Comment by andmis** [comment]
Could we reopen this, since AFAICT there isn't a simple way of doing this anymore without editing the plugin code?
