### ISSUE TITLE
Remove recommendation to use MathJax CDN

### ISSUE THREAD

**Issue by louwers** [vimwiki/vimwiki#381]
https://github.com/vimwiki/vimwiki/blob/dev/doc/vimwiki.txt#L1239

The MathJax CDN [already shut down officially](https://www.mathjax.org/cdn-shutting-down/), so the recommendation to use it should be removed.

This CDN can be recommended instead: https://cdnjs.com/libraries/mathjax. Alternatively, the recommendation to use a CDN can be removed altogether.

**Comment by Nudin** [comment]
Fixed in https://github.com/vimwiki/vimwiki/commit/3cbc5:
I added recommendation for using local version and updated the url to cdnjs.
