### ISSUE TITLE
Don't show error when cancelling link rename

### ISSUE THREAD

**Issue by louwers** [vimwiki/vimwiki#383]
When cancelling renaming a link using escape or C-g, an error is shown ("[Vimwiki Error: Cannot rename to an empty filename!"](https://github.com/vimwiki/vimwiki/blob/e4fe5ce09d7cfdf336cdef61394296768d79cf6d/autoload/vimwiki/base.vim#L1395). Cancelling is not an error, so it should not be shown in this case.

Steps to reproduce:

1. Open link
2. `:VimwikiRenameLink`, y
3. (optional) type some text
4. press escape or C-g

Expected behavior:

No error, rename cancelled

Actual behavior:

Error, rename cancelled

**Comment by Nudin** [comment]
There is no way in vim to distinguish if the user entered an empty filename or if he canceled with <Esc> or C-c. So the only option would be to remove the error message completely.

**Comment by ranebrown** [comment]
From my testing `C-c` cancels out without an error message. I don't think we want to completely remove the error message so I'm closing this.
