### ISSUE TITLE
Wiki Links not working | Syntax highlighting disabled | Error since Vimwiki update

### ISSUE THREAD

**Issue by hersh-verthun** [vimwiki/vimwiki#387]
I use [vim-plug](https://github.com/junegunn/vim-plug) to manage vim plugins. Ever since I ran the `:PlugUpdate` command to update the plugins today whenever I try to go to my index wiki I encounter several errors. The first one reads:

> Error detected while processing function <SNR>92_highlight_existing_links[11]..vimwiki#base#apply_template:
line 3

It also gives me another error
> E15: Invalid expression:

I ignore the errors to keep working but vimwiki markup is no more highlighted and the wiki links sometimes work and sometimes don't.

Please help.

**Comment by jarvist** [comment]
I had to roll all the way back to v2.2 to fix these errors. I'm not sure whether other bits of my vim setup are too old, and I don't really have time to triage what was going on beyond getting it working again!

`git checkout 2f95a6a`

Was the required command in the relevant directory for me (~/.vim/bundle/vimwiki/).

**Comment by johnmarcampbell** [comment]
@hersh-verthun Are you still having this problem? I was unable to recreate it. Can you try using vimwiki with your other plugins disabled?

**Comment by johnmarcampbell** [comment]
Closing this, due to going ~9 days without getting any info. We can reopen if this info is provided.

**Comment by hersh-verthun** [comment]
I am sorry for replying late. I have been moving my data away from Vimwiki into Org-Mode for the past few weeks. When vimwiki broke for me I started looking at alternatives. I know its a community-effort but I couldn't find help in community so switched.

**Comment by johnmarcampbell** [comment]
That's completely understandable. @EinfachToll has put some more people on the project recently (me and @Nudin), and we're working through the backlog of Issues and Pull Requests.

If you're happy with Org-Mode, no worries. But if you'd like to keep troubleshooting this problem, could you: 
1) Make sure you have the latest version from the *dev* branch (`Plug 'vimwiki/vimwiki', {'branch','dev'}`
2) See if the problem persists with other plugins disabled

and we'll see if we can figure it out.
