### ISSUE TITLE
Vimwiki shortcut ?

### ISSUE THREAD

**Issue by guakamole** [vimwiki/vimwiki#388]
Hello,

Thank you for vimwiki :+1: 

Is there a way to invoke vimwiki other than having to start vim and then do a <leader>ww?

**Comment by Nudin** [comment]
Doing ww is basically a shortcut to open the file you use as the mainpage of your wiki. So, yes – You can for example start vim with the path to your wiki page:
`$ vim ~/vimwiki/index.wiki`

If you are using Linux you can add something like
`alias vimwiki='vim ~/vimwiki/index.wiki'`
to your bashrc. Or you can create a desktop-icon starting vim with the given file…

[Edit path to whatever you have configured…]

**Comment by firmart** [comment]
You could also add an alias like 
`alias vw='vim -c VimwikiIndex'`
which is more portable.

**Comment by guakamole** [comment]
Thank you for your answers :) :kissing_cat:
