### ISSUE TITLE
"sourcing" or including external text or vimwiki markup

### ISSUE THREAD

**Issue by Isaac-Kleinman** [vimwiki/vimwiki#39]
Feature suggestion: 
When I write documentation, I often include code snippets that I have in other files. Pasting the code directly into my page makes it somewhat ugly. It would be great if I can do something like:
`source myExternalFile.c` or `source myExternalPage.wiki`

**Comment by MartyLake** [comment]
It seems that this snippet should now be:

```
function! VimwikiWikiIncludeHandler(value) "{{{
    let str = a:value

    let url_0 = matchstr(str, g:vimwiki_global_vars.rxWikiInclMatchUrl)
    if filereadable(url_0)
        return '<pre>'.join(readfile(url_0), "\r").'</pre>'
    end

    " Return the empty string when unable to process link
    return ''
endfunction "}}}

```
