### ISSUE TITLE
Create a unique wiki for each project

### ISSUE THREAD

**Issue by CodingJonas** [vimwiki/vimwiki#397]
vimwiki looks great!
I read through the help file, but couldn't really figure out a way to create a unique wiki for each project.
Is there a way to open the same wiki whenever I'm editing a file in a certain directory or its subdirectories?

**Comment by johnmarcampbell** [comment]
Check out ```:help g:vimwiki_list``` for directions on registering different wiki's with vimwiki. Once you've registered different wiki's (one for each project, or however you want to organize them), you can switch between them with ```:vimwikiUISelect```.

**Comment by psiho** [comment]
Sorry for bumping this old post up, but failed to find an answer so wrote a small script to do it. It might be helpful for others that want similar functionality... https://dev.to/psiho/vimwiki-how-to-automate-wikis-per-project-folder-neovim-3k72

**Comment by luator** [comment]
@psiho Thanks a lot!  It is great if you are looking for a solution to some problem and find that someone just posted one a few days ago :)

I think it would be a great enhancement for vimwiki to add a functionality similar to this (i.e. to open a wiki from the current working directory without the need to explicitly add it to the config).

**Comment by psiho** [comment]
> I think it would be a great enhancement for vimwiki to add a functionality similar to this (i.e. to open a wiki from the current working directory without the need to explicitly add it to the config).
I guess we have similar workflows. Becase just days after posting I also realized I need quick open of the Wiki, related to current file, even without the menu. So I added this to my script:
```
function _G.ProjectWikiOpenCurrent(external)
	local wikifolder = vim.api.nvim_call_function("systemlist", {"find ./{'',../'',../../'',../../../'',} -maxdepth 1 -name "..config.rootWikiFolder})
	if wikifolder[1] then
		local path = wikifolder[1] .. '/index' .. config.wikiConfig.ext
		if external then
			vim.api.nvim_command(':silent exec ":!~/scripts/wiki.sh '..path..'"')
		else
			vim.api.nvim_command(':e '..path)
		end
	else
		print("no Wiki found here")
	end
end


-- add commands
vim.api.nvim_command([[command! -nargs=? ProjectWikiOpen lua ProjectWikiOpen(<f-args>)]])
```
... and now you have a new command. Just do a keybinding of your choice.
Note `external` parameter and shell script if `external=true`. That's just a little extra to open WIki in separate window (terminal).  I use Kitty and tiling window manager so I bascally open borderless, centered, floating Wiki window (in Goyo mode). This is a really fast way to open, write not, close, without interfering with the project files.

So my wiki.sh is simple:
```
#!/bin/sh
kitty --class=vimwiki --title="Wiki" nvim $1 "+:Goyo 82" &
```
... and window special styling is in my tiling window config which is out of the scope of VimWiki :)
