### ISSUE TITLE
Add ability to diagram in vimwiki

### ISSUE THREAD

**Issue by imbilltucker** [vimwiki/vimwiki#398]
ditaa is a commandline tool to convert ascii art to diagrams, q.v.   http://ditaa.sourceforge.net/

Could vimwiki support adding diagrams from a ditaa format ascii art to make diagrams when converting to html via the Vimwiki2HTML command?

**Comment by cjbarroso** [comment]
Im adding another idea: support for the [DOT language](https://en.wikipedia.org/wiki/DOT_(graph_description_language)). Im aware that it may not be the use case you are looking for, but it may prove useful to you.

**Comment by xkpd3** [comment]
I'm also interested in diagrams one way or the other.

Both could be supported (and more) if it would be possible to pass parts of the document through an external command that returns an image.

**Comment by hq6** [comment]
I would not be opposed to this idea, but likely do not have the bandwidth to implement it currently.

**Comment by ranebrown** [comment]
I think it makes more sense to use a different plugin or external tool for this functionality. Here are a few options:
- https://github.com/wannesm/wmgraphviz.vim
- https://github.com/gyim/vim-boxdraw
- https://www.vim.org/scripts/script.php?script_id=40

**Comment by imbilltucker** [comment]
Here is a link with plantuml using ditaa:  http://plantuml.com/ditaa
Maybe plantuml itself would be a viable alternative?

I'm not that attached to ditaa.  But I would like to see ascii graphs, because text seems the most durable format.   And, I would like to have the option for making them pretty by translating them into an image.

Dot (graphviz) has some merit, but it can be hard to see, interpret the graphs without rendering the dot code.  I imagine that the vimwiki community might want both.

I'm adding this comment to document the existence of plantuml for any future effort to provide graphing capabilities for vimwiki.

**Comment by tinmarino** [comment]
**Closing**: I will not maintain the html convertion, user contribution does but will not improve it.

Dot and aidagram are external programs => up to the user to plug them in its custom conversion script.

**Comment by wanghuibin0** [comment]
> **Closing**: I will not maintain the html convertion, user contribution does but will not improve it.
> 
> Dot and aidagram are external programs => up to the user to plug them in its custom conversion script.

bad news.
