### ISSUE TITLE
URL's and other wiki links not highlighted or underlined

### ISSUE THREAD

**Issue by RainbowSwirls** [vimwiki/vimwiki#400]
I just started with vimwiki but already ran into an issue where vimwiki won't highlight URL's or other wiki links. The brackets for the wiki links do disappear when the cursor is on a different line and all the functionality works as far as I can tell (URL's open the page in the browser and wiki links open the wiki file). I've tried reading the documentation but didn't find anything related to this. If anybody can help me get the links to look like the screenshots on the GitHub README page that would be great. Here's a screenshot:

![screen shot 2017-10-08 at 3 16 35 am](https://user-images.githubusercontent.com/25623715/31315514-57b8e976-abd7-11e7-8d7c-943b2ac93764.png)

Already tried:
set nocompatible
filetype plugin on
syntax on

EDIT:
Another thing I forgot to mention. Checkbox list items do not get greyed out when marked with the X.

**Comment by johnmarcampbell** [comment]
Have you customized any syntax highlighting options anywhere in your vim config? You can run ```:so $VIMRUNTIME/syntax/hitest.vim``` to see all your highlighting options. Scroll down to the ```Underlined``` option to see if it is actually underlined.
1) If it *is* underlined, that probably means for some reason wiki links aren't using the ```Underlined``` highlight group
2) If it *isn't* underlined, that probably means that vim has changed the highlighting options for the ```Underlined``` highlight group

**Comment by johnmarcampbell** [comment]
You can check out ```:help g:vimwiki_hl_cb_checked``` for help on your checkbox highlighting issue

**Comment by RainbowSwirls** [comment]
The Underlined option wasn't underlined in my hitest.vim, so after switching to another colorscheme I noticed the issue was only present in my colorscheme. I'm using a colorscheme called one dark which apparently didn't set any highlight settings for the Underlined option.  After setting gui=underline and guifg=blue for the Underlined option, I got the expected behaviour.

Thanks for the help!

**Comment by nikinbaidarr** [comment]
Try :syntax enable
