### ISSUE TITLE
Font effects in tables

### ISSUE THREAD

**Issue by marza91** [vimwiki/vimwiki#404]
Hi,

I've just started using tables in vimwiki and discovered that when trying to create bold headers the star characters won't disappear when moving the cursor to another line. As an example I tried with all the different typefaces from the help page:

```
*bold text*
_italic text_
~~strikeout text~~
`code (no syntax) text`
super^script^
sub,,script,,

| *bold header*  | _italic text_ | ~~strikeout~~ | `code (no syntax) text` | super^script^ | sub,,script,, |
|----------------|---------------|---------------|-------------------------|---------------|---------------|
| This is a text | Hello there   | test          |                         |               |               |

```

It ends up looking like this:
![2017_10_26_09_22_51](https://user-images.githubusercontent.com/1224973/32039954-56700a20-ba2f-11e7-9c3b-aabcf1cf6725.png)

The bold text actually appears bold and the other effects are applied, but the only item actually removing special characters is the strikeout, but that in turn makes the column alignment go wonky. When focusing on the header line, the columns align again:
![2017_10_26_09_23_07](https://user-images.githubusercontent.com/1224973/32039961-5b8e7212-ba2f-11e7-99ae-142f09b3956b.png)

Not a big problem for me at all, just thought I'd mention my findings 😄 The biggest irritation is probably the strikeout messing with collumn alignmet, but I personally only ever use the bold effect.

**Comment by EinfachToll** [comment]
Yes, the characters for the strikethrough normally should also not be hidden in table headers.
