### ISSUE TITLE
Renaming file does not work for markdown syntax

### ISSUE THREAD

**Issue by yangkev** [vimwiki/vimwiki#406]
When I create a link by pressing `<CR>`, and then follow that link, if I change the name of the file with `<leader>wr`, the index file's link does not get updated.

Info:
- Using Markdown

**Comment by EinfachToll** [comment]
I allowed myself to change the title. Looks like renaming doesn't work at all for markdown syntax.

**Comment by Nudin** [comment]
Can you check with latest version from dev-branch is the problem still exist? I just fixed #550 and this could be the same bug.

**Comment by Nudin** [comment]
Fixed one more bug and tested it, seems to work now!?

**Comment by ranebrown** [comment]
@yangkev This should be fixed. If you are still having issues pease reopen.

**Comment by ranebrown** [comment]
This actually still seems to be an issue but lets track it in the other duplicate issue.

@Nudin Can you take a look at this since it is something you worked on in the past?
