### ISSUE TITLE
Fenced code block in list breaks list in Markdown

### ISSUE THREAD

**Issue by yangkev** [vimwiki/vimwiki#407]
````
- Item 1
- Item 2
   ```
   echo "hello world"
   ```
- Item 3
````

In the above, `Item 3` is no longer connected to the list containing `Item 1` and `Item 2`. So renumbering the list/changing list style no longer works.

**Comment by EinfachToll** [comment]
Interestingly, the equivalent in the vimwiki default syntax works. Hm.

**Comment by simias** [comment]
Just stumbled upon this myself, still a problem with the latest dev version https://github.com/vimwiki/vimwiki/commit/0c561e53414707544d3ffcb38301eb2b30c49493

**Comment by simias** [comment]
I should add that both github and pandoc are happy with the markdown so I think it's vimwiki's compatibility that's at fault:

```md
* [ ] Test
    + [ ] Foo
    ```c
    printf("Hello, World\n")
    ```
    + [ ] Bar
    + [ ] Baz
```
Shows:

* [ ] Test
    + [ ] Foo
    ```c
    printf("Hello, World\n")
    ```
    + [ ] Bar
    + [ ] Baz
