### ISSUE TITLE
Please add external file support

### ISSUE THREAD

**Issue by raingo** [vimwiki/vimwiki#42]
In version 1.2, there is a configuration option 

```
g:vimwiki_file_exts
```

in order to support external files, such as pdf and docx.

However, it becomes extremely difficult to make external files work in the new version. I end up scripting an ugly `VimwikiWikiIncludeHandler`

Basically, file extension specific behaviors should come back.

**Comment by ranebrown** [comment]
This seems to be fixed with the `file:` or `local:` scheme. @raingo Does this address your problem?
