### ISSUE TITLE
vimwiki_+ is bugged: doesn't create multi-word links

### ISSUE THREAD

**Issue by AbsurdMagpieScrutinies** [vimwiki/vimwiki#421]
*If there is a multi word text fragment:*

aaa bbb ccc

*that a vimwiki user wants to turn into a vimwiki link, then that user may highlight the words:*

**aaa bbb ccc**

*and type CTRL-+*     *and*
 
[aaa bbb ccc]]

*results, which is not a vimwiki link.*

**Comment by Nudin** [comment]
I ether don't understand you correctly or can't reproduce.

- Why are you using `CTRL-+?? Is that a custom mapping? Defaultmapping are `+` and `Enter`.
- What do you mean with highlight? Do you mean visual selection?
- With format are you using?
- Are you using newest version?

**Comment by AbsurdMagpieScrutinies** [comment]
> Why  are you using CTRL-+?? Is that a custom mapping? Defaultmapping are+andEnter`.

User Error. I somehow incorrectly taught myself that it was CTRL-+.  Just "+" is correct and works fine. 

Closing.
