### ISSUE TITLE
Tags in the header

### ISSUE THREAD

**Issue by teranex** [vimwiki/vimwiki#424]
I know it is possible to tag a section by adding a tag right below the heading, but is there any reason why a tag inside a header is not recognized?

This for example works
```md
# My header
:test:
* foo
* bar
```

But when adding the tag inside the header, it is not recognized by vimwiki:

```md
# My header :test:
* foo
* bar
```

The reason i'd like to be able to do this is because
* the second case is a bit more compact
* The first case is invalid Markdown. Which is not really important when only using Vimwiki, but when exporting through Pandoc the first example is invalid and would require an additional blank line before the bullet-list (making it even less compact).

**Comment by hq6** [comment]
@teranex , Can you be more specific about what behavior is missing when a tag is not recognized? For example, is it the syntax highlighting, the ability to link to it, or something else?

**Comment by ranebrown** [comment]
@teranex It has to do with the regex patterns used and the fact that headers are also used for anchors that you can link to. Does pandoc recognize the vimwiki style tags and create links to them?

**Comment by hq6** [comment]
@ranebrown Feel free to take over this one, since it seems you have a more clear idea of the desired behavior.

**Comment by teranex** [comment]
@hq6 It's both actually. The syntax is not recognized in headers, and they are also not added to the tags file, so you can't just to them.

@ranebrown I don't think Pandoc recognizes vimwiki tag syntax.

An important note is that I'm using Markdown syntax in Vimwiki, so it might be specific to that.

**Comment by ranebrown** [comment]
I don't think this is something we will change since tags work by adding a couple of blank lines and you can link directly to a header with `[Description](Page#Header title)`
