### ISSUE TITLE
if !hasmapto VimwikiTableAlign{W,Q}

### ISSUE THREAD

**Issue by sharethewisdom** [vimwiki/vimwiki#425]
I'd like to use **vim-sentencewrap**'s mapping `gw` which breaks only at punctuation marks .;:?! in a vimwiki file

but vimwiki remaps it regardless of what I have in `my/ftplugin/vimwiki.vim`.

https://github.com/vimwiki/vimwiki/blob/dev/ftplugin/vimwiki.vim#L612
```vim
nnoremap <buffer> gqq :VimwikiTableAlignQ<CR>
nnoremap <buffer> gww :VimwikiTableAlignW<CR>
```

why is this not enclosed in an if statement?

**Comment by ranebrown** [comment]
@sharethewisdom can you try the latest `dev` branch to see if the change I pushed fixed this for you? If you have an alternative mapping for `gqq` or `gww` it shouldn't be overwritten.

**Comment by sharethewisdom** [comment]
thanks. It's still mapping `gw*` though, which forces users to overwrite the mapping in `after/vimwiki.vim` in order for them not to have to wait `timeoutlen`. I'm not sure what good practice is for a ftplugin, but I think is would be fine to leave it to the user to configure mappings.

I have a particular setup with [wiki.vim](https://github.com/lervag/wiki.vim) now. I can't easily test this and I'm quite busy at the moment.

**Comment by hq6** [comment]
@sharethewisdom , Please try the new `g:vimwiki_key_mappings` introduced in #686 to see if it fixes this issue. That is pull `dev` and then put the following in your `.vimrc`.

```
  let g:vimwiki_key_mappings =
    \ {
    \   'table_format': 0,
    \ }
```

**Comment by sharethewisdom** [comment]
hmm I'm not sure what's going on yet

from test.txt

```
:verbose set ft?
  filetype=text
        Last set from /usr/share/nvim/runtime/filetype.vim
:echo g:vimwiki_key_mappings
{'table_format': 0, 'headers': 1, 'lists': 1, 'global': 1, 'links': 1, 'all_maps': 1, 'text_objs':  1, 'mouse': 0, 'table_mappings': 1, 'html': 1}
:verbose nmap gw
n  gwgw         @gww
        Last set from ~/.local/share/nvim/site/pack/github/start/sentencewrap/plugin/sentencewrap.vim                                                                                     
n  gww          @'gw' . v:count1 . '<SNR>98_(underline)'
        Last set from ~/.local/share/nvim/site/pack/github/start/sentencewrap/plugin/sentencewrap.vim
n  gw          *@:<C-U>set opfunc=sentencewrap#format<CR>g@
        Last set from ~/.local/share/nvim/site/pack/github/start/sentencewrap/plugin/sentencewrap.vim
```

from test.wiki

```
:verbose set ft?
  filetype=vimwiki
        Last set from ~/.local/share/nvim/site/pack/github/start/vimwiki/plugin/vimwiki.vim
:echo g:vimwiki_key_mappings
{'table_format': 0}
:verbose nmap gw
No mapping found
```

**Comment by hq6** [comment]
It looks almost like `sentencewrap` is not doing the mapping because the filetype is `wiki`. Does that plugin have a setting for list of filetypes that it works on?

**Comment by ranebrown** [comment]
Seems to work fine for me as long as spelling is enabled (`:set spell`) which seems to be a [requirement]( https://github.com/Konfekt/vim-sentencewrap/blob/09fcd87a7ad524dd827581ef0db94aec8d3d0b41/plugin/sentencewrap.vim#L4-L6) of sentencewrap.

**Comment by sharethewisdom** [comment]
@ranebrown  ok thanks you're right. I used `ftplugin/wiki.vim` to set `spell`.

**Comment by ranebrown** [comment]
No problem. I would recommend putting `set spell` in your `.vimrc`. If you only want it active for certain filetypes you could use an autocommand. Glad it is working:)

(Also make sure to pull the latest `dev` branch because there was a bug with the keymappings that I fixed. )
