### ISSUE TITLE
how input: `

### ISSUE THREAD

**Issue by youanan** [vimwiki/vimwiki#429]
: Ctrl + `

`Ctrl` + ```  is not right~

**Comment by johnmarcampbell** [comment]
I'm sorry, I'm not sure what you're trying to do. Could you give an example?

**Comment by youanan** [comment]
I want to enter (`), the brackets in the symbol, surrounded by` `, the source code would be: <code>` <code>

**Comment by youanan** [comment]
<code>` <code>

**Comment by youanan** [comment]
<c0de>` </c0de>……0 is o

**Comment by youanan** [comment]
*bold*

**Comment by Nudin** [comment]
I'm sorry but I still don't understand you.
