### ISSUE TITLE
Can I disable "syntax=vimwiki"

### ISSUE THREAD

**Issue by DougBeney** [vimwiki/vimwiki#431]
Having a great time with this plugin.

However, I'm currently looking for a way to use default markdown syntax rather than vimwiki markdown syntax.

I currently have the following line to enable functionality with markdown files:

`let g:vimwiki_ext2syntax = {'.md': 'markdown'}`

Is there any way to do this? I tried to add this line to automatically switch the syntax for markdown files, but vimwiki overwrote it:

`au BufReadPost,BufNewFile *.md set syntax=markdown`

Thanks.

**Comment by samiralajmovic** [comment]
Have you tried setting the filetype?

```
autocmd BufEnter,BufRead,BufNewFile *.md set filetype=markdown
```

**Comment by DougBeney** [comment]
Thanks @samiralajmovic! Worked perfectly.
