### ISSUE TITLE
Is it possible to shorten a raw link with a description?

### ISSUE THREAD

**Issue by marcelodeleon** [vimwiki/vimwiki#432]
Whenever adding a raw link into a vimwiki page, the link is functional by default. Even though the link is shortened by vimwiki (automatically), is it possible to select the way we want the link to show on the page and have the url mapped? Like it is done in markdown.

Something like:
[link-description][http://example.com]

**Comment by Nudin** [comment]
Hey,
is `[[http://example.com|Text]]` what you want?

**Comment by marcelodeleon** [comment]
Yes, that's exactly it! I did not find an example like that in the documentation so I wasn't sure how to do it. Thanks!
