### ISSUE TITLE
Vimwiki .wiki format switches to markdown formatting after opening a markdown file 

### ISSUE THREAD

**Issue by DougBeney** [vimwiki/vimwiki#433]
Here's my configuration line:
`let g:vimwiki_ext2syntax = {'.md': 'markdown', '.wiki': 'media'}`

So, let's say you have `notes.wiki` loaded up. Everything is working fine. When you press `=` on a line, it increases the heading properly.

```mediawiki
== My Heading ==
```

Now, in a new tab, you open up `somefile.md`. You make your edits, close it, and return to your `notes.wiki` buffer.

**When you try to use `=` or `-` to increase/decrease the heading, it adds markdown syntax.**

Ex.

```mediawiki
# == My Heading ==
```

**Comment by hq6** [comment]
I cannot reproduce this on either `master` or `dev`.

Are you still able to reproduce this?

**Comment by hq6** [comment]
Closing due to lack of response. Feel free to reopen if you can reproduce this again.
