### ISSUE TITLE
Add thunderlink to web_schemes2

### ISSUE THREAD

**Issue by kaiec** [vimwiki/vimwiki#435]
I really like thunderlink (https://addons.mozilla.org/de/thunderbird/addon/thunderlink/) to link to emails from within a wiki. If you simply add the thunderlink scheme to the webschemes, it works out of the box by hitting enter on a thunderlink, just like every other URL.

I tested it by adding it to this line:

https://github.com/vimwiki/vimwiki/blob/75fe1d4f003f77a33955f436e023a4ce9548cb69/plugin/vimwiki.vim#L414

**Comment by Nudin** [comment]
Seems fine, can you create a PR?

**Comment by tinmarino** [comment]
Closing <= done
