### ISSUE TITLE
How to efficiently enter links to files?

### ISSUE THREAD

**Issue by nirgivon** [vimwiki/vimwiki#437]
Hi!

Not an issue but a question,

Using window/gvim, is there an effective way to add links to files?
instead of manually typing c:/Blahh/Blahh/ Blahh...

I have bean digging around, mabe using NEARDTree, in NEARDTree you can use the "m" menu and "l' (list) but i couldent fine any way to use that in Vim/Vimwiki.

Thanks!

**Comment by EinfachToll** [comment]
You can always use Vim's built-in path completion with Ctrl+x Ctrl+f (see `:h compl-filename`). Doesn't work well if the path contains spaces, though (maybe adding a space to 'isfname' helps, but I didn't try that).

**Comment by EinfachToll** [comment]
I don't understand your question. What do you expect? What do you want to achieve?

**Comment by nirgivon** [comment]
Say I am maintaining a Wiki for a project I am building.
I can have detailed descriptions, tables, links to websites with relevant information...

Now I have a Data sheet on my PC, and I want to point to that Data sheet.
I would like to have a link to a file that is not a source file.

**Comment by EinfachToll** [comment]
OK, you want to "point" to a data sheet. And then what? What keys do you want to press and what would you like to happen? Please be specific. Anyway, you may want to read the complete part here: `:h vimwiki-syntax-links`.

**Comment by nirgivon** [comment]
I guess... Hitting <CR> will open the file?
Or folder?
Like opening a web link?

**Comment by EinfachToll** [comment]
Try `[[file:C:\link\to\file.png]]` and read the part of the documentation I mentioned above.

**Comment by nirgivon** [comment]
So, I finally got what I needed working...

Using NEARDTree and This extention:
https://www.codesd.com/item/copy-the-path-file-with-the-nerdtree-vim-plugin.html

I can use NEARDTree to locate the file I want and copy I'ts path in to vim.

Then just replace the \ slashes with / and the link works!

:-)

**Comment by redapemusic35** [comment]
If you are using a Mac, this worked for me: `[[file:~/.....]]` the dots represent any path and Vimwiki recognizes the spaces as well. Very handy.
