### ISSUE TITLE
VimwikiNormalizeLinkVisual does not work for multiple words inside of diary page 

### ISSUE THREAD

**Issue by emilhuseynli** [vimwiki/vimwiki#438]
Only first word of the selection is turned into link, and all next words just disappear.
Same is with VimwikiFollowLink, i.e. visually selecting and pressing Enter. I'm using vim 8 and tested with both master and dev branches.

**Comment by ranebrown** [comment]
@emilhuseynli  I'm not seeing this behavior in the latest `dev` branch. I created a diary page for the current day and then typed `this is a test` and visually selected the text. Pressing enter creates a link and enter again follows the link and creates the page.

Is this the same scenario as when you saw the issue?

**Comment by ranebrown** [comment]
Please reopen if you are still experiencing this behavior, otherwise I'm considering this as fixed.

**Comment by johnyoonh** [comment]
Works on dev branch, but not master branch.

**Comment by ranebrown** [comment]
Confirmed this is still an issue on master. The fix will be part of the v2.5 release. #638
