### ISSUE TITLE
E486: Pattern not found: ww

### ISSUE THREAD

**Issue by OnlyBrakeForRainbows** [vimwiki/vimwiki#439]
This is probably something silly, (New to vim here also) but every time I execute:

`/ww`

I get the error

`E486: Pattern not found: ww`

Installed doing the following:

## Setup pathogen

`sudo apt install git curl vim-pathogen`

`mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim`

`vim ~/.vimrc`

```
execute pathogen#infect()
syntax on
filetype plugin indent on
```

`:wq`

## Setup vimwiki

`cd ~/.vim/bundle`
`git clone https://github.com/vimwiki/vimwiki.git`

The command `:help vimwiki` does work however which I assume verifies successful installation.

* vim version 8.0.707
* Debian GNU/Linux 9 (stretch) 64-bit
* Gnome 3.22.2 (Using Gnome Terminal)

**Comment by EinfachToll** [comment]
You probably want to type `\ww`, because `\` is the so-called leader key.

**Comment by OnlyBrakeForRainbows** [comment]
Thanks for the reply,

Interesting as vim will not allow me to use '\' to perform the command as suggested, it will only allow '/'

**Comment by EinfachToll** [comment]
You're funny, `\` doesn't work, so you take `/` instead and then you are surprised that it doesn't do what you want? `/` does exactly what it is supposed to do, that is, searching for a string in the file. Anyway, what happens if you press `\`? And what does `:echo mapleader` show?

**Comment by OnlyBrakeForRainbows** [comment]
Haha, glad to amuse :+1: in vim I can't `\` period for some reason, I can `/`, `:echo mapleader` returns an error:

```
E121: Undefined variable: mapleader
E15: Invalid expression: mapleader
```

Like I say just new to vim, I can edit files no problem (the basics) this is my first go at some extensions. If I'm causing too much trouble feel free to close the issue however.

**Comment by EinfachToll** [comment]
Of course you can press `\`, but what happens if you do that? Nothing?
Anyway, try this: `:let mapleader=','` and then you can probably use `,ww` to start Vimwiki. If that works, you can put `:let mapleader=','` into your .vimrc.

**Comment by guakamole** [comment]
@OnlyBrakeForRainbows 

Hello,

What do you mean when saying that you can't `\` ? Does it mean that you get no visual feedback ?

If so, that's normal.

Try again `\` (you won't get any visual feedback so you might have the feeling that nothing is happening) followed by `ww` (do not press any other key in the meantime).

**Comment by OnlyBrakeForRainbows** [comment]
Yeah that's what happens, all I hear is the drip noise as if it's not letting me even '\' and can't do `ww` after. @EinfachToll I have tried the mapleader, still nothing, It's me I know it is, I must be doing something stupid...

**Comment by EinfachToll** [comment]
Hm. What happens if you type `:VimwikiIndex`? The `\ww` key combo is just a shortcut for this command.

**Comment by OnlyBrakeForRainbows** [comment]
returns: `E492: Not an editor command:VimwikiIndex` think we may have the problem

**Comment by OnlyBrakeForRainbows** [comment]
I've recently reinstalled my system, and, by creating the `~/vimwiki/index.wiki` manually everything now works :)
