### ISSUE TITLE
vimwiki broken: links don't work anymore

### ISSUE THREAD

**Issue by Newexplorer** [vimwiki/vimwiki#441]
This is how my index look like:
`= Contents =

== Vim ==
	 - [[vimplugins]]
	 - [[vimwiki]]
	 - [[vim]]
etc.'

The links are broken. All of them. On all pages.

**Comment by guakamole** [comment]
Duplicate of #440

**Comment by guakamole** [comment]
@Newexplorer could you please answer these questions to help debug the problem https://github.com/vimwiki/vimwiki/issues/440#issuecomment-367592185 ?

**Comment by EinfachToll** [comment]
Not, this is not a duplicate of #440, but the workaround is the same: register a wiki in your .vimrc, that is, put there something like `let g:vimwiki_list = [{'path': '~/my_site/', 'path_html': '~/public_html/'}]`. This should help until the issue is fixed...

**Comment by guakamole** [comment]
Sorry, my bad.

**Comment by Newexplorer** [comment]
The issue appeared after updating my plugins (:PluginUpdate with Vundle).  
I have taken a look at issue 440 and used the solution presented there:
`let g:vimwiki_list = [{'path': '~/vimwiki/', 'path_html': '~/vimwiki_html/'}]  `
That worked.  
Thank you for answering.

**Comment by EinfachToll** [comment]
That was only a workaround, not a fix, so this issue should remain open.

**Comment by EinfachToll** [comment]
Should be fixed now.
