### ISSUE TITLE
`:VimwikiReturn 3 5` behavior

### ISSUE THREAD

**Issue by waxlamp** [vimwiki/vimwiki#443]
Hi! I love VimWiki!

I have a question about customizing the behavior of `<CR>` via `:VimwikiReturn`. The behavior I want is (I think) encoded by `:VimwikiReturn 3 5`. That is, I want to press enter in the middle of a list item, *even one that has been continued to the next line*, and get a new list item at the same indentation level. On a blank list item, I want to press enter to dedent the empty list item, or delete it completely if it already at the left margin.

However, the behavior I get is a bit different: now, whenever I'm on *any* line, whether I'm creating list items or not, pressing enter gives me a new list item on the next line. If I'm just on a blank line in insert mode and I want to press enter to create some blank lines, I can no longer do it: instead, I get a single empty list item, indented once, on the next line.

I think this happens because VimWiki can't tell the difference between being on the continued part of a list item, and being on a completely non-list item line.

For now I've reverted to the standard behavior where pressing enter on a continued list item takes me to the right position on the next line without creating a new item, and I hit `<C-l><C-m>` to force the creation of a new item. But the original behavior I described at the top would be ideal for me.

Let me know if you have any suggestions. Thanks!

**Comment by ranebrown** [comment]
I initially thought this was a bug but after looking at it some I'm not so sure. The command `VimwikiReturn 3 5` behaves as advertised the issue is mapping it to `<CR>` which also has another purpose. The only way I can think of to make that mapping work would be to check above the cursor position x lines for a list marker. That wouldn't solve the problem completely though because there would be false positives depending on how many lines up you were looking.

I'm going to leave this open in case someone can think of a more elegant way to handle the situation but the best option for now is to use a different mapping or use `<C-l><C-m>` like you mentioned.

**Comment by ranebrown** [comment]
`inoremap <C-K> <Esc>:VimwikiReturn 3 5<CR>` seems to work well.

**Comment by waxlamp** [comment]
Thank you for the suggestion!

Unfortunately, I was hoping to use `<C-CR>` or `<S-CR>` for that purpose but it seems like Vim has longstanding issues with those key combos in the terminal :crying_cat_face:

But I am ok with using muscle memory to type `<C-l><C-m>` when needed.

I'll leave it to you if/when to close this issue. Thanks so much!

**Comment by ranebrown** [comment]
If anyone comes up with a way to solve this please reopen.

**Comment by ranebrown** [comment]
@waxlamp I made a change that should allow `VimwikiReturn 3 5` to work when mapped to `CR`. Try something like:
```vim
augroup VimwikiKeyMap
    autocmd!
    autocmd FileType vimwiki inoremap <silent><buffer> <CR>
                \ <C-]><Esc>:VimwikiReturn 3 5<CR>
augroup END
```

**Comment by waxlamp** [comment]
Seems to work like a charm! Thanks!

If you feel like it, could you explain how that `autocmd` works?

**Comment by ranebrown** [comment]
It just remaps the keys only when the filetype is vimwiki in case plugins for other filetypes want to also remap `<CR>`. See the comment [here](https://github.com/vimwiki/vimwiki/issues/415#issuecomment-482919609) for a description of the `C-]` part.

**Comment by waxlamp** [comment]
Ah, thanks for the explanation. Not sure I knew about `iabbrev` before now.
