### ISSUE TITLE
When moving between files, vim/vimwiki displays info about the changes

### ISSUE THREAD

**Issue by guakamole** [vimwiki/vimwiki#445]
Hello (again),

I hope that I am being helpful (and not a burden) by reporting these issues, I know that you have been working hard on refactoring the code and have recently integrated some of this refactoring. Thank you again for all your work and thank you to the contributors :+1: 

## Bug or feature?

When navigating between wiki pages (using `Enter` on an internal link and `Backspace` on a wiki page), vim/vimwiki displays some stats about the current page and/or updates  if the page has been modified.

## Steps to reproduce

```
vim -c VimwikiIndex
# navigate to next internal link (foobar), hit Enter
# go to the end of page, insert a word
# return to normal mode, hit Backspace
```

```
"~/vimwiki/foobar.md" 150L, 6789C written
"~/vimwiki/index.md" 372L, 134501C
Press ENTER or type command to continue
```

**Comment by EinfachToll** [comment]
Should be fixed now.
