### ISSUE TITLE
Contents with short wiki links

### ISSUE THREAD

**Issue by cizmazia** [vimwiki/vimwiki#446]
Please could you add an option for generating short wiki links `[[URL]]` instead of the long ones `[[URL|DESCRIPTION]]` in the table of contents?

Input file:
```
= Contents =
= Agenda =
```
The current default output:
```
= Contents =
- [[#Agenda|Agenda]]
= Agenda =
```
Desired output:
```
= Contents =
- [[#Agenda]]
= Agenda =
```

Workaround:
```vim
au BufWritePre *.text let g:vimwiki_global_vars.WikiLinkTemplate2 = g:vimwiki_global_vars.WikiLinkTemplate1
```

**Comment by ranebrown** [comment]
@cizmazia If you create a PR we will be more than willing to review and merge in the new option. Otherwise this probably isn't going to happen anytime soon.

**Comment by hq6** [comment]
This has been merged.
