### ISSUE TITLE
Can't get MathJax to work

### ISSUE THREAD

**Issue by nirgivon** [vimwiki/vimwiki#447]
I have try both linking to the online CDN and linking to my local installation.

I tested the template file to make sure it is working (added an h1 with some text)

here is the template file:
<html>
<head>
    <title>%title%</title>
        <link rel="Stylesheet" type="text/css" href="%root_path%style.css" />
        <title>%title%</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script type="text/javascript" src="<../mathjax>/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
</head>
<body>
    <div class="content">
    %content%
    </div>
    <p><small>Page created on %date%</small></p>
</body>
</html>

I am using gVim, Windows 10, chrome.

**Comment by Nudin** [comment]
> <title>%title%</title> <title>%title%</title> <script type="text/javascript" src="<../mathjax>/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

Don't put the folder inside '<>'. Do something like:
> <title>%title%</title> <title>%title%</title> <script type="text/javascript" src="../mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

[Download Mathjax](https://github.com/mathjax/MathJax/archive/master.zip) and put it to a folder called "mathjax" in the same folder your template-folder is in.

**Comment by nirgivon** [comment]
Well, putting the full path did the job!

Thanks!
