### ISSUE TITLE
feature request: %toc%

### ISSUE THREAD

**Issue by sharethewisdom** [vimwiki/vimwiki#453]
Consider the following:
```html
<body>
  <nav>%toc%</nav>
  <section>%contents%</section>
</body>
```
I know I can add `<nav>`, `<section>`, `<aside>`, etc... to `g:vimwiki_valid_html_tags`. But I'd like there to be a way to put the TOC in a `<nav>`, which would be a sibling to `<section>` which would hold the rest of `%contents%`. Having the TOC inside `%contents%` by default is a problem, because it means I can't wrap it separately, which means that I cannot make an off-screen menu with `position:fixed;` hide behind its parent, or use css grid to achieve the same effect. (I don't like to be forced to find a way around css limitations with javascript.)

As for backward compatability: maybe vimwiki could check for `%toc%` first, and then decide to include the TOC inside `%contents%` or in `%toc%`?

**Comment by tinmarino** [comment]
Closing <= Move to #1139 to mutualise
