### ISSUE TITLE
Is there a documentaion for available shortcuts?

### ISSUE THREAD

**Issue by MoHD20** [vimwiki/vimwiki#455]
Where I could find vimwiki keyboard shortcuts in vim's help? I searched the help page `:h vimwiki` but didn't fine any.

**Comment by vegsplore** [comment]
Just a user and it might not be complete, but I've assembled this list for me. Hope it's not too cryptic and perhaps helps ...

[vimwiki.txt](https://github.com/vimwiki/vimwiki/files/1824504/vimwiki.txt)

**Comment by Nudin** [comment]
The official documentation is in ` :help vimwiki-mappings`, there are also a few nice overviews made by users:
- http://www.picb.ac.cn/~xiaohang/vimwiki/tools/commands/vimwiki/Vimwiki1.1.1QR.pdf
- http://thedarnedestthing.com/vimwiki%20cheatsheet

Pull request improving the documentation are always welcome. ;)

I'm closing this – feel free to reopen if you think there's still an issue.
