### ISSUE TITLE
Omnicomplete links issue (Markdown syntax on Windows)

### ISSUE THREAD

**Issue by RayDrew49** [vimwiki/vimwiki#456]
Hi,

When trying to use omnicomplete to generate a list of links I'm getting the following:

[test omni](<c-x><c-o> gives a list of long paths like:

[test omni](../../../../../C:\Users\rdrew\onedrive\vimwiki\TaskPool

If I start the link with a hint like... [test omni](Tas<c-x><c-o> ... I get 'Pattern not found'

This is with markdown syntax on Windows 10. I get the same with or without the following in my vimrc:
set omnifunc=vimwiki#Complete

I'm new to both Vim and Vimwiki so hoping I'm missing something obvious.

Thanks for any help,

Ray

**Comment by previsualconsent** [comment]
I'm getting the same thing.

**Comment by ranebrown** [comment]
This is related to path handling which has issues in a few places on windows. See #478

**Comment by ranebrown** [comment]
@RayDrew49 @previsualconsent Do you mind testing the changes I pushed to this [branch](https://github.com/vimwiki/vimwiki/tree/omni) and posting any results here or on PR #660? Thanks!
