### ISSUE TITLE
<Leader>w<Leader>w with markdown doesn't properly go to .md file for current day

### ISSUE THREAD

**Issue by TranquilMarmot** [vimwiki/vimwiki#458]
In `.vimrc` put:
```vim
let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': '.md' }]
```

Then, open vim and press `<Leader>w<Leader>w`

This _should_ create a `.md` file for today's date but instead it creates a `.wiki` file.

Note that if you _first_ do `<Leader>wi` to get to the diary index, then do  `<Leader>w<Leader>w` it will take you to the proper file.

**Comment by EinfachToll** [comment]
This is fixed now thanks to @blyoa.
