### ISSUE TITLE
Can't set foldmethod for vimwiki files

### ISSUE THREAD

**Issue by emKaroly** [vimwiki/vimwiki#460]
I have in my .vimrc
let g:vimwiki_folding = ''
set foldmethod=indent

but it doesn't work. Is there a workaround to have foldmethod=indent in wiki files?

**Comment by EinfachToll** [comment]
When I use the settings you mentioned, then there is no folding, which is exactly what is supposed to happen. What did you expect?

**Comment by emKaroly** [comment]
If i do ":set foldmethod=indent" in vim while the wiki file is open it immediately fold my lists so thats the behaviour i expect.

**Comment by beuerle** [comment]
> ```let g:vimwiki_folding = ''```

you disable folding with that command. From the help:

```vim
*g:vimwiki_folding*

Enable/disable Vimwiki's folding (outline) functionality. Folding in Vimwiki
can uses either the 'expr' or the 'syntax' |foldmethod| of Vim.

Value           Description~
''              Disable folding
'expr'          Folding based on expression (folds sections and code blocks)
'syntax'        Folding based on syntax (folds sections; slower than 'expr')
'list'          Folding based on expression (folds list subitems; much slower)
'custom'        Leave the folding settings as they are (e.g. set by another
                plugin)

Default: ''

Limitations:
  - Opening very large files may be slow when folding is enabled.
  - 'list' folding is particularly slow with larger files.
  - 'list' is intended to work with lists nicely indented with 'shiftwidth'.
  - 'syntax' is only available for the default syntax so far.
```

**Comment by emKaroly** [comment]
because vimwiki doesn't provide "indent" option which i want

**Comment by EinfachToll** [comment]
But look at the last option: `'custom'        Leave the folding settings as they are (e.g. set by another plugin)`. Maybe  this is what you want?

**Comment by emKaroly** [comment]
Ok. That's it. Thank you 👍
