### ISSUE TITLE
Motion between headings

### ISSUE THREAD

**Issue by TheoMcGinley** [vimwiki/vimwiki#462]
I am loving vimwiki but I feel the one thing that is missing is easy navigation between headings. I am aware that anchors exists but it'd be far more efficient to be able to jump directly between headings of the same level and going up/down levels, as can be done in Org mode: https://orgmode.org/manual/Motion.html

Would such a thing be viable to implement?

**Comment by EinfachToll** [comment]
There is even a pull request for it (#23) which nobody got around to polish. I will take another look at it.

**Comment by TheoMcGinley** [comment]
That'd be much appreciated, thank you! Is there anything I can do to help it along?

**Comment by EinfachToll** [comment]
The work on this can't really be parallelized, so I'm afraid no 😀
