### ISSUE TITLE
Vimwiki containing carriage returns

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#465]
The file `autoload/vimwiki/lst.vim` contains carriage returns in dos-newline-format. On my system this leads to Error-messages whenever you try to make a new line in a itemize.

PS: Sorry, I was off for some time, I hope I can do more for vimwiki again in the near future.

**Comment by Nudin** [comment]
There's also a form feed on line 1091. This isn't on purpose, is it?

**Comment by Nudin** [comment]
Fixed the CRs, but it still contains the FF as well as several ESC. I wasn't sure if it's save to simply remove them.

**Comment by Nudin** [comment]
Oh dear. It seems that I messed up something somehow and my patch actually added this crap to the code instead of removing it. It's now fixed and I'm putting on the hat of shame. :/
Sorry!

**Comment by EinfachToll** [comment]
The purpose of the `^T` in line 1091 is to execute the key sequence Ctrl+t. Is your original error still present? Maybe there is another way to encode this key using only printable characters.

**Comment by Nudin** [comment]
> The purpose of the ^T in line 1091 is to execute the key sequence Ctrl+t. Is your original error still present? Maybe there is another way to encode this key using only printable characters.

The error is fixed. But we might anyway want to get rid of the `^T`, as it's not visible in some editors and will imho for sure break something at some point.
This should work (but I haven't tested it within the change_level-function):
```
exe "normal! gi\<C-T>"
```

**Comment by EinfachToll** [comment]
Aha. Ich bin übrigens dieser Tage und hoffentlich in Zukunft auch immer mal im IRC anwesend, falls weiterer Gesprächsbedarf besteht.
