### ISSUE TITLE
enter key behavior change

### ISSUE THREAD

**Issue by biffbaxter** [vimwiki/vimwiki#469]
Running Neovim and vimwiki recently updated this morning and "enter" key behavior changed. I have not disabled all my plugins to start figuring out if one of them is causing it, but opening a non-vimwiki file does not produce the same problems with all the same plugins running. 

Normally in insert mode I would expect to be typing, hit enter and create a new line. (like typing a paragraph) 

Basically now when in insert mode in a vimwiki file when you hit enter it simply goes to the next line, and does not add or insert a line...of course then when at the bottom of a document (or when typing a new one) you cannot <CR> to keep typing a new line, you have to "o" in normal mode. 

The exception to this is when you are making a bulleted list (like with "*" or "-")

I am running the dev branch of vimwiki.

**Comment by Nudin** [comment]
I'm having this issue as well and maybe I even am responsible for this bug ;)
It's very likely connected to #465.

**Comment by Nudin** [comment]
It's fixed now, please update. Sorry!
