### ISSUE TITLE
External link with description in VimWiki syntax

### ISSUE THREAD

**Issue by cuihaoleo** [vimwiki/vimwiki#470]
Some old tutorials mentioned that VimWiki support `[http://link description]` syntax. But it doesn't work in the newest version. According to `doc/vimwiki.txt` the syntax was removed in version 2.0.

I wonder if there is an alternative syntax? I didn't find it in the latest document.

**Comment by cuihaoleo** [comment]
I read the code and find that `[[http://link|description]]` works.

**Comment by ranebrown** [comment]
Looks like this has been added to the documentation under `vimwiki-syntax-links`.
>With description: >
>  [[This is a link source|Description of the link]]
