### ISSUE TITLE
:q is silently saving a changed buffer?

### ISSUE THREAD

**Issue by shaggyaxe** [vimwiki/vimwiki#472]
It seems that if I `:q` out of a changed `.wiki` file, it's getting saved, instead of halting me with a warning.

**Comment by EinfachToll** [comment]
Yes, that's because of the option `g:vimwiki_autowriteall` which is activated per default. What it does is basically that it sets the Vim option 'autowriteall' for Vimwiki buffers. To deactivate it, put `let g:vimwiki_autowriteall = 0` into your .vimrc.

**Comment by shaggyaxe** [comment]
Hm, guess I never noticed this behavior before.

Thanks!!
