### ISSUE TITLE
list level specific highlighting

### ISSUE THREAD

**Issue by nbraun-clgx** [vimwiki/vimwiki#476]
Hi there, I love this plugin, I use it every day, thanks for the great work.

I was wondering what you guys thought about incorporating the option (similar to headers now) of including text highlighting/color based on list level?

An example of how this would look is junegunn's vim-journal plugin:

https://github.com/junegunn/vim-journal

I've hacked together a version that combines both vimwiki and vimi-journal right now and sort of works, but it's not great.  IMO different colors is a lot more readable, let me know what you guys think.

**Comment by ranebrown** [comment]
@nbraun-clgx I personally think the extra syntax highlighting makes the wiki look cluttered. You should be able to achieve what you want fairly easily but creating a custom syntax file `~/.vim/after/syntax/vimwiki.vim`.

For example, if you wanted to highlight a line starting with `NOTE:` until the first blank line you could use something like this:

```vim
syn match MyGroup "\(NOTE\:.*\)\(\(\r*\n\(\r*\n\)\@!\).*\)*" contains=VimwikiLink
hi link MyGroup Type
```

You would just need to create the appropriate groups (you could probably reuse some of what is found in vim-journal) and apply the syntax highlighting that you want. If you do get something working it would be great if you could post a link to a gist or something here in case anyone else finds it useful.

**Comment by Nudin** [comment]
I think this feature would be nice for some usercases – but I also think that it would be annoying for a lot of users. One could add it as an Opt-in feature, but I would prefere not to but instead split it into an own plugin similar to what @ranebrown suggests – I hope to have a large set of plugins working together of building upon vimwiki in the future. (There are already quite [some](https://github.com/vimwiki/vimwiki/wiki/Connected-Plugins))

**Comment by ranebrown** [comment]
@nbraun-clgx If you (or anyone else that is interested) create a plugin or a working `~/.vim/after/syntax/vimwiki.vim` please post something here, create a new issue to announce, or add to the wiki so other people can benefit. Thanks!
