### ISSUE TITLE
Case insensitive search?

### ISSUE THREAD

**Issue by horror-vacui** [vimwiki/vimwiki#480]
Is there a way to make the :VWS search command case insensitive?
I have found nothing related in the documentation.

Using the \c parameter as in normal vim search returns: 
`E682: Invalid search pattern or delimiter`

**Comment by EinfachToll** [comment]
`:VWS` is only a thin wrapper around Vim's inbuild `:lvimgrep`. The stuff you put after `:VWS` is just passed to `:lvimgrep`, so, to do a case insensitive search, you can either (temporarily) `:set ignorecase` or use a pattern like this: `:VWS /\cfoo/`.
I will add a note to the doc.
