### ISSUE TITLE
Raw URL wrapped in < > does not work

### ISSUE THREAD

**Issue by t0str** [vimwiki/vimwiki#481]
Hi

Using markdown as syntax gives me the following problem:

```
<http://someurl.tld>
```

This renders fine to html using pandoc (namely as an `<a ...>` tag), but in vim if I press enter on the URL it includes the final `>` in the browser (and the highlighting).

Switching the `ft` from vimwiki to markdown fixes the highlighting, but pressing enter still includes the `>`.

**Comment by ranebrown** [comment]
Same issue with the default syntax.

**Comment by ranebrown** [comment]
This should be fixed on the latest `dev` branch. Please reopen if you are still seeing any problems.
