### ISSUE TITLE
Fold issues on some files

### ISSUE THREAD

**Issue by mMontu** [vimwiki/vimwiki#488]
I've been using an old version of vimwiki (specifically, my branch for #227). A few days ago I switched back to the latest dev branch, and start noticing that sometimes the fold doesn't work for some wiki files. I found a way to consistently reproduce the issue:

    <simple test file>
    echo -e "= abc = \ndef" > test.wiki

    vim -u NONE -U NONE -N -i NONE
    set nocompatible
    filetype plugin on
    syntax on
    let g:vimwiki_folding = 'expr:quick'
    let &rtp.=',~/.vim/bundle/vimwiki'
    source ~/.vim/bundle/vimwiki/plugin/vimwiki.vim
    <the settings above can be copied to clipboard and then applied with :@+>

    e ~/test.wiki  --> no folds displayed
    zc  --> E490: No fold found
    <delete the buffer and open the file again>
    new
    wincmd p
    bd
    e ~/test.wiki  --> folds displayed, `zo` and `zc` works normally
    --> no fold in any case; must be missing some configuration

The issue also happens with `let g:vimwiki_folding = 'expr'`.

Any ideas on how to debug this issue?

**Comment by EinfachToll** [comment]
Thanks for the reproducing recipe. Should be fixed now.

**Comment by mMontu** [comment]
It works like a charm
Thanks!!
