### ISSUE TITLE
Anchors in github markdown flavor.

### ISSUE THREAD

**Issue by BonaBeavis** [vimwiki/vimwiki#489]
```
## Table of Contents

- [Links](ApacheNifiRDF#links) <- Works
- [Links](#links) <- Does not work

## Links
```

Would be nice to have both cases working, remark toc does produce such links.

**Comment by EinfachToll** [comment]
This should work. But is it possible that your example is wrong? The second link is supposed to jump to an anchor `links` (lowercase), but in your snippet, there is only an anchor `Links`, so it's correct that it doesn't work.

**Comment by BonaBeavis** [comment]
You are right, the problem was that the toc generator generated lings like `header-with-spaces` for a header like `## Header with Spaces`. But I won't expect vimwiki to handle those cases.
