### ISSUE TITLE
Two errors when starting vim

### ISSUE THREAD

**Issue by Newexplorer** [vimwiki/vimwiki#494]
> Error detected while processing /home/porter/.vim/bundle/vimwiki/plugin/vimwiki.vim:
> line   16:
> E121: Undefined variable: g:vimwiki_autowriteall
> E15: Invalid expression: g:vimwiki_autowriteall
> Press ENTER or type command to continue

When I press enter, I can still make use of the pages I made with Vimwiki.

**Comment by Nudin** [comment]
The Change that caused this was reverted. If you update the error should be gone. Please report if not or if it happens again. Thanks!
