### ISSUE TITLE
Error on startup after updating to latest Vimwiki version

### ISSUE THREAD

**Issue by pmcRTR** [vimwiki/vimwiki#495]
After updating to latest version of the plugin I now get this error when starting Vim:

```
Error detected while processing ~\.vim\bundle\vimwiki\plugin\vimwiki.vim:

line   16:

E121: Undefined variable: g:vimwiki_autowriteall

E15: Invalid expression: g:vimwiki_autowriteall
```

I am using latest Vim version 8.0.1839

**Comment by Nudin** [comment]
The Change that caused this was reverted. If you update the error should be gone. Please report if not or if it happens again. Thanks!

**Comment by pmcRTR** [comment]
Latest update has fixed it - thanks :)
