### ISSUE TITLE
Header text objects not working (markdown)

### ISSUE THREAD

**Issue by mrbig033** [vimwiki/vimwiki#501]
* MX Linux 17
* NVIM v0.3.0-1029-g48967695c, Build type: RelWithDebInfo
* [init.vim](https://gitlab.com/mrbig/dotfiles/blob/master/nvim/init.vim)
* [plugins.vim](https://gitlab.com/mrbig/dotfiles/blob/master/nvim/plugins.vim)
* used [vim-plug](https://github.com/junegunn/vim-plug) to install
* [vimwiki settings](https://gitlab.com/mrbig/dotfiles/blob/master/nvim/plugins.vim#L131)

None of the [documented header text objects](https://github.com/vimwiki/vimwiki/blob/966a94bd477f3b10ae7b66693508274c9aaf1288/doc/vimwiki.txt#L610) are working for me.

**Comment by Nudin** [comment]
@mrbig033 I closed this, since you apparently forgot. If it's not done, feel free to reopen.
