### ISSUE TITLE
Don't set vimwiki filetype on files outside wiki root

### ISSUE THREAD

**Issue by swalladge** [vimwiki/vimwiki#506]
My scenario was a custom wiki with the file extension set to '.txt'. Now every time I open a '.txt' file somewhere in the filesystem, it sets it to vimwiki filetype, which is undesirable.

Better behaviour would be to only automatically set the vimwiki filetype on files with the configured extension that under the wiki root directory.

**Comment by EinfachToll** [comment]
In order to not create a so-called temporary wiki, set `g:vimwiki_global_ext` to 0. See `:h vimwiki-temporary-wiki` for more information.
