### ISSUE TITLE
Am I supposed to be seeing the asterisks and underscores when I try to bold/italicize a word?

### ISSUE THREAD

**Issue by yamini-krishnamurthy** [vimwiki/vimwiki#507]
When I try to bold a word, I see -asterisk-**hello**-asterisk- instead of just **hello**. Is that what is supposed to happen? Cheers

**Comment by EinfachToll** [comment]
Normally not. Theory 1: you're using `**hello**` to bold something (like in markdown). In Vimwiki, however, you would use `*hello*` for bold text and `_hello_` for italics. Theory 2: Concealing is switched off in your Vim (although Vimwiki switches it on by default). What does it say if you type `:set conceallevel?` ?

**Comment by yamini-krishnamurthy** [comment]
I see "E519:  Option not supported: conceallevel"

**Comment by EinfachToll** [comment]
Well, that means your Vim is compiled without the conceal feature. I bet when you type `:version` you will see `-conceal` in the list of the features (with the `-` which means that it is disabled). If you want the asterisks hidden, you have to get a Vim version with conceal enabled or compile Vim yourself.

**Comment by EinfachToll** [comment]
> I cannot see my words actually being bolded or italicized

Wait, I missed that remark. What about other syntax elements like links or headers? Are they highlighted in some way? If not, there is probably something wrong with Vimwiki. If yes, my guess is that the terminal you run Vim in can't display bold and italic fonts. I sometimes use this WSL bash-on-ubuntu-on-windows console thing, which can't. If you have no clue at all, can you at least post a screenshot?

**Comment by yamini-krishnamurthy** [comment]
<img width="236" alt="screen shot 2018-06-05 at 3 06 07 pm" src="https://user-images.githubusercontent.com/32017567/40967946-04a55752-68d2-11e8-9078-743cb788bc13.png">
here you go. 
so after some tweaking, i am getting italics when i use one or two underscores, and bold when i use one or two asterisks. this however isn't markdown syntax, but vimwiki syntax. so i'm pretty confused.

**Comment by EinfachToll** [comment]
Ok, so, the `hi`s are indeed highlighted, only the asterisks and underscores are not concealed. As I said above, that's a problem of your Vim and nothing we can do something about.

**Comment by yamini-krishnamurthy** [comment]
Thank you!
