### ISSUE TITLE
Settings in .vim/after/vimwiki.vim are not applied

### ISSUE THREAD

**Issue by ahmedelgabri** [vimwiki/vimwiki#510]
This is my current settings

```vim
let g:vimwiki_folding = 'expr'
let g:vimwiki_dir_link = 'index'
let g:vimwiki_toc_header = 'Table of contents'
let g:vimwiki_list = [{
      \ 'path': '/Users/' . $USER . '/path/to/vimwiki/',
      \ 'diary_rel_path': 'Diary/',
      \ 'diary_index': 'index',
      \ 'syntax': 'markdown',
      \ 'ext': '.md',
      \ 'auto_toc': 1,
      \}]
```

Which was already working, I ran `PlugUpdate` a couple of days ago & since then everytime I run `:VimwikiIndex` it will ask if I want to create a new folder at `~/vimwiki`? but checking the docs seems like this should work, but it's not.

**Comment by EinfachToll** [comment]
If you really updated a couple of days ago then try updating again, because yesterday were some changes which may or may not have something to do with your issue.

**Comment by ahmedelgabri** [comment]
I did update now, pulling the `dev` branch too (which is the active one) & nothing changed. The issue still exists.

**Comment by EinfachToll** [comment]
Hm, strange. Does it really want to create the new folder `~/ahmed/vimwiki` or is it rather `~/vimwiki`? What happens if you instead of `:VimwikiIndex` type `:call vimwiki#base#goto_index(1)`? Can you post the output of `:echo vimwiki#vars#get_wikilocal('path', 0)`?

**Comment by ahmedelgabri** [comment]
> Hm, strange. Does it really want to create the new folder `~/ahmed/vimwiki` or is it rather `~/vimwiki`? 

Sorry, yeah it wants to create `~/vimwiki`.

> What happens if you instead of `:VimwikiIndex` type `:call vimwiki#base#goto_index(1)`?

Same wants to create `~/vimwiki`.

> Can you post the output of `:echo vimwiki#vars#get_wikilocal('path', 0)`?

`/Users/ahmed/vimwiki`

---

Ok, I dunno what changed exactly but I usually put plugin settings in `~/.vim/after/plugin/<plugin>.vim`. So in this case, it's `~/.vim/after/plugin/vimwiki.vim` & this was working fine, for some reason this doesn't work anymore. Because if I move my settings to my `.vimrc`/`init.vim` it works fine.

**Comment by EinfachToll** [comment]
> but I usually put plugin settings in ~/.vim/after/plugin/<plugin>.vim

Aha! That doesn't work because these settings are read after Vim and Vimwiki have been loaded and Vimwiki can't really know that its settings have changed. But I think this is still a valid use case, so we should fix it. Until then, if you want to keep your settings in `~/.vim/after/plugin/vimwiki.vim`, you can put the line `call vimwiki#vars#init()` at the end of this file, which should make it work (didn't test it).

**Comment by ahmedelgabri** [comment]
> [...] you can put the line `call vimwiki#vars#init()` at the end of this file, which should make it work (didn't test it).

This worked, thanks!

**Comment by EinfachToll** [comment]
Nevermind, fixing this makes everything complicated and would be a hack which would work only half of the time anyway. I added a note to the doc instead.
