### ISSUE TITLE
Issue template and Version-gathering function

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#513]
For a lot of the issues opened here we respond with the same two questions: How up to date is you version of vimwiki (aka how did you install it) and which syntax do you use.
I think we could make things easier by creating a issue template asking for these informations and providing an easy way to find out the revision the user is currently working with.

I created two pull requests with a basic sketch:  #511 & #512. Not perfect yet, but let me know what you think about the idea.

**Comment by ranebrown** [comment]
@Nudin I created a pull request template and an issue template [here](https://github.com/vimwiki/vimwiki/tree/master/.github). They probably need some modifications but I think it is a good starting point. The text in the respective file will be shown when opening a new pull request or issue.

**Comment by ranebrown** [comment]
I was thinking it might be good to add a note about trying to reproduce the issue with a minimal vimrc using `vim -u min_vimrc` and providing a basic example. What do you think?

**Comment by Nudin** [comment]
@ranebrown:

- About the issue template: I created one it the past but apparently github fooled me since the commit is empty!? Anyway I would remove point 1 since most people know it anyway and the rest won't listen, but it sounds unnessacary withering. Another point that defnitly has to be in there it asking the people about what syntax they use or even better asking them to copy-paste their vimwiki-config! This is what I've been asking back the users in 80% of all issues.
- About the PR template: Nice.
- About the minimal vimrc: Yes! I've planning to do this as soon as I can create additional repos in the vimwiki group. It should not only have a minimal vimrc but also 3 wikis with the three syntaxes, filled with pages demonstrating all the features to be able to quickly do (regression) tests.

**Comment by ranebrown** [comment]
I made a couple changes to the issue template but feel free to modify things as you see fit.

Creating a wiki for each syntax to use for testing is an awesome idea! I think the minimal vimrc and those wikis should be a priority since they would definitely help us with debugging issues and testing fixes!

**Comment by Nudin** [comment]
> Creating a wiki for each syntax to use for testing is an awesome idea! I think the minimal vimrc and those wikis should be a priority since they would definitely help us with debugging issues and testing fixes!

@ranebrown @hq6 I created a repo on my account for now and stared to fill it for the vimwiki-syntax. I will move it to the vimwiki-organisation as soon as @EinfachToll adds me to the group. I allready added you as maintainers – please help filling it with life.
