### ISSUE TITLE
vimwiki and vim-markdown <Enter> issue

### ISSUE THREAD

**Issue by sprnza** [vimwiki/vimwiki#514]
Hi there!
I've already seen a feature request to make vimwiki and vim-markdown compatible but it was without any complaints though.
My main issue that when I enable vim-markdown Enter stops creating links and folowing already created ones. Is there a workaround for this?

**Comment by sprnza** [comment]
I'm not sure why whould I need vim-markdown though :)

**Comment by krzkrzkrz** [comment]
Can you explain your solution? Not clear if you found something or just decided to close

**Comment by Kwask94** [comment]
I have the same Problem, I think I'm going to change Vimwiki Markdown Syntax file and try it out

**Comment by ranebrown** [comment]
I think this issue is related to using an alternative syntax not officially supported by vimwiki and doing that is probably going to break some internal workings. I'm closing this but feel free to post any solutions or workarounds that others might find useful.

**Comment by edrex** [comment]
I'm not sure this should be closed. Vimwiki should try to interoperate with the rest of the vim ecosystem, and there's clearly some bug with the '<CR>' mapping.

**Comment by edrex** [comment]
I realized my conflict was actually with another plugin, and I just needed to redo the binding in my config.
