### ISSUE TITLE
Vimwiki Requires Internet Access

### ISSUE THREAD

**Issue by rtilk89** [vimwiki/vimwiki#519]
I get the following error when I try to start up vimwiki:

`Error detected while processing function <SNR>67_setup_new_wiki_buffer..vimwiki#vars#get_bufferlocal:                                                            
line    3:
E118: Too many arguments for function: getbufvar                                                                                                                 
E15: Invalid expression: getbufvar(buffer, 'vimwiki_'.a:key, '/\/\')  `

This is on a machine that sits behind a proxy. I do not get this error when I open vim with access to the proxy. Is there a way to get around this?

**Comment by EinfachToll** [comment]
Come on, not so fast with your diagnosis. Vimwiki has absolutely no knowledge of what the internet is. Maybe your plugin manager does. Anyway, the error message looks to me as if you use an old Vim where the built-in function getbufvar() accepted only 2 arguments. What is your Vim version? You can see it e.g. in the output of `:ve`.

**Comment by rtilk89** [comment]
You're right @EinfachToll I was using vim 7.3. Upgrading my version seemed to resolve this issue. Thanks
