### ISSUE TITLE
Can't turn off Autoindent when editing files which have registered wiki extensions

### ISSUE THREAD

**Issue by felix-vs** [vimwiki/vimwiki#520]
Hi, so I want to edit my wiki files in Vim without automatic indentation.

My attempts to turn the option off by command Vim itself didn't succeed.

I confirmed this issue is only in effect when Vimwiki files directory is present in my plugins folder (~/.vim/pack/plugins/start/vimwiki) by removing it and then readding it.

I tried to disable automatic indentation as described in the Vim wikia under 'disable filetype indentation for all file types': http://vim.wikia.com/wiki/How_to_stop_auto_indenting

UPDATE:
Psuedo-code describing the issue:

``Let {ext1, ext2,..., extN} be a set of  strings``

``Let wiki1, wiki2,..., wikiN be  dictionaries with key 'ext' with values ext1, ext2,..., extN  respectively``

``g:vimwiki_list ← List of {wiki1, wiki2,..., wikiN}``

Now to replicate the issue:
Edit a text file with an extension among {ext1, ext2,..., extN}
Notice that automatic indentation is in effect (at least for me it is)

Implement above in .vimrc to replicate the issue.
Example implementation:

1.  Add following to ~/.vimrc :
``Let g:vimwiki_list = [{'ext': '.wiki'}, {'ext': '.md'},{'ext': '.document'}]``

2. Edit a text file with an extension among {'.wiki', '.md', '.document'}
Notice that automatic indentation is in effect (at least for me it is)

UPDATE 2:
Tried with 'ext' values: '.wiki' , '.md', '.document' and the above update description is true for those.
However with 'ext' value '.py' it is inconsistent with above update description, as shown in table below:

--------------------------------------------------------------------------
'ext' option          | Autoindent active|Can create links|automatic save
----------------------|------------------|----------------|---------------
'.wiki/.md/.document/'| yes              | yes            | yes
'.py'                 | no               | no             | yes
--------------------------------------------------------------------------

Any idea why this is happening?

**Comment by felix-vs** [comment]
Hi @joeytwiddle 

That suggestion did not solve it for me.

Going to edit the first post/title with new information i got now after trying to figure it out:
This issue is with every value of 'ext' that a registered Vimwiki has, basically described:

Psuedo-code:
Let wiki1, wiki2,..., wikiN = {'path': '/PATH/1, 'ext': '.wiki1'},  {'path': '/PATH/2, 'ext': '.wiki2'},...,  {'path': '/PATH/N, 'ext': '.wikiN'}

Let g:vimwiki_list = [wiki1, wiki2,..., wikiN]

Now to replicate the issue:
Edit a text file with an extension among {'.wiki1',  '.wiki2',  '.wikiN'}.
Notice that automatic indentation is in effect (at least for me it is)

**Comment by joeytwiddle** [comment]
You can also try

```
setlocal indentexpr=
```

https://vi.stackexchange.com/questions/10128/how-do-i-disable-intelligent-indentation-in-html-files

When you do eventually work out which option you need to unset, restart Vim to bring the problem back, and type

```
verbose setlocal smartindent?
```

That will tell you which script last set the value of `smartindent`, which may help you to disable it permanently.

**Comment by felix-vs** [comment]
@joeytwiddle 

This suggestion also didn't solve it for me.

Here're responses I got when checking automatic indentation settings:
`:set autoindent?` 
=> `noautoindent`
`:set smartindent?`
=> `nosmartindent`
`:set cindent?`
=> `nocindent`

**Comment by felix-vs** [comment]
> This the output of verbose setlocal smartindent?:
autoindent
Last set from ~/.vim/pack/plugins/start/vimwiki/ftplugin/vimwiki.vim

>Will try to see what that file is about.

OK so the following line in my .vimrc is responsible:
`filetype plugin on`
which is part of the instructions that allow Vimwiki to be used (README page).
For example, trying to enter links (with Enter key) doesn't work when `filetyple plugin on` is removed.

**Comment by EinfachToll** [comment]
If you really want to turn autoindent off, you can put `au FileType vimwiki set noautoindent` into your vimrc. But I don't know if this breaks some functionality.

**Comment by felix-vs** [comment]
@EinfachToll 

This suggestion solved it for me (at least for now).
