### ISSUE TITLE
Very slow easymotion word (w) mode when vimwiki is enabled

### ISSUE THREAD

**Issue by heratech** [vimwiki/vimwiki#521]
Hi,
Vim wiki is amazing, especially with taskwiki (taskwarrior integration).
However one problem I found is there is a rather long delay now on almost any file when using easymotion (word find mode).
I went through all my plugins and it is definitely fine when vimwiki is disabled and a problem when it is enabled.

I tried a clean .vim folder to.
This is using both the dev branch and latest release.
Example config:

let g:mapleader = "\<Space>"
call plug#begin('~/.vim/plugged')
Plug 'easymotion/vim-easymotion'
Plug 'vimwiki/vimwiki', { 'branch': 'dev' }
call plug#end()
set nocompatible
filetype plugin on
syntax on
map \<Leader> \<Plug>(easymotion-prefix)

If you try that, open up the .vimrc to edit and try <space>w and you will see a delay before the easymotion stuff renders. COmment out the vimiwiki line and easymotion will load instantly.

**Comment by heratech** [comment]
For now as a slight workaround I am conditionally loading the vimwiki:

Plug 'vimwiki/vimwiki', { 'branch': 'dev', 'on': 'VimwikiIndex'}

**Comment by hq6** [comment]
This likely due to easymotion's mapping being a prefix of a vimwiki mapping. 

Have you tried changing the mapping for the easymotion command to see if that changes things?

**Comment by hq6** [comment]
Since there has been no response on this issue, I am closing it. Please feel free to reopen if there is renewed interest.
