### ISSUE TITLE
All Header types display as Header1

### ISSUE THREAD

**Issue by danielchen115** [vimwiki/vimwiki#523]
Hi,

Screenshot below as to what I mean.

![image](https://user-images.githubusercontent.com/22237453/42196402-d0dd1bfa-7e4b-11e8-9d03-3d18d046a63a.png)

Thanks!

**Comment by hollasch** [comment]
See `:help vimwiki-syntax-headers`. By default, all styles are the same. If, for example, you execute `:hi VimwikiHeader2 guifg=#00ffff`, you'll get cyan level-2 headers.
