### ISSUE TITLE
More freedom with Table of Contents generation (heading level & not first thing on page).

### ISSUE THREAD

**Issue by atimholt** [vimwiki/vimwiki#526]
Currently, the table of contents must be a level 1 heading. You can change the wording from “Contents”, but there’s no way to dissuade the toc generator from asserting that the toc is the most important thing on the page (as opposed to, say, the main heading of the page). This also throws off correct folding, asserting that everything that isn’t the single most important thing on the page (that follows “`= Contents =`”) is somehow a subcategory of the table of contents.

My particular use case is having a level 1 heading at the top, a brief blurb, then the table of contents, then the contents. I’d like to have reasonable formatting even if the table of contents isn’t the first thing on the page.

**Comment by tonyg-mg** [comment]
I preferred the previous `%toc` implementation as it made no assumptions about sticking a heading into the page.  I use heading 1 as the top-level title for the page (I realize that the generated HTML uses the file name for the official <title>).  Now, if I use auto-generated TOC, all my pages are forced render as "Contents" as the most visible section.  The current implementation assumes a document layout where there are multiple level-1 headings so the contents won't compete as the most important (stylistically) heading--but its pretty common to use a layout like so:
```
level 1 (effectively the title from a reader's point of view)
   level 2 subhead
   level 2 subhead
   level 2 subhead
```
While I'm not privy to the decisions which led to replacing the previous `%toc` ability, I found it much  more to my liking than the newer approach.

**Comment by ranebrown** [comment]
@atimholt, @tonyg-mg A new option `g:vimwiki_toc_header_level` was added in PR #629 which should give you the desired behavior. The TOC is still placed at the top of the file but it can be manually moved and will update correctly from the new location. Please give this a try on the `dev` branch. This will be part of the v2.5 release #638.
