### ISSUE TITLE
Set the default wiki creation path in diary

### ISSUE THREAD

**Issue by johnyoonh** [vimwiki/vimwiki#527]
if the wiki already exists, the diary link will follow the existing link. On the other hand, if does not exist, it will create one under ./diary
I think it would be nice to have a global variable so that the diary honors the default wiki location when `follow_link` function creates a new one.

**Comment by hq6** [comment]
I am not sure I entirely understand this problem. Can you give concrete steps for reproducing the behavior?

**Comment by hq6** [comment]
Closing this issue due to lack of response and lack of clarity for reproducing.
