### ISSUE TITLE
Error Opening Link, `Missing :endif`

### ISSUE THREAD

**Issue by aozgaa** [vimwiki/vimwiki#534]
vimwiki commit: 9f8b0082dbd99e706cc18de2076f7a66c2ca0a90
vim version: 8.1.1 (built from source with nix, full features below)
I've no other plugins installed except vimwiki and pathogen.

When opening a link, I get an error message and them vimwiki seems to stop working (the file is opened in readonly mode and further vimwiki commands such as generating a new link with CR trigger more error messages).

**Error**
```
Error detected while processing function vimwiki#base#follow_link[58]..vimwiki#base#open_link[30]..vimwik
i#base#edit_file:
line   21:
E325: ATTENTION
Error detected while processing function vimwiki#base#follow_link[58]..vimwiki#base#open_link:
line   30:
E171: Missing :endif
Error detected while processing function vimwiki#base#follow_link:
line   58:
E171: Missing :endif
```

[Link to line 58 at this commit](https://github.com/vimwiki/vimwiki/blob/9f8b0082dbd99e706cc18de2076f7a66c2ca0a90/autoload/vimwiki/base.vim#L58).

It looks like there is already a comment about this issue. I suppose this is a :+1 stating this affects an end user.

What would go into fixing this issue?

If there is a need for it, I can try creating a small repro.

## Vim Setup
```
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jan  1 1970 00:00:01)
Included patches: 1
Compiled by nixbld
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vertsplit
-clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         -python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               -ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "
/nix/store/93b02cwmd6hn9szsjyh048351h6cf14d-vim-8.1.0001/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -ldl           
```

**Comment by Nudin** [comment]
I think this bug is not in line 58 of the file but in 727 (vim's stacktraces are a bit hard to read). I think I might know the issue and run in it myself in the past – but don't know a way to fix it (yet).
I assume that your vim crashed in the past (or was killed or you have still an instance running in some other terminal) while having this file open. So there now it a swap-file for this file. If you open the file with vim but without vimwiki you'd get a warning and would be asked what to do, see `:h E325` but since vimwiki calls this with `silent` you don't see the message and other the file read-only.

Can you please check if this is the reason for your problem? Just open the file with vim directly (`$vim file.wiki`).

**Comment by aozgaa** [comment]
Yup, it looks like there is a swap file that already exists that I'd accidentally checked in. Whoops. Deleting the .swp file and reopening vim restored normal functionality.

I'm unsure what vimwiki can do when it encounters a wiki file with an accompanying swp file. Does the experience degrade substantially when the file is opened read-only? Should the file be silently opened in this mode or should the default .swp file prompt be shown?

Regardless, since there is an easy enough workaround (don't open the same file in multiple editors or check-in .swp files), this is not a blocking issue for me anymore.

**Comment by Nudin** [comment]
The problem is that vim offers no way to a vimscript to detect if there's an swapfile nor any way to react to the warning.
After digging through code an vim-help for a very long time I now did a easy workaround that hopefully fixes this big annoyance for most users and doesn't produce break anything important.
