### ISSUE TITLE
Creating a relative link to files from the converted html documents

### ISSUE THREAD

**Issue by kaphula** [vimwiki/vimwiki#535]
Hey,

I am trying to use vimwiki for creating a separate set of web pages that can be uploaded to a server without the need of changing the paths of its links and resources. 

The issue I am having is that the output location of my html files are in a completely different place than the vimwiki articles, so using a "{{local:something.png}} generates a relative path to the vimwiki article instead of the generated html document. I was having the same issue with the template files, but moving a copy of the template files as sub files in the folder where html documents will be outputted resolved the issue.

**Comment by tinmarino** [comment]
Use links relative to the current file (with `./` prefix) or to the current wiki (and will be relative to the site) (with `/` prefix)
