### ISSUE TITLE
Markdown reference-style link doesn't work?

### ISSUE THREAD

**Issue by sprnza** [vimwiki/vimwiki#538]
Hi there!
I'd like to utilize reference style links in markdown, but I fail to get ones working. I add this in my file:

```

[link][1]

...
...
[1]: https://google.com
```

And when I hit enter above the link reference it opens a Vimwiki file named "1" instead. What could be wrong here?

**Comment by sprnza** [comment]
The link must look like this `[link](1)` in md

**Comment by matt-snider** [comment]
@sprnza Were you able to get this working for wikilinks? I'm trying to do the following:

```
Here is a [diary link][1].
...
[1]: diary:2018-11-07
```

I've tried `[diary link](1)` and changing the reference to `[1]: /diary/2018-11-07` to no avail.
