### ISSUE TITLE
Trouble openning URL in Windows OS. 

### ISSUE THREAD

**Issue by llinfeng** [vimwiki/vimwiki#54]
In the screenshot goes what I have when trying to open an URL in Vimwiki. 

![untitled picture](https://cloud.githubusercontent.com/assets/5890407/3281510/7f6698c8-f4b1-11e3-8f4e-01885b216c44.png)

Could anyone help me?

All the best, 
 
- Linfeng

**Comment by llinfeng** [comment]
Hi @EinfachToll, maybe you would like to "sync" the `dev` branch with the main branch for now. The problem we discussed in this thread is persisting for the master branch. (Installing Vimwiki directly through Vundle will still encounter problem for opening URL on a machine with Chinese as system Locale.

**Comment by EinfachToll** [comment]
Yes, when the tags feature is stable and usable, it's time to think about a new release. That won't be forgotten, so I'm closing this issue.
