### ISSUE TITLE
Error opening wiki links or moving back a link with cygwin and vimwiki

### ISSUE THREAD

**Issue by abers** [vimwiki/vimwiki#540]
I use vimwiki across multiple devices that includes a Linux PC at home, an Android hybrid device via termux, a couple of Raspberry Pis, and on a Windows PC at work (they only provide staff option of Windows or Mac) via cygwin. Vimwiki works fine on both Linux and Android devices but I have had persistent issues with it on the Windows machine. I regularly use vim for coding, data analysis, and editing markdown documents and it works fine for all of those tasks.

The primary issue experienced is when opening wiki links or moving back a link. Opening links tends to take a good 4-7 seconds and it regularly freezes when moving back a link. When this happens hitting escape presents the following error message:

```
Error detected while processing function vimwiki#base#go_back_link[4]..vimwiki#base#edit_file:
line   21:
E325: ATTENTION
Error detected while processing function vimwiki#base#go_back_link:
line    4:
E171: Missing :endif
```

Using vim 8.0 and vundle as plugin manager with cygwin 64-bit on Windows 7. Tried removing cygwin and reinstalling as well as removing vimwiki and reinstalling. Please let me know if you need any further information, and any steps required to produce it.

**Comment by Nudin** [comment]
Hi, your vim likley crashed in the past leaving a swap-file. Please see here: https://github.com/vimwiki/vimwiki/issues/534#issuecomment-406817735

A patch has been pushed to the dev-branch and will be part of the master-branch and the next release soon.
