### ISSUE TITLE
'I' at beginning of sentence creates bullet point in HTML

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#542]
```
I am Lorem ipsum dolor sit amet, consectetur adipisici elit,
sed eiusmod tempor incidunt ut labore et dolore magna aliqua. 
```
will result in the HTML:

-  am Lorem ipsum dolor sit amet, consectetur adipisici elit,
sed eiusmod tempor incidunt ut labore et dolore magna aliqua. 

This is very annoying since it basically makes it impossible to write english texts in vimwiki and export them to HTML.

**Comment by Nudin** [comment]
Ideas to solve this:
- make it possible to disable alphabetically numbered lists
- Don't convert to list if there is only one bullet point
- Don't convert if the previous line is neither empty nor stating with an list-indicator

**Comment by EinfachToll** [comment]
I can't confirm the issue. Was this the exact text you put into the wiki file? If yes, it's clearly a but. `I` alone  should not be recognized as bullet point, `I)` should, but also not as bullet point, but as a numbered list item.

**Comment by Nudin** [comment]
>  Was this the exact text you put into the wiki file?

Yes.

But it seems that this bug only occurs in my not up to date and divergent branch, I'm currently using. I will try to rebase and check if the bug is vanished then.

**Comment by ranebrown** [comment]
@Nudin looks like this can likely be closed?

**Comment by ranebrown** [comment]
I'm going to close this under the assumption is was an issue in your branch.
