### ISSUE TITLE
:VimwikiDiaryIndex not opening diary index for the "current" wiki.

### ISSUE THREAD

**Issue by NausX** [vimwiki/vimwiki#543]
The next quote is from the manual.

    :VimwikiDiaryIndex*
        Open diary index file of the current wiki.

So, according to this, it *should* open the diary index for the *current wiki* but it's not the case, it keeps opening the diary index for the *first wiki* in the list. *Just a remark, It doesn't say what should happen if you're not in a wiki, which I think, if it was working. should fallback to the first of the list.*

Although, it seems there is a mismatch with the section about the mapping to this function. For `<leader>wi` the manual has the following.

    [count]<Leader>wi or <Plug>VimwikiDiaryIndex
            Open diary index file of the [count]'s wiki.

            <Leader>wi opens diary index file of the first wiki from
            |g:vimwiki_list|.
            1<Leader>wi the same as above.
            2<Leader>wi opens diary index file of the second wiki from
            |g:vimwiki_list|.
            etc.
            To remap: >
            :nmap <Leader>i <Plug>VimwikiDiaryIndex

    See also |:VimwikiDiaryIndex|

So, according to the part `<Leader>wi` it should open the diary index for the *first wiki* from the list.

Now I'm ambivalent, according to the first one, it should be a bug. According to the later one, it should be a request. Indeed, I think opening the diary for the current wiki would be more convenient.

That said, I've noticed same dissonances in the documentation for the functions `:VimwikiMakeDiaryNote` and `:VimwikiTabMakeDiaryNote`. As for the `:VimwikiDiaryIndex` function, The function documentation sates that it will open a diary note for the *current wiki*. Again that's a mismatch against the documentation for the mapping to those functions which says the default (no wiki number) would open a note for the *first wiki*. **Unlike** `:VimwikiDiaryIndex`, it does open the diary for the *current wiki* for **both**, the mapping and the function. Honestly, I think it's nice that way but perhaps the manual needs some update.

Have a good day.

**Comment by amitbeka** [comment]
:+1: 

In general, I think a better default for all global commands which take a wiki number is:
1) if a number is specified, use that wiki
2) else, use current wiki. current wiki = wiki this buffer belongs to, or wiki in current work directory
2) else, use first wiki

**Comment by ranebrown** [comment]
@NausX I agree there is quite a bit of inconsistency there which needs addressed. Thanks for the detailed description! If you are interested in creating a PR to fix this that would be awesome, otherwise its on the list.

**Comment by ranebrown** [comment]
@NausX @amitbeka Please test the changes on the `dev` branch and let me know if there are any problems.

**Comment by amitbeka** [comment]
Works great, thanks for fixing!
