### ISSUE TITLE
Why can't I bold inside a word ?

### ISSUE THREAD

**Issue by Doshirae** [vimwiki/vimwiki#545]
Hi

Currently, only whole words can be bolded/emphasized
 eg : if I want to write te**s**t, writing te\*s\*t doesn't work
I tried to put a zero width space in between the \* but that doesn't work either :/

Is there a reason for that ?

**Comment by EinfachToll** [comment]
Well, if you use regular characters like \* in a text as "meta characters", that is, for formatting, you always have the trade-off between being able to format everything you want to format and being able to still use \* in a normal way. I can't give you a convincing argument why Vimwiki behaves this way other than it's the way it is and it's difficult to change.
