### ISSUE TITLE
Highlighting and folds are acting super weird (+ tagbar involved somehow)

### ISSUE THREAD

**Issue by Doshirae** [vimwiki/vimwiki#549]
So, I got some really weird behavior with syntax highlighting and folds in my wiki files

First, when I open a wiki file, I got a messy syntax highlighting, especially visible with links (It happens also on markdown i think, so it might be something doing with my vimrc)
![Syntax highlighting when first opening a file](https://user-images.githubusercontent.com/19783971/44361965-dbe92a80-a4bf-11e8-8b87-4e412935bf5e.png)
That is a problem I had since my beginning with vimwiki, and I know I have to source my vimrc to get back to the "good" syntax highlighting
![After sourcing vimrc](https://user-images.githubusercontent.com/19783971/44362034-13f06d80-a4c0-11e8-8f05-a35b856d9a49.png)
But now, folds disappear

BUT
When I toggle Tagbar, now everything works the way it should : good syntax highlighting and folds are working
![Everything fine with Tagbar](https://user-images.githubusercontent.com/19783971/44362248-aa249380-a4c0-11e8-8a67-45b8b4f6ec85.png)

I'm really clueless on what could be causing that, hence the issue

If needed, here's my [vimrc](https://files.doshi.re/vimrc.txt)

**Comment by Doshirae** [comment]
I tried to erase my vimrc to keep only vimwiki to see if it was some sort of conflict with my vimrc, and it is, syntax higlighting and folds works nice now

I'm trying to find what makes this bug

**Comment by Doshirae** [comment]
Ok it was messing up with Rainbow parentheses

And when I source vimrc, folds are disabled because I think it gets back to my `foldmethod=marker`

**Comment by ranebrown** [comment]
Sounds like this was a configuration issue so I'm going to close it. Feel free to reopen if you think there is something else going on.
