### ISSUE TITLE
Blockquote Issues

### ISSUE THREAD

**Issue by mmbradle** [vimwiki/vimwiki#55]
#### Code

```
# Item 1
# Item 2
    Block Quote Text
# Item 3
```
#### Result

```
1. Item 1
2. Item 2 Block Quote
3. Item 3
```

The documentation for 2.1 claims: `Text started with 4 or more spaces is a blockquote`
This doesn't seem true in this case. Perhaps this is merely a documentation bug. However, the newline is awkward anyway, so it would be nice if this would work
#### Code

```
# Item 1
# Item 2

    Block Quote Text
# Item 3
```
#### Result

```
1. Item 1
2. Item 2 
    Block Quote
1. Item 3
```

Item 3 should be number 3, but it shows up as number 1
## Issue 3: BlockQuote at multiple list levels

GitHub style markdown allows for the following:

```
1. Outer Item 1
    1. Inner Item 1
        > quote 1
    1. Inner Item 2
2. Outer Item 2
> quote 2
```

Quote 1 and quote 2 show up at different levels. I cannot seem to achieve the same with vimwiki markdown
## Issue 4: No nested BlockQuotes

In GitHub style markdown this is achievable like this:

```
> This is the first level of quoting.
>
> > This is nested blockquote.
>
> Back to the first level.
```

It seems like this is a deficiency with not having a delimiting character dedicated to block quotes.
## Issue 5: Newlines in blockquotes are not honored

```
    Block quote line 1 
    Block quote line 2
```

This all shows up on one line.

Note: The desired result _is_ achievable with:

```
    Block quote line 1<br> 
    Block quote line 2
```

---

PS Thank you for vimwiki. It is a fantastic tool.

**Comment by tinmarino** [comment]
Fixed by last commit: (issue 2 and 5)

2. OK BlockQuote restarts list numbering
5. OK Newlines in blockquotes are not honored
    - Fixed: see the tests

1. NO No blockquote without newline
    - Same behavior as pandoc/markdown => This is normal

4. NO No nested BlockQuotes
3. NO BlockQuote at multiple list levels
    - Too hard to code (3-6h) for only litte:
    - 4 feature is useless and 
    - 3 feature is a lot of code refactoring to hold the state of the current blockquote prefix.

This issue is very old. To be clear, 3 and 4 remains some enhancement possibility but I doubt someone will take the time to code them in vim. Otherwise, please open a PR.

**Comment by brennen** [comment]
I only just noticed this, but the change in dc63a5da breaks blockquote handling for the documented 4-space indent entirely:

> Text which starts with 4 or more spaces is a blockquote.
>
>    This would be a blockquote in Vimwiki. It is not highlighted in Vim but
>    could be styled by CSS in HTML. Blockquotes are usually used to quote a
>    long piece of text from another source.

A `<pre><code>...</code></pre>` block isn't a blockquote.

It looks like blockquote rendering _in general_ is pretty broken at the moment. As far as I can tell from testing, nothing matches the documentation and multi-line quotes don't seem to work at all.

I'll try to write up a separate issue describing the situation.

**Comment by brennen** [comment]
> I'll try to write up a separate issue describing the situation.

Nevermind - I see this is already captured in #1007.
