### ISSUE TITLE
Renaming files does not update the reference links (I'm NOT using markdown)

### ISSUE THREAD

**Issue by Linkandzelda** [vimwiki/vimwiki#550]
I've seen similar issues posted here where when using `<Leader>wr` to rename the current wiki file, the links references in other files are not updated *when using markdown syntax*. However I have the same issue but I'm using the default vimwiki syntax.

**Comment by MarkQueppet** [comment]
I'm having the same problem, but ONLY if I change the default directory to something like:

`let g:vimwiki_list = [{'path': '~/notes/''}]`

If I remove that line and build a wiki in the default `~/vimwiki/ ` location, then it works fine. So I'm thinking it might be something with the rename function where it is grabbing the path. 

I'm on Windows too, so I'm wondering if that might have something to do with it?

**Comment by Georacer** [comment]
I have the same issue: Standard Wiki syntax, non-standard wiki path -> Page renaming doesn't work.

**Comment by Nudin** [comment]
Fixed in a2442466411ee7793de1c124a6a23a32eae9bda3 – update to latest 'dev'-branch and it should work.

**Comment by Georacer** [comment]
Thanks! I'm using Deon for package management. Do you know how I could
point it to the correct branch?

**Comment by Nudin** [comment]
You mean 'dein.vim'? According to it's page you can set the option `rev` to the branch-name (`dev`). If I read there help correctly something like:
```
		call dein#add('vimwiki/vimwiki', {'rev': 'dev'})
```
in doubt look at `:h dein-options`

**Comment by Georacer** [comment]
Ok, renaming seems to work now, BUT, I think another bug crept up:
After the renaming procedure, the other Vim windows I have opened get closed. This doesn't sound right...
