### ISSUE TITLE
Table goes to next line automatically when adding text

### ISSUE THREAD

**Issue by indeedwatson** [vimwiki/vimwiki#551]
This behavior started happening some time in recent weeks, not sure exactly when or why:

If I have this table
```
| asdf | asdf |
|      |      |
|      |      |
```
And I enter text in one of the rows, I expect this:
```
| asdf | asdf              |
|      |      sd sd dfdsdf |
|      |                   |

```
Instead I get:
```
| asdf | asdf |
|      |      sd sd d
fdsdf|
|      |      |
```

Why is this happening and how can I make it not break line automatically?

**Comment by ranebrown** [comment]
@indeedwatson  I would assume this is related some settings in your `.vimrc`. Take a look at `:h textwidth`, `:h formatoptions`, `:h fo-table`.

Try `:set textwidth=120` or a larger number and see if that solves your issue.

**Comment by ranebrown** [comment]
Please reopen if you require further help.

**Comment by indeedwatson** [comment]
Thanks for responding. It happens past the textwidth that I have set by default, and if I manually set it to something high like 300, it will break at the same point as before.

These are the formatting options I have for md files:

```vim
augroup Formatting
    autocmd!
    autocmd BufNew,BufRead *.txt,*.py,*.md,*markdown setlocal formatoptions=cqta
                \ textwidth=80 wrapmargin=80
augroup END
```

However, commenting out that and reloading vim doesn't change the behavior. It's probably not an issue with vimwiki if you can't reproduce it, but I can't figure this out.

**Comment by ranebrown** [comment]
Give the steps on [this page](https://github.com/vimwiki/vimwiki/wiki/Troubleshooting) a try. If that works it is likely something with your config so just start with no other plugins or settings and add things back in until you can isolate the problem.
