### ISSUE TITLE
automatic_nested_syntaxes  conflicts with nested_syntaxes

### ISSUE THREAD

**Issue by jfishe** [vimwiki/vimwiki#555]
In Vim 8.1.318

```
let s:wiki_1.nested_syntaxes = {'python': 'python', 'bash': 'sh', 'DOS': 'dosbatch', 'powershell': 'ps1'}
...
let g:vimwiki_list = [s:wiki_1] 
```

initially produces the what you'd expect, when no code blocks are present. However, when they are:

[{'template_default': 'default', 'path_html': 'C:\Users\fishe/Documents/vimwiki_html/html', 'auto_toc': 1, 'auto_tags': 1, 'index': 'main', 'path': 'C:\Users\fishe/Documents/vimwiki/', 'nested_syntaxes': {'powershell': 'ps1', 'DOS': 'dosbatch', 'bash': 'sh', 'dos': 'dos', 'python': 'python'}, 'list_margin': 0, 'diary_sort': 'asc', 'template_ext': '.tpl', 'template_path': 'C:\Users\fishe/Documents/vimwiki_html/templates/', 'css_name': '../css/style.css'}]

Vimwiki automatically adds 'dos' : 'dos', which sometimes prevents syntax highlighting per 'DOS' : 'dosbatch'. It may be the somewhat random order that items get added to nested_syntaxe--i.e., first match wins. Note how the input had python first but the result shows powershell first.

It also interferes with using 'dosbatch" for highlighting too. If {{{DOS is changed to {{{dosbatch, 'dosbatch' : 'dosbatch' gets added to nested_syntaxes. If it's appears after DOS, highlighting breaks.

Turning off automatic fixes the problem. Explicitly setting automatic_nested_syntaxes = 1 sometimes fixes the problem, but that may be the order in which automatic additions appear in the list.

```
let s:wiki_1.automatic_nested_syntaxes = 0
let s:wiki_1.nested_syntaxes = {'python': 'python', 'bash': 'sh', 'DOS': 'dosbatch', 'powershell': 'ps1'}
....
let g:vimwiki_list = [s:wiki_1] 
```

**Comment by hq6** [comment]
I am a bit confused by this issue.
Can you clarify what you mean by "highlighting breaks"? 
That is, it is highlighted with the wrong syntax or not highlighted at all?

Also, are you specifying the syntax explicitly or relying solely on automatic syntax detection?

**Comment by hq6** [comment]
Closing due to lack of response. Please reopen if there is more information and renewed interest.
