### ISSUE TITLE
Multiple wikis not working

### ISSUE THREAD

**Issue by michaelainsworth** [vimwiki/vimwiki#558]
I like to have a single wiki for personal organisation, and a per-project wiki. E.g., my "~/.vim/vimrc" file contains:

    let global_wiki = [{'path':'~/Organisation/', 'ext':'.txt'}]
    if !exists('g:vimwiki_list')
        let g:vimwiki_list = global_wiki
    else
        let g:vimwiki_list += global_wiki
    endi

And in "~/some_project/.vimrc" I have:

    let project_wiki = [{'path': 'doc', 'ext': '.txt'}]
    if !exists('g:vimwiki_list')
        let g:vimwiki_list = project_wiki
    else
        let g:vimwiki_list += project_wiki
    endif

When I type `echo g:vimwiki_list`, I see:

    [{'path': '~/Organisation/', 'ext': '.txt'}, {'path': 'doc', 'ext': '.txt'}]

When I type `<leader>ww` I'm taken to the first wiki, but when I type `2<leader>ww`, I see the error:

    Vimwiki Error: Wiki 2 is not registered in your Vimwiki settings!

**Comment by Nudin** [comment]
Try putting `call vimwiki#vars#init()` at the end of the `~/some_project/.vimrc`-file. (See https://github.com/vimwiki/vimwiki/issues/510#issuecomment-395651932)

**Comment by michaelainsworth** [comment]
That solved it, thank you! Perhaps this should be in the manual?

**Comment by Nudin** [comment]
>  That solved it, thank you! Perhaps this should be in the manual?

It is/will be: https://github.com/vimwiki/vimwiki/commit/44a1f3a6f36d9695029a5134a8ffd2809228d5e9
