### ISSUE TITLE
Error detected while processing function vimwiki#html#Wiki2HTML[1]..<SNR>127_convert_file[109]..<SNR>127_get_html_template

### ISSUE THREAD

**Issue by klivan** [vimwiki/vimwiki#565]
`:Vimwiki2HTML` shows an error
```
Error detected while processing function vimwiki#html#Wiki2HTML[1]..<SNR>127_convert_file[109]..<SNR>127_get_html_template:
line   20:
E484: Can't open file ~/.vim/bundle/vimwiki/autoload/vimwiki/default.tpl
Vimwiki: HTML conversion is done, output: /Users/user/vimwiki_html/
```
This file exists:
```
➜  ~ 18-09-24 19:53 ls -la ~/.vim/bundle/vimwiki/autoload/vimwiki/default.tpl
-rw-r--r--  1 user  staff  231 May 16 20:59 /Users/user/.vim/bundle/vimwiki/autoload/vimwiki/default.tpl
```
also, after finishing this command I can see output in `/Users/user/vimwiki_html/` but, it has 0 size:
```
➜  ~ 18-09-24 19:53 ls -la ~/vimwiki_html
total 0
drwxr-xr-x   4 user  staff   128 Sep 24 19:51 .
drwxr-xr-x+ 80 user  staff  2560 Sep 24 19:54 ..
-rw-r--r--   1 user  staff     0 Sep 24 19:51 index.html
-rw-r--r--   1 user  staff     0 Sep 24 19:51 style.css
```
Tested with `vim version 8.1.400` on MacOS, on two different laptops but with the same config. Also, on Linux the same config works perfectly.

Does anyone else have this issue or at least can recommend something?

**Comment by EinfachToll** [comment]
Looks like the call `readfile('~/.vim/bundle/vimwiki/autoload/vimwiki/default.tpl')` fails, but I can't see why. Maybe Vim on MacOS has problems with expanding the `~` in the filename? (Did you maybe start Vim as another user, e.g. as root?) What happens when you type `:echo readfile('~/.vim/bundle/vimwiki/autoload/vimwiki/default.tpl')` and `:echo readfile('/Users/user/.vim/bundle/vimwiki/autoload/vimwiki/default.tpl')`?

**Comment by klivan** [comment]
@EinfachToll This doesn't work
```
:echo readfile('~/.vim/bundle/vimwiki/autoload/vimwiki/default.tpl')
E484: Can't open file ~/.vim/bundle/vimwiki/autoload/vimwiki/default.tpl
```
but when I use `$HOME` instead of `~`
```
:echo readfile($HOME  . '/.vim/bundle/vimwiki/autoload/vimwiki/default.tpl')
['<!DOCTYPE html>', '<html>', '<head>', '<link rel="Stylesheet" type="text/css" href="%root_path%%css%">', '<
title>%title%</title>', '<meta http-equiv="Content-Type" content="text/html; charset=%encoding%">', '</head>'
, '<body>', '%content%', '</body>', '</html>']
```

**Comment by EinfachToll** [comment]
I changed it so that `~/` is not used for paths. Does it solve your problem?

**Comment by ranebrown** [comment]
Looks like this should be fixed. Please reopen if there is still a problem.
