### ISSUE TITLE
Feature request: Automatically add bullet when moving to new line after multi-line list item

### ISSUE THREAD

**Issue by WillDHB** [vimwiki/vimwiki#566]
Ordinarily, if you create a list with bullets, e.g.:

* First
* Second
* Third

...when you hit enter after the third line, the next line will automatically be indented and start with a matching bullet.  However, if you have a long item that uses hard line wrapping, when you move on to the next line, you won't get a bullet inserted automatically.

Is this something that is feasible to support?  (I understand that it might be cumbersome, since it would involve searching backward to the start of a paragraph to determine whether it was a list item)

**Comment by EinfachToll** [comment]
With the standard settings, you can press Shift+Return to insert the bullet after a multi-line item. Is this what you want? You can read more about that in `:h vimwiki-lists`.
