### ISSUE TITLE
Question: indent foldmethod

### ISSUE THREAD

**Issue by ryanp97** [vimwiki/vimwiki#567]
Is there any reason that there's not option for folding by indent? This seems like a common use case that is not supported by vimwiki at the moment.

**Comment by EinfachToll** [comment]
The setting `vimwiki_folding` is for fold methods which rely on Vimwiki syntax, so it must be managed by Vimwiki. Folding by indent is something which Vim can do on its own. So, if you want to fold by indent, you can use `let g:vimwiki_folding='custom'` and `set foldmethod=indent`.
