### ISSUE TITLE
Feature: Add markdown to HTML conversion support

### ISSUE THREAD

**Issue by danielb2** [vimwiki/vimwiki#57]
> only vimwiki's default markup will be converted to HTML at the moment

I don't see an open issue so this issue is merely to have an issue tracking that this be done.

**Comment by patrickdavey** [comment]
I did create a rubygem (vimwiki_markdown) if you want to try that.  It's very much a work in progress and does require some config, but it's working for me!

**Comment by giddie** [comment]
I've found the following thread hugely helpful in getting a good automatic markdown->html export set up:

https://gist.github.com/maikeldotuk/54a91c21ed9623705fdce7bab2989742

**Comment by danielb2** [comment]
I'm doing `pip3 install vimwiki_markdown` and in my config: `'custom_wiki2html': 'vimwiki_markdown'` + `'syntax': 'markdown', 'ext': '.md'`

would be nice if vimwiki would handle it natively tho.

**Comment by tinmarino** [comment]
[pandoc](https://pandoc.org/) is the recommended way of doing. Here is my [wiki2html](https://github.com/tinmarino/wiki/blob/ea8c264647fb674ff8e497b8592966e666ff3e7f/wiki2html.sh). There is the same in the doc.

As of 2020, there is still no native markdown conversion
If someone is willing to create a vimscript for the conversion [mdforvim](https://github.com/kurocode25/mdforvim) may be a good start.
Meanwhile, I prefer to close, just to narrow the dev scope.
