### ISSUE TITLE
`<c-s>` is mapped to toggle list item by inserting `""`, `TODO` and `DONE`??

### ISSUE THREAD

**Issue by llinfeng** [vimwiki/vimwiki#577]
I have global settings in my `~/.vimrc` that let `<c-s>` to save stuff, but have the following weird behavior of `<c-s>` ONLY in a `*.wiki` file:
* In the beginning, `<c-s>` in insert mode does not do anything.
* In a list, if in insert mode:  `<c-s>` inserts `TODO` to the top of the list content.
* In a list, if in normal mode: `<c-s>` should circle through `""`, `TODO` and `DONE`
![ctrlsproblem](https://user-images.githubusercontent.com/5890407/48283621-0dbcbe00-e42b-11e8-8953-2a7856697400.gif)

I have tried to drop the following mappings in both `~/.vim/ftplugin` and some `~/.vim/after/vimwiki.vim` file, but I still have this weird behavior anyways.
```
nnoremap <C-s> :wall!<CR>
inoremap <C-s> <ESC>:wall!<CR><right>
```

Please help identify if this is a Vimwiki setting that I may turn off. Thank you in advance!

**Comment by Nudin** [comment]
Hi, that does not sound familiar and I cannot repoduce it. What version are you using?

**Comment by llinfeng** [comment]
I did not opt to dig much into the problem, and have switched all the way over to the Markdown syntax for my Vimwiki configuration. The conversion was a bit bumpy, but as a side bonus, the wired behavior for `<c-s>` stops occurring.

Here goes the Python script I used when converting my exiting `*.wiki` files into `*.md` files: <https://github.com/llinfeng/Vimwiki_converter/blob/master/VimWiki_2_MD.py>
