### ISSUE TITLE
[announcement] vimwiki_markdown python version

### ISSUE THREAD

**Issue by WnP** [vimwiki/vimwiki#578]
I've just released avec python version of [vimwiki_markdown](https://github.com/WnP/vimwiki_markdown).

It support templates, including placeholders:

- `%title`
- `%date`
- `%nohtml`
- `%template`
- `%root_path%`

It also provide syntax highlighting out of the box in a github like fashion.

Feedback are welcome.

**Comment by ranebrown** [comment]
Moved this information to https://github.com/vimwiki/vimwiki/wiki/Connected-Plugins
