### ISSUE TITLE
Vim gets slow when edditing long wiki files

### ISSUE THREAD

**Issue by mMontu** [vimwiki/vimwiki#580]
In the last few days I noticed Vim got slower, but I couldn't figure out why. Now I found that the main reason is because I updated this plugin and I maintaining a few long vimwiki files open (~10k lines, ~150 level 2 headers).

For example, when switching to a tabpage it may take a long time (~6 seconds) to finish the redraw if the cursor will end on a wiki page of the new tab. Removing the [`BufEnter` autocmd that calls `s:setup_buffer_enter()`](https://github.com/vimwiki/vimwiki/blob/dev/plugin/vimwiki.vim#L236) solves the issue.

I also found that editing the long wiki files is slow, even though the fix for #225 is in place. For example, inserting  a newline on the middle of text with normal mode <kbd>o</kbd> take ~6 seconds, while insert mode <kbd>Enter</kbd> takes ~12 seconds, and removing those two mappings makes things faster.

I have little knowledge of this cod, and I'm wondering if it is possible to optimize the implementation of those functions, or if it is better to disable them only for long files.

**Comment by mMontu** [comment]
I don't have the context, but some things are little bit strange on the implementation of `s:setup_buffer_enter()`. For example, it seems strange to set the filetype every time the cursor enters the window with the wiki buffer -- it should be enough to set it only when the buffer is first loaded.

**Comment by EinfachToll** [comment]
Hm, I made a very long file as well and I see no such delays. The only thing which takes several seconds for me is when I save the buffer, because of the HTML conversion. Do you have folding enabled? This is known to cause huge lags (depending on the folding method).
You can try profiling:
- `:profile start foo | profile func *`
- do something which causes lags
- quit Vim
- look at the file `foo` to see which function needed that much time. Maybe you can upload the file here as a gist.

**Comment by mMontu** [comment]
The issue can be reproduce with [this file](https://github.com/vimwiki/vimwiki/files/2590344/delay.zip) by running the following:

    gvim -u NONE -U NONE -N -i NONE
    set nocompatible
    filetype plugin on
    syntax on
    let g:vimwiki_camel_case = 0  " Don't make links from CamelCased words
    let g:vimwiki_table_auto_fmt = 0 " Turn off table auto-formatting
    let g:vimwiki_autowriteall = 0
    let g:vimwiki_folding = 'expr:quick'    " Enable folding.
    let &rtp.=',~/.vim/bundle/vimwiki'
    source ~/.vim/bundle/vimwiki/plugin/vimwiki.vim
    e ~/tmp/delay.wiki
    tabe
    gt

The profiling is similar to the one from the previous comment:

    FUNCTIONS SORTED ON TOTAL TIME
    count  total (s)   self (s)  function
    10922  10.415964   2.362005  VimwikiFoldLevel()
    32365   8.047176   3.967159  vimwiki#vars#get_syntaxlocal()
    32365   4.080017   2.286404  vimwiki#vars#get_wikilocal()
    32367   1.793875             vimwiki#vars#get_bufferlocal()
      162   0.007335             vimwiki#u#count_first_sym()
        1   0.003906   0.001368  <SNR>13_setup_buffer_enter()
        1   0.001877   0.001479  <SNR>13_set_windowlocal_options()
        2   0.001118   0.000355  VimwikiFoldText()
        1   0.001020   0.000812  <SNR>13_setup_buffer_leave()
        9   0.000568             vimwiki#vars#get_global()
        1   0.000534   0.000437  <SNR>13_set_global_options()
        2   0.000211             <SNR>20_shorten_text()


But as you mentioned it seems to be caused by the `vimwiki_folding`, as removing it leads to the following:

    FUNCTIONS SORTED ON TOTAL TIME
    count  total (s)   self (s)  function
        1   0.035088   0.002956  <SNR>13_setup_buffer_enter()
        1   0.030936   0.030856  <SNR>13_set_windowlocal_options()
        1   0.000866   0.000758  <SNR>13_set_global_options()
        1   0.000330             vimwiki#vars#get_bufferlocal()
        7   0.000188             vimwiki#vars#get_global()

**Comment by mMontu** [comment]
@EinfachToll, do you think it is possible to have folding disabled automatically for large files? Or have a buffer variable (possibly set from modeline) that disables folds locally?

**Comment by mMontu** [comment]
The delay when editing long files with fold is solved by [Fast Fold plugin](https://github.com/Konfekt/FastFold).

**Comment by mMontu** [comment]
The delay when editing long files can be avoided by using the great plugin: [FastFold](https://github.com/Konfekt/FastFold)
