### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#582]
When the cursor is on a '-' and you press `+` you get a syntax error:

> Fehler beim Ausführen von "function vimwiki#base#follow_link[75]..vimwiki#base#normalize_link[6]..<SNR>37_normalize_link_syntax_n[37]..vimwiki#base#normalize_
> link_helper[4]..<SNR>37_clean_url":                                                                                                                           
> Zeile    6:                                                                                                                                                   
> E684: List-Index außerhalb des zulässigen Bereichs: 0                                                                                                         
> E15: ungültiger Ausdruck: url[0] == "www"                                                                                                                     
> Zeile    9:                                                                                                                                                   
> E684: List-Index außerhalb des zulässigen Bereichs: -1                                                                                                        
> E15: ungültiger Ausdruck: url[-1] =~ '^\(htm\|html\|php\)$'

**Comment by Nudin** [comment]
Should be easy to fix and is of low priority.

**Comment by EinfachToll** [comment]
Well, it was not extremely easy. Anyway, it's crazy that I never encountered this bug before.
