### ISSUE TITLE
VCS support

### ISSUE THREAD

**Issue by copyme** [vimwiki/vimwiki#583]
It would be nice if Vimwiki could detect whether the current wiki is versioned and if so called e.g., `git rm` on `VimwikiDeleteLink`. Such a support does not need to be very advanced, adding just a little support for git like `git add` and `git rm` would be sufficient for me.

**Comment by Nudin** [comment]
You are not the first to wish for such an git support. I think a lot of people use vimwiki inside a git repo. This feature request feels a bit like pandora's box to be open. Even through the functionality you proposed it relative simple to build in, it will probably be followed by a big amount of further feature requests. Currently there are only two recurring vimwiki developers and the list of issues is growing faster than we can work on it. :(

I will still consider it as one of my next projects. (But I have quite a few of those and it's open when I will have time again)

**Comment by copyme** [comment]
@Nudin do you have a PayPal for project donations? Let me put some support for this idea.

**Comment by jaywilliams** [comment]
I think such a feature would be a nifty tool, but in keeping with the UNIX philosophy, I'm included to agree with Nudin that it could very easily open pandora's box and lead to [featuritis](https://en.wikipedia.org/wiki/Feature_creep). As an alternative, I think it would make more sense to use fugitive.vim or create your own custom function which combined `VimwikiDeleteLink` and `git rm`. Keep VimWiki clean, fast, and focused.

**Comment by EinfachToll** [comment]
I must admit I don't even get the use case. I too use Git with my personal wiki, so what I do every now and then is `git add -u; git commit`, which removes deleted wiki files. I don't really see the value of adding and removing files automatically.

**Comment by ranebrown** [comment]
I don't think this is something we plan to implement (@Nudin please reopen this if you feel differently). Please take a look at [fugitive](https://github.com/tpope/vim-fugitive) or [gitgutter](https://github.com/airblade/vim-gitgutter)

**Comment by Nudin** [comment]
I still keep this in mind and think about if I can come up with a good way to do this. For now I keep this closed.
