### ISSUE TITLE
issue with d key

### ISSUE THREAD

**Issue by Brutus11111** [vimwiki/vimwiki#584]
Hi, I'm a bit confused. Probably not a software issue but a user issue. 

When working in a document, I can use the d key to cut a piece of text in visual mode. When I'm working in a document that's in my wiki directory, I can't. When I press the d key I get this: 

:'<,'>VimwikiMakeDiaryNote

I'm confused. My leader is set to ,

I use vimwiki to write documents. I want to be able to cut again in vim, because that's something I use very often. I don't know why it's trying to make a diary note, I'm not in my diary. Can you please assist?

**Comment by Nudin** [comment]
Hmm. I can't reproduce that. VimwikiMakeDiaryNote shouldn't be mapped to `d` in visual mode. Can you look at `:vmap` to see how it is mapped?

**Comment by Brutus11111** [comment]
I'm sorry, It's a user issue. 

I can't remember where I found this, but the part below was how I got vimwiki working. That came from a website after spending quite some time figuring out how it works. 


 " vimwiki - Personal Wiki for Vim
 " https://github.com/vimwiki/vimwiki
 set nocompatible
 filetype plugin on
 syntax on
 " vimwiki with markdown support
 let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown', '.  wiki': 'markdown'}
 
 let g:vimwiki_list = [
             \{'path': '~/vimwiki/index.wiki'},
             \{'path': '~/vimwiki/personal.wiki'},
                 \]
 au BufRead,BufNewFile *.wiki set filetype=vimwiki
 :autocmd FileType vimwiki map d :VimwikiMakeDiaryNote
 function! ToggleCalendar()
   execute ":Calendar"
   if exists("g:calendar_open")
     if g:calendar_open == 1
       execute "q"
       unlet g:calendar_open
     else
       g:calendar_open = 1
     end
   else
     let g:calendar_open = 1
   end
 endfunction
 :autocmd FileType vimwiki map c :call ToggleCalendar()


also, would be nice to press the comment button to actually post the reply. you can close this message.
