### ISSUE TITLE
Vimwiki needs a logo

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#589]
For a vim-plugin having a logo might not be the most important thing, but I still think it would be usefull to have an icon for the website (incl. favicon), the Github-Organisation, repositories and third party websites.
Maybe some vimwiki user can design a logo?

**Comment by EinfachToll** [comment]
There was a logo in the old project page: https://code.google.com/archive/p/vimwiki/
Not sure it would be a good choice (the font sizes are a bit off) but it resembles the Vim logo which I like a bit ;)

**Comment by Mantissa-23** [comment]
I can cook something up real quick, gimme a day or two.

**Comment by HugoNikanor** [comment]
The logo is available as an SVG file here: https://github.com/vimwiki/vimwiki-tst/tree/master/images. But at least on my current system it looks horrible (The string "VIM" and its drop-shadow use different fonts).

**Comment by ranebrown** [comment]
See #670

**Comment by illus0r** [comment]
My take on the logo

![Frame 18](https://user-images.githubusercontent.com/797993/69050804-32734a80-0a1c-11ea-9668-e7e739711522.png)

**Comment by joejobber** [comment]
I can't code that well. And as a business owner my time is too limited as it is (just ask my wife). My graphic skills are worse than those of an earth worm, so that won't help either.  ;-) 

But, if you would like a logo for vimwiki, there is something I can and am willing to do: sponsor a professionally-made logo. If you are open to this, please contact me and we'll arrange something.

**Comment by tinmarino** [comment]
@joejobber Yes I think a good logo would help Vimwiki's survival for years on so it will be useful for all of us

**Comment by joejobber** [comment]
I would be happy to sponsor this for the project. That way I can at
least contribute in my own manner and show my appreciation for a tool
that I find indispensable.

Just ask around for some quotes and let me know which one you would
prefer. If it is not prohibitively expensive, then I'll gladly pay the
invoice. I know what is "standard pricing" in this industry, so don't
worry about that remark.

Or maybe this would even be easier. After you have found a party that
can do what you need/like, let me place the order and pay for it. All
the intermediate communication with the designer can then be done
directly through you. Afterward I will transfer the deliverable and a
written statement that I transfer all rights to the project.

Is that workable?

With regards,

HdV

**Comment by tinmarino** [comment]
I don't know anyone, if someone here do, please contact @joejobber 
By the way, glad to see other profession than computerist using Vimwiki

**Comment by joejobber** [comment]
Oops, that was a bit dense of me... I assumed you represented the project, but this is public forum. How daft... Sorry for that.

But if of the "leads" think this is something we could do, then please contact me.

**Comment by Nudin** [comment]
Hi, I struggled for a long time to answer here. The issue it that I'm currently considered to be something like the lead of vimwiki – but I became this because no one else was around at the time. Therefore, there is currently no agreed procedure of how we decide things like this…
@EinfachToll @ranebrown @tinmarino any thoughts?

**Comment by Nudin** [comment]
To the original topic. Here are all three so far existing logos:
![current_logo](https://user-images.githubusercontent.com/509205/95689952-baee7100-0c14-11eb-804b-61987ba9431c.png)
![logo_illus0r](https://user-images.githubusercontent.com/509205/95689957-be81f800-0c14-11eb-8abc-76febbbb37f5.png)
![old_highres](https://user-images.githubusercontent.com/509205/95689961-c0e45200-0c14-11eb-8424-88179c33b550.png)

The first one is currently used in the README – but it's missing a square version for the favicon of the website.

**Comment by joejobber** [comment]
Ah, OK. Still thanks for all your efforts! Even if you are "only" an accidental lead, someone has to do it and we should be glad you took it upon you to do what noone else did. As far as a logo is concerned, if the others feel there is a need or even just a "that would be nice to have", please let me know. My offer still stands.

**Comment by monkinco** [comment]
Hi @, as I’m the author of the first logo, I will provide source files, icon, and alternative logo use cases for VimWiki. :-)
Will make a new Pull Request with all assets.

**Comment by tinmarino** [comment]
I did not vote ... my bad.
1/ @monkinco first log (but I prefer Vim above wiki, i.e vertical
2/ The W like a V (2 logo)
3/ The thrid which font I do not like (too sharp).


Thank you @monkinco for you contribution.
