### ISSUE TITLE
value of %diary in template file cannot be updated

### ISSUE THREAD

**Issue by johnmathews** [vimwiki/vimwiki#595]
In my .vimrc file I have tried to update the values of various vimwiki `diary_xxx` variables so that a template creates a valid html path for a link to my diary index page. 

However, it never updates and is always `%root_path/diary/diary_index.html`, even if `diary_rel_path` is changed in .vimrc.

Am I missing something?

**Comment by EinfachToll** [comment]
I don't understand the issue at all. Can you please state what you did, what you expected and what you saw instead?

**Comment by ranebrown** [comment]
Closing due to no response from author.
