### ISSUE TITLE
Get rid of all control characters

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#598]
We have quite a few unencoded control characters in the source code. These cause problems with some editors and tools and are hard to handle. We should find a way to eliminate them.

**Comment by ranebrown** [comment]
@Nudin can you give link to a few examples in the code?

Any specific editors/tools that you have had issues with?

**Comment by Nudin** [comment]
`$ grep -n '[[:cntrl:]]' *` shows the occurences:
```
lst.vim:1170:      normal! gi
lst.vim:1470:  normal! ox
lst.vim:1481:  normal! Ox
lst.vim:1495:    normal! gi

lst.vim:1522:    normal! "_cc
lst.vim:1552:  normal! gi
x
lst.vim:1562:    normal! gi

lst.vim:1571:    normal! gi

lst.vim.orig:1169:      normal! gi
lst.vim.orig:1469:  normal! ox
lst.vim.orig:1480:  normal! Ox
lst.vim.orig:1495:
lst.vim.orig:1553:x
lst.vim.orig:1564:
lst.vim.orig:1574:
tbl.vim:649:    let indentstring = repeat('	', indent / &tabstop) . repeat(' ', indent % &tabstop)
```

An example for a tool that has problem with them is `meld`. But also commandline-tools like (grep, cat, git…) behave weird since they'll "execute" them when printing out to stdout.

**Comment by ranebrown** [comment]
@Nudin this should be fixed now. If you have a chance can you take a look and see if I missed any and make sure everything still works as expected?

**Comment by Nudin** [comment]
Cool, thanks for taking care of this issue! Having this fixed will make it way easier to contribute to this part of the code. Sadly my computer broke and I therefore can't test it until I got a new one…
The diff looks good. If your confident that it's fixed, feel free to close.
