### ISSUE TITLE
Error with lists other than bulleted

### ISSUE THREAD

**Issue by szaffarano** [vimwiki/vimwiki#602]
I have an error with both markdown and vimwiki syntax when I use numbered lists.  When I type a number followed by a dot, write something and press enter:
```
1. Hello <enter>
```

then I get the following error

```
Error detected while processing function <SNR>132_CR[9]..vimwiki#lst#kbd_cr[36]..<SNR>164_cr_on_list_item[4]..<SNR>164_clone_marker_from_to[13]..<SNR>164_adjust_numbered_list_below[5]..<SNR>
164_guess_kind_of_numbered_item[5]..vimwiki#vars#get_syntaxlocal:
line   10:
E716: Key not present in Dictionary: number_kinds
E15: Invalid expression: g:vimwiki_syntax_variables[syntax][a:key]
Error detected while processing function <SNR>132_CR[9]..vimwiki#lst#kbd_cr[36]..<SNR>164_cr_on_list_item[4]..<SNR>164_clone_marker_from_to[13]..<SNR>164_adjust_numbered_list_below[13]..<SNR
>164_get_next_list_item[3]..<SNR>164_regexp_of_marker[4]..vimwiki#vars#get_syntaxlocal:
line   10:
E716: Key not present in Dictionary: number_divisors
E15: Invalid expression: g:vimwiki_syntax_variables[syntax][a:key]
```

I found that the "bug" (actually I don't know if it's a bug!) started with commit 75819ca23a1244416aba3db2843f77cc55c06e16 because until f9b890698599dd3aaf58b5ebe46bb4ebdb04ceb0 everything worked fine.

- Vim version:  2:8.1.0693-2
- Operating System: Debian GNU/Linux buster
- Vimrc file
```
set nocompatible
filetype plugin on
syntax on
```
- Vim plugins installed
  - [vim-plug](https://github.com/junegunn/vim-plug)
  - vim-wiki

**Comment by llinfeng** [comment]
I'd like to report the same problem on Windows 10. Switching away from the `dev` branch did revert things back to normal. I deleted the folder for the plugin completely, and specified the following for the setting for `Plug.vim`:

```
Plug 'vimwiki/vimwiki'
```

**Comment by EinfachToll** [comment]
Should be fixed now.

**Comment by szaffarano** [comment]
Thank you! It works fine now

**Comment by llinfeng** [comment]
Fixed here, too.
