### ISSUE TITLE
Finished multiline todo-items do not get hightlighted completely

### ISSUE THREAD

**Issue by TheSilvus** [vimwiki/vimwiki#605]
Config:

    let g:vimwiki_hl_cb_checked=1

Example:

    - [X] This is a todo-item
      that spans multiple lines

Only the first line is highlighted, the second one isn't.

**Comment by EinfachToll** [comment]
Try `let g:vimwiki_hl_cb_checked=2`. Admittedly, the doc is a bit inaccurate here.
