### ISSUE TITLE
Remove hover link behaviour

### ISSUE THREAD

**Issue by ghost** [vimwiki/vimwiki#61]
I just started to use vimwiki and already fall in love with. There is just one thing I dont like about. When hover over a link with the cursor, the link expands to [[Link]] with the surrounding brackets. Just because I select a link, doesnt mean I want to edit. So I'm asking, if there is a way to get rid of this behaviour? It is disturbing when browsing trough a list of links.

**Comment by hrj** [comment]
Can we have a `g:vimwiki_concealcursor`, similar to `g:vimwiki_conceallevel`, that is something that sets `concealcursor` automatically when editing vimwiki buffers?
