### ISSUE TITLE
Vimwiki menu only shows one entry if wiki paths all end with same folder name

### ISSUE THREAD

**Issue by ACGarland** [vimwiki/vimwiki#612]
I have about 12 different vim wikis and they all use the same ending folder name: `vimwiki`. (Make it easier for other tools to find them throughout the file system.)

For example:
```
/project1/vimwiki/
/project2/vimwiki/
/projectN/vimwiki/
```

The problem is that when vimwiki computes the index menu, it appears to only use the final directory name and since they all match, I wind up with a single entry (which activates the last wiki in my list of wikis).

One solution would be to enumerate matching names when mapping them to the index: `vimwiki1`, `vimwiki2`, ... 

A more useful approach would be to use the next higher level in the path when names match (`projectN` in my example). Of course those could theoretically match too in which case you'd have to move yet one more level up.  It seems reliable to assume that the paths _will_ differ at some level or they couldn't refer to different locations on the file system.

**Comment by hq6** [comment]
What is the *index menu* that you are referring to?

Is this the one generated in the GUI based on the setting of `g:vimwiki_menu`, or some other one?

**Comment by ACGarland** [comment]
Yes, that is the one.  On the mac version of vimwiki (under gvim) the menu sequence is: Vimwiki > Open Index > [list of known wikis]

It is the [list of known wikis] that all collapse down to a single entry, "vimwiki" in the case described since the final folder name in each path is apparently used to make the list.

**Comment by hq6** [comment]
I am able to reproduce this on Ubuntu in `gvim` so I can confirm it is not a platform-specific issue.

As I said on your other issue, if you would like to see this fixed sooner, a PR is welcome.

Otherwise, we will eventually get to it, but it will likely take a while since there are many bugs and issues yet to be triaged.

**Comment by ranebrown** [comment]
I think using named wikis as outlined in #477 would be a good way to solve this problem.
