### ISSUE TITLE
Error on following diary link

### ISSUE THREAD

**Issue by CharlesB2** [vimwiki/vimwiki#620]
I  get the following error when trying to follow a link in the diary index: (then ENTER takes me to the diary page). I have no problem in following a "normal" link.

```
"~/vimwiki/diary/2019-03-02.md" 3 lines --33%--
Error detected while processing function vimwiki#base#follow_link[58]..vimwiki#base#open_link[30]..vimwiki#base#edit_file:
line   23:
E518: Unknown option: f
Error detected while processing function vimwiki#base#follow_link[58]..vimwiki#base#open_link:
line   30:
E171: Missing :endif
Error detected while processing function vimwiki#base#follow_link:
line   58:
E171: Missing :endif
Press ENTER or type command to continue
```

Using Homebrew's Vim 8.1, on the latest master branch (`417490f30b3aaec600c19cfa59018cf2368dd87b`), with markdown syntax

**Comment by ptooley** [comment]
This happens for me on the main wiki page.  I can reproduce with a single link named [[Work TODO]] following the link gives exactly this error.

**Comment by ranebrown** [comment]
@CharlesB2 I'm haven't been able to reproduce this issue. Is it a specific link or any link on the diary page that causes the problem? Were your links built with `VimwikiDiaryGenerateLinks`?

**Comment by ranebrown** [comment]
If you are still having problems please test against the latest `dev` branch and reopen.
