### ISSUE TITLE
Diary Entry Template

### ISSUE THREAD

**Issue by akoutmos** [vimwiki/vimwiki#622]
Firstly, a HUGE thank you to an awesome plugin. I use it daily and appreciate the work put into it.

Next, I was wondering if it is possible to create diary entry templates. Every time I create a diary entry I outline the diary the same way and it would be nice to automate that. So if I create a new diary entry I would automatically get an entry filled out with:
```
Completed Today:
  -

Started Today:
  -

Notes For Tomorrow:
  -
```

**Comment by divramod** [comment]
Hey @akoutmos.

I also use the plugin daily and solve the task of templates with https://github.com/SirVer/ultisnips
Ultisnips is really powerful in the way, that you can insert the results of bash scripts like 

```
snippet d1f "Diarynote Tpl Full (Tomorrow)" w
# [ ] `env LC_ALL=en_US.utf8 date --date="tomorrow" "+%Y.%m.%d %A"`

Completed Today:
  - ...
endsnippet
```

Hope that helps.

**Comment by akoutmos** [comment]
Thanks for the good idea! I've always had issues with UltiSnips in the past as I could never get it to pick up my local snippets files....but I put some time in and got it working :).

**Comment by jumbosushi** [comment]
Also a daily user :raised_hands: Did some googling and found that you can use vim's `r` command to copy a file content into the currently opened file

```vimscript
:r <FilePath>
``` 

Added a quick shortcut in my `.vimrc` to make this easier with `Space + L`

```vimscript
nmap <Space>l :r ~/wiki/diary/template.md<CR>
```

**Comment by FrostyX** [comment]
For the record, I've described my solution to diary templates in this post http://frostyx.cz/posts/vimwiki-diary-template

**Comment by mkirchner** [comment]
Another simple starting point is:

```
autocmd BufNewFile ~/.vimwiki/diary/[0-9]*.md :silent 0r !echo "\# `date +'\%Y-\%m-\%d'`"
```

Note: replace the `#` with `== ... ==` for vimwiki markup.

**Comment by amenat** [comment]
Just a note for future readers who might refer this. `autocmd-pattern` resolves symlinks. 


From Vim help file:
> When there is a '/' in the pattern, Vim checks for a match against both the
   short file name (as you typed it) and the full file name (after expanding
   it to a full path and resolving symbolic links).



Hence it would be better to use something like:
```
autocmd BufNewFile */diary/[0-9]*.md : <command you want to execute>
```

**Comment by libinvarghese** [comment]
Adding to @mkirchner, the below will fetch the date to transform from the buffer file name & insert it a header

```
autocmd BufNewFile ~/.vimwiki/diary/[0-9]*.md :silent %!echo "\# `date -d '%:t:r' +'\%A, \%B \%d \%Y'`\n"
```

eg: For file *2022-07-14.md* inserts `# Thursday, July 14 2022`
