### ISSUE TITLE
Still getting vimwiki links instead of markdown links on :VimwikiDiaryGenerateLinks

### ISSUE THREAD

**Issue by maikeldotuk** [vimwiki/vimwiki#623]
This has been mentioned before and has been "fixed" before but it doesn't work in my current configuration:

This is what I get:

```
---
title: Diary
---
# Diary

## 2019

### March
  * [[2019-03-07|Moving out]]
```
As you see the titles were correctly added in markdown, the links were not. 

So it knows my current config for syntax is markdown but it just ignores it with the links. Could someone please help with this?

**Comment by ranebrown** [comment]
This is not the behavior that I'm seeing. Have you tried using a minimal `.vimrc` with only vimwiki settings enabled to isolate the issue? Can you provide your configuration so I can attempt to duplicate the issue?

**Comment by cjtapper** [comment]
I'm also not seeing this behaviour. Markdown links are being correctly generated.

**Comment by ranebrown** [comment]
I'm closing this since there hasn't been a response. There are a few additional commands that were not generating markdown links which have been fixed in #529. This PR should be merged to the `dev` branch soon.

@maikeldotuk If you are still having issues first test out the `dev` branch and then reopen this. Thanks!

**Comment by ionescu77** [comment]
I am also using markdown, and diary (and `:VimwikiDiaryGenerateLinks`).
For anyone landing here and experiences the same issue as above

It works as expected. In the vimwiki help there is a section about `list_margin` parameter.

After I have set it to zero (as recommended in the help), then the indentation for the links dissapeared and I can render the links in gollum and github wiki.

In my case in `.vimrc` changed:
```vim
  let g:vimwiki_list = [{'path': '~/my_site/',
                       \ 'syntax': 'markdown', 'ext': '.md'}]
```
to:
```vim
  let g:vimwiki_list = [{'path': '~/my_site/',
                       \ 'syntax': 'markdown', 'ext': '.md','list_margin': 0}]
```

From the help:
```vim
*vimwiki-option-list_margin*
------------------------------------------------------------------------------
Key               Default value~
list_margin       -1

Description~
Width of left-hand margin for lists.  When negative, the current 'shiftwidth'
is used.  This affects the appearance of the generated links (see
|:VimwikiGenerateLinks|), the Table of contents (|vimwiki-toc|) and the
behavior of the list manipulation commands |:VimwikiListChangeLevel| and the
local mappings |vimwiki_glstar|, |vimwiki_gl#| |vimwiki_gl-|, |vimwiki_gl-|,
|vimwiki_gl1|, |vimwiki_gla|, |vimwiki_glA|, |vimwiki_gli|, |vimwiki_glI| and
|vimwiki_i_<C-L>_<C-M>|.

Note: if you use Markdown or MediaWiki syntax, you probably would like to set
this option to 0, because every indented line is considered verbatim text.
```

So I would say in help that it also affects the indentation of `VimwikiDiaryGenerateLinks`

**Comment by ionescu77** [comment]
Thank you all for this great tool! 🙌🏼
