### ISSUE TITLE
Maintainer discussion: Let's have a consistent threshold for merging to master!

### ISSUE THREAD

**Issue by hq6** [vimwiki/vimwiki#628]
@Nudin @ranebrown @EinfachToll 

I recently went through the notes in `CONTRIBUTING.md` and see the following text:

> Whenever a reasonable set of changes has piled up in the `dev` branch, a release is done.

Here's the current set of changes between `dev` and `master`.

```
[hq6@hq6-x1:~/.vim/pack/plugins/start/vimwiki$ git diff --stat origin/master
 CONTRIBUTING.md            |  55 +++++++++++++++++++++++++++++++++++++++++++++++
 README-cn.md               |   2 +-
 README.md                  |  22 +++++++++++++------
 autoload/vimwiki/base.vim  | 192 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------------
 autoload/vimwiki/diary.vim |   5 +++++
 autoload/vimwiki/html.vim  |  28 +++++++++++-------------
 autoload/vimwiki/lst.vim   | 124 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------------
 autoload/vimwiki/style.css |   1 +
 autoload/vimwiki/vars.vim  | 291 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------------
 doc/vimwiki.txt            | 166 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------------------------------
 ftplugin/vimwiki.vim       |  12 +++++------
 plugin/vimwiki.vim         |  42 +++++++++++++++++++-----------------
 12 files changed, 635 insertions(+), 305 deletions(-)
```

I think it would be good to roughly quantify "a reasonable set of changes", so that `dev` does not run too far ahead of `master`, so that improvements / bugfixes introduced by PR's can make it out to a wider audience in a timely manner. The current set of changes represent roughly 1000 LOC of change, and seems reasonable to me.

How do you folks feel about merging this old set of changes into master before we start merging the new set of pull requests into dev? 

Please share your thoughts on why a bigger / smaller number of changes would be a better threshold.

**Comment by ranebrown** [comment]
I think there are a couple other issues as well:

1. `CONTRIBUTING.md` mentions creating tags for each release but this hasn't been done since v2.3 in 2016.

2. Many of the pull requests are to the master branch. There should probably be a link to `CONTRIBUTING.md` on the master readme.

**Comment by hq6** [comment]
1. I think we should deal with creating tags for each release as a second issue to rolling over changes from `dev` to `master`.
2. Actually, I think `CONTRIBUTING.md` should be available on the master branch, to inform people that they should make PR's against the `dev` branch. The fact that many PR's are to the master branch is further reason why we might want to keep `master` not very far behind `dev`.

Let's wait for one of @Nudin or @EinfachToll to comment on this before we act though, since they probably know more about the history of this issue.

**Comment by ranebrown** [comment]
Related to #504

**Comment by Nudin** [comment]
Yes, I think we should definitely release a new version. I also would propose to release new version more often in the future. For the future we should do all the development strict on `dev` and only "back-port" pure bugfixes without risk of regressions and changes in the documentation back to `master` in between releases.

**Comment by ranebrown** [comment]
Let's move discussion to #638
