### ISSUE TITLE
VimwikiGenerateTags does not support markdown links 

### ISSUE THREAD

**Issue by project-repo** [vimwiki/vimwiki#639]
Hi,
I recently  discovered vimwiki and I am enjoying it greatly. Great work guys! However, while attempting to use markdown with vimwiki, I discovered that I was not able to use VimwikiGenerateTags since it continued to use the vimwiki syntax. After some investigation, I found that the reason for this appears to be the wikilink_prefix/sufifx variable, defined in autoload/vimwiki/vars.vim, line 107-108. This prefix and suffix seems to be hardcoded so there is no possibility in changing the syntax. My vimwiki version is the HEAD on the master branch. I am sorry if I missed something obvious.
cheers,
project-repo

**Comment by ranebrown** [comment]
This is something that should be fixed with PR #634. It should be merged to the `dev` branch soon but won't be available on `master` until the v2.5 release. See #638 to keep up to date on the release status.

**Comment by ranebrown** [comment]
I decided to leave this open until the merge is actually complete.

**Comment by project-repo** [comment]
Awesome, I look forward to the release. Amazing support guys! Never in my entire time on github has anyone responded so quickly!

**Comment by ranebrown** [comment]
Should have basic support now but the generated descriptions aren't working all the way yet. They currently just use the first found header. #635 fixes this behavior.
