### ISSUE TITLE
tags not working on second machine

### ISSUE THREAD

**Issue by gmoneymagna** [vimwiki/vimwiki#647]
Hello. I am very excited about vimwiki. For my use, I need it to be syncd across multiple machines. To accomplish this I use an SQlite server. I have transferred the .wiki and .md files fine and the links work and etc. However, the tags don't work. They don't show as syntax'd when in the :tag: format and they do not show up in a tagsearch. I cannot make new functional tags.

When I try to run 

:VimwikiRebuildTags
:VimiwikiGenerateTags
:Vimwiki-build-tags

in vim i can an error 'E492: Not an editor command: Vimwiki-build-tags' and etc.

I assume there is a metadata file somewhere that holds tag information? I see it referenced in the README but I cannot find it anywhere in my vimwiki directory on my original machine (where tags still work).

Thanks!

**Comment by ranebrown** [comment]
There should be a hidden `.tags` file in your wiki directory.

You should be able to rebuild the tags on a new machine though and the syntax highlighting should work. You probably have some sort of configuration issue on the second machine. You can try the steps on the [troubleshooting page](https://github.com/vimwiki/vimwiki/wiki/Troubleshooting#minimal-vimrc).

**Comment by gmoneymagna** [comment]
Thanks I will check the troubleshooting page. However, in the original machine I cannot find a .tags file. The tags work so I assume there is one. It definitely should be in the wiki correct? Because it would make sense if it was stored somewhere else and then it wasn't transferred when I shared the wiki. I searched throughout my entire ~/vimwiki directory using ls -al to show hidden files and couldn't find it.

**Comment by ranebrown** [comment]
It should be in your wiki directory. Can you copy your vimwiki settings here? Also, what is the output of `set tags?` after opening your wiki?

**Comment by ranebrown** [comment]
This command should also print the path to your tags file `:echo vimwiki#tags#metadata_file_path()`

**Comment by ranebrown** [comment]
Please reopen if you still need help.
