### ISSUE TITLE
VimwikiShowVersion broken on dev

### ISSUE THREAD

**Issue by hq6** [vimwiki/vimwiki#649]
This issue was introduced in `3396e87dbee617cbf0aa5b6ee9bcfe21270cc19a`.

### Steps to reproduce

1. Open Vim.
2. Type `:VimwikiShowVersion`
3. Observe output:
```
Error detected while processing function <SNR>25_get_version:
line    1:
E15: Invalid expression: s:plugin_vers != -1 echo "Stable version: " . s:plugin_vers
Press ENTER or type command to continue
```
@ranebrown , I apologize for missing this when reviewing your PR, but it looks like the numbering changes broke our show version command.

**Comment by hq6** [comment]
This has been fixed on `dev`.

**Comment by ranebrown** [comment]
Thanks for the catch! Must have accidentally joined those two lines.
