### ISSUE TITLE
Regression: Horizontal table delimiter being treated as element in the dev branch

### ISSUE THREAD

**Issue by hq6** [vimwiki/vimwiki#650]
I found this issue on the `dev` branch but not the `master` branch. The current commit is `3396e87dbee617cbf0aa5b6ee9bcfe21270cc19a`, although the issue was likely introduced earlier.
This issue is reproducible in the default syntax, with no customizations.

### Steps to Reproduce:

1. Copy the following table into a Vimwiki file.
```
| Example headline 1 | Example 2                    |
|--------------------|------------------------------|
| one                | two                          |
| three              | four                         |
```
2. Put the cursor on line 2, column 1.
3. Enter insert mode with `i`. 
4. Type `<Tab>`.
5. Observe that the table now looks like the following. Note the extra spaces between the `|` and `-` characters on line 2.
```
| Example headline 1   | Example 2                      |
| -------------------- | ------------------------------ |
| one                  | two                            |
| three                | four                           |
```

### Why is this not just an aesthetic problem?

After the extra spaces are added, Vimwiki no longer recognizes line 2 as a horizontal delimiter. Thus, if one tries to use table alignments `---:` and `:---`, they have no effect.

**Comment by hq6** [comment]
@lyokha I performed a `git bisect` and found that the problem was introduced in `5e4a89c89889c2e630cc97c620bc138c7efa5adf`.

**Comment by lyokha** [comment]
I can make *wrong* table

```
| Example headline 1   | Example 2                      |
| -------------------- | ------------------------------ |
| one                  | two                            |
| three                | four                           |
```
by pressing `Tab` in Insert mode on the separator line. This also happens when pressing `gqq` over the separator line. As soon as `gqq` re-formats all the table, I suspect that the older implementation had the same effect.

**Comment by hq6** [comment]
@lyokha , I was referring to pressing `Tab` in insert mode on the separator line creating the _wrong_ table.
Pressing `gqq` also has this effect.

However, neither of those actions has this effect on the `master` branch.

**Comment by lyokha** [comment]
Ok, I will look at this.

**Comment by lyokha** [comment]
Yes, this was my fault: the separator line required special treatment (it shouldn't be `fmt_row`'ed). Here is a small patch that fixes this issue:

```diff
diff --git a/autoload/vimwiki/tbl.vim b/autoload/vimwiki/tbl.vim
index 8bd9fcf..10385de 100644
--- a/autoload/vimwiki/tbl.vim
+++ b/autoload/vimwiki/tbl.vim
@@ -254,7 +254,7 @@ function! s:get_rows(lnum, ...)
   while lnum <= line('$')
     let line = getline(lnum)
     if s:is_table(line)
-      if lnum == a:lnum
+      if lnum == a:lnum && !s:is_separator(line)
         let cells = vimwiki#tbl#get_cells(line)
         let clen = len(cells)
         let max_lens = repeat([0], clen)
```

**Comment by Nudin** [comment]
@lyokha sure, that would be great!
