### ISSUE TITLE
Proposed policy change: Keep changelog up to date in dev-branch

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#652]
One of the hardest things to do when releasing 2.4 was to search through all the commits for relevant changes and update the Changelog in `doc/vimwiki.txt`. Therefore I propose that we update the changelog with every PR. This way also people using `dev` can know what changes.
@hq6 @ranebrown If you are ok with this we should update the CONTRIBUTING.md an ask people to update the changelog whenever they do a non-trivial change. And we should add all the changes we made in dev so far.

**Comment by Nudin** [comment]
Another idea would be to also ask all first-time-contributers to add there name to the contributers-section.

**Comment by ranebrown** [comment]
Sounds like a good idea to me. I've been trying to keep the changes updated on the [release project](https://github.com/vimwiki/vimwiki/projects/2) so that can probably be used as a starting point.

**Comment by hq6** [comment]
This makes a lot of sense.

**Comment by ranebrown** [comment]
I think I added everything up to this point to the changelog. We should just need to make sure any new PRs or issues we close include updates.
