### ISSUE TITLE
Raw URL shortening leaves cosmetic overhang on long URLs 

### ISSUE THREAD

**Issue by hq6** [vimwiki/vimwiki#653]
This issue is present on the `dev` and `master` branches in the default vimwiki syntax, with no special vimwiki settings.

### Steps to Reproduce.

1. Set your terminal width to 100. This emulates what happens when running vim inside a tmux pane.
2. Open a wiki file.
3. Paste in a long URL such as `https://www.forbes.com/sites/alexkonrad/2019/04/02/andreessen-horowitz-is-blowing-up-the-venture-capital-model-again/#34cd333e7d9f`.
4. Move the cursor to a different line.
5. Observe that the shortened URL spans two lines instead of one.

```
https://www.forbes.com/~  
#34cd333e7d9f             
```

Note that this issue does not arise when the terminal is sufficiently wide to hold the full URL on a single line in edit mode.

**Comment by ranebrown** [comment]
This sounds related to Vim settings not a Vimwiki issue to me. I don't see this behavior, maybe it is related to your `formatoptions`? Are you seeing the same thing using a minmal vimrc like on the [troubleshooting page](https://github.com/vimwiki/vimwiki/wiki/Troubleshooting#minimal-vimrc)?

**Comment by ranebrown** [comment]
You could also try `set paste` which should disable all formatting options.

**Comment by hq6** [comment]
Yes, this reproduces under the minimal vimrc setting as well. I just tried again to make sure.

`set paste` only affects formatting during the paste, rather than post-processing after the paste, as far as I know, but I tried it anyways and it has no effect.

The key step in reproducing this issue for me is that the terminal width has to be less than the length of the full URL.

**Comment by ranebrown** [comment]
Are you using `set wrap`?

From the documentation:
>   When using the default |wrap| option of Vim, the effect of concealed links
    is not always pleasing, because the visible text on longer lines with
    a lot of concealed parts may appear to be strangely broken across several
    lines. This is a limitation of Vim's |conceal| feature.

**Comment by hq6** [comment]
Ah, you nailed it! It seems that my Vim has `set wrap` on by default, so even with the minimum configuration, it was still exhibiting the behavior. After doing `set nowrap`, the issue is resolved.

Closing this issue until it becomes fixable without source code changes to Vim.

NB: It looks like `conceal` is not the only way to hide text, but I do not know if the other mechanism do not have this limitation.
