### ISSUE TITLE
Release v2.4.1

### ISSUE THREAD

**Issue by ranebrown** [vimwiki/vimwiki#659]
As a bug fix I think we should release v2.4.1 incorporating the fix in #654. I'm not sure if the best way to handle this is to cherry-pick c21de17a345eeb4baefb470e4575532f044a91e8 or to revert that commit and create a new branch with those changes and merge that to both `master` and `dev`.

My concern is that cherry-pick might cause conflicts down the road when merging `dev` to `master` for the v2.5 release. I'm not that familiar with how cherry-pick works in that situation though.

@Nudin @hq6 what do you think?

**Comment by ranebrown** [comment]
Also, are there any other important bug fixes we should include with this?

**Comment by Nudin** [comment]
Yes, thanks for bringing that up. I was also about to propose a 2.4.1-release. Cherry-picking will probably result in a merge-conflict, but I don't see any better option. Resolving the merge should hopefully be not that hard. Worst case we can rollback to `v2.4` and instantly merge `dev` – right?
c21de17 propably needs e9115047 to be added first.
Other commits we might add are 308e205 cdc9940 32c7f289 54d1a997

**Comment by Nudin** [comment]
Note: before merging 308e205 we should make new screenshots and readd them.

**Comment by monkinco** [comment]
> Note: before merging [308e205](https://github.com/vimwiki/vimwiki/commit/308e2056f6153798934fcc829e408eb50dafb227) we should make new screenshots and readd them.

I will add new screenshots today with new logo proposal. 
Any special wishes regarding screenshots?

**Comment by monkinco** [comment]
Other idea, what about making screen recording using asciinema like that: https://asciinema.org/a/137065

**Comment by ranebrown** [comment]
Good point.
> Worst case we can rollback to v2.4 and instantly merge dev – right?


I think another one a lot of people would like to see added is f40f0544416a41665950346da0565888a256d9b5. Also, b77473960a2898a6d325ccb571c1cc4ab886b6c3 would be useful.

@monkinco As for screenshots I think it would be good to put at least one using markdown syntax. A screen recording would also be nice but that might be something that could go in the [wiki](https://github.com/vimwiki/vimwiki/wiki) and maybe just link to it?

**Comment by hq6** [comment]
@ranebrown @Nudin, I think that cherry-picking bug fixes is fine, but [this post](https://devblogs.microsoft.com/oldnewthing/20180312-00/?p=98215) raises some interesting concerns with it.

How would we feel about rewriting the history of the `dev` branch so that the `master` branch remains a proper parent of it, and the cherry picking doesn't cause headaches on the next merge?
I have mixed feelings about it myself (trading off future merge conflicts and confusing history for requiring people to `git reset --hard origin/dev`), so I'm curious about what you folks think.

**Comment by ranebrown** [comment]
I think the method of using branches for specific bug fixes would work if we adopted that in the future. It would probably be too much work to try and resolve everything at this point though since all the fixes are already commits on `dev`. I think we should go ahead and cherry pick and then maybe just reset master to 2.4 as @Nudin suggested prior to the 2.5 release.

**Comment by ranebrown** [comment]
@monkinco Any progress on the screenshots, logo, and screencast?

@Nudin Are you planning on handling the release again?

**Comment by hq6** [comment]
@ranebrown, I suspect that rewriting history on the `master` branch later is going to cause more pane than rewriting history on the `dev` branch, since people checking out the `dev` branch will likely have at least a little more git experience than people using only the `master` branch.

**Comment by monkinco** [comment]
This is the best thing that I can think of right now, but I'm working on few other concepts.

[Logo Proposal](https://imgur.com/a/SKJPI53)

**Comment by monkinco** [comment]
As for the screencasts themselves, in fact, the best option is to write a complete guide and use them in there. Initially, it could be written using GitHub Wiki but also later used at the official website.

**Comment by Nudin** [comment]
> @ranebrown, I suspect that rewriting history on the `master` branch later is going to cause more pane than rewriting history on the `dev` branch, since people checking out the `dev` branch will likely have at least a little more git experience than people using only the `master` branch.

I defnitly wouldn't rewrite history of any of the both branches. Worst case scenario would be reverting the charry-picked commits with an undo-commit.

> @Nudin Are you planning on handling the release again?

Yes, I will release it in the next few days. I've been waiting for the screenshots – will add them, but will wait with the logo for 2.5 – considering the current developement speed 2.5 won't take that long anyway.

**Comment by Nudin** [comment]
2.4.1 is out. I only included bugfixes and the update of README, Sreenshots and CONTRIBUTING, most other patches mentioned above where already in 2.4 or fixed bugs introduced in dev.
I did not include the logo nor #f40f054 since I think a bugfix release should only contain bug fixes and 2.5 seems not to distant.
