### ISSUE TITLE
feature request: g:vimwiki_folding = 'done'

### ISSUE THREAD

**Issue by johnyoonh** [vimwiki/vimwiki#667]
I think it would be helpful to fold task items that were completed [X] with foldexpr expression so that users can focus on items that are not yet completed.

Suggested solution that should be improved...:
  
```
set foldmethod=expr
set foldexpr=FoldLevel(v:lnum)
set foldlevel=0

function! FoldLevel(linenum)
  let linetext = getline(a:linenum)
  if linetext =~ '^\s*-\s*\[[|×|X]\]'
    let level = indent(a:linenum) + 1
  endif
  return level
endfunction
```

**Comment by ranebrown** [comment]
@johnyoonh does using `let g:vimwiki_folding = 'custom'` allow you to define this fold function and work as desired? If so I think it would make sense to place this example on a new [wiki](https://github.com/vimwiki/vimwiki/wiki) page as mentioned in #700.
