### ISSUE TITLE
Wiki Links displaying brackets at all times on a Mac?

### ISSUE THREAD

**Issue by jonathonpday** [vimwiki/vimwiki#674]
In my vimwiki links on my Macbook with the oh-my-zsh theme I am seeing the wikilinks not display properly as  the brackets are clearly showing at all times, even when I am not on the selected lines. I have tried changing colorschemes but that has no impact.

![Screenshot 2019-04-16 at 07 09 20](https://user-images.githubusercontent.com/36718060/56186258-c6101300-6016-11e9-8238-bd947dac1426.png)

I use this vimwiki across two computers with the same vimrc accessed via dropbox and there is no issue with my Linux terminal, jut my macbook one.

my vimrc is:

```set number
syntax on
set tabstop=2
set softtabstop=2
set expandtab
set cursorline
set showmatch
set wildmenu
colorscheme slate
filetype indent on
filetype plugin on
set nocompatible
set backspace=indent,eol,start
let g:vimwiki_list = [{'path': '$HOME/Dropbox/vimwiki'}]
set backupdir=$HOME/Dropbox/vimtmp
set directory=$HOME/Dropbox/vimtmp```

It was displaying normally before vut changed wthout a clear reason about 2 weeks ago.

If anyone has any idea what the issue might be I would be very grateful.

**Comment by ranebrown** [comment]
This is most likely related to `conceallevel`. What is the value of `:set conceallevel?`

**Comment by jonathonpday** [comment]
I don't appear to have one.

When I type in `:set conceallevel` in vim I get `E519: Option not supported: conceallevel`.

**Comment by ranebrown** [comment]
You need a version of Vim with that option compiled in. Typing `:version` or `vim --version` should show you what features are enabled. I would take a look at Macvim or compile from source.

**Comment by jonathonpday** [comment]
Cheers have downloaded Macvim, it works :)

**Comment by sushovannits** [comment]
I downloaded macvim but still not sure how to make this work. I still see [[]] in links and __ in italics.
What should the conceallevel be?
