### ISSUE TITLE
Create Guide & Screencast

### ISSUE THREAD

**Issue by monkinco** [vimwiki/vimwiki#676]
I'm working on a simple website to replace [vimwiki.github.io](https://vimwiki.github.io).

I would like to create Documentation page based on [vimwiki.txt](https://github.com/vimwiki/vimwiki/blob/master/doc/vimwiki.txt) using this [approach](https://vimhelp.org/vim_faq.txt.html). Every time there's a change in the repository it will automatically update itself. 

In addition to that we could add a screencast to each section describing each future and option. 

----

Does VimWiki project have an official domain? :)

**Comment by ranebrown** [comment]
I don't think there is an official domain. How would the website hosting work and how would access be controlled for editing? The nice thing about using github.io is the site is tied to the repository.

**Comment by monkinco** [comment]
> I don't think there is an official domain. How would the website hosting work and how would access be controlled for editing? The nice thing about using github.io is the site is tied to the repository.

Of course it will be hosted on GitHub, it's fastest and easier way to do so. :)
vimwiki.org is free to buy, so it could be nice addition to website itself, as GitHub Pages supports custom domains.

**Comment by ranebrown** [comment]
Oh nice, didn't know you could use a custom domain. I think it's a good idea!

**Comment by monkinco** [comment]
> Oh nice, didn't know you could use a custom domain. I think it's a good idea!

Now question is, who will buy (🎁) this domain?

**Comment by hq6** [comment]
I think we may have to stick with vimwiki.github.io until @EinfachToll (or some successor he chooses) can speak to this, since he is still the  owner of the project. Even if someone effectively donated the $$ to buy the domain, I think there would concerns about the trademark on the name if it wasn't owned by the same person who owned the project.

@monkinco I hope your new site isn't dependent on having a custom domain?

**Comment by monkinco** [comment]
> @monkinco I hope your new site isn't dependent on having a custom domain?

No it's not, but would be a nice addition, and would be nice to secure it for the future. :)

**Comment by ranebrown** [comment]
@monkinco when you have a working version of the site let us know and we can figure out the domain part later on since it is just a nice to have addition.

**Comment by ranebrown** [comment]
@monkinco have you made any progress on this?

**Comment by monkinco** [comment]
> @monkinco have you made any progress on this?

Yes, at the end of the week I will push first version for review.

**Comment by ranebrown** [comment]
@monkinco any updates?

**Comment by hq6** [comment]
Closing this issue due to lack of response in several months. Please reopen if this project is resumed.
