### ISSUE TITLE
links containing [] are misread

### ISSUE THREAD

**Issue by capcionista** [vimwiki/vimwiki#678]
I have tried to "import" my txt note collection into Vimwiki. My notes are in .txt, many of them contain [] in their names. When clicking on a link to a file which in its name contains square brackets, e.g. cursor on "Bookname" in 

This is a [[Bookname [Author]]]

Vimwiki opens/creates 

Bookname [Author.txt

instead of

Bookname [Author].txt

i.e. it takes the first two ]] as ending brackets, instead of recognizing the correct layering. Is there any way to change this?

## Info

set nocompatible
filetype plugin on
syntax on

let g:tq_language=['en', 'de']
let g:vimwiki_list = [{'path': '~/vimwiki/','syntax': 'default', 'ext': '.txt'}]

Output of ':VimwikiShowVersion' E806, E15

**Comment by hq6** [comment]
i'm not sure that interpreting (and then ignoring) the nested set of brackets is supported behavior. 

As far as I can tell, Vimwiki treats the first pair of `]]` as the closing delimiter, rather than trying to determine whether the the first `]` it sees is paired with some `[` earlier in the string. Effectively, vimwiki sees `[[ Bookname [Author ]] ]`, which it quite reasonably interprets to mean you want a link with a name `Bookname [Author`.

I suspect that doing something more complex than looking for the first set of `]]` is likely going to involve a lot of special cases.

**Comment by capcionista** [comment]
Thank you for your fast reply! I will change my filenames to [[bookname {author}]] instead. OFF TOPIC: I have been able to batch rename a test set of notes using the renamer plugin; if you could help me out with the regex for replacing the structure inside the note body from

text text may contain any kind of brackets [[bookname may contain several words but only round and no other brackets [author]]] 

to

text text may contain any kind of brackets [[bookname may contain several words but only round and no other brackets {author}]] 

as well as from:

text text may contain any kind of brackets [[bookname may contain several words but only round and no other brackets [author].txt]] 

to

text text may contain any kind of brackets [[bookname may contain several words but only round and no other brackets {author}.txt]] 

that would be amazing!

**Comment by hq6** [comment]
Here's a command that might do what you want. 
Note that this will not work if the `[[ ...]]` block spans multiple pages or if there are stray `[[` in your file.
```
sed 's/\[\[\([^][]*\)\[\([^]]*\)\]/[[\1{\2}/' MyFile.txt > MyFile_Changed.txt
```
If there are additional constraints and this isn't giving you the right behavior, I'd recommend asking a question on StackOverflow with more details. If you write the question clearly, someone with much better regex-fu than me will be able to address it.

**Comment by hq6** [comment]
I assume this issue is resolved due to lack of additional response. Please re-open if this is not the case.
