### ISSUE TITLE
create vimwiki links while using Markdown syntax

### ISSUE THREAD

**Issue by capcionista** [vimwiki/vimwiki#679]
When using Markdown Syntax, vimwiki links still lead to the corresponding files. When creating new links, a markdown `[link](link)` is created.
Is there any way to create [[vimwiki links]] while using markdown syntax? I would really appreciate if there was an option for that. (Background: This would make things easier for people migrating vom Notational Velocity & other note taking systems using [[ ]] + markdown syntax.)

**Comment by ranebrown** [comment]
The support for vimwiki style links is more than likely going to be removed when using Markdown syntax. The goal is to make the syntax more closely match the commonmark spec rather than creating a hybrid syntax.

**Comment by ranebrown** [comment]
I think it would be pretty easy to use`sed` to convert the `[[links]]` to markdown style.

**Comment by capcionista** [comment]
I see. As I am using a plain txt editor on my phone, writing '[[links]]' is much quicker than writing '[links](links)'. I have been looking at deleting/changing parts of the markdown specific code, without success. Can you tell me what files/lines I would have to adjust to make this work or is this a more complex issue?

**Comment by ranebrown** [comment]
Quick and dirty hack - just comment out the `if` statement looking for the syntax specific links in [this function](https://github.com/vimwiki/vimwiki/blob/37f020d21a2a70e2163eea25dc71bcf4de6be22b/autoload/vimwiki/base.vim#L2159-L2171).

If you are interested in trying a different app I would take a look at [Markor](https://github.com/gsantner/markor). I use that for vimwiki on by phone and it is pretty awesome. Link creation can be automated with one of the builtins.

**Comment by capcionista** [comment]
> 
> If you are interested in trying a different app I would take a look at [Markor](https://github.com/gsantner/markor). I use that for vimwiki on by phone and it is pretty awesome. Link creation can be automated with one of the builtins.

This did the trick! Thank you very much!
