### ISSUE TITLE
List folding hides next list items

### ISSUE THREAD

**Issue by jmolero** [vimwiki/vimwiki#680]
Hi. 

There's a problem when using the list folding. It folds list more than it should and that can hide a lot of information in long lists.

I followed the example in the docs and it works well in that case. But if you take the following example that doesn't have `  * [ ] Do substuff 1.3`:

```
* [ ] Do stuff 1
    * [ ] Do substuff 1.1
    * [ ] Do substuff 1.2
        * [ ] Do substuff 1.2.1
        * [ ] Do substuff 1.2.2
* [ ] Do stuff 2
* [ ] Do stuff 3
``` 

Hitting zM makes it fold like this: 

```
= My current task =
* [ ] Do stuff 1 [6] ------------------
* [ ] Do stuff 3
```

I think it should look like this instead:

```
= My current task =
* [ ] Do stuff 1 [5] ------------------
* [ ] Do stuff 2
* [ ] Do stuff 3
```

This seems to  happen because the first sublist doesn't end in the same indent level.

I tried with the the dev branch but it has the same behavior.

I'm using this version: 

```
Branch: master
Revision: be793e2
Date: 2019-04-20 14:13:17 +0200
```

**Comment by hq6** [comment]
Thanks for reporting this!
I can confirm that this behavior reproduces and definitely seems broken.
We will look into this eventually, but if you are interested in contributing and see it fixed faster, a PR is quite welcome!

**Comment by ranebrown** [comment]
Has anyone checked if this behavior has always been present or was introduced in one of the more recent releases?

**Comment by hq6** [comment]
@ranebrown Not yet, but I can bisect it and report back.

**Comment by hq6** [comment]
Wow, this issue was introduced in c6e110a368562c30ac3126cec6cccd46efee8eb6 from 2013. 
The fact that we haven't found it until now seems to imply that not many people use `g:vimwiki_folding = 'list'`.
