### ISSUE TITLE
Headers as Tags

### ISSUE THREAD

**Issue by jupart** [vimwiki/vimwiki#682]
Is there a way to have headers (items in = Header syntax =) generate tags? I'd like to be able to jump to headers as if they were a tag like I would jump to a function in a file with correct ctags.

**Comment by jupart** [comment]
I've found I can use the workflow described here https://stackoverflow.com/questions/7037055/ctags-vimwiki-vim-and-tagbar-plugin

**Comment by ranebrown** [comment]
You can also take a look at the [tagbar script](https://github.com/vimwiki/vimwiki/wiki/Related-Tools#vim-plugins). Using `VimwikiTOC` creates links to each header on that page if that helps as well.
