### ISSUE TITLE
`diary_rel_path` has minimum length 1, but could be 0

### ISSUE THREAD

**Issue by agude** [vimwiki/vimwiki#684]
Recently some error checking was added to the parsing of the user settings: https://github.com/vimwiki/vimwiki/commit/fdc367f7250989e78ccbd6454fade109e008cdaa

Previously I had been using `'diary_rel_path': '',` to put my diary files in the same directory as the rest of my wiki files, but now this breaks because `diary_rel_path` has a minimum length of 1. See here: https://github.com/vimwiki/vimwiki/blob/be793e28bea4ac30c19c15c4db3fd42d26a5debe/autoload/vimwiki/vars.vim#L253

This leads to the following error: 
```
Vimwiki Error: The provided value '' of the option 'diary_rel_path' in g:vimwiki_list must have at least 1 character(s) but has 0. See ':h g:vimwiki_diary_rel_path'.
```

A work around is I can set `'diary_rel_path': '.',`, but it seems like there is no reason to force this variable to have a set number of characters.

**Comment by agude** [comment]
In Unix (where I live primarily) `/./` and `//` are the same, but perhaps that isn't true always? If there is a decision about what to do, I'm happy to implement it.

**Comment by ranebrown** [comment]
I tested this and I didn't see any issues with setting the length to 0. If you can create a PR that would be helpful.

**Comment by agude** [comment]
I'll send a PR!

**Comment by jean** [comment]
This has been merged to `dev` but I'm running into this issue now --- could it be merged to `master`? 
In fact, I see `master` is getting commits that aren't in `dev`!

> This branch is 209 commits ahead, 13 commits behind master.
