### ISSUE TITLE
`s:check_users_value()` returns help suggestions that do not exist for options

### ISSUE THREAD

**Issue by agude** [vimwiki/vimwiki#685]
For example, when I mis-set `diary_rel_path` (as in #684), it gives the error:
```
Vimwiki Error: The provided value '' of the option 'diary_rel_path' in g:vimwiki_list must have at least 1 character(s) but has 0. See ':h g:vimwiki_diary_rel_path'.
```

But running `:h g:vimwiki_diary_rel_path` gives the error:
```
E149: Sorry, no help for g:vimwiki_diary_rel_path
```

Instead, it should suggest:
```
:h vimwiki-option-diary_rel_path
```

**Comment by ranebrown** [comment]
Thanks for pointing this out. There is a common function used for printing the error messages that needs updated for the wikilocal options. If you can make the change as part of your PR for #684 that would be great.

**Comment by agude** [comment]
I'll give this one a go, but I suspect it will take me a bit to wrap my head around it.
