### ISSUE TITLE
How to hide format characters?

### ISSUE THREAD

**Issue by IceDream61** [vimwiki/vimwiki#690]
This is my text content: [[https://www.youtube.com|YouTube]]
On my old computer, when my cursor is not at this line, it will display as: YouTube
But on my new computer, it will display as: [[https://www.youtube.com|YouTube]]
I want to know which setting can I use to fix this problem?
Notice that this is just a display problem~

**Comment by ranebrown** [comment]
See #674

**Comment by ranebrown** [comment]
Also take a look at the option `g:vimwiki_conceallevel`. Please reopen or comment here if you are still having issues.
