### ISSUE TITLE
Some key mappings of g:vimwiki_key_mappings should be enabled only on vimwiki buffers

### ISSUE THREAD

**Issue by ichitera** [vimwiki/vimwiki#693]
#686 enables key mappings globally, but some key mappings (e.g. `o`, `O`) does not work on a buffer of which filetype is not `vimwiki`.

![1](https://user-images.githubusercontent.com/31098747/56941054-dcf15200-6b4c-11e9-85ed-1ab813dfa0fb.gif)
(In the screencast, I tried to enter the insert-mode on a blank buffer by `o` key, but I could not. `o` key was mapped to `<Plug>VimwikiListo` in the buffer of which filetype is not `vimwiki`, which prevented me from entering the insert-mode.)

**steps to reproduce this issue:**
1. `vim -u vimrc -N`
2. `<leader>w<leader>w`
3. `:enew<CR>`
4. type `o`
5. ( The issue occurs; insert-mode does not start.)

`vimrc` to reproduce the issue:
```VimL
language C

if !filereadable('plug.vim')
  silent !curl --insecure -fLo plug.vim
    \  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif
source plug.vim

call plug#begin('./plug')
Plug 'vimwiki/vimwiki', {
      \ 'branch': 'dev',
      \ }
call plug#end()
```

The output of `:VimwikiSHowVersion`:
```
Branch: dev
Revision: bb15cd1
Date: 2019-04-29 22:09:38 -0600
```

**Comment by ranebrown** [comment]
I noticed this as well. I think it is fixed if you want to pull the latest and check.

**Comment by ichitera** [comment]
Thank you for the very quick response. I confirmed that the latest commit 50a3c78c87899ba2eacdb4d0798b311df9ccfffd fixed the issue.
