### ISSUE TITLE
Links to Subheaders

### ISSUE THREAD

**Issue by jupart** [vimwiki/vimwiki#697]
(enhancement)

Add the ability to scope anchor links like [[index#Header1##Subheader of Header 1]]. Currently, [[index#Subheader of Header 1]] works, which is a problem when ##Subheader of Header 1 has duplicates in multiple headers.

**Comment by hq6** [comment]
I'm worried about breaking backwards compatibility (existing links might break) with a change like this.
@Nudin @ranebrown , do you have any thoughts on this?

**Comment by ranebrown** [comment]
Maybe I'm misunderstanding but I think this already works. With the below headers and links it is possible to jump to the correct subheader even if it has a duplicate name. Maybe the documentation needs updated? I didn't take a look at that.
```
= Header 1 =

== Sub Header Same ==

= Header 2 =

== Sub Header Same ==
```
```
- [[index#Header 1|Header 1]]
    - [[index#Header 1#Sub Header Same|Sub Header Same]]
- [[index#Header 2|Header 2]]
    - [[index#Header 2#Sub Header Same|Sub Header Same]]
```

**Comment by jupart** [comment]
It does seem to work, although sometimes I can't jump to the link, but that's a different matter. Thanks!

**Comment by ranebrown** [comment]
@hq6 if you have a chance can you check the documentation on this? Otherwise I'll get to it in the next few days. Thanks!

**Comment by hq6** [comment]
@ranebrown , It looks like the documentation is indeed missing this point. I will try to create a PR to fix it.

**Comment by jupart** [comment]
I can check this out and create a PR a a needed.

**Comment by ranebrown** [comment]
@jupart PRs are always welcome! There are a couple of issues labeled easy if you want to take a look at those. Otherwise anything helps including opening issues for bugs or feature requests. Even just improving the documentation helps, if you think something could be made more clear in this case go for it.
