### ISSUE TITLE
A foldexpr function for flexible header folding 

### ISSUE THREAD

**Issue by sdondley** [vimwiki/vimwiki#700]
I've been boning up on my vim scripting skills and fine-tuned a function for `foldexpr` that folds on headers. It has a couple of configuration variables:

1) `g:header_type`: allows it to work with wiki or markdown syntax
2) `g:fold_blank_lines`: allows you to control whether the last blank line before a header is folded.

Thought I'd share this in case there is interest in implementing this in vimwiki. If there is, I'd be happy to supply a patch. Consider this a prototype:

```
 let g:fold_blank_lines = 0
 let g:header_type = '#'

 function! Fold(lnum)
   let fold_level = strlen(matchstr(getline(a:lnum), '^' . g:header_type . '\+'))
   if (fold_level)
     return '>' . fold_level  " start a fold level
   endif
   if getline(a:lnum) =~? '\v^\s*$'
     if (strlen(matchstr(getline(a:lnum + 1), '^' . g:header_type . '\+')) > 0 && !g:fold_blank_lines)
       return '-1' " don't fold last blank line before header
     endif
   endif
   return '=' " return previous fold level
 endfunction
```

**Comment by ranebrown** [comment]
How does this compare to using the `expr` fold option? Doesn't that fold on headers as well?

**Comment by sdondley** [comment]
This gives users an option for folding the blank lines on or off. Nothing ground-breaking. I thought it was annoying to have blank lines folded in.

**Comment by ranebrown** [comment]
I think this would be good to put on a new [wiki](https://github.com/vimwiki/vimwiki/wiki) page. Maybe create a "Tips and Tricks" page with a folding section?

**Comment by sdondley** [comment]
That probably makes sense. You probably don't want to get into the business of writing folding code to try to satisfy the whim's of every user. But if you show them how they can write their own folding code, that would be useful.

**Comment by ranebrown** [comment]
I don't think the wiki has any access restrictions if you want to go ahead and create the page.

**Comment by sdondley** [comment]
Yeah, was planning to. Will get to it soon.

**Comment by sdondley** [comment]
Added wiki page.
