### ISSUE TITLE
Make remapping documentation more accessible to newer vim users

### ISSUE THREAD

**Issue by sdondley** [vimwiki/vimwiki#702]
As a rather amateur Vim user, I found Section 3.1 on "Global mappings" to be somewhat confusing and has other problems:

1. I had no idea what `<Plug>` was. Though I had seen this before, I didn't know what to do with it or why it was important.
2. To remap a key, the documentation suggests that `:nmap` be used. However, it's best practice to use `nnoremap`
3. The documentation seems to provide a suggestion for another key for remapping. Example:

`:nmap <Leader>w <Plug>VimwikiIndex`

However, a newer vim user may not realize they can make the {lhs} with anything they want. It doesn't have to include the `<Leader>` key or the suggested remap (`w` in the above example).

Suggestions for improvement:

1. Place a clear tutorial on how to perform remaps at the top of the section
2. Remove confusing documentation

Proposed patch forthcoming.

**Comment by ranebrown** [comment]
> To remap a key, the documentation suggests that :nmap be used. However, it's best practice to use nnoremap

The `<Plug>` mappings need to be recursive to work properly. The actual definitions use the `nnoremap` versions if you look in `ftplugin/vimwiki.vim`. Anything that doesn't use `<Plug>` should use the `nnoremap` version as you suggested.

**Comment by sdondley** [comment]
Yeah, figured that out afterwards and made a new commit to address my error.
