### ISSUE TITLE
Import from vim-notes

### ISSUE THREAD

**Issue by NikosAlexandris** [vimwiki/vimwiki#706]
Would you think of a straightforward way to import notes created with [vim-notes](https://github.com/xolox/vim-notes), regardless of the syntax (VimWiki, Markdown or MediaWiki) that is set.

**Comment by ranebrown** [comment]
I'm not familiar with the syntax of vim-notes but I think you would need to write a script to translate the syntax elements into one of the 3 recognized Vimwiki syntaxes. I would try to find the one that most closely matches and go for that. I think `sed` or `awk` would be your best bet.

**Comment by NikosAlexandris** [comment]
Even if the source is Markdown, and the syntax for vimwiki is set to Markdown, still there is such conversion work to do?

**Comment by NikosAlexandris** [comment]
And, where could I start reading upon this, in case I want to go on with such a conversion script?

**Comment by ranebrown** [comment]
If the source is markdown then you shouldn't need to do anything other than configure Vimwiki to use markdown syntax. Update to the correct path and extension.

```vim
    let vimwiki = {}
    let vimwiki.path = 'path/to/your/markdown/files'
    let vimwiki.syntax = 'markdown'
    let vimwiki.ext = '.md'
    let g:vimwiki_list = [vimwiki]
```

**Comment by ranebrown** [comment]
You could take a look at [The GNU Awk User's Guide](https://www.gnu.org/software/gawk/manual/gawk.html) or look for a `sed` tutorial online. Basically you need to use regex patterns to find specific elements and then replace them with a different syntax.

**Comment by NikosAlexandris** [comment]
Thank you

**Comment by chmanie** [comment]
Sorry to hijack this but I'm struggling with a similar problem. All my notes are already in markdown and I could easily just copy them to the vimwiki folder, but how do I "wikify" them? As they are not in the index I can't really access them inside of vimwiki. I think this might be a general question. How to deal with "dangling" notes, as in notes for which files exist but they aren't linked to anywhere. Do I have to manually add them?

**Comment by chmanie** [comment]
I think I'm rather struggling with how to access these files once they are in the wiki. I can't find a way to open a specific file that is not linked to

**Comment by uolot** [comment]
You can:
- simply open them in Vim, just as you open regular files
- use command `VimwikiGoto`
- use command `VimwikiSearch`
- use command `Files <your/vimiki/path>` for fuzzy search if you have `fzf` plugin installed

It's generally a good idea to read, or at least skim through, the help file - `:help vimwiki`
