### ISSUE TITLE
Overview table with Markdown to HTML converters

### ISSUE THREAD

**Issue by NikosAlexandris** [vimwiki/vimwiki#708]
There seem to be a few different tools under https://github.com/vimwiki/vimwiki/wiki/Related-Tools#external-tools to do the same conversion: Markdown to HTML. Maybe adding an overview table would help to understand their differences.

**Comment by ranebrown** [comment]
An overview table would definitely be helpful. If you try out some of the tools you can update the wiki with your findings! 😄

**Comment by ranebrown** [comment]
The external tools page is now found [here](https://vimwiki.github.io/vimwikiwiki/Related%20Tools.html#Related%20Tools-External%20Tools). The base repository where PRs can be made is https://github.com/vimwiki/vimwikiwiki
