### ISSUE TITLE
Hyper link for openning local file in Windows System

### ISSUE THREAD

**Issue by llinfeng** [vimwiki/vimwiki#71]
It struck me this morning that Vimwiki could be turned into a real knowledge base if it could conduct the action of opening files from local directory.

The ideal thing would be to enable opening of directory and files by a string of directory. For those without file extension, we open it up as a directory (i.e. opening a new folder); for those with certain file extension, we open it up using the default setting by the operating system. `[["Directory"]]` might be a reasonable syntax for this purpose. 

I wish this would be doable. 

All the best, 

-Linfeng

**Comment by jon-yip** [comment]
Firstly I would like to thank you for this amazing plugin.
However, I've been trying to doing something like [[~/playground/mycodes]] to open a directory but instead of opening the directory vimwiki keeps asking me if I want to create a new directory under the current ~/vimwiki directory. Also I tried to use [[file:]] and [[local:]] to access other local files without success. 
Have I missed something here?

**Comment by severoraz** [comment]
Here is a modified version of the script that works for me. The other suggestions didn't.
This script opens all files with explorer.exe, which results in 
* for directories, opening them in explorer.exe
* for files, opening them with their assigned application (system default)

```vim
function! VimwikiLinkHandler(link)
    let link = a:link
    let islink = 0
    if link =~ '^local:.*'
        let islink = 1
        let local_dir = matchstr(link, '^local:\zs.*')
        let abs_dir = expand('%:p:h').'/'.local_dir
        " open dolphin in the desired directory. Sorry, I don't know how to open Windows explorer
        " call system("cmd " . shellescape(abs_dir) . " &")
        " exe "!explorer '" . substitute(abs_dir,"/","\\\\",'g') . "'"
        " return 1
    elseif link =~ '^file:.*'
        let islink = 1
        let abs_dir = matchstr(link, '^file:\zs.*')
        " open the directory with netrw
        " call system("cmd " . substitute(dir,"/","\\",'g'))
        " return 1
    endif
    if islink == 1
        exe "!explorer '" . substitute(abs_dir,"/","\\\\",'g') . "'"
        return 1
    else
        return 0
    endif
endfunction
```
