### ISSUE TITLE
Indent list on tab

### ISSUE THREAD

**Issue by project-repo** [vimwiki/vimwiki#712]
Hi,

I am currently using vimwiki as a preparation tool for an upcoming test and in doing so, I make heavy use of the list functionality, which is really awesome for writing concise summaries. However, after some time, I noticed that indenting list items can become quite tedious, since I must remove the bullet, add the indention and then readd the bullet. I know that vimwiki has functionality for indenting lists in normal mode and that it is possible to remap these functions to keys in insert mode, however, my question is if it is possible to include indenting lists into the ``vimwiki#tbl#kbd_tab()`` function, as is done similarly for tables. I'm sorry for bothering you if this has already been discussed somewhere or if this feature was willingly excluded.

cheers,
project-repo

**Comment by ranebrown** [comment]
The default key mappings ctrl-t and ctrl-d increase and decrease indentation in insert mode. They can be remapped with `imap your_keys_here <Plug>VimwikiIncreaseLvlSingleItem` and `imap your_keys_here <Plug>VimwikiDecreaseLvlSingleItem`. If you want to use tab you might need to take a look at [supertab](https://github.com/ervandew/supertab) or disable other tab mappings. Does that help?

**Comment by project-repo** [comment]
Cool, thanks! I remapped the tab key to ``<c-t>`` in vimwiki files and it works great. This perfectly solves my issue.
cheers,
Jeremy

**Comment by mbpowers** [comment]
For any future readers:
```
let g:vimwiki_table_mappings = 0
autocmd BufRead,BufNewFile ~/vimwiki/* imap <Tab> <Plug>VimwikiIncreaseLvlSingleItem
```
Pop in your vimrc, replace `~/vimwiki/*` with the location of your wiki folder and your good to go. This will disable the tab keybinding within tables though, as they are in conflict.

It would be cool if we could avoid the table and increaselvl functions conflict by having one function that detects whether or not you are in a table then behaves accordingly to avoid double mapping. Not sure about the feasibility just an idea.
