### ISSUE TITLE
markdown syntax vimwiki export with pandoc

### ISSUE THREAD

**Issue by jessebett** [vimwiki/vimwiki#713]
I am getting started with vimwiki and would like to use the markdown syntax as I  am already familiar with it and use it elsewhere. I am primarily interested in the support for exporting markdown vimwiki to html and pdfs. I have tried using `patrickdavey/vimwiki_markdown` but this does not seem to work for my markdown files whose syntax were targeting pandoc. 

In particular, my markdown contains a lot of latex math environments, and pandoc is able to export these to html and pdf fine, where `vimwiki_markdown` does not. 

Is there any resources demonstrating how I can use pandoc in conjunction with markdown syntax'd vimwiki to easily export the entire wiki to pdf and html using pandoc defined export rules?

Following the `vimwiki_markdown` readme my vimrc has
```
let g:vimwiki_list = [{'path': '~/vimwiki', 'template_path': '~/vimwiki/templates/',
          \ 'template_default': 'default', 'syntax': 'markdown', 'ext': '.md',
          \ 'path_html': '~/vimwiki/site_html/', 'custom_wiki2html': 'vimwiki_markdown',
          \ 'html_filename_parameterization': 1,
          \ 'template_ext': '.tpl'}]
let g:vimwiki_global_ext = 0
let g:vimwiki_markdown_link_ext = 1
```

**Comment by ranebrown** [comment]
There is a pretty good example of how to use pandoc in [this comment](https://github.com/vimwiki/vimwiki/issues/642#issuecomment-477815553). You basically need a script to take the arguments that vimwiki provides and process things as needed then pass it off to pandoc.

**Comment by ranebrown** [comment]
@jessebett were you able to get something working? Do you have any other questions?

**Comment by jessebett** [comment]
@ranebrown sorry about the non-response. Thank you very much for pointing me to this script. I see that it is for using pandoc to export html, so I will have to modify a bit for my purposes. I'll take a look at that in a bit and reopen if I run into any issues with vimwiki.

**Comment by ashwinvis** [comment]
GladTeX could be a lightweight option to convert math elements in an html. https://github.com/humenda/GladTeX/blob/master/manpage.md#examples
