### ISSUE TITLE
Creating links after setting markdown default fails

### ISSUE THREAD

**Issue by jacobseiler** [vimwiki/vimwiki#715]
Hey there, just started using Vimwiki.  I'm attempting to set Markdown as my default syntax and have added the following lines to my `.vimrc`

```vim
let g:vimwiki_list = [{'path': '~/vimwiki/',
                      \ 'syntax': 'markdown', 'ext': '.md'}]
```

Going to my ``~/vimwiki/index.md``, I attempt to create a link (by setting my cursor and pressing ``Enter``) and get the following error

```
Error detected while processing function vimwiki#base#follow_link..vimwiki#base#normalize_link..vimwiki#markdown_base#normalize_link..<SNR>30_normalize_link_syntax_n..vimwiki#base#normalize_link_helper..<SNR>29_clean_url:
line    5:
E706: Variable type mismatch for: url
line    6:
E712: Argument of filter() must be a List or Dictionary
line   14:
E712: Argument of filter() must be a List or Dictionary
line   15:
E712: Argument of filter() must be a List or Dictionary
line   16:
E714: List required
```

VimwikiShowVersion gives ``Stable version: '2.4.1' ``                                                                                                                                                                              

Any tips would be appreciated!

**Comment by ranebrown** [comment]
What is the link text you are pressing enter on?

Do links work if you create them manually e.g. `[test](page.md)`.

Can you try the minimal vimrc steps [here](https://vimwiki.github.io/vimwikiwiki/Troubleshooting.html#Troubleshooting-Minimal%20Vimrc)

**Comment by jacobseiler** [comment]
Thanks for the reply.

I'm pressing enter on `Test` text.

The links work if I create them manually.

I tried the minimal `.vimrc` and it works fine using the default syntax and `.wiki` extension.  However, changing the syntax to `markdown` and the extension to `.md` throws the same error when I try and press "Enter" to create the link on the `Test` text.  Again, creating the links manually works.

**Comment by ranebrown** [comment]
I haven't been able to reproduce this. A few more questions:
1. Do you see the same behavior on the `dev` branch?
2. What version of vim are you using?
3. What OS are you using?

**Comment by jacobseiler** [comment]
1: Yes I do. The minimal `.vimrc` was done following the example which (I believe) uses the `dev` branch.
2, 3: I have attempted running this on my Mac (using Vim `version 7.4.8056`) and SSHing onto a super computer (Vim `version 7.4.1099`).

In the meantime I've just been putting `[]()` around my links manually and have been loving Vimwiki :)

**Comment by ranebrown** [comment]
@jacobseiler if you can try the latest dev branch this should be fixed. Version of Vim prior to 7.4.1546 did not allow a variables type to change (sticky type checking) which was causing this problem. You might run into similar issues elsewhere but it should be quick to fix in most cases.

**Comment by jacobseiler** [comment]
Thank you very much @ranebrown , works perfectly!

(Also, in the past month, productivity has skyrocketed <3)

**Comment by chris2fr** [comment]
Hi, I am running into the same problem now.

VimwikiShowVersion: Stable version: 2.5

VIM 8.2 MS Windows 64 bits OLE
