### ISSUE TITLE
Enter key not working on windows 10

### ISSUE THREAD

**Issue by brijgogogo** [vimwiki/vimwiki#716]
Vimwiki version: 2.4.1
Vim: 8.1

I am on Windows 10. Enter is not working, it just moves the cursor to line below.

Is there some setting that need to be enabled to make enter work on Windows ?

**Comment by ranebrown** [comment]
What is the output of `:verbose imap <CR>`?

Do you see the same behavior using a [minimal vimrc](https://vimwiki.github.io/vimwikiwiki/Troubleshooting.html#Troubleshooting-Minimal%20Vimrc)?

**Comment by brijgogogo** [comment]
:verbose imap <CR> give:

i  <CR>        &@<SNR>72_AutoPairsOldCRWrapper73<SNR>72_AutoPairsReturn
Last set from ~\vimfiles\plugged\auto-pairs\plugin\auto-pairs.vim

**Comment by brijgogogo** [comment]
Looks like it is conflicting with https://github.com/jiangmiao/auto-pairs, which says:
<CR>  : Insert new indented line after return if cursor in blank brackets or quotes.

**Comment by brijgogogo** [comment]
I disabled the auto-pairs, now the output shows as:
i  <CR>        *@<Esc>:VimwikiReturn 1 5<CR>
Last set from ~\vimfiles\plugged\vimwiki\ftplugin\vimwiki.vim

Still, the enter behaves same, it moves the cursor to the line below.

**Comment by ranebrown** [comment]
What is the behavior you are expecting? To create a link when on a word? If that is the case what is the output of `verbose nmap <CR>`. The `VimwikiReturn` mapping is used when working in lists in insert mode.

**Comment by ranebrown** [comment]
@brijgogogo any update here?

**Comment by brijgogogo** [comment]
`verboase nmap <CR>' gave output : no mapping found.
I added explicit mapping `noremap <CR> :VimwikiFollowLink<cr>`, and it is working now.
