### ISSUE TITLE
vimwiki <leader>ww not working

### ISSUE THREAD

**Issue by alexwms** [vimwiki/vimwiki#717]
I am using macvim. My .gvimrc file is the following:

let mapleader = ','

:map <Leader>A  oanother line <Esc>

set nocompatible
filetype plugin on
syntax on

call plug#begin('~/.vim/plugged')

Plug 'lervag/vimtex'
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'

Plug 'vimwiki/vimwiki'

Plug 'morhetz/gruvbox'

call plug#end()

colorscheme gruvbox

Running :VimwikiShowVersion gives `Stable version: '2.4.1'` and :help vimwiki displays the documentation, but leader+ww does not open the default wiki index file (except in two rare occasions where it did, but I'm not sure how to reproduce those). I am only just starting out with vim so it is very possible I am making a simple error somewhere. Also, fyi, I created the test leader+A (see config above) and it consistently works.

**Comment by alexwms** [comment]
I just ran `:verbose map ,ww` and got back `No mapping found`

**Comment by ranebrown** [comment]
You might need to do that with `<leader>ww`. You can also just type `:nmap` and browse through the listed mappings.

**Comment by ranebrown** [comment]
Maybe try `\ww` as well which should be the default leader key.

**Comment by alexwms** [comment]
I tried all of your suggestions, but nothing is coming up. `:nmap` shows no commands for vimwiki.

**Comment by ranebrown** [comment]
Does `:VimwikiIndex` open the wiki page?

Can you try the minimal vimrc steps [here](https://vimwiki.github.io/vimwikiwiki/Troubleshooting.html#Troubleshooting-Minimal%20Vimrc) and add the `mapleader` command?

**Comment by alexwms** [comment]
`:VimwikiIndex` gives `Not an editor command` when executed in macvim.

I followed the minimal vimrc steps and everything works. So, this seems to be a problem involving macvim/vim-plug.

**Comment by alexwms** [comment]
I have discovered the following: If I launch macvim (with vimwiki already installed via vim-plug) and then issue `:map ,`, the vimwiki commands do not show up. If I instead first run `:PlugInstall` and then run `:map ,`, the vimwiki commands appear and I am able to execute them. But then, if I close and reopen macvim, the commands no longer show up when I issue `:map ,`.

**Comment by alexwms** [comment]
I figured it out. I was having this issue:[https://github.com/junegunn/vim-plug/issues/540]( https://github.com/junegunn/vim-plug/issues/540)

**Comment by ranebrown** [comment]
Glad you figured it out!
