### ISSUE TITLE
Unable to create "~/vimwiki/index.wiki" 

### ISSUE THREAD

**Issue by jmpicaza** [vimwiki/vimwiki#720]
Hi,
I'm trying to use Vimwiki, but I'm unable to point it to "~/vimwiki/index.wiki" or whatever other location. Each time it asks:
![image](https://user-images.githubusercontent.com/2660543/58879185-57c20580-86d5-11e9-8c85-63ec5e7eeb69.png)

and the .vimrc is:
let g:vimwiki_list = [ {'path': '~/Documents/vimwiki', 'syntax': 'markdown', 'ext': '.md.wiki'}, {'path': '~/Documents/vimWiki/curro.wiki'}, {'path': '~/Documents/vimWiki/personal.wiki'} ]
but :VimWikiUISelect resolves to:
![image](https://user-images.githubusercontent.com/2660543/58879894-fc911280-86d6-11e9-8fd0-63e1968303fd.png)

Im using macvim:
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:46)
macOS version
Included patches: 1-950
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +cmdline_hist      +ex_extra          +jumplist          +mouse_dec         +path_extra        +startuptime       +title             -X11
+arabic            +cmdline_info      +extra_search      +keymap            -mouse_gpm         +perl              +statusline        +toolbar           -xfontset
+autocmd           +comments          -farsi             +lambda            -mouse_jsbterm     +persistent_undo   -sun_workshop      +transparency      +xim
+autochdir         +conceal           +file_in_path      +langmap           +mouse_netterm     +postscript        +syntax            +user_commands     -xpm
-autoservername    +cryptv            +find_in_path      +libcall           +mouse_sgr         +printer           +tag_binary        +vartabs           -xsmp
+balloon_eval      +cscope            +float             +linebreak         -mouse_sysmouse    +profile           +tag_old_static    +vertsplit         -xterm_clipboard
+balloon_eval_term +cursorbind        +folding           +lispindent        +mouse_urxvt       -python            -tag_any_white     +virtualedit       -xterm_save
+browse            +cursorshape       -footer            +listcmds          +mouse_xterm       +python3           +tcl               +visual
++builtin_terms    +dialog_con_gui    +fork()            +localmap          +multi_byte        +quickfix          +termguicolors     +visualextra
+byte_offset       +diff              +fullscreen        +lua               +multi_lang        +reltime           +terminal          +viminfo
+channel           +digraphs          -gettext           +menu              -mzscheme          +rightleft         +terminfo          +vreplace
+cindent           +dnd               -hangul_input      +mksession         +netbeans_intg     +ruby              +termresponse      +wildignore
+clientserver      -ebcdic            +iconv             +modify_fname      +num64             +scrollbind        +textobjects       +wildmenu
+clipboard         +emacs_tags        +insert_expand     +mouse             +odbeditor         +signs             +textprop          +windows
+cmdline_compl     +eval              +job               +mouseshape        +packages          +smartindent       +timers            +writebackup
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"

**Comment by jmpicaza** [comment]
The command ":echo g:vimwiki_wikilocal_vars" resolves to:

```
[{'auto_tags':` 0, 'css_name': 'style.css', 'auto_export': 0, 'diary_index': 'diary', 'template_default': 'default', 'nested_syntaxes': {}, 'auto_toc': 0, 'maxhi': 0, 'diary
_sort': 'desc', 'path': '/', 'custom_wiki2html_args': '', 'auto_diary_index': 0, 'syntax': 'default', 'custom_wiki2html': '', 'automatic_nested_syntaxes': 1, 'index': 'inde
x', 'diary_header': 'Diary', 'ext': '.wiki', 'is_temporary_wiki': 0, 'path_html': '/', 'template_path': '/', 'template_ext': '.tpl', 'list_margin': -1, 'diary_rel_path': '/
'}, {'auto_tags': 0, 'css_name': 'style.css', 'auto_export': 0, 'diary_index': 'diary', 'template_default': 'default', 'nested_syntaxes': {}, 'auto_toc': 0, 'maxhi': 0, 'di
ary_sort': 'desc', 'path': '/', 'custom_wiki2html_args': '', 'auto_diary_index': 0, 'syntax': 'default', 'custom_wiki2html': '', 'automatic_nested_syntaxes': 1, 'index': 'i
ndex', 'path_html': '/', 'ext': '.wiki', 'is_temporary_wiki': 1, 'diary_header': 'Diary', 'template_path': '/', 'template_ext': '.tpl', 'list_margin': -1, 'diary_rel_path':
 '/'}]
```

All paths are fixed to "/". This is the problem.

**Comment by ranebrown** [comment]
The path should default to `$HOME/vimwiki` unless you are changing it in your vimrc. Can you try the minimal vimrc steps [here](https://vimwiki.github.io/vimwikiwiki/Troubleshooting.html#Troubleshooting-Minimal%20Vimrc)?

**Comment by jmpicaza** [comment]
Thanks. After uninstalling, installing dev-macvim and other test, I began to test with minimal .vimrc.
At the end, it seems that the problem is in the lines:
```
    " It's also helpful to have the patchmode value in the backupskip, suffixes, and wildignore vim options:
	exe "set backupskip+=*" . &patchmode
	exe "set suffixes+=" . &patchmode
	exe "set wildignore+=*" . &patchmode
```
I commented the lines and all works fine. Thanks for the help.
