### ISSUE TITLE
Vimwiki Error: You can generate diary links only in a diary index page!'

### ISSUE THREAD

**Issue by li-ruijie** [vimwiki/vimwiki#721]
Trying to generate diary index causes the error:

    "Vimwiki Error: You can generate diary links only in a diary index page!'"

Potential fix:
change line 389 from:
    
    let diary_file = vimwiki#path#path_norm(s:diary_index())

to

    let diary_file = vimwiki#path#path_norm(s:diary_index(0))

Does it ever make sense not to set diary_index to current diary when generating index?

**Comment by ranebrown** [comment]
What is your use case for generating the diary index when you aren't actually on the diary index page?

**Comment by rehaby** [comment]
@ranebrown I am having trouble with this. I have no idea where the diary index file should be. I've got a file ~/vimwiki/diary/index.wiki and that doesn't seem to work. If this command created the file it would be easier to use

**Comment by ranebrown** [comment]
If you use the command `VimwikiDiaryIndex` (default key map of `<leader>wi`) it will open the diary index for the open wiki and create it if it doesn't exist. From that page you can then generate the links to all diary pages with `VimwikiDiaryGenerateLinks`. You can also use the option `vimwiki-option-auto_diary_index` to automatically keep the links up to date. Does that help?
