### ISSUE TITLE
Patch to add cell alignment to tables

### ISSUE THREAD

**Issue by joejobber** [vimwiki/vimwiki#722]
The last couple of years I've used a patched version of tbl.vim in vimwiki 2.3 to add left/center/right alignment functionality to table cells by adding semi-colons to the separator lines. I did not write the original code. I don't know who did. I do know it works flawlessly for me. 

Recently I noticed development of vimwiki has been reanimated again and thought it would be a good idea to request the addition of this code to vimwiki itself. That way others can reap its benefits as well (and of course then I don't have to keep patching tbl.vim in new versions of vimwiki myself). As far as I can see this functionality is not (yet) in the dev branch. I have made the required changes to tbl.vim to make this work in 2.4.1. See attached diff file for a review of the changes.

Would it be possible to add this to vimwiki? I so, what do I need to do?

P.S. I expected it to be possible to upload a diff file, but had to rename it to .txt. Am I missing something?

[tbl.diff.txt](https://github.com/vimwiki/vimwiki/files/3293464/tbl.diff.txt)

**Comment by joejobber** [comment]
One possible issue I can see is that semi-colons are used as anchor markers. Would that be a problem?

**Comment by ranebrown** [comment]
Is your proposal different than what was merged into the dev branch in #377 (other than using colons)?

**Comment by joejobber** [comment]
On 16/06/2019 14.48, Rane Brown wrote:
> Is your proposal different than what was merged into the dev branch in #377
> <https://github.com/vimwiki/vimwiki/pull/377> (other than using colons)?

Aha, there it is! Sorry, I didn't see this when I searched for similar
suggestions yesterday. It seems that does precisely what I had in mind.

As a matter of fact, I do use colons, as you can see in the diff. No idea why I
named them semi-colons. I probably was too sleepy when I wrote that.

Sorry for wasting your time with this.

Any idea when this will be part of a new stable release? Or otherwise: how
stable is the current dev branch? If you deem it safe for everyday use I could
start using that.

Thanks!

Grx HdV

**Comment by ranebrown** [comment]
There will likely be another release within a few months. The dev branch is fairly stable and should be good for daily use. It is always good to have extra help finding and reporting bugs on the dev branch prior to a release!

**Comment by joejobber** [comment]
On 16/06/2019 15.14, Rane Brown wrote:
> There will likely be another release within a few months. The dev branch is
> fairly stable and should be good for daily use. It is always good to have extra
> help finding and reporting bugs on the dev branch prior to a release!

I that case I think I will try the dev branch. If I encounter an issue I'll
communicate it.

By the way: I am really glad to see that vimiwiki development has been revived!
Thank you and all the other contributors for that. Much appreciated.

Grx HdV

**Comment by ranebrown** [comment]
See discussion in #377. There was some odd behavior that is probably related to the fast table formatting changes.

**Comment by tinmarino** [comment]
Fixed and [tested](https://github.com/vimwiki/vimwiki/blob/master/test/table_autoformat.vader)

**Comment by joejobber** [comment]
Thanks. It seems most issues are gone now. (Couldn't test extensively from here, sorry.)
