### ISSUE TITLE
Vimwiki Header Folding highlight groups

### ISSUE THREAD

**Issue by soctar** [vimwiki/vimwiki#725]
Do the `VimwikiH1Folding`, `VimwikiH2Folding`, etc. highlight groups actually get used? If they aren't (they don't seem to be), could they be used? It'd be nice to be able to differentiate between fold levels.

I'm using markdown syntax, my settings are below:
```
let g:vimwiki_list = [{'path': 'wiki/',
                    \ 'path_html': 'wiki/html',
                    \ 'custom_wiki2html' : '~/.files/convert.py',
                    \ 'auto_export' : 1,
                    \ 'syntax': 'markdown',
                    \ 'ext': '.md'}]
let g:vimwiki_global_ext=0 " Don't treat every .md file as Vimwiki
let g:vimwiki_conceallevel=2
let g:vimwiki_url_maxsave = 0
let g:vimwiki_folding = 'expr:quick'
let g:vimwiki_hl_headers = 1

"Default to other applications conceallevel
augroup vimrc-vimwiki
    autocmd!
    autocmd FileType vimwiki setlocal spell textwidth=80
        \ concealcursor=nc formatoptions=na autoindent
    autocmd FileType vimwiki highlight Folded gui=italic guifg=5 guibg=Grey20
    autocmd FileType vimwiki highlight VimwikiH2Folding gui=italic guifg=5 guibg=Grey90
augroup END
```

Branch: dev
Revision: b997e68
Date: 2019-06-05 06:04:41 -0600

**Comment by ranebrown** [comment]
Where are you seeing `VimwikiH1Folding` defined? I don't think those are present in the `dev` (or `master`) branch. You can set custom colors for each header level as described in the [documentation](https://github.com/vimwiki/vimwiki/blob/b997e687c3e34c1451d8573a23d91dfe6b4122c5/doc/vimwiki.txt#L1185-L1192) but I'm not sure what you will see with folding enabled.

**Comment by soctar** [comment]
I didn't see it defined in a cursory peek through the code base -- I saw it as an autocomplete option for `:hi Vimwiki`

**Comment by ranebrown** [comment]
Those highlight groups are actually defined [here](https://github.com/vimwiki/vimwiki/blob/b997e687c3e34c1451d8573a23d91dfe6b4122c5/syntax/vimwiki.vim#L147-L150). I'm not entirely sure how they are used without digging into things a bit more but they are defined as `transparent`. (See `:h transparent`).

Were you able to get different color highlighting for different fold levels? Can you attach a screenshot?

**Comment by soctar** [comment]
I wasn't able to get different color highlighting -- I can define a broad highlight group for all folded items, but I can't seem to get a finer granularity than that.

**Comment by ranebrown** [comment]
Yeah, I'm not sure if it is possible to do what you want. I think the `VimwikiH1Folding` etc. groups are just used to define where a fold should occur (`:h syn-fold`). If you can figure out a way to color the different groups it shouldn't be a problem to add the option.

**Comment by ranebrown** [comment]
@soctar If you find a way to get this working or have any additional information feel free to reopen.
