### ISSUE TITLE
feature request: custom filename formatter

### ISSUE THREAD

**Issue by seagoj** [vimwiki/vimwiki#726]
Hello,

I would like to add the ability to customize the created filename when making a link. 

In my case, I'd like the highlighted string to be cast to lowercase, remove all symbols, add hyphens for the spaces and retain the '.md' in the link, so the markdown files are more portable.

For example if you were to create a link highlighting the string 'Here's my link', I'd like the following code to be inserted:

```markdown
[Here's my link](heres-my-link.md)
```
And while I think this makes sense, I understand that others may not want that specific format, but might want the ability to define their own which is why I think a customizable hook would be best.

I'm happy to make an attempt myself, but would appreciate being pointed in a direction both in the code and in keeping within the scope of the project.

Thanks!

**Comment by ranebrown** [comment]
Take a look at #707. If you are interested in creating a PR I will review.

**Comment by ranebrown** [comment]
Closing since there is more detail in #707.
