### ISSUE TITLE
Writing with tradition markdown grammar

### ISSUE THREAD

**Issue by Pcrab** [vimwiki/vimwiki#727]
I have some problem when I want to creat a title by typing 

# title

but vimwiki seems do not support change it to proper form when I use vimwiki2html.
anything I can do to make vimwiki support that?

**Comment by Pcrab** [comment]
by typing
\# title

**Comment by ranebrown** [comment]
I think you are talking about using markdown syntax? See the help file [here](https://github.com/vimwiki/vimwiki/blob/be793e28bea4ac30c19c15c4db3fd42d26a5debe/doc/vimwiki.txt#L855-L858) and [here](https://github.com/vimwiki/vimwiki/blob/be793e28bea4ac30c19c15c4db3fd42d26a5debe/doc/vimwiki.txt#L1996-L2009).

Does that answer your question?

**Comment by Pcrab** [comment]
yeah , thanks
