### ISSUE TITLE
Normalize links in diary with markdown syntax

### ISSUE THREAD

**Issue by jmorim** [vimwiki/vimwiki#729]
my vimrc settings for vimwiki:
```
""" wiki_7
let wiki_7 = {}
let wiki_7.index = 'index'
let wiki_7.path = '~/vimwiki/test/markdown/wiki'
let wiki_7.ext = 'md'
let wiki_7.syntax = 'markdown'
""" wiki_8
let wiki_8 = {}
let wiki_8.index = 'index'
let wiki_8.path = '~/vimwiki/test/wiki'

let g:vimwiki_list = [wiki_7, wiki_8]

```

Related to
#66
#77 
Link normalization in the diary works for default syntax but not for markdown. E.g. I need to manually change the default link generated in a diary from ```[page_1](page_1)``` to ```[page_1](../page_1)``` to go up one directory. Lervag implemented an in_diary() function for base.vim but there is no equivalent in markdown_base.vim

If you make two test wikis as above and try to generate a link in a diary, the default syntax will automatically go up one directory to find the existing page.

vimwiki version 2.4.1

**Comment by ranebrown** [comment]
@jmorim can you try out the change I pushed to the dev branch?

**Comment by jmorim** [comment]
I tested both syntaxes and they're working now. Thanks
