### ISSUE TITLE
Markdown files open as filetype=vimwiki

### ISSUE THREAD

**Issue by harrisonthorne** [vimwiki/vimwiki#730]
```
Branch: dev              
Revision: 585a9fd                                                                                       
Date: 2019-07-14 21:50:49 -0600
```

My minimum nvim config:

```
filetype on
filetype plugin indent on
syntax on

let mapleader=","

call plug#begin('~/.local/share/nvim/plugged')
Plug 'vimwiki/vimwiki'
call plug#end()

" VimWiki
let g:vimwiki_global_ext = 0
let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
let g:vimwiki_list = [{'path': '~/notebook/', 'syntax': 'markdown', 'ext': '.md'}]
```

I've seen a number of issues with Markdown, but none of them have helped me out with this issue, so I'm posting a new issue.

I expect .md files to open with markdown syntax, but instead, all markdown files *inside* my wiki open with vimwiki syntax. Outside of my `~/notebook/`, .md files open with markdown syntax as expected.

How do I have markdown files within my wiki open with markdown syntax?

**Comment by ranebrown** [comment]
Vimwiki sets the filetype to `vimwiki` which is needed for some of the functionality to work correctly. You can try out the branch and settings from [this comment](https://github.com/vimwiki/vimwiki/issues/461#issuecomment-482583541) but there was only minimal testing done so I'm not sure that it won't break something.

What is your use case for wanting the filetype set to `markdown` instead of `vimwiki` (I'm assuming for another plugin)?

**Comment by harrisonthorne** [comment]
Correct syntax highlighting/formatting, really. Vimwiki bolds text with single asterisks while Markdown italicizes, and I expect single asterisks to italicize in Markdown. I also have custom settings I use for Markdown filetypes. I mean, overall i'm just accustomed to Markdown and find it much simpler to use.

**Comment by ranebrown** [comment]
The bold/italics issues have been fixed on the `dev` branch. If you can try out that experimental branch and provide any feedback I'll look into merging it to `dev` and it will eventually make it to a release.

**Comment by harrisonthorne** [comment]
Oh dang, I didn't notice that haha. The only other (minor) problem then is that headers aren't syntax highlighted. I'll reopen this issue if I come across any other Markdown problems, but for now I've gotten  enough helpful information for me to understand better. Thanks!
