### ISSUE TITLE
Question: Can you auto create [[wikilink]] in a syntax:markdown vimwiki

### ISSUE THREAD

**Issue by thecontinium** [vimwiki/vimwiki#733]
Hi

Is it possible to configure vimwiki to add a `[[wikilink]]` on `<CR>` rather than a `[markdown](markdown)` link in a vimwiki with `'syntax': 'markdown'`

Cheers

**Comment by ranebrown** [comment]
There isn't an option to allow that but you could probably `call vimwiki#base#replacestr_at_cursor` directly and bind that to a custom mapping.
