### ISSUE TITLE
Error while trying to build test Docker environment

### ISSUE THREAD

**Issue by simias** [vimwiki/vimwiki#736]
I'm trying to set up the docker environment to run the tests. I don't know much about docker so I'm dumbly following the instructions in `test/Readme.md`.

I installed docker, then from the root  of the vimwiki repository (dev branch) I try to run:

```sh
docker build -t vimwiki
```
However it seems that the syntax isn't accepted by my version of docker:

```
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
```
`docker build -h` says that the syntax of the `-t` option is:

```
  -t, --tag list                Name and optionally a tag in the 'name:tag' format
```
Here's the output of `docker version`:

```
Client:
 Version:           19.03.1-ce
 API version:       1.40
 Go version:        go1.12.7
 Git commit:        74b1e89e8a
 Built:             Sat Jul 27 21:08:50 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Comment by ranebrown** [comment]
Try `docker build -t vimwiki .` I think it is missing the required path which is the current directory. I'll update the readme if that works. I plan on uploading a prebuilt image to dockerhub eventually which should simplify and speed this up some. Thanks for giving it a try!

**Comment by ranebrown** [comment]
You should call the script to run the tests from within the test directory with `./run_tests.sh -t vader`

**Comment by simias** [comment]
Yes that did it, it's working now. Thanks!
