### ISSUE TITLE
Can't create newline when editing wiki

### ISSUE THREAD

**Issue by yifongau** [vimwiki/vimwiki#738]
Hi, I installed vimwiki yesterday, and I set it up with the follow settings in .vimrc (see below).

For some reason I can't create a newline when the filetype is 'vimwiki' and when the line is not empty. 

Pressing enter or shift+enter in insert-mode does nothing.
Pressing o or O also does nothing.

When the line is empty those keys work as expected. 
Please let me know if you have any idea's.

```
" General settings
set nocompatible
syntax on
	if has("autocmd")
		filetype plugin indent on
	endif

" Plugin settings 
call plug#begin('~/.vim/plugged')

Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'reedes/vim-pencil'
Plug 'masukomi/vim-markdown-folding'
Plug 'vimwiki/vimwiki'

call plug#end()

" Initialize Goyo and Pencil automatically  
augroup markdown
       autocmd!
       autocmd Filetype markdown,mkd call WritingMode()
augroup END

function! WritingMode()
	 
	if !exists('#goyo')
		Goyo 65
	endif
	
	if !exists('#pencil')
		Pencil
	endif	
	
endfunction

" Markdown folding settings
autocmd FileType markdown set foldexpr=NestedMarkdownFolds()

" Vimwiki settings
let g:vimwiki_global_ext = 0 
let g:vimwiki_list = [{'path': '~/projecten/wiki', 'syntax':  'markdown', 'ext': '.md'}]
let g:vimwiki_folding = 'expr'

```

**Comment by yifongau** [comment]
Correction:

Pressing o or O does not do nothing, it enters insert-mode, but on the same line.
Pressing enter or shift+enter while in insert-mode creates a white space at the end of line; repeatedly pressing enter or shift+enter in insert-mode does not create additional spaces if they have already been pressed once.

**Comment by yifongau** [comment]
I actually found the problem. The vim-pencil plugin conflicts with vimwiki, but I am not sure why.
I changed

`if !exists('#pencil')
		Pencil
	endif	`

into

`if !exists('#pencil')
		SoftPencil
	endif	`

And everything worked out fine, because the hard-line break mode, which I think is what my previous setting defaulted to, creates problems. While the soft-line break mode does not. Not sure why.

**Comment by ranebrown** [comment]
Vimwiki remaps `CR` and some other keys for lists and tables to work correctly. You can run `verbose imap <CR>` from a vimwiki page to see what the conflict might be.

**Comment by qvieth** [comment]
`let g:pencil#autoformat = 0` also fix the issue (but still keep the PencilHard mode working).

https://github.com/preservim/vim-pencil#automatic-formatting

 I think this formatting option of Pencil somehow conflicts with vimwiki.
