### ISSUE TITLE
Diary index not compatible with gollum rendering

### ISSUE THREAD

**Issue by stormyweathers** [vimwiki/vimwiki#740]
I'm using markdown syntax, and version 2.4.1

When I use <Leader>W<Leader>I to autogenerate the diary index, there is a bunch of unnecessary whitespace before each entry.  This whitespace causes rendering issues with gollum.  I have to manually delete the whitespace each time I re-render the index.

I couldn't find where to edit the source to adjust this macro.

**Comment by ranebrown** [comment]
Does `:h vimwiki-option-list_margin` do what you want if you set it to 0? Otherwise can you provide actual and desired output?

**Comment by ranebrown** [comment]
Reopen if you can provide more info.

**Comment by stormyweathers** [comment]
how do I actually change the option?   When I try to edit the buffer shown in  `:h vimwiki-option-list_margin` it says that modifications are not allowed.

**Comment by ratfactor** [comment]
@stormyweathers It sounds like you were trying to edit the Help window itself.

`list_margin` is a per-wiki ("local") setting.  If you haven't already, you'll need to create an entry for your wiki (typically in `~/.vimrc`) in the `g:vimwiki_list` global variable.

You can set as many or few options for your wiki as you would like. This could be your entire entry:

```
let g:vimwiki_list = [{'list_margin': 0}]
```

This would use defaults for all settings except for `list_margin`, which it would set to `0`.  I'm not sure if this will solve your problem, but it _did_ un-indent the VimWiki diary links when I tested it.

**Comment by stormyweathers** [comment]
Thanks!
