### ISSUE TITLE
The current wiki resets when leaving the diary

### ISSUE THREAD

**Issue by sangaline** [vimwiki/vimwiki#741]
Many of the vimwiki commands are documented as operating within the current wiki unless a number is specified to indicate a specific wiki. This works when staying within only the diary or only the rest of a wiki, but the "current wiki" seems to reset to the first wiki when exiting the diary. This sequence of commands demonstrates the issue:

- `2<Leader>ww` - Opens the index of the second wiki.
- `<Leader>wi` - Opens the diary index of the second wiki.
- `<Leader>w<Leader>w` - Opens the current day's diary entry for the second wiki.
- `<Leader>ww` - Opens the index of the *first* wiki.

Is the last command supposed to open the first wiki or the second?

------

Configuration:

```
set nocompatible
filetype plugin on
syntax on
let g:vimwiki_list = [
    \{
        \'path': '~//wiki/personal',
        \ 'syntax': 'markdown', 'ext': '.md',
        \ 'auto_tags': 1,
        \ 'auto_diary_index': 1,
        \ 'auto_generate_links': 1,
        \ 'auto_generate_tags': 1
    \},
    \{
        \'path': '~/wiki/work',
        \ 'syntax': 'markdown', 'ext': '.md',
        \ 'auto_tags': 1,
        \ 'auto_diary_index': 1,
        \ 'auto_generate_links': 1,
        \ 'auto_generate_tags': 1
    \},
\]
let g:vimwiki_conceallevel = 2
" disable setting the 'vimwiki' filetype for all markdown files
let g:vimwiki_global_ext=0
let g:vimwiki_dir_link='index'
let g:vimwiki_auto_chdir=1
let g:vimwiki_url_maxsave=0
```

Output of `:VimwikiShowVersion`:

```
Branch: dev
Revision: 45025fa
Date: 2019-08-01 05:19:39 -0600
```

**Comment by ranebrown** [comment]
Pretty sure that behavior was intentional at the time but it might make more sense to have the behavior be consistent. It is a pretty simple change - on [these lines](https://github.com/vimwiki/vimwiki/blob/28d78b0d3906449b4a653b41066b98f6f8c0d838/plugin/vimwiki.vim#L376-L379) the `v:count1` should just need changed to `v:count`.

**Comment by sangaline** [comment]
It's just one anecdote, but my vote as a user would be to do that because I flip between the diary and wiki much more frequently than I flip between the different wikis.

**Comment by ranebrown** [comment]
I implemented this change (`<leader>ww` opens index of active wiki). Let me know if you see any issues.

**Comment by sangaline** [comment]
Thank you!
