### ISSUE TITLE
Tag management commands not available

### ISSUE THREAD

**Issue by somospocos** [vimwiki/vimwiki#743]
I am running the dev branch:

    Branch: dev
    Revision: 28d78b0
    Date: 2019-08-19 21:59:08 -0700

I lack the tag management commands :VimwikiRebuildTags, :VimwikiGenerateTags and :VimwikiSearchTags when I type :Vimwiki&lt;TAB&gt;

I have read about them in the vimwiki help file but for some reason they don't work for me. Is it because they were documented but not implemented yet or should I do some additional setting to be able to use them?

**Comment by ranebrown** [comment]
Those commands are only available when you are in a vimwiki buffer. Open the index page to your wiki and then try those commands.

**Comment by somospocos** [comment]
> Open the index page to your wiki and then try those commands.

Thank you.
