### ISSUE TITLE
Sending wiki as a static webpage to others

### ISSUE THREAD

**Issue by isaiahfisher** [vimwiki/vimwiki#748]
Vimwiki gurus,

I am using Vimwiki to document a development project and I need to regularly send the resulting wiki to our project supervisor. I would like it if my css could be found in the same directory as my vimwiki .html files. I send the files in a tar/zip archive with style.css and each .html file inside. The wiki pages themselves all work, but the css does not work when sent to another machine. Is there an edit I can make to the html converter in order to make sure the .html files are able to look for style.css in the directory which they are in.

sorry if this request and question do not make sense. I would be happy to clarify if needed.

Best,
Isaiah Fisher

**Comment by ranebrown** [comment]
I think you can use the `css_name` option and just set it to a relative path. (`:h vimwiki-option-css_name`). If you open one of the generated html files in a text editor you can check the path being used for the css. You can also manually edit the path in the html file for testing purposes.

**Comment by isaiahfisher** [comment]
@ranebrown will that allow it to be transferrable between machines as a zipped directory of .html files or will the HTML generator script build the relative path as a full path based on the machine?

**Comment by ranebrown** [comment]
That is my thought but I haven't tested it. If you run into problems post back here with the settings you were using in your vimrc and what occurred.
