### ISSUE TITLE
wikilinks don't work when vim-pandoc is loaded

### ISSUE THREAD

**Issue by mickmcq** [vimwiki/vimwiki#749]
I have set

```vim
let g:vimwiki_list = [{'path': '~/vimwiki/', 'path_html': '~/vimwiki_html/', 'syntax': 'markdown', 'ext': '.md'}]
```

in my .vimrc so that my vimwiki files are markdown. Sometime between May and September 2019, wikilinks stopped working when I have the vim-pandoc plugin loaded. I believe that it worked before that. When I press enter on a wikilink the behavior is to go to the beginning of the next line, which is the default behavior of the enter key.

VimwikiShowVersion outputs Stable version: '2.4.1'

**Comment by ranebrown** [comment]
I would guess vim-pandoc is remapping your enter key. Vimwiki remaps enter to properly work with lists and to follow links. If the mapping is overwritten things won't work as expected. Try running `:verbose imap <CR>` from within one of you wiki pages.

**Comment by mickmcq** [comment]
I get "No mapping found"

I then tried to manually remap it, copying line 570 of vimwiki.vim as follows

```vim
    inoremap <silent><buffer> <S-CR> <Esc>:VimwikiReturn 2 2<CR>
```

but with no immediate effect. I may be in over my head here.

**Comment by ranebrown** [comment]
I put the wrong command for you to test. It should be `:verbose nmap <CR>` since you are looking for the behavior to follow links. You should see something like `n  <CR>         @<Plug>VimwikiFollowLink`. If not then it is being overwritten. Sorry for the confusion.

**Comment by mickmcq** [comment]
I also get "No mapping found" for :verbose nmap <CR>

**Comment by ranebrown** [comment]
Does it work if you manually add the mapping `:nmap <CR> <Plug>VImwikiFollowLink`? You are going to have to find what is causing the mapping to be cleared or overwritten. I would recommend starting with a minimal vimrc as described [here](https://vimwiki.github.io/vimwikiwiki/Troubleshooting.html#Troubleshooting-Minimal%20Vimrc) (you can change it to use the master branch instead of dev) and then one-by-one add the plugins and settings you are using in your vimrc.

**Comment by mickmcq** [comment]
No, it doesn't work if I manually add that mapping. Moreover, VimwikiFollowLink does not appear in a list of completions for :Vimwiki although other Vimwiki commands do.

**Comment by ranebrown** [comment]
Ah, him pandoc is probably changing the file type. The file type must be vimwiki. See #461

**Comment by mickmcq** [comment]
The response to :set filetype is "filetype=vimwiki"

**Comment by ranebrown** [comment]
@mickmcq were you able to discover what was causing the issue? Did you find anything useful in #461?

**Comment by jzbor** [comment]
I have the same/a similar problem although I have no pandoc plugin or similar (though I have pandoc installed if that matters). None of the mappings that contain <Enter> are working. 

All of the verbose commands above say that there is no binding. The .md files are recognized as vimwiki.

Here is my [.vimrc](https://github.com/jzbor/dotfiles/blob/master/.vimrc)

**Comment by mickmcq** [comment]
Yes, I was successful using a combination of lines from #461 as follows. I haven't tested this extensively, though:

```vim
let g:vimwiki_list = [{'path': '~/vimwiki/', 'path_html': '~/vimwiki_html/', 'syntax': 'markdown', 'ext': '.md'}]
au FileType vimwiki set syntax=markdown.pandoc
let g:pandoc#filetypes#pandoc_markdown = 0
let g:vimwiki_ext2syntax = {'.md': 'markdown'}
let g:vimwiki_folding='expr'
```

**Comment by jzbor** [comment]
If I try
`:<Plug>VimwikiFollowLink`
I just get
`E488: Trailing characters`

**Comment by wngrtn** [comment]
Potentially, the same issue here. I don't have `vim-pandoc` installed and none of the local mappings (including <CR> for following links) get set after a recent update of my plugins. Global mappings work and `filetype=vimwiki`.

I also tried `execute "normal \<Plug>VimwikiFollowLink"` with my cursor on a link but I get no effect. Is there a way to trace why execute fails to produce any result?

**Comment by wngrtn** [comment]
For me, it was `vim-polyglot` taking over the `markdown` filetype.

@ranebrown, pointed out a simple solution in #788:

```vim
let g:polyglot_disabled = ['markdown']
```
