### ISSUE TITLE
Strikethrough in neovim 0.4.0+

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#750]
So far Vims syntax highlight didn't supported strikethroughed text, therefore VimWiki displays it in brown color.
Neovim 0.4.0 has support for strikethrough text.
It can be tested with:
`:highlight Constant ctermfg=none cterm=strikethrough`

We should think about how we want to integrate this in Vimwiki.

**Comment by Nudin** [comment]
`has('nvim-0.4')` can be used to check for support.

**Comment by greemin** [comment]
Any updates for this issue? Is there a way to get this to work for (n)vim-gui? The posted testcommand "only" works in console. I would like to do something like this in vimwiki:

# 2020-12-28
* [X] write some code
* [X] wash the dog
* ~~[ ] write a letter~~
  * didn't happen because i had a thing

**Comment by tinmarino** [comment]
Hello @greemin,

It is a pleasure to tell you that this issue has been fixed. But you must use the dev branch. You can strikethough like ~~this~~.
Which syntax region is `VimwikiDelText` and get highlighted with strikethrough.

![Screenshot-2020-12-29-10_23_39](https://user-images.githubusercontent.com/6123962/103287130-7b882300-49c0-11eb-9ed2-f6db535f959e.png)

```
:hi VimwikiDelText
VimwikiDelText xxx term=strikethrough
                   cterm=strikethrough
                   gui=strikethrough
```

If you cannot get it work, feel free to ask in a comment here.

**Comment by greemin** [comment]
Hi @tinmarino,

`:hi VimwikiDelText term=strikethrough cterm=strikethrough gui=strikethrough`
works in gvim but not in nvim. There I only get get "Illegal value: strikethrough".

How do I make these changes permanent? I tried adding a line to my vimrc but with no effect.
