### ISSUE TITLE
Feature req: Link updates when moving pages between directories

### ISSUE THREAD

**Issue by edrex** [vimwiki/vimwiki#751]
**Use case:** I have a fairly heirarchical markdown wiki I imported from Zim via pandoc export to markdown. I have some pages that are in the wrong directory (often created accidentally in a journal dir like /Journal/2015/03/MyTopic) since dangling links go to sibling pages by default. I want to be able to move these pages to the root, automatically updating links.

## UI ideas
1. Could support passing an absolute path like `/Foo/MyNewName` to `VimwikiRenameLink
2. Or add a new `VimwikiMoveLink` action that takes a path

Option 2 seems cleaner. Both options require the user to learn more interface.

**Comment by ratfactor** [comment]
Alternatively:

3. Support relative paths when prompted for the new page name:

```
:VimwikiRenameLink
Rename "foo" [y]es/[N]o? y
Enter new name: ../foo
```

(Would move the page up a directory. `Enter new name: ../panda/foo` would move it to a different directory on the same level.)

The challenge is _probably_ to get VimWiki to update relative links in the rest of the wiki.

I'm not sure how well it currently "understands" that these are both the same link:

```
~/my_wiki/index.wiki          [[foo/buzz]]
~/my_wiki/foo/bar.wiki        [[buzz]]
```

The mechanics of moving and/or renaming the page file is no problem: I can comment out the `if` statement in `vimwiki#base#rename_link()` preventing a path in the new page name and then it _does_ move the page when given a relative path.  But my links to the page aren't correctly updated.

**Comment by edrex** [comment]
On Sat, Sep 21, 2019, 7:01 AM Dave Gauer <notifications@github.com> wrote:

> Alternatively:
>
>    1. Support relative paths when prompted for the new page name:
>
> :VimwikiRenameLink
> Rename "foo" [y]es/[N]o? y
> Enter new name: ../foo
>
> (Would move the page up a directory. Enter new name: ../panda/foo would
> move it to a different directory on the same level.)
>
That's what i tried first, so i guess one data point for 3 being least
surprising.

> The challenge is *probably* to get VimWiki to update relative links in
> the rest of the wiki.
>
> I'm not sure how well it currently "understands" that these are both the
> same link:
>
> ~/my_wiki/index.wiki          [[foo/buzz]]
> ~/my_wiki/foo/bar.wiki        [[buzz]]
>
> The mechanics of moving and/or renaming the page file is no problem: I can
> comment out the if statement in vimwiki#base#rename_link() preventing a
> path in the new page name and then it *does* move the page when given a
> relative path. But my links to the page aren't correctly updated.
>
Seems like a naive impl could normalize all links to abs to test, then
normalize to minimal relative path to update (says the person just figuring
out how variables work in vimscript)

**Comment by ratfactor** [comment]
>> I'm not sure how well it currently "understands" that these are both the same link: ~/my_wiki/index.wiki [[foo/buzz]] ~/my_wiki/foo/bar.wiki [[buzz]] 

> Seems like a naive impl could normalize all links to abs to test, then normalize to minimal relative path to update 

That is _exactly_ what I was thinking.  It feels like a robust and generally applicable method, but somebody with a deeper understanding of VimWiki internals might be able to point to a flaw or nasty edge case.  On the other hand, the best way to test it out is probably just to try it.

> (says the person just figuring out how variables work in vimscript)

Ha ha, that's where I was about three weeks ago.  I'm finding it to be arcane, but not nearly as bad as I'd been lead to believe.  Then again, maybe years of PHP and JavaScript have permanently damaged those portions of my brain. :laughing:

**Comment by Jasha10** [comment]
> Seems like a naive impl could normalize all links to abs to test, then normalize to minimal relative path to update (says the person just figuring out how variables work in vimscript)

I wonder if anyone has thoughts on the following alternative to the "normalize to minimal relative path" proposal:
  - if the link was previously a relative link, the updated link should be minimal relative path
  - if the link was previously an absolute link, the updated link should be minimal absolute path

My motivation for the above idea is that users may have different reasons for choosing absolute vs relative paths. Keeping the link relative if previously relative, and absolute if previously absolute, may result in less disruption to that user decision.

**Comment by tinmarino** [comment]
Done in VimwikiRenameLink.
@Jasha10, you are correct, this is the desired behaviour. Well explained.

I think vimwiki still has some bigs with absolute links but those are tracked in (multiple) other tikets
