### ISSUE TITLE
Embedding videos into wiki

### ISSUE THREAD

**Issue by isaiahfisher** [vimwiki/vimwiki#752]
I would like to be able to embed video into my wiki pages. I want to have a single wiki file with several embedded videos as sub wiki pages. These videos will be used to track game demos as part of an incremental development process. I so far have been unable to find a video embedding feature and wanted to know if this was possible to implement in Vimwiki.

**Comment by ranebrown** [comment]
I think your best option is to use a `file:` link which would just open the video with an external program. I'm not sure how complicated it would be to support embedded videos; I don't think GitHub supports that even.

If you really want support for this I would recommend creating a PR. You can also do some research on how it might be accomplished and post info here if you aren't familiar with vimscript. Someone else might be able to pick it up eventually.

**Comment by tinmarino** [comment]
__Html:__  Add the [video](https://www.w3schools.com/html/html5_video.asp) html tag
__Markdown:__ It is not currently supported in markdown, there is a image link trick in [Stackoverflow](https://stackoverflow.com/questions/11804820)
__Wiki:__ [Need extension](https://www.mediawiki.org/wiki/Extension:EmbedVideo) and just add a link to the mp4
__Pdf:__ No standard support: Only acrobat reader support embedded video as far as I know

I close it considering it is not in vimwiki scope. Feel free to reopen if you have some implementation, concrete features ideas.
