### ISSUE TITLE
Folding with markdown syntax and a python code block comments is broken

### ISSUE THREAD

**Issue by OliverKnights** [vimwiki/vimwiki#756]
Branch: dev          
Revision: ba84981
Date: 2019-08-28 03:51:51 -0600

With the following code using markdown syntax and trying to fold headings, vimwiki interprets the python comments as headers and doesn't fold correctly.

    # Python test

    ``` python
    # python comment
    print("test")
    ```

    ## other heading
    other heading text

I would expect folding on the first line using foldmethod=expr to fold the entire file, but it only folds up until the comment 

Thanks

**Comment by ranebrown** [comment]
@OliverKnights can you give the dev branch a try?

Duplicate of #212

**Comment by OliverKnights** [comment]
Works perfectly, thanks!

**Comment by ranebrown** [comment]
No problem!

**Comment by mellery451** [comment]
I have this exact problem in stable version 2.5. Is it possible it regressed for some reason ?
