### ISSUE TITLE
VimWiki should have an option to disable all mappings

### ISSUE THREAD

**Issue by Julian** [vimwiki/vimwiki#758]
Hi.

VimWiki sets quite a few mappings. I'm the kind of user that does not want any plugin setting any mapping, so in general I disable all mappings, and add only the ones I want and will use. It would be extremely helpful if vimwiki offered such an option.

I've seen #282, but that only covers a subset of VimWiki's mappings, and is quite indirect.

Is that something there'd be appetite to add at this point?

**Comment by ranebrown** [comment]
This has already been done on the `dev` branch. Can you give that a try? The documentation is [here](https://github.com/vimwiki/vimwiki/blob/ba84981b5ae54af32e320cd04b583dd7e9fe1c6c/doc/vimwiki.txt#L3311-L3325)

**Comment by Julian** [comment]
Thanks! That does do it.
