### ISSUE TITLE
Highlight Markdown Line Breaks

### ISSUE THREAD

**Issue by GregoryShields** [vimwiki/vimwiki#759]
A couple of days ago I started using vimwiki and so far I like it really well.

However, I quickly noticed that the highlighting I had gotten used to seeing at the end of Markdown lines was no longer present.

What I'm referring to is how two spaces at the end of a line in Markdown produce a line break in the rendered HTML output.  The plasticboy/vim-markdown plugin highlights two or more spaces at the end of lines in a Markdown file so that you can visually see whether a line break will be rendered, and I would like to see that feature implemented in vimwiki.

Here is the relevant line of code in that plugin:
[HtmlHiLink mkdLineBreak     Todo](https://github.com/plasticboy/vim-markdown/blob/b41a604a71bfa1d3e832b67c211f7c356d530ee6/syntax/mkd.vim#L119)

I also noticed that I had to disable the vim-markdown plugin in order to get vimwiki's folding functionality to work. I tried doing this...
let g:vimwiki_folding = 'custom'
...but that did not work.

Therefore, I would like to be able to abandon the other plugin in favor of vimwiki, if only I could get back the ability to visualize line endings where a break occurs.

Thanks,
Gregory Shields

**Comment by ranebrown** [comment]
You should be able to put something in `.vim/after/syntax/vimwiki.vim` to modify the highlighting how you want. Can you give that a try and see if it works?

The custom folding option is more for you to write your own folding function (or use a plugin that doesn't depend on filetype detection). The issue with the vim-markdown plugin is that it expects the filetype to be markdown but vimwiki sets the filetype to vimwiki, even for markdown files.

**Comment by ranebrown** [comment]
@GregoryShields were you able to get something working?
