### ISSUE TITLE
Restricting `<leader>w<leader>w` to only create/switch-to the diary in the default Wiki?

### ISSUE THREAD

**Issue by llinfeng** [vimwiki/vimwiki#761]
I chose to use `markdown` as the syntax for my Wiki and have been accidentally creating a new directory (`/diary`) and new diary files in project folders where I was actually editing the readme files. (These readme files are also ending in `*.md`.) It was musle memory for me to press `<leader>w<leader>w` to get to the diary of the day, and it always surprises me when I got a blank buffer opened in the newly created `/diary` directory in the project folder.

Since I only use on Wiki, **can I restrict `<leader>w<leader>w` to only open the diary page/file in my default wiki?**

I tried the following mapping in `~/vimfiles/after/syntax/vimwiki.vim` and it does nothing at all; it even wipes out the existing functionality of `<leader>w<leader>w` completely (I must have got the mapping wrong).
```
nnoremap <leader>w<leader>w 1<leader>w<leader>w
```
Please advise if there is a simpler command that I can (re-)assign to `<leader>w<leader>w` so that it only opens/creates the diary in the **default Wiki**.

**Comment by ranebrown** [comment]
You should be able to add something like this to you `.vimrc`. Replace `1` with whatever wiki you want it to always use.

```vim
nnoremap <silent> <leader>w<leader>w :VimwikiMakeDiaryNote 1<CR>
```

**Comment by llinfeng** [comment]
@ranebrown I am with Version: 2.4.1 and I assume `:VimwikiMakeDiaryNote ` command does not take a trailing argument at all? Here is what I see without the mapping (the mapping above failed as well).

![TryingMakDiary_with_arg](https://user-images.githubusercontent.com/5890407/67104491-0bafc300-f195-11e9-8b2e-8e8df7012b40.gif)

**Comment by ranebrown** [comment]
Yeah, you will need to use the dev branch for that to work

**Comment by llinfeng** [comment]
@ranebrown Thank you for pointing me to the dev-branch. It does both things correctly:
1. `:VimwikiMakeDiaryNote` does take arguments, and
2. Dropping the following line anywhere in the `~/.vimrc` shall work
    ```
    nnoremap <silent> <leader>w<leader>w :VimwikiMakeDiaryNote 1<CR>
    ```
Lastly, will the dev-branch be merged to master in the near future? I have a number of machine that I work with daily.

----

In `Version 2.4.1`, the following error shall occur when I start Vim with the one-liner mapping in my `~/.vimrc`.
![image](https://user-images.githubusercontent.com/5890407/67108512-b1b2fb80-f19c-11e9-9c57-98754cd2cb2e.png)

**Comment by ranebrown** [comment]
No problem. I was hoping to get the changes merged to master before Christmas. Hopefully sooner but everyone that works on this project has been pretty busy lately.

**Comment by ranebrown** [comment]
@llinfeng are you ok with closing this since you can get things to work as expected with the dev branch?

**Comment by llinfeng** [comment]
Closing this ticket as switching to the `dev` branch helped.
