### ISSUE TITLE
Weird index behavior with lazy-loading UltiSnips

### ISSUE THREAD

**Issue by krisezra87** [vimwiki/vimwiki#762]
Not a bug, but I'm getting weird behavior I'm not sure how to troubleshoot.

I use ultisnips to create new index entries by date.  When I load my index with <leader>ww and try to expand a lazy-loaded ultisnips snippet, my snippet doesn't work for one, and the index goes to the "normal" view where links are not collapsed, almost like vimwiki is off somehow, but it's loaded in :scriptnames.  If I open it again with <leader>ww, everything behaves normally as it did before I implemented lazy loading.  My lazy load looks like this:

function! UltiSnipsLazyLoad()
    call plug#load('ultisnips')
    imap \<silent\> \<leader\>\<leader\> \<C-R\>=UltiSnips#ExpandSnippetOrJump()\<CR\>
    return UltiSnips#ExpandSnippetOrJump()
endfunction

inoremap \<silent\> \<leader\>\<leader\> \<C-r\>=UltiSnipsLazyLoad()\<CR\>

Any idea what is up or how to fix?  It's rather inconvenient and I like the lazy loading so I'd like to keep it in general.

My vimwiki config:
" Use markdown instead of vimwiki syntax
let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
" help -> "h vimwiki-syntax

let g:vimwiki_global_ext = 0

let core_wiki = {}
let core_wiki.path = '\~/.vimwiki/'
let core_wiki.syntax = 'markdown'
let core_wiki.ext = '.md'

" Prevent write on quit if there are mods
let g:vimwiki_autowriteall = 0

if !empty(glob(expand("\~/work_notes/")))
    let work_wiki = {}
    let work_wiki.path = '\~/work_notes/'
    let work_wiki.syntax = 'markdown'
    let work_wiki.ext = '.md'
    let g:vimwiki_list = [core_wiki, work_wiki]
else
    let g:vimwiki_list = [core_wiki]
endif
Version: Stable 2.4.1

**Comment by krisezra87** [comment]
I also notice if I leave a buffer and come back that this problem resolves itself, but I'd like to fix it in the lazy load or vimwiki to resolve all at once.

**Comment by ranebrown** [comment]
I would guess it is related to the filetype setting. Maybe try this:

```vim
function! UltiSnipsLazyLoad()
call plug#load('ultisnips')
set filetype=vimwiki " possible fix
imap <silent> <leader><leader> <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>
return UltiSnips#ExpandSnippetOrJump()
endfunction
```

**Comment by krisezra87** [comment]
Thanks that solved the issue!  I'm a little new to vimscript but I'm going to try to build a more robust solution.  This breaks ultisnips if the original class is not actually a vimwiki file type (obviously) so I think I need to read the class first, save it local, then load ultisnips, and set the filetype back to whatever it was originally.

If I get it done I'll re-post it here, but if you happen to be able to do this off the top of your head I'll keep a watch on the issue.

**Comment by krisezra87** [comment]
Ok for anybody that bothers to find this, here's the answer:

```
function! UltiSnipsLazyLoad()
    let l:my_ft = &filetype
    call plug#load('ultisnips')
    let &filetype = l:my_ft
    imap <silent> <leader><leader> <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>
    return UltiSnips#ExpandSnippetOrJump()
endfunction

```
To make ultisnips play nice with vimwiki (and also other file types), simply cache the filetype to a variable, then set it again after ultisnips loads.  This is NOT a vimwiki issue but maybe someone will find it here.
