### ISSUE TITLE
How do I uninstall vimwiki completely?

### ISSUE THREAD

**Issue by haranrk** [vimwiki/vimwiki#770]
I installed via `Vim-plug` by adding the following to the config
```
Plug 'vimwiki/vimwiki'
```
I uninstalled it by removing the line above and calling `PlugClean`

However, even after that the `.md` files (which were associated with vimwiki) continue to have the `vimwiki` filetype and keymappings

**Comment by ranebrown** [comment]
You must have an additional copy of Vimwiki installed somewhere. You should be able to run `:verbose nmap <leader>ww` to see where a keymapping is being defined from.

**Comment by haranrk** [comment]
When I run
```
:verbose nmap <Tab>
```
I get this
```
n  <Tab>        @<Plug>VimwikiNextLink
        Last set from ~/.local/share/nvim/view/~=+somepath=+somepath=+file.md= line yy
   <Tab>       * :tabnext<CR>
        Last set from ~/.vimrc line xx
```

**Comment by ranebrown** [comment]
That path is strange looking, not sure what is going on with that.
You can also do `:set runtimepath?` to see all the locations that vim is loading from. You have some spare files somewhere that you need to remove. This isn't really a Vimwiki issuse but something related to how you installed/uninstalled it.

**Comment by ranebrown** [comment]
> How do I locate this additional copy?
Maybe just trying moving `~/.local/share/nvim` to a backup location and start from scratch with your plugins.
