### ISSUE TITLE
Better links with spaces in markdown mode

### ISSUE THREAD

**Issue by squito** [vimwiki/vimwiki#771]
I use vimwiki in markdown mode, and overall it works wonderfully.  I especially love being able to push my wiki to github, and now I've got a fully browsable version of my wiki for folks that don't use vimwiki.

However, I've run into one wrinkle.  If I create a link in vimwiki, the created file and the link itself have a space in them.  Vimwiki itself understands this fine, but when I push to github, the links are broken.  I thought this was a github bug, but actually its not part of the common mark spec: https://spec.commonmark.org/0.25/#link-destination
https://github.com/nteract/nteract/issues/914

I understand this is "my fault" for creating a link with a space in it in the first place.  I've worked around this by manually using '_' instead.  As a bonus, I prefer filenames without spaces anyway. 
 But, it would be nice if there was an option to automatically sanitize links & filenames like this.

I'm running "Stable version: '2.4.1'".  

Thanks again for vimwiki, its a fantastic tool!

**Comment by ranebrown** [comment]
Does [this option](https://github.com/vimwiki/vimwiki/blob/241126631dd902e3efde34060bb4d2f8c6cda4ab/doc/vimwiki.txt#L2195-L2209) on the `dev` branch work for you?

**Comment by squito** [comment]
yes that looks perfect!  Sorry I missed it.

(A quick test of the dev branch led to some other errors, so I haven't actually tried this, but the feature looks perfect.)

**Comment by fancypantalons** [comment]
Just tested in the dev branch and it definitely does what I'm looking for!  I also see 4458216, which makes me a very happy camper, as that was another nuisance that was troubling me but I was too lazy to investigate fixing...

**Comment by Arrow-x** [comment]
It also breaks because vimwiki doesn't generate a link with the file extension.
