### ISSUE TITLE
Bug: can't follow the txt with "vim: 稳"

### ISSUE THREAD

**Issue by ChenWeird** [vimwiki/vimwiki#772]
**1. Checkout the `dev` branch and confirm the issue is present there as well.
   The `dev` branch contains fixes that may not have been merged to `master` yet.**

```Plug 'vimwiki/vimwiki', { 'branch': 'dev' }```

**2. Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`**

syntax: default
vimrc:
```
let wiki = {}
let wiki.name = 'Personal'
let wiki.path = 'd:/Vimwiki/'
let wiki.ext = '.wiki'
let wiki.syntax = 'default'
let wiki.nested_syntaxes = {'python': 'python'}
let wiki.links_space_char = '_'
" If use Markdown or MediaWiki syntax, set this option to 0, else to 1
let wiki.list_margin = 1
let wiki.auto_toc = 1
let wiki.auto_tags = 1
let wiki.auto_generate_tags = 1

let g:vimwiki_list = [wiki]
let g:vimwiki_auto_chdir = 1
```
**3. Provide a detailed description of the problem including **steps to reproduce the issue**.**

1.  In any wiki page,  move cursor to the word 'anyword' and press `Enter`.  This will create a Vimwiki link :'[[anyword]]'.
2. Add the following txt to new line ```vim: 稳```
![special txt](https://i.imgur.com/hpFRwDF.png)
3. Backspace. 
4. Follow the link '[[anyword]]', there are errors:
![Error message](https://i.imgur.com/IuSWdii.png)

**4. Include the output of `:VimwikiShowVersion`.**

```
Branch: dev
Revision: 2411266
Date: 2019-10-28 05:05:03 -0600
```

**Comment by ChenWeird** [comment]
And if I change the txt "v" to capital "V"， Vimwiki haven't error, returns to normal.
![New special txt](https://i.imgur.com/gK6x3nu.png)

**Comment by ranebrown** [comment]
Vim is interpreting that as a `modeline` and trying to process commands. If you `set nomodeline` you shouldn't see any errors. Does that resolve your problem?

**Comment by ChenWeird** [comment]
It has resolve my problem! Thanks!
