### ISSUE TITLE
Optionally convert whitespace to non-white in visual mode link creation

### ISSUE THREAD

**Issue by fancypantalons** [vimwiki/vimwiki#773]
I've implemented a cheap hack for this in my local copy of the vimwiki module, but before I spend time learning the codebase, I figured I'd describe the idea and see if it has merit for mainline.

Basically, today, if you run a visual mode selection over multiple words and press <CR> you get a link to a new page that includes spaces in the file name.  But not everyone wants to put spaces (for example) in their filenames, either as a matter of personal preference, or due to compatibility issues (for example, Vimwiki Markdown isn't compatible with Markor because the spaces in the links cause the latter to get confused (technically they're supposed to be %20's, which then Vimwiki doesn't handle)).

The simplest solution, in my mind, is to give the user an option to convert whitespace to a safe characters (underscore, dash, etc) when creating new pages.

My hacked vimwiki instance does the latter.  In my case it's specifically for markdown files, and converts spaces to underscores in the file name (but not the description), but a generalized option would include a new configuration variable to set the alternative whitespace character in URLs.

Anyway, if this could get accepted but you don't have time, I could take a run at implementing it myself.

**Comment by ranebrown** [comment]
See #771

**Comment by ranebrown** [comment]
Also #707

**Comment by fancypantalons** [comment]
You must really get tired of pointing people to those issue keys... *sigh*  Thank you. :)

**Comment by ranebrown** [comment]
Haha, no worries :)

**Comment by ibnishak** [comment]
For those who want to make the links compatible with **markor** but not want to install **dev** branch.

- Open the location where vimwiki plugin is installed. If you are using [vim-plug](https://github.com/junegunn/vim-plug), the location would be `~/.cache/nvim/plugged/vimwiki/`
- In the location, open the file `autoload/vimwiki/markdown_base.vim`
- In the function `s:normalize_link_syntax_v()`, find the line that says `let link = s:safesubstitute(link, '__LinkDescription__', visual_selection, '')`
- Add the following line **before** the above line
```vim
" Change the spaces to hyphens
let link = substitute(link, '\s', '-', 'g')
" Change uppercase to lowercase
let link = substitute(link, '[A-Z]', '\L&', 'g')
```
- Restart vim/nvim
