### ISSUE TITLE
[html conversion] Ignoring certain lines and pasting them to the html file as they are

### ISSUE THREAD

**Issue by kaphula** [vimwiki/vimwiki#774]
Hey,

I was wondering how would it be possible to add custom `<div>` tags from the vimwiki file so that the tags would show up in the html conversion. With `<div>` tags,  I could decide case by case how certain elements are being displayed on the web page. As it is, I have to use uniform styling for all of the same kind of html elements.

Having said that, writing `<div>` tags straight into the vimwiki file kinda works, but the conversion system wraps them inside `<p>` tags. If it were possible to mark lines to be ignored during the conversion, this approach would probably work no problem as the `<div>` tags would appear in the html file without any modifications.

Unless there are methods in place that allows to do this already, I'd like to suggest a new feature that would work something like this. The name of the marker that triggers ignoring should probably be clean and short, but in this example it is  `<vimwiki_html_ignore>`

**How it looks in the vimwiki file:**
```
<vimwiki_html_ignore> <div id="move_to_left">
= My regular header =
My regular vimwiki paragraph.
<vimwiki_html_ignore> </div>
```

**How it looks in the html conversion:**

```
<div id="move_to_left">
<h1> My regular header </h1>
<p> My regular vimwiki paragraph </p>
</div>
```

Any tips on how to implement this feature are welcome, since I can also try to implement it myself, although I am not very experienced with vimscripting.

**Comment by ranebrown** [comment]
I haven't done any work with the html conversion but you are welcome to take a look at it and submit a PR if you get something working.

**Comment by kaphula** [comment]
Cool. I already got it to work with custom modification, but there's still an issue when "the line to be ignored" is not surrounded by empty lines, because otherwise it will be considered part of the preceding paragraph and the nested order of html elements break.

Here's the modification that enables line ignoring when the line starts with **%plainhtml** prefix.

This snipper can be inserted as the first "processed" check inside the function:
_autoload_ > _html.vim_ > _function! s:parse_line(line, state)_

```
  if !processed
    let trigger = '%plainhtml'
    if line =~# '^\s*' . trigger
      let pp = split(line, trigger)
      call extend(res_lines, pp)
      let processed = 1
    endif
  endif
```
If you know a quick fix for the issue described above or there is something fishy with the code snippet, please let me know. I literally started learning vimscript at the same time as I started to investigate how to add this feature. I'll do a pull request once I get it to work properly.

**Comment by tinmarino** [comment]
Closed by your PR 778. Nice share @kaphula.
