### ISSUE TITLE
[bug] VimwikiGenerateLinks can't generate subfolder files correctly.

### ISSUE THREAD

**Issue by VimWei** [vimwiki/vimwiki#775]
**1. Checkout the `dev` branch and confirm the issue is present there as well.
   The `dev` branch contains fixes that may not have been merged to `master` yet.**

```Plug 'vimwiki/vimwiki', { 'branch': 'dev' }```

**2. Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`**

syntax: default
vimrc:
```
let wiki = {}
let wiki.name = 'Personal'
let wiki.path = 'd:/Vimwiki/'
let wiki.ext = '.wiki'
let wiki.syntax = 'default'
let wiki.nested_syntaxes = {'python': 'python'}
let wiki.links_space_char = '_'
" If use Markdown or MediaWiki syntax, set this option to 0, else to 1
let wiki.list_margin = 1
let wiki.auto_toc = 1
let wiki.auto_tags = 1
let wiki.auto_generate_tags = 1

let g:vimwiki_list = [wiki]
let g:vimwiki_auto_chdir = 1
```
**3. Provide a detailed description of the problem including **steps to reproduce the issue**.**

1.  `:VimwikiGenerateLinks`
2.   GenerateLink   `- [[diary\2019-11-14]]`  ,  and it can't be followed correctly.

Correct mechanism   `\`  ==> `/` ，   `- [[diary/2019-11-14]]`

**4. Include the output of `:VimwikiShowVersion`.**

```
Branch: dev
Revision: 2411266
Date: 2019-10-28 05:05:03 -0600
```

**Comment by ranebrown** [comment]
What page are you on when you run `VimwikiGenerateLinks`?

Are you on Windows?

**Comment by ChenWeird** [comment]
The page is under vimwiki root, just any new page followed from index.
The target page is vimwiki diary.

I use gvim in Windows 10.

- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  vim 8.1 (2018 May 18) MS-windows 32位图形界面版本，带OLE支持 包含补丁1  巨型版本
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python36.dll
- Output of `:py print(sys.version)`: 此命令不可用
- Output of `:py3 print(sys.version)`: 3.6.6 [MSC v.1900 32 bit (Intel)]
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.

**Comment by ChenWeird** [comment]
Now I have transfer from default syntax to markdown. This problem still exists:

`:VimwikiGenerateLinks` generate links as: ` [diary\diary](diary\diary)` and `[diary\2019-12-31](diary\2019-12-31)`, and it can't be follow.

The correct links should be ` [diary/diary](diary\diary)` and `[diary/2019-12-31](diary\2019-12-31)`

**Comment by levirs565** [comment]
I also have same problem. But i have been fix my issue with my  [my pull request](https://github.com/vimwiki/vimwiki/pull/1057). This pull request maybe resolve your problem. **Please check if this pull request resolve your problem!**

**Comment by VimWei** [comment]
Thanks! It work!
