### ISSUE TITLE
Help debugging very down slow vimwiki#base#open_link

### ISSUE THREAD

**Issue by dgrabla** [vimwiki/vimwiki#777]
Hello,

I used vimwiki for a couple of years now and have a big collection of journal files. Lately I noticed vim blocks for a relatively long time every time I open *for the first time* a vimwiki buffer. That means, it happens when I first open vim wiki with 
<leader>wi or when I travel from a journal file to the previous / next.

I profiled vim and found the culprit on this call `execute a:command fname` on base.vim
![image](https://user-images.githubusercontent.com/1942073/69410892-38af4280-0d0c-11ea-8101-611c08a12e46.png)

My problem is that I don't know what this line does, the profiler doesn't tell me what function is running or if the problem is on vimscript, or maybe waiting for i/o (The files are on a SSD, it should not be the problem). 

Do you have any hints what the problem on that line could be or alternatively what can I do to get more details about what is the command being executed? Whatever it does, does it need to run synchronously?

:VimwikiShowVersion` Stable version: 2.4.1

```
:version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-
fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/dgrabla/s
rc/neovim/build/config -I/home/dgrabla/src/neovim/src -I/home/dgrabla/src/neovim/.deps/usr/include -I/usr/include -I/home/dgrabla/src/neovim/build/src/nvim/auto -I/home/dgrabla/src/neovim
/build/include
Compiled by dgrabla@Atalanta

Features: +acl +iconv +tui
```

**Comment by dgrabla** [comment]
Something similar was reported in 2017 by @llinfeng. The interesting thing is that he experienced a huge slowdown with his Thinkpad X230 with a slow SSD and I am also using a X230, with an old SSD.

Therefore it could be the problem are too many I/O calls - even for an SSD. But if thats the problem it should make vimwiki unusable on old harddrives and AFAIK nobody complained yet. 

Maybe it is a filesystem issue? I am using BRTFS on this partition.

Does vimwiki list the files to get the filename or opens every journal files to retrieve also the title?

**Comment by ranebrown** [comment]
How many files and avg line count per file so I can see if I can duplicate this?
