### ISSUE TITLE
Why doesn't the tag file meet Ctags' standards?

### ISSUE THREAD

**Issue by ChenWeird** [vimwiki/vimwiki#779]
**Standards tags file has six lines:**
```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.8	//
```
**But Vimwiki's tags file has only one line:**
```
!_TAG_FILE_SORTED	1
```
So, another great vim plugin `Leaderf` can't read the vimwiki tags file accurately.
https://github.com/Yggdroot/LeaderF/issues/381

**Comment by ranebrown** [comment]
Take a look at #85 for the discussion regarding the usage of tags. Using the ctags standard probably just wasn't thought of since it is a pretty specific use case. Feel free to open a PR that modifies the behavior to meet the standard.

**Comment by ChenWeird** [comment]
Thanks! But I'm not a programmer, do not know how to fix and PR. It would be great if you fix it.

**Comment by ranebrown** [comment]
@ChenWeird can you try this update? I'm not sure jumping to the file will work correctly with how the Vimwiki tags are formatted but they should be readable at least.

**Comment by ChenWeird** [comment]
It works correctly! Thanks!
