### ISSUE TITLE
Feature request: Cycle todo-item check-marks

### ISSUE THREAD

**Issue by Ginner** [vimwiki/vimwiki#782]
First off, thanks for your amazing work on this project. I use it a lot! 

Seems like @Nudin has been doing a lot of work on somewhat similar functionalities in #557. However I'd love some additional functionality.

I was wondering if it would be possible to implement a 'check-mark cycle feature'? 
What I'd like is that when I'm on a todo-item and hit `<C-Space>`, I'll firstly check it (`- [X] Whatevs)` and then if I press `<C-Space>` again, I'd cycle through a custom list of 'check marks'.

The functionality I'd hope to achieve is to cycle a list of TaskWiki status marks, i.e. `_XDS`. So, if I'm on a todo-item I'll press `<C-Space>` to check it with a `X`, maybe hit `<C-Space>` again to mark it with a `D` instead (in this case meaning 'deleted'), again to mark it with an `S` (meaning 'started'), and again to start the cycle over with a space for 'pending'.

The list should of course be custom so users could specify what suits them best, with the default being `<space>, X` (maybe throw the `-` in there?).

P.s. I think I remember similar functionality from Emacs Org-mode.

**Comment by Nudin** [comment]
Basically you can do this already, by "misusing" one of the features I've built in:

With `g:vimwiki_listsyms` you can specify different states with different chars. For example I use unicode signs for different progress from not yet started to finished:
```
let g:vimwiki_listsyms = ' ▁▂▃▄▅▆▇✓'
```
You could set it to ' XDS'.

You can then cycle through the different states by VimwikiIncrementListItem or VimwikiDecrementListItm. You can map them to any key binding.
```
nmap <C-Space> <Plug>VimwikiIncrementListItem
vmap <C-Space> <Plug>VimwikiIncrementListItem
```

But: you have to be aware that even through this does what you want, the semantics are different: the first and last char in `vimwiki_listsyms` are considered "not yet started" and "finished", the chars in between are considered different states of in progress. Therefore you will get surprising behavior in afaik two situations:
* The HTML rendering will show a progress-bar
* When using sub points the progress of the the parent point will be updated based on the progress of the sub tasks.

**Comment by Ginner** [comment]
Yeah, you're right. However I've also grown quite fond of the progress indicator :)

My current workflow is also totally acceptable. I can toggle pending/done (` `/`X`) with `<C-Space>`, toggle start (`S`) with the TaskWiki binding `<leader>t+` and delete with `<leader>tD`. So I'm just being difficult.

I'll close the issue, as I'm sure there's plenty more pressing stuff to be done. However, I hope it ends up one some list somewhere, as a possible future feature. I think it'd be a neat feature to have :)
