### ISSUE TITLE
Links generated by `:VimwikiGenerateLinks` always use vimwiki syntax

### ISSUE THREAD

**Issue by S73ph4n** [vimwiki/vimwiki#786]
When I use` :VimwikiGenerateLinks `on my markdown wiki, it generates links in vimwiki syntax. Example : 
```
# Generated Links
        - [[academic/index]]
        - [[academic/todo]]
```
Where I would instead want : 
```
# Generated Links
        - [academic/index](academic/index)
        - [academic/todo](academic/todo)
```
This does not happen when creating a link in any other way, including with `:VimwikiDiaryGenerateLinks` or `:VimwikiTOC` : those follow correct markdown syntax.
I believe the problem to be similar to #499 , but I have so far not been able to fix it.

I'm using markdown syntax on Vimwiki version 2.4.1. Same thing with dev branch and minimal .vimrc.
Here's the config from my .vimrc :
```
let vimwiki_path=$HOME.'/vimwiki/'
let vimwiki_html_path=$HOME.'/vimwiki_html/'
let g:vimwiki_list = [{'path_html':vimwiki_html_path,
			\ 'syntax':'markdown',
		        \ 'ext':'.md',
			\ 'custom_wiki2html':$HOME.'/.vim/bundle/vimwiki/autoload/vimwiki/customwiki2html.sh'}]
```
Thank you for all the good work you have done with Vimwiki.

**Comment by ranebrown** [comment]
Can you confirm you still see this behavior with a [minimal vimrc](https://vimwiki.github.io/vimwikiwiki/Troubleshooting.html#Troubleshooting-Minimal%20Vimrc)?

**Comment by S73ph4n** [comment]
It does indeed get fixed with this procedure. I'll find what I did wrong, sorry for the inconvenience.

**Comment by ranebrown** [comment]
No worries. Good luck!
