### ISSUE TITLE
Enter key not working on Ubuntu 19.10

### ISSUE THREAD

**Issue by just-a-nick** [vimwiki/vimwiki#788]
I have a problem similar to [issue 716](https://github.com/vimwiki/vimwiki/issues/716) (and probably [issue 749](https://github.com/vimwiki/vimwiki/issues/749)): When pressing **enter**, the cursor just moves to the line below.

`noremap <CR> :VimwikiFollowLink<cr>` does not work, it gives the following error message:

> E492: Not an editor command: VimwikiFollowLink 

I also cannot tab complete _VimwikiF_. There are also other Vimwiki commands that seem to be missing (e.g., the commands to convert wiki pages to html). Other commands, however, do exist (e.g., _VimwikiIndex_) and can be tab completed.

`verbose nmap <CR>` gives the following output:

> No mapping found

When using the [minimal example](https://vimwiki.github.io/vimwikiwiki/Troubleshooting.html#Troubleshooting-Minimal%20Vimrc), **enter** is working correctly. My Vimwiki is installed by vim-plug; the runtime path seems to be correct: _~/.vim/bundle/vimwiki_.

I have noticed said problem only now. It might have to do with a distro upgrade (Ubuntu 19.04 to 19.10) or with new plugins (I tried to deinstall new plugins in order to solve the problem, but to no avail). My Vimwiki version is 2.4.1.

The following (correct) paths are in my vimrc:

> let g:vimwiki_list = [{
  \ 'path': '$HOME/.../Vimwiki/',
  \ 'template_path': '$HOME/.../Vimwiki/templates',
  \ 'template_default': 'default',
  \ 'template_ext': '.html'}]

Any ideas how to solve this problem?

**Comment by wngrtn** [comment]
Same symptoms here on up-to-date Void Linux and Win10.

The mappings that work are the global ones. Local mappings don't work.

**Comment by just-a-nick** [comment]
I have done some more testing by de-installing plugins one by one: In my case, [vim-polyglot](https://github.com/sheerun/vim-polyglot) is the culprit: Without it, Vimwiki works again.

@wngrtn: Same problem/solution for you?

**Comment by ranebrown** [comment]
Another plugin must be taking over the filetype so none of the buffer local mappings or commands get set. For vim-polyglot you should be able to do `let g:polyglot_disabled = ['markdown']`. Other than that you will need to go through your `.vimrc` and find out what is causing the conflict.

**Comment by wngrtn** [comment]
`vim-polyglot` was indeed the culprit and `let g:polyglot_disabled = ['markdown']` fixed it for me. Many thanks!

**Comment by just-a-nick** [comment]
Thanks,  ranebrown!
