### ISSUE TITLE
vimwiki-option-list_margin can't work

### ISSUE THREAD

**Issue by ChenWeird** [vimwiki/vimwiki#789]
**1. Checkout the `dev` branch and confirm the issue is present there as well.   The `dev` branch contains fixes that may not have been merged to `master` yet.**

```
    Plug 'vimwiki/vimwiki', { 'branch': 'dev' }
```

**2. Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`**

```
    let wiki = {}
    let wiki.name = 'Personal'
    let wiki.path = 'd:/Vimwiki/'
    let wiki.ext = '.wiki'
    let wiki.syntax = 'default'
    let wiki.nested_syntaxes = {'python': 'python'}
    let wiki.links_space_char = '_'
    " If use Markdown or MediaWiki syntax, set this option to 0
    let wiki.list_margin = 1
    let wiki.auto_toc = 1
    let wiki.auto_tags = 1
    let wiki.auto_generate_tags = 1

    let g:vimwiki_list = [wiki]
    let g:vimwiki_auto_chdir = 1

    let g:vimwiki_folding = 'expr'
```

**3. Provide a detailed description of the problem including** 

```
1) vim
2) <leader>ww
3) itest<esc>
4) gl*
```
**Whatever let wiki.list_margin = -1  or 0 or 1,   width of left-hand margin for lists always use the current 'shiftwidth'.**

```set shiftwidth=4```  

**A few weeks ago, width of left-hand margin for lists was only one space, but now it's four spaces.**

**4. Include the output of `:VimwikiShowVersion`.**

Branch: dev
Revision:3cc6fa7
Date: 2019-12-21 09:16:48 -0700

**Comment by ranebrown** [comment]
Thanks for reporting this. A recent change is overwriting user settings for that option. I'll fix it by the end of the day.

**Comment by ranebrown** [comment]
@ChenWeird Can you give it a try now?

**Comment by ChenWeird** [comment]
Thanks! User setting of list_margin can work.
