### ISSUE TITLE
VimwikiGenerateTags got Vimwikierror: Tags must appear after a header.

### ISSUE THREAD

**Issue by ChenWeird** [vimwiki/vimwiki#790]
**1. Checkout the `dev` branch and confirm the issue is present there as well.   The `dev` branch contains fixes that may not have been merged to `master` yet.**

```
    Plug 'vimwiki/vimwiki', { 'branch': 'dev' }
```

**2. Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`**

```
    let wiki_2 = {}
    let wiki_2.name = 'Markdownwiki'
    let wiki_2.path = 'd:/Markdownwiki/'
    let wiki_2.ext = '.md'
    let wiki_2.syntax = 'markdown'
    let wiki_2.nested_syntaxes = {'python': 'python'}
    let wiki_2.links_space_char = '_'
    let wiki_2.list_margin = 0
    let wiki_2.auto_toc = 1
    let wiki_2.auto_tags = 1
    let wiki_2.auto_generate_tags = 1

    let g:vimwiki_list = [wiki_2]
    let g:vimwiki_ext2syntax = {'.md': 'markdown'}
    let g:vimwiki_global_ext = 1
    let g:vimwiki_autowriteall = 1
    let g:vimwiki_auto_chdir = 1
    let g:vimwiki_folding = 'expr'

```

**3. Provide a detailed description of the problem including** 

```
1) vim
2) <leader>ww
3) :VimwikiGenerateTags
4) There is a message:  Vimwikierror: Tags must appear after a header.
```

**It only Generate a header: # Generated Tags**
**but no any Tags contents.**

**And If I use 'default' syntax, `:VimwikiGenerateTags` can work.**

**4. Include the output of `:VimwikiShowVersion`.**

Branch: dev
Revision:19f9134
Date: 2019-12-23 13:35:31 -0700

**Comment by ranebrown** [comment]
The vimwiki error message was added to prevent a bunch of other error messages. Currently the markdown syntax doesn't handle placing a tag that doesn't fall under a header. I'm working on fixing this and making some new test cases.

**Comment by ChenWeird** [comment]
Thanks! I'm transfering from default syntax to markdown syntax today.

**Comment by ranebrown** [comment]
@ChenWeird Can you pull the latest and check if it works for you?

**Comment by ChenWeird** [comment]
Cool! It's working! Thanks!
