### ISSUE TITLE
Feature idea: git support

### ISSUE THREAD

**Issue by Unip0rn** [vimwiki/vimwiki#791]
I just noticed vimwiki doesn't offer managing wikis with git and thought that would be a neat feature, e.g. for having version control on it. (And I happen to usually use git, so that would be a nice fit :))

**Comment by ThomasFeher** [comment]
See #139 for a previous discussion on that topic.

**Comment by Unip0rn** [comment]
Oh thanks! Guess I forgot to look at closed issues. Have a nice time then :)
