### ISSUE TITLE
:VimwikiGenerateTags can't generate correct link to non .md file.

### ISSUE THREAD

**Issue by ChenWeird** [vimwiki/vimwiki#792]
[The commit Allow markdown syntax to have tags at top of file](https://github.com/vimwiki/vimwiki/commit/b4e0f738a32e0dbfdad6c74e22721d1872932ef8) 

But there is an issue, when a tag included by a non .md file in the vimwiki folder, then `:VimwikiGenerateTags` can't generate correct link to this file.

For example:  tag ‘abc’  in the xyz.vim
`:VimwikiGenerateTags` would generate link to `xyz#abc`
but the correct link should be `xyz.vim#abc`

**Comment by ChenWeird** [comment]
Maybe retaining the file extension would resolves this problem.

**Comment by ranebrown** [comment]
In my test `:VimwikiRebuildTags` doesn't even create a tag in a file with `.vim` extension. What is the use case here? And what settings are you using to make it generate the tags?

**Comment by ChenWeird** [comment]
I use auto_tags and auto_generate_tags.

This is the GIF what I do, please check:

![VimwikiGenerateTags](https://s2.ax1x.com/2020/01/03/lUDjWn.gif)

**Comment by ChenWeird** [comment]
**How to open .vim page may make different:**

If open .vim page from a .md wiki page, then the .vim page's filetype is vimwiki. And auto_tags and auto_generate_tags work.

If open .vim page directly such as `:find wiki2md.vim`, then the .vim page's filetype is vim. And auto_tags and auto_generate_tags can't work.
