### ISSUE TITLE
Pages created from a diary page aren't diary pages

### ISSUE THREAD

**Issue by jean** [vimwiki/vimwiki#793]
With default `diary_rel_path`, create a new page in a diary page. I.e type `TestPage` in `diary/2020-01-02.wiki`, and press enter on it twice. 

- This results in `diary/TestPage.wiki` being created. **This is wrong**: `TestPage` is not a diary page.

----

Syntax: default.

## From `.vimrc`:

```vim
let wiki = {}
let wiki.name = 'wiki'
let wiki.path = '~/wiki/'
let wiki.nested_syntaxes = nested_syntaxes
let wiki.auto_tags = 1
```

## The output of `:VimwikiShowVersion`.

Branch: dev
Revision: 5cdeb9a
Date: 2020-01-01 10:58:56 -0700

**Comment by ranebrown** [comment]
If you are creating the link from an existing diary page the newly created page will be relative to that page i.e. in the diary folder. If you want it somewhere else just edit the relative path prior to pressing enter the second time.

**Comment by jean** [comment]
Fair enough :ok_hand:
