### ISSUE TITLE
vimwiki_auto_chdir not working

### ISSUE THREAD

**Issue by carugnom** [vimwiki/vimwiki#802]
Hi there
I'm setting this in my vimrc
```
let g:vimwiki_list = [{'path': '~/vimwiki', 'syntax': 'default', 'ext': '.wiki'}]
let g:vimwiki_global_ext = 0
let g:vimwiki_dir_link = 'index'
let g:vimwiki_folding = 'expr:quick'
let g:vimwiki_auto_chdir = 1
```
The output of `:VimwikiShowVersion` is `2.4.1`

I enter vimwiki (,ww) and I follow a linked subdir like [[comp/]] where I have wiki notes.
Then I type `:pwd`
The current dir is not `~/vimwiki/comp` (as I expect) but just `~/vimwiki`
Looks like `vimwiki_auto_chdir` has no effect

**Comment by ChenWeird** [comment]
`vimwiki_auto_chdir` always cd to current vimwiki path of `g:vimwiki_list`

You can use: `:cd %:p:h`

**Comment by carugnom** [comment]
> `vimwiki_auto_chdir` always cd to current vimwiki path of `g:vimwiki_list`

Well, according to the documentation that's not the behavior
```
*g:vimwiki_auto_chdir*

When set to 1, enables auto-cd feature.  Whenever Vimwiki page is opened,
Vimwiki performs an |:lcd| to the Vimwiki folder to where the page belongs.
```

**Comment by ranebrown** [comment]
> Vimwiki folder to where the page belongs.

I think this means the root wiki folder set in `g:vimwiki_list` as mentioned by @ChenWeird. The call is `exe 'lcd' vimwiki#vars#get_wikilocal('path')` which confirms that behavior.

The documentation could more clearly state the behavior.

**Comment by carugnom** [comment]
Well, I still think it is an issue.
From its name (auto_chdir) the expected behavior is vimwiki to change into the directory of the current file, so the use can search from that directory, for instance.
If that's not the intended behavior, then the command name and its documentation are the issues.

**Comment by hq6** [comment]
@carugnom You are welcome to update the documentation through a PR if you think there is more clear wording. 
I suspect changing the command name may break other people's workflows, but more clear documentation is always a plus.

**Comment by tinmarino** [comment]
c6564119b06. Feel free to make a PR if improvable.

The original help seemed clear to me (wiki path Vs file path). But now a quadruple explication on __root__  __Vimwiki__ __folder__ of the file __wiki__ seems different from __file path__
