### ISSUE TITLE
VimwikiGet does not work anymore since update

### ISSUE THREAD

**Issue by mowgli** [vimwiki/vimwiki#804]
Prior to submitting a new issue make sure to complete these steps:

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
- [ ] The `dev` branch contains fixes that may not have been merged to `master` yet.
- [ ] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [ ] Include the output of `:VimwikiShowVersion`.

Since I updated from version 2.0.1 to the most current (master branch or even dev branch), my git autocommit does not work anymore.
```vim
augroup vimwiki
  au BufWritePost <buffer>
    \ execute 'silent ! cd ' . shellescape(expand(VimwikiGet('path')), 1) . '; [ -d .git ] || exit 0; export GIT_DIR=' . shellescape(expand(VimwikiGet('path')) . '/.git', 1) . '; git add ' . shellescape('%') . '; git commit -m ' . shellescape('Autocommit %:t') . ' ' . shellescape('%') . ' >/dev/null || :'
augroup END
```

I get the error
```
Fehler beim Ausführen von "BufWritePost Autokommandos für "<buffer=2>"":
E117: Unbekannte Funktion: VimwikiGet
E116: Ungültige Argumente für die Funktion expand(VimwikiGet('path')), 1) . '; [ -d .git ] || exit 0; export GIT
_DIR=' . shellescape(expand(VimwikiGet('path')) . '/.git', 1) . '; git add ' . shellescape('%') . '; git commit 
-m ' . shellescape('Autocommit %:t') . ' ' . shellescape('%') . ' >/dev/null || :'
E116: Ungültige Argumente für die Funktion shellescape(expand(VimwikiGet('path')), 1) . '; [ -d .git ] || exit 0
; export GIT_DIR=' . shellescape(expand(VimwikiGet('path')) . '/.git', 1) . '; git add ' . shellescape('%') . ';
 git commit -m ' . shellescape('Autocommit %:t') . ' ' . shellescape('%') . ' >/dev/null || :'
```

As I have multiple wikis, the hardcoded approach for path does not work.

**Comment by ranebrown** [comment]
There has been some refactoring of how the internal variables are handled. You should be able to achieve the same thing using `vimwiki#vars#get_wikilocal('path')`

**Comment by ranebrown** [comment]
@mowgli did using the new function work?

**Comment by mowgli** [comment]
Sure, that work, thanks.

Sorry for answering that late. I am somewhat busy currently.

**Comment by mowgli** [comment]
Short note, could you please document the new behavior in the otherwise great help page?
