### ISSUE TITLE
Vimwiki slow markdown table editing

### ISSUE THREAD

**Issue by electronblue** [vimwiki/vimwiki#809]
Vimwiki Version: Stable 2.4.1

Even though the table has only 200 rows and 3 columns, editing is it really slow (both switching between modes as well as tabbing through the fields, particularly creating new rows). I don't think this should be the case when the file has only 200 lines, maybe with 200000 but not with 200. I profiled the problem, here is the output. 

https://pastebin.com/raw/DHJkFuJ6

Generally, it seems to be due to vimwiki#tbl#format taking up a heap of time.

**Comment by ranebrown** [comment]
Give the `dev` branch a try. There were a couple of PRs (#658, #47) that made some updates to tables to speed things up. They will be part of the next release, hopefully around March timeframe.
