### ISSUE TITLE
slow to open links

### ISSUE THREAD

**Issue by rpietro** [vimwiki/vimwiki#812]
I have the dev branch installed through:

Plug 'https://github.com/vimwiki/vimwiki', { 'branch': 'dev' }
set nocompatible
filetype plugin on
syntax on
let wiki = {}
let g:vimwikidir = $HOME . "/Dropbox/vimwiki"
let wiki.path = g:vimwikidir
let g:vimwiki_list=[wiki]
let g:vimwiki_list = [{
  \ 'path': '~/misc/vimwiki/',
  \ 'path_html': '~/web/otherware.org/vimwiki/',
  \ 'template_path': '~/misc/vimwiki/',
  \ 'template_default': 'default',
  \ 'template_ext': '.tpl.html',
  \ 'css_name': 'style.css',
  \ 'auto_export': 1}]

I am using the .wiki syntax 

This issue just got started on a new laptop, but using the exact same setting I am using on another laptop where the issue is not present. To reproduce the issue, I just try to open a link placing the cursor on top of the link and hitting enter. It takes a few seconds before the link is opened. Everything else looks normal.

Version is 2.4.1

**Comment by ranebrown** [comment]
My first guess is it is related to using Dropbox. Your settings also look a bit muddled, you should try to clean those up and make sure you aren't overwriting you desired settings.

You can do it like this:
```vim
let wiki = {}
let wiki.path = 'your path'
let wiki.template_path = 'your path'
let wiki.auto_export = 1
" more settings

" another wiki if you want
let wiki2 = {}
let wiki2.path = 'path'
let wiki2.ext = 'md'
" other settings

let g:vimwiki_list = [wiki, wiki2]
```

Or like this:
```vim
let g:vimwiki_list = [
    \   {
    \     'path': 'your path for first wiki',
    \     'template_path': 'your path',
    \     'auto_export': 1,
    \   },
    \   {
    \     'path': = 'path for second wiki',
    \     'ext': 'md',
    \   },
    \ ]
```

**Comment by rpietro** [comment]
@ranebrown thanks, I tried both. Unfortunately, none worked. Again, I have another laptop, nearly identical, under the same wifi connection and setup, where there is no delay.

**Comment by rpietro** [comment]
found the problem in my init:

```
" repeat macro with space bar
:nnoremap <CR><Space> @q

```
although I still don't understand the reason why this line  was causing the delay
