### ISSUE TITLE
Question: How do I add modline to VimWiki text?

### ISSUE THREAD

**Issue by justrajdeep** [vimwiki/vimwiki#814]
Hi 

How can i add `modline` to vimwiki text?

I see the following for google search but does not work for vimwiki

[[modeline]: # ( vim: set fenc=utf-8 spell spl=en: )](https://davidjb.com/blog/2016/10/adding-a-vim-modeline-in-a-markdown-document/)

**Comment by ranebrown** [comment]
Try `%%` or `<!-- modeline here -->`. I think those are markdown comment characters that might work.

**Comment by justrajdeep** [comment]
Perfect ... used `%%` and it worked.
