### ISSUE TITLE
Add highlighting for @user in todo-lists

### ISSUE THREAD

**Issue by jrop** [vimwiki/vimwiki#815]
I just wanted to start discussion around a potential feature addition: it would be nice to have syntax highlighting in TODO-lists for user assignment.  Say I have the following list:

```md
- [ ] A task for @john
- [ ] A task for @jane
```

Currently, the `- [ ]` is highlighted, but the `@john` and `@jane` snippets are the same color as plain text.

(Obligatory: Thank you for developing such a great VIM plugin!)

**Comment by ranebrown** [comment]
Related to #309

**Comment by jrop** [comment]
Ah.  No need to duplicate.  I'll close this issue and subscribe to that one.
