### ISSUE TITLE
is it possible to change the way vim-wiki names linked files?

### ISSUE THREAD

**Issue by agaAdams** [vimwiki/vimwiki#821]
The file name created via :VimwikiFollowLink is usually equal to the word under the cursor or the word(s) currently marked.
I would like to change the name of the target wiki page to sth like: "%Y%m%d%H%M%S.md"
Is this possible?

**Comment by ranebrown** [comment]
Maybe try something like [Ultisnips](https://github.com/SirVer/ultisnips)?
