### ISSUE TITLE
Disable need for two spaces for linebreak in vimwiki

### ISSUE THREAD

**Issue by electronblue** [vimwiki/vimwiki#822]
Version: 2.4.1

Vimwiki requires you to insert two spaces at the end of each line if you want it to be interpreted as a break for HTML conversion. Is it possible to deactivate this feature so that no extra spaces at the end of each line are needed?

**Comment by ranebrown** [comment]
Without using an explicit indicator (spaces, blank line, `<br>`) people can't limit their line length with something like `textwidth` and still get the correct html output.

**Comment by brennen** [comment]
@electronblue see `:help g:vimwiki_text_ignore_newline`.  I believe this should do what you want.
