### ISSUE TITLE
<TAB> conflict issue in insert mode

### ISSUE THREAD

**Issue by BSDxxxx** [vimwiki/vimwiki#827]
.vimrc:
```
let g:vimwiki_list = [{
  \ 'path': 'F:\ProgramFiles\GitHub\Notes',
  \ 'syntax': 'markdown',
  \ 'ext':'.md',
  \}]

let g:vimwiki_CJK_length = 1

let g:taskwiki_sort_orders={"C": "pri-"}
let g:taskwiki_syntax = 'markdown'
let g:taskwiki_markdown_syntax='markdown'
let g:taskwiki_markup_syntax='markdown'
```
`:VimwikiShowVersion`: Stable version:'2.4.1'

I wish ```<TAB>``` do auto-complete in markdown files in insert mode (just like it worked on other filetypes), but vimwiki somehow affected it.

![123](https://user-images.githubusercontent.com/59258592/76487172-8d61ff00-645c-11ea-9ce2-51cc43bb75dc.gif)

If I Inactivate vimwiki plug, the auto-complete function will work fine.

So, how do I get the auto-complete function with the vimwiki  plugin activated?

**Comment by yaohunzhanyue** [comment]
#845
