### ISSUE TITLE
Changing .md filetype to vimwiki cause other markdown plugin not working.

### ISSUE THREAD

**Issue by BSDxxxx** [vimwiki/vimwiki#830]
.vimrc:
```
let g:vimwiki_list = [{
  \ 'path': 'F:\ProgramFiles\GitHub\Notes',
  \ 'syntax': 'markdown',
  \ 'ext':'.md',
  \}]

let g:vimwiki_CJK_length = 1

let g:taskwiki_sort_orders={"C": "pri-"}
let g:taskwiki_syntax = 'markdown'
let g:taskwiki_markdown_syntax='markdown'
let g:taskwiki_markup_syntax='markdown'
```
`:VimwikiShowVersion`: Stable version:'2.4.1'

How to make markdown plugin (such as [masukomi/vim-markdown-folding](https://github.com/masukomi/vim-markdown-folding)) works in vimwiki filetype?

**Comment by dathinaios** [comment]
Did you find a solution for this? I am having issues with folding when using the `vim-markdown` plugin.

**Comment by dathinaios** [comment]
Did you need to do anything to enable it? Cause in my case there are no folds.. 🤔

**Comment by yaohunzhanyue** [comment]
@dathinaios I suggest you use vimwiki dev branch, and set filetype to `markdown.vimwiki`. Then follow vimwiki help doc set custom folding syntax.
Then you can load other markdown folding plugin. I'm using vim-pandoc by the way.

**Comment by dathinaios** [comment]
@yaohunzhanyue Thank you for your answer 🙂

I followed the instructions but it is not working and I am not even sure what I am trying to achieve. Why am I using `pandoc`? 🤔

Here is what I have in my `vimrc`:

```
" Markdown {{{
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
"}}}
" Pandoc{{{
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
"}}}
" Vimwiki{{{
Plug 'vimwiki/vimwiki', { 'branch': 'dev' }
" Customisation
let g:vimwiki_list = [{'path': '~/Dropbox/Apps/notes_/vimwiki/',
      \ 'syntax': 'markdown', 'ext': '.md'}]
let g:vimwiki_folding = '' "list, expr
let g:vimwiki_filetypes = ['markdown.vimwiki']
let g:vimwiki_map_prefix = '<Leader>W'
nmap <Leader>WW <Plug>VimwikiIndex
"}}}
```
I had it working with the built in folding of `vimwiki` but the folding behaviour was really hit and miss so I am looking for an alternative.

**Comment by yaohunzhanyue** [comment]
@dathinaios I use pandoc for it's folding function. Theoretically, You can replace that to any other folding plugin you want (maybe you want vim-markdown).
My vimrc:
```
Plug 'vimwiki/vimwiki', {'branch': 'dev'}
let g:vimwiki_list = [{
	\ 'path': 'your path',
	\ 'syntax': 'markdown',
	\ 'ext':'.md',
	\},
let g:vimwiki_filetypes        = ['markdown', 'pandoc']
let g:vimwiki_folding          = 'custom' 
function! VimwikiFoldLevelCustom(lnum)
let pounds = strlen(matchstr(getline(a:lnum), '^#\+'))
if (pounds)
  return '>' . pounds  " start a fold level
endif
return '=' " return previous fold level
endfunction

augroup VimrcAuGroup
autocmd!
autocmd FileType vimwiki setlocal foldmethod=expr |
  \ setlocal foldenable | set foldexpr=VimwikiFoldLevelCustom(v:lnum)
augroup END


Plug 'vim-pandoc/vim-pandoc'
let g:pandoc#toc#position                               = 'left'
let g:pandoc#formatting#textwidth                       = 0 "default 79
let g:pandoc#formatting#mode                            = 's'
let g:pandoc#formatting#smart_autoformat_on_cursormoved = 1
let g:pandoc#folding#level                              = 9
let g:pandoc#folding#fdc                                = 0
let g:pandoc#folding#mode                               = 'relative'
let g:pandoc#filetypes#handled                          = ['markdown','pandoc']
let g:pandoc#filetypes#pandoc_markdown                  = 1
let g:pandoc#modules#disabled                           = ['spell']
let g:pandoc#modules#enable                             = ['folding', 'command']
let g:pandoc#completion#bib#mode                        = 'citeproc'
"let g:pandoc#syntax#colorcolumn                        = 1 "causes display bug
let g:pandoc#toc#close_after_navigating    
```

**Comment by dathinaios** [comment]
Thank you @yaohunzhanyue 🙂

It is almost working! The folding etc. is working fine (with even added fancy formatting from `pandoc`). Unfortunately the link display functionality of `vimwiki` is gone. 

So I get this:

![1](https://user-images.githubusercontent.com/481589/78590354-9e264a80-7839-11ea-9433-e5cbb9373ce5.png)

Instead of the usual:

![2](https://user-images.githubusercontent.com/481589/78590357-9f577780-7839-11ea-8e29-00cde3f22b9e.png)

Is this happening on your side?

**Comment by dathinaios** [comment]
Ah nevermind. It works fine as long as I remove the `vim-pandoc-syntax` in this line:

```vim
Plug 'vim-pandoc/vim-pandoc-syntax' 
```
Shame cause I really liked the formatting from pandoc... But that's good enough for now. Thanks! 👍

**Comment by yaohunzhanyue** [comment]
@dathinaios Thanks for the vim-pandoc-syntax tip, really useful.
