### ISSUE TITLE
Spaces in filenames trip up VimwikiRebuildTags command

### ISSUE THREAD

**Issue by waxlamp** [vimwiki/vimwiki#832]
Default syntax. No special options set. `:VimwikiShowVersion` says "Unknown version"; I'm building mine off of the `dev` branch as suggested in the docs.

I have many wiki files with spaces in the names. When I run `:VimwikiRebuildTags` I get an error `Can't open file /home/roni/vimwiki/personal/A` (referring to the file `A Wizard of Earthsea, by Ursula Le Guin.wiki`).

I believe I could fix this problem partway by setting `links_space_char` in the options to an underscore or hyphen. But that brings up two follow-on questions:
- what can I do about batch converting my existing wiki files to the new filename format?
- will that scheme mean that my in-text hyperlinks all have underscores/hyphens in them?

And I suppose a grand question encompassing the others, in light of the fact that `links_space_char` is a single space character by default:
- in the default config, how should I be using the `VimwikiRebuildTags` and related commands without triggering the space-in-filename error?

Thanks as always for bringing vimwiki to us. It's a wonderful piece of software.

**Comment by tinmarino** [comment]
Closing <= Inactive question

Apparently you can't. Anyway avoid spaces for path or url.
