### ISSUE TITLE
Default Vim packages install does not deploy the documentation

### ISSUE THREAD

**Issue by ubitux** [vimwiki/vimwiki#836]
The documentation states the following for a "Vim packages" install:

```
git clone https://github.com/vimwiki/vimwiki.git ~/.vim/pack/plugins/start/vimwiki
```

While this does actually work to enable VimWiki, `:help vimwiki` and similar commands do not work: `E149: Sorry, no help for vimwiki`

This is specific to the "Vim packages" install: installing VimWiki through `vim-plug` does enable access to the doc.

`~/.vimrc`:
```
set nocompatible
filetype plugin on
syntax on
```

`:VimwikiShowVersion`:
```
Branch: dev
Revision: 75c557b
Date: 2020-01-08 06:03:40 -0700
```

The issue is also reproducible with `master`.

Vim version: `8.2.343`

By the way, the equivalent for `neovim` does not seem to work at all (the whole thing is not installed): `git clone https://github.com/vimwiki/vimwiki.git ~/.local/share/nvim/site/pack/vimwiki/start`. Again, on the other hand, `vim-plug` works fine. This may belong in another issue, but I'm mentioning it since it may be related somehow.

**Comment by Andreilys** [comment]
+1, I have the same issue although my vim version is 

> 8.0.1283

**Comment by ranebrown** [comment]
See `:h helptags`. Most third party plugin managers run that automatically but I don't think the built in vim packages does.

**Comment by ranebrown** [comment]
I added a note to the readme. Reopen or comment if there is something else going on.

**Comment by ubitux** [comment]
Why not document to execute something like `vim -c 'helptags ~/.vim/pack/plugins/start/vimwiki/doc' -c quit` (not sure if there is something simpler) since the documentation already hardcode that pack path?

The proposed patch is a bit like, "You did half the installation, now here is a doc you need to figure out the rest by yourself", while the command has nothing specific to the user setup.

**Comment by ranebrown** [comment]
Sure
