### ISSUE TITLE
AsciiDoc syntax support

### ISSUE THREAD

**Issue by hulmakerik** [vimwiki/vimwiki#839]
VimWiki currently ships with 3 syntaxes: VimWiki, Markdown, and MediaWiki. Would it be possible to add an AsciiDoc (adoc) support?

**Comment by ranebrown** [comment]
I would say it is highly unlikely unless someone like yourself adds and maintains it.

**Comment by hulmakerik** [comment]
Ok, let's hope some hero appears. But still, I very much appreciate your work.

**Comment by ratfactor** [comment]
@hulmakerik - I started adding AsciiDoc support, but it's a pretty big effort due to the way the syntax is so integral to the way VimWiki works.

I'm hesitant to point anyone to this (particularly on VimWiki's own issue tracker), but I did take the plunge and write my own AsciiDoc wiki plugin for home use (which I use daily): https://github.com/ratfactor/vviki

The above is obviously nowhere near as feature complete or mature as VimWiki (which I still use daily at work and have NO intention of switching).  In fact, I'd like to contribute more to VimWiki when I get another block of time!  The VimWiki team is doing an amazing job of keeping the development going.

**Comment by hulmakerik** [comment]
Oh cool! I will sure check it out! This small thing I wanted, thank you :grin:

**Comment by benibilme** [comment]
Hello,
I really would like to use asciidoc, I keep my personal notes in asciidoc. I write in vim. Can vimwiki use an external helper such as asciidoctor..It is very mature product. Many static site generators are using it. It will be tremendeus effort to implemet for vim viki, but external tool may help if possible..

**Comment by ratfactor** [comment]
> Can vimwiki use an external helper such as asciidoctor.

The problem isn't in the exporting from AsciiDoc to HTML or other formats (which is what Asciidoctor provides), it's the internal parsing and detection of the wiki syntax within VimWiki.  There is a lot of vimscript in the plugin that does nothing but handle the chosen wiki syntax.  Sadly, there is really no way to get around this.

**Comment by AlexCzar** [comment]
So, I'm a big fan of Asciidoc[tor] and use it for all my writing. Recently started using vim more and discovered vimwiki, I love it but would love it even more if it supported Asciidoc. I'm willing to try to contribute the support. Unfortunately, I have zero experience developing plugins for vim at this point, so pardon the newbie questions.
What needs to be done?
So far I did a little bit of investigating and see that I'll need to create and supply a syntax file, similar to
`syntax/vimwiki_markdown.vim `.
I would also need to add some tests.
What I haven't yet discovered is:
* How the 2HTML conversion is handled? I imagine there's an extension point somewhere where can I specify how custom syntax can be converted to HTML.
* Is there something else, or will the rest "just work", given the custom syntax file and conversion is implemented?

**Comment by ratfactor** [comment]
@AlexCzar I'll try to answer as best I can:

For a general understanding of how Vim plugins are structured, I _highly_ recommend going through https://learnvimscriptthehardway.stevelosh.com/

It takes you from the basics to actually making a tiny plugin.  I reference it so much, I ended up buying the hardcover print-on-demand book.

Yeah, I think the Markdown syntax file(s) would be a good place to start for adding AsciiDoc syntax needed - Vim itself already comes with AsciiDoc highlighting, as you know, so it might just be a question of adding the "conceal" for links and that sort of thing. You can see how I did this in my own plugin here (arguably, it was a bit naughty putting `syntax` statements in my main plugin file, but I'm happy with the result):

https://github.com/ratfactor/vviki/blob/master/plugin/vviki.vim#L256

Other things are: testing with the Vader test library (search for "markdown" and/or "custom" in the `test/` dir to see what might be needed) and updating the help file, emulating what exists for markdown. The biggest initial hurdle for me was running Docker for the test Vim instances, but as I recall, that was actually pretty painless.

The HTML conversion itself would be the easy part. Here's the script for Markdown: `vimwiki/autoload/vimwiki/customwiki2html.sh`

As you can see, it's just executing another external program. AsciiDoc would call `asciidoc` (Python) or `asciidoctor` (Ruby) instead.

The 2HTML commands are setup here: `vimwiki/autoload/vimwiki/html.vim`:

```
function! s:use_custom_wiki2html() abort
  ...
endfunction

function! vimwiki#html#CustomWiki2HTML(path, wikifile, force) abort
  ...
endfunction

function! s:convert_file(path_html, wikifile) abort
  ...
  if s:use_custom_wiki2html()
    let force = 1
    call vimwiki#html#CustomWiki2HTML(path_html, wikifile, force)
    let done = 1
  endif
  ...
endfunction
```

Clearly Vimwiki has grown organically to support Markdown.  It seems to me that ideally, the "custom" wording would go away and be replaced with "markdown", "asciidoc", etc.  If you get _that_ far, you'll probably be in a better place than I to determine how to cleanly support multiple syntaxes. 😅

**Comment by AlexCzar** [comment]
Thanks, this all looks very useful for the start.
I'll see if it goes anywhere.

**Comment by tinmarino** [comment]
@AlexCzar that is a nice initiative. We will accept the PR is if it passes the current tests. Estimated time: 10..15h but very instructive, syntax is an interesting topic an Vimscript has a nice interface, separing syntax and highlight.

It may be easier than it appears, I agree with @ratfactor that the html convertion is for external tools like Pandoc.

For the Vim(wiki) specific stuff, (in autoload/vimwiki), first look at vars.vim which parse user variable like the syntax (add yours) and define some internal regex for links and header.
The the syntax/vimwiki_asciddoc.vim will be loeaded for asciidoc syntax, you may inspire ou even source the `$RUNTIME/syntax/ascidooc` from there and try to give them the same highlight names like `VimwikiHeader2`

Baby steps and commit every time you got something working, if you can add test it will help you during dev and it will maintain alone.

**Comment by AlexCzar** [comment]
Thanks for the great advice, currently I'm following the suggested vimscript book to learn how stuff works and how to make new stuff, at some point I'll start the actual development, just don't expect results very soon, amount I can dedicate to this is very limited at the moment.
