### ISSUE TITLE
Please support another standard markdown h1 syntax for diary generate links

### ISSUE THREAD

**Issue by yaohunzhanyue** [vimwiki/vimwiki#841]
vimrc:
``` 
 'syntax': 'markdown',
  'ext':'.md',
```
example diary file 2020-03-25.md:
```
2020-03-25
==========

## contents
```
expect diary generate links:
```
# Diary

## 2020

### March
    * [2020-03-25](2020-03-25)
```
actually get these:
```
# Diary

## 2020

### March
    * [contents](2020-03-25)
```

**Comment by ranebrown** [comment]
Do you see the same thing on the `dev` branch? There is also an option on the `dev` branch `diary_caption_level` that controls how the headers are generated.

**Comment by yaohunzhanyue** [comment]
@ranebrown The problem is that vimwiki can't detect `===============` as caption, it will detect '#' symbol, but in markdown syntax, these two are the same.

**Comment by ranebrown** [comment]
I see. This is a duplicate of #209. Sorry to say it isn't really a priority though.
