### ISSUE TITLE
Duplicate toc of contents with markdown and prettier

### ISSUE THREAD

**Issue by chinwobble** [vimwiki/vimwiki#844]
I described the issue in this issues.

https://github.com/prettier/prettier/issues/7909

Solution:
Make the toc already exists smarter.

**Comment by chinwobble** [comment]
For prettier, it wants the blank line after the headings.

However for vimwiki, it expects no blank line after the `#Contents` heading. 

This causes a bug where duplicate table of contents are created.

If my document looks like this. I don't want vimwiki to create a duplicate. I want it to update the existing contents section.

```md
# contents 

- [Section 1](#Section 1)

## Section 1
## Section 2
```

**Comment by ranebrown** [comment]
I think this behavior has changed on the dev branch. Have you tried that?

**Comment by chinwobble** [comment]
yea I tried on dev branch yesterday and still got this issue.

**Comment by ranebrown** [comment]
Using the latest dev branch and a minimal vimrc I get the following output from `VimwikiTOC` which includes a blank line after `Contents`

```
# Contents

- [Heading 1](#Heading 1)
        - [Heading 2](#Heading 1#Heading 2)
                - [Heading 3](#Heading 1#Heading 2#Heading 3)
- [Another Heading 1](#Another Heading 1)
        - [Another Heading 2](#Another Heading 1#Another Heading 2)
```

**Comment by chinwobble** [comment]
I have ale and prettier installed and I get issues.
Here's my vimrc
https://github.com/chinwobble/dotfiles/blob/master/.vimrc

**Comment by tinmarino** [comment]
Hi @chinwobble. Thanks for the issue.
After a look at the code that this feature (the new line) is deeply hard-coded in : 
```
function! vimwiki#base#update_listing_in_buffer(Generator, start_header,
      \ content_regex, default_lnum, header_level, create) abort
```

So we will __not change that code nor add an option__ to customize this: it would change too much.



But __you can customize:__
I advise you to add the following to your __vimrc:__

```vim
command! -bar ZhelperTOC VimwikiTOC
command! ChinTOC ZhelperTOC | g/^# contents/+1d  
```
And then use your custom command `ChinTOC`.


PS : I am closing the issue to help developer know what they should code new but feel free to answer here.
