### ISSUE TITLE
Wrap bug

### ISSUE THREAD

**Issue by yaohunzhanyue** [vimwiki/vimwiki#846]
Branch: dev  
Revision: 78a41b7  
Date: 2020-04-03 13:31:36 -0600  
syntax: markdown

---

set nowrap in vimrc --> open vimwiki file --> file is wrapped --> exec ':source $MYVIMRC' --> nowrap

**Comment by ranebrown** [comment]
Have you tried this with a minimal vimrc as described [here](https://vimwiki.github.io/vimwikiwiki/Troubleshooting.html)?

**Comment by yaohunzhanyue** [comment]
@ranebrown You are right, this is not vimwiki's problem.
