### ISSUE TITLE
What's the best way to export releated markdown/wiki files?

### ISSUE THREAD

**Issue by BSDxxxx** [vimwiki/vimwiki#851]
Is there a convient way to exort notes under these circumstance?
1. notes tagged with `tagA`
2. notes under header `headA`

**Comment by tinmarino** [comment]
Not really: tags are used to generate links and not entire site.
The idea would be to get a path list and copy them.
Have a look at https://github.com/vimwiki/vimwiki/blob/dev/autoload/vimwiki/tags.vim
