### ISSUE TITLE
Provide customization to remove keybindings

### ISSUE THREAD

**Issue by phaazon** [vimwiki/vimwiki#852]
Hello,

Is it possible to disable some keybindings? The `<leader>ww` clashes with my `<leader>w` (Easymotion word), and then make my keybinding slow.

**Comment by BSDxxxx** [comment]
Try the dev branch , there's a variable for this:
```
Plug 'vimwiki/vimwiki', {'branch': 'dev'}

let g:vimwiki_key_mappings =
\ {
\   'all_maps': 1,
\   'global': 1,
\   'headers': 1,
\   'text_objs': 1,
\   'table_format': 1,
\   'table_mappings': 0,
\   'lists': 0,
\   'links': 1,
\   'html': 1,
\   'mouse': 0,
\ }
```

**Comment by phaazon** [comment]
Cool, thanks!

**Comment by phaazon** [comment]
Hm, looks like there’s some bugs… I want to disable the global mapping but I still want the local ones… No way to do that?

**Comment by BSDxxxx** [comment]
@phaazon What’s “the local ones” mean? Specify your request pls.

**Comment by phaazon** [comment]
For instance, `+`, `h`, etc. while in a `vimwiki` buffer.

**Comment by tinmarino** [comment]
Have you tried putting `0` to `all_maps` and `global` ? 

```vim
let g:vimwiki_key_mappings =
\ {
\   'all_maps': 0,
\   'global': 0,
\   'headers': 1,
\   'text_objs': 1,
\   'table_format': 1,
\   'table_mappings': 1,
\   'lists': 1,
\   'links': 1,
\   'html': 1,
\   'mouse': 0,
\ }
```

**Comment by phaazon** [comment]
Yeah, it seems to disable the markup keybindings, and looking at the `:help`, it seems to be legit. I think those keybindings are actually in `global`. :(

**Comment by tinmarino** [comment]
I think you only want to change `g:vimwiki_map_prefix`:
* `:h g:vimwiki_map_prefix`
* `:let g:vimwiki_map_prefix = ,k`

But if you want to take the long path of customization (Which I don't recommend):

* `+` is defined in links `h` in html. All in `ftplugin/vimwiki.vim`

```vim
if str2nr(vimwiki#vars#get_global('key_mappings').links)
  call vimwiki#u#map_key('n', '+', '<Plug>VimwikiNormalizeLink')
if str2nr(vimwiki#vars#get_global('key_mappings').html)
  call vimwiki#u#map_key('n', vimwiki#vars#get_global('map_prefix').'h', '<Plug>Vimwiki2HTML')
```

* `<leader>ww` in global in `plugin/vimwiki.vim`:

```vim
if str2nr(vimwiki#vars#get_global('key_mappings').global)
  call vimwiki#u#map_key('n', s:map_prefix . 'w', '<Plug>VimwikiIndex', 2)
```

PS: Feel free to comment/reopen issue
