### ISSUE TITLE
Markdown links can't be concealed

### ISSUE THREAD

**Issue by BSDxxxx** [vimwiki/vimwiki#853]
vimwiki version: 
Branch: dev
Revision: 78a41b7
Date: 2020-04-03 13:31:36 -0600
syntax: markdown
![image](https://user-images.githubusercontent.com/59258592/79059610-83772a00-7cae-11ea-8cb6-f3aa61e6a58b.png)

**Comment by tinmarino** [comment]
It is concealed for me. Sure you don't have a `modeline` in your file and your `:set filetype=vimwiki` ?

**Comment by BSDxxxx** [comment]
@tinmarino You are right. This is caused by the following settings in my vimrc:
```
"set vimwiki filetype to vimwiki.markdown.pandoc
let g:vimwiki_filetypes = ['markdown', 'pandoc']
```
The markdown syntax conceal should be handled by pandoc.vim plugin rather than vimwiki.
