### ISSUE TITLE
CDN MathJax isn't working on HTML pages

### ISSUE THREAD

**Issue by shihabdider** [vimwiki/vimwiki#856]
Can't seem to get MathJax to work on my vimwiki installation (I'm using the online version of MathJax on CDN) 

Here's my default.html:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
        <title>%title%</title>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/config/TeX-AMS-MML_HTMLorMML.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=%encoding%">
</head>
<body>
    %content%
</body>
</html>

```

But the output is not rendered: `$\frac {1} {1 + \alpha} $` shows up as `\(\frac {1} {1 + \alpha} \)`

**Comment by kaphula** [comment]
Have you tried different version [like this one](https://docs.mathjax.org/en/latest/web/start.html):
```
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>
```

**Comment by mgarort** [comment]
Hi @shihabdider 

I have never used the online version, but have you considered running MathJax locally? It's super simple. You just need to clone the MathJax repository:

`git clone https://github.com/mathjax/MathJax.git MathJax`

and then add the following within the `<body>  </body>` section of your HTML template/file.

`<script type="text/javascript" src="/path/to/repos/folder/mathjax/tex-chtml.js?config=TeX-AMS-MML_HTMLorMML"></script>`

This works great for me.

**Comment by shihabdider** [comment]
Adjusting the default.html didn't help, so I took a peek into the wiki-generated HTML file using chrome's developer tools. Turns out that the HTML files weren't being generated from the template because of a naming issue (`default.html**~** -> default.html` did the trick).
