### ISSUE TITLE
[Question] Prevent link conceal in insert mode, while concealing in normal mode?

### ISSUE THREAD

**Issue by Datamance** [vimwiki/vimwiki#858]
Hi there,

This is a question and not so much a bug report (though... it could be depending on your answer...).

Right now, when I create links manually with this kind of syntax
`[[https://www.example.com/|The Link Text]]`
in insert mode, vimwiki starts trying to create the link "right away" and eats the special characters as I'm typing them; formatting the text as I go. 

This is not preferable behavior - first of all, I can't see what I've actually typed; secondly, the cursor jumps out as many columns as there are characters that I've typed, so that it's way off to the right even as characters are inserted back where the cursor _should_ be.

I would much prefer an insert mode that shows the "raw characters" as is - no formatting applied at all. When I go out of insert mode, _that's_ when I want to see the (very pretty!) formatting applied.

I can't imagine that this sort of awkward, jumpy autoformatting behavior in Insert Mode is hardcoded. What option am I missing? Or, worse, is this actually a bug?

**Comment by Datamance** [comment]
Update: After [combing through the docs](https://github.com/vimwiki/vimwiki/blob/master/doc/vimwiki.txt) I've found that the word I was looking for was "conceal", and I indeed found the global flag responsible for link concealment.

I'm rather new to vim - is this something I can hack on top of the plugin with vimscript, or would I need to change how the plugin itself works to get the desired behavior?

**Comment by Datamance** [comment]
Nevermind, I figured out what was going on - it turns out the indentLine plugin breaks vimwiki's intended behavior here by forcing `concealcursor=inc`; the workaround is noted [here](https://github.com/plasticboy/vim-markdown/issues/395#issuecomment-436719952). Sad!

**Comment by tinmarino** [comment]
@Datamance did you fix it ?

**Comment by Datamance** [comment]
@tinmarino I didn't fix it so much as work around it, and then promptly abandoned vimwiki for joplin after encountering many frustrating issues like this.

**Comment by tinmarino** [comment]
>  abandoned vimwiki for joplin 

Pretty bad new.
__I don't advice you to use Vim__ over Emacs or Visual Studio code. But yes, __I advice you to have only one text editor__ for all the different languages (md, cpp, python). Joplin seems to treat only markdown.
You can try Emacs and orgmode the first and great. It may take years but at the end will pay.
