### ISSUE TITLE
Will the VimWiki Support Preview?

### ISSUE THREAD

**Issue by y1rah** [vimwiki/vimwiki#860]
Awesome work the vimwiki. While searching in doc, I found that vimwiki seems to lack a support of preview in pum (popup-menu).

Was this functionality an intentional action with design?

Or I really hope this feature lands.

**Comment by tinmarino** [comment]
Can you add:

1. An example screenshot
2. A typical use

I don't understand what is your idea. Are you kindly saying that `<C-X>O` is broken ?

> Was this functionality an intentional action with design?

I don't think so. The design is very old. Vimwiki seems to evolve with mutations.

**Comment by tinmarino** [comment]
Closed in favor of #36
With so little information, my guess is that the user want a preview window with the reduced buffer content like Visual Studio Code or many editor witch is exactly what this old issue is aksing.
