### ISSUE TITLE
RMarkdown files being treated as markdown even with `let g:vimwiki_global_ext = 0`

### ISSUE THREAD

**Issue by tallguyjenks** [vimwiki/vimwiki#862]
Prior to submitting a new issue make sure to complete these steps:

- [X] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [X] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [X] Include the output of `:VimwikiShowVersion`.

----

using markdown syntax

`:VimwikiShowVersion`.
Branch: dev
Revision: 6a0210c
Date: 2020-04-17 19:02:59 -0400

reproduce: make a .Rmd file anywhere on your system, and see if the vim wiki link jumping works

Detailed issue:
My neovim init.vim looks like this for vimwiki options:

```vim
"=================================="
"             VIM WIKI             "
"=================================="
    " ~~~~~ Ensure files are read as what I want in vimwiki:
        let g:vimwiki_global_ext = 0
        let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
        let g:vimwiki_root = '~/VimWiki'
        let g:vimwiki_listsyms = '✗○◐●✓'
        let g:vimwiki_list = [
            \{'path': '~/VimWiki', 'syntax': 'markdown', 'ext': '.md'},
            \{'path': '~/VimWiki/academia', 'syntax': 'markdown', 'ext':'.md'},
            \{'path': '~/VimWiki/academia/statistics', 'syntax': 'markdown', 'ext':'.md'},
            \{'path': '~/VimWiki/social', 'syntax': 'markdown', 'ext':'.md'},
            \{'path': '~/VimWiki/spirituality', 'syntax': 'markdown', 'ext':'.md'},
            \{'path': '~/VimWiki/tech', 'syntax': 'markdown', 'ext':'.md'},
            \{'path': '~/VimWiki/tech/linux', 'syntax': 'markdown', 'ext':'.md'},
            \{'path': '~/VimWiki/tech/css', 'syntax': 'markdown', 'ext':'.md'},
            \{'path': '~/VimWiki/tech/bash', 'syntax': 'markdown', 'ext':'.md'},
            \{'path': '~/VimWiki/tech/html', 'syntax': 'markdown', 'ext':'.md'},
            \{'path': '~/VimWiki/tech/latex', 'syntax': 'markdown', 'ext':'.md'},
            \{'path': '~/VimWiki/tech/r', 'syntax': 'markdown', 'ext':'.md'},
            \{'path': '~/VimWiki/tech/regex', 'syntax': 'markdown', 'ext':'.md'},
            \{'path': '~/VimWiki/tech/rust', 'syntax': 'markdown', 'ext':'.md'},
            \{'path': '~/VimWiki/tech/python', 'syntax': 'markdown', 'ext':'.md'}]
```

i am currently using [ultisnips](https://github.com/SirVer/ultisnips) and using tab for completion, but with vimwiki overriding the tab key for link jumping (i like the behavior and dont want to remap) it prevents me from using snippets in markdown files, this is fine for me specifically because everything i would do in markdown i can do in RMarkdown, but RMarkdown is being treated like a plain markdown file by vimwiki as well. despite the above configurations not sure if there's another option i've missed.

**Comment by ranebrown** [comment]
So if you open a file such as `file.rmd` the Vimwiki key mappings are still defined?

**Comment by tallguyjenks** [comment]
weird, now the Vimwiki key mapping are not working in the file and airline says "rmarkdown" instead of "Vimwiki" now, and im not sure what i changed, and still neither my `Rmd` or `rmarkdown`.snippets files work with the file type... and when im in insert mode it kicks me out to normal mode with this error displayed: 

![pic-selected-200424-1753-01](https://user-images.githubusercontent.com/29872822/80267158-8b42b100-8654-11ea-969f-abb48bd1cfcd.png)

**Comment by tinmarino** [comment]
```vim
let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
->
let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown', '.rmd', 'markdown'}
```

and craft a custom `ftplugin/vimwiki.vim` that source the plugin one plus the others related to rmd Vs md

**Comment by tallguyjenks** [comment]
@tinmarino thank you!
