### ISSUE TITLE
Markdown again: italic/bold issue

### ISSUE THREAD

**Issue by tetrodoxin** [vimwiki/vimwiki#863]
I'm facing again the problems of #318, nut I'm using version 2.4.1.

My config is like this:
```
let wiki_1 = {}
let wiki_1.path = '~/somwhere'
let wiki_1.syntax = 'markdown'
let wiki_1.ext = '.md'

let wiki_2 = {}
let wiki_2.path = '~/otherwhere'
let wiki_2.syntax = 'markdown'
let wiki_2.ext = '.md'

let g:vimwiki_list = [wiki_1, wiki_2]
let g:vimwiki_global_ext = 0
```

Now, when I try `:echo vimwiki#vars#get_wikilocal('syntax')` I correctly get `markdown'.

But `**bold text**` is displayed as **`*bold text*`**, same with underscore.
I expect the behavior as described in #318 but can't get it to work. Even trying to change `vimwiki/syntax/vimwiki_markdown.vim` with changes to variables like `s:markdown_syntax.char_bold` ha absolutely no effect.

What am I missing here?

**Comment by ranebrown** [comment]
This has been fixed on the dev branch which hasn't been merged to master yet (which is the 2.4.1 release currently). See #638
