### ISSUE TITLE
Navigation between markdown files not working

### ISSUE THREAD

**Issue by landge** [vimwiki/vimwiki#865]
Prior to submitting a new issue make sure to complete these steps:

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.

Syntax: markdown
init.vim settings:
```
let wiki_1 = {}
let wiki_1.path = '~/tech_memo'
let wiki_1.syntax = 'markdown'
let wiki_1.ext = '.md'

let wiki_2 = {}
let wiki_2.path = '~/technotes/'
let wiki_2.syntax = 'markdown'
let wiki_2.ext = '.md'
```
```
let  g:vimwiki_list = [wiki_1, wiki_2]
let  g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
let  g:vimwiki_table_mappings = 0
```
Problem:
It's not possible to navigate between markdown files. Commands like 
`:VimwikiGoBackLink` have no effect at all. The only link related command that works is 
`:VimwikiFollowLink`.
Any ideas what might cause this issue?

```
Branch: dev
Revision: 35af13c
Date: 2020-04-20 22:11:40 -0400
```

**Comment by landge** [comment]
After commenting out 

`" let g:vimwiki_ext2syntax` 

from init.vim everything worked fine again. Once it worked, it was even possible to set 

`let g:vimwiki_ext2syntax` 

again without any negative effects. So, the issue is solved, while I still don't understand why.

**Comment by ranebrown** [comment]
No sure. I'm going to close this for now but feel free to reopen if you can provide any more info.
