### ISSUE TITLE
No menu 'Vimwiki' triggered on setup_buffer_leave

### ISSUE THREAD

**Issue by teto** [vimwiki/vimwiki#867]
Prior to submitting a new issue make sure to complete these steps:

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
```
let wiki_1 = {}
let wiki_1.path = '~/Nextcloud2/perso/notes'
let wiki_1.index = 'main'
let wiki_1.ext = '.txt'
let g:vimwiki_list = [
  \ wiki_1, {'path': '~/dotfiles/tips'} 
  \ ]
```
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
I am using neovim master, whenever I switch buffer, I get an error about a missing `Vimwiki` menu.
```
|| Erreur détectée en traitant function <SNR>83_setup_buffer_leave :
|| ligne   10 :
|| E329: Aucun menu "Vimwiki"
|| Erreur détectée en traitant function <SNR>83_setup_buffer_enter[7]..<SNR>83_set_global_options :
|| ligne    5 :
|| E329: Aucun menu "Vimwiki"
|| Erreur détectée en traitant function <SNR>83_setup_buffer_leave :
|| ligne   10 :
|| E329: Aucun menu "Vimwiki"
|| Erreur détectée en traitant function vimwiki#base#follow_link[75]..vimwiki#base#open_link :
|| ligne   34 :
|| E171: :endif manquant
|| Erreur détectée en traitant function vimwiki#base#follow_link :
|| ligne   75 :
|| E171: :endif manquant
|| Erreur détectée en traitant function <SNR>83_setup_buffer_leave :
|| ligne   10 :
|| E329: Aucun menu "Vimwiki"
|| Erreur détectée en traitant function <SNR>83_setup_buffer_enter[7]..<SNR>83_set_global_options :
|| ligne    5 :
|| E329: Aucun menu "Vimwiki"
```
Can't this error be silenced and moved to a potential `checkhealth` script ?

- [x] Include the output of `:VimwikiShowVersion`.
```
Branch: dev                                                                                                                     
Revision: 1020ac5                                                                                                               
Date: 2020-04-22 11:22:53 -0400
```

**Comment by tinmarino** [comment]
The menu should be created on buffer enter.
I suspect you enter the buffer the `packadd vimwiki` then leave it. or no ?
A quick workaround would be to add
```
exe 'nmenu enable '.vimwiki#vars#get_global('menu').'.Table'
```
on buffer enter as done in `plugin.vimwiki.vim`: 
```
  exe 'autocmd BufLeave '.pat.' call s:setup_buffer_leave()'
```

**Comment by tinmarino** [comment]
Cannot reproduce, it may be already solved.
if someone experience the same issue, reopen or link the issue.
