### ISSUE TITLE
UltiSnips stops working for extensions set with VimWiki

### ISSUE THREAD

**Issue by ScheiklP** [vimwiki/vimwiki#868]
Hi,
I have SirVer/ultisnips and honza/vim-snippets in my init.vim (NVIM v0.5.0-nightly-1-gdc0e534).
The snippets work perfectly for both .md and .markdown (CTRL-B for snippet expanding).

Once I include vimwiki and set the extension to .md or .markdown, the one stops working for ultisnips (.md does not work when 'ext':'.md', but .markdown works, and vice versa).
```
let g:vimwiki_list = [{'ext': '.markdown', 'path': $HOME/VimWiki/', 'syntax': 'markdown'}]
let g:vimwiki_table_mappings = 0

let g:UltiSnipsExpandTrigger="<c-b>"         
let g:UltiSnipsJumpForwardTrigger="<c-n>"
let g:UltiSnipsJumpBackwardTrigger="<c-g>"
```

:verbose imap <c-b> is healthy and only returns the ultisnips binding.
:VimwikiShowVersio returns Stable version: '2.4.1'

**Comment by tinmarino** [comment]
> .md does not work when 'ext':'.md', but .markdown works, and vice versa

Hahaha, I get it you don't get it (neither do I).

1. Your filetype is `vimwiki` isn't it ?
In which case Ultisnip should not load `markdown`. Seems fair.
But you want __ultisnip__ (1) to load __markdown snippets__ (2)  if `ft` is `vimwiki` (3)

So you write in `.vim/ftplugin/vimwiki.vim` (3) the following:
```vim
UltiSnipsAddFiletypes markdown  " (1) and (2)
```

**Comment by ScheiklP** [comment]
That did it!
Thank you so much! :)
