### ISSUE TITLE
Feature Requestion: hyper link for definition?

### ISSUE THREAD

**Issue by llinfeng** [vimwiki/vimwiki#87]
The following syntax would give a well-structured definition: 

```
Term_1 :: explanation to the term

Term_2 ::
:: explanation to the term;
:: more explanations
```

The question is: can I _point to_  where a term is defined in vimwiki? If this is too hard to implement, would it be possible to enable syntax highlighting for those "Term_n" defined according to the syntax shown above? 

Alternatively, can I manually put some "anchor" to the line of definition and jump to this anchor when I want to refer to the definition?

Thanks.

**Comment by hq6** [comment]
Due to no additional comments from the @llinfeng , I am assuming all questions have been addressed by @EinfachToll 's latest response and closing this issue.
