### ISSUE TITLE
Open local pdf files with Zathura 

### ISSUE THREAD

**Issue by jbgriesner** [vimwiki/vimwiki#870]
Vimwiki seems to fail to open links towards local pdf files with my default pdf reader: zathura. Instead it opens pdf files into my browser...
Though I thought to add these lines to my vimrc was enough:

```shell
let g:wiki_viewer = {'pdf': 'zathura'}
let g:wiki_file_open = 'File_open'

function! File_open(...) abort dict " {{{1
    if self.path =~# 'pdf$'
        silent execute '!zathura' fnameescape(self.path) '&'
        return 1
    endif
    if self.path =~# 'png$'
        silent execute '!feh -.' fnameescape(self.path) '&'
        return 1
    endif
    if self.path =~# '\v(doc|xls|ppt)x?$'
        silent execute '!libreoffice' fnameescape(self.path) '&'
        return 1
    endif
endfunction
```
I observe no error message or anything suspicious.
It just opens my browser even for pdf files.
I know it's a minor problem, but what do you think could be wrong ?

Thanks:)

**Comment by mgarort** [comment]
Hi,

I'm just a Vim beginner so there's syntax in your code that I don't understand.

However, I created this simple function that opens the HTML file that corresponds to the current buffer, and created a mapping to `<C-h>`  to it:

``` vim
" Load the html of the current file in firefox (h for html)
function! OpenThisHTML()
    let path_to_html_folder = expand(g:vimwiki_list[0]['path_html'])
    let full_path_to_wiki_file = expand('%:p')
    let note_name = split(full_path_to_wiki_file, "wiki")[1]
    " The quotes around make sure that firefox receives the full path instead
    " of just the path up to the first parenthesis
    let full_path_to_html_file = "'" . path_to_html_folder . note_name . "html'"
    "The & at the end guarantees that firefox is executed in the background,
    "so Vim goes back to editing instead of hanging while Firefox is open
    execute "!firefox" full_path_to_html_file "&"  
endfunction
nmap <C-h> :call OpenThisHTML()<CR><CR>
```

It seems similar to what you want to do, so if you change "html" for "pdf" and `firefox` by `zathura` it should work.

Good luck!

**Comment by jbgriesner** [comment]
Hi,
Thanks for your great answer! It was very helpful!
I didn't investigate more the problem, so I will consider to use your solution.
Cheers,
