### ISSUE TITLE
don't conceal markup on current line

### ISSUE THREAD

**Issue by davy79** [vimwiki/vimwiki#874]
More of a question than an issue...

In my instance of vimWiki running neoVim all markup is concealed... also the current line which is sometimes difficult while editing because you don't see your link brackets, url's are shortened etc.
Then recently I saw a video of vimwiki where the active line disabled the concealing which would be very helpfull.

I read the doc's but can't seem to find an option related to this?

I did play around with `g:vimwiki_conceallevel` but I don't see any difference between all the settings from 0-3

Any pointers would be appreciated.

**Comment by tinmarino** [comment]
1. __Screenshot:__ Can you add a screenshot. I don't understand: I mean I cannot reproduce it: the line I am editing is not concealed at all ?
2. __Change conceallevel:__ Can you play with `set conceallevel` because vimwiki's one is just an autocommand that set it on buffer open ?

From `:h conceallevel`:
```
	Note: in the cursor line concealed text is not hidden, so that you can
	edit and copy the text.  This can be changed with the 'concealcursor'
	option.
```
That is why I am surprised.

**Comment by davy79** [comment]
Hi thanks for the great pointer!

When I `:set concealcursor=nc` it works as expected... showing all markup in insert/visual mode; but hiding it in normal mode. which is what I desire.

also `set conceallevel` seems to work now...

I wasn't aware these were vim options instead of vimWiki options.

Now just one more thing...
I can't seem to manage to make these settings permanent?

adding `set concealcursor=nc` to my vimrc doesn't seem to work? is vimWiki setting them as well?

**Comment by tinmarino** [comment]
Keep trying methodically.
Then you'll discover some magic. Note it in a vimwiki file for vim's magic.
Note each time your conceal level before and after changing buffer.

from `:h g:vimwiki_conceallevel`:

```
Vimwiki sets 'conceallevel' to g:vimwiki_conceallevel every time a Vimwiki
buffer is entered.
```

**Comment by davy79** [comment]
mystery solved...

I had another plugin (https://github.com/Yggdroot/indentLine) which was re-configuring the conceal options...

Thanks for the tips and pointing me in the right direction!
Now I can enjoy vimWiki even more as it was quite annoying editing links etc. while the markup was concealed ;-)
