### ISSUE TITLE
E684: list index out of range: 0, when creating a link containing a `.`

### ISSUE THREAD

**Issue by erich0123** [vimwiki/vimwiki#876]
Hello, I'm using the `dev` branch and tried to create a wiki link that contains a `.`.
The link does get created but the `.md` suffix is missing.
I used the following vimrc and get the following error, when creating a link such as `foo.bar` in my index file. I'm using markdown syntax.

Steps to reproduce:
1. Create an `index.md` index file with `<leader>ww`
2. Write `foo.bar`
3. Visually select `foo.bar`
4. Press `Enter`

`init.vim` for Neovim:
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'vimwiki/vimwiki', {'branch': 'dev'}
call plug#end()

let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]
let g:vimwiki_ext2syntax = {'.md': 'markdown'}
autocmd FileType vimwiki set syntax=markdown
```

Error message:
```
Error detected while processing function vimwiki#base#follow_link[75]..vimwiki#base#open_link[34]..vimwiki#base#edit_file[34]..vimwiki#u
#ft_is_vw:
line    1:
E684: list index out of range: 0
E15: Invalid expression: split(&filetype, '\.')[0] ==? 'vimwiki'
```

`:VimwikiShowVersion`
```
Branch: dev
Revision: 1020ac5
Date: 2020-04-22 11:22:53 -0400
```

**Comment by ranebrown** [comment]
Probably related to #835. Haven't had a chance to look at this but I'm guessing the regex needs adjusted.

**Comment by tinmarino** [comment]
It is the normal behavior: If we change this, we cannot add links to files with other extension as `layout.css`.

If you want a link to `foo.bar.md` you must write it completely, press enter and get:
```
[foo bar](foo.bar.md)
```
