### ISSUE TITLE
Centering images in native syntax

### ISSUE THREAD

**Issue by mgarort** [vimwiki/vimwiki#877]
What is the easiest way to tell Vimwiki, in the native Vimwiki syntax,  to center an image in the HTML display?

Is it to create your custom HTML class of images, and center that class?

Thanks!

**Comment by chuahou** [comment]
From the vimwiki help, you can try this:

```
Transclude image with alternate text and some style:

  {{http://.../vimwiki_logo.png|cool stuff|style="width:150px;height:120px;"}}

in HTML:

  <img src="http://vimwiki.googlecode.com/hg/images/vimwiki_logo.png"
  alt="cool stuff" style="width:150px; height:120px"/>
```

if you don't want to do this for an entire class of images.

You can see more information by accessing the help file (`:h vimwiki-syntax-links`) and scrolling down to "Transclusion (Wiki-Include) Links".

**Comment by tinmarino** [comment]
Thanks @chuahou

**Comment by mgarort** [comment]
Hello @chuahou and @tinmarino,

Thanks, I had already read the vimwiki help. However, as far as I understand (I could be wrong), this doesn't solve the issue:  this explains how to include an image, but not how to center it. I want to include an image in the HTML, and to format it so that it is centered along the page's width.

Do you know how I could do this?

**Comment by tinmarino** [comment]
You are right, the answer is not complete. The idea is to customize the style (css) which enable to center [see there](https://stackoverflow.com/questions/7055393)

```
  {{http://.../vimwiki_logo.png|cool stuff|style="width:150px; height:120px; display:block; margin:0 auto;"}}
```

Supposing  the `display:block; margin:0 auto` is centering well your image.
But this is verbose. I avice  you to use a custom css so then you only have to describe the class like `class=center`. See my [wiki](https://tinmarino.github.io/wiki_html) for example (I configure  the background color, display ... even include some js. I did it once, took me 10h but now I am free of css for life.

Hope that answer your question.

**Comment by tinmarino** [comment]
Self advertizing: I am actually proud of this [one](https://tinmarino.github.io/wiki_html/Cheat/Vim-Advanced.html) related to vim's tricks orthis [one](https://tinmarino.github.io/wiki_html/Cheat/Vim-Wiki.html) for vimwiki.

But I 1/ added some customization 2/ Use markdown and 3/pandoc as you can see in my [wiki2html.sh](https://github.com/tinmarino/wiki/blob/master/wiki2html.sh)

That said, if you can configure the style, the css/js power is in your hands. vimwiki focuses on the wiki or markdown syntax. It is far from perfect, we recognize, but then you got the power and portability of vim.

**Comment by chuahou** [comment]
Sorry, @mgarort, you're right, I should have pointed out exactly which part of my answer had to do with styling. As @tinmarino showed in their answer, I meant to show that you can put the CSS for centering in the "style" section of the transclusion.

To do style only,
```
{{{path/to/img|alt text|style="display: block; margin: 0 auto;"}}}
```

To do class, do
```
{{{path/to/img|class="center"}}}
```

and in your custom CSS add
```
.center {
    display: block;
    margin: 0 auto;
}
```

I'd like to second @tinmarino's answer that you should try writing a complete custom CSS. His linked examples of his wiki and custom `wiki2html.sh` are excellent. If you have more specific questions I'd be happy to try to help. (I jumped through some loops to get pandoc working seamlessly with vimwiki syntax instead of markdown, so I can help you with that if you so wish.)

**Comment by mgarort** [comment]
I see, this is what I was looking for! Thanks so much.
