### ISSUE TITLE
imap <cr> is prohibiting usage of vimwiki

### ISSUE THREAD

**Issue by thchha** [vimwiki/vimwiki#878]
Prior to submitting a new issue make sure to complete these steps:

- [X] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [X] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
Im using the .wiki syntax. 
```
  6   """"""""""""""""""""""""""""""  VIMWIKI   """""""""""""""""""""""""""""""""""""
    1 let g:vimwiki_list = [{'path': '~/workspace/wiki/raw'}]
    2 let g:vimwiki_global_ext = 0
    3 let g:vimwiki_folding='list'
```
- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.
`NVIM v0.5.0-501-g281e44f7b`
Hitting `<cr>` in insert mode exists the file I am in, but the index.wiki.

- [X] Include the output of `:VimwikiShowVersion`.
```
Branch: dev
Revision: 1020ac5
Date: 2020-04-22 11:22:53 -0400
```

You can also check my vim-specifics here: https://github.com/thchha/dotfiles/tree/master/nvim
There is one plugin of mine which redefines the completion popup, but even discarding this won't resolve the issue.

**Comment by thchha** [comment]
I closed the issue, because completely removing my plugin resolves the issue - 
In any case, if you have a hint about the missbehaviour I introduced with [myplugin](https://github.com/thchha/sticky_suggestions-vim/tree/94286c01d29e2dfe308f68d5210e11396e49b581) I would greatly appreciate it. Sorry for flooding your issue-tracker.

**Comment by ranebrown** [comment]
Not really sure what the issue is from your description. Vimwiki maps `<CR>` to handle lists properly. You can disable or remap that behavior if it is a conflict.

**Comment by thchha** [comment]
Meanwhile, I updated  to `NVIM v0.5.0-508-gc37d9fa3d` and the issue resolved. I am not able to relate any patch of neovim in between to the error which was: 
Entering _any_ newline via the enter-key (`<CR>`) while in insert mode exits the document (just like `<BS>` in normal mode), but my index.wiki.
Thanks for your fast response & interest!
