### ISSUE TITLE
Making links with quotation marks in them fails

### ISSUE THREAD

**Issue by Fruglemonkey** [vimwiki/vimwiki#88]
If you have a visual selection with an apostrophe (For example: test's) in it, then pressing enter to make a link fails.

Pressing enter on the word itself without a visual selection however, works fine.

Pressing enter on a word with quotation marks in it (For example: "tests") also fails, and gives you an empty link. However, making a link out of a visual selection containing a quotation mark is fine.

Tested on both the master branch and the dev branch.

**Comment by DQuomsieh** [comment]
has there been any updates on this issue?

**Comment by johnmarcampbell** [comment]
Yes. This should work now. If it's not working for you, try using the dev branch.

**Comment by DQuomsieh** [comment]
It works now, but only with visual selection on the entire word. Pressing enter on either side of the apostrophe of a word like "they're" will either form a link on "they" or "re" while pressing enter on the apostrophe gives me nothing. This seems to be the case for quotation marks as well.
