### ISSUE TITLE
E65 Error

### ISSUE THREAD

**Issue by ChenWeird** [vimwiki/vimwiki#881]
## my  `.vimrc` and have updated
    Plug 'vimwiki/vimwiki', { 'branch': 'dev' }
    let wiki = {}
    let wiki.name = 'ChenWei VimwikiMd'
    let wiki.path = 'd:/WeirdData/VimwikiMd/'
    let wiki.ext = '.md'
    let wiki.syntax = 'markdown'
    let wiki.nested_syntaxes = {'python': 'python'}
    let wiki.links_space_char = '_'
    let wiki.list_margin = 0
    let wiki.auto_toc = 1
    let wiki.auto_tags = 1
    let wiki.auto_generate_tags = 1

## `:VimwikiShowVersion`
Branch: dev
Revision: e850cb8
Date: 2020-05-13 11:35:22 -0400

## error

When I in a vimwiki page, just `enter`, it show the following error:

**Yesterday, I updated vimwiki.**
![E65-old.gif](https://i.loli.net/2020/05/14/ZQOvR3BcljSsXC1.gif)

**Today, I updated vimwiki.**
![E65-new.gif](https://i.loli.net/2020/05/14/hubAWV3Jvpi95UG.gif)

**messages**
处理 function vimwiki#base#follow_link[89]..vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[5]..<SNR>81_normalize_link_syntax_n[48]..vimwiki#base#is_diary_file 时发生错误:
第    4 行:
E65: 无效的回引
处理 function vimwiki#base#follow_link[89]..vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[5]..<SNR>81_normalize_link_syntax_n[48]..vimwiki#base#is_diary_file 时发生错误:

**Comment by ChenWeird** [comment]
When I rename the wikipage "2020年中战略会准备" to "年中战略会准备2020", it is back to normal.

**Comment by tinmarino** [comment]
Hi, must be related to #849 or #879. Sorry I cannot reproduce it. My commits may be guilties ...

1. Does it happen on master branch ?
2. What is the output of `:echo vimwiki#base#is_diary_file(@%)` ?
3. Can you debug the function `is_diary_file` in `base.vim` ?

**Comment by tinmarino** [comment]
To debug:
1. `:breakadd func  vimwiki#base#is_diary_file`
2. Do what fails
3. In the debug section:
```
next
echo l:diary_file_paths
next
echo l:normalised_file_paths
next
echo let l:matching_files
```

Ah and what is your vim version ? 8.2 ? 8.1 ? Neovim ? I already saw you are on windows.

Thanks

**Comment by ChenWeird** [comment]
# version

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 29 2019 23:21:03)
MS-Windows 64-bit GUI version 带 OLE 支持
包含补丁: 1-57
编译者 appveyor@APPVYR-WIN
巨型版本 带图形界面。  可使用(+)与不可使用(-)的功能:
+acl                +comments           +file_in_path       +listcmds           +persistent_undo    +statusline         +vartabs
+arabic             +conceal            +find_in_path       +localmap           +popupwin           -sun_workshop       +vertsplit
+autocmd            +cryptv             +float              +lua/dyn            -postscript         +syntax             +virtualedit
+autochdir          +cscope             +folding            +menu               +printer            +tag_binary         +visual
+autoservername     +cursorbind         -footer             +mksession          +profile            -tag_old_static     +visualextra
+balloon_eval       +cursorshape        +gettext/dyn        +modify_fname       +python/dyn         -tag_any_white      +viminfo
-balloon_eval_term  +dialog_con_gui     -hangul_input       +mouse              +python3/dyn        +tcl/dyn            +vreplace
+browse             +diff               +iconv/dyn          +mouseshape         +quickfix           -termguicolors      -vtp
++builtin_terms     +digraphs           +insert_expand      +multi_byte_ime/dyn +reltime            +terminal           +wildignore
+byte_offset        +directx            +job                +multi_lang         +rightleft          -termresponse       +wildmenu
+channel            -dnd                +jumplist           +mzscheme/dyn       +ruby/dyn           +textobjects        +windows
+cindent            -ebcdic             +keymap             +netbeans_intg      +scrollbind         +textprop           +writebackup
+clientserver       +emacs_tags         +lambda             +num64              +signs              -tgetent            -xfontset
+clipboard          +eval               +langmap            +ole                +smartindent        +timers             -xim
+cmdline_compl      +ex_extra           +libcall            +packages           +sound              +title              +xpm_w32
+cmdline_hist       +extra_search       +linebreak          +path_extra         +spell              +toolbar            -xterm_save
+cmdline_info       -farsi              +lispindent         +perl/dyn           +startuptime        +user_commands      
     系统 vimrc 文件: "$VIM\vimrc"
     用户 vimrc 文件: "$HOME\_vimrc"
 第二用户 vimrc 文件: "$HOME\vimfiles\vimrc"
 第三用户 vimrc 文件: "$VIM\_vimrc"
      用户 exrc 文件: "$HOME\_exrc"
  第二用户 exrc 文件: "$VIM\_exrc"
    系统 gvimrc 文件: "$VIM\gvimrc"
    用户 gvimrc 文件: "$HOME\_gvimrc"
第二用户 gvimrc 文件: "$HOME\vimfiles\gvimrc"
第三用户 gvimrc 文件: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
        系统菜单文件: "$VIMRUNTIME\menu.vim"
编译方式: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python37.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
链接方式: link  /nologo /opt:ref /LTCG:STATUS /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib netapi32.lib  /machine:AMD64  libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python37.lib   "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.lib xpm\x64\lib-vc14\libXpm.lib /PDB:gvim.pdb -debug

**Comment by ChenWeird** [comment]
# `:echo vimwiki#base#is_diary_file(@%)`
0

**Comment by ChenWeird** [comment]
## debug

简体中文消息维护者: Yuheng Xie <elephant@linux.net.cn>
"d:\WeirdData\VimwikiMd\index.md" [unix] 65L, 1675C
"D:\WeirdData\VimwikiMd\GTD.md" [unix] 55L, 1851C
断点 "vimwiki#base#is_diary_file" 第 1 行
进入调试模式。输入 "cont" 继续运行。
function vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[8]..<SNR>64_normalize_link_syntax_v[12]..vimwiki#base#is_diary_file
第 1 行: let l:diary_file_paths = a:0 > 0 ? a:1 : vimwiki#diary#get_diary_files()
function vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[8]..<SNR>64_normalize_link_syntax_v[12]..vimwiki#base#is_diary_file
第 2 行: let l:normalised_file_paths = map(l:diary_file_paths, 'vimwiki#path#normalize(v:val)')
处理 function vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[8]..<SNR>64_normalize_link_syntax_v[12]..vimwiki#base#is_diary_file 时发生错误:
第    2 行:
E121: 未定义的变量: :diary_file_paths
function vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[8]..<SNR>64_normalize_link_syntax_v[12]..vimwiki#base#is_diary_file
第 4 行: let l:matching_files = filter(l:normalised_file_paths, 'v:val =~# a:filename')
第    4 行:
E121: 未定义的变量: :normalised_file_paths
function vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[8]..<SNR>64_normalize_link_syntax_v[12]..vimwiki#base#is_diary_file
第 6 行: return len(l:matching_files) > 0 " filename is a diary file if match is found
第    6 行:
E121: 未定义的变量: let

**Comment by tinmarino** [comment]
```vim
:echo vimwiki#base#is_diary_file(@%)
```
Was it on the buggy file ("2020年中战略会准备")? I was expecting an error ...
Try to keep the errored file for some testing: you are belonging to vimwiki's tester already if you accept it ;-)

**Comment by ChenWeird** [comment]
> ```viml
> :echo vimwiki#base#is_diary_file(@%)
> ```
> 
> Was it on the buggy file ("2020年中战略会准备")? I was expecting an error ...
> Try to keep the errored file for some testing: you are belonging to vimwiki's tester already if you accept it ;-)

### YES

**Comment by ChenWeird** [comment]
## redebug on the buggy file ("2020年中战略会准备")

简体中文消息维护者: Yuheng Xie <elephant@linux.net.cn>
"d:\WeirdData\VimwikiMd\index.md" [unix] 65L, 1675C
"D:\WeirdData\VimwikiMd\GTD.md" [unix] 55L, 1886C
"D:\WeirdData\VimwikiMd\2020年中战略会准备.md" [unix] 6L, 154C
断点 "vimwiki#base#is_diary_file" 第 1 行
进入调试模式。输入 "cont" 继续运行。
function vimwiki#base#follow_link[89]..vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[5]..<SNR>64_normalize_link_syntax_n[48]..vimwiki#base#is_diary_file
第 1 行: let l:diary_file_paths = a:0 > 0 ? a:1 : vimwiki#diary#get_diary_files()
function vimwiki#base#follow_link[89]..vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[5]..<SNR>64_normalize_link_syntax_n[48]..vimwiki#base#is_diary_file
第 2 行: let l:normalised_file_paths = map(l:diary_file_paths, 'vimwiki#path#normalize(v:val)')
处理 function vimwiki#base#follow_link[89]..vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[5]..<SNR>64_normalize_link_syntax_n[48]..vimwiki#base#is_diary_file 时发生错误:
第    2 行:
E121: 未定义的变量: :diary_file_paths
function vimwiki#base#follow_link[89]..vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[5]..<SNR>64_normalize_link_syntax_n[48]..vimwiki#base#is_diary_file
第 4 行: let l:matching_files = filter(l:normalised_file_paths, 'v:val =~# a:filename')
第    4 行:
E121: 未定义的变量: :normalised_file_paths
E65: 无效的回引
function vimwiki#base#follow_link[89]..vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[5]..<SNR>64_normalize_link_syntax_n[48]..vimwiki#base#is_diary_file
第 4 行: 函数结束
E121: 未定义的变量: let

**Comment by ChenWeird** [comment]
sorry, there are more setting in my .vimrc about vimwiki. 

## This is the whole list:

    Plug 'vimwiki/vimwiki', { 'branch': 'dev' }
    let wiki = {}
    let wiki.name = 'ChenWei VimwikiMd'
    let wiki.path = 'd:/WeirdData/VimwikiMd/'
    let wiki.ext = '.md'
    let wiki.syntax = 'markdown'
    let wiki.nested_syntaxes = {'python': 'python'}
    let wiki.links_space_char = '_'
    let wiki.list_margin = 0
    let wiki.auto_toc = 1
    let wiki.auto_tags = 1
    let wiki.auto_generate_tags = 1

    let g:vimwiki_list = [wiki]
    let g:vimwiki_ext2syntax = {'.md': 'markdown'}
    let g:vimwiki_global_ext = 1
    let g:vimwiki_autowriteall = 1
    let g:vimwiki_auto_chdir = 1
    let g:vimwiki_folding = 'expr'

**Comment by ChenWeird** [comment]
> Does it happen on master branch ?

I reinstall vimwiki from `Plug 'vimwiki/vimwiki', { 'branch': 'dev' }` to `Plug 'vimwiki/vimwiki'`.

 it is back to normal.

**Comment by tinmarino** [comment]
> I reinstall vimwiki from Plug 'vimwiki/vimwiki', { 'branch': 'dev' } to Plug 'vimwiki/vimwiki'.

Cool ! Good idea from you

Thanks for the debugging section.
I have no idea what happened it seemed that `diary_file_paths` was undefined but no idea why as it was just defined. `E121: 未定义的变量: :diary_file_paths`. I wondered what the output of `echo l:diary_file_paths` just after defining it.

**Comment by tinmarino** [comment]
Fell free to reopen in need.
See you.

**Comment by ChenWeird** [comment]
## Which branch is currently the recommended version?
`Plug 'vimwiki/vimwiki', { 'branch': 'dev' }` or  `Plug 'vimwiki/vimwiki'`

I remember that the community has always recommended the use of dev branches.

**Comment by tinmarino** [comment]
Yes the dev branch is better
