### ISSUE TITLE
Escaping backticks in inline code?

### ISSUE THREAD

**Issue by descrip** [vimwiki/vimwiki#882]
Is there a way to escape backticks in inline code? In Markdown, I could do

    ```This is a backtick (`) in inline code.```

And this would render as  ```This is a backtick (`) in inline code.``` However, this doesn't seem to work in Vimwiki. In addition, backslash escaping doesn't seem to work.

`:VimwikiShowVersion` gives `Stable Version: 2.4.1`. I'm on a fresh installation of Vimwiki with no configuration in my `.vimrc`.

**Comment by tinmarino** [comment]
Can you add more info ?
1. Are you using markdown or default (wiki) syntax ?
2. Are you using the dev branch ?
3. Which conversion script are you using ?
4. You problem seems to be related to `md` -> `html` ? Isn't it ? can you post the both ?

**Comment by descrip** [comment]
Ah, sorry, I didn't realise Vimwiki supported multiple markup languages. I'm on the default Vimwiki syntax on the master branch.

**Comment by descrip** [comment]
For example, here is how 

```
`This is a backtick (`) in inline code.`
``This is a backtick (`) in inline code.``
```This is a backtick (`) in inline code.```
```

is rendered in Vim:

![image](https://user-images.githubusercontent.com/6173806/82160123-17658400-9861-11ea-8860-6f3e442547b4.png)

And HTML:

![image](https://user-images.githubusercontent.com/6173806/82160139-395f0680-9861-11ea-86b8-92eaa8f17c23.png)

**Comment by tinmarino** [comment]
Use the markdown syntax in that case

**Comment by tinmarino** [comment]
In any case, do not use `\`

# Wiki syntax

do not escape

```
Hi this is some code

<code> azezae ` eazeaz (`) aza </code>
```

# Markdown syntax

Use double ``` `` ``` or triple backtick as decribed [there](https://meta.stackexchange.com/questions/82718/how-do-i-escape-a-backtick-within-in-line-code-in-markdown). And do not escape

* Input
```markdown
# unescaped

* `This is a backtick (`) in inline code.`
* ``This is a backtick (`) in inline code.``
* ```This is a backtick (`) in inline code.```

# Escaped

* `This is a backtick (\`) in inline code.`
* ``This is a backtick (\`) in inline code.``
* ```This is a backtick (\`) in inline code.```

# Too much
* ```This is a backtick (\`\`\`\`\`) in inline code.```

```

* Ouput
```html
<h1 id="unescaped">unescaped</h1>
<ul>
<li><code>This is a backtick (</code>) in inline code.`</li>
<li><code>This is a backtick (`) in inline code.</code></li>
<li><code>This is a backtick (`) in inline code.</code></li>
</ul>
<h1 id="escaped">Escaped</h1>
<ul>
<li><code>This is a backtick (\</code>) in inline code.`</li>
<li><code>This is a backtick (\`) in inline code.</code></li>
<li><code>This is a backtick (\`) in inline code.</code></li>
</ul>
<h1 id="too-much">Too much</h1>
<ul>
<li><code>This is a backtick (\`\`\`\`\`) in inline code.</code></li>
</ul>
```
