### ISSUE TITLE
Visual Concealing issue with MacOS

### ISSUE THREAD

**Issue by franck-noahk** [vimwiki/vimwiki#893]
Prior to submitting a new issue make sure to complete these steps:

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.
----
I am having issues with the display of the wiki on my Mac. I am using the default syntax for .wiki files. but when I place links their syntax isn't hidden. So what I expect and what happens on other computers:
```
[[diary/index.wiki | Diary Home]] // would only display 'Diary Home' 
```
My set up is the same between a Mac & an Arch Linux box but I am only running into this issue on the Mac. Is it a bug with Catalina? (I am running Catalina 10.15.4) At the time of posting the master branch is the same as the dev branch so the bug doesn't appear to have been fixed yet. 

![Screen Shot 2020-05-29 at 12 08 13 PM](https://user-images.githubusercontent.com/46761809/83286203-21fb1400-a1a5-11ea-9d09-b0724b25f5e7.png)

Vimwiki related .vimrc:
```
nmap <F6> :VimwikiDiaryGenerateLinks<CR>
au BufNewFile ~/vimwiki/diary/*.wiki :silent 0r !~/.vim/bin/vimwiki-template '%'
filetype plugin on                  
set nocompatible    
```

**Comment by patrikjohansson** [comment]
Looks like your Vim install has not included support for `conceal`. Run  `vim --version` and see if what the result it. Is it not included it will be printed as `-conceal`.

I checked the default Vim in my Catalina install and it does not have conceal included.

**Comment by franck-noahk** [comment]
So I think you are right @patrikjohansson. Below is the output of my `vim --version command` is there any way to add support for conceal? 

`VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 29 2020 00:47:39)
macOS version
Included patches: 1-503, 505-680, 682-2292
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
-arabic            +file_in_path      -mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       -termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
-balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            -gettext           +num64             +textprop
+builtin_terms     -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     -perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        -vartabs
+clipboard         -keymap            +printer           +vertsplit
+cmdline_compl     +lambda            -profile           +virtualedit
+cmdline_hist      -langmap           +python/dyn        +visual
+cmdline_info      +libcall           -python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
-conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          -rightleft         +wildignore
+cscope            +localmap          +ruby/dyn          +wildmenu
+cursorbind        -lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            -mouse_dec         +statusline        -xsmp
-emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          -mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa           
`

**Comment by patrikjohansson** [comment]
@franck-noahk `conceal` is a compile-time flag, so you need to install some other Vim build, for example with Homebrew.

**Comment by Nudin** [comment]
Thanks @patrikjohansson for answering!
