### ISSUE TITLE
Travis tests are successful even if tests fails

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#896]
The new Travis tests are marked as successful even if there has been tests that failed.
[Example](https://travis-ci.com/github/vimwiki/vimwiki/builds/167865799)

**Comment by tinmarino** [comment]
Sorry, I am not a bash expert as @ranebrown 
I fixed this the easy way, with a global set where ranebrown is grepping the stdout of vader: 285f1628c2

**Comment by Nudin** [comment]
@tinmarino no problem, let me know if I can help. I know bash better then vimscript. ;)
