### ISSUE TITLE
Eror 484

### ISSUE THREAD

**Issue by Dmitryi** [vimwiki/vimwiki#897]
1. I open the diary.md file and create a new .md file.
In the file diary.md I press Enter on the new file and try to open it, but it does not work. In the folder diary a new file is not created. 

2. I am writing tasks for the day.
- [ ] Task one
- [ ] Task Two

Previously, when i press Enter, the cursor would go to the next line and the dash itself would appear, I only added square brackets and wrote text. Now this not work.

3. I press the zg key and this error appears.
E484: Unable to open the file /home/f32/.config/nvim/spell/en.utf-8.add

VimwikiShowVersion - Stable version: 2.5

**Comment by tinmarino** [comment]
Hi @Dmitryi,
1. I Cannot reproduce (sorry)
2. Press `<C-Space>` (and not `<Cr>`) and read `:h vimwiki-todo-lists`
3. This is not related to vimwiki: you did not download the english spell file. Read `:h 'spell'`

**Comment by Dmitryi** [comment]
In the file init.vim contains the path to the files

`set spellfile=~/.config/nvim/spell/ru.utf-8.add`
`set spellfile=~/.config/nvim/spell/en.utf-8.add`

The directory and files made writable, but no changes have been made.

`sudo chmod 777 -R spell`

Haved a empty files ru.utf-8.add and en.utf-8.add in directory spell

**Comment by tinmarino** [comment]
I Close because unrelated to vimwiki.
Try to read `:h spell` and to install spell files or with vim or by hand as proposed in the doc.
