### ISSUE TITLE
Help not working

### ISSUE THREAD

**Issue by dpecos** [vimwiki/vimwiki#9]
Hi

I just installed this plugin using bundle, and it works great, but I can't access to the docs from vi. When typing

```
:h vimwiki
```

I'm getting:

```
E149: Sorry, no help for vimwiki
```

Can you fix this?

Great work, btw.

Dani.

**Comment by DaveLG** [comment]
Well I have vimwiki installed on a Windows 10 machine with gvim. It seems to work as I can see vimwiki in the top menu as well as look at my old wiki's that I had in drop box with MacOS and MacVim.

I am missing vimwiki help though. I have tried these two commands in gvim but neither worked:

:helptags "C:\Program Files (x86)\Vim\vimfiles\bundle\vimwiki\doc\vimwiki.txt"
E471: Arguement required

:helptags "C:\Program Files (x86)\Vim\vimfiles\bundle\vimwiki\doc"
E471: Arguement required

If I run :Helptags nothing seems to happen. The cursor just returns to the edit window

Any ideas?
