### ISSUE TITLE
VimwikiRenameLink doesn't update links in diary

### ISSUE THREAD

**Issue by lervag** [vimwiki/vimwiki#90]
I have most of my wiki files in the root wiki folder `/path/to/wiki`, and I use a diary/journal inside a folder `/path/to/wiki/journal`. When I rename a file in the root wiki folder with `VimwikiRenameLink`, it updates the links correctly in the root wiki, but not in the diary, where the links are given as `[[../name]]` or `[[wiki0:name]]`.

**Comment by EinfachToll** [comment]
Just a quick update so that it doesn't look like I am lazy (of course I am, but I hope no one notices ;): this is a bit complicated to fix and needs some refactoring of the way Vimwiki handles its internal state. So it can take some time.

**Comment by lervag** [comment]
I see. No hurries, take your time. :)

**Comment by ranebrown** [comment]
This issue is still present.
