### ISSUE TITLE
Question about screenshots

### ISSUE THREAD

**Issue by ironyman** [vimwiki/vimwiki#903]
Unrelated to vimwiki, I really like the status bar in screenshots. 

https://github.com/vimwiki/vimwiki/blob/master/README.md#screenshots

Can the person that made the screenshot share how that's configured? Thanks!

**Comment by tinmarino** [comment]
I think you are speaking of iTerm2 Status Bar with @monkinco configuration.
You can find his dotfiles [here](https://github.com/monkinco/dotfiles) and a tutorial [here](https://medium.com/@msvechla/customizing-the-new-iterm2-status-bar-to-your-needs-252eee06bf39)
@monkinco ?

**Comment by monkinco** [comment]
I was using https://www.iterm2.com/3.3/documentation-status-bar.html with custom colors based on Jellybeans theme.

**Comment by ironyman** [comment]
Thanks!
