### ISSUE TITLE
Strange wrapping in rendered Markdown

### ISSUE THREAD

**Issue by elazar** [vimwiki/vimwiki#905]
# Configuration

vim: 8.2.869 (stock dnf package on Fedora 32)

vimwiki: 2.5 stable (also tried dev branch)

```vim
set nocompatible
filetype plugin on
syntax on
Plug 'vimwiki/vimwiki'
let g:vimwiki_list = [ 
    \ {'path': '~/path/to/wiki', 'syntax': 'markdown', 'ext': '.md'}
    \ ]

" Not required by vimwiki, but potentially relevant to this issue
set wrap
```

# Problem

The wrapping of the Markdown below when it's rendered is odd. When viewing the line unrendered, its wrapping appears to be relatively correct. In short, wrapping doesn't seem to be applied properly when the line is rendered, at least not immediately after links.

```md
A subsect of the [Legion of Dusk](https://mtg.gamepedia.com/Legion_of_Dusk), mainly composed of younger [vampires](https://mtg.gamepedia.com/Vampire#Ixalan) who have become disillusioned with the church, the aristocracy, and their pursuit of conquest and the [Immortal Sun](https://mtg.gamepedia.com/Immortal_Sun), and who simply want to live freely and in peace without oppression.
```

Rendered:

![Screenshot from 2020-06-05 13-31-49](https://user-images.githubusercontent.com/15487/83910954-0954a600-a731-11ea-85cc-8948b2de22eb.png)

Unrendered:

![Screenshot from 2020-06-05 13-32-11](https://user-images.githubusercontent.com/15487/83910962-0eb1f080-a731-11ea-8b20-3644cbd33b5d.png)

**Comment by elazar** [comment]
Here's an additional case that may or may not be related to this specific issue.

```md
* [The Ultimate Guide to Creating Captivating Characters](https://medium.com/the-1000-day-mfa/the-ultimate-guide-to-creating-captivating-characters-4becc1b1d465)
```

Rendered:

![Screenshot from 2020-06-05 13-48-37](https://user-images.githubusercontent.com/15487/83912319-4b7ee700-a733-11ea-8394-5d518a64e7ea.png)

Unrendered:

![Screenshot from 2020-06-05 13-49-02](https://user-images.githubusercontent.com/15487/83912355-5b96c680-a733-11ea-83b0-062eefa08bdf.png)

**Comment by tinmarino** [comment]
Old [vim issue](https://github.com/vim/vim/issues/260). Not easy to fix at all even for Bram Moolenar.
He may fix that when adding "tags" to buffer to help syntax color, say in two years

Actually very very hard. I admit I shamelessly remove that from vimwiki's scope. Thanks for the report, we cannot do anything (except may be investing 80h in vim source code).

**Comment by tinmarino** [comment]
Keywords: Conceal, Wrap, Markdown
Issue track: vim#260  Concealed text causes vim to wrap before window width
