### ISSUE TITLE
VimwikiTOC removes the following non-empty line if it contains a hyphen

### ISSUE THREAD

**Issue by chuahou** [vimwiki/vimwiki#910]
## Problem

`:VimwikiTOC` removes the following non-empty line if it contains a hyphen (`-`). I suspect it may be removing it as it uses hyphens to detect if that line is part of the existing TOC before updating it.

![GIF of problem](https://i.imgur.com/2wImkoP.gif)

## Steps to reproduce

1. Add some headers
2. `:VimwikiTOC`
3. Add a line containing a hyphen after the generated TOC
4. `:VimwikiTOC`

## Configuration

**Syntax**: default
```
let g:vimwiki_list = [{
			\ 'path'             : '~/Projects/knowledge/wiki/',
			\ 'path_html'        : '~/Projects/knowledge/docs/',
			\ 'template_path'    : '~/Projects/knowledge/templates/',
			\ 'template_default' : 'template',
			\ 'template_ext'     : '.html',
			\ 'nested_syntaxes'  : {
				\ 'algorithm': 'plaintex',
				\ 'cpp': 'cpp',
				\ 'clang': 'c',
				\ 'scala': 'scala',
				\ 'haskell': 'haskell'},
			\ 'custom_wiki2html' : '~/Projects/knowledge/wiki2html.sh',
			\ }]
let g:vimwiki_global_ext=0
noremap <Leader>wo :VimwikiGoto<Space>
noremap <Leader>wb :Vimwiki2HTMLBrowse<CR>
let g:vimwiki_conceallevel=0

```

## VimwikiShowVersion
```
Os: Linux
Vim: 800
Branch: dev
Revision: 285f162
Date: 2020-05-30 18:08:23 -0400
```

---

Prior to submitting a new issue make sure to complete these steps:

- [X] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [X] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [X] Include the output of `:VimwikiShowVersion`.

**Comment by tinmarino** [comment]
Fixed: 0693e4113252
