### ISSUE TITLE
Conceal list markers with other "disc" unicode character

### ISSUE THREAD

**Issue by nkakouros** [vimwiki/vimwiki#912]
This is feature request.

I would like to have my list bullets (in markdown) display in vim using a unicode character like this one `•`. 

When editing tex files using [vimtex](https://github.com/lervag/vimtex), I noticed that in an item list, the keywords for the list items get concealed:

![Screenshot_20200614_213800](https://user-images.githubusercontent.com/11805218/84602396-5c440100-ae87-11ea-9a70-fe6a34b53c92.png)

In the screenshot above, there are 3 `\item`s. I have the cursor on the first one.

I was wondering if it would be possible to do the same with markdown lists and conceal the `-` or `*` with a user defined character.

My use case is that I am trying to make my wikis look nice, sth like this:
![Screenshot_20200614_214231](https://user-images.githubusercontent.com/11805218/84602589-d923aa80-ae88-11ea-8c77-a6ccf2fd9e3a.png)

And I would like to have lists that look nice but that are still perceived as lists by markdown syntax. In the image above the third item list is not actually in the list because it starts with `•`. Similarly, a todo list could have the `- [ ]` and `- [x]` parts replaced with `✅🗹`.

**Comment by tinmarino** [comment]
Very good idea. A workaround exists but many people may want this feature.
I agree to add this behavior by default until someone complains.

Are you willing to try a PR ?


PS: You may play with `vimwiki-option-bullet_types` and `vimwiki-listsyms` but then you change the content of

**Comment by tinmarino** [comment]
@nkakouros @lervag how do you get this feature for vimtex, so that I can copy ?

**Comment by nkakouros** [comment]
I think this is provided by https://github.com/Konfekt/tex-conceal.vim.

With vimtex and this plugin installed, `set conceallevel=1` or `2` and the item list becomes a bullet.

**Comment by tinmarino** [comment]
@nkakouros  and for the vertical unicode line to show indentation `: ¦⁞⋮┆┊┋┇︙` ?

**Comment by nkakouros** [comment]
These are from another plugin https://github.com/Yggdroot/indentLine

**Comment by tinmarino** [comment]
Now it got easy to implement but the problem is that there is only one Conceal color (usually grey).
So I prefer `*` with color than `•`  without at least by default.

![Screenshot from 2020-08-06 15-01-02-wiki1](https://user-images.githubusercontent.com/6123962/89571829-4eab5780-d7f6-11ea-8c85-17bcc7f1144d.png)
![Screenshot from 2020-08-06 15-04-31-wiki2](https://user-images.githubusercontent.com/6123962/89571833-4f43ee00-d7f6-11ea-8332-c54154f1fec2.png)

The minimal code to change was in `syntax/vimwiki.vim`:

```vim
let list_cmd = 'syntax match VimwikiList /'.vimwiki#vars#get_wikilocal('rxListItemWithoutCB').'/'
" See: #912
if has('conceal')
  let list_cmd .= ' conceal cchar=•'
endif
execute list_cmd
```

But in real case, it must consider that user can modify rxListItemWithoutCB with vimwiki-option-bullet_types and vimwiki-listsyms

**Comment by lervag** [comment]
> @nkakouros: I would like to have my list bullets (in markdown) display in vim using a unicode character like this one `•`.
>
> ...

> @tinmarino: @nkakouros @lervag how do you get this feature for vimtex, so that I can copy ?

> @nkakouros: I think this is provided by https://github.com/Konfekt/tex-conceal.vim.
> 
> With vimtex and this plugin installed, `set conceallevel=1` or `2` and the item list becomes a bullet.

Sorry for the late reply. I've been away.

I just want to confirm that this particular conceal is not a vimtex feature.

> @tinmarino: Now it got easy to implement but the problem is that there is only one Conceal color (usually grey).

I assume this means you are already familiar with the conceal feature in Vim and the `cchar` (see `:help :syn-cchar`). Highlighting of the concealed character can (unfortunately) not be done "individually" for each concealement. There's the `Conceal` (`:help hl-Conceal`) highlight group, but it would set highlighting for _all_ conceal replacements.

----

An alternative to using the conceal option is to actually _type_ the bullet characters and to include it in the allowed bullets in vimwiki. This may break the filetype compatibility with e.g. pandoc or other tools, but it could be made to work quite seamlessly. E.g. with snippets or insert mode mappings.

**Comment by tinmarino** [comment]
Thanks @lervag, that is what I thought.
Sorry also for the late reply: I took time to digest.
Then we won't implement this issue: a personal workaround is possible in `.vim/ftpluin/vimwiki.vim`
I agree with @lervag: the best is to use `vimwiki-option-bullet_types` and `vimwiki-listsyms` and convert them back in the compiler preprocessor.

Thanks to both of you, see you around.

PS: By the way @lervag I love vimtex (especially the auto-compilation, jumping and concealing). Lot of inspiration comes from reading its code.

PS2: If someone want to code the concealing `- [X]` -> `✅` with some option, I think It will be accepted.

**Comment by lervag** [comment]
> Thanks to both of you, see you around.

No problem, happy to "pitch in"! :)
