### ISSUE TITLE
:VimwikiGoto tab completion only works when written in-line, not when called from \wn 

### ISSUE THREAD

**Issue by igor-kupczynski** [vimwiki/vimwiki#913]
PR #785 adds completion to `:VimwikiGoto`, however it works only when you try to type the filename after the command, e.g.

Say I have a file called `Hammerspoon.md`

```
:VimwikiGoto Hamm<tab>    # ✅  shows the completion pop-up
```

It doesn't work when called like that:
```
:VimwikiGoto<ret>
Hamm<tab>                  # ❌ shows `Hamm^I` (see below)
```
<img width="144" alt="image" src="https://user-images.githubusercontent.com/166651/84602657-623ae180-ae89-11ea-9a98-84b4d3a46825.png">

This is more problematic when used together with the `<Leader>wn` keyboard shortcut because it acts like the second, broken way.

It would be nice to improve the completion.

## Env

```
$ nvim --version
NVIM v0.4.3
```

```
:VimwikiShowVersion
Stable version: 2.5
```

```
call minpac#add('vimwiki/vimwiki')
let g:vimwiki_list = [
    \ {'path': '~/Notes', 'syntax': 'markdown', 'ext': '.md', 'index': 'README'},
.. other wikis here
    \ }
    \ ]
```

**Comment by tinmarino** [comment]
Fixed: 75a9232 
<- `input()` is taking the completion desired as argument
-> wanna see my dirty face -> 
```
function! vimwiki#base#goto(...) abort
  let key = a:0 > 0 ? a:1 : input('Enter name: ', '',
        \ 'customlist,vimwiki#base#complete_links_escaped')
```


Thanks for the feedback
