### ISSUE TITLE
Generating a vimwiki markdown link adds `__FileExtention__` instead of the correct extension `.md`

### ISSUE THREAD

**Issue by beuerle** [vimwiki/vimwiki#914]
I'm using the `dev` branch with the most recent commit. Running `:VimwikiShowVersion` gives me `Unknown version`.

This is probably related to the changes introduced by #895. Generating a markdown style link when pressing `ENTER` on a word now results in the following:

```markdown
- [test](test__FileExtention__)
```

I haven't changed any settings in my `vimrc` regarding vimwiki recently, and I am able to reproduce the issue with this minimal vimwiki config:

```vim
let g:vimwiki_list = [
    \ {'path':      '~/vimwiki/',
    \  'syntax':    'markdown',
    \  'ext':       '.md',
    \  'index':     'README'
    \},
    \]

let g:vimwiki_markdown_link_ext = 1
```

I am not too familiar with the codebase, but I tried to figure out what is going on.

If `vimwiki_markdown_link_ext` is set `__FileExtention__` is assigned:

https://github.com/vimwiki/vimwiki/blob/a9f21c6d4a8cedc58971d57df0c2bd2dea8c4d4c/autoload/vimwiki/vars.vim#L820-L822

and then `apply_template` should substitute `__FileExtention__` with the correct extension. but where is `a:rxExtension` coming from?

https://github.com/vimwiki/vimwiki/blob/a9f21c6d4a8cedc58971d57df0c2bd2dea8c4d4c/autoload/vimwiki/base.vim#L2206-L2208

Something I'm missing here?

**Comment by tinmarino** [comment]
> Running :VimwikiShowVersion gives me Unknown version

You are not in a good git branch. See `git status`

> but where is `a:rxExtension` coming from?

From sytanx file calling `vimwiki#base#apply_template`. (You can search the function name with grep or `ag 'vimwiki#base#apply_template'`
https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/syntax/vimwiki_markdown_custom.vim#L69-L71

> Something I'm missing here?

Yes and me too. Sorry. You can try to [debug](http://inlehmansterms.net/2014/10/31/debugging-vim/) to go futher. But `:VimwikiShowVersion` should give you something ok. Otherwise, you may go deep in analyse for nothing.

**Comment by beuerle** [comment]
> > Running :VimwikiShowVersion gives me Unknown version
> 
> You are not in a good git branch. See `git status`

I'm mainly using `neovim`, and `vimwiki` installed with `dein`. I verified before that the cache is at the most recent commit of `dev`.

I also tried it with `vim` itself:

```
Os: Linux
Vim: 802
Branch: dev
Revision: 865b402
Date: 2020-06-16 14:48:15 -0400
```

The behavior here is the same:

```markdown
* [test](test__FileExtention__)
```

**Comment by tinmarino** [comment]
Nice, my bad. I also get the same !

1. The error comes from here: `let g:vimwiki_markdown_link_ext = 1`. I'll follow that and make an update.

2. You are also showing an other error: `:VimwikiShowVersion` do not work with neovim. May you help on this one with `debug VimwikiShowVersion` ?

**Comment by tinmarino** [comment]
Bug introduced here: afc868929d8119a41

**Comment by tinmarino** [comment]
It should work now: e182670

**Comment by beuerle** [comment]
> 2. You are also showing an other error: `:VimwikiShowVersion` do not work with neovim. May you help on this one with `debug VimwikiShowVersion` ?

```
Entering Debug mode.  Type "cont" to continue.
cmd: VimwikiShowVersion
cmd: call s:get_version()
function <SNR>58_get_version
line 1: if s:plugin_vers != -1
function <SNR>58_get_version
line 3: else
function <SNR>58_get_version
line 4: let l:plugin_rev    = system('git --git-dir ' . s:plugin_dir . '/.git rev-parse --short HEAD')
function <SNR>58_get_version
line 5: let l:plugin_branch = system('git --git-dir ' . s:plugin_dir . '/.git rev-parse --abbrev-ref HEAD')
function <SNR>58_get_version
line 6: let l:plugin_date   = system('git --git-dir ' . s:plugin_dir . '/.git show -s --format=%ci')
function <SNR>58_get_version
line 7: if v:shell_error == 0
function <SNR>58_get_version
line 13: else
function <SNR>58_get_version
line 14: echo 'Unknown version'
function <SNR>58_get_version
line 15: endif
function <SNR>58_get_version
line 16: endif
function <SNR>58_get_version
line 16: End of function
```

**Comment by beuerle** [comment]
> It should work now: [e182670](https://github.com/vimwiki/vimwiki/commit/e1826702b7c1c538ce5b3993c9f3aea60df5dcc6)!

Thank you for the quick fix, excellent!

**Comment by tinmarino** [comment]
Thanks for the neovim feefback. Your `system` command fail. I'll have a look to give user a feedback even if some system command fails.

**Comment by beuerle** [comment]
Don't have time right now to resolve this myself, just to report:

the issue prevails when doing `VimwikiDiaryGenerateLinks`:

```markdown
# Diary

## 2020

### June


- [Tue 2020-06-16](2020-06-16__FileExtension__)
- ...
```

**Comment by tinmarino** [comment]
> Don't have time right now to resolve this myself, just to report:
> 
> the issue prevails when doing `VimwikiDiaryGenerateLinks`:
> 
> ```gfm
> # Diary
> 
> ## 2020
> 
> ### June
> 
> 
> - [Tue 2020-06-16](2020-06-16__FileExtension__)
> - ...
> ```

Fixed: 45b7515

**Comment by beuerle** [comment]
Still more hidden in the codebase!

`:VimwikiGenerateTagLinks`:

```
# Generated Tags

## tag

- [1517h](diary/2020-01-03__FileExtension__#Fri 2020-01-03#1517h)
[...]
```

(I'm sitting on the most current commit `69ead3b` on `dev`)

**Comment by tinmarino** [comment]
Thank you @beuerle, I thought I found them all ...

**Comment by beuerle** [comment]
thanks!

you might wanna merge it to `vimwiki/dev` at some point
