### ISSUE TITLE
Error due to duplicate helptags; followup to #911

### ISSUE THREAD

**Issue by ebassett** [vimwiki/vimwiki#918]
Prior to submitting a new issue make sure to complete these steps:

- [X] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [N/A] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [SEE DETAILS BELOW] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [X] Include the output of `:VimwikiShowVersion`.
    Os: Linux
    Vim: 802
    Branch: dev
    Revision: e182670
    Date: 2020-06-16 17:47:40 -0400

DETAILS:
In **.../doc/vimwiki.txt**, in **Section 12.3 Per-Wiki Options**, the helptag subheader **vimwiki-option-bullet_types** is listed twice: once for the intended _bullet_types_ option, and then immediately below that again for the _cycle_bullets_ option. This makes the `:helptags` command (which, in my case, is run automatically by the Vundle plugin-manager following updates of plugins) error out.
The latter helptag subheader should obviously be **vimwiki-option-cycle_bullets**, as confirmed by my making that edit locally and re-running `:helptags`.

I would like to submit the PR to fix this myself, if you don't mind.

**Comment by tinmarino** [comment]
My bad sorry. Tk for the PR: its nice to get corrected so fast
