### ISSUE TITLE
Inline code parse conflicts with inline equations

### ISSUE THREAD

**Issue by brookst** [vimwiki/vimwiki#92]
I ran into this issue doing something like:

```
 `$` `$`
```

Vimwiki renders this as:

```
\( \)
```

The inline equation regex parses the dollars even though they are within inline code blocks. I took a cursory look around the [html.vim](https://github.com/vimwiki/vimwiki/blob/master/autoload/vimwiki/html.vim#L512) file and tried blindly reordering some of the regex matching but it looks like it's tricky to solve without breaking any other syntax.

Is this a known issue that's too hard to solve or can someone fix it?

**Comment by tinmarino** [comment]
Thanks @brookst for the nice regression test that we will used.
Sorry to say that it is still not fixed.
Closing <= I am refactoring tickets => #1139 1139
