### ISSUE TITLE
Alternative tags syntax

### ISSUE THREAD

**Issue by lfrati** [vimwiki/vimwiki#922]
I love using vimwiki but I was wondering if it would be possible to have a tags syntax that is compatible with YAML front matters. I use the Markdown format and I add headers like this to new entries
```
---
tags: :test: 
date: 2020-06-17T12:17:15-04:00
---
```
The surrounding double colon seems to mess with the parser and the front matter is not recognized.
I could just remove the colons but I would like to keep vimwiki's tags indexing capabilities (especially for omnicomplete suggestions).

**Comment by regnat** [comment]
That would indeed be pretty useful to tag markdown files in an idiomatic way

As a (rather ugly) workaround atm I embed the tags in a yaml multi-line string, which makes them both clearly visible in the front-matter and recognized by vimwiki

```yaml
tags: |
  :test: :someothertag:
```

**Comment by oz** [comment]
But you are already using tags with vimwiki then... :smile: 

On my side, I started tagging things with one or more lines starting with `tags: ` and a bunch of `@tags`. The point is to be able to search easily with grep-like tools, and the syntax does not really matter here (I'm not strongly attached to mine).

Now, maybe we think of some features related to tags...

1. a (temp?) page with links to docs matching a number of tags?
2. tagging of TODO items/lists?
3. autocompletion of tags?

**Comment by tinmarino** [comment]
4. Tag file coherent with ctags format

**Comment by tinmarino** [comment]
Fixed: 188ead55db340f

See the new doc: https://github.com/vimwiki/vimwiki/blob/188ead55db340fc10e9d5facf40f0ecb42b81985/doc/vimwiki.txt#L3602-L3631

#### 1 Paste In VimRc
```vim
let g:vimwiki_tag_format = {'pre': '\(^[ -]*tags\s*:.*\)\@<=', 'pre_mark': '', 'post_mark': '', 'sep': '>><<'}
```

#### 2 Edit file {ensure filtype is vimwiki)

```markdown
# Tags here

tags: tag1 tag2 tag3
```


#### 3 Execute
```
:exe 'VimwikiRebuildTags!' | VimwikiGenerateTagLinks
```

#### 4 Admire

```markdown
# Generated Tags

## tag1

- [tags-here](tag.md#tags-here)

## tag2

- [tags-here](tag.md#tags-here)

## tag3

- [tags-here](tag.md#tags-here)
```

![Screenshot from 2020-08-08 04-23-03vimwiki](https://user-images.githubusercontent.com/6123962/89705886-e8762000-d92e-11ea-83b5-3fd6110a47ed.png)

#### 5 Tell if it works and maybe read the new doc

**Comment by kryst3q** [comment]
> EDIT feature already present:
> 3. ✔️ autocompletion of tags? Working is stars with :
> 4. ✔️ Tag file coherent with ctags format

@tinmarino How can I use autocompletion of tags? When I start typing a tag there is no window with proposed, already existing tags? What should I do to enable that functionality?

**Comment by Smingvin** [comment]
Hi, I needed this. Great! 

One thing to note. To make the :VimwikiSearchTags command work with the new syntax, you'll need to edit this line in the ftplugin/vimwiki.vim file:

`
command! -buffer -nargs=* -complete=custom,vimwiki#tags#complete_tags
      \ VimwikiSearchTags VimwikiSearch /:<args>:/
`

I don't know how it would work in the use case from this topic. But if you usued @tags or #tags then it would simply be @<args> or #<args>

Btw, I'm not git-literate so I can't contribute.
