### ISSUE TITLE
Is it possible to make VimwikiFollowLink generate absolute links?

### ISSUE THREAD

**Issue by sdondley** [vimwiki/vimwiki#936]
I've poured through the documentation and code but don't see a way to force newly created links to generate absolute paths. In other words, instead of `[link](link)` I want `[link](/link)`.

As a last resort, I hacked the vars.vim file:

```
  let mkd_syntax.Weblink1Template = mkd_syntax.rxWeblink1Prefix . '__LinkDescription__'.
        \ mkd_syntax.rxWeblink1Separator. '/__LinkUrl__'. rxWeblink1Ext.
        \ mkd_syntax.rxWeblink1Suffix
```

Am I missing some better way of doing this?

**Comment by tinmarino** [comment]
Hi,
When a after a press Enter on `link`, it is not an option currently as far as I know. The way you handled it was the faster win.
#811 is related but is not the same feature and is not merged

**Comment by tinmarino** [comment]
You put your eyes in a big machinery that may be improved and parametrised but it will take some time. (Well of course we work slowly) First we are trying (Nudin idea) to separe language options from wiki options and here you are, in the language vars.vim that are called like spaghetti.
So my advice:
1/ Choose the easy win: if it works, that is nice
or
2/ Try PR to despagetify a little and put a custom option that we will try to maintain and improve with non regression tests.

**Comment by sdondley** [comment]
Thanks for getting back.

I'm now using `:vim2HTML` with a custom script to modify the markdown links and make them absolute for me. So for now, this is no longer an issue for me.

**Comment by sdondley** [comment]
Closing

**Comment by tinmarino** [comment]
> Thanks for getting back.
> 
> I'm now using `:vim2HTML` with a custom script to modify the markdown links and make them absolute for me. So for now, this is no longer an issue for me.

Same here: thie (pandoc) is the recomended way: better to maintain a parser in Haskell than vimscript
