### ISSUE TITLE
Feature Request: Table conversion to html should have thead element if header exists for table

### ISSUE THREAD

**Issue by gaurangkher** [vimwiki/vimwiki#940]
### Syntax
default

### Description
When table is converted to html , the table headers are part of tbody tag instead of thead tag.
If a wiki table has headers they should be added to the thead tag 
Javascript libraries like datatables rely heavily on table headers to be contained inside thead tag.

Eg: Currently 
```
| header1 | header1 |
|---------|---------|
|  val1    | val2    |
```
is converted to
```
<table>
    <tr>
       <th> header1</th>
       <th> header2 </th>
    </tr>
    <tr>
       <td> val1 </td>
       <td> val2 </td>
    </tr> 
</table>
```
However This should be converted as below:
```
<table>
   <thead>
    <tr>
       <th> header1</th>
       <th> header2 </th>
    </tr>
   </thead>
   <tbody>
    <tr>
       <td> val1 </td>
       <td> val2 </td>
    </tr> 
   </tbody>
</table>
```

**Comment by tinmarino** [comment]
Closed by #940
