### ISSUE TITLE
Markdown strong emphasis is not highlighted

### ISSUE THREAD

**Issue by kejadlen** [vimwiki/vimwiki#944]
Text surrounded by two asterisks or underscores isn't highlighted. I'd expect `**foo** or __bar__` to be emphasized in some form. It does seem like the emphasis is detected, since the "control characters" are hidden, but the word itself doesn't get any extra highlighting.

`.vimrc`:

```
let g:vimwiki_global_ext = 0
let g:vimwiki_list = [{'path': '~/.vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]
```

`:VimwikiShowVersion`:

```
Os: Mac
Vim: 802
Branch: dev
Revision: da9ef92
Date: 2020-06-16 23:21:41 -0400
```

**Comment by tinmarino** [comment]
This is not a normal behavior.

Your cursor on the `bolded text __here__ please`
`:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')`
`:hi VimwikiBold`

Please paste the output of thos 2 commands

**Comment by tinmarino** [comment]
Also: 'highlighted' is called 'bold' and in a white font on dark terminal, the effect is very small: the backgroung should not be changed.
I don't know if you want to change the backgound but if this is the case you can change `:hi VimwikiBold` (considering you got the output I expect in the 2 commands in the comment above)

**Comment by tinmarino** [comment]
I am closing, because it seems to need no development but feel free to:
- Comment
- Reopen

**Comment by kejadlen** [comment]
Ah, for some reason, bold fonts were disabled in Terminal.app. Thanks so much for the debugging help!
