### ISSUE TITLE
How to use vimwiki filetype only for vimwiki files (not all .md files)

### ISSUE THREAD

**Issue by nfarrar** [vimwiki/vimwiki#95]
I've just started using vimwiki, and set the base configuration as:

    let g:vimwiki_root = $HOME . '/Documents/Wiki'
    let g:vimwiki_list = [{'path': $HOME . '/Documents/Wiki',
      \ 'syntax': 'markdown', 'ext': '.md'}]

When I open markdown files not inside that filepath, they are detected as ft=vimwiki rather than markdown. I've looked through the docs, but not seeing an obvious way to control this behavior.

My assumption is that I could do this through the syntax/ext - something like this:

    let g:vimwiki_root = $HOME . '/Documents/Wiki'
    let g:vimwiki_list = [{'path': $HOME . '/Documents/Wiki',
      \ 'syntax': 'markdown', 'ext': '.vmwd'}]

Would allow vimwiki to use markdown and associate the exten .vmwd with those files, so regular .md files would not be hijacked. However, I'll have to do additional configuration with other applications to make them recognize this extension. Is this the best solution?

**Comment by EinfachToll** [comment]
There is an option `g:vimwiki_global_ext` for that problem. Set it to 0 to disable the creation of temporary wikis.
