### ISSUE TITLE
Error when converting to html using custom script for markdown syntax

### ISSUE THREAD

**Issue by sdondley** [vimwiki/vimwiki#951]
With `:Vimwiki2HTML` I get:
```
Error detected while processing function vimwiki#html#Wiki2HTML[1]..<SNR>112_convert_file:
line   27:
E121: Undefined variable: htmlfile
E15: Invalid expression: path_html.htmlfile
```

I fixed the issue with a hack. I have no idea if it's a correct hack, but hopefully it helps track down the problem. I'll submit pull request with the hack.

**Comment by tinmarino** [comment]
Thanks for taking the time for the PR, it solved it (sorry for not merging your PR directly, I had some of mine to squash)
As I stole your commit, I offer you the command I discovered (may you already know):
```
git fetch wiki pull/953/head:test_953 # Steal the branch from your PR 
git checkout test_953  # checkout to the branch I decided to call test_953
```

Anyway, very nice catch.
Hope to see you soon.
