### ISSUE TITLE
Optionally disable autoupdate of parent checkbox

### ISSUE THREAD

**Issue by liskin** [vimwiki/vimwiki#954]
[taskwiki](https://github.com/tools-life/taskwiki) integrates vimwiki with taskwarrior, and in doing so [changes the semantics of checkboxes](https://github.com/tools-life/taskwiki/blob/9565f1f30e439c6a4606a72b1a568dc2dd8f1c83/doc/taskwiki.txt#L261-L267) a bit:

```vim
   * [ ] Install Taskwiki   |   pending task
   * [X] Install Taskwiki   |   completed task
   * [D] Install Taskwiki   |   deleted task
   * [S] Install Taskwiki   |   started task
   * [W] Install Taskwiki   |   waiting task
```

It's still desirable for vimwiki to automatically insert `* [ ]` on `i_<CR>`, `o` and `O` and to syntax highlight all these five as checkboxes, so I have this in my .vimrc:

```vim
let g:vimwiki_listsym_rejected = 'D'
let g:vimwiki_listsyms = ' WSX'
```

but it results in undesirable behaviour with task hierarchies: when I add a new subtask (using`i_<CR>`, `o` or `O`) 
 or mark a subtask done, the parent's checkbox is updated to reflect its overall completion, to one of ` `, `W`, `S` or `X`, depending on subtasks completion. This makes little sense in taskwiki. One usually doesn't want to touch the "parent" task in taskwarrior until the "subtasks" are done. Setting

```vim
let g:vimwiki_listsym_rejected = 'W'
let g:vimwiki_listsyms = ' SX'
```

results in slightly less illogical behaviour, but it still assumes that (1) all subtasks are visible (not necessarily true in taskwiki) and (2) that it's a parent/subtask relationship, not a dependency relationship (not true in taskwarrior, questionable in taskwiki).

It would be awesome if this auto updating of parent task state could be disabled somehow. The other option is for taskwiki to provide its own mappings for these operations, but that seems like unnecessary code duplication to me.

I am open to trying to implement this myself, but I feel like such a feature should be discussed first. I'm also not sure if this should be a user-configured thing or if vimwiki should somehow detect (or be told by) taskwiki and disable it automatically.

**Comment by tinmarino** [comment]
> I am open to trying to implement this myself, but I feel like such a feature should be discussed first. I'm also not sure if this should be a user-configured thing or if vimwiki should somehow detect (or be told by) taskwiki and disable it automatically.

Nice attitude. In your case,  it seems to be a boolean variable close to `vimwiki-listsyms-propagate = 0` for no propagation.
I usually do not like to stack boolean variable but my first contribution was `*g:vimwiki_table_reduce_last_col*` which I may be the only one to use. So as long as you:
1.  use it
2. do not change default behaviour
3. add test for maintenance

A boolean variable is ok.

My estimate: 2h for the feature and 2h for the tests. Thanks for your will to contribute.

**Comment by liskin** [comment]
This was merged in https://github.com/vimwiki/vimwiki/pull/1041
