### ISSUE TITLE
HI .I  like your vim statusline  in the Screenshots

### ISSUE THREAD

**Issue by clnote** [vimwiki/vimwiki#960]
Can you give me  the statusline  code? 
and what on the top right ,there have  sytem info

**Comment by tinmarino** [comment]
> I was using https://www.iterm2.com/3.3/documentation-status-bar.html with custom colors based on Jellybeans theme.

From: https://github.com/vimwiki/vimwiki/issues/903#issuecomment-639461065

Found searching `screenshot README status` in the issues
