### ISSUE TITLE
Diary index is cleared instead of updated

### ISSUE THREAD

**Issue by MaralWa** [vimwiki/vimwiki#961]
When I try to update the index of the diary the index is cleared. All existing entries are removed and no new entries are added, i.e. after I have performed the shortcut <leader>w<leader>i or entered the command :VimwikiDiaryGenerateLinks the index of the diary is empty but existing diary files still exists.

**Comment by tinmarino** [comment]
Are you on the dev branch ?

**Comment by MaralWa** [comment]
No, I am on the master:

commit 619f04f89861c58e5a6415a4f83847752928252d (HEAD -> master, tag: v2.5, origin/master, origin/HEAD)
Author: Michael F. Schönitzer <michael@schoenitzer.de>
Date:   Tue May 26 23:39:31 2020 +0200

    Bump version number – release 2.5

**Comment by tinmarino** [comment]
It has been fixed in the dev branch commit: af08e340006e Issue  #921
Checkout to the dev branch : in vimwiki plugin path
```
git checkout --track -b dev origin/dev
```
