### ISSUE TITLE
turn off support for markdown

### ISSUE THREAD

**Issue by iandstanley** [vimwiki/vimwiki#969]
using vim 8.1.1401 with latest vimwiki (updated last week)

I've been using vimwiki with vimwiki .wiki files for a few weeks now and loving it

but I am also writing some longer documentation in markdown 

Occaisionally I hit enter when I am not in insert mode and vimwiki kicks in to insert a link

How can I disable vimwiki for markdown files?

Basically I only want vimwiki for .wiki files and NOT markdown

**Comment by tinmarino** [comment]
The doc is really hard to read, our bad. __In your case `let vimwiki_ext2syntax = {}` before packadd vimwiki does the trick__ (:h  vimwiki_ext2syntax).

There is no `ftdetect`. So only `plugin` can define such behavior with autocommands. Scrolling after the function definition or searching for autocommand leads you here. Sorry to say the "code is the doc" but such a bi project is hard to index (even if it is made to generate index .... monday jokes ....)


This line https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/plugin/vimwiki.vim#L301

Calling https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/plugin/vimwiki.vim#L143-L155

**Comment by tinmarino** [comment]
By the way, don't do that, better learn to use Vimwiki with markdown, it is made for that (syntax, map, command, table).

**Comment by jarbus** [comment]
Would it be possible to add a feature to disable Vimwiki on markdown files? It's overriding the markdown filetype as a Vimwiki filetype and screwing up my Ultisnips snippets for markdown
