### ISSUE TITLE
pressing d key error occurs

### ISSUE THREAD

**Issue by douglas86** [vimwiki/vimwiki#973]
Prior to submitting a new issue make sure to complete these steps:

- [ ] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [ ] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [ ] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [ ] Include the output of `:VimwikiShowVersion`.

when pressing the d key, I get VimwikiMakeDairyNotes pop up at the bottom, how do I turn that off.

**Comment by tinmarino** [comment]
No idea, I cannot reproduce, please follow the steps (checkout dev, details, Version)
