### ISSUE TITLE
Question: Accessing other files within vimwiki

### ISSUE THREAD

**Issue by zamlz** [vimwiki/vimwiki#979]
It's pretty straightforward to link other files in vimwiki, specifically I woudl like to be able to open up my ledger file (ledger-cli) and it uses the vim-ledger plugin. However, when I open the `*.journal` through vimwiki, I'm not seeing it use the syntax and keybindings provided by the vim-ledger plugin. I can open the main.journal file normally and see the syntax. Any thoughts as to how to go about fixing this?

**Comment by tinmarino** [comment]
Hi @zamlz 

Thanks for raising the issue. It is actually a bug (That I can reproduce). The filetype should be set to journal

**Comment by tinmarino** [comment]
Fixed : 659ca62 removing the annoying line
