### ISSUE TITLE
Broken TOC links format when using default syntax

### ISSUE THREAD

**Issue by uolot** [vimwiki/vimwiki#981]
Since the recent changes to markdown links, links in my TOC became odd when using the default syntax.
Previously, a `= Foo =` header would appear in the contents as `[[#Foo|Foo]]`, but now it's `[[#foo]]`.
The links work as expected and do navigate to the linked header when pressing `<Cr>`, they just don't look good.

I'm using the `dev` branch and the syntax is set to `default`.

## Sample file

The links inside `Contents` were generated automatically.

```
= Test =

= Contents =
  - [[#test]]
  - [[#foo]]
  - [[#-foo-]]
  - [[#-a-]]
  - [[#-b-]]
  - [[#bar]]
  - [[#-bar-]]
  - [[#-x-]]
  - [[#-xa-]]
  - [[#-xb-]]
  - [[#-y-]]
  - [[#-ya-]]

= Foo =
== A ==
== B ==
== C ==

= Bar =
== X ==
=== Xa ===
=== Xb ===
== Y ==
=== Ya ===
=== Yb ===
```

## `:VimwikiShowVersion`

```
Os: Linux
Vim: 802
Branch: dev
Revision: a1f1b9c
Date: 2020-08-09 16:29:39 -0400
```

## Config:

```vim
Plug 'vimwiki/vimwiki', { 'branch': 'dev' }

" Contents
" 01 Vimwiki wikis
" 02 Vimwiki config
" 03 Vimwiki mappings

" 01 Vimwiki wikis

let wiki1 = {}
let wiki1.path = '~/.vimwiki'
let wiki1.maxhi = 1
let wiki1.auto_diary_index = 1
let wiki1.auto_export = 1
let wiki1.auto_generate_links = 1
let wiki1.auto_generate_tags = 1
let wiki1.auto_tags = 1
let wiki1.auto_toc = 1

let g:vimwiki_list = [wiki1]

" 02 Vimwiki config

let g:vimwiki_auto_chdir = 1
let g:vimwiki_auto_header = 1
" let g:vimwiki_conceal_pre = 1
let g:vimwiki_emoji_enable = 0
let g:vimwiki_hl_cb_checked = 0
let g:vimwiki_hl_headers = 1
let g:vimwiki_list_ignore_newline = 1
let g:vimwiki_listsym_rejected = '-'
let g:vimwiki_listsyms = ' .x'
let g:vimwiki_markdown_link_ext = 0
let g:vimwiki_table_auto_fmt = 1
let g:vimwiki_text_ignore_newline = 0
" let g:vimwiki_toc_header_level = 2
let g:vimwiki_url_maxsave = 50

function! VimwikiFindIncompleteTasks()
  lvimgrep /- \[ \]/ %:p
  lopen
endfunction

function! VimwikiFindAllIncompleteTasks()
  VimwikiSearch /- \[ \]/
  lopen
endfunction

" 03 Vimwiki mappings

nnoremap <Leader>wa :call VimwikiFindAllIncompleteTasks()<CR>
nnoremap <Leader>wx :call VimwikiFindIncompleteTasks()<CR>

nmap glt I- [ ] <Esc>
vnoremap glt :'<,'>norm I- [ ] <CR>

nnoremap <Leader>wg :VimwikiGoto 
nnoremap <Leader>wf :Files ~/.vimwiki/<CR>
nnoremap <Leader>w/ :VimwikiSearch 
nnoremap <Leader>wT :VimwikiTOC<CR>
nnoremap <Leader>wq :VimwikiGoto Scratchpad<CR>
nmap <Leader>ws <Plug>VimwikiSplitLink
nmap <Leader>wv <Plug>VimwikiVSplitLink
nnoremap <Leader>wl :VimwikiRenumberList<CR>

autocmd FileType vimwiki setlocal textwidth=120 nowrap linebreak nolist wrapmargin=0

```

**Comment by tinmarino** [comment]
My bad, with `vimwiki#base#nomalize` : I'll fix that in the next 2 days

---
```
let g:vimwiki_emoji_enable = 0
```

Have a look a `:h ki-em` or longer `:h vimwiki-emoji.txt`

```
nnoremap <Leader>wf :Files ~/.vimwiki/<CR>
```

Do you use that more than `nnoremap <Leader>wg :VimwikiGoto` ?
Very nice vimrc, we should add some of this to doc for new users
---

**Comment by tinmarino** [comment]
Fixed !

### Note 
I think I change the behavior of `let g:vimwiki_toc_link_format = 1` : 1 means big and 0 means small (default). I got so confused in the code that I just changed it a week ago. I don't remember how it was done before for markdown.

* `let g:vimwiki_toc_link_format = 0`
```wiki
= Contents =
  - [[#Foo]]
    - [[#A]]
    - [[#B]]
    - [[#C]]
  - [[#Bar]]
    - [[#X]]
      - [[#Xa]]
      - [[#Xb]]
    - [[#Y]]
      - [[#Ya]]
      - [[#Yb]]

= Foo =
== A ==
== B ==
== C ==

= Bar =
== X ==
=== Xa ===
=== Xb ===
== Y ==
=== Ya ===
=== Yb ===
```


* `let g:vimwiki_toc_link_format = 1`
```wiki
= Contents =
  - [[#Foo|Foo]]
    - [[#Foo#A|A]]
    - [[#Foo#B|B]]
    - [[#Foo#C|C]]
  - [[#Bar|Bar]]
    - [[#Bar#X|X]]
      - [[#Bar#X#Xa|Xa]]
      - [[#Bar#X#Xb|Xb]]
    - [[#Bar#Y|Y]]
      - [[#Bar#Y#Ya|Ya]]
      - [[#Bar#Y#Yb|Yb]]

= Foo =
== A ==
== B ==
== C ==

= Bar =
== X ==
=== Xa ===
=== Xb ===
== Y ==
=== Ya ===
=== Yb ===
```

### Changes

The changes are very small: Just:
1. Return from normalize and unormalize if not markdown
2. Fix this regex for to detect markdown SetExt header `\s\{0,3}[=-][=-]\+$'` -> `^\s\{0,3}[=-][=-]\+\s*$'` : I forgot the `^` begin of line

```
A setext heading underline is a sequence of = characters or a sequence of - characters, with no more than 3 spaces indentation and any number of trailing spaces.
```


PS: The test failed for vim7.4 so I just deleted it. trust me it works

```vim
Given (Spaces {{{2):
  [[#h1 h2 h3 h4]]

  = h1 h2 h3 h4 =

Execute (Set syntax default):
  file wiki_test.wiki
  call SetSyntax('default')

Do (follow spaces):
  gg\<Cr>A __HERE__

Expect (followed spaces):
  [[#h1 h2 h3 h4]]

  = h1 h2 h3 h4 = __HERE__

Given (Toc bad char {{{2):
  [[#h!@$%^&()]]

  = h!@$%^&() =

Execute (Set syntax default):
  file wiki_test.wiki
  call SetSyntax('default')

Do (follow spaces):
  gg\<Cr>A __HERE__

Expect (followed bad char):
  [[#h!@$%^&()]]

  = h!@$%^&() = __HERE__

```

**Comment by uolot** [comment]
> My bad, with `vimwiki#base#nomalize` : I'll fix that in the next 2 days
Thanks for fixing it, that was quick! I'll test it out and let you know whether it works ok

> ```
> let g:vimwiki_emoji_enable = 0
> ```
> 
> Have a look a `:h ki-em` or longer `:h vimwiki-emoji.txt`
The thing is I don't want emoji in my vim, so I turned it off :) It's a nice feature anyways and I'm sure many users love it, but I'm just not one them.
 
> ```
> nnoremap <Leader>wf :Files ~/.vimwiki/<CR>
> ```
> 
> Do you use that more than `nnoremap <Leader>wg :VimwikiGoto` ?
Yes, I use it all the time due to fuzzy searching.

> Very nice vimrc, we should add some of this to doc for new users
Thanks! Feel free to check the rest of my vim config: https://github.com/uolot/dotfiles/tree/master/vim

**Comment by uolot** [comment]
I've tested on default syntax and I confirm the bug is gone :+1: Thanks again!
