### ISSUE TITLE
<Plug>VimwikiFollowLink does not follow links 

### ISSUE THREAD

**Issue by 1xch** [vimwiki/vimwiki#987]
Prior to submitting a new issue make sure to complete these steps:

- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
syntax: markdown

settings
```
let g:vimwiki_list = [
   \{},
   \{'path':'~/.wiki/test','syntax':'markdown','ext':'.md'},
   \]
nmap <Leader><CR> <Plug>VimwikiFollowLink
```
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.

create link (visual text, press z, in vim-zettel)
press <Leader><CR> on link
unable to go to link

I can't follow links with the default mapping either 

- [x] Include the output of `:VimwikiShowVersion`.
    NVIM v0.4.3
    Stable version: 2.5

I can't follow links of markdown type

 ```[test](1597709776-test)```

with default or remapped 

I had some difficulty with vim-zettel earlier so maybe its conflicted there for some reason, but I do not know vim script well or at all really.

The following do nothing for me as default or remapped:
```<Enter> -- Follow/Create wiki link.
<Shift-Enter> -- Split and follow/create wiki link.
<Ctrl-Enter> -- Vertical split and follow/create wiki link.
<Backspace> -- Go back to parent(previous) wiki link.
<Tab> -- Find next wiki link.
<Shift-Tab> -- Find previous wiki link.```

**Comment by tinmarino** [comment]
Remove the backslash ?
```markdown
[test]\(1597709776-test)  -> [test](1597709776-test)
```

**Comment by 1xch** [comment]
@tinmarino 
I just put that here to prevent the link from being rendered by github markdown

there is no slash in the links I am attempting to traverse

**Comment by 1xch** [comment]
Perhaps this is related to #924

**Comment by 1xch** [comment]
I did attempt that once, but I must not have fully recached, because I attempted it again, checking that I recached and that appears to be it. Links are opening with vim-zettel disabled, so thats that for now.
