### ISSUE TITLE
vimwiki_< CR > mapping should ignore syntax elements

### ISSUE THREAD

**Issue by linuxcaffe** [vimwiki/vimwiki#99]
In normal mode, the mapping for < CR > will follow/create wiki link (creating target wiki page if needed.
This is good..
unless the cursor is over a bullet-point (*), a todo checkbox ([ ]), a heading-marker (=) or table-separator (|) or other character used in the syntax, that is not "a word". In those cases, turning those characters into links is nonsensical. In those cases (ond others like them) < CR > should NOT create a link. Perhaps that behavior should be reserved for a "word" or character that is not recognized as part of the markup.

**Comment by EinfachToll** [comment]
Agreed, the current behaviour is sometimes annoying.

**Comment by EinfachToll** [comment]
I've added more characters to the respective regexp. I've decided (rather arbitrarily), that the allowed characters are Ascii alphanumeric characters plus #|./@-_~ plus all non-Ascii characters.
