### ISSUE TITLE
Indentation broken within lists

### ISSUE THREAD

**Issue by ranebrown** [vimwiki/vimwiki#991]
@tinmarino it looks like commit 21c5a7f796a96fd05e06a8c3015cbc6d07e9409c broke the correct indentation within lists. It also disables the correct insertion of a new list character when pressing enter using `:inoremap <silent><buffer> <CR> <C-]><Esc>:VimwikiReturn 3 5<CR>`. 

Expected:
```
- one two three four five six seven eight nine ten eleven twelve thirteen
  fourteen fifteen <-- press <CR> here should result in new marker
- 
```

Actual:
```
- one two three four five six seven eight nine ten eleven twelve thirteen
fourteen fifteen <-- <CR> here no new marker

```

Minimal vimrc:
```vim
set nocompatible
filetype plugin on
syntax on
set runtimepath+=~/vimwiki_dev

set textwidth=80
set linebreak
if has('patch-7.4.338')
  set breakindent
endif

augroup VimwikiKeyMap
    autocmd!
    autocmd FileType vimwiki inoremap <silent><buffer> <CR>
                \ <C-]><Esc>:VimwikiReturn 3 5<CR>
augroup END


let g:vimwiki_list = [
    \    {
    \      'path': '~/testwiki',
    \      'syntax': 'markdown',
    \      'ext': '.md',
    \    },]
```

**Comment by tinmarino** [comment]
@ranebrown thanks for your encouragement. Glad to know I am on the good way. I, on the contrary, had a bit of time with everything going on.
Don't hesitate to open issue and assign them to me (anyway I can unassign if I don't feel): the github interface helps me to sort out the next issue I should track.
See you.
