### ISSUE TITLE
:Vimwiki2HTMLBrowse broken when using a custom converter

### ISSUE THREAD

**Issue by ranebrown** [vimwiki/vimwiki#992]
A recent change broke `:Vimwiki2HTMLBrowse` when using a custom converter. This occurs because of [this line](https://github.com/vimwiki/vimwiki/blob/dev/autoload/vimwiki/html.vim#L1798) which doesn't return the correct path to the html page. Should return `path_html.htmlfile` like the standard converter.

**Comment by sdondley** [comment]
This appears to still be broken when working with a file in a subdirectory of the wiki.

**Comment by sdondley** [comment]
This seems to still be broken. I'm doing :Vimwiki2HTMLBrowse on a file called `Raku Programming Language.md` and the page is not opening up in a browser. It's working fine for other pages. Maybe the spaces in the name are causing problems?

**Comment by sdondley** [comment]
OK, yeah. Fixed by adding `'links_space_char': '-'` to `vimwiki_list` and renaming files by replacing spaces in file names with dashes.

This may only be a problem for people like me using the `vimwiki_markdown` ruby gem. Not sure.
