### ISSUE TITLE
`vimwiki#base#linkify()` ignores markdown syntax setting

### ISSUE THREAD

**Issue by beuerle** [vimwiki/vimwiki#994]
Calling the new `vimwiki#base#linkify()` function ignores the `markdown` syntax setting and always creates a `vimwiki` syntax link.

Calling the function for example with `https://github.com/vimwiki/vimwiki` under the cursor gives:

```
[[https://github.com/vimwiki/vimwiki|GitHub - vimwiki/vimwiki: Personal Wiki for Vim]]
```
config:

```vim
let g:vimwiki_list = [
	\ {'path':				'~/vimwiki/',
	\  'syntax':				'markdown',
	\  'ext':				'.md',
	\  'index':				'README'
	\},
[..]
```

**Comment by tinmarino** [comment]
Fixed by last commit
