### ISSUE TITLE
Duplicate help tags

### ISSUE THREAD

**Issue by ebassett** [vimwiki/vimwiki#999]
Prior to submitting a new issue make sure to complete these steps:

- [X] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [N/A] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.
    `:helptags $HOME/.vim[/bundle]/vimwiki/doc` =>
      E154: Duplicate tag "vimwiki-global-options" in file [...]/vimwiki/doc/vimwiki.txt
- [X] Include the output of `:VimwikiShowVersion`.
    Os: Linux
    Vim: 802
    Branch: dev
    Revision: dc63a5d
    Date: 2020-08-24 01:14:18 -0400

I use vundle as my plugin manager, and it automatically runs `:helptags` after every installation/update of plugins, which is currently failing on vimwiki due to a duplicate tag: evidentally, the tag "vimwiki-syntax-options" was inadvertantly set to "vimwiki-global-options", which is actually the (correct) tag of the next section of the help file.

NOTE:
I have a Pull Request ready for fixing this error, and will submit it as soon as I have submitted this Issue and so have an Issue Number to attach to the Pull Request.

**Comment by tinmarino** [comment]
Fixed in #1000 by same author.

Thanks.
